 /*FLEXMITT.P*/
DEFINE VARIABLE nyaprog AS LOGICAL NO-UNDO. 
/*START PROG FÖR FLEX TERM
 1. ÄNDRA I WC-CECK
 2. SKAPA ETT LIKA PROG SOM DETTA
 3. LÄGG UPPEN ANVÄNDARE FLEX FLEX MED BEHÖRIGHET ENDAST FLEX.
 4.  Guru.Konstanter:appfel = TRUE + GLOBANV FLEX STYR OM FLEXS SKA STARTAS AUTO.
*/
&Scoped-define NEW NEW 
{APPCONDEF.I}
{VALDBDEF.I}
/*obs BARA DESSA 3 RADER BEHÖVS BYTAS*/

{VALDBMISV.I}
FIND FIRST valdbtemp WHERE valdbtemp.DBNAMN = "misv" NO-ERROR.
IF NOT AVAILABLE valdbtemp THEN RETURN.
{FLEXSTART.I}
