
DEFINE VARIABLE aonrvar AS CHARACTER NO-UNDO.
DEFINE VARIABLE delnrvar AS INTEGER NO-UNDO.

REPEAT:
   UPDATE aonrvar delnrvar WITH FRAME cc.
   IF aonrvar = "x" THEN LEAVE.
   
   OPEN QUERY atq FOR EACH AONRTAB WHERE AONRTAB.AONR = aonrvar
   NO-LOCK.
   GET FIRST atq NO-LOCK.
   DO WHILE AVAILABLE(AONRTAB):
      DO TRANSACTION:
         GET CURRENT atq EXCLUSIVE-LOCK.
         ASSIGN 
         AONRTAB.OMRADE = "76".
      END.
      OPEN QUERY aq FOR EACH AONRKONTKOD WHERE 
      AONRKONTKOD.AONR = AONRTAB.AONR  AND AONRKONTKOD.DELNR = AONRTAB.DELNR
      NO-LOCK.
      GET FIRST aq NO-LOCK.
      DO WHILE AVAILABLE(AONRKONTKOD):
         DO TRANSACTION:
            GET CURRENT aq EXCLUSIVE-LOCK.
            ASSIGN 
            AONRKONTKOD.K1 = "076".
         END.
         GET NEXT aq NO-LOCK.
      END.
      MESSAGE AONRTAB.AONR AONRTAB.DELNR OMRADE.
      GET NEXT atq NO-LOCK.
   END.
  
END.
