/* lt-06-03.p */
DEFINE INPUT PARAMETER Paris AS CHARACTER FORMAT "x(20)".
DEFINE BUTTON BTN-EXIT LABEL "Exit".

DEFINE FRAME frame1 
   SKIP(1)
   Paris SKIP(1)
   BTN-EXIT
      WITH SIDE-LABELS NO-BOX CENTERED THREE-D.

DISPLAY Paris WITH FRAME frame1.
ENABLE ALL WITH FRAME frame1.

WAIT-FOR CHOOSE OF BTN-EXIT.
