/* lt-03-04.p */
DEFINE VARIABLE Field1 AS CHARACTER INITIAL "Hello!" VIEW-AS TEXT.
DEFINE BUTTON BTN-EXIT LABEL "Exit".
DEFINE BUTTON BTN-DATA LABEL "Display Data".

ENABLE SKIP(2) BTN-DATA SKIP(2) BTN-EXIT SKIP(2)
   WITH SIDE-LABELS CENTERED NO-BOX THREE-D.

ON CHOOSE OF BTN-DATA 
DO:
   DISPLAY Field1.
END.

WAIT-FOR CHOOSE OF BTN-EXIT.
