/* lt-03-03.p */
DEFINE VARIABLE Field1 AS CHARACTER INITIAL "Hello!" VIEW-AS TEXT.

DISPLAY SKIP(3) Field1 VIEW-AS FILL-IN
   WITH SIDE-LABELS CENTERED NO-BOX THREE-D.

ENABLE Field1.

WAIT-FOR RETURN OF Field1.
