/* lt-03-06.p */
DEFINE BUTTON BTN-EXIT LABEL "Exit".
DEFINE FRAME parent1 WITH TITLE "Parent1" SIZE 40 BY 10
   AT ROW 3 COLUMN 3.
DEFINE FRAME child1 BTN-EXIT WITH TITLE "Child1" SIZE 20 BY 5
   AT ROW 3 COLUMN 3.

FRAME child1:FRAME = FRAME parent1:HANDLE.

DISPLAY WITH FRAME parent1.
ENABLE ALL WITH FRAME parent1.
ENABLE ALL WITH FRAME child1.

WAIT-FOR CHOOSE OF BTN-EXIT.
