/* lt-03-01.p */
DEFINE VARIABLE field1 AS CHARACTER INITIAL "Hello".
DEFINE VARIABLE field2 AS CHARACTER INITIAL "Progress".
DEFINE VARIABLE field3 AS CHARACTER INITIAL "World!".

DISPLAY SKIP(1) field1 SKIP(1) field2 SKIP(1) field3
   WITH SIDE-LABELS CENTERED NO-BOX.
/*DISPLAY SKIP(3) field1 SKIP(2) field2 SKIP(2) field3
   WITH SIDE-LABELS CENTERED NO-BOX. */

ENABLE field1 field2 field3.

WAIT-FOR RETURN OF field3.
