/*BORTFAK.P*/
/*bortagning av plan*/
DEFINE INPUT PARAMETER infakplannr AS INTEGER NO-UNDO.
DEFINE VARIABLE faktrec AS RECID NO-UNDO.
FIND FIRST FAKTPLAN WHERE FAKTPLAN.FAKTNR = infakplannr NO-LOCK NO-ERROR.
IF NOT AVAILABLE FAKTPLAN THEN RETURN.
faktrec = RECID(FAKTPLAN). 
IF AVAILABLE FAKTPLAN THEN DO:                   
   OPEN QUERY faktbefq
   FOR EACH FAKTBEF WHERE FAKTBEF.FAKTNR = FAKTPLAN.FAKTNR 
   USE-INDEX FAKTBEF NO-LOCK.         
   DO TRANSACTION:       
      GET FIRST faktbefq EXCLUSIVE-LOCK.
      IF AVAILABLE FAKTBEF THEN DELETE FAKTBEF.    
   END.
   REPEAT:  
      DO TRANSACTION:
         GET NEXT faktbefq EXCLUSIVE-LOCK.
         IF AVAILABLE FAKTBEF THEN DELETE FAKTBEF.    
         ELSE LEAVE.      
      END.         
   END.     
   CLOSE QUERY faktbefq. 
   OPEN QUERY faktreglq
   FOR EACH FAKTREGLER WHERE FAKTREGLER.FAKTNR = FAKTPLAN.FAKTNR 
   USE-INDEX FAKTREGLER NO-LOCK.         
   DO TRANSACTION:       
      GET FIRST faktreglq EXCLUSIVE-LOCK.
      IF AVAILABLE FAKTREGLER THEN DELETE FAKTREGLER.    
   END.
   REPEAT:  
      DO TRANSACTION:
         GET NEXT faktreglq EXCLUSIVE-LOCK.
         IF AVAILABLE FAKTREGLER THEN DELETE FAKTREGLER.    
         ELSE LEAVE.      
      END.         
   END.   
   CLOSE QUERY faktreglq.
   OPEN QUERY faktoverq
   FOR EACH FAKTOVER WHERE FAKTOVER.FAKTNR = FAKTPLAN.FAKTNR 
   USE-INDEX FAKTOVER NO-LOCK.                 
   DO TRANSACTION:       
      GET FIRST faktoverq EXCLUSIVE-LOCK.
      IF AVAILABLE FAKTOVER THEN DELETE FAKTOVER.    
   END.
   REPEAT:  
      DO TRANSACTION:
         GET NEXT faktoverq EXCLUSIVE-LOCK.
         IF AVAILABLE FAKTOVER THEN DELETE FAKTOVER.    
         ELSE LEAVE.      
      END.         
   END.
   CLOSE QUERY faktoverq. 
   OPEN QUERY faktaonrq
   FOR EACH FAKTAONR WHERE FAKTAONR.FAKTNR = FAKTPLAN.FAKTNR 
   USE-INDEX FAKTA NO-LOCK.   
   DO TRANSACTION:
      GET FIRST faktaonrq EXCLUSIVE-LOCK.
      DO WHILE AVAILABLE(FAKTAONR):            
         DELETE FAKTAONR.         
         GET NEXT faktaonrq EXCLUSIVE-LOCK.
      END.   
   END.
   CLOSE QUERY faktaonrq.    
   OPEN QUERY faktkollq
   FOR EACH FAKTKOLL WHERE FAKTKOLL.FAKTNR = FAKTPLAN.FAKTNR 
   USE-INDEX FAKTNR NO-LOCK.
   DO TRANSACTION:
      GET FIRST faktkollq EXCLUSIVE-LOCK.
      DO WHILE AVAILABLE(FAKTKOLL):            
         DELETE FAKTKOLL.         
         GET NEXT faktkollq EXCLUSIVE-LOCK.
      END.   
   END.
   CLOSE QUERY faktkollq.                
   OPEN QUERY aonrq FOR EACH AONRTAB WHERE 
   AONRTAB.FAKTNR = FAKTPLAN.FAKTNR 
   USE-INDEX FAKTNR NO-LOCK. 
   DO TRANSACTION:
      GET FIRST aonrq EXCLUSIVE-LOCK.
      DO WHILE AVAILABLE(AONRTAB):
         ASSIGN AONRTAB.FAKTNR = 0.         
         GET NEXT aonrq EXCLUSIVE-LOCK.
      END.   
   END.
   CLOSE QUERY aonrq.                                                   
   DO TRANSACTION:            
      OPEN QUERY fnamnq FOR EACH FAKTNAMN WHERE FAKTNAMN.FAKTURNR = FAKTPLAN.FAKTNR  
      NO-LOCK.
      GET FIRST fnamnq EXCLUSIVE-LOCK.
      DO WHILE AVAILABLE(FAKTNAMN):
         DELETE FAKTNAMN. 
         GET NEXT fnamnq EXCLUSIVE-LOCK.
      END. 
   END.   
   DO TRANSACTION:         
      OPEN QUERY faktstartq
      FOR EACH FAKTSTART WHERE FAKTSTART.FAKTNR = FAKTPLAN.FAKTNR NO-LOCK.        
      GET FIRST faktstartq EXCLUSIVE-LOCK.
      DO WHILE AVAILABLE(FAKTSTART):            
         DELETE FAKTSTART.         
         GET NEXT faktstartq EXCLUSIVE-LOCK.
      END.   
   END.
   OPEN QUERY faktuppplanq
   FOR EACH FAKTUPPPLAN WHERE FAKTUPPPLAN.FAKTNR = FAKTPLAN.FAKTNR NO-LOCK.        
   DO TRANSACTION:
      GET FIRST faktuppplanq EXCLUSIVE-LOCK.
      DO WHILE AVAILABLE(FAKTUPPPLAN):            
         DELETE FAKTUPPPLAN.         
         GET NEXT faktuppplanq EXCLUSIVE-LOCK.
      END.         
   END.
   OPEN QUERY faktupparbq
   FOR EACH FAKTUPPARB WHERE FAKTUPPARB.FAKTNR = FAKTPLAN.FAKTNR NO-LOCK.        
   DO TRANSACTION:
      GET FIRST faktupparbq EXCLUSIVE-LOCK.
      DO WHILE AVAILABLE(FAKTUPPARB):            
         DELETE FAKTUPPARB.         
         GET NEXT faktupparbq EXCLUSIVE-LOCK.
      END.         
   END.
   DO TRANSACTION:         
      OPEN QUERY faktavq
      FOR EACH FAKTAVTALAONR WHERE FAKTAVTALAONR.FAKTNR = FAKTPLAN.FAKTNR NO-LOCK.        
      GET FIRST faktstartq EXCLUSIVE-LOCK.
      DO WHILE AVAILABLE(FAKTAVTALAONR):            
         DELETE FAKTAVTALAONR.         
         GET NEXT faktavq EXCLUSIVE-LOCK.
      END.   
   END.
   FOR EACH FAKTPRISLISTA WHERE FAKTPRISLISTA.FAKTNR = FAKTPLAN.FAKTNR:
      DELETE FAKTPRISLISTA.
   END.
   DO TRANSACTION:                        
      FIND FAKTPLAN WHERE RECID(FAKTPLAN) = faktrec EXCLUSIVE-LOCK NO-ERROR.   
      DELETE FAKTPLAN.             
   END.
END.   
