/*FAAOOPEN.P*/
/* {AONRTEMP.I} */
&Scoped-define NEW NEW
&Scoped-define SHARED SHARED
&Scoped-define NEW NEW
{GLOBVAR2DEL1.I}

{AONRDEF.I}
DEFINE INPUT PARAMETER Cglobanv AS CHARACTER NO-UNDO. 
DEFINE INPUT PARAMETER Cglobniv LIKE ANVANDARE.AV-LEVEL NO-UNDO. 
DEFINE INPUT PARAMETER Cglobforetag LIKE FORETAG.FORETAG NO-UNDO.
DEFINE INPUT PARAMETER bnr LIKE BESTTAB.BESTID NO-UNDO.
DEFINE INPUT PARAMETER CMB_FAK AS CHARACTER NO-UNDO.
DEFINE INPUT PARAMETER FILL-IN_ANVANDARE LIKE ANVANDARE.ANVANDARE NO-UNDO.
DEFINE INPUT PARAMETER arbartvar AS INTEGER NO-UNDO.
DEFINE INPUT  PARAMETER fakntnrvar AS INTEGER NO-UNDO.
DEFINE INPUT-OUTPUT PARAMETER TABLE FOR aonrtemp.
DEFINE OUTPUT PARAMETER musz AS LOGICAL NO-UNDO.
DEFINE VARIABLE allvar AS LOGICAL NO-UNDO.
DEFINE VARIABLE kundtypidvar AS INTEGER NO-UNDO.


RUN STYRFORE.P (INPUT Guru.Konstanter:globforetag).
/*CMB_FAK OK SKICKAR EJ VISA FATYP UTAN BARA FAKTYP*/
FIND FIRST FAKTURADM NO-LOCK NO-ERROR.       
IF FAKTURADM.ANVANDARE = Guru.Konstanter:globanv THEN allvar = TRUE.
IF CMB_FAK = "Fri fakturering" OR CMB_FAK = "Bokföring" THEN DO:   
   IF Guru.Konstanter:globniv = 0 OR allvar = TRUE THEN DO:   
      IF arbartvar = 0 THEN DO:
         OPEN QUERY aonrq FOR EACH AONRTAB         
         USE-INDEX FAKTNR NO-LOCK.              
      END.
      ELSE DO:
         OPEN QUERY aonrq FOR EACH AONRTAB WHERE AONRTAB.ARBARTKOD = arbartvar        
         USE-INDEX FAKTNR NO-LOCK.                 
      END.     
   END.
   ELSE DO:   
      IF arbartvar = 0 THEN DO:
         OPEN QUERY aonrq FOR EACH AONRTAB WHERE  
         AONRTAB.ANVANDARE = FILL-IN_ANVANDARE         
         USE-INDEX FAKTNR NO-LOCK.     
      END.
      ELSE DO:
         OPEN QUERY aonrq FOR EACH AONRTAB WHERE  
         AONRTAB.ANVANDARE = FILL-IN_ANVANDARE AND AONRTAB.ARBARTKOD = arbartvar
         USE-INDEX FAKTNR NO-LOCK.     
      END.
   END.
END.
ELSE DO:
   FIND FIRST FAKTREGLER WHERE FAKTREGLER.FAKTNR = fakntnrvar NO-LOCK NO-ERROR.
   IF AVAILABLE FAKTREGLER THEN DO:
      kundtypidvar = FAKTREGLER.KUNDID.
   END.   
   IF Guru.Konstanter:globniv = 0 OR allvar = TRUE THEN DO:
      IF kundtypidvar = 3 THEN DO:
         OPEN QUERY aonrq FOR EACH AONRTAB WHERE        
         AONRTAB.FAKTTYP = CMB_FAK AND 
         AONRTAB.AONRAVDATUM = 01/01/91 USE-INDEX FAKTNR NO-LOCK.
      END.      
      ELSE IF arbartvar = 0 THEN DO:
         OPEN QUERY aonrq FOR EACH AONRTAB WHERE        
         AONRTAB.BESTID = bnr AND AONRTAB.FAKTTYP = CMB_FAK AND 
         AONRTAB.FAKTNR = 0 USE-INDEX FAKTNR NO-LOCK.     
      END.
      ELSE DO:
         OPEN QUERY aonrq FOR EACH AONRTAB WHERE        
         AONRTAB.BESTID = bnr AND AONRTAB.FAKTTYP = CMB_FAK AND 
         AONRTAB.FAKTNR = 0 AND AONRTAB.ARBARTKOD = arbartvar USE-INDEX FAKTNR NO-LOCK.     
      END.

   END.
   ELSE DO:
      IF kundtypidvar = 3 THEN DO:
         OPEN QUERY aonrq FOR EACH AONRTAB WHERE  
         AONRTAB.ANVANDARE = FILL-IN_ANVANDARE AND      
         AONRTAB.FAKTTYP = CMB_FAK AND 
         AONRTAB.AONRAVDATUM = 01/01/91 USE-INDEX FAKTNR NO-LOCK.
      END.   
      ELSE IF arbartvar = 0 THEN DO:
         OPEN QUERY aonrq FOR EACH AONRTAB WHERE  
         AONRTAB.ANVANDARE = FILL-IN_ANVANDARE AND
         AONRTAB.BESTID = bnr AND AONRTAB.FAKTTYP = CMB_FAK AND 
         AONRTAB.FAKTNR = 0 USE-INDEX FAKTNR NO-LOCK.     
      END.
      ELSE DO:
         OPEN QUERY aonrq FOR EACH AONRTAB WHERE  
         AONRTAB.ANVANDARE = FILL-IN_ANVANDARE AND
         AONRTAB.BESTID = bnr AND AONRTAB.FAKTTYP = CMB_FAK AND 
         AONRTAB.FAKTNR = 0 AND AONRTAB.ARBARTKOD = arbartvar USE-INDEX FAKTNR NO-LOCK.     
      END.
   END.
END.    
GET FIRST aonrq NO-LOCK.
musz = TRUE.
DO WHILE AVAILABLE(AONRTAB) TRANSACTION:
   
   musz = FALSE.  
   
   IF kundtypidvar = 3 THEN RUN aonrfplankoll_UI.    
   IF Guru.Konstanter:globforetag = "XNORD" THEN DO: /*991019*/
      IF AONRTAB.AONRAVDATUM NE 01/01/91 THEN musz = TRUE.
   END.
   IF Guru.Konstanter:varforetypval[9] = 1 THEN DO:
      IF AONRTAB.DELNR NE 0 THEN  musz = TRUE.
   END.
   IF musz = FALSE THEN DO:
      FIND FIRST aonrtemp WHERE aonrtemp.AONR = AONRTAB.AONR AND
      aonrtemp.DELNR = AONRTAB.DELNR USE-INDEX AONR NO-ERROR.
      IF NOT AVAILABLE aonrtemp THEN CREATE aonrtemp.
      ASSIGN 
      aonrtemp.AONR = AONRTAB.AONR
      aonrtemp.DELNR = AONRTAB.DELNR
      aonrtemp.ORT = AONRTAB.ORT
      aonrtemp.OMRADE = AONRTAB.OMRADE
      aonrtemp.AONRAVDATUM = AONRTAB.AONRAVDATUM
      aonrtemp.STARTDATUM = AONRTAB.STARTDATUM
      aonrtemp.ELVOMRKOD = AONRTAB.ELVOMRKOD
      aonrtemp.PLANOFFERT = AONRTAB.BETNR.
   END.
   musz = FALSE.
   GET NEXT aonrq NO-LOCK.                  
END.
CLOSE QUERY aonrq.

PROCEDURE aonrfplankoll_UI :
   
   FOR EACH FAKTKOLL WHERE FAKTKOLL.AONR = AONRTAB.AONR AND FAKTKOLL.DELNR = AONRTAB.DELNR NO-LOCK:
      IF FAKTKOLL.SLUTFAKT = FALSE THEN DO:
         musz = TRUE.
         RETURN.
      END.          
   END.
   
END PROCEDURE.