/*FAKOSAPP.P*/
&Scoped-define NEW NEW                          
{FAKTTEMP.I}
DEFINE INPUT PARAMETER fnr LIKE FAKTPLAN.FAKTNR NO-UNDO.
DEFINE INPUT PARAMETER fdelnrvar              AS INTEGER NO-UNDO.
DEFINE INPUT PARAMETER aonrvar AS CHARACTER NO-UNDO.
DEFINE INPUT PARAMETER delnrvar AS INTEGER NO-UNDO.
DEFINE INPUT PARAMETER FILL-IN-TOMDAT AS DATE NO-UNDO.
DEFINE INPUT-OUTPUT PARAMETER FILL-IN_INKOMST AS DECIMAL NO-UNDO.
DEFINE INPUT-OUTPUT PARAMETER TABLE FOR kosttemp.   
{FAKOSAPP.I}
