/*FAKTKOLL.P*/
DEFINE VARIABLE vpers AS CHARACTER NO-UNDO.
OPEN QUERY fpq FOR EACH FAKTPLAN WHERE FAKTPLAN.SLUTFAKT = FALSE AND 
FAKTPLAN.FAKTTYP = "Löpande utan", 
EACH FAKTAONR WHERE FAKTAONR.FAKTNR = FAKTPLAN.FAKTNR NO-LOCK. 
GET FIRST fpq NO-LOCK.
DO WHILE AVAILABLE(FAKTPLAN): 
   REPEAT:
      FIND FIRST SUMTIDDAG WHERE SUMTIDDAG.AONR = FAKTAONR.AONR AND SUMTIDDAG.DELNR = FAKTAONR.DELNR AND
      SUMTIDDAG.PERSONALKOD > vpers NO-LOCK NO-ERROR.
      IF AVAILABLE SUMTIDDAG THEN DO:
         vpers = SUMTIDDAG.PERSONALKOD.
         FIND FIRST FAKTKOLL WHERE FAKTKOLL.FAKTNR = FAKTPLAN.FAKTNR AND
         FAKTKOLL.AONR = FAKTAONR.AONR AND FAKTKOLL.DELNR = FAKTAONR.DELNR AND
         FAKTKOLL.BESTID = vpers NO-LOCK NO-ERROR.
         IF NOT AVAILABLE FAKTKOLL THEN DO:
            CREATE FAKTKOLL.
            ASSIGN
            FAKTKOLL.FAKTNR = FAKTPLAN.FAKTNR
            FAKTKOLL.BESTID = vpers
            FAKTKOLL.AONR   = FAKTAONR.AONR
            FAKTKOLL.DELNR  = FAKTAONR.DELNR
            FAKTKOLL.VECKOKORD = "UTAN@".
         END.
      END.
      ELSE DO:
         vpers = "".
         LEAVE.
      END.
   END.
   GET NEXT fpq NO-LOCK.
END.
 
