/*FAKTUPPHMT.P*/

&Scoped-define NEW NEW
&Scoped-define SHARED SHARED
{FAKKOTEMP.I}
{GLOBVAR2DEL1.I}

{NAMNDB.I}
DEFINE VARIABLE edataapph AS HANDLE NO-UNDO.
DEFINE VARIABLE fbestapph AS HANDLE NO-UNDO.
DEFINE VARIABLE musz AS LOGICAL NO-UNDO.
DEFINE BUFFER aobuff FOR AONRTAB.
DEFINE BUFFER faktplanbuff FOR FAKTPLAN.
DEFINE BUFFER faktkollbuff FOR FAKTKOLL.
DEFINE BUFFER exkoppbuff FOR EXTRAKOPPLINGAR.
FIND FIRST FORETAG NO-LOCK NO-ERROR.
FIND FIRST FAKTURADM NO-LOCK NO-ERROR.
Guru.Konstanter:globforetag = FORETAG.FORETAG.

RUN STYRFORE.P (INPUT Guru.Konstanter:globforetag).
&Scoped-define NEW NEW
{ORGPRIS.I}
{SOKDEF.I}
{OMRTEMPW.I}
{FAKTTEMP.I}
{FAKTPLANTEMP.I}                 
{FAKTTYPDEF.I}
{FAKTTYPSKAP.I}
{EXTRATAB.I}  
{FAKTSTART.I}
{DYNHMT.I}
{EXTRADATA.I}

{VISKONTAB.I}
{SMTPDEF3.I}
DEFINE VARIABLE servervar AS CHARACTER LABEL "Smtp Server" NO-UNDO.
DEFINE VARIABLE tillvar   AS CHARACTER LABEL "To" NO-UNDO.

DEFINE BUFFER faktureradbuff FOR FAKTURERAD.
DEFINE BUFFER faktkundkontobuff FOR FAKTKUNDKONTO.
DEFINE BUFFER faktintaktkontbuff FOR FAKTINTAKTKONT.
DEFINE BUFFER faktmomsbuff FOR FAKTMOMS.


PROCEDURE viskont_UI:
   DEFINE INPUT PARAMETER infakplannr  AS INTEGER NO-UNDO.
   DEFINE INPUT PARAMETER fdelnrvar   AS INTEGER NO-UNDO.
   DEFINE OUTPUT PARAMETER TABLE FOR viskonttemp.
   EMPTY TEMP-TABLE viskonttemp NO-ERROR.
   EMPTY TEMP-TABLE vismomstemp NO-ERROR.
   FIND FIRST FAKTPLAN WHERE FAKTPLAN.FAKTNR = infakplannr NO-LOCK NO-ERROR.
   FIND FIRST FAKTURERAD WHERE FAKTURERAD.FAKTNR = infakplannr AND FAKTURERAD.FDELNR = fdelnrvar
   NO-LOCK NO-ERROR.
   FIND FIRST FAKTURERINGSTYP WHERE 
   FAKTURERINGSTYP.FAKTTYPID = FAKTURERAD.FAKTTYPID NO-LOCK NO-ERROR.      
   
   OPEN QUERY BRW_K1 FOR EACH FAKTKUNDKONTO WHERE 
   FAKTKUNDKONTO.FAKTNR = infakplannr AND 
   FAKTKUNDKONTO.FDELNR = fdelnrvar NO-LOCK, 
   EACH KUNDFODRAN WHERE KUNDFODRAN.KUNDKONTOID = FAKTKUNDKONTO.KUNDKONTOID NO-LOCK, 
   EACH MOTPART WHERE MOTPART.MOTPARTID = FAKTKUNDKONTO.MOTPARTID NO-LOCK.
   
   OPEN QUERY BRW_K2 FOR EACH FAKTINTAKTKONT WHERE 
   FAKTINTAKTKONT.FAKTNR = infakplannr AND 
   FAKTINTAKTKONT.FDELNR = fdelnrvar NO-LOCK, 
   EACH INTAKTTAB WHERE INTAKTTAB.INTAKTID = FAKTINTAKTKONT.INTAKTID NO-LOCK, 
   EACH MOTPART WHERE MOTPART.MOTPARTID = FAKTINTAKTKONT.MOTPARTID NO-LOCK.
   
   OPEN QUERY BRW_K4 FOR EACH FAKTMOMS WHERE 
   FAKTMOMS.FAKTNR = infakplannr AND 
   FAKTMOMS.FDELNR = fdelnrvar NO-LOCK, 
   EACH MOMSTAB WHERE MOMSTAB.MOMSID = FAKTMOMS.MOMSID NO-LOCK.      
   {VISKONT.I}    
END PROCEDURE.
PROCEDURE viskontk_UI:
   DEFINE INPUT PARAMETER infakplannr  AS INTEGER NO-UNDO.
   DEFINE INPUT PARAMETER fdelnrvar   AS INTEGER NO-UNDO.
   DEFINE OUTPUT PARAMETER TABLE FOR viskonttemp.
   EMPTY TEMP-TABLE viskonttemp NO-ERROR.
   EMPTY TEMP-TABLE vismomstemp NO-ERROR.
   FIND FIRST FAKTPLAN WHERE FAKTPLAN.FAKTNR = infakplannr NO-LOCK NO-ERROR.
   FIND FIRST FAKTKRED WHERE FAKTKRED.FAKTNR = infakplannr AND FAKTKRED.FDELNR = fdelnrvar
   NO-LOCK NO-ERROR.
   FIND FIRST FAKTURERINGSTYP WHERE 
   FAKTURERINGSTYP.FAKTTYPID = FAKTKRED.FAKTTYPID NO-LOCK NO-ERROR.      
   
   OPEN QUERY BRW_K1 FOR EACH FAKTKUNDKONTOKRED WHERE 
   FAKTKUNDKONTOKRED.FAKTNR = infakplannr AND 
   FAKTKUNDKONTOKRED.FDELNR = fdelnrvar NO-LOCK, 
   EACH KUNDFODRAN WHERE KUNDFODRAN.KUNDKONTOID = FAKTKUNDKONTOKRED.KUNDKONTOID NO-LOCK, 
   EACH MOTPART WHERE MOTPART.MOTPARTID = FAKTKUNDKONTOKRED.MOTPARTID NO-LOCK.

   OPEN QUERY BRW_K2 FOR EACH FAKTINTAKTKONTKRED WHERE 
   FAKTINTAKTKONTKRED.FAKTNR = infakplannr AND 
   FAKTINTAKTKONTKRED.FDELNR = fdelnrvar NO-LOCK, 
   EACH INTAKTTAB WHERE INTAKTTAB.INTAKTID = FAKTINTAKTKONTKRED.INTAKTID NO-LOCK, 
   EACH MOTPART WHERE MOTPART.MOTPARTID = FAKTINTAKTKONTKRED.MOTPARTID NO-LOCK.

   OPEN QUERY BRW_K4 FOR EACH FAKTMOMSKRED WHERE 
   FAKTMOMSKRED.FAKTNR = infakplannr AND 
   FAKTMOMSKRED.FDELNR = fdelnrvar NO-LOCK, 
   EACH MOMSTAB WHERE MOMSTAB.MOMSID = FAKTMOMSKRED.MOMSID NO-LOCK.      
   {VISKONTK.I}    
END PROCEDURE.
PROCEDURE styrintakt_UI :    
   {STYRDEB.I}   
END PROCEDURE.
PROCEDURE kontonbort_UI:
   DEFINE INPUT PARAMETER vart  AS INTEGER NO-UNDO.
   DEFINE INPUT PARAMETER rowbort AS ROWID NO-UNDO.
   IF vart = 1 THEN DO TRANSACTION:
      FIND FAKTKUNDKONTO WHERE ROWID(FAKTKUNDKONTO) = rowbort EXCLUSIVE-LOCK NO-ERROR.
      DELETE FAKTKUNDKONTO.      
   END.
   ELSE IF vart = 2 THEN DO TRANSACTION:
      FIND FAKTINTAKTKONT WHERE ROWID(FAKTINTAKTKONT) = rowbort EXCLUSIVE-LOCK NO-ERROR.
      DELETE FAKTINTAKTKONT.      
   END.
   IF vart = 4 THEN DO TRANSACTION:
      FIND FAKTMOMS WHERE ROWID(FAKTMOMS) = rowbort EXCLUSIVE-LOCK NO-ERROR.
      DELETE FAKTMOMS.      
   END.
END PROCEDURE.
PROCEDURE kontonbortk_UI:
   DEFINE INPUT PARAMETER vart  AS INTEGER NO-UNDO.
   DEFINE INPUT PARAMETER rowbort AS ROWID NO-UNDO.
   IF vart = 1 THEN DO TRANSACTION:
      FIND FAKTKUNDKONTOKRED WHERE ROWID(FAKTKUNDKONTOKRED) = rowbort EXCLUSIVE-LOCK NO-ERROR.
      DELETE FAKTKUNDKONTOKRED.      
   END.
   ELSE IF vart = 2 THEN DO TRANSACTION:
      FIND FAKTINTAKTKONTKRED WHERE ROWID(FAKTINTAKTKONTKRED) = rowbort EXCLUSIVE-LOCK NO-ERROR.
      DELETE FAKTINTAKTKONTKRED.      
   END.
   IF vart = 4 THEN DO TRANSACTION:
      FIND FAKTMOMSKRED WHERE ROWID(FAKTMOMSKRED) = rowbort EXCLUSIVE-LOCK NO-ERROR.
      DELETE FAKTMOMSKRED.      
   END.
END PROCEDURE.
PROCEDURE kontondela_UI:
   DEFINE INPUT PARAMETER infakplannr  AS INTEGER NO-UNDO.
   DEFINE INPUT PARAMETER fdelnrvar   AS INTEGER NO-UNDO.
   DEFINE INPUT PARAMETER vart  AS INTEGER NO-UNDO.
   DEFINE INPUT PARAMETER TABLE FOR efaktkundtemp.
   DEFINE INPUT PARAMETER TABLE FOR efaktinkontotemp.
   DEFINE INPUT PARAMETER TABLE FOR efaktmomstemp.
   IF vart = 1 THEN DO TRANSACTION:
      FIND FIRST efaktkundtemp NO-LOCK NO-ERROR.
      FIND FAKTKUNDKONTO WHERE ROWID(FAKTKUNDKONTO) = efaktkundtemp.FROW EXCLUSIVE-LOCK NO-ERROR.
      IF NOT AVAILABLE FAKTKUNDKONTO THEN CREATE FAKTKUNDKONTO.
      BUFFER-COPY efaktkundtemp TO FAKTKUNDKONTO.
      FOR EACH FAKTKUNDKONTO WHERE FAKTKUNDKONTO.FAKTNR = infakplannr AND 
      FAKTKUNDKONTO.FDELNR = fdelnrvar EXCLUSIVE-LOCK: 
         ASSIGN
         FAKTKUNDKONTO.FAKTDATUM = efaktkundtemp.FAKTDATUM  
         FAKTKUNDKONTO.FDATUM = efaktkundtemp.FDATUM.        
      END.
   END.
   IF vart = 2 THEN DO TRANSACTION:
      FIND FIRST efaktinkontotemp NO-LOCK NO-ERROR.
      FIND FAKTINTAKTKONT WHERE ROWID(FAKTINTAKTKONT) = efaktinkontotemp.FROW EXCLUSIVE-LOCK NO-ERROR.
      IF NOT AVAILABLE FAKTINTAKTKONT THEN DO:
         CREATE FAKTINTAKTKONT.
      END.
      BUFFER-COPY efaktinkontotemp TO FAKTINTAKTKONT.
      
   END.
   IF vart = 4 THEN DO TRANSACTION:
      FIND FIRST efaktmomstemp NO-LOCK NO-ERROR.
      FIND FAKTMOMS WHERE ROWID(FAKTMOMS) = efaktmomstemp.FROW EXCLUSIVE-LOCK NO-ERROR.
      IF NOT AVAILABLE FAKTMOMS THEN DO:
         CREATE FAKTMOMS.
      END.
      BUFFER-COPY efaktmomstemp TO FAKTMOMS.
   END.
   RELEASE FAKTKUNDKONTO NO-ERROR.
   RELEASE FAKTINTAKTKONT NO-ERROR.
   RELEASE FAKTMOMS NO-ERROR. 
END PROCEDURE.

PROCEDURE kontondelak_UI:
   DEFINE INPUT PARAMETER infakplannr  AS INTEGER NO-UNDO.
   DEFINE INPUT PARAMETER fdelnrvar   AS INTEGER NO-UNDO.
   DEFINE INPUT PARAMETER vart  AS INTEGER NO-UNDO.
   DEFINE INPUT PARAMETER TABLE FOR efaktkundtemp.
   DEFINE INPUT PARAMETER TABLE FOR efaktinkontotemp.
   DEFINE INPUT PARAMETER TABLE FOR efaktmomstemp.
   IF vart = 1 THEN DO TRANSACTION:
      FIND FIRST efaktkundtemp NO-LOCK NO-ERROR.
      FIND FAKTKUNDKONTOKRED WHERE ROWID(FAKTKUNDKONTOKRED) = efaktkundtemp.FROW EXCLUSIVE-LOCK NO-ERROR.
      IF NOT AVAILABLE FAKTKUNDKONTOKRED THEN CREATE FAKTKUNDKONTOKRED.
      BUFFER-COPY efaktkundtemp TO FAKTKUNDKONTOKRED.
      FOR EACH FAKTKUNDKONTOKRED WHERE FAKTKUNDKONTOKRED.FAKTNR = infakplannr AND 
      FAKTKUNDKONTOKRED.FDELNR = fdelnrvar EXCLUSIVE-LOCK: 
         ASSIGN
         FAKTKUNDKONTOKRED.FAKTDATUM = efaktkundtemp.FAKTDATUM  
         FAKTKUNDKONTOKRED.FDATUM = efaktkundtemp.FDATUM.        
      END.
   END.
   IF vart = 2 THEN DO TRANSACTION:
      FIND FIRST efaktinkontotemp NO-LOCK NO-ERROR.
      FIND FAKTINTAKTKONTKRED WHERE ROWID(FAKTINTAKTKONTKRED) = efaktkundtemp.FROW EXCLUSIVE-LOCK NO-ERROR.
      IF NOT AVAILABLE FAKTINTAKTKONTKRED THEN CREATE FAKTINTAKTKONTKRED.
      BUFFER-COPY efaktkundtemp TO FAKTINTAKTKONTKRED.
      
   END.
   IF vart = 3 THEN DO TRANSACTION:
      FIND FIRST efaktmomstemp NO-LOCK NO-ERROR.
      FIND FAKTMOMSKRED WHERE ROWID(FAKTMOMSKRED) = efaktmomstemp.FROW EXCLUSIVE-LOCK NO-ERROR.
      IF NOT AVAILABLE FAKTMOMSKRED THEN CREATE FAKTMOMSKRED.
      BUFFER-COPY efaktmomstemp TO FAKTMOMSKRED.
   END.
   RELEASE FAKTKUNDKONTOKRED NO-ERROR.
   RELEASE FAKTINTAKTKONTKRED NO-ERROR.
   RELEASE FAKTMOMSKRED NO-ERROR. 
END PROCEDURE.
PROCEDURE hmtkonton_UI:
   DEFINE INPUT PARAMETER vart  AS INTEGER NO-UNDO.
   DEFINE INPUT PARAMETER infakplannr  AS INTEGER NO-UNDO.
   DEFINE INPUT PARAMETER fdelnrvar   AS INTEGER NO-UNDO.
   DEFINE INPUT PARAMETER bytvar   AS INTEGER NO-UNDO.
   DEFINE VARIABLE brwk1h AS HANDLE NO-UNDO.
   IF vart = 1 THEN DO:
      /*TAKPRIS*/
      OPEN QUERY BRW_K1 FOR EACH FAKTKUNDKONTO WHERE 
      FAKTKUNDKONTO.FAKTNR = infakplannr AND 
      FAKTKUNDKONTO.FDELNR = fdelnrvar NO-LOCK, 
      EACH KUNDFODRAN WHERE KUNDFODRAN.KUNDKONTOID = FAKTKUNDKONTO.KUNDKONTOID NO-LOCK, 
      EACH MOTPART WHERE MOTPART.MOTPARTID = FAKTKUNDKONTO.MOTPARTID NO-LOCK.
      
      OPEN QUERY BRW_K2 FOR EACH FAKTINTAKTKONT WHERE 
      FAKTINTAKTKONT.FAKTNR = infakplannr AND 
      FAKTINTAKTKONT.FDELNR = fdelnrvar NO-LOCK, 
      EACH INTAKTTAB WHERE INTAKTTAB.INTAKTID = FAKTINTAKTKONT.INTAKTID NO-LOCK, 
      EACH MOTPART WHERE MOTPART.MOTPARTID = FAKTINTAKTKONT.MOTPARTID NO-LOCK.
      
      OPEN QUERY BRW_K4 FOR EACH FAKTMOMS WHERE 
      FAKTMOMS.FAKTNR = infakplannr AND 
      FAKTMOMS.FDELNR = fdelnrvar NO-LOCK, 
      EACH MOMSTAB WHERE MOMSTAB.MOMSID = FAKTMOMS.MOMSID NO-LOCK.                       
   END.
   IF vart >= 2 THEN DO:
      OPEN QUERY BRW_K1 FOR EACH FAKTKUNDKONTO WHERE 
      FAKTKUNDKONTO.FAKTNR = infakplannr AND 
      FAKTKUNDKONTO.FDELNR = fdelnrvar NO-LOCK, 
      EACH KUNDFODRAN WHERE KUNDFODRAN.KUNDKONTOID = FAKTKUNDKONTO.KUNDKONTOID NO-LOCK, 
      EACH MOTPART WHERE MOTPART.MOTPARTID = FAKTKUNDKONTO.MOTPARTID NO-LOCK.
      OPEN QUERY BRW_K2 FOR EACH FAKTINTAKTKONT WHERE 
      FAKTINTAKTKONT.FAKTNR = infakplannr AND 
      FAKTINTAKTKONT.FDELNR = fdelnrvar NO-LOCK, 
      EACH INTAKTTAB WHERE INTAKTTAB.INTAKTID = FAKTINTAKTKONT.INTAKTID NO-LOCK, 
      EACH MOTPART WHERE MOTPART.MOTPARTID = FAKTINTAKTKONT.MOTPARTID NO-LOCK.
      OPEN QUERY BRW_K4 FOR EACH FAKTMOMS WHERE 
      FAKTMOMS.FAKTNR = infakplannr AND 
      FAKTMOMS.FDELNR = fdelnrvar NO-LOCK, 
      EACH MOMSTAB WHERE MOMSTAB.MOMSID = FAKTMOMS.MOMSID NO-LOCK.      
   END.
   IF vart = 13 THEN DO:
      GET FIRST BRW_K1 NO-LOCK.
      DO WHILE AVAILABLE(FAKTKUNDKONTO):
         DO TRANSACTION:
            GET CURRENT BRW_K1 EXCLUSIVE-LOCK.
            FAKTKUNDKONTO.MOTPARTID = bytvar.
         END.
         GET NEXT BRW_K1 NO-LOCK.
      END.
      GET FIRST BRW_K2 NO-LOCK.
      DO WHILE AVAILABLE(FAKTINTAKTKONT):
         DO TRANSACTION:
            GET CURRENT BRW_K2 EXCLUSIVE-LOCK.
            FAKTINTAKTKONT.MOTPARTID = bytvar.
         END.
         GET NEXT BRW_K2 NO-LOCK.
      END.
   END.
   GET FIRST BRW_K1 NO-LOCK.
   DO WHILE AVAILABLE(FAKTKUNDKONTO):
      CREATE faktkundtemp.
      BUFFER-COPY FAKTKUNDKONTO TO faktkundtemp.
      ASSIGN
      faktkundtemp.FROW = ROWID(FAKTKUNDKONTO)
      faktkundtemp.KUNDKONTO =  KUNDFODRAN.KUNDKONTO 
      faktkundtemp.KUNDFODTEXT =  SUBSTRING(KUNDFODRAN.KUNDFODTEXT,1,1) + LC(SUBSTRING(KUNDFODRAN.KUNDFODTEXT,2))
      faktkundtemp.MOTPART =  MOTPART.MOTPART 
      faktkundtemp.MOTPARTTEXT = SUBSTRING(MOTPART.MOTPARTTEXT,1,1) + LC(SUBSTRING(MOTPART.MOTPARTTEXT,2)).
      GET NEXT BRW_K1 NO-LOCK.      
   END.
   GET FIRST BRW_K2 NO-LOCK.
   DO WHILE AVAILABLE(FAKTINTAKTKONT):
      CREATE faktinkontotemp.
      BUFFER-COPY FAKTINTAKTKONT TO faktinkontotemp.
      ASSIGN
      faktinkontotemp.FROW = ROWID(FAKTINTAKTKONT)
      faktinkontotemp.INTAKTKONTO =  INTAKTTAB.INTAKTKONTO 
      faktinkontotemp.INTAKTTEXT =  SUBSTRING(INTAKTTAB.INTAKTTEXT,1,1) + LC(SUBSTRING(INTAKTTAB.INTAKTTEXT,2))
      faktinkontotemp.MOTPART =  MOTPART.MOTPART 
      faktinkontotemp.MOTPARTTEXT = SUBSTRING(MOTPART.MOTPARTTEXT,1,1) + LC(SUBSTRING(MOTPART.MOTPARTTEXT,2)).
      GET NEXT BRW_K2 NO-LOCK.      
   END.
   GET FIRST BRW_K4 NO-LOCK.
   DO WHILE AVAILABLE(FAKTMOMS):
      CREATE faktmomstemp.
      BUFFER-COPY FAKTMOMS TO faktmomstemp.
      ASSIGN
      faktmomstemp.FROW = ROWID(FAKTMOMS)
      faktmomstemp.MOMSKOD =  MOMSTAB.MOMSKOD 
      faktmomstemp.MOMSTEXT =  SUBSTRING(MOMSTAB.MOMSTEXT,1,1) + LC(SUBSTRING(MOMSTAB.MOMSTEXT,2)).           
      GET NEXT BRW_K4 NO-LOCK.      
   END.
END PROCEDURE.
PROCEDURE hmtkontonk_UI:
   DEFINE INPUT PARAMETER vart  AS INTEGER NO-UNDO.
   DEFINE INPUT PARAMETER infakplannr  AS INTEGER NO-UNDO.
   DEFINE INPUT PARAMETER fdelnrvar   AS INTEGER NO-UNDO.
   DEFINE INPUT PARAMETER bytvar   AS INTEGER NO-UNDO.
   IF vart = 1 THEN DO:
      OPEN QUERY BRW_K1 FOR EACH FAKTKUNDKONTOKRED WHERE 
      FAKTKUNDKONTOKRED.FAKTNR = infakplannr AND 
      FAKTKUNDKONTOKRED.FDELNR = fdelnrvar NO-LOCK, 
      EACH KUNDFODRAN WHERE KUNDFODRAN.KUNDKONTOID = FAKTKUNDKONTOKRED.KUNDKONTOID NO-LOCK, 
      EACH MOTPART WHERE MOTPART.MOTPARTID = FAKTKUNDKONTOKRED.MOTPARTID NO-LOCK.
      
      OPEN QUERY BRW_K2 FOR EACH FAKTINTAKTKONTKRED WHERE 
      FAKTINTAKTKONTKRED.FAKTNR = infakplannr AND 
      FAKTINTAKTKONTKRED.FDELNR = fdelnrvar NO-LOCK, 
      EACH INTAKTTAB WHERE INTAKTTAB.INTAKTID = FAKTINTAKTKONTKRED.INTAKTID NO-LOCK, 
      EACH MOTPART WHERE MOTPART.MOTPARTID = FAKTINTAKTKONTKRED.MOTPARTID NO-LOCK.
      
      OPEN QUERY BRW_K4 FOR EACH FAKTMOMSKRED WHERE 
      FAKTMOMSKRED.FAKTNR = infakplannr AND 
      FAKTMOMSKRED.FDELNR = fdelnrvar NO-LOCK, 
      EACH MOMSTAB WHERE MOMSTAB.MOMSID = FAKTMOMSKRED.MOMSID NO-LOCK.      
      
   END.
   IF vart >= 2 THEN DO:
      OPEN QUERY BRW_K1 FOR EACH FAKTKUNDKONTOKRED WHERE 
      FAKTKUNDKONTOKRED.FAKTNR = infakplannr AND 
      FAKTKUNDKONTOKRED.FDELNR = fdelnrvar NO-LOCK, 
      EACH KUNDFODRAN WHERE KUNDFODRAN.KUNDKONTOID = FAKTKUNDKONTOKRED.KUNDKONTOID NO-LOCK, 
      EACH MOTPART WHERE MOTPART.MOTPARTID = FAKTKUNDKONTOKRED.MOTPARTID NO-LOCK.
      OPEN QUERY BRW_K2 FOR EACH FAKTINTAKTKONTKRED WHERE 
      FAKTINTAKTKONTKRED.FAKTNR = infakplannr AND 
      FAKTINTAKTKONTKRED.FDELNR = fdelnrvar NO-LOCK, 
      EACH INTAKTTAB WHERE INTAKTTAB.INTAKTID = FAKTINTAKTKONTKRED.INTAKTID NO-LOCK, 
      EACH MOTPART WHERE MOTPART.MOTPARTID = FAKTINTAKTKONTKRED.MOTPARTID NO-LOCK.
      OPEN QUERY BRW_K4 FOR EACH FAKTMOMSKRED WHERE 
      FAKTMOMSKRED.FAKTNR = infakplannr AND 
      FAKTMOMSKRED.FDELNR = fdelnrvar NO-LOCK, 
      EACH MOMSTAB WHERE MOMSTAB.MOMSID = FAKTMOMSKRED.MOMSID NO-LOCK.      
   END.
   IF vart = 13 THEN DO:
      GET FIRST BRW_K1 NO-LOCK.
      DO WHILE AVAILABLE(FAKTKUNDKONTOKRED):
         DO TRANSACTION:
            GET CURRENT BRW_K1 EXCLUSIVE-LOCK.
            FAKTKUNDKONTOKRED.MOTPARTID = bytvar.
         END.
         GET NEXT BRW_K1 NO-LOCK.
      END.
      GET FIRST BRW_K2 NO-LOCK.
      DO WHILE AVAILABLE(FAKTINTAKTKONTKRED):
         DO TRANSACTION:
            GET CURRENT BRW_K2 EXCLUSIVE-LOCK.
            FAKTINTAKTKONTKRED.MOTPARTID = bytvar.
         END.
         GET NEXT BRW_K2 NO-LOCK.
      END.
   END.
   GET FIRST BRW_K1 NO-LOCK.
   DO WHILE AVAILABLE(FAKTKUNDKONTOKRED):
      CREATE faktkundtemp.
      BUFFER-COPY FAKTKUNDKONTOKRED TO faktkundtemp.
      ASSIGN
      faktkundtemp.FROW = ROWID(FAKTKUNDKONTOKRED)
      faktkundtemp.KUNDKONTO =  KUNDFODRAN.KUNDKONTO 
      faktkundtemp.KUNDFODTEXT =  SUBSTRING(KUNDFODRAN.KUNDFODTEXT,1,1) + LC(SUBSTRING(KUNDFODRAN.KUNDFODTEXT,2))
      faktkundtemp.MOTPART =  MOTPART.MOTPART 
      faktkundtemp.MOTPARTTEXT = SUBSTRING(MOTPART.MOTPARTTEXT,1,1) + LC(SUBSTRING(MOTPART.MOTPARTTEXT,2)).
      GET NEXT BRW_K1 NO-LOCK.      
   END.
   GET FIRST BRW_K2 NO-LOCK.
   DO WHILE AVAILABLE(FAKTINTAKTKONTKRED):
      CREATE faktinkontotemp.
      BUFFER-COPY FAKTINTAKTKONTKRED TO faktinkontotemp.
      ASSIGN
      faktinkontotemp.FROW = ROWID(FAKTINTAKTKONTKRED)
      faktinkontotemp.INTAKTKONTO =  INTAKTTAB.INTAKTKONTO 
      faktinkontotemp.INTAKTTEXT =  SUBSTRING(INTAKTTAB.INTAKTTEXT,1,1) + LC(SUBSTRING(INTAKTTAB.INTAKTTEXT,2))
      faktinkontotemp.MOTPART =  MOTPART.MOTPART 
      faktinkontotemp.MOTPARTTEXT = SUBSTRING(MOTPART.MOTPARTTEXT,1,1) + LC(SUBSTRING(MOTPART.MOTPARTTEXT,2)).
      GET NEXT BRW_K2 NO-LOCK.      
   END.
   GET FIRST BRW_K4 NO-LOCK.
   DO WHILE AVAILABLE(FAKTMOMSKRED):
      CREATE faktmomstemp.
      BUFFER-COPY FAKTMOMSKRED TO faktmomstemp.
      ASSIGN
      faktmomstemp.FROW = ROWID(FAKTMOMSKRED)
      faktmomstemp.MOMSKOD =  MOMSTAB.MOMSKOD 
      faktmomstemp.MOMSTEXT =  SUBSTRING(MOMSTAB.MOMSTEXT,1,1) + LC(SUBSTRING(MOMSTAB.MOMSTEXT,2)).           
      GET NEXT BRW_K4 NO-LOCK.      
   END.
END PROCEDURE.

PROCEDURE nykonton_UI:
   DEFINE INPUT PARAMETER vart AS INTEGER NO-UNDO.
   DEFINE INPUT PARAMETER infakplannr  AS INTEGER NO-UNDO.
   DEFINE INPUT PARAMETER fdelnrvar   AS INTEGER NO-UNDO.
   DEFINE INPUT PARAMETER bytvar   AS INTEGER NO-UNDO.
   DEFINE INPUT-OUTPUT PARAMETER TABLE FOR kolltabeltemp.
   DEFINE OUTPUT PARAMETER TABLE FOR faktkundtemp.
   DEFINE OUTPUT PARAMETER TABLE FOR faktinkontotemp.
   DEFINE OUTPUT PARAMETER TABLE FOR faktmomstemp.
   EMPTY TEMP-TABLE faktkundtemp NO-ERROR.
   EMPTY TEMP-TABLE faktinkontotemp NO-ERROR.
   EMPTY TEMP-TABLE faktmomstemp NO-ERROR.
   IF vart = 1 THEN DO:
      FIND FIRST kolltabeltemp NO-ERROR.            
      IF kolltabeltemp.DENNAFAKT NE kolltabeltemp.NYFAKT THEN DO:
         /*TAKPRIS*/
         kolltabeltemp.NYFAKT = kolltabeltemp.DENNAFAKT.
         OPEN QUERY BRW_K1 FOR EACH FAKTKUNDKONTO WHERE 
         FAKTKUNDKONTO.FAKTNR = infakplannr AND 
         FAKTKUNDKONTO.FDELNR = fdelnrvar NO-LOCK, 
         EACH KUNDFODRAN WHERE KUNDFODRAN.KUNDKONTOID = FAKTKUNDKONTO.KUNDKONTOID NO-LOCK, 
         EACH MOTPART WHERE MOTPART.MOTPARTID = FAKTKUNDKONTO.MOTPARTID NO-LOCK.
         GET FIRST BRW_K1 NO-LOCK.
         IF AVAILABLE FAKTKUNDKONTO THEN DO TRANSACTION:
            GET CURRENT BRW_K1 EXCLUSIVE-LOCK.
            ASSIGN 
            FAKTKUNDKONTO.BELOPP = kolltabeltemp.NYFAKT. 
         END.
         DO WHILE AVAILABLE(FAKTKUNDKONTO):
            GET NEXT BRW_K1 NO-LOCK.
            IF AVAILABLE FAKTKUNDKONTO THEN DO TRANSACTION:
               GET CURRENT BRW_K1 EXCLUSIVE-LOCK.
               ASSIGN 
               FAKTKUNDKONTO.BELOPP = 0.
            END.         
         END.
         OPEN QUERY BRW_K2 FOR EACH FAKTINTAKTKONT WHERE 
         FAKTINTAKTKONT.FAKTNR = infakplannr AND 
         FAKTINTAKTKONT.FDELNR = fdelnrvar NO-LOCK, 
         EACH INTAKTTAB WHERE INTAKTTAB.INTAKTID = FAKTINTAKTKONT.INTAKTID NO-LOCK, 
         EACH MOTPART WHERE MOTPART.MOTPARTID = FAKTINTAKTKONT.MOTPARTID NO-LOCK.
         GET FIRST BRW_K2 NO-LOCK.
         IF AVAILABLE FAKTINTAKTKONT THEN DO TRANSACTION:
            GET CURRENT BRW_K2 EXCLUSIVE-LOCK.
            ASSIGN 
            FAKTINTAKTKONT.BELOPP = kolltabeltemp.NYFAKT. 
         END.
         DO WHILE AVAILABLE(FAKTINTAKTKONT):
            GET NEXT BRW_K2 NO-LOCK.
            IF AVAILABLE FAKTINTAKTKONT THEN DO TRANSACTION:
               GET CURRENT BRW_K2 EXCLUSIVE-LOCK.
               ASSIGN 
               FAKTINTAKTKONT.BELOPP = 0.
            END.         
         END.
         OPEN QUERY BRW_K4 FOR EACH FAKTMOMS WHERE 
         FAKTMOMS.FAKTNR = infakplannr AND 
         FAKTMOMS.FDELNR = fdelnrvar NO-LOCK, 
         EACH MOMSTAB WHERE MOMSTAB.MOMSID = FAKTMOMS.MOMSID NO-LOCK.      
         GET FIRST BRW_K4 NO-LOCK.
         IF AVAILABLE FAKTMOMS THEN DO TRANSACTION:
            GET CURRENT BRW_K4 EXCLUSIVE-LOCK.
            ASSIGN 
            FAKTMOMS.BELOPP = kolltabeltemp.NYFAKT 
            FAKTMOMS.MOMSBELOPP = kolltabeltemp.NYFAKT * FAKTMOMS.MOMSEXTERNT / 100.
         END.
         DO WHILE AVAILABLE(FAKTMOMS):
            GET NEXT BRW_K4 NO-LOCK.
            IF AVAILABLE FAKTMOMS THEN DO TRANSACTION:
               GET CURRENT BRW_K4 EXCLUSIVE-LOCK.
               ASSIGN 
               FAKTMOMS.BELOPP = 0 
               FAKTMOMS.MOMSBELOPP = 0.         
            END.         
         END.         
      END.     
      ELSE DO:
         vart = 2.         
      END.
      /*SLUTFAKT*/
      IF kolltabeltemp.SLUTFAKT = TRUE THEN DO:   
         /*ACCONTO*/
         IF kolltabeltemp.ACONTO = TRUE THEN DO:
            ASSIGN
            kolltabeltemp.NYFAKT = kolltabeltemp.NYFAKT - kolltabeltemp.GFAKT.                  
            /*TIDIGARE OMOMSAT FÖRSKOTT*/
            IF kolltabeltemp.GMOMS = 0 THEN DO:
               /*MOMS PÅ TOTALEN.*/            
            END.         
            ELSE DO:
               DO TRANSACTION:
                  GET FIRST BRW_K4 EXCLUSIVE-LOCK.              
                  IF AVAILABLE FAKTMOMS THEN DO:         
                     ASSIGN 
                     FAKTMOMS.BELOPP = kolltabeltemp.NYFAKT 
                     FAKTMOMS.MOMSBELOPP = kolltabeltemp.NYFAKT * FAKTMOMS.MOMSEXTERNT / 100.
                  END.
               END.   
               REPEAT:
                  DO TRANSACTION:
                     GET NEXT BRW_K4 EXCLUSIVE-LOCK.
                     IF AVAILABLE FAKTMOMS THEN DO:         
                        ASSIGN 
                        FAKTMOMS.BELOPP = 0 
                        FAKTMOMS.MOMSBELOPP = 0.         
                     END.   
                     ELSE LEAVE.
                  END.   
               END.            
            END.
            DO TRANSACTION:
               GET FIRST BRW_K1 EXCLUSIVE-LOCK.
               ASSIGN 
               FAKTKUNDKONTO.BELOPP = kolltabeltemp.NYFAKT. 
            END.
            REPEAT:
               DO TRANSACTION: 
                  GET NEXT BRW_K1 EXCLUSIVE-LOCK.
                  IF AVAILABLE FAKTKUNDKONTO THEN FAKTKUNDKONTO.BELOPP = 0.
                  ELSE LEAVE.
               END.   
            END.
            DO TRANSACTION:
               GET FIRST BRW_K2 EXCLUSIVE-LOCK.
               ASSIGN 
               FAKTINTAKTKONT.BELOPP = kolltabeltemp.NYFAKT. 
            END.
            REPEAT:
               DO TRANSACTION:
                  GET NEXT BRW_K2 EXCLUSIVE-LOCK.
                  IF AVAILABLE FAKTINTAKTKONT THEN FAKTINTAKTKONT.BELOPP = 0.
                  ELSE LEAVE.
               END.   
            END.   
         END.      
      END. 
   END.
   RUN hmtkonton_UI (INPUT vart,INPUT infakplannr,INPUT fdelnrvar,INPUT bytvar).
END PROCEDURE.
PROCEDURE nykontonk_UI:
   DEFINE INPUT PARAMETER vart AS INTEGER NO-UNDO.
   DEFINE INPUT PARAMETER infakplannr  AS INTEGER NO-UNDO.
   DEFINE INPUT PARAMETER fdelnrvar   AS INTEGER NO-UNDO.
   DEFINE INPUT PARAMETER bytvar   AS INTEGER NO-UNDO.
   DEFINE INPUT-OUTPUT PARAMETER TABLE FOR kolltabeltemp.
   DEFINE OUTPUT PARAMETER TABLE FOR faktkundtemp.
   DEFINE OUTPUT PARAMETER TABLE FOR faktinkontotemp.
   DEFINE OUTPUT PARAMETER TABLE FOR faktmomstemp.
   EMPTY TEMP-TABLE faktkundtemp NO-ERROR.
   EMPTY TEMP-TABLE faktinkontotemp NO-ERROR.
   EMPTY TEMP-TABLE faktmomstemp NO-ERROR.
   IF vart = 1 THEN DO:
      FIND FIRST kolltabeltemp NO-ERROR.            
      IF kolltabeltemp.DENNAFAKT NE kolltabeltemp.NYFAKT THEN DO:
         /*TAKPRIS*/
         kolltabeltemp.NYFAKT = kolltabeltemp.DENNAFAKT.
         OPEN QUERY BRW_K1 FOR EACH FAKTKUNDKONTOKRED WHERE 
         FAKTKUNDKONTOKRED.FAKTNR = infakplannr AND 
         FAKTKUNDKONTOKRED.FDELNR = fdelnrvar NO-LOCK, 
         EACH KUNDFODRAN WHERE KUNDFODRAN.KUNDKONTOID = FAKTKUNDKONTOKRED.KUNDKONTOID NO-LOCK, 
         EACH MOTPART WHERE MOTPART.MOTPARTID = FAKTKUNDKONTOKRED.MOTPARTID NO-LOCK.
         GET FIRST BRW_K1 NO-LOCK.
         IF AVAILABLE FAKTKUNDKONTOKRED THEN DO TRANSACTION:
            GET CURRENT BRW_K1 EXCLUSIVE-LOCK.
            ASSIGN 
            FAKTKUNDKONTOKRED.BELOPP = kolltabeltemp.NYFAKT. 
         END.
         DO WHILE AVAILABLE(FAKTKUNDKONTOKRED):
            GET NEXT BRW_K1 NO-LOCK.
            IF AVAILABLE FAKTKUNDKONTOKRED THEN DO TRANSACTION:
               GET CURRENT BRW_K1 EXCLUSIVE-LOCK.
               ASSIGN 
               FAKTKUNDKONTOKRED.BELOPP = 0.
            END.         
         END.
         OPEN QUERY BRW_K2 FOR EACH FAKTINTAKTKONTKRED WHERE 
         FAKTINTAKTKONTKRED.FAKTNR = infakplannr AND 
         FAKTINTAKTKONTKRED.FDELNR = fdelnrvar NO-LOCK, 
         EACH INTAKTTAB WHERE INTAKTTAB.INTAKTID = FAKTINTAKTKONTKRED.INTAKTID NO-LOCK, 
         EACH MOTPART WHERE MOTPART.MOTPARTID = FAKTINTAKTKONTKRED.MOTPARTID NO-LOCK.
         GET FIRST BRW_K2 NO-LOCK.
         IF AVAILABLE FAKTINTAKTKONTKRED THEN DO TRANSACTION:
            GET CURRENT BRW_K2 EXCLUSIVE-LOCK.
            ASSIGN 
            FAKTINTAKTKONTKRED.BELOPP = kolltabeltemp.NYFAKT. 
         END.
         DO WHILE AVAILABLE(FAKTINTAKTKONTKRED):
            GET NEXT BRW_K2 NO-LOCK.
            IF AVAILABLE FAKTINTAKTKONTKRED THEN DO TRANSACTION:
               GET CURRENT BRW_K2 EXCLUSIVE-LOCK.
               ASSIGN 
               FAKTINTAKTKONTKRED.BELOPP = 0.
            END.         
         END.
         OPEN QUERY BRW_K4 FOR EACH FAKTMOMSKRED WHERE 
         FAKTMOMSKRED.FAKTNR = infakplannr AND 
         FAKTMOMSKRED.FDELNR = fdelnrvar NO-LOCK, 
         EACH MOMSTAB WHERE MOMSTAB.MOMSID = FAKTMOMSKRED.MOMSID NO-LOCK.      
         GET FIRST BRW_K4 NO-LOCK.
         IF AVAILABLE FAKTMOMSKRED THEN DO TRANSACTION:
            GET CURRENT BRW_K4 EXCLUSIVE-LOCK.
            ASSIGN 
            FAKTMOMSKRED.BELOPP = kolltabeltemp.NYFAKT 
            FAKTMOMSKRED.MOMSBELOPP = kolltabeltemp.NYFAKT * FAKTMOMSKRED.MOMSEXTERNT / 100.
         END.
         DO WHILE AVAILABLE(FAKTMOMS):
            GET NEXT BRW_K4 NO-LOCK.
            IF AVAILABLE FAKTMOMSKRED THEN DO TRANSACTION:
               GET CURRENT BRW_K4 EXCLUSIVE-LOCK.
               ASSIGN 
               FAKTMOMSKRED.BELOPP = 0 
               FAKTMOMSKRED.MOMSBELOPP = 0.         
            END.         
         END.         
      END.     
      ELSE DO:
         vart = 2.         
      END.      
   END.
   RUN hmtkontonk_UI (INPUT vart,INPUT infakplannr,INPUT fdelnrvar,INPUT bytvar).
END PROCEDURE.
         
PROCEDURE sattanv_UI :
    DEFINE INPUT PARAMETER infakplannr  AS INTEGER NO-UNDO.
    DEFINE INPUT PARAMETER globanv AS CHARACTER NO-UNDO.
    DO TRANSACTION:
       FIND FIRST FAKTPLAN WHERE FAKTPLAN.FAKTNR = infakplannr EXCLUSIVE-LOCK NO-ERROR.
       FAKTPLAN.PANVANDARE = Guru.Konstanter:globanv.      
    END.   
    RELEASE FAKTPLAN NO-ERROR.
END PROCEDURE.
PROCEDURE medskick_UI:
   DEFINE INPUT PARAMETER infakplannr  AS INTEGER NO-UNDO.
   DEFINE INPUT PARAMETER fdelnrvar   AS INTEGER NO-UNDO.
   DEFINE INPUT PARAMETER skarpvar AS INTEGER NO-UNDO.
   DEFINE INPUT PARAMETER answeradm AS LOGICAL NO-UNDO.
   DEFINE INPUT PARAMETER answerprel AS LOGICAL NO-UNDO.
   DEFINE INPUT PARAMETER answerFB AS LOGICAL NO-UNDO.
   DEFINE INPUT PARAMETER gamanv AS CHARACTER NO-UNDO.
   DEFINE INPUT PARAMETER ganv AS CHARACTER NO-UNDO.
   DEFINE INPUT PARAMETER varfaktsek AS LOGICAL NO-UNDO.
   RUN EXTRATABHMT.P PERSISTENT SET fbestapph.         
   
   FIND FIRST FAKTPLAN WHERE FAKTPLAN.FAKTNR = infakplannr NO-LOCK NO-ERROR.
   FIND FIRST FAKTURERAD WHERE FAKTURERAD.FAKTNR = infakplannr AND FAKTURERAD.FDELNR = fdelnrvar
   NO-LOCK NO-ERROR.
   FIND FIRST FAKTREGLER WHERE FAKTREGLER.FAKTNR = infakplannr NO-LOCK NO-ERROR.
   IF answeradm = TRUE THEN DO TRANSACTION:  
      FIND FIRST FAKTURADM USE-INDEX ANDV NO-LOCK NO-ERROR. 
      FIND FIRST faktyptemp WHERE faktyptemp.FAKTTYP = FAKTPLAN.FAKTTYP NO-ERROR.
      FIND FIRST MEDDELANDE WHERE MEDDELANDE.SDATUM = TODAY AND MEDDELANDE.EMOTAGET = FALSE AND MEDDELANDE.MOTTAGARE = FAKTURADM.ANVANDARE AND
      MEDDELANDE.SANDARE = ganv   
      EXCLUSIVE-LOCK NO-ERROR.
      IF NOT AVAILABLE MEDDELANDE THEN DO:
         CREATE MEDDELANDE.
      END.
      ASSIGN 
      MEDDELANDE.SDATUM = TODAY
      MEDDELANDE.EMOTAGET = FALSE
      MEDDELANDE.MEDD = MEDDELANDE.MEDD + CHR(10) + faktyptemp.VIFAKTTYP + " " +
      STRING(FAKTPLAN.FAKTNR) + " " + STRING(FAKTURERAD.FDELNR) + CHR(10) 
      + STRING(skarpvar,"9999999999999") +
      " Har fakturerats." 
      MEDDELANDE.MOTTAGARE = FAKTURADM.ANVANDARE
      MEDDELANDE.SANDARE = ganv.         
   END.
   RELEASE MEDDELANDE NO-ERROR.
   IF answerprel = TRUE THEN DO TRANSACTION:     
      FIND FIRST faktyptemp WHERE faktyptemp.FAKTTYP = FAKTPLAN.FAKTTYP NO-ERROR.
      FIND FIRST MEDDELANDE WHERE MEDDELANDE.SDATUM = TODAY AND MEDDELANDE.EMOTAGET = FALSE AND MEDDELANDE.MOTTAGARE = gamanv AND
      MEDDELANDE.SANDARE = ganv   
      EXCLUSIVE-LOCK NO-ERROR.
      IF NOT AVAILABLE MEDDELANDE THEN DO:
         CREATE MEDDELANDE.
      END.
      IF varfaktsek = TRUE THEN DO:
         ASSIGN 
         MEDDELANDE.SDATUM = TODAY
         MEDDELANDE.EMOTAGET = FALSE
         MEDDELANDE.MEDD = MEDDELANDE.MEDD + CHR(10) + faktyptemp.VIFAKTTYP + " " +
         STRING(FAKTPLAN.FAKTNR) + " " + STRING(FAKTURERAD.FDELNR) + CHR(10) 
         + STRING(skarpvar,"9999999999999") +
         " Är godkänd och fakturerad."
         MEDDELANDE.MOTTAGARE = gamanv 
         MEDDELANDE.SANDARE = ganv.           
      END.
      ELSE DO:
         ASSIGN 
         MEDDELANDE.SDATUM = TODAY
         MEDDELANDE.EMOTAGET = FALSE
         MEDDELANDE.MEDD = MEDDELANDE.MEDD + CHR(10) + faktyptemp.VIFAKTTYP + " " +
         STRING(FAKTPLAN.FAKTNR) + " " + STRING(FAKTURERAD.FDELNR) + CHR(10) 
         + STRING(skarpvar,"9999999999999") +
         " Har fakturerats."
         MEDDELANDE.MOTTAGARE = gamanv 
         MEDDELANDE.SANDARE = ganv.           
      END.
      RUN epostadd_UI.            
   END. 
   RELEASE MEDDELANDE NO-ERROR.
   
   IF answerFB = TRUE THEN DO TRANSACTION:     
      FIND FIRST faktyptemp WHERE faktyptemp.FAKTTYP = FAKTPLAN.FAKTTYP NO-ERROR.
      CREATE inextrakopptemp.          
      ASSIGN                           
      inextrakopptemp.PROGRAM = "FBFPLAN"                   
      inextrakopptemp.KOPPLACHAR1 = ?
      inextrakopptemp.KOPPLAINT1 =  FAKTREGLER.FAKTNR      
      inextrakopptemp.KOPPLACHAR2 = ?            
      inextrakopptemp.KOPPLAINT2 =  ?.
      RUN etabhamt_UI IN fbestapph (INPUT TABLE inextrakopptemp,OUTPUT TABLE extrakopptemp).        
      FIND FIRST extrakopptemp NO-ERROR.
      IF AVAILABLE extrakopptemp THEN DO:
         IF extrakopptemp.SOKCHAR[1] NE "" THEN DO:      
            FIND FIRST MEDDELANDE WHERE MEDDELANDE.SDATUM = TODAY AND MEDDELANDE.EMOTAGET = FALSE AND MEDDELANDE.MOTTAGARE = extrakopptemp.SOKCHAR[1] AND
            MEDDELANDE.SANDARE = ganv   
            EXCLUSIVE-LOCK NO-ERROR.
            IF NOT AVAILABLE MEDDELANDE THEN DO:
               CREATE MEDDELANDE.
            END.
            CREATE MEDDELANDE.
            ASSIGN 
            MEDDELANDE.SDATUM = TODAY
            MEDDELANDE.EMOTAGET = FALSE
            MEDDELANDE.MEDD = MEDDELANDE.MEDD + CHR(10) + STRING(FAKTPLAN.FAKTNR) + " " + STRING(FAKTURERAD.FDELNR) + CHR(10) 
            + "Klar till beställare"
            MEDDELANDE.MOTTAGARE = extrakopptemp.SOKCHAR[1] 
            MEDDELANDE.SANDARE = ganv.           
            RUN epostadd_UI.
         END.
      END.     
   END.
   RELEASE MEDDELANDE NO-ERROR.
   IF VALID-HANDLE(fbestapph) THEN DELETE PROCEDURE fbestapph.      
   fbestapph = ?.   
END PROCEDURE.

PROCEDURE mailstart_UI :
   DEFINE INPUT PARAMETER amnevar AS CHARACTER NO-UNDO.
   DEFINE INPUT PARAMETER meddvar AS CHARACTER NO-UNDO.
   DEFINE VARIABLE franvar AS CHARACTER NO-UNDO.
   IF Guru.Konstanter:globforetag = "SUND"  THEN DO:
      ASSIGN
      /*
      servervar = "172.16.79.249". 
      servervar = "130.1.27.253".
      */
      servervar = CHR(49) + CHR(55) + CHR(50) + CHR(46) + CHR(49) + CHR(54) + CHR(46) + CHR(50) + CHR(53) + CHR(52) + CHR(46) + CHR(50) + CHR(50) + CHR(50).
   END.
   ELSE IF Guru.Konstanter:globforetag = "SNAT" THEN DO:
      {SMTPFRANELPOOL.I}
   END.
   IF servervar = "" OR tillvar = "" THEN RETURN.
   IF namndb() = "utbi" THEN RETURN.
   ASSIGN 
   mailhub             = servervar     
   EmailTo             = tillvar 
   EmailFrom           = franvar
   EmailCC             = ""
   Attachmentstyp      = ""
   LocalFiles          = ""
   Subject             = amnevar
   Bodysmtp            = meddvar
   MIMEHeader          = "type=text/html:charset=iso-8859-1:filetype=ascii"
   BodyType            = "".
   IF Guru.Konstanter:globforetag = "sund" THEN EmailFrom = "webguru@sundsvallenergi.se".
   IF Guru.Konstanter:globforetag = "SNAT" THEN EmailFrom = "@guru.sundsvallelnat.se".
   IF Guru.Konstanter:globforetag = "MISV" THEN EmailFrom = "webguru@mittsverigevatten.se".
   RUN smtpmail_UI (INPUT FALSE).
   IF oSuccessful = TRUE THEN DO:
      oSuccessful = FALSE.                      
   END.            
END PROCEDURE.
PROCEDURE medskickk_UI:
   DEFINE INPUT PARAMETER infakplannr  AS INTEGER NO-UNDO.
   DEFINE INPUT PARAMETER fdelnrvar   AS INTEGER NO-UNDO.
   DEFINE INPUT PARAMETER skarpvar AS INTEGER NO-UNDO.
   DEFINE INPUT PARAMETER answeradm AS LOGICAL NO-UNDO.
   DEFINE INPUT PARAMETER answerprel AS LOGICAL NO-UNDO.
   DEFINE INPUT PARAMETER answerFB AS LOGICAL NO-UNDO.
   DEFINE INPUT PARAMETER gamanv AS CHARACTER NO-UNDO.
   DEFINE INPUT PARAMETER ganv AS CHARACTER NO-UNDO.
   DEFINE INPUT PARAMETER varfaktsek AS LOGICAL NO-UNDO.
   RUN EXTRATABHMT.P PERSISTENT SET fbestapph.         
   
   FIND FIRST FAKTPLAN WHERE FAKTPLAN.FAKTNR = infakplannr NO-LOCK NO-ERROR.
   FIND FIRST FAKTKRED WHERE FAKTKRED.FAKTNR = infakplannr AND FAKTKRED.FDELNR = fdelnrvar
   NO-LOCK NO-ERROR.
   FIND FIRST FAKTREGLER WHERE FAKTREGLER.FAKTNR = infakplannr NO-LOCK NO-ERROR.
   IF answeradm = TRUE THEN DO TRANSACTION:  
      FIND FIRST FAKTURADM USE-INDEX ANDV NO-LOCK NO-ERROR. 
      FIND FIRST faktyptemp WHERE faktyptemp.FAKTTYP = FAKTPLAN.FAKTTYP NO-ERROR.
      FIND FIRST MEDDELANDE WHERE MEDDELANDE.SDATUM = TODAY AND MEDDELANDE.EMOTAGET = FALSE AND MEDDELANDE.MOTTAGARE = FAKTURADM.ANVANDARE AND
      MEDDELANDE.SANDARE = ganv
      NO-LOCK NO-ERROR.
      IF NOT AVAILABLE MEDDELANDE THEN CREATE MEDDELANDE.
      ASSIGN 
      MEDDELANDE.SDATUM = TODAY
      MEDDELANDE.EMOTAGET = FALSE
      MEDDELANDE.MEDD = MEDDELANDE.MEDD + CHR(10) + faktyptemp.VIFAKTTYP + " " +
      STRING(FAKTPLAN.FAKTNR) + " " + STRING(FAKTKRED.FDELNR) + CHR(10) 
      + STRING(skarpvar,"9999999999999") +
      " Har krediterats." 
      MEDDELANDE.MOTTAGARE = FAKTURADM.ANVANDARE
      MEDDELANDE.SANDARE = ganv.         
   END.        
   IF answerprel = TRUE THEN DO TRANSACTION:     
      FIND FIRST faktyptemp WHERE faktyptemp.FAKTTYP = FAKTPLAN.FAKTTYP NO-ERROR.
      FIND FIRST MEDDELANDE WHERE MEDDELANDE.SDATUM = TODAY AND MEDDELANDE.EMOTAGET = FALSE AND MEDDELANDE.MOTTAGARE = gamanv AND
      MEDDELANDE.SANDARE = ganv
      NO-LOCK NO-ERROR.
      IF NOT AVAILABLE MEDDELANDE THEN CREATE MEDDELANDE.      
      IF varfaktsek = TRUE THEN DO:
         ASSIGN 
         MEDDELANDE.SDATUM = TODAY
         MEDDELANDE.EMOTAGET = FALSE
         MEDDELANDE.MEDD = MEDDELANDE.MEDD + CHR(10) + faktyptemp.VIFAKTTYP + " " +
         STRING(FAKTPLAN.FAKTNR) + " " + STRING(FAKTKRED.FDELNR) + CHR(10) 
         + STRING(skarpvar,"9999999999999") +
         " Är godkänd och krediterats."
         MEDDELANDE.MOTTAGARE = gamanv 
         MEDDELANDE.SANDARE = Guru.Konstanter:globanv.           
      END.
      ELSE DO:
         ASSIGN 
         MEDDELANDE.SDATUM = TODAY
         MEDDELANDE.EMOTAGET = FALSE
         MEDDELANDE.MEDD = MEDDELANDE.MEDD + CHR(10) + faktyptemp.VIFAKTTYP + " " +
         STRING(FAKTPLAN.FAKTNR) + " " + STRING(FAKTKRED.FDELNR) + CHR(10) 
         + STRING(skarpvar,"9999999999999") +
         " Har krediterats."
         MEDDELANDE.MOTTAGARE = gamanv 
         MEDDELANDE.SANDARE = Guru.Konstanter:globanv.           
      END.
      RUN epostadd_UI.
   END. 
   IF answerFB = TRUE THEN DO TRANSACTION:     
      FIND FIRST faktyptemp WHERE faktyptemp.FAKTTYP = FAKTPLAN.FAKTTYP NO-ERROR.
      CREATE inextrakopptemp.          
      ASSIGN
      inextrakopptemp.PROGRAM = "FBFPLAN"                   
      inextrakopptemp.KOPPLACHAR1 = ?
      inextrakopptemp.KOPPLAINT1 =  FAKTREGLER.FAKTNR      
      inextrakopptemp.KOPPLACHAR2 = ?            
      inextrakopptemp.KOPPLAINT2 =  ?.
      RUN etabhamt_UI IN fbestapph (INPUT TABLE inextrakopptemp,OUTPUT TABLE extrakopptemp).        
      FIND FIRST extrakopptemp NO-ERROR.
      IF AVAILABLE extrakopptemp THEN DO:
         IF extrakopptemp.SOKCHAR[1] NE "" THEN DO:      
            FIND FIRST MEDDELANDE WHERE MEDDELANDE.SDATUM = TODAY AND MEDDELANDE.EMOTAGET = FALSE AND MEDDELANDE.MOTTAGARE = extrakopptemp.SOKCHAR[1]  AND
            MEDDELANDE.SANDARE = ganv
            NO-LOCK NO-ERROR.
            IF NOT AVAILABLE MEDDELANDE THEN CREATE MEDDELANDE.
            ASSIGN 
            MEDDELANDE.SDATUM = TODAY
            MEDDELANDE.EMOTAGET = FALSE
            MEDDELANDE.MEDD = MEDDELANDE.MEDD +  CHR(10) + STRING(FAKTPLAN.FAKTNR) + " " + STRING(FAKTKRED.FDELNR) + CHR(10) 
            + "Klar för kreditering till beställare"
            MEDDELANDE.MOTTAGARE = extrakopptemp.SOKCHAR[1] 
            MEDDELANDE.SANDARE = Guru.Konstanter:globanv.           
            RUN epostadd_UI.            
         END.
      END.                 
   END.
   IF VALID-HANDLE(fbestapph) THEN DELETE PROCEDURE fbestapph.      
   fbestapph = ?.
   RELEASE MEDDELANDE NO-ERROR.
END PROCEDURE.

PROCEDURE epostadd_UI :
   tillvar = "".
   FIND FIRST ANVANDARE WHERE ANVANDARE.ANVANDARE = MEDDELANDE.MOTTAGARE NO-LOCK NO-ERROR.
   IF AVAILABLE ANVANDARE THEN DO:
      FIND FIRST PERSONALTAB WHERE PERSONALTAB.PERSONALKOD = ANVANDARE.PERSONALKOD NO-LOCK NO-ERROR.
      IF AVAILABLE PERSONALTAB THEN DO:
         tillvar = SUBSTRING(PERSONALTAB.PERSONSOK,20).
         RUN mailstart_UI (INPUT "Dags att godkänna fakturor i Guru.",INPUT MEDDELANDE.MEDD).
      END.
   END.           
END PROCEDURE.
PROCEDURE skarpsatt_UI:
   DEFINE INPUT PARAMETER infakplannr  AS INTEGER NO-UNDO.
   DEFINE INPUT PARAMETER fdelnrvar   AS INTEGER NO-UNDO.
   DEFINE INPUT PARAMETER skarpvar AS INTEGER NO-UNDO.
   DEFINE INPUT PARAMETER varbokdatum AS DATE NO-UNDO.
   DEFINE INPUT PARAMETER varfakturd AS DATE NO-UNDO.
   DEFINE INPUT PARAMETER varforfalld AS DATE NO-UNDO.
   DEFINE OUTPUT PARAMETER sluttotpris AS DECIMAL NO-UNDO.
   RUN EXTRADATAHMT.P PERSISTENT SET edataapph.
         
   FIND FIRST FAKTPLAN WHERE FAKTPLAN.FAKTNR = infakplannr NO-LOCK NO-ERROR.
   FIND FIRST FAKTURERAD WHERE FAKTURERAD.FAKTNR = infakplannr AND FAKTURERAD.FDELNR = fdelnrvar
   NO-LOCK NO-ERROR.
   OPEN QUERY faktfriq FOR EACH FAKTFRIA WHERE FAKTFRIA.FAKTNR = FAKTPLAN.FAKTNR AND
   FAKTFRIA.FDELNR = fdelnrvar NO-LOCK.  
   GET FIRST faktfriq NO-LOCK.
   DO WHILE AVAILABLE(FAKTFRIA):
      DO TRANSACTION:
         GET CURRENT faktfriq EXCLUSIVE-LOCK.   
         FAKTFRIA.VFAKTNR = skarpvar.                                  
      END.
      GET NEXT faktfriq NO-LOCK.   
   END. 
   OPEN QUERY faktmtrlq FOR EACH FAKTMTRL WHERE FAKTMTRL.FAKTNR = FAKTPLAN.FAKTNR AND
   FAKTMTRL.FDELNR = fdelnrvar NO-LOCK.  
   GET FIRST faktmtrlq NO-LOCK.
   DO WHILE AVAILABLE(FAKTMTRL):
      DO TRANSACTION:
         GET CURRENT faktmtrlq EXCLUSIVE-LOCK.   
         FAKTMTRL.VFAKTNR = skarpvar.                                  
      END.
      GET NEXT faktmtrlq NO-LOCK.   
   END.   
   /*FÖRDELNING AV KOSTNADER PÅ AONR'S KONTOT*/
   OPEN QUERY faktkontq FOR EACH FAKTINTAKTKONT WHERE 
   FAKTINTAKTKONT.FAKTNR = FAKTPLAN.FAKTNR AND  
   FAKTINTAKTKONT.FDELNR = fdelnrvar AND 
   FAKTINTAKTKONT.VFAKTNR = 0 NO-LOCK.
   GET FIRST faktkontq NO-LOCK.   
   DO WHILE AVAILABLE(FAKTINTAKTKONT):
      DO TRANSACTION:
         GET CURRENT faktkontq EXCLUSIVE-LOCK. 
         FAKTINTAKTKONT.VFAKTNR = skarpvar.            
         OPEN QUERY aokq FOR EACH AONRKONTKOD WHERE AONRKONTKOD.AONR = FAKTINTAKTKONT.AONR AND       
         AONRKONTKOD.DELNR = FAKTINTAKTKONT.DELNR NO-LOCK.
         GET FIRST aokq NO-LOCK.
         
         DO WHILE AVAILABLE(AONRKONTKOD):
            IF AONRKONTKOD.SATS% > 0 THEN DO:
               CREATE FAKTAONRKONTO.
               ASSIGN
               FAKTAONRKONTO.FDELNR = 0 
               FAKTAONRKONTO.FAKTNR = FAKTINTAKTKONT.FAKTNR 
               FAKTAONRKONTO.VFAKTNR = skarpvar 
               FAKTAONRKONTO.AONR = AONRKONTKOD.AONR 
               FAKTAONRKONTO.DELNR = AONRKONTKOD.DELNR
               FAKTAONRKONTO.K1 = AONRKONTKOD.K1 
               FAKTAONRKONTO.K2 = AONRKONTKOD.K2 
               FAKTAONRKONTO.K3 = AONRKONTKOD.K3 
               FAKTAONRKONTO.K4 = AONRKONTKOD.K4 
               FAKTAONRKONTO.K5 = AONRKONTKOD.K5 
               FAKTAONRKONTO.SATS% = AONRKONTKOD.SATS%.
            END.
            GET NEXT aokq NO-LOCK.
         END.  
         /*Bara ett aonr*/
         IF Guru.Konstanter:globforetag = "SUND" OR Guru.Konstanter:globforetag = "SNAT" OR Guru.Konstanter:globforetag = "ELPA" THEN DO:
            FOR EACH EXTRAKOPPLINGAR WHERE EXTRAKOPPLINGAR.PROGRAM = "FBAONR" AND
            EXTRAKOPPLINGAR.KOPPLACHAR1 = FAKTINTAKTKONT.AONR AND       
            EXTRAKOPPLINGAR.KOPPLAINT1 = FAKTINTAKTKONT.DELNR NO-LOCK:               
               FOR EACH AONRKONTKOD WHERE AONRKONTKOD.AONR = EXTRAKOPPLINGAR.KOPPLACHAR2 AND       
               AONRKONTKOD.DELNR = EXTRAKOPPLINGAR.KOPPLAINT2 NO-LOCK:
                  IF AONRKONTKOD.SATS% > 0 THEN DO:
                     
                     FIND FIRST FAKTAONRKONTO WHERE 
                     FAKTAONRKONTO.FDELNR = 1  AND
                     FAKTAONRKONTO.FAKTNR = FAKTINTAKTKONT.FAKTNR AND
                     FAKTAONRKONTO.VFAKTNR = skarpvar  AND
                     FAKTAONRKONTO.AONR = EXTRAKOPPLINGAR.KOPPLACHAR2 AND
                     FAKTAONRKONTO.DELNR = EXTRAKOPPLINGAR.KOPPLAINT2 AND  
                     FAKTAONRKONTO.K1 = AONRKONTKOD.K1 AND
                     FAKTAONRKONTO.K2 = AONRKONTKOD.K2 AND
                     FAKTAONRKONTO.K3 = AONRKONTKOD.K3 AND
                     FAKTAONRKONTO.K4 = AONRKONTKOD.K4 AND
                     FAKTAONRKONTO.K5 = AONRKONTKOD.K5 
                     EXCLUSIVE-LOCK NO-ERROR.
                     IF NOT AVAILABLE FAKTAONRKONTO THEN DO:
                        CREATE FAKTAONRKONTO.
                        
                     END.                                         
                     ASSIGN
                     FAKTAONRKONTO.FDELNR = 1
                     FAKTAONRKONTO.FAKTNR = FAKTINTAKTKONT.FAKTNR 
                     FAKTAONRKONTO.VFAKTNR = skarpvar 
                     FAKTAONRKONTO.AONR = EXTRAKOPPLINGAR.KOPPLACHAR2 
                     FAKTAONRKONTO.DELNR = EXTRAKOPPLINGAR.KOPPLAINT2
                     FAKTAONRKONTO.K1 = AONRKONTKOD.K1 
                     FAKTAONRKONTO.K2 = AONRKONTKOD.K2 
                     FAKTAONRKONTO.K3 = AONRKONTKOD.K3 
                     FAKTAONRKONTO.K4 = AONRKONTKOD.K4 
                     FAKTAONRKONTO.K5 = AONRKONTKOD.K5 
                     FAKTAONRKONTO.SATS% = AONRKONTKOD.SATS%.                                      
                  END.
               END.
               /*Bara ett aonr*/
               CREATE  exkoppbuff.          
               ASSIGN                           
               exkoppbuff.PROGRAM = "FBDEB"                  
               exkoppbuff.KOPPLACHAR1 = EXTRAKOPPLINGAR.KOPPLACHAR1
               exkoppbuff.KOPPLAINT1 =  EXTRAKOPPLINGAR.KOPPLAINT1     
               exkoppbuff.KOPPLACHAR2 = EXTRAKOPPLINGAR.KOPPLACHAR2          
               exkoppbuff.KOPPLAINT2 =  EXTRAKOPPLINGAR.KOPPLAINT2
               exkoppbuff.SOKINT[1] = skarpvar
               exkoppbuff.SOKINT[2] = FAKTINTAKTKONT.FAKTNR
               exkoppbuff.SOKDATE[1] = varbokdatum            
               exkoppbuff.SOKDEC[1] = FAKTINTAKTKONT.BELOPP * EXTRAKOPPLINGAR.SOKINT[1] / 100. 
                                                                /*procent uppdeling mellen aonr just nu alltid 100*/                            
                                                            /*fakturerat belopp * % från faktura bestproj */
            END.
            RELEASE exkoppbuff NO-ERROR.
         END.             
      END.
      GET NEXT faktkontq NO-LOCK.
   END.
  
   IF VALID-HANDLE(edataapph) THEN DELETE PROCEDURE edataapph.      
   edataapph = ?.
   
   OPEN QUERY faktkundq FOR EACH FAKTKUNDKONTO WHERE 
   FAKTKUNDKONTO.FAKTNR = FAKTPLAN.FAKTNR AND  
   FAKTKUNDKONTO.FDELNR = fdelnrvar AND 
   FAKTKUNDKONTO.VFAKTNR = 0 NO-LOCK.
   DO TRANSACTION:
      FIND CURRENT FAKTURERAD EXCLUSIVE-LOCK NO-ERROR. 
      ASSIGN
      FAKTURERAD.PRELGOD = FALSE
      FAKTURERAD.TOTPRIS = 0. 
      GET FIRST faktkundq EXCLUSIVE-LOCK.
      DO WHILE AVAILABLE(FAKTKUNDKONTO):
         ASSIGN
         FAKTURERAD.TOTPRIS = FAKTURERAD.TOTPRIS  + FAKTKUNDKONTO.BELOPP
         FAKTKUNDKONTO.FAKTDATUM = varfakturd
         FAKTKUNDKONTO.FDATUM = varforfalld
         FAKTKUNDKONTO.VFAKTNR = skarpvar.
         GET NEXT faktkundq EXCLUSIVE-LOCK.
      END.
   END.
   sluttotpris = FAKTURERAD.TOTPRIS.
   OPEN QUERY faktmomsq FOR EACH FAKTMOMS WHERE 
   FAKTMOMS.FAKTNR = FAKTPLAN.FAKTNR AND  
   FAKTMOMS.FDELNR = fdelnrvar AND 
   FAKTMOMS.VFAKTNR = 0 NO-LOCK.
   GET FIRST faktmomsq NO-LOCK.
   DO WHILE AVAILABLE(FAKTMOMS):
      DO TRANSACTION:
         GET CURRENT faktmomsq EXCLUSIVE-LOCK.     
         FAKTMOMS.VFAKTNR = skarpvar.         
      END.
      GET NEXT faktmomsq NO-LOCK.
   END.
   RELEASE FAKTURERAD NO-ERROR.
   RELEASE FAKTMOMS NO-ERROR.
   RELEASE FAKTMTRL NO-ERROR.
   RELEASE FAKTINTAKTKONT NO-ERROR.
   RELEASE FAKTAONRKONTO NO-ERROR.
   RELEASE FAKTKUNDKONTO NO-ERROR.

END PROCEDURE.
PROCEDURE skarpsattk_UI:
   DEFINE INPUT PARAMETER infakplannr  AS INTEGER NO-UNDO.
   DEFINE INPUT PARAMETER fdelnrvar   AS INTEGER NO-UNDO.
   DEFINE INPUT PARAMETER skarpvar AS INTEGER NO-UNDO.
   DEFINE INPUT PARAMETER varbokdatum AS DATE NO-UNDO.
   DEFINE INPUT PARAMETER varfakturd AS DATE NO-UNDO.
   DEFINE INPUT PARAMETER varforfalld AS DATE NO-UNDO.
   RUN EXTRADATAHMT.P PERSISTENT SET edataapph. 
   FIND FIRST FAKTPLAN WHERE FAKTPLAN.FAKTNR = infakplannr NO-LOCK NO-ERROR.
   FIND FIRST FAKTKRED WHERE FAKTKRED.FAKTNR = infakplannr AND FAKTKRED.FDELNR = fdelnrvar
   NO-LOCK NO-ERROR.
   OPEN QUERY faktfriq FOR EACH FAKTFRIAKRED WHERE FAKTFRIAKRED.FAKTNR = FAKTPLAN.FAKTNR AND
   FAKTFRIAKRED.FDELNR = fdelnrvar NO-LOCK.  
   GET FIRST faktfriq NO-LOCK.
   DO WHILE AVAILABLE(FAKTFRIAKRED):
      DO TRANSACTION:
         GET CURRENT faktfriq EXCLUSIVE-LOCK.   
         FAKTFRIAKRED.VKREDIT = skarpvar.                                  
      END.
      GET NEXT faktfriq NO-LOCK.   
   END. 
   OPEN QUERY faktmtrlq FOR EACH FAKTMTRLKRED WHERE FAKTMTRLKRED.FAKTNR = FAKTPLAN.FAKTNR AND
   FAKTMTRLKRED.FDELNR = fdelnrvar NO-LOCK.  
   GET FIRST faktmtrlq NO-LOCK.
   DO WHILE AVAILABLE(FAKTMTRLKRED):
      DO TRANSACTION:
         GET CURRENT faktmtrlq EXCLUSIVE-LOCK.   
         FAKTMTRLKRED.VKREDIT = skarpvar.                                  
      END.
      GET NEXT faktmtrlq NO-LOCK.   
   END.   
   /*FÖRDELNING AV KOSTNADER PÅ AONR'S KONTOT*/
   OPEN QUERY faktkontq FOR EACH FAKTINTAKTKONTKRED WHERE 
   FAKTINTAKTKONTKRED.FAKTNR = FAKTPLAN.FAKTNR AND  
   FAKTINTAKTKONTKRED.FDELNR = fdelnrvar AND 
   FAKTINTAKTKONTKRED.VKREDIT = 0 NO-LOCK.
   GET FIRST faktkontq NO-LOCK.   
   DO WHILE AVAILABLE(FAKTINTAKTKONTKRED):
      DO TRANSACTION:
         GET CURRENT faktkontq EXCLUSIVE-LOCK. 
         FAKTINTAKTKONTKRED.VKREDIT = skarpvar.            
         OPEN QUERY aokq FOR EACH AONRKONTKOD WHERE AONRKONTKOD.AONR = FAKTINTAKTKONTKRED.AONR AND       
         AONRKONTKOD.DELNR = FAKTINTAKTKONTKRED.DELNR NO-LOCK.
         GET FIRST aokq NO-LOCK.         
         DO WHILE AVAILABLE(AONRKONTKOD):
            IF AONRKONTKOD.SATS% > 0 THEN DO:
               IF AONRKONTKOD.SATS% > 0 THEN DO:
                  CREATE FAKTAONRKONTOKRED.
                  ASSIGN
                  FAKTAONRKONTOKRED.FDELNR = 0 
                  FAKTAONRKONTOKRED.FAKTNR = FAKTINTAKTKONTKRED.FAKTNR 
                  FAKTAONRKONTOKRED.VKREDIT = skarpvar 
                  FAKTAONRKONTOKRED.AONR = AONRKONTKOD.AONR 
                  FAKTAONRKONTOKRED.DELNR = AONRKONTKOD.DELNR
                  FAKTAONRKONTOKRED.K1 = AONRKONTKOD.K1 
                  FAKTAONRKONTOKRED.K2 = AONRKONTKOD.K2 
                  FAKTAONRKONTOKRED.K3 = AONRKONTKOD.K3 
                  FAKTAONRKONTOKRED.K4 = AONRKONTKOD.K4 
                  FAKTAONRKONTOKRED.K5 = AONRKONTKOD.K5 
                  FAKTAONRKONTOKRED.SATS% = AONRKONTKOD.SATS%.
               END.             
            END.
            GET NEXT aokq NO-LOCK.
         END.        
         /*Bara ett aonr*/
         IF Guru.Konstanter:globforetag = "SUND" OR Guru.Konstanter:globforetag = "SNAT" OR Guru.Konstanter:globforetag = "ELPA" THEN DO:
            FOR EACH EXTRAKOPPLINGAR WHERE EXTRAKOPPLINGAR.PROGRAM = "FBAONR" AND
            EXTRAKOPPLINGAR.KOPPLACHAR1 = FAKTINTAKTKONTKRED.AONR AND       
            EXTRAKOPPLINGAR.KOPPLAINT1 = FAKTINTAKTKONTKRED.DELNR NO-LOCK:               
               FOR EACH AONRKONTKOD WHERE AONRKONTKOD.AONR = EXTRAKOPPLINGAR.KOPPLACHAR2 AND       
               AONRKONTKOD.DELNR = EXTRAKOPPLINGAR.KOPPLAINT2 NO-LOCK:
                  IF AONRKONTKOD.SATS% > 0 THEN DO:
                     FIND FIRST FAKTAONRKONTOKRED WHERE 
                     FAKTAONRKONTOKRED.FDELNR = 1  AND
                     FAKTAONRKONTOKRED.FAKTNR = FAKTINTAKTKONTKRED.FAKTNR AND
                     FAKTAONRKONTOKRED.VKREDIT = skarpvar  AND
                     FAKTAONRKONTOKRED.AONR = EXTRAKOPPLINGAR.KOPPLACHAR2 AND
                     FAKTAONRKONTOKRED.DELNR = EXTRAKOPPLINGAR.KOPPLAINT2 AND  
                     FAKTAONRKONTOKRED.K1 = AONRKONTKOD.K1 AND
                     FAKTAONRKONTOKRED.K2 = AONRKONTKOD.K2 AND
                     FAKTAONRKONTOKRED.K3 = AONRKONTKOD.K3 AND
                     FAKTAONRKONTOKRED.K4 = AONRKONTKOD.K4 AND
                     FAKTAONRKONTOKRED.K5 = AONRKONTKOD.K5 
                     EXCLUSIVE-LOCK NO-ERROR.
                     IF NOT AVAILABLE FAKTAONRKONTOKRED THEN DO:
                        CREATE FAKTAONRKONTOKRED.
                     END.
                     ASSIGN
                     FAKTAONRKONTOKRED.FDELNR = 1
                     FAKTAONRKONTOKRED.FAKTNR = FAKTINTAKTKONTKRED.FAKTNR 
                     FAKTAONRKONTOKRED.VKREDIT = skarpvar 
                     FAKTAONRKONTOKRED.AONR = EXTRAKOPPLINGAR.KOPPLACHAR2 
                     FAKTAONRKONTOKRED.DELNR = EXTRAKOPPLINGAR.KOPPLAINT2
                     FAKTAONRKONTOKRED.K1 = AONRKONTKOD.K1 
                     FAKTAONRKONTOKRED.K2 = AONRKONTKOD.K2 
                     FAKTAONRKONTOKRED.K3 = AONRKONTKOD.K3 
                     FAKTAONRKONTOKRED.K4 = AONRKONTKOD.K4 
                     FAKTAONRKONTOKRED.K5 = AONRKONTKOD.K5 
                     FAKTAONRKONTOKRED.SATS% = AONRKONTKOD.SATS%.                                      
                  END.
               END.
               /*Bara ett aonr*/
               CREATE  exkoppbuff.          
               ASSIGN                           
               exkoppbuff.PROGRAM = "FBKRED"                  
               exkoppbuff.KOPPLACHAR1 = EXTRAKOPPLINGAR.KOPPLACHAR1
               exkoppbuff.KOPPLAINT1 =  EXTRAKOPPLINGAR.KOPPLAINT1     
               exkoppbuff.KOPPLACHAR2 = EXTRAKOPPLINGAR.KOPPLACHAR2          
               exkoppbuff.KOPPLAINT2 =  EXTRAKOPPLINGAR.KOPPLAINT2
               exkoppbuff.SOKINT[1] = skarpvar
               exkoppbuff.SOKINT[2] = FAKTINTAKTKONTKRED.FAKTNR
               exkoppbuff.SOKDATE[1] = varbokdatum            
               exkoppbuff.SOKDEC[1] = FAKTINTAKTKONTKRED.BELOPP * EXTRAKOPPLINGAR.SOKINT[1] / 100. 
                                                                /*procent uppdeling mellen aonr just nu alltid 100*/                            
            END.
            RELEASE exkoppbuff NO-ERROR.             
         END.             
      END.
      GET NEXT faktkontq NO-LOCK.
   END.
   
   IF VALID-HANDLE(edataapph) THEN DELETE PROCEDURE edataapph.      
   edataapph = ?.
   OPEN QUERY faktkundq FOR EACH FAKTKUNDKONTOKRED WHERE 
   FAKTKUNDKONTOKRED.FAKTNR = FAKTPLAN.FAKTNR AND  
   FAKTKUNDKONTOKRED.FDELNR = fdelnrvar AND 
   FAKTKUNDKONTOKRED.VKREDIT = 0 NO-LOCK.
   DO TRANSACTION:
      FIND CURRENT FAKTKRED EXCLUSIVE-LOCK NO-ERROR. 
      ASSIGN
      FAKTKRED.PRELGOD = FALSE
      FAKTKRED.TOTPRIS = 0. 
      GET FIRST faktkundq EXCLUSIVE-LOCK.
      DO WHILE AVAILABLE(FAKTKUNDKONTOKRED):
         ASSIGN
         FAKTKRED.TOTPRIS = FAKTKRED.TOTPRIS + FAKTKUNDKONTOKRED.BELOPP
         FAKTKUNDKONTOKRED.FAKTDATUM = varfakturd
         FAKTKUNDKONTOKRED.FDATUM = varforfalld
         FAKTKUNDKONTOKRED.VKREDIT = skarpvar.
         GET NEXT faktkundq EXCLUSIVE-LOCK.
      END.
   END.
   OPEN QUERY faktmomsq FOR EACH FAKTMOMSKRED WHERE 
   FAKTMOMSKRED.FAKTNR = FAKTPLAN.FAKTNR AND  
   FAKTMOMSKRED.FDELNR = FAKTKRED.FDELNR AND 
   FAKTMOMSKRED.VKREDIT = 0 NO-LOCK.
   DO TRANSACTION:
      GET FIRST faktmomsq EXCLUSIVE-LOCK.
      DO WHILE AVAILABLE(FAKTMOMSKRED):
         FAKTMOMSKRED.VKREDIT = skarpvar.
         GET NEXT faktmomsq EXCLUSIVE-LOCK.
      END.
   END.   
   RELEASE FAKTKRED NO-ERROR.
   RELEASE FAKTMOMSKRED NO-ERROR.
   RELEASE FAKTMTRLKRED NO-ERROR.
   RELEASE FAKTINTAKTKONTKRED NO-ERROR.
   RELEASE FAKTAONRKONTOKRED NO-ERROR.
   RELEASE FAKTKUNDKONTOKRED NO-ERROR.
END PROCEDURE.
PROCEDURE faktkollspar_UI:
   DEFINE INPUT PARAMETER infakplannr  AS INTEGER NO-UNDO.
   DEFINE INPUT PARAMETER TABLE FOR faktkolltemp.
   DEFINE INPUT PARAMETER TABLE FOR kosttemp.
   FIND FIRST FAKTPLAN WHERE FAKTPLAN.FAKTNR = infakplannr NO-LOCK NO-ERROR.
   FOR EACH faktkolltemp:
      DO TRANSACTION:
         FIND FIRST FAKTKOLL WHERE ROWID(FAKTKOLL) = faktkolltemp.KOLLROW EXCLUSIVE-LOCK NO-ERROR.
         IF AVAILABL FAKTKOLL THEN DO:
            BUFFER-COPY faktkolltemp TO FAKTKOLL.
         END.
      END.      
   END.           
   FOR EACH kosttemp NO-LOCK:
      DO TRANSACTION:
         FIND KOSTREG WHERE KOSTREG.AONR = kosttemp.AONR AND
         KOSTREG.DELNR = kosttemp.DELNR AND KOSTREG.RADNR = kosttemp.RADNR 
         EXCLUSIVE-LOCK NO-ERROR.
         KOSTREG.FAKTURERAD = kosttemp.MED.
      END.   
   END.
   RELEASE FAKTKOLL NO-ERROR.
   RELEASE KOSTREG NO-ERROR.
END PROCEDURE.
PROCEDURE faktkollhmt_UI:
   DEFINE INPUT PARAMETER infakplannr  AS INTEGER NO-UNDO.
   DEFINE OUTPUT PARAMETER TABLE FOR faktkolltemp.
   EMPTY TEMP-TABLE faktkolltemp NO-ERROR.
   FOR EACH FAKTKOLL WHERE FAKTKOLL.FAKTNR = infakplannr NO-LOCK:
      CREATE faktkolltemp.
      BUFFER-COPY FAKTKOLL TO faktkolltemp.
      faktkolltemp.KOLLROW = ROWID(FAKTKOLL).
   END.
END PROCEDURE.
PROCEDURE skarpnr_UI:
   DEFINE INPUT PARAMETER infakplannr  AS INTEGER NO-UNDO.
   DEFINE OUTPUT PARAMETER skarpvar AS INTEGER NO-UNDO.
   DEFINE OUTPUT PARAMETER feltextvar AS CHARACTER NO-UNDO.
   feltextvar = "".
   FIND FIRST FAKTPLAN WHERE FAKTPLAN.FAKTNR = infakplannr NO-LOCK NO-ERROR.
   DO TRANSACTION:        
      FIND FIRST OMRADETAB WHERE OMRADETAB.OMRADE = FAKTPLAN.OMRADE NO-LOCK NO-ERROR.
      FIND FIRST FAKTSKARP WHERE FAKTSKARP.OMRADE = FAKTPLAN.OMRADE 
      EXCLUSIVE-LOCK NO-ERROR.       
      IF NOT AVAILABLE FAKTSKARP THEN DO:         
         FIND FIRST FAKTSKARP EXCLUSIVE-LOCK NO-ERROR.
      END.
      IF NOT AVAILABLE FAKTSKARP THEN DO:
         feltextvar = "Ingen fakturanummerserie är upplaggd! Du kan inte fakturera!".  
         RETURN.
      END.
      skarpvar = FAKTSKARP.LOPNR.
      FAKTSKARP.LOPNR = FAKTSKARP.LOPNR + 1.                
   END.
END PROCEDURE.
PROCEDURE forfaldatum_UI:
   DEFINE INPUT-OUTPUT PARAMETER varforfalld AS DATE NO-UNDO.
   REPEAT:
      IF WEEKDAY(varforfalld) = 1 THEN varforfalld = varforfalld + 1.
      IF WEEKDAY(varforfalld) = 7 THEN varforfalld = varforfalld + 2.
      FIND FIRST OVERAVTAB WHERE OVERAVTAB.DATUM = varforfalld NO-LOCK NO-ERROR.
      IF NOT AVAILABLE OVERAVTAB THEN DO:
         LEAVE.
      END.
      ELSE IF OVERAVTAB.EQDAG = 1 THEN varforfalld = varforfalld + 1.
      ELSE IF OVERAVTAB.EQDAG = 7 THEN varforfalld = varforfalld + 1.
      ELSE LEAVE.
   END.
END PROCEDURE.
PROCEDURE sparfaktkkred_UI:   
   DEFINE INPUT PARAMETER TABLE FOR efaktkredtemp.
   FIND FIRST efaktkredtemp NO-LOCK NO-ERROR.
   DO TRANSACTION:
      FIND FIRST FAKTKRED WHERE FAKTKRED.FAKTNR = efaktkredtemp.FAKTNR AND FAKTKRED.FDELNR = efaktkredtemp.FDELNR
      EXCLUSIVE-LOCK NO-ERROR.
      BUFFER-COPY efaktkredtemp TO FAKTKRED.
   END.
   FIND CURRENT FAKTKRED NO-LOCK NO-ERROR.     
END.
PROCEDURE sparfaktk_UI:
   DEFINE INPUT PARAMETER infakplannr           AS INTEGER NO-UNDO.
   DEFINE INPUT PARAMETER fdelnrvar             AS INTEGER NO-UNDO.
   DEFINE INPUT PARAMETER TABLE FOR efaktkredtemp.
   DEFINE INPUT PARAMETER TABLE FOR faktstarttemp.
   DEFINE INPUT PARAMETER TABLE FOR faktupparbtemp.
   FIND FIRST FAKTPLAN WHERE FAKTPLAN.FAKTNR = infakplannr NO-LOCK NO-ERROR.
   FIND FIRST efaktkredtemp WHERE efaktkredtemp.FAKTNR = infakplannr AND efaktkredtemp.FDELNR = fdelnrvar NO-LOCK NO-ERROR.
   DO TRANSACTION:
      FIND FIRST FAKTKRED WHERE FAKTKRED.FAKTNR = infakplannr AND FAKTKRED.FDELNR = fdelnrvar
      EXCLUSIVE-LOCK NO-ERROR.
      BUFFER-COPY efaktkredtemp TO FAKTKRED.
   END.
   FIND CURRENT FAKTKRED NO-LOCK NO-ERROR.
   FOR EACH FAKTUPPARBKRED WHERE FAKTUPPARBKRED.FAKTNR = FAKTPLAN.FAKTNR AND FAKTUPPARBKRED.FDELNR = fdelnrvar EXCLUSIVE-LOCK:
      DELETE FAKTUPPARBKRED.
   END.
   FOR EACH faktupparbtemp WHERE faktupparbtemp.FAKTNR = FAKTPLAN.FAKTNR AND faktupparbtemp.FDELNR = fdelnrvar NO-LOCK:
      CREATE FAKTUPPARBKRED.
      BUFFER-COPY faktupparbtemp TO FAKTUPPARBKRED.
   END.
   FOR EACH FAKTSTARTKRED WHERE FAKTSTARTKRED.FAKTNR = FAKTPLAN.FAKTNR AND FAKTSTARTKRED.FDELNR = fdelnrvar EXCLUSIVE-LOCK:
      DELETE FAKTSTARTKRED.
   END.
   FOR EACH faktstarttemp WHERE faktstarttemp.FAKTNR = FAKTPLAN.FAKTNR AND faktstarttemp.FDELNR = fdelnrvar NO-LOCK:
      CREATE FAKTSTARTKRED.
      BUFFER-COPY faktstarttemp TO FAKTSTARTKRED.
   END.
   RELEASE FAKTSTARTKRED NO-ERROR.
   RELEASE FAKTUPPARBKRED NO-ERROR.      
END.
PROCEDURE sparfakturerad_UI:
   DEFINE INPUT PARAMETER TABLE FOR faktureradtemp.
   FIND FIRST faktureradtemp NO-LOCK NO-ERROR.
   DO TRANSACTION:
      FIND FIRST FAKTURERAD WHERE FAKTURERAD.FAKTNR = faktureradtemp.FAKTNR AND FAKTURERAD.FDELNR = faktureradtemp.FDELNR
      EXCLUSIVE-LOCK NO-ERROR.
      BUFFER-COPY faktureradtemp TO FAKTURERAD.
   END.     
   FIND CURRENT FAKTURERAD NO-LOCK NO-ERROR.
END.
PROCEDURE sparfakt_UI:
   DEFINE INPUT PARAMETER infakplannr           AS INTEGER NO-UNDO.
   DEFINE INPUT PARAMETER fdelnrvar             AS INTEGER NO-UNDO.
   DEFINE INPUT PARAMETER TABLE FOR vfaktplantemp.
   DEFINE INPUT PARAMETER TABLE FOR faktureradtemp.
   DEFINE INPUT PARAMETER TABLE FOR faktstarttemp.
   DEFINE INPUT PARAMETER TABLE FOR faktupparbtemp.
   FIND FIRST vfaktplantemp WHERE vfaktplantemp.FAKTNR = infakplannr NO-LOCK NO-ERROR.
   FIND FIRST faktureradtemp WHERE faktureradtemp.FAKTNR = infakplannr AND faktureradtemp.FDELNR = fdelnrvar NO-LOCK NO-ERROR.
   DO TRANSACTION:
      FIND FIRST FAKTPLAN WHERE FAKTPLAN.FAKTNR = infakplannr EXCLUSIVE-LOCK NO-ERROR.
      BUFFER-COPY vfaktplantemp TO FAKTPLAN.
      FIND FIRST FAKTURERAD WHERE FAKTURERAD.FAKTNR = infakplannr AND FAKTURERAD.FDELNR = fdelnrvar
      EXCLUSIVE-LOCK NO-ERROR.
      BUFFER-COPY faktureradtemp TO FAKTURERAD.
   END.
   FIND CURRENT FAKTPLAN NO-LOCK NO-ERROR.
   FIND CURRENT FAKTURERAD NO-LOCK NO-ERROR.
   FOR EACH FAKTUPPARB WHERE FAKTUPPARB.FAKTNR = FAKTPLAN.FAKTNR AND FAKTUPPARB.VFAKTNR = 0 EXCLUSIVE-LOCK:
      DELETE FAKTUPPARB.
   END.
   FOR EACH faktupparbtemp WHERE faktupparbtemp.FAKTNR = FAKTPLAN.FAKTNR AND faktupparbtemp.VFAKTNR = 0 NO-LOCK:
      CREATE FAKTUPPARB.
      BUFFER-COPY faktupparbtemp TO FAKTUPPARB.
   END.
   FOR EACH FAKTSTART WHERE FAKTSTART.FAKTNR = FAKTPLAN.FAKTNR AND FAKTSTART.VFAKTNR = 0 EXCLUSIVE-LOCK:
      DELETE FAKTSTART.
   END.
   FOR EACH faktstarttemp WHERE faktstarttemp.FAKTNR = FAKTPLAN.FAKTNR NO-LOCK:
      CREATE FAKTSTART.
      BUFFER-COPY faktstarttemp TO FAKTSTART.
   END.
   RELEASE FAKTSTART NO-ERROR.
   RELEASE FAKTUPPARB NO-ERROR.   
END.
PROCEDURE momsbortk_UI:
   DEFINE INPUT PARAMETER infakplannr           AS INTEGER NO-UNDO.
   DEFINE INPUT PARAMETER fdelnrvar             AS INTEGER NO-UNDO.
   DO TRANSACTION:
      FIND FIRST FAKTKRED WHERE FAKTKRED.FAKTNR = infakplannr AND FAKTKRED.FDELNR = fdelnrvar
      EXCLUSIVE-LOCK NO-ERROR.
      FAKTKRED.PRELGOD = FALSE.
   END.
   OPEN QUERY faktkontq FOR EACH FAKTINTAKTKONTKRED WHERE 
   FAKTINTAKTKONTKRED.FAKTNR = infakplannr AND  
   FAKTINTAKTKONTKRED.FDELNR = fdelnrvar AND 
   FAKTINTAKTKONTKRED.VKREDIT = 0 NO-LOCK.
   DO TRANSACTION:
      GET FIRST faktkontq EXCLUSIVE-LOCK.
      DO WHILE AVAILABLE(FAKTINTAKTKONTKRED):
         DELETE FAKTINTAKTKONTKRED.
         GET NEXT faktkontq EXCLUSIVE-LOCK.
      END.
   END.
   OPEN QUERY faktkundq FOR EACH FAKTKUNDKONTOKRED WHERE 
   FAKTKUNDKONTOKRED.FAKTNR = infakplannr AND  
   FAKTKUNDKONTOKRED.FDELNR = fdelnrvar AND 
   FAKTKUNDKONTOKRED.VKREDIT = 0 NO-LOCK.
   DO TRANSACTION:
      GET FIRST faktkundq EXCLUSIVE-LOCK.
      DO WHILE AVAILABLE(FAKTKUNDKONTOKRED):
         DELETE FAKTKUNDKONTOKRED.
         GET NEXT faktkundq EXCLUSIVE-LOCK.
      END.
   END.
   OPEN QUERY faktmomsq FOR EACH FAKTMOMSKRED WHERE 
   FAKTMOMSKRED.FAKTNR = infakplannr AND  
   FAKTMOMSKRED.FDELNR = fdelnrvar AND 
   FAKTMOMSKRED.VKREDIT = 0 NO-LOCK.
   DO TRANSACTION:
      GET FIRST faktmomsq EXCLUSIVE-LOCK.
      DO WHILE AVAILABLE(FAKTMOMSKRED):
         DELETE FAKTMOMSKRED.
         GET NEXT faktmomsq EXCLUSIVE-LOCK.
      END.
   END.
   RELEASE FAKTKRED NO-ERROR.
END PROCEDURE.
PROCEDURE momsbort_UI:
   DEFINE INPUT PARAMETER infakplannr           AS INTEGER NO-UNDO.
   DEFINE INPUT PARAMETER fdelnrvar             AS INTEGER NO-UNDO.
   DEFINE INPUT PARAMETER fribortvar AS LOGICAL NO-UNDO.
   DO TRANSACTION:
      FIND FIRST FAKTURERAD WHERE FAKTURERAD.FAKTNR = infakplannr AND FAKTURERAD.FDELNR = fdelnrvar
      EXCLUSIVE-LOCK NO-ERROR.
      ASSIGN
      FAKTURERAD.ORESUTJ = 0
      FAKTURERAD.MOMSBELOPP = 0
      FAKTURERAD.PRELGOD = FALSE.
   END.
   OPEN QUERY faktkontq FOR EACH FAKTINTAKTKONT WHERE 
   FAKTINTAKTKONT.FAKTNR = infakplannr AND  
   FAKTINTAKTKONT.FDELNR = fdelnrvar AND 
   FAKTINTAKTKONT.VFAKTNR = 0 NO-LOCK.
   DO TRANSACTION:
      GET FIRST faktkontq EXCLUSIVE-LOCK.
      DO WHILE AVAILABLE(FAKTINTAKTKONT):
         DELETE FAKTINTAKTKONT.
         GET NEXT faktkontq EXCLUSIVE-LOCK.
      END.
   END.
   OPEN QUERY faktkundq FOR EACH FAKTKUNDKONTO WHERE 
   FAKTKUNDKONTO.FAKTNR = infakplannr AND  
   FAKTKUNDKONTO.FDELNR = fdelnrvar AND 
   FAKTKUNDKONTO.VFAKTNR = 0 NO-LOCK.
   DO TRANSACTION:
      GET FIRST faktkundq EXCLUSIVE-LOCK.
      DO WHILE AVAILABLE(FAKTKUNDKONTO):
         DELETE FAKTKUNDKONTO.
         GET NEXT faktkundq EXCLUSIVE-LOCK.
      END.
   END.
   OPEN QUERY faktmomsq FOR EACH FAKTMOMS WHERE 
   FAKTMOMS.FAKTNR = infakplannr AND  
   FAKTMOMS.FDELNR = fdelnrvar AND 
   FAKTMOMS.VFAKTNR = 0 NO-LOCK.
   DO TRANSACTION:
      GET FIRST faktmomsq EXCLUSIVE-LOCK.
      DO WHILE AVAILABLE(FAKTMOMS):
         DELETE FAKTMOMS.
         GET NEXT faktmomsq EXCLUSIVE-LOCK.
      END.
   END.
   RELEASE FAKTURERAD NO-ERROR.
END PROCEDURE.
PROCEDURE favb_UI:
   DEFINE INPUT PARAMETER infakplannr           AS INTEGER NO-UNDO.
   DO TRANSACTION:
      FIND FIRST FAKTPLAN WHERE FAKTPLAN.FAKTNR = infakplannr EXCLUSIVE-LOCK NO-ERROR.
      FAKTPLAN.SLUTFAKT = FALSE.
   END.
   FOR EACH FAKTAONR WHERE FAKTAONR.FAKTNR = infakplannr NO-LOCK:
      FIND FIRST FAKTKOLL WHERE FAKTKOLL.FAKTNR = infakplannr AND           
      FAKTKOLL.AONR = FAKTAONR.AONR  AND
      FAKTKOLL.DELNR = FAKTAONR.DELNR 
      USE-INDEX FAKTNR EXCLUSIVE-LOCK NO-ERROR.
      IF FAKTKOLL.SLUTFAKT = FALSE THEN FAKTKOLL.SLUTFAKT = FAKTPLAN.SLUTFAKT.                 
   END.         
   RELEASE FAKTPLAN NO-ERROR.
   RELEASE FAKTKOLL NO-ERROR.
END PROCEDURE.
PROCEDURE overdatum_UI:
   DEFINE INPUT PARAMETER odatum AS DATE NO-UNDO.
   DEFINE INPUT PARAMETER kodvar AS CHARACTER NO-UNDO.
   DEFINE OUTPUT PARAMETER vareqdag AS INTEGER NO-UNDO.
   FIND FIRST OVERAVTAB WHERE OVERAVTAB.DATUM = odatum AND 
   OVERAVTAB.KOD = kodvar USE-INDEX ODATUM NO-LOCK NO-ERROR.
   IF AVAILABLE OVERAVTAB THEN DO:
      ASSIGN vareqdag = OVERAVTAB.EQDAG.
   END. 
   ELSE DO:
      ASSIGN vareqdag = WEEKDAY(odatum).
   END.
END PROCEDURE. 
PROCEDURE avslutkoll_UI:
   DEFINE INPUT PARAMETER aonrvar AS CHARACTER NO-UNDO.
   DEFINE INPUT PARAMETER delnrvar AS INTEGER NO-UNDO.
   DEFINE OUTPUT PARAMETER feltext AS CHARACTER NO-UNDO.
   FIND FIRST AONRTAB WHERE AONRTAB.AONR = aonrvar AND
   AONRTAB.DELNR = delnrvar NO-LOCK NO-ERROR.
   IF AONRTAB.AONRAVDATUM = 01/01/91 THEN feltext = "Denn post är inte upparbetad till rätt nivå för fakturering.".
   ELSE IF AONRTAB.AONRAVDATUM > TODAY THEN feltext = "Denn post är inte upparbetad till rätt nivå för fakturering.".
   FIND FIRST AONRTIDLAGE WHERE 
   AONRTIDLAGE.AONR = AONRTAB.AONR AND 
   AONRTIDLAGE.DELNR = AONRTAB.DELNR AND
   AONRTIDLAGE.IDTIDLAG = "Slutfakturering"
   NO-LOCK NO-ERROR.
   IF AVAILABLE AONRTIDLAGE THEN feltext = "".
END PROCEDURE.
PROCEDURE hamtfriK_UI:
   DEFINE INPUT PARAMETER infakplannr           AS INTEGER NO-UNDO.
   DEFINE INPUT PARAMETER fdelnrvar             AS INTEGER NO-UNDO.
   DEFINE OUTPUT PARAMETER TABLE FOR faktfriatemp.
   EMPTY TEMP-TABLE faktfriatemp NO-ERROR.
   FOR EACH FAKTFRIAKRED WHERE FAKTFRIAKRED.FAKTNR = infakplannr AND FAKTFRIAKRED.FDELNR = fdelnrvar NO-LOCK:
      CREATE faktfriatemp.
      BUFFER-COPY FAKTFRIAKRED TO faktfriatemp.
      faktfriatemp.ROWFRIA = ROWID(FAKTFRIAKRED).
   END.
END PROCEDURE.
PROCEDURE hamtfri_UI:
   DEFINE INPUT PARAMETER infakplannr           AS INTEGER NO-UNDO.
   DEFINE INPUT PARAMETER fdelnrvar             AS INTEGER NO-UNDO.
   DEFINE OUTPUT PARAMETER TABLE FOR faktfriatemp.
   EMPTY TEMP-TABLE faktfriatemp NO-ERROR.
   FOR EACH FAKTFRIA WHERE FAKTFRIA.FAKTNR = infakplannr AND FAKTFRIA.FDELNR = fdelnrvar NO-LOCK:
      CREATE faktfriatemp.
      BUFFER-COPY FAKTFRIA TO faktfriatemp.
      faktfriatemp.ROWFRIA = ROWID(FAKTFRIA).
   END.
END PROCEDURE.

PROCEDURE fribortk_UI:
   DEFINE INPUT PARAMETER frirow AS ROWID NO-UNDO.  
   DO TRANSACTION:
     FIND FIRST FAKTFRIAKRED WHERE ROWID(FAKTFRIAKRED) = frirow EXCLUSIVE-LOCK NO-ERROR.
     IF FAKTFRIAKRED.TYP = "MATRL" THEN DO:
        OPEN QUERY frimtrlq FOR EACH FAKTMTRLKRED WHERE FAKTMTRLKRED.FAKTNR = FAKTFRIAKRED.FAKTNR AND
        FAKTMTRLKRED.FDELNR = FAKTFRIAKRED.FDELNR AND FAKTMTRLKRED.LOPNR = FAKTFRIAKRED.LOPNR NO-LOCK.
        GET FIRST frimtrlq EXCLUSIVE-LOCK.  
        DO WHILE AVAILABLE(FAKTMTRLKRED):
           DELETE FAKTMTRLKRED.    
           GET NEXT frimtrlq EXCLUSIVE-LOCK.
        END.
     END.
     DELETE FAKTFRIAKRED.
 END.
END PROCEDURE.
PROCEDURE fribort_UI:
   DEFINE INPUT PARAMETER frirow AS ROWID NO-UNDO.  
   DO TRANSACTION:
     FIND FIRST FAKTFRIA WHERE ROWID(FAKTFRIA) = frirow EXCLUSIVE-LOCK NO-ERROR.
     IF FAKTFRIA.TYP = "MATRL" THEN DO:
        OPEN QUERY frimtrlq FOR EACH FAKTMTRL WHERE FAKTMTRL.FAKTNR = FAKTFRIA.FAKTNR AND
        FAKTMTRL.FDELNR = FAKTFRIA.FDELNR AND FAKTMTRL.LOPNR = FAKTFRIA.LOPNR NO-LOCK.
        GET FIRST frimtrlq EXCLUSIVE-LOCK.  
        DO WHILE AVAILABLE(FAKTMTRL):
           DELETE FAKTMTRL.    
           GET NEXT frimtrlq EXCLUSIVE-LOCK.
        END.
     END.
     DELETE FAKTFRIA.
 END.
END PROCEDURE.


PROCEDURE hamtfaktk_UI:
   DEFINE INPUT PARAMETER infakplannr           AS INTEGER NO-UNDO.
   DEFINE INPUT PARAMETER fdelnrvar             AS INTEGER NO-UNDO.
   DEFINE INPUT PARAMETER  vartyp               AS INTEGER NO-UNDO.
   DEFINE OUTPUT PARAMETER TABLE FOR faktaonrtemp.
   DEFINE OUTPUT PARAMETER TABLE FOR faktfriatemp.
   DEFINE OUTPUT PARAMETER TABLE FOR kundregeltemp.
   DEFINE OUTPUT PARAMETER TABLE FOR faktintakkontotemp.
   DEFINE OUTPUT PARAMETER TABLE FOR kundbeftemp.
   DEFINE OUTPUT PARAMETER TABLE FOR faktupparbtemp.
   DEFINE OUTPUT PARAMETER TABLE FOR faktstarttemp.
   DEFINE OUTPUT PARAMETER TABLE FOR kundovertemp.
   EMPTY TEMP-TABLE faktaonrtemp NO-ERROR.
   EMPTY TEMP-TABLE faktfriatemp NO-ERROR.
   EMPTY TEMP-TABLE kundregeltemp NO-ERROR.
   EMPTY TEMP-TABLE faktintakkontotemp NO-ERROR.   
   EMPTY TEMP-TABLE kundbeftemp NO-ERROR.
   EMPTY TEMP-TABLE faktupparbtemp NO-ERROR.
   EMPTY TEMP-TABLE faktstarttemp NO-ERROR.
   EMPTY TEMP-TABLE kundovertemp NO-ERROR.
   FIND FIRST FAKTPLAN WHERE FAKTPLAN.FAKTNR = infakplannr NO-LOCK NO-ERROR.
   FOR EACH FAKTAONR WHERE FAKTAONR.FAKTNR = FAKTPLAN.FAKTNR NO-LOCK:
      CREATE faktaonrtemp.
      BUFFER-COPY FAKTAONR TO faktaonrtemp.
      {FAKTAONRSTOPP.I}
   END.
   FOR EACH FAKTFRIAKRED WHERE FAKTFRIAKRED.FAKTNR = FAKTPLAN.FAKTNR AND FAKTFRIAKRED.FDELNR = fdelnrvar NO-LOCK:
      CREATE faktfriatemp.
      BUFFER-COPY FAKTFRIAKRED TO faktfriatemp.
      faktfriatemp.ROWFRIA = ROWID(FAKTFRIAKRED).
   END.
   FOR EACH FAKTINTAKTKONTKRED WHERE FAKTINTAKTKONTKRED.FAKTNR = FAKTPLAN.FAKTNR AND FAKTINTAKTKONTKRED.FDELNR = fdelnrvar NO-LOCK:
      CREATE faktintakkontotemp.
      BUFFER-COPY FAKTINTAKTKONTKRED TO faktintakkontotemp.
   END.
   
   FOR EACH FAKTBEF WHERE FAKTBEF.FAKTNR = FAKTPLAN.FAKTNR NO-LOCK:
      CREATE kundbeftemp.
      BUFFER-COPY FAKTBEF TO kundbeftemp.
      FOR EACH kundbeftemp,
      EACH BEFATTNINGSTAB WHERE BEFATTNINGSTAB.BEFATTNING = kundbeftemp.BEFATTNING NO-LOCK:
         kundbeftemp.VIBEFATTNING = BEFATTNINGSTAB.NAMN.      
      END.      
   END.
   FOR EACH FAKTUPPARBKRED WHERE FAKTUPPARBKRED.FAKTNR = FAKTPLAN.FAKTNR NO-LOCK:
      CREATE faktupparbtemp.
      BUFFER-COPY FAKTUPPARBKRED TO faktupparbtemp.
   END.
   FOR EACH FAKTSTARTKRED WHERE FAKTSTARTKRED.FAKTNR = FAKTPLAN.FAKTNR NO-LOCK:
      CREATE faktstarttemp.
      BUFFER-COPY FAKTSTARTKRED TO faktstarttemp.
   END.
   FOR EACH FAKTOVER WHERE FAKTOVER.FAKTNR = FAKTPLAN.FAKTNR NO-LOCK.
      CREATE kundovertemp.  
      BUFFER-COPY FAKTOVER TO kundovertemp.                         
   END.
   FOR EACH kundovertemp,
   EACH OVERTEXTFAKT WHERE OVERTEXTFAKT.OTEXTID = kundovertemp.OTEXTID NO-LOCK:
      kundovertemp.OTEXT = OVERTEXTFAKT.OTEXT.      
   END.

   ASSIGN
   nytab      = "kundregeltemp"
   orginaltab = "FAKTREGLER".
   
   kommandoquery = "FAKTREGLER.FAKTNR = " + STRING(infakplannr).
   kommandoquery = "FOR EACH " +  orginaltab + " WHERE " + kommandoquery + " NO-LOCK".       
   /*BUGG 9.1c FIX*/
   ASSIGN extratemptabh = TEMP-TABLE kundregeltemp:DEFAULT-BUFFER-HANDLE.
   RUN dynquery_UI (INPUT FALSE,INPUT FALSE).                  
   RUN objdelete_UI.
END PROCEDURE.
PROCEDURE hamtfaktu_UI:
   DEFINE INPUT PARAMETER infakplannr           AS INTEGER NO-UNDO.
   DEFINE INPUT PARAMETER fdelnrvar             AS INTEGER NO-UNDO.
   DEFINE OUTPUT PARAMETER TABLE FOR faktureradtemp.
   EMPTY TEMP-TABLE faktureradtemp NO-ERROR.
   FIND FIRST FAKTURERAD WHERE FAKTURERAD.FAKTNR = infakplannr AND  FAKTURERAD.FDELNR = fdelnrvar NO-LOCK NO-ERROR.
   CREATE faktureradtemp.
   BUFFER-COPY FAKTURERAD TO faktureradtemp.   
END PROCEDURE.
PROCEDURE hamtfaktku_UI:
   DEFINE INPUT PARAMETER infakplannr           AS INTEGER NO-UNDO.
   DEFINE INPUT PARAMETER fdelnrvar             AS INTEGER NO-UNDO.
   DEFINE OUTPUT PARAMETER TABLE FOR efaktkredtemp.
   EMPTY TEMP-TABLE efaktkredtemp NO-ERROR.
   FIND FIRST FAKTKRED WHERE FAKTKRED.FAKTNR = infakplannr AND FAKTKRED.FDELNR = fdelnrvar NO-LOCK NO-ERROR.
   CREATE efaktkredtemp.
   BUFFER-COPY FAKTKRED TO efaktkredtemp.   
END PROCEDURE.
PROCEDURE hamtallfakturerad_UI:
   DEFINE INPUT PARAMETER infakplannr           AS INTEGER NO-UNDO.
   DEFINE OUTPUT PARAMETER TABLE FOR allafaktureradtemp.
   DEFINE OUTPUT PARAMETER TABLE FOR kredallafaktureradtemp.
   EMPTY TEMP-TABLE allafaktureradtemp NO-ERROR.  
   FOR EACH FAKTURERAD WHERE FAKTURERAD.FAKTNR = infakplannr NO-LOCK:
      CREATE allafaktureradtemp.
      BUFFER-COPY FAKTURERAD TO allafaktureradtemp.
   END.
   
   FOR EACH FAKTKRED WHERE FAKTKRED.FAKTNR = infakplannr AND FAKTKRED.VKREDIT NE 0 NO-LOCK:
      CREATE kredallafaktureradtemp.
      ASSIGN
      kredallafaktureradtemp.FAKTNR = infakplannr 
      kredallafaktureradtemp.BOKDATUM = FAKTKRED.BOKDATUM 
      kredallafaktureradtemp.KREDIT = FAKTKRED.TOTPRIS.
   END.
   
END PROCEDURE.
PROCEDURE hamtfakt_UI:
   DEFINE INPUT PARAMETER infakplannr           AS INTEGER NO-UNDO.
   DEFINE INPUT PARAMETER fdelnrvar             AS INTEGER NO-UNDO.
   DEFINE INPUT PARAMETER  vartyp               AS INTEGER NO-UNDO.
   DEFINE INPUT PARAMETER FILL-IN_SLUTFAKT      AS LOGICAL NO-UNDO.
   DEFINE OUTPUT PARAMETER aonrstart AS LOGICAL NO-UNDO.
   DEFINE OUTPUT PARAMETER aonrslut AS LOGICAL NO-UNDO.
   DEFINE OUTPUT PARAMETER tidfaktvar AS DECIMAL NO-UNDO.
   DEFINE OUTPUT PARAMETER tidmomsvar AS DECIMAL NO-UNDO.
   DEFINE OUTPUT PARAMETER TABLE FOR faktureradtemp.
   DEFINE OUTPUT PARAMETER TABLE FOR faktaonrtemp.
   DEFINE OUTPUT PARAMETER TABLE FOR faktfriatemp.
   DEFINE OUTPUT PARAMETER TABLE FOR kundregeltemp.
   DEFINE OUTPUT PARAMETER TABLE FOR faktintakkontotemp.
   DEFINE OUTPUT PARAMETER TABLE FOR kundbeftemp.
   DEFINE OUTPUT PARAMETER TABLE FOR faktupparbtemp.
   DEFINE OUTPUT PARAMETER TABLE FOR faktstarttemp.
   DEFINE OUTPUT PARAMETER TABLE FOR kundovertemp.
   EMPTY TEMP-TABLE kundovertemp NO-ERROR.
   EMPTY TEMP-TABLE faktureradtemp NO-ERROR.
   EMPTY TEMP-TABLE faktaonrtemp NO-ERROR.
   EMPTY TEMP-TABLE faktfriatemp NO-ERROR.
   EMPTY TEMP-TABLE faktintakkontotemp NO-ERROR.
   EMPTY TEMP-TABLE kundregeltemp NO-ERROR.
   EMPTY TEMP-TABLE kundbeftemp NO-ERROR.
   EMPTY TEMP-TABLE faktupparbtemp NO-ERROR.
   EMPTY TEMP-TABLE faktstarttemp NO-ERROR.
   FIND FIRST FAKTPLAN WHERE FAKTPLAN.FAKTNR = infakplannr NO-LOCK NO-ERROR.
   FIND FIRST FAKTURERAD WHERE FAKTURERAD.FAKTNR = infakplannr AND  FAKTURERAD.FDELNR = fdelnrvar NO-LOCK NO-ERROR.
   CREATE faktureradtemp.
   BUFFER-COPY FAKTURERAD TO faktureradtemp.
   FOR EACH FAKTAONR WHERE FAKTAONR.FAKTNR = FAKTPLAN.FAKTNR NO-LOCK:
      CREATE faktaonrtemp.
      BUFFER-COPY FAKTAONR TO faktaonrtemp.
      {FAKTAONRSTOPP.I}
   END.
   FOR EACH FAKTFRIA WHERE FAKTFRIA.FAKTNR = FAKTPLAN.FAKTNR AND FAKTFRIA.FDELNR = fdelnrvar NO-LOCK:
      CREATE faktfriatemp.
      BUFFER-COPY FAKTFRIA TO faktfriatemp.
      faktfriatemp.ROWFRIA = ROWID(FAKTFRIA).
   END.
   FOR EACH FAKTINTAKTKONT WHERE FAKTINTAKTKONT.FAKTNR = FAKTPLAN.FAKTNR AND FAKTINTAKTKONT.FDELNR = fdelnrvar NO-LOCK:
      CREATE faktintakkontotemp.
      BUFFER-COPY FAKTINTAKTKONT TO faktintakkontotemp.
   END.
   
   FOR EACH FAKTBEF WHERE FAKTBEF.FAKTNR = FAKTPLAN.FAKTNR NO-LOCK:
      CREATE kundbeftemp.
      BUFFER-COPY FAKTBEF TO kundbeftemp.
      FOR EACH kundbeftemp,
      EACH BEFATTNINGSTAB WHERE BEFATTNINGSTAB.BEFATTNING = kundbeftemp.BEFATTNING NO-LOCK:
         kundbeftemp.VIBEFATTNING = BEFATTNINGSTAB.NAMN.      
      END.      
   END.
   FOR EACH FAKTUPPARB WHERE FAKTUPPARB.FAKTNR = FAKTPLAN.FAKTNR NO-LOCK:
      CREATE faktupparbtemp.
      BUFFER-COPY FAKTUPPARB TO faktupparbtemp.
   END.
   FOR EACH FAKTSTART WHERE FAKTSTART.FAKTNR = FAKTPLAN.FAKTNR NO-LOCK:
      CREATE faktstarttemp.
      BUFFER-COPY FAKTSTART TO faktstarttemp.
   END.
   FOR EACH FAKTOVER WHERE FAKTOVER.FAKTNR = FAKTPLAN.FAKTNR NO-LOCK.
      CREATE kundovertemp.  
      BUFFER-COPY FAKTOVER TO kundovertemp.                         
   END.
   FOR EACH kundovertemp,
   EACH OVERTEXTFAKT WHERE OVERTEXTFAKT.OTEXTID = kundovertemp.OTEXTID NO-LOCK:
      kundovertemp.OTEXT = OVERTEXTFAKT.OTEXT.      
   END.

   ASSIGN
   nytab      = "kundregeltemp"
   orginaltab = "FAKTREGLER".
   
   kommandoquery = "FAKTREGLER.FAKTNR = " + STRING(infakplannr).
   kommandoquery = "FOR EACH " +  orginaltab + " WHERE " + kommandoquery + " NO-LOCK".       
   /*BUGG 9.1c FIX*/
   ASSIGN extratemptabh = TEMP-TABLE kundregeltemp:DEFAULT-BUFFER-HANDLE.
   RUN dynquery_UI (INPUT FALSE,INPUT FALSE).            
   
   ASSIGN
   aonrstart = FALSE
   aonrslut = TRUE.   
   IF vartyp = 6 OR vartyp = 7 THEN DO:   
   END.
   ELSE DO:  
      OPEN QUERY aonrq FOR EACH AONRTAB WHERE AONRTAB.FAKTNR = FAKTPLAN.FAKTNR 
      NO-LOCK.
      GET FIRST aonrq NO-LOCK.   
      DO WHILE AVAILABLE(AONRTAB):
         IF AONRTAB.STARTDATUM NE ? THEN aonrstart = TRUE.
         IF AONRTAB.AONRAVDATUM = 01/01/91 THEN aonrslut = FALSE.
         GET NEXT aonrq NO-LOCK.
      END.         
      CLOSE QUERY aonrq.
   END.
   ASSIGN                  
   tidfaktvar = 0
   tidmomsvar = 0.
   IF FILL-IN_SLUTFAKT = FALSE THEN DO:
      RETURN.
   END.
   OPEN QUERY faktuq FOR EACH FAKTURERAD WHERE 
   FAKTURERAD.FAKTNR = FAKTPLAN.FAKTNR USE-INDEX FAKTNR NO-LOCK.
   GET FIRST faktuq NO-LOCK.   
   DO WHILE AVAILABLE(FAKTURERAD):
      IF FAKTURERAD.FDELNR NE fdelnrvar THEN DO:
         ASSIGN                  
         tidmomsvar = tidmomsvar + FAKTURERAD.MOMSBELOPP
         tidfaktvar =  tidfaktvar + FAKTURERAD.TOTPRIS. 
      END.     
      GET NEXT faktuq NO-LOCK.
   END.    
   RUN objdelete_UI.
END PROCEDURE.

