/*FAOBER.P*/
&Scoped-define NEW NEW                          
{FAKTTEMP.I}
&Scoped-define NEW NEW
{GLOBVAR2DEL1.I}
DEFINE VARIABLE musz AS LOGICAL NO-UNDO.
/* ************************  Function Implementations ***************** */


FUNCTION klockan100 RETURNS DECIMAL
  ( INPUT ber60 AS DECIMAL ):
  RETURN  (TRUNCATE(ber60,0) * 3600 + (ber60 - TRUNCATE(ber60,0)) * 100 * 60) / 3600.

END FUNCTION.

FUNCTION klockan60 RETURNS DECIMAL
  ( INPUT ber100 AS DECIMAL ):
  RETURN TRUNCATE(ber100,0) + ((ber100 - TRUNCATE(ber100,0)) / 100) * 60 . 
END FUNCTION.


FUNCTION runda RETURNS DECIMAL
  ( INPUT varedin AS DECIMAL) :
  RETURN ROUND(varedin,0).   /* Function return value. */
END FUNCTION.

DEFINE INPUT PARAMETER cglobforetag LIKE FORETAG.FORETAG NO-UNDO. 
DEFINE INPUT PARAMETER faktrec AS RECID NO-UNDO.     
DEFINE INPUT PARAMETER FILL-IN-TOMDAT AS DATE NO-UNDO.
DEFINE INPUT PARAMETER aonrvar AS CHARACTER NO-UNDO.
DEFINE INPUT PARAMETER delnrvar AS INTEGER NO-UNDO.
DEFINE INPUT-OUTPUT PARAMETER kollvecko LIKE TIDREGITAB.VECKOKORD NO-UNDO.
DEFINE INPUT-OUTPUT PARAMETER TABLE FOR tidtemp.
DEFINE INPUT-OUTPUT PARAMETER TABLE FOR extrasum.


FIND FAKTPLAN WHERE RECID(FAKTPLAN) = faktrec NO-LOCK NO-ERROR.
{FAOBERSTART.I}
{FAOBERU.I}

