/*FASPARA.P*/
&Scoped-define NEW NEW
{FAKTTEMP.I}

DEFINE INPUT PARAMETER skarp AS INTEGER NO-UNDO.
DEFINE INPUT PARAMETER faktrec AS RECID NO-UNDO.
DEFINE INPUT PARAMETER vartyp AS INTEGER NO-UNDO.
DEFINE INPUT PARAMETER FILL-IN_SLUTFAKT AS LOGICAL NO-UNDO.
DEFINE INPUT PARAMETER hamttid AS LOGICAL NO-UNDO.
DEFINE INPUT PARAMETER hamtkost AS LOGICAL NO-UNDO.  
DEFINE INPUT PARAMETER faktanmrec AS RECID NO-UNDO.
DEFINE INPUT PARAMETER kollvecko LIKE TIDREGITAB.VECKOKORD NO-UNDO.
DEFINE INPUT PARAMETER TABLE FOR kosttemp.
DEFINE INPUT PARAMETER TABLE FOR sumtidtemp.
DO TRANSACTION:
   FIND FAKTPLAN WHERE RECID(FAKTPLAN) = faktrec EXCLUSIVE-LOCK NO-ERROR.
END.
FIND CURRENT FAKTPLAN NO-LOCK.
FIND FAKTURERAD WHERE RECID(FAKTURERAD) = faktanmrec NO-LOCK NO-ERROR.
{FASPARA.I}
