/*FPRISKOL.P*/
DEFINE INPUT PARAMETER varfaktnummer LIKE FAKTPLAN.FAKTNR NO-UNDO.
DEFINE OUTPUT PARAMETER musz AS LOGICAL NO-UNDO.
DEFINE OUTPUT PARAMETER feltextvar AS CHARACTER NO-UNDO. 

FIND FIRST FORETAG NO-LOCK NO-ERROR.
Guru.Konstanter:globforetag = FORETAG.FORETAG.
FIND FIRST FAKTPLAN WHERE FAKTPLAN.FAKTNR = varfaktnummer NO-LOCK NO-ERROR.
IF Guru.Konstanter:globforetag = "ESAN" THEN DO:
   /*PETER N. 00/06/30*/
   /*KOLL OM RÄTT PRISLISTA LIGGER PÅ FAKTPLAN*/
   /*KOMMER PRISLISTAN ÄR PRISLISTAN EJ DENNSAMM FÖR PLANEN SOM FÖR FAKTURAN TAS DEN BORT*/
   RUN prislkoll_UI.
END.   
OPEN QUERY fpq FOR EACH FAKTPRISLISTA WHERE FAKTPRISLISTA.FAKTNR = FAKTPLAN.FAKTNR NO-LOCK.
GET FIRST fpq NO-LOCK.
IF NOT AVAILABLE FAKTPRISLISTA THEN DO:
   /*KOLLA ATT ALLA BEFATTNINGAR HAR PRIS*/
   RUN faktpris_UI.  
   /*KOLLA ATT ALLA BEFATTNINGAR HAR ÖVERTIDSPRIS*/
   RUN faktover_UI.
   RETURN.
END.   
RUN faktover_UI.
PROCEDURE prislkoll_UI :
   IF FAKTPLAN.VISAONR BEGINS "S" THEN RETURN.
   FIND FIRST DEFPRISLISTA WHERE DEFPRISLISTA.PRISNUM = FAKTPLAN.PRISNUM AND 
   DEFPRISLISTA.OVER = FALSE 
   NO-LOCK NO-ERROR.
   IF AVAILABLE DEFPRISLISTA THEN DO:
      FIND FIRST FAKTPRISLISTA WHERE FAKTPRISLISTA.FAKTNR = FAKTPLAN.FAKTNR AND
      FAKTPRISLISTA.OVER = FALSE
      NO-LOCK NO-ERROR.
      IF AVAILABLE FAKTPRISLISTA THEN DO:
         IF FAKTPRISLISTA.PRISID = DEFPRISLISTA.PRISID THEN musz = musz.
         ELSE DO:            
            OPEN QUERY faktbefq
            FOR EACH FAKTBEF WHERE FAKTBEF.FAKTNR = FAKTPLAN.FAKTNR 
            USE-INDEX FAKTBEF NO-LOCK.         
            DO TRANSACTION:       
               GET FIRST faktbefq EXCLUSIVE-LOCK.
               IF AVAILABLE FAKTBEF THEN DELETE FAKTBEF.    
            END.
            REPEAT:  
               DO TRANSACTION:
                  GET NEXT faktbefq EXCLUSIVE-LOCK.
                  IF AVAILABLE FAKTBEF THEN DELETE FAKTBEF.    
                  ELSE LEAVE.      
               END.         
            END.
            DO TRANSACTION:
               FIND CURRENT FAKTPRISLISTA EXCLUSIVE-LOCK NO-ERROR.
               DELETE FAKTPRISLISTA.
            END.
         END.
      END.
   END.   
   FIND FIRST DEFPRISLISTA WHERE DEFPRISLISTA.PRISNUM = FAKTPLAN.PRISNUMO AND 
   DEFPRISLISTA.OVER = TRUE 
   NO-LOCK NO-ERROR.
   IF AVAILABLE DEFPRISLISTA THEN DO:
      FIND FIRST FAKTPRISLISTA WHERE FAKTPRISLISTA.FAKTNR = FAKTPLAN.FAKTNR AND
      FAKTPRISLISTA.OVER = TRUE
      NO-LOCK NO-ERROR.
      IF AVAILABLE FAKTPRISLISTA THEN DO:
         IF FAKTPRISLISTA.PRISID = DEFPRISLISTA.PRISID THEN musz = musz.
         ELSE DO:
            OPEN QUERY faktoverq
            FOR EACH FAKTOVER WHERE FAKTOVER.FAKTNR = FAKTPLAN.FAKTNR 
            USE-INDEX FAKTOVER NO-LOCK.                 
            DO TRANSACTION:       
               GET FIRST faktoverq EXCLUSIVE-LOCK.
               IF AVAILABLE FAKTOVER THEN DELETE FAKTOVER.    
            END.
            REPEAT:  
               DO TRANSACTION:
                  GET NEXT faktoverq EXCLUSIVE-LOCK.
                  IF AVAILABLE FAKTOVER THEN DELETE FAKTOVER.    
                  ELSE LEAVE.      
               END.         
            END.
            DO TRANSACTION:
               FIND CURRENT FAKTPRISLISTA EXCLUSIVE-LOCK NO-ERROR.
               DELETE FAKTPRISLISTA.
            END.
         END.
      END.
   END.
END PROCEDURE.
PROCEDURE faktpris_UI :
   IF Guru.Konstanter:globforetag = "ESAN" THEN DO:
      /*HÄMTAR IN RÄTT PRISLISTA */
      /*FINNS INGEN PRISLISTA TAS PRISERNA FRÅN KUND*/
      IF FAKTPLAN.PRISNUM = 0 THEN musz = TRUE.
      ELSE RUN prislistnum_UI.
      IF musz = TRUE THEN musz = FALSE.
      ELSE RETURN.
   END.                    
   OPEN QUERY kundbefq FOR EACH KUNDBEF WHERE KUNDBEF.BESTID = FAKTPLAN.BESTID 
   USE-INDEX KUNDBEF NO-LOCK.
   GET FIRST kundbefq NO-LOCK.
   IF NOT AVAILABLE KUNDBEF THEN DO:
      musz = TRUE.
      feltextvar = "Denna kund saknar prislistor och kan ej faktureras.". 
      RETURN.
   END.
   DO WHILE AVAILABLE(KUNDBEF):             
      FIND FIRST FAKTBEF WHERE FAKTBEF.FAKTNR = FAKTPLAN.FAKTNR AND
      FAKTBEF.BEFATTNING = KUNDBEF.BEFATTNING USE-INDEX FAKTBEF NO-LOCK NO-ERROR.
      IF NOT AVAILABLE FAKTBEF THEN DO TRANSACTION:
         CREATE FAKTBEF.
         ASSIGN 
         FAKTBEF.FAKTNR = FAKTPLAN.FAKTNR
         FAKTBEF.BEFATTNING = KUNDBEF.BEFATTNING
         FAKTBEF.PRISA = KUNDBEF.PRISA
         FAKTBEF.PRISRES = KUNDBEF.PRISRES.      
      END.
      GET NEXT kundbefq NO-LOCK.
   END.  
   CLOSE QUERY kundbefq.  
   DO TRANSACTION:
      FIND FIRST FAKTPRISLIST WHERE FAKTPRISLISTA.FAKTNR = FAKTPLAN.FAKTNR AND 
      FAKTPRISLISTA.OVER = FALSE
      EXCLUSIVE-LOCK NO-ERROR.   
      FIND FIRST KUNDPRISLIST WHERE KUNDPRISLIST.BESTID = FAKTPLAN.BESTID AND 
      KUNDPRISLIST.OVER = FALSE
      NO-LOCK NO-ERROR.
      IF AVAILABLE KUNDPRISLIST THEN DO:
         IF NOT AVAILABLE FAKTPRISLIST THEN DO:
            CREATE FAKTPRISLISTA.   
            ASSIGN
            FAKTPRISLISTA.FAKTNR = FAKTPLAN.FAKTNR
            FAKTPRISLISTA.OVER = KUNDPRISLIST.OVER
            FAKTPRISLISTA.PRISID = KUNDPRISLIST.PRISID
            FAKTPRISLISTA.FRAGAEJ = FALSE
            FAKTPRISLISTA.STARTDATUM = KUNDPRISLIST.STARTDATUM.
         END.      
         FIND FIRST PRISLISTOVRIGT WHERE 
         PRISLISTOVRIGT.PRISID = KUNDPRISLIST.PRISID NO-LOCK NO-ERROR.
         IF AVAILABLE PRISLISTOVRIGT THEN DO:
            FIND FIRST FAKTREGLER WHERE FAKTREGLER.FAKTNR = FAKTPLAN.FAKTNR
            EXCLUSIVE-LOCK NO-ERROR.
            IF AVAILABLE FAKTREGLER THEN DO:          
               IF FAKTREGLER.TIMRGL = "KUNDENS EGNA" THEN DO:
                  ASSIGN
                  FAKTREGLER.ENTRAK = PRISLISTOVRIGT.ENTRAK 
                  FAKTREGLER.FLERTRAK = PRISLISTOVRIGT.FLERTRAK
                  FAKTREGLER.FRTJPA = PRISLISTOVRIGT.FRTJPA
                  FAKTREGLER.MIL = PRISLISTOVRIGT.MIL
                  FAKTREGLER.MTRLPA = PRISLISTOVRIGT.MTRLPA.
               END.   
            END.
         END.      
      END.   
   END.                       
END PROCEDURE.

PROCEDURE faktover_UI :
   FIND FIRST FAKTOVER WHERE FAKTOVER.FAKTNR = FAKTPLAN.FAKTNR 
   USE-INDEX FAKTOVER NO-LOCK NO-ERROR.
   IF NOT AVAILABLE FAKTOVER THEN DO:
      IF Guru.Konstanter:globforetag = "ESAN" THEN DO:
         /*HÄMTAR IN RÄTT PRISLISTA */
         /*FINNS INGEN PRISLISTA TAS PRISERNA FRÅN KUND*/
         IF FAKTPLAN.PRISNUMO = 0 THEN musz = TRUE.
         ELSE RUN prislistnumo_UI.
         IF musz = TRUE THEN musz = FALSE.
         ELSE RETURN.
      END.
      OPEN QUERY kundoverq FOR EACH KUNDOVER WHERE KUNDOVER.BESTID = FAKTPLAN.BESTID  
      USE-INDEX KUNDOVER NO-LOCK.
      GET FIRST kundoverq NO-LOCK.
      IF NOT AVAILABLE KUNDOVER THEN DO:
         musz = TRUE.
         feltextvar = "Denna kund saknar prislistor och kan ej faktureras.".
         RETURN.
      END.
      DO WHILE AVAILABLE(KUNDOVER) TRANSACTION:               
         CREATE FAKTOVER.   
         ASSIGN 
         FAKTOVER.BEFATTNING = KUNDOVER.BEFATTNING
         FAKTOVER.FAKTNR = FAKTPLAN.FAKTNR
         FAKTOVER.DAGTYP = KUNDOVER.DAGTYP
         FAKTOVER.OTEXTID = KUNDOVER.OTEXTID
         FAKTOVER.EQDAG = KUNDOVER.EQDAG
         FAKTOVER.PRISA = KUNDOVER.PRISA
         FAKTOVER.START = KUNDOVER.START
         FAKTOVER.SLUT = KUNDOVER.SLUT.
         GET NEXT kundoverq NO-LOCK.
      END. 
      CLOSE QUERY kundoverq.
   END.
   DO TRANSACTION:
      FIND FIRST FAKTPRISLIST WHERE FAKTPRISLISTA.FAKTNR = FAKTPLAN.FAKTNR AND 
      FAKTPRISLISTA.OVER = TRUE
      EXCLUSIVE-LOCK NO-ERROR.   
      FIND FIRST KUNDPRISLIST WHERE KUNDPRISLIST.BESTID = FAKTPLAN.BESTID AND 
      KUNDPRISLIST.OVER = TRUE
      NO-LOCK NO-ERROR.
      IF AVAILABLE KUNDPRISLIST THEN DO:
         IF NOT AVAILABLE FAKTPRISLIST THEN DO:
            CREATE FAKTPRISLISTA.   
            ASSIGN
            FAKTPRISLISTA.FAKTNR = FAKTPLAN.FAKTNR
            FAKTPRISLISTA.OVER = KUNDPRISLIST.OVER
            FAKTPRISLISTA.PRISID = KUNDPRISLIST.PRISID
            FAKTPRISLISTA.FRAGAEJ = FALSE
            FAKTPRISLISTA.STARTDATUM = KUNDPRISLIST.STARTDATUM.
         END.
      END.
   END.
   RELEASE FAKTPRISLISTA.     
END PROCEDURE.

PROCEDURE prislistnum_UI :
   FIND FIRST DEFPRISLISTA WHERE DEFPRISLISTA.PRISNUM = FAKTPLAN.PRISNUM AND 
   DEFPRISLISTA.OVER = FALSE 
   NO-LOCK NO-ERROR.
   IF NOT AVAILABLE DEFPRISLISTA THEN DO:
      musz = TRUE.
      RETURN.
   END.     
   OPEN QUERY prisq FOR EACH PRISLISTFAKT WHERE 
   PRISLISTFAKT.PRISID = DEFPRISLISTA.PRISID NO-LOCK.
   GET FIRST prisq NO-LOCK.
   DO WHILE AVAILABLE(PRISLISTFAKT):
      DO TRANSACTION:
         CREATE FAKTBEF.
         ASSIGN 
         FAKTBEF.FAKTNR = FAKTPLAN.FAKTNR
         FAKTBEF.BEFATTNING = PRISLISTFAKT.BEFATTNING
         FAKTBEF.PRISA = PRISLISTFAKT.PRISA
         FAKTBEF.PRISRES = PRISLISTFAKT.PRISRES.             
      END.
      GET NEXT prisq NO-LOCK. 
   END.
   CLOSE QUERY prisq.  
   DO TRANSACTION:
      FIND FIRST FAKTPRISLIST WHERE FAKTPRISLISTA.FAKTNR = FAKTPLAN.FAKTNR AND 
      FAKTPRISLISTA.OVER = DEFPRISLISTA.OVER
      EXCLUSIVE-LOCK NO-ERROR.   
      IF NOT AVAILABLE FAKTPRISLIST THEN CREATE FAKTPRISLISTA.   
      ASSIGN
      FAKTPRISLISTA.FAKTNR = FAKTPLAN.FAKTNR
      FAKTPRISLISTA.OVER = DEFPRISLISTA.OVER
      FAKTPRISLISTA.PRISID = DEFPRISLISTA.PRISID
      FAKTPRISLISTA.FRAGAEJ = FALSE
      FAKTPRISLISTA.STARTDATUM = DEFPRISLISTA.STARTDATUM.            
   END.
   DO TRANSACTION:
      FIND FIRST PRISLISTOVRIGT WHERE 
      PRISLISTOVRIGT.PRISID = DEFPRISLISTA.PRISID NO-LOCK NO-ERROR.
      IF AVAILABLE PRISLISTOVRIGT THEN DO:
         FIND FIRST FAKTREGLER WHERE FAKTREGLER.FAKTNR = FAKTPLAN.FAKTNR
         EXCLUSIVE-LOCK NO-ERROR.
         IF AVAILABLE FAKTREGLER THEN DO:          
            IF FAKTREGLER.TIMRGL = "KUNDENS EGNA" THEN DO:
               ASSIGN
               FAKTREGLER.ENTRAK = PRISLISTOVRIGT.ENTRAK 
               FAKTREGLER.FLERTRAK = PRISLISTOVRIGT.FLERTRAK
               FAKTREGLER.FRTJPA = PRISLISTOVRIGT.FRTJPA
               FAKTREGLER.MIL = PRISLISTOVRIGT.MIL
               FAKTREGLER.MTRLPA = PRISLISTOVRIGT.MTRLPA.
            END.    
         END.
      END.
   END.
END PROCEDURE.

PROCEDURE prislistnumo_UI :
   FIND FIRST DEFPRISLISTA WHERE DEFPRISLISTA.PRISNUM = FAKTPLAN.PRISNUMO AND 
   DEFPRISLISTA.OVER = TRUE 
   NO-LOCK NO-ERROR.
   IF NOT AVAILABLE DEFPRISLISTA THEN DO:
      musz = TRUE.
      RETURN.
   END.     
   OPEN QUERY prisoq FOR EACH OVERPRISLISTA WHERE 
   OVERPRISLISTA.PRISID = DEFPRISLISTA.PRISID NO-LOCK.
   GET FIRST prisoq NO-LOCK.
   DO WHILE AVAILABLE(OVERPRISLISTA):
      DO TRANSACTION:        
         CREATE FAKTOVER.   
         ASSIGN 
         FAKTOVER.BEFATTNING = OVERPRISLISTA.BEFATTNING
         FAKTOVER.FAKTNR = FAKTPLAN.FAKTNR
         FAKTOVER.DAGTYP = OVERPRISLISTA.DAGTYP
         FAKTOVER.OTEXTID = OVERPRISLISTA.OTEXTID
         FAKTOVER.EQDAG = OVERPRISLISTA.EQDAG
         FAKTOVER.PRISA = OVERPRISLISTA.PRISA
         FAKTOVER.START = OVERPRISLISTA.START
         FAKTOVER.SLUT = OVERPRISLISTA.SLUT.
         GET NEXT prisoq NO-LOCK.
      END.                  
      GET NEXT prisoq NO-LOCK. 
   END.
   CLOSE QUERY prisoq.  
   DO TRANSACTION:
      FIND FIRST FAKTPRISLIST WHERE FAKTPRISLISTA.FAKTNR = FAKTPLAN.FAKTNR AND 
      FAKTPRISLISTA.OVER = DEFPRISLISTA.OVER
      EXCLUSIVE-LOCK NO-ERROR.   
      IF NOT AVAILABLE FAKTPRISLIST THEN CREATE FAKTPRISLISTA.   
      ASSIGN
      FAKTPRISLISTA.FAKTNR = FAKTPLAN.FAKTNR
      FAKTPRISLISTA.OVER = DEFPRISLISTA.OVER
      FAKTPRISLISTA.PRISID = DEFPRISLISTA.PRISID
      FAKTPRISLISTA.FRAGAEJ = FALSE
      FAKTPRISLISTA.STARTDATUM = DEFPRISLISTA.STARTDATUM.            
   END.
END PROCEDURE.



