/*NYPRISL.P*/
DEFINE VARIABLE musz AS LOGICAL NO-UNDO.
OPEN QUERY dpq FOR EACH DEFPRISLISTA NO-LOCK.
GET FIRST dpq NO-LOCK.
DO WHILE AVAILABLE(DEFPRISLISTA):
   OPEN QUERY kpq FOR EACH KUNDPRISLIST WHERE 
   KUNDPRISLIST.PRISID = DEFPRISLISTA.PRISID NO-LOCK.
   GET FIRST kpq NO-LOCK.
   DO WHILE AVAILABLE(KUNDPRISLIST):
      IF DEFPRISLISTA.STARTDATUM >= KUNDPRISLIST.STARTDATUM THEN DO:
         IF DEFPRISLISTA.STARTDATUM > TODAY + 1 THEN musz = musz.
         ELSE DO TRANSACTION:
            GET CURRENT kpq EXCLUSIVE-LOCK.
            KUNDPRISLIST.STARTDATUM = DEFPRISLISTA.STARTDATUM.         
         END.
      END. 
      GET NEXT kpq NO-LOCK.
   END.     
   GET FIRST kpq NO-LOCK.
   DO WHILE AVAILABLE(KUNDPRISLIST):                  
      IF KUNDPRISLIST.OVER = FALSE THEN RUN norm_UI.
      ELSE RUN over_UI.
      GET NEXT kpq NO-LOCK.
   END.   
   GET NEXT dpq NO-LOCK.
END.
PROCEDURE norm_UI:
   OPEN QUERY kbq FOR EACH KUNDBEF WHERE 
   KUNDBEF.BESTID = KUNDPRISLIST.BESTID NO-LOCK.
   DO TRANSACTION:
      GET FIRST kbq EXCLUSIVE-LOCK.
      IF AVAILABLE KUNDBEF THEN DELETE KUNDBEF.
   END.    
   REPEAT:
      DO TRANSACTION:
         GET NEXT kbq EXCLUSIVE-LOCK.
         IF AVAILABLE KUNDBEF THEN DELETE KUNDBEF.
         ELSE LEAVE.
      END.
   END.
   OPEN QUERY prisq FOR EACH PRISLISTFAKT WHERE 
   PRISLISTFAKT.PRISID = DEFPRISLISTA.PRISID NO-LOCK.
   GET FIRST prisq NO-LOCK.
   DO WHILE AVAILABLE(PRISLISTFAKT):
      DO TRANSACTION:
         CREATE KUNDBEF.  
         ASSIGN          
         KUNDBEF.BEFATTNING = PRISLISTFAKT.BEFATTNING 
         KUNDBEF.BESTID = KUNDPRISLIST.BESTID          
         KUNDBEF.PRISA = PRISLISTFAKT.PRISA 
         KUNDBEF.PRISRES = PRISLISTFAKT.PRISRES.                        
      END.   
      GET NEXT prisq NO-LOCK.                     
   END.
   DO TRANSACTION:
      FIND FIRST PRISLISTOVRIGT WHERE 
      PRISLISTOVRIGT.PRISID = DEFPRISLISTA.PRISID NO-LOCK NO-ERROR.
      IF AVAILABLE PRISLISTOVRIGT THEN DO:
         FIND FIRST KUNDREGLER WHERE KUNDREGLER.BESTID = KUNDPRISLIST.BESTID
         EXCLUSIVE-LOCK NO-ERROR.
         IF AVAILABLE KUNDREGLER THEN DO:          
            IF KUNDREGLER.TIMRGL = "KUNDENS EGNA" THEN DO:
               ASSIGN
               KUNDREGLER.ENTRAK = PRISLISTOVRIGT.ENTRAK 
               KUNDREGLER.FLERTRAK = PRISLISTOVRIGT.FLERTRAK
               KUNDREGLER.FRTJPA = PRISLISTOVRIGT.FRTJPA
               KUNDREGLER.MIL = PRISLISTOVRIGT.MIL
               KUNDREGLER.MTRLPA = PRISLISTOVRIGT.MTRLPA.
            END.   
         END.
      END.
   END.         
END PROCEDURE.     
PROCEDURE over_UI: 
   OPEN QUERY kbq FOR EACH KUNDOVER WHERE 
   KUNDOVER.BESTID = KUNDPRISLIST.BESTID NO-LOCK.
   DO TRANSACTION:
      GET FIRST kbq EXCLUSIVE-LOCK.
      IF AVAILABLE KUNDOVER THEN DELETE KUNDOVER.
   END.    
   REPEAT:
      DO TRANSACTION:
         GET NEXT kbq EXCLUSIVE-LOCK.
         IF AVAILABLE KUNDOVER THEN DELETE KUNDOVER.
         ELSE LEAVE.
      END.
   END.
   OPEN QUERY oprisq FOR EACH OVERPRISLISTA WHERE 
   OVERPRISLISTA.PRISID = DEFPRISLISTA.PRISID NO-LOCK.
   GET FIRST oprisq NO-LOCK.
   DO WHILE AVAILABLE(PRISLISTFAKT):
      DO TRANSACTION:
         CREATE KUNDOVER.  
         ASSIGN 
         KUNDOVER.OTEXTID = OVERPRISLIST.OTEXTID
         KUNDOVER.BEFATTNING = OVERPRISLIST.BEFATTNING 
         KUNDOVER.BESTID = KUNDPRISLIST.BESTID 
         KUNDOVER.DAGTYP = OVERPRISLIST.DAGTYP 
         KUNDOVER.EQDAG = OVERPRISLIST.EQDAG 
         KUNDOVER.PRISA = OVERPRISLIST.PRISA 
         KUNDOVER.SLUT = OVERPRISLIST.SLUT 
         KUNDOVER.START = OVERPRISLIST.START.                        
      END.   
      GET NEXT oprisq NO-LOCK.                     
   END.
END PROCEDURE.     
      
      
      
      
      
      
      
      
      
      
  
