/*PRISTAB.P*/
/*
DEFPRISLISTA

DEFPRISLISTA.PRISID
DEFPRISLISTA.OVER 
DEFPRISLISTA.PRISTEXT 
DEFPRISLISTA.STARTDATUM

BESTÄMMER VAD DET ÄR FÖR TYP AV PRISLISTA NORMAL ELLER ÖVERTID
NÄR BÖRJAR DEN ATT GÄLLA.

PRISLISTFAKT

PRISLISTFAKT.PRISID 
PRISLISTFAKT.BEFATTNING 
PRISLISTFAKT.PRISA 
PRISLISTFAKT.PRISRES

GRUNDPRISLISTAN NORMALTID.

PRISLISTOVRIGT

PRISLISTOVRIGT.PRISID
PRISLISTOVRIGT.ENTRAK 
PRISLISTOVRIGT.FLERTRAK 
PRISLISTOVRIGT.FRTJPA 
PRISLISTOVRIGT.MIL 
PRISLISTOVRIGT.MTRLPA 

GRUNDPRISLISTAN NORMALTIDS ÖVRIGA PRISER SOM LAGRAS PÅ KUNDEN OCH FAKTURAN.

OVERPRISLISTA

OVERPRISLISTA.PRISID 
OVERPRISLISTA.OTEXTID 
OVERPRISLISTA.BEFATTNING 
OVERPRISLISTA.DAGTYP 
OVERPRISLISTA.EQDAG 
OVERPRISLISTA.PRISA 
OVERPRISLISTA.SLUT 
OVERPRISLISTA.START

GRUNDPRISLISTAN ÖVERTID.

OVERTEXTFAKT

OVERTEXTFAKT.OTEXTID
OVERTEXTFAKT.BEFATTNING 
OVERTEXTFAKT.OTEXT 

TEXTER FÖR ÖVERTID

KUNDPRISLIST

KUNDPRISLIST.PRISID 
KUNDPRISLIST.BESTID 
KUNDPRISLIST.OVER 
KUNDPRISLIST.STARTDATUM

VILKEN PRISLISTA GÄLLER FÖR DENNA KUND. NÄR BÖRJADE DEN ATT GÄLLA. 
VILKEN TYP AV PRISLISTA.

KUNDBEF

KUNDBEF.BESTID 
KUNDBEF.BEFATTNING 
KUNDBEF.PRISA 
KUNDBEF.PRISRES

KUNDENPRIS NORMALTID.

KUNDOVER

KUNDOVER.BESTID
KUNDOVER.OTEXTID 
KUNDOVER.BEFATTNING 
KUNDOVER.DAGTYP 
KUNDOVER.EQDAG  
KUNDOVER.PRISA 
KUNDOVER.SLUT 
KUNDOVER.START  

KUNDPRISER ÖVERTID.

FAKTPRISLISTA

FAKTPRISLISTA.FAKTNR
FAKTPRISLISTA.PRISID 
FAKTPRISLISTA.OVER  
FAKTPRISLISTA.STARTDATUM

VILKEN PRISLISTA GÄLLER FÖR DENNA FAKTURA. NÄR BÖRJADE DEN ATT GÄLLA. 
VILKEN TYP AV PRISLISTA.

FAKTBEF

FAKTBEF.FAKTNR 
FAKTBEFFAKTBEF.BEFATTNING 
FAKTBEF.PRISA 
FAKTBEF.PRISRES

FAKTURANS NORMALTID.

FAKTOVER

FAKTOVER.FAKTNR 
FAKTOVER.OTEXTID
FAKTOVER.BEFATTNING 
FAKTOVER.DAGTYP 
FAKTOVER.EQDAG  
FAKTOVER.PRISA 
FAKTOVER.SLUT 
FAKTOVER.SLUT100 
FAKTOVER.START 
FAKTOVER.START100

FAKTURANS ÖVERTID.
*/
