/*STIDAPP.P*/
&Scoped-define NEW NEW
{FAKTTEMP.I}
DEFINE INPUT PARAMETER fnr LIKE FAKTPLAN.FAKTNR NO-UNDO.
DEFINE INPUT-OUTPUT PARAMETER TABLE FOR sumtidtemp.   
OPEN QUERY stidq FOR EACH sumtidtemp NO-LOCK, 
EACH FAKTTID WHERE FAKTTID.FAKTNR = fnr AND
FAKTTID.VFAKTNR = 0 AND FAKTTID.AONR = sumtidtemp.AONR AND
FAKTTID.DELNR = sumtidtemp.DELNR AND 
FAKTTID.PERSONALKOD = sumtidtemp.PERSONALKOD AND 
FAKTTID.DATUM = sumtidtemp.DATUM AND FAKTTID.GSTART = sumtidtemp.GSTART AND 
FAKTTID.GSLUT = sumtidtemp.GSLUT AND TRIM(SUBSTRING(FAKTTID.VECKOKORD,1,29)) = sumtidtemp.VECKOKORD AND
TRIM(SUBSTRING(FAKTTID.VECKOKORD,30)) = sumtidtemp.FELKORD
 NO-LOCK.
   
GET FIRST stidq.
DO WHILE AVAILABLE(sumtidtemp):
   ASSIGN
   sumtidtemp.START = FAKTTID.START 
   sumtidtemp.SLUT = FAKTTID.SLUT
   sumtidtemp.OTEXTID = FAKTTID.OTEXTID
   sumtidtemp.PERSMASK = FAKTTID.PERSMASK
   sumtidtemp.BEFATTNING = FAKTTID.BEFATTNING
   sumtidtemp.MED = FAKTTID.MED         
   sumtidtemp.TIMMAR = FAKTTID.TIMMAR
   sumtidtemp.BELOPP = FAKTTID.BELOPP        
   sumtidtemp.OBELOPP = FAKTTID.OBELOPP       
   sumtidtemp.OTIMMAR = FAKTTID.OTIMMAR             
   sumtidtemp.RESPRIS = FAKTTID.RESPRIS
   sumtidtemp.OPRIS = FAKTTID.OPRIS
   sumtidtemp.RESTIM = FAKTTID.DECRESTID
   sumtidtemp.RESKOSTDEC = FAKTTID.RESKOSTDEC
   sumtidtemp.OANT1 = FAKTTID.OANT1.  
   GET NEXT stidq.
END.
CLOSE QUERY stidq.
