 /*XAOKONT.P*/
 OPEN QUERY faktkontq FOR EACH FAKTINTAKTKONT WHERE            
 FAKTINTAKTKONT.VFAKTNR NE 0 NO-LOCK.

 GET FIRST faktkontq NO-LOCK.
 DO WHILE AVAILABLE(FAKTINTAKTKONT):            
    OPEN QUERY aokq FOR EACH AONRKONTKOD WHERE AONRKONTKOD.AONR = FAKTINTAKTKONT.AONR AND       
    AONRKONTKOD.DELNR = FAKTINTAKTKONT.DELNR NO-LOCK.
    GET FIRST aokq NO-LOCK.
    DO WHILE AVAILABLE(AONRKONTKOD):
       DO TRANSACTION:
       
           CREATE FAKTAONRKONTO.
           ASSIGN
           FAKTAONRKONTO.FAKTNR = FAKTINTAKTKONT.FAKTNR 
           FAKTAONRKONTO.VFAKTNR = FAKTINTAKTKONT.VFAKTNR 
           FAKTAONRKONTO.AONR = AONRKONTKOD.AONR 
           FAKTAONRKONTO.DELNR = AONRKONTKOD.DELNR
           FAKTAONRKONTO.K1 = AONRKONTKOD.K1 
           FAKTAONRKONTO.K2 = AONRKONTKOD.K2 
           FAKTAONRKONTO.K3 = AONRKONTKOD.K3 
           FAKTAONRKONTO.K4 = AONRKONTKOD.K4 
           FAKTAONRKONTO.K5 = AONRKONTKOD.K5 
           FAKTAONRKONTO.SATS% = AONRKONTKOD.SATS%.
       END.
       GET NEXT aokq NO-LOCK.
    END.
    GET NEXT faktkontq NO-LOCK.
 END.

 OPEN QUERY kfaktkontq FOR EACH FAKTINTAKTKONTKRED WHERE 
 FAKTINTAKTKONTKRED.VKREDIT NE 0 NO-LOCK.     
 GET FIRST kfaktkontq NO-LOCK.
 DO WHILE AVAILABLE(FAKTINTAKTKONTKRED):            
    OPEN QUERY aokq FOR EACH AONRKONTKOD WHERE AONRKONTKOD.AONR = FAKTINTAKTKONTKRED.AONR AND       
    AONRKONTKOD.DELNR = FAKTINTAKTKONTKRED.DELNR NO-LOCK.
    GET FIRST aokq NO-LOCK.
    DO WHILE AVAILABLE(AONRKONTKOD):
       DO TRANSACTION:
          CREATE FAKTAONRKONTOKRED.
          ASSIGN
          FAKTAONRKONTOKRED.FAKTNR = FAKTINTAKTKONTKRED.FAKTNR 
          FAKTAONRKONTOKRED.VKREDIT = FAKTINTAKTKONTKRED.VKREDIT 
          FAKTAONRKONTOKRED.AONR = AONRKONTKOD.AONR 
          FAKTAONRKONTOKRED.DELNR = AONRKONTKOD.DELNR
          FAKTAONRKONTOKRED.K1 = AONRKONTKOD.K1 
          FAKTAONRKONTOKRED.K2 = AONRKONTKOD.K2 
          FAKTAONRKONTOKRED.K3 = AONRKONTKOD.K3 
          FAKTAONRKONTOKRED.K4 = AONRKONTKOD.K4 
          FAKTAONRKONTOKRED.K5 = AONRKONTKOD.K5 
          FAKTAONRKONTOKRED.SATS% = AONRKONTKOD.SATS%.
       END.
       GET NEXT aokq NO-LOCK.
    END.
    GET NEXT Kfaktkontq NO-LOCK.
 END.
     
