FIND FIRST FAKTPLAN WHERE FAKTPLAN.FAKTNR = 25 NO-ERROR.
  ASSIGN
  FAKTPLAN.FDELNR = FAKTPLAN.FDELNR - 1
  FAKTPLAN.SENASTFAK = TODAY - 1.
  IF FAKTPLAN.FDELNR < 0 THEN FAKTPLAN.FDELNR = 0.

FOR EACH FAKTURERAD WHERE FAKTURERAD.FAKTNR = FAKTPLAN.FAKTNR:
   ASSIGN
   FAKTURERAD.FDELNR = FAKTURERAD.FDELNR - 1    
   FAKTURERAD.DATUM = TODAY - 1.
   IF FAKTURERAD.FDELNR < 0 THEN FAKTURERAD.FDELNR = 0.
END.

FOR EACH FAKTTID WHERE FAKTTID.FAKTNR = FAKTPLAN.FAKTNR:
  IF med NE ? THEN DO:  
     ASSIGN
     FAKTTID.FDELNR = FAKTTID.FDELNR - 1
     FAKTTID.SENASTFAK = TODAY - 1.  
  END.
  ELSE FAKTTID.SENASTFAK = ?. 
  IF FAKTTID.FDELNR < 0 THEN FAKTTID.FDELNR = 0.     
END.

FOR EACH FAKTKOLL WHERE FAKTKOLL.FAKTNR = FAKTPLAN.FAKTNR:
   ASSIGN  
   FAKTKOLL.SENASTFAK = TODAY - 1.     
END.
FOR EACH FAKTKOST WHERE FAKTKOST.FAKTNR = FAKTPLAN.FAKTNR:
  ASSIGN
  FAKTKOST.FDELNR = FAKTKOST.FDELNR - 1.  
  IF FAKTKOST.FDELNR < 0 THEN FAKTKOST.FDELNR = 0.
END.
FOR EACH FAKTFRIA WHERE FAKTFRIA.FAKTNR = FAKTPLAN.FAKTNR:
  ASSIGN
  FAKTFRIA.FDELNR = FAKTFRIA.FDELNR - 1.  
  IF FAKTFRIA.FDELNR < 0 THEN FAKTFRIA.FDELNR = 0.
END.
FOR EACH FAKTINTAKTKONT WHERE FAKTINTAKTKONT.FAKTNR = FAKTPLAN.FAKTNR:
  ASSIGN
  FAKTINTAKTKONT.FDELNR = FAKTINTAKTKONT.FDELNR - 1.  
  IF FAKTINTAKTKONT.FDELNR < 0 THEN FAKTINTAKTKONT.FDELNR = 0.
END.
FOR EACH FAKTKUNDKONTO WHERE FAKTKUNDKONTO.FAKTNR = FAKTPLAN.FAKTNR:
  ASSIGN
  FAKTKUNDKONTO.FDELNR = FAKTKUNDKONTO.FDELNR - 1.  
  IF FAKTKUNDKONTO.FDELNR < 0 THEN FAKTKUNDKONTO.FDELNR = 0.
END.
FOR EACH FAKTMOMS WHERE FAKTMOMS.FAKTNR = FAKTPLAN.FAKTNR:
  ASSIGN
  FAKTMOMS.FDELNR = FAKTMOMS.FDELNR - 1.  
  IF FAKTMOMS.FDELNR < 0 THEN FAKTMOMS.FDELNR = 0.
END.
FOR EACH FAKTMOMS WHERE FAKTMOMS.FAKTNR = FAKTPLAN.FAKTNR:
  ASSIGN
  FAKTMOMS.FDELNR = FAKTMOMS.FDELNR - 1.  
  IF FAKTMOMS.FDELNR < 0 THEN FAKTMOMS.FDELNR = 0.
END.

