output to printer.
for each momstab:
display MOMSTAB.MOMSEXTERNT MOMSTAB.MOMSID MOMSTAB.MOMSINTERNT MOMSTAB.MOMSKOD MOMSTAB.MOMSNR MOMSTAB.MOMSTEXT format "x(20)".
end.
for each INTAKTTAB:
display INTAKTTAB.INTAKTID INTAKTTAB.INTAKTKONTO INTAKTTAB.INTAKTTEXT format "x(30)".

end.
for each KUNDFODRAN:
display  KUNDFODRAN.KUNDKONTO KUNDFODRAN.KUNDKONTOID KUNDFODRAN.KUNDFODTEXT format "x(30)".
end. 
for each FAKTURERINGSTYP:
display FAKTURERINGSTYP.FAKTTYPID 
FAKTURERINGSTYP.OBLMOMS 
FAKTURERINGSTYP.SLUT 
FAKTURERINGSTYP.TIDIGAREACONTO label "tac"
FAKTURERINGSTYP.TIDIGAREFAKT label "tfa"
FAKTURERINGSTYP.TIDIGAREMOMS label "tmo"
FAKTURERINGSTYP.FAKTTYPTEXT format "x(30)".
end.
for each STYRINTAKT:
display STYRINTAKT.FAKTTYPID STYRINTAKT.INTAKTID STYRINTAKT.KUNDID STYRINTAKT.MOMSID.
end.
for each STYRKUND:
display STYRKUND.KUNDID STYRKUND.KUNDKONTOID.
end.

for each STYRMOMS:
display STYRMOMS.FAKTTYPID STYRMOMS.KUNDID STYRMOMS.MOMSID.
end.

