/*XOTEXT.P*/
/*
OPEN QUERY kUq FOR EACH KUNDREGLER NO-LOCK.
DO TRANSACTION:
   GET FIRST kUq EXCLUSIVE-LOCK.
   IF AVAILABLE KUNDREGLER THEN DO:
      FIND FIRST INTAKTTAB NO-LOCK NO-ERROR.
         FIND FIRST KUNDFODRAN NO-LOCK NO-ERROR.
         FIND FIRST MOMSTAB NO-LOCK NO-ERROR.
         FIND FIRST MOTPART NO-LOCK NO-ERROR.  
         ASSIGN 
         KUNDREGLER.INTAKTID =  INTAKTTAB.INTAKTID
         KUNDREGLER.KUNDKONTOID = KUNDFODRAN.KUNDKONTOID
         KUNDREGLER.MOMSID = MOMSTAB.MOMSID
         KUNDREGLER.MOTPARTID = MOTPART.MOTPARTID.    
   END.   
END.
REPEAT:   
   DO TRANSACTION:
      GET NEXT kUq EXCLUSIVE-LOCK.
      IF AVAILABLE KUNDREGLER THEN DO:
                  ASSIGN 
         KUNDREGLER.INTAKTID =  INTAKTTAB.INTAKTID
         KUNDREGLER.KUNDKONTOID = KUNDFODRAN.KUNDKONTOID
         KUNDREGLER.MOMSID = MOMSTAB.MOMSID
         KUNDREGLER.MOTPARTID = MOTPART.MOTPARTID.
      END.
      ELSE LEAVE.
   END.
END.
OPEN QUERY FUQ FOR EACH FAKTREGLER NO-LOCK.
DO TRANSACTION:
   GET FIRST FUQ EXCLUSIVE-LOCK.
   IF AVAILABLE FAKTREGLER THEN DO:
      FIND FIRST INTAKTTAB NO-LOCK NO-ERROR.
         FIND FIRST KUNDFODRAN NO-LOCK NO-ERROR.
         FIND FIRST MOMSTAB NO-LOCK NO-ERROR.
         FIND FIRST MOTPART NO-LOCK NO-ERROR.  
         ASSIGN 
         FAKTREGLER.INTAKTID =  INTAKTTAB.INTAKTID
         FAKTREGLER.KUNDKONTOID = KUNDFODRAN.KUNDKONTOID
         FAKTREGLER.MOMSID = MOMSTAB.MOMSID
         FAKTREGLER.MOTPARTID = MOTPART.MOTPARTID.    
   END.   
END.
REPEAT:   
   DO TRANSACTION:
      GET NEXT FUQ EXCLUSIVE-LOCK.
      IF AVAILABLE FAKTREGLER THEN DO:
                  ASSIGN 
         FAKTREGLER.INTAKTID =  INTAKTTAB.INTAKTID
         FAKTREGLER.KUNDKONTOID = KUNDFODRAN.KUNDKONTOID
         FAKTREGLER.MOMSID = MOMSTAB.MOMSID
         FAKTREGLER.MOTPARTID = MOTPART.MOTPARTID.
      END.
      ELSE LEAVE.
   END.
END.
OPEN QUERY kq FOR EACH KUNDOVER NO-LOCK.
DO TRANSACTION:
   GET FIRST kq EXCLUSIVE-LOCK.
   IF AVAILABLE KUNDOVER THEN DO:
      FIND FIRST OVERTEXTFAKT WHERE OVERTEXTFAKT.BEFATTNING = KUNDOVER.BEFATTNING 
      NO-LOCK NO-ERROR.
      ASSIGN KUNDOVER.OTEXTID = OVERTEXTFAKT.OTEXTID.
   END.   
END.
REPEAT:   
   DO TRANSACTION:
      GET NEXT kq EXCLUSIVE-LOCK.
      IF AVAILABLE KUNDOVER THEN DO:
         FIND FIRST OVERTEXTFAKT WHERE OVERTEXTFAKT.BEFATTNING = KUNDOVER.BEFATTNING 
         NO-LOCK NO-ERROR.      
         ASSIGN KUNDOVER.OTEXTID = OVERTEXTFAKT.OTEXTID.
      END.
      ELSE LEAVE.
   END.
END.
OPEN QUERY ftq FOR EACH KUNDOVER NO-LOCK.
DO TRANSACTION:
   GET FIRST ftq EXCLUSIVE-LOCK.
   IF AVAILABLE FAKTTID THEN FAKTTID.RESKOSTDEC = FAKTTID.RESKOST.   
END.
REPEAT:   
   DO TRANSACTION:
      GET NEXT ftq EXCLUSIVE-LOCK.
      IF AVAILABLE FAKTTID THEN DO:
         IF AVAILABLE FAKTTID THEN FAKTTID.RESKOSTDEC = FAKTTID.RESKOST.  
      END.
      ELSE LEAVE.
   END.
END.

   
OPEN QUERY fq FOR EACH FAKTOVER NO-LOCK.
DO TRANSACTION:
   GET FIRST fq EXCLUSIVE-LOCK.
   IF AVAILABLE FAKTOVER THEN DO:
      FIND FIRST OVERTEXTFAKT WHERE OVERTEXTFAKT.BEFATTNING = FAKTOVER.BEFATTNING 
       NO-LOCK NO-ERROR.
      ASSIGN FAKTOVER.OTEXTID = OVERTEXTFAKT.OTEXTID.
   END.   
END.
REPEAT:   
   DO TRANSACTION:
      GET NEXT fq EXCLUSIVE-LOCK.
      IF AVAILABLE FAKTOVER THEN DO:
         FIND FIRST OVERTEXTFAKT WHERE OVERTEXTFAKT.BEFATTNING = FAKTOVER.BEFATTNING 
         NO-LOCK NO-ERROR.      
         ASSIGN FAKTOVER.OTEXTID = OVERTEXTFAKT.OTEXTID.
      END.
      ELSE LEAVE.
   END.
END.   

OPEN QUERY fpq FOR EACH FAKTPLAN NO-LOCK.
do transaction:
   GET FIRST fpq EXCLUSIVE-LOCK.
   
   IF AVAILABLE FAKTPLAN THEN DO:
      
      FIND FIRST FAKTAONR WHERE FAKTAONR.FAKTNR = FAKTPLAN.FAKTNR NO-LOCK NO-ERROR.
      IF AVAILABLE FAKTAONR THEN DO:
         FIND FIRST AONRTAB WHERE AONRTAB.AONR = FAKTAONR.AONR AND
         AONRTAB.DELNR = FAKTAONR.DELNR NO-LOCK NO-ERROR.
         ASSIGN 
         FAKTPLAN.HANVANDARE = AONRTAB.ANVANDARE
         FAKTPLAN.OMRADE = AONRTAB.OMRADE
         FAKTPLAN.VISAONR = AONRTAB.AONR + STRING(AONRTAB.DELNR,">99")
         FAKTPLAN.FAKTTYP = "Löpande räkning".         
         IF AONRTAB.DELNR NE 0 THEN DO:
            FIND FIRST AONRTAB WHERE AONRTAB.AONR = FAKTAONR.AONR AND
            AONRTAB.DELNR = 0 NO-LOCK NO-ERROR.
            IF AVAILABLE AONRTAB THEN DO:
               ASSIGN 
               FAKTPLAN.HANVANDARE = AONRTAB.ANVANDARE.               
            END.
         END.
         
         FIND NEXT FAKTAONR WHERE FAKTAONR.FAKTNR = FAKTPLAN.FAKTNR NO-LOCK no-error. 
         IF AVAILABLE FAKTAONR THEN FAKTPLAN.VISAONR = "Sammfakt.".
      END.
      
      ELSE DO:
         ASSIGN 
         FAKTPLAN.HANVANDARE = FAKTPLAN.ANVANDARE
         FAKTPLAN.VISAONR = "Inga " + LC(Guru.Konstanter:gaok) + " kopplade"
         FAKTPLAN.FAKTTYP = "Löpande räkning".
      END.
      
   END.
END.
repeat:
      

   do transaction:
      GET NEXT fpq EXCLUSIVE-LOCK.
      IF AVAILABLE FAKTPLAN THEN DO:
         FIND FIRST FAKTAONR WHERE FAKTAONR.FAKTNR = FAKTPLAN.FAKTNR NO-LOCK.
         IF AVAILABLE FAKTAONR THEN DO:
            FIND FIRST AONRTAB WHERE AONRTAB.AONR = FAKTAONR.AONR AND
            AONRTAB.DELNR = FAKTAONR.DELNR NO-LOCK NO-ERROR.
            ASSIGN 
            FAKTPLAN.HANVANDARE = AONRTAB.ANVANDARE
            FAKTPLAN.OMRADE = AONRTAB.OMRADE
            FAKTPLAN.VISAONR = AONRTAB.AONR + STRING(AONRTAB.DELNR,">99")
            FAKTPLAN.FAKTTYP = "Löpande räkning".
            IF AONRTAB.DELNR NE 0 THEN DO:
               FIND FIRST AONRTAB WHERE AONRTAB.AONR = FAKTAONR.AONR AND
               AONRTAB.DELNR = 0 NO-LOCK NO-ERROR.
               IF AVAILABLE AONRTAB THEN DO:
                  ASSIGN 
                  FAKTPLAN.HANVANDARE = AONRTAB.ANVANDARE.                  
               END.
            END.
            FIND NEXT FAKTAONR WHERE FAKTAONR.FAKTNR = FAKTPLAN.FAKTNR NO-LOCK NO-ERROR. 
            IF AVAILABLE FAKTAONR THEN FAKTPLAN.VISAONR = "Sammfakt.".
         END.
         ELSE DO:
            ASSIGN 
            FAKTPLAN.HANVANDARE = FAKTPLAN.ANVANDARE
            FAKTPLAN.VISAONR = "Inga " + LC(Guru.Konstanter:gaok) + " kopplade"
            FAKTPLAN.FAKTTYP = "Löpande räkning".
         END.
      END.
      else leave.   
   END.   
END.      
OPEN QUERY faoq FOR EACH FAKTAONR NO-LOCK.
do transaction:
   GET FIRST faoq EXCLUSIVE-LOCK.
   
   IF AVAILABLE FAKTAONR THEN DO:
      
      FIND FIRST AONRTAB WHERE AONRTAB.AONR = FAKTAONR.AONR AND
      AONRTAB.DELNR = FAKTAONR.DELNR NO-LOCK NO-ERROR.
      IF AVAILABLE AONRtab THEN DO:
         FAKTAONR.GDATUM = AONRTAB.ELVOMRKOD.      
        FIND FIRST FAKTKOLL WHERE FAKTKOLL.FAKTNR = FAKTAONR.FAKTNR AND
         FAKTKOLL.AONR = FAKTAONR.AONR  AND
         FAKTKOLL.DELNR = FAKTAONR.DELNR USE-INDEX FAKTNR NO-LOCK NO-ERROR. 
         IF NOT AVAILABLE FAKTKOLL THEN DO:
            CREATE FAKTKOLL.
            ASSIGN
            FAKTKOLL.AONR = FAKTAONR.AONR
            FAKTKOLL.DELNR = FAKTAONR.DELNR
            FAKTKOLL.BESTID = AONRTAB.BESTID
            FAKTKOLL.FAKTNR = FAKTAONR.FAKTNR
            FAKTKOLL.SENASTFAK = ?
            FAKTKOLL.SENASTTID = ?
            FAKTKOLL.SLUTFAKT = FALSE
            FAKTKOLL.VECKOKORD = "".
         end.
      END.
   END.
END.   
repeat:
do transaction:
   GET NEXT faoq EXCLUSIVE-LOCK.
   
   IF AVAILABLE FAKTAONR THEN DO:      
      FIND FIRST AONRTAB WHERE AONRTAB.AONR = FAKTAONR.AONR AND
      AONRTAB.DELNR = FAKTAONR.DELNR NO-LOCK NO-ERROR.
      IF AVAILABLE AONRtab THEN DO:
         FAKTAONR.GDATUM = AONRTAB.ELVOMRKOD.    
         FIND FIRST FAKTKOLL WHERE FAKTKOLL.FAKTNR = FAKTAONR.FAKTNR AND
         FAKTKOLL.AONR = FAKTAONR.AONR  AND
         FAKTKOLL.DELNR = FAKTAONR.DELNR USE-INDEX FAKTNR NO-LOCK NO-ERROR. 
         IF NOT AVAILABLE FAKTKOLL THEN DO:
           CREATE FAKTKOLL.
           ASSIGN
           FAKTKOLL.AONR = FAKTAONR.AONR
           FAKTKOLL.DELNR = FAKTAONR.DELNR
           FAKTKOLL.BESTID = AONRTAB.BESTID
           FAKTKOLL.FAKTNR = FAKTAONR.FAKTNR
           FAKTKOLL.SENASTFAK = ?
           FAKTKOLL.SENASTTID = ?
            FAKTKOLL.SLUTFAKT = FALSE
           FAKTKOLL.VECKOKORD = "".
        end. 
      END.
   END.
   ELSE LEAVE.
END.
END.      
FOR EACH AONRKONTKOD WHERE 
AONRKONTKOD.K3 = "UA" OR AONRKONTKOD.K3 = "UF" NO-LOCK:
   DO TRANSACTION:
      FIND FIRST AONRTAB WHERE AONRTAB.AONR = AONRKONTKOD.AONR AND 
      AONRTAB.DELNR = AONRKONTKOD.DELNR   
      EXCLUSIVE-LOCK NO-ERROR.
      if available AONRTAB THEN DO:      
         AONRTAB.FAKTTYP = "Avtal".
         FIND FIRST FAKTPLAN WHERE FAKTPLAN.FAKTNR = AONRTAB.FAKTNR 
         EXCLUSIVE-LOCK NO-ERROR.  
         if available FAKTPLAN THEN DO:    
            FAKTPLAN.FAKTTYP = "Avtal".
         END.
      END.
   END.
END.
FOR EACH AONRKONTKOD WHERE AONRKONTKOD.K3 = "UL" NO-LOCK:
   DO TRANSACTION:
      FIND FIRST AONRTAB WHERE AONRTAB.AONR = AONRKONTKOD.AONR AND 
      AONRTAB.DELNR = AONRKONTKOD.DELNR   
      EXCLUSIVE-LOCK NO-ERROR.     
      if available AONRTAB THEN DO: 
         AONRTAB.FAKTTYP = "Löpande räkning".    
         FIND FIRST FAKTPLAN WHERE FAKTPLAN.FAKTNR = AONRTAB.FAKTNR 
         EXCLUSIVE-LOCK NO-ERROR.      
         if available FAKTPLAN THEN DO:
            FAKTPLAN.FAKTTYP = "Löpande räkning".
         END.   
      END.
   END.
END.                     
*/
/*      
OPEN QUERY fTq FOR EACH FAKTTID NO-LOCK.
do transaction:
   GET FIRST fTq EXCLUSIVE-LOCK.
   
   IF AVAILABLE FAKTTID THEN DO:
      IF FAKTTID.OTIMMAR NE 0 THEN FAKTTID.OPRIS = FAKTTID.OBELOPP / FAKTTID.OTIMMAR.      
      IF FAKTTID.RESTIM NE 0 THEN FAKTTID.RESPRIS = FAKTTID.RESKOSTDEC / FAKTTID.RESTIM.
   END.
END.
REPEAT:
   do transaction:
      GET NEXT fTq EXCLUSIVE-LOCK.
   
      IF AVAILABLE FAKTTID THEN DO:
         IF FAKTTID.OTIMMAR NE 0 THEN FAKTTID.OPRIS = FAKTTID.OBELOPP / FAKTTID.OTIMMAR.      
         IF FAKTTID.DECRESTID NE 0 THEN FAKTTID.RESPRIS = FAKTTID.RESKOSTDEC / FAKTTID.DECRESTID.
     END.
     ELSE LEAVE.
   END.
END.
*/
OPEN QUERY fTq FOR EACH KALKKATEGORI NO-LOCK.
do transaction:
   GET FIRST fTq EXCLUSIVE-LOCK.
   
   IF AVAILABLE KALKKATEGORI THEN DO:
      KALKKATEGORI.VINAMN =  KALKKATEGORI.NAMN.
   END.
END.
REPEAT:
   do transaction:
      GET NEXT fTq EXCLUSIVE-LOCK.
   
      IF AVAILABLE KALKKATEGORI THEN DO:
      KALKKATEGORI.VINAMN =  KALKKATEGORI.NAMN.
   END.
     ELSE LEAVE.
   END.
END.
OPEN QUERY fpq FOR EACH FAKTPLAN NO-LOCK.
do transaction:
   GET FIRST fpq EXCLUSIVE-LOCK.
   
   IF AVAILABLE FAKTPLAN THEN DO:
      FAKTPLAN.pANVANDARE = FAKTPLAN.ANVANDARE.
      
   END.
END.
repeat:
      

   do transaction:
      GET NEXT fpq EXCLUSIVE-LOCK.
      IF AVAILABLE FAKTPLAN THEN DO:
            FAKTPLAN.pANVANDARE = FAKTPLAN.ANVANDARE.
         
      END.
      else leave.   
   END.   
END.
