/*XUNIXUT.P*/
/*
 
 
DEFINE VARIABLE unixskriv AS CHARACTER NO-UNDO.


*/
{TIDUTTT.I}
DEFINE INPUT PARAMETER unixskriv AS CHARACTER NO-UNDO.
RUN ut_UI.
PROCEDURE ut_UI:
   FIND FIRST SKRIVARDEF WHERE SKRIVARDEF.SKRIVARID = unixskriv
   USE-INDEX SKRIVARE NO-LOCK NO-ERROR.   
   DEFINE VARIABLE i AS INTEGER NO-UNDO.
   REPEAT i = 1 TO 145:
      CREATE tidut.
      ASSIGN tidut.UT = "Detta är rad nr " + STRING(i).      
      IF i = 1 THEN DO:
         tidut.UT = tidut.UT + " Antal rader per sida: " + STRING(SKRIVARDEF.SIDA). 
      END.     
      IF i = 7 THEN DO:                                     
         tidut.UT = "123456789012345678901234567890123456789012345678901234567890123456789012345". 
      END.
   END.
   IF OPSYS = "UNIX" THEN DO:      
      OUTPUT THROUGH VALUE(SKRIVARDEF.UTSKRIFTSTYP) PAGE-SIZE VALUE(SKRIVARDEF.SIDA) MAP asc8.
   END.
   ELSE DO:      
      OUTPUT TO VALUE(SKRIVARDEF.UTSKRIFTSTYP) PAGE-SIZE VALUE(SKRIVARDEF.SIDA).
      FOR EACH SKRIVARKODER WHERE
	  SKRIVARKODER.SKRIVARKLASS = SKRIVARDEF.SKRIVARKLASS AND
	  SKRIVARKODER.KODNAMN BEGINS "INIT" NO-LOCK:
	  PUT CONTROL SKRIVARKODER.KODSTR.
      END.
   END.
   FOR EACH tidut:
      PUT UNFORMATTED tidut.UT AT 6 SKIP.
   END.
   OUTPUT CLOSE.
END PROCEDURE.	 
