/*SKOVAV.P UTSKRIFT OVERTIDAVVIKELSE OVERAVTAB*/
     
OUTPUT TO PRINTER PAGE-SIZE 73
   CONVERT TARGET "iso8859-1".
PUT SKIP (2).
FOR EACH OVERAVTAB:
   PUT OVERAVTAB.KOD AT 6 OVERAVTAB.DATUM AT 12 OVERAVTAB.OVERTIDUTTAG AT 25
   OVERAVTAB.OVERTIDTILL AT 28 OVERAVTAB.START1  AT 35 OVERAVTAB.STOPP1  AT 42
   OVERAVTAB.START2 AT 49 OVERAVTAB.STOPP2 AT 56 
   OVERAVTAB.EQDAG AT 63 OVERAVTAB.DAGEQ AT 67.
             
END.  
OUTPUT CLOSE.
