OPEN QUERY BQ FOR EACH KONSTRUKTION WHERE KONSTRUKTION.KONSKOD = 14 NO-LOCK.
DO  TRANSACTION:
   GET FIRST BQ NO-LOCK.
   CREATE KONSTVAL.
   ASSIGN
   KONSTVAL.KTYPKOD = "CDC"
   KONSTVAL.KONSKOD = 0
   KONSTVAL.KVALKOD = KONSTRUKTION.KTYPKOD
   KONSTVAL.BENAMNING = KONSTRUKTION.BENAMNING
   KONSTVAL.KOPP = TRUE
   KONSTVAL.BB = "Kablar".
END.
REPEAT:
   DO TRANSACTION:
      GET NEXT bq NO-LOCK.
      IF AVAILABLE KONSTRUKTION THEN DO:
         CREATE KONSTVAL.
         ASSIGN
         KONSTVAL.KTYPKOD = "CDC"
         KONSTVAL.KONSKOD = 0
         KONSTVAL.KVALKOD = KONSTRUKTION.KTYPKOD
         KONSTVAL.BENAMNING = KONSTRUKTION.BENAMNING
         KONSTVAL.KOPP = TRUE
         KONSTVAL.BB = "Kablar".
      END.
      ELSE LEAVE.
   END.
END.
