DEFINE QUERY persekq FOR PERSEK.
DEFINE QUERY tidsekq FOR TIDSEK.
   OPEN QUERY PQ FOR EACH PERSONALTAB NO-LOCK.   
   DO TRANSACTION:
      GET FIRST PQ EXCLUSIVE-LOCK. 
      FIND FIRST OMRADETAB WHERE OMRADETAB.OMRADE = PERSONALTAB.OMRADE 
      NO-LOCK NO-ERROR.
      IF NOT AVAILABLE OMRADETAB THEN DO:    
      OPEN QUERY timq
      FOR EACH TIMKOSTNADSTAB WHERE TIMKOSTNADSTAB.PERSONALKOD = PERSONALTAB.PERSONALKOD
      USE-INDEX PRISPERS NO-LOCK.
      GET FIRST timq EXCLUSIVE-LOCK.
      DO WHILE AVAILABLE(TIMKOSTNADSTAB):    
         DELETE TIMKOSTNADSTAB.
         GET NEXT timq EXCLUSIVE-LOCK. 
      END.                    
      CLOSE QUERY timq.
      OPEN QUERY psekq
      FOR EACH PERSEK WHERE PERSEK.PERSONALKOD = PERSONALTAB.PERSONALKOD 
      USE-INDEX PERSONALKOD NO-LOCK.
      GET FIRST psekq EXCLUSIVE-LOCK.
      DO WHILE AVAILABLE(PERSEK):     
         DELETE PERSEK.
         GET NEXT psekq EXCLUSIVE-LOCK. 
      END.   
      CLOSE QUERY psekq.
      OPEN QUERY tsekq
      FOR EACH TIDSEK WHERE TIDSEK.PERSONALKOD = PERSONALTAB.PERSONALKOD 
      USE-INDEX PERSONALKOD NO-LOCK.
      GET FIRST tsekq EXCLUSIVE-LOCK.
      DO WHILE AVAILABLE(TIDSEK):         
         DELETE TIDSEK. 
         GET NEXT tsekq EXCLUSIVE-LOCK.                     
      END.   
      CLOSE QUERY tsekq.                                 
        
      
      FIND FIRST BEREDAONR WHERE BEREDAONR.PERSONALKOD = PERSONALTAB.PERSONALKOD 
      USE-INDEX PERSONALKOD EXCLUSIVE-LOCK NO-ERROR. 
      IF AVAILABLE BEREDAONR THEN DO:
         DELETE BEREDAONR.
      END.   
      FIND FIRST ANSVAONR WHERE ANSVAONR.PERSONALKOD = PERSONALTAB.PERSONALKOD 
      USE-INDEX PERSONALKOD EXCLUSIVE-LOCK NO-ERROR.   
      IF AVAILABLE ANSVAONR THEN DO:
         DELETE ANSVAONR.
      END.                  
         
      FIND ANVANDARE WHERE ANVANDARE.PERSONALKOD = PERSONALTAB.PERSONALKOD EXCLUSIVE-LOCK NO-ERROR.       
      IF AVAILABLE ANVANDARE THEN DO:                                                                    
         DELETE ANVANDARE.     
         DELETE PERSONALTAB.            
      END.   
      ELSE DO:
         DELETE PERSONALTAB.
      END.
      END.
   END.      
   REPEAT:
      DO TRANSACTION:
         GET NEXT PQ EXCLUSIVE-LOCK.
         IF AVAILABLE PERSONALTAB THEN DO:
            
            
         FIND FIRST OMRADETAB WHERE OMRADETAB.OMRADE = PERSONALTAB.OMRADE 
      NO-LOCK NO-ERROR.
      IF NOT AVAILABLE OMRADETAB THEN DO:    
      OPEN QUERY timq
      FOR EACH TIMKOSTNADSTAB WHERE TIMKOSTNADSTAB.PERSONALKOD = PERSONALTAB.PERSONALKOD
      USE-INDEX PRISPERS NO-LOCK.
      GET FIRST timq EXCLUSIVE-LOCK.
      DO WHILE AVAILABLE(TIMKOSTNADSTAB):    
         DELETE TIMKOSTNADSTAB.
         GET NEXT timq EXCLUSIVE-LOCK. 
      END.                    
      CLOSE QUERY timq.
      OPEN QUERY psekq
      FOR EACH PERSEK WHERE PERSEK.PERSONALKOD = PERSONALTAB.PERSONALKOD 
      USE-INDEX PERSONALKOD NO-LOCK.
      GET FIRST psekq EXCLUSIVE-LOCK.
      DO WHILE AVAILABLE(PERSEK):     
         DELETE PERSEK.
         GET NEXT psekq EXCLUSIVE-LOCK. 
      END.   
      CLOSE QUERY psekq.
      OPEN QUERY tsekq
      FOR EACH TIDSEK WHERE TIDSEK.PERSONALKOD = PERSONALTAB.PERSONALKOD 
      USE-INDEX PERSONALKOD NO-LOCK.
      GET FIRST tsekq EXCLUSIVE-LOCK.
      DO WHILE AVAILABLE(TIDSEK):         
         DELETE TIDSEK. 
         GET NEXT tsekq EXCLUSIVE-LOCK.                     
      END.   
      CLOSE QUERY tsekq.                                 
        
      
      FIND FIRST BEREDAONR WHERE BEREDAONR.PERSONALKOD = PERSONALTAB.PERSONALKOD 
      USE-INDEX PERSONALKOD EXCLUSIVE-LOCK NO-ERROR. 
      IF AVAILABLE BEREDAONR THEN DO:
         DELETE BEREDAONR.
      END.   
      FIND FIRST ANSVAONR WHERE ANSVAONR.PERSONALKOD = PERSONALTAB.PERSONALKOD 
      USE-INDEX PERSONALKOD EXCLUSIVE-LOCK NO-ERROR.   
      IF AVAILABLE ANSVAONR THEN DO:
         DELETE ANSVAONR.
      END.                  
         
      FIND ANVANDARE WHERE ANVANDARE.PERSONALKOD = PERSONALTAB.PERSONALKOD EXCLUSIVE-LOCK NO-ERROR.       
      IF AVAILABLE ANVANDARE THEN DO:                                                            
         DELETE ANVANDARE.     
         DELETE PERSONALTAB.            
      END.   
      ELSE DO:
         DELETE PERSONALTAB.
      END.
      END.   
            
            
         END.
         ELSE LEAVE.
      END.
   END.      
