/*FLYTTA MTRL FRÅN ETT FÄLT TILL ETT ANNAT INOM EN KONST.GRUPP*/

OPEN QUERY kq FOR EACH KONSTRUKTION WHERE KONSTRUKTION.KONSKOD = 9 NO-LOCK.
GET FIRST kq NO-LOCK.
DO WHILE AVAILABLE(KONSTRUKTION):
   OPEN QUERY kq2 FOR EACH MTRLBER WHERE MTRLBER.KTYPKOD = KONSTRUKTION.KTYPKOD NO-LOCK.
   DO TRANSACTION:
      GET FIRST kq2 EXCLUSIVE-LOCK.
      IF AVAILABLE MTRLBER THEN DO:
         IF MTRLBER.F4 NE " " THEN DO:
            ASSIGN
            MTRLBER.F5 = MTRLBER.F4
            MTRLBER.F4 = "".
         END.
      END.
   END.      
   REPEAT:
      DO TRANSACTION:
         GET NEXT kq2 EXCLUSIVE-LOCK.
         IF AVAILABLE MTRLBER THEN DO:
            IF MTRLBER.F4 NE " " THEN DO:
               ASSIGN
               MTRLBER.F5 = MTRLBER.F4
               MTRLBER.F4 = "".
            END.
         END.
         ELSE LEAVE.
      END.      
   END.
   CLOSE QUERY kq2.
   GET NEXT kq NO-LOCK.
END.
CLOSE QUERY kq.
