DEFINE BUFFER konbuff FOR KONSTVAL.
OPEN QUERY konstq FOR EACH KONSTVAL WHERE KONSTVAL.KONSKOD = 12 NO-LOCK.
GET FIRST konstq NO-LOCK.
DO WHILE AVAILABLE(KONSTVAL):
   FIND FIRST konbuff WHERE konbuff.KONSKOD = 30
   AND konbuff.KTYPKOD = "KOPI" AND konbuff.KVALKOD = KONSTVAL.KVALKOD AND
   konbuff.BB = KONSTVAL.BB NO-LOCK NO-ERROR.
   IF NOT AVAILABLE konbuff THEN DO:
      CREATE konbuff.
      ASSIGN
      konbuff.KONSKOD = 30
      konbuff.KTYPKOD = "KOPI"
      konbuff.KVALKOD = KONSTVAL.KVALKOD
      konbuff.BB = KONSTVAL.BB
      konbuff.BENAMNING = KONSTVAL.BENAMNING
      konbuff.KOPP = TRUE
      konbuff.ORDNING = KONSTVAL.ORDNING.
   END.
   GET NEXT konstq NO-LOCK.
END.      
