
DEFINE VARIABLE ORD AS INTEGER NO-UNDO.
FIND LAST KONSTRUKTION USE-INDEX ORDNING NO-LOCK NO-ERROR.
IF AVAILABLE KONSTRUKTION THEN DO:
   ord = KONSTRUKTION.ORDNING.
END.
ELSE DO:
   ord = 1.
END.      
OPEN QUERY MQ FOR EACH MTRL WHERE MTRL.LEVKOD = "5" AND 
MTRL.KALKNR = 0 NO-LOCK.
DO TRANSACTION:
    GET FIRST MQ NO-LOCK.
    CREATE KONSTRUKTION.
    ASSIGN
    KONSTRUKTION.KTYPKOD = MTRL.ENR
    KONSTRUKTION.BENAMNING = MTRL.BENAMNING
    KONSTRUKTION.KONSKOD = 30
    KONSTRUKTION.ORDNING = ORD + 1.
END.
REPEAT:
    DO TRANSACTION:
        GET NEXT MQ NO-LOCK.
        IF AVAILABLE MTRL THEN DO:
           CREATE KONSTRUKTION.
           ASSIGN
           KONSTRUKTION.KTYPKOD = MTRL.ENR
           KONSTRUKTION.BENAMNING = MTRL.BENAMNING
           KONSTRUKTION.KONSKOD = 30
           KONSTRUKTION.ORDNING = ORD + 1.
        END.
        ELSE LEAVE.
    END.
END.
