/*AVBEF.P */
{TIDUTTTNEW.I}
DEFINE TEMP-TABLE felmeddtemp 
  FIELD FELMEDD AS CHARACTER
  FIELD VAL AS INTEGER.
DEFINE INPUT PARAMETER pkod AS CHARACTER NO-UNDO.
DEFINE INPUT PARAMETER brwbdatum AS DATE NO-UNDO.
DEFINE INPUT PARAMETER brwavdatum AS DATE NO-UNDO.
DEFINE OUTPUT PARAMETER TABLE FOR felmeddtemp.
DEFINE OUTPUT PARAMETER TABLE FOR tidut.
DEFINE VARIABLE finns AS LOGICAL NO-UNDO.
FIND FIRST PERSONALTAB WHERE PERSONALTAB.PERSONALKOD = pkod NO-LOCK NO-ERROR.
OPEN QUERY tidbefq FOR EACH TIDREGITAB WHERE 
TIDREGITAB.PERSONALKOD = PERSONALTAB.PERSONALKOD AND
YEAR(TIDREGITAB.DATUM) = YEAR(brwbdatum) AND
MONTH(TIDREGITAB.DATUM) = MONTH(brwbdatum) AND 
TIDREGITAB.TIDLOG = TRUE USE-INDEX PSTART NO-LOCK,
EACH BEFATTNINGSTAB WHERE BEFATTNING.BEFATTNING = TIDREGITAB.OVERTIDTILL NO-LOCK.

CREATE tidut. 
SUBSTRING(tidut.UT,60) = STRING(TODAY) + " " + STRING(TIME,"HH:MM").
CREATE tidut.
CREATE tidut.                           
tidut.UT = "Tidposter med avvikande befattning.".
CREATE tidut.
CREATE tidut.
CREATE tidut.   
ASSIGN
SUBSTRING(tidut.UT,1) = "DATUM"         
SUBSTRING(tidut.UT,10) = "DAG"                    
SUBSTRING(tidut.UT,14) = "AONR" 
SUBSTRING(tidut.UT,21) = CAPS(Guru.Konstanter:gdelnrk)  
SUBSTRING(tidut.UT,27) = "START" 
SUBSTRING(tidut.UT,33) = "SLUT"                   
SUBSTRING(tidut.UT,39) = "BEFATTNING".    
CREATE tidut.   
ASSIGN
tidut.UT = "========.===.======.=====.=====.=====.====================".  
GET FIRST tidbefq NO-LOCK.
DO WHILE AVAILABLE(BEFATTNINGSTAB): 
   IF PERSONALTAB.BEFATTNING NE TIDREGITAB.OVERTIDTILL THEN DO:
      finns = TRUE.
      CREATE tidut.   
      ASSIGN
      SUBSTRING(tidut.UT,1) = STRING(TIDREGITAB.DATUM,"99/99/99")         
      SUBSTRING(tidut.UT,10) = TIDREGITAB.DAG                    
      SUBSTRING(tidut.UT,14) = TIDREGITAB.AONR 
      SUBSTRING(tidut.UT,21) = STRING(TIDREGITAB.DELNR,">>>99") 
      SUBSTRING(tidut.UT,27) = STRING(TIDREGITAB.START,"99.99") 
      SUBSTRING(tidut.UT,33) = STRING(TIDREGITAB.SLUT,"99.99")                   
      SUBSTRING(tidut.UT,39) = BEFATTNINGSTAB.NAMN.        
   END.
   GET NEXT tidbefq NO-LOCK.
END.

IF finns = FALSE THEN DO:
   CREATE felmeddtemp.     
   felmeddtemp.FELMEDD = "Det finns inga tidposter med avikande befattning.". 
   RETURN.
END.
