/*BERKODHMT.P*/
{BEREDSKAP.I}
DEFINE INPUT PARAMETER pkod AS CHARACTER NO-UNDO.
DEFINE OUTPUT PARAMETER TABLE FOR berkodtemp.
FIND FIRST PERSONALTAB WHERE PERSONALTAB.PERSONALKOD = pkod NO-LOCK NO-ERROR.
OPEN QUERY bq FOR EACH BERKOD WHERE BERKOD.BEREDSKAPSAVTAL = PERSONALTAB.BEREDSKAPSAVTAL 
AND BERKOD.VALBAR = TRUE NO-LOCK.
GET FIRST bq NO-LOCK.
DO WHILE AVAILABLE(BERKOD): 
   CREATE berkodtemp.
      BUFFER-COPY BERKOD TO berkodtemp.
   GET NEXT bq NO-LOCK.
END.
   
