/*FLLON2N.P FLERDYGNSTRAKTAMENTE */
/*DEFINE SHARED VARIABLE globanv LIKE ANVANDARE.ANVANDARE NO-UNDO.*/
DEFINE SHARED VARIABLE regdatum LIKE TIDREGITAB.DATUM NO-UNDO.
DEFINE SHARED VARIABLE regvnr LIKE TIDREGITAB.VECKONUMMER NO-UNDO.
DEFINE SHARED VARIABLE tidtabrec AS RECID  NO-UNDO.
DEFINE SHARED VARIABLE persrec AS RECID NO-UNDO.  
DEFINE SHARED VARIABLE fostart AS LOGICAL NO-UNDO.
DEFINE SHARED VARIABLE foslut AS LOGICAL NO-UNDO.
DEFINE SHARED VARIABLE restart AS DECIMAL NO-UNDO.
DEFINE SHARED VARIABLE reslut AS DECIMAL NO-UNDO.
DEFINE VARIABLE hjrec AS RECID NO-UNDO.
DEFINE SHARED VARIABLE bdatum LIKE TIDREGITAB.DATUM NO-UNDO.
DEFINE SHARED VARIABLE avdatum LIKE TIDREGITAB.DATUM NO-UNDO.
DEFINE SHARED VARIABLE reddatum LIKE TIDREGITAB.DATUM NO-UNDO.
&Scoped-define NEW
{RESDEF.I}
/*DEFINE SHARED TEMP-TABLE respers    
   FIELD AONR LIKE TIDREGITAB.AONR
   FIELD DELNR LIKE TIDREGITAB.DELNR
   FIELD VECKONUMMER LIKE TIDREGITAB.VECKONUMMER
   FIELD DATUM LIKE TIDREGITAB.DATUM
   FIELD DAG LIKE TIDREGITAB.DAG
   FIELD START LIKE TIDREGITAB.START
   FIELD SLUT LIKE TIDREGITAB.SLUT 
   FIELD PRIS AS DECIMAL
   FIELD PRISTYP AS CHARACTER
   FIELD NATTRAKT AS LOGICAL FORMAT "JA/NEJ" LABEL "NATT TRAKT"
   FIELD OVERTIDUTTAG LIKE PERSONALTAB.OVERTIDUTTAG 
   FIELD BILFORARE LIKE TIDREGITAB.BILFORARE
   FIELD ENFLERDAGS LIKE TIDREGITAB.ENFLERDAGS  
   FIELD TIDREC AS RECID
   INDEX RESPERS IS PRIMARY DATUM START SLUT ASCENDING.
   DEFINE SHARED TEMP-TABLE kosters
   FIELD MPERSONALKOD LIKE PERSONALTAB.PERSONALKOD
   FIELD MDAG LIKE TIDREGITAB.DAG
   FIELD MVECKONUMMER LIKE TIDREGITAB.VECKONUMMER
   FIELD MDATUM LIKE TIDREGITAB.DATUM
   FIELD KR LIKE TIDREGITAB.LONTILLANTAL.
DEFINE SHARED TEMP-TABLE maltidfil
   FIELD MPERSONALKOD LIKE MALTIDTAB.PERSONALKOD
   FIELD MDAG LIKE MALTIDTAB.DAG
   FIELD MVECKONUMMER LIKE MALTIDTAB.VECKONUMMER
   FIELD MDATUM LIKE MALTIDTAB.DATUM
   FIELD MFRU LIKE MALTIDTAB.FRU
   FIELD MLUN LIKE MALTIDTAB.FRU
   FIELD MMID LIKE MALTIDTAB.FRU.*/
DEFINE SHARED VARIABLE enflerdygns AS LOGICAL FORMAT "ENDAGS/FLERDYGNS" NO-UNDO.
DEFINE SHARED VARIABLE bilforare AS LOGICAL FORMAT "JA/NEJ" NO-UNDO.
DEFINE SHARED VARIABLE resrec AS RECID NO-UNDO.
DEFINE BUFFER tidbuff FOR TIDREGITAB.
DEFINE SHARED VARIABLE FILL-IN-FRIMAT AS LOGICAL FORMAT "JA/NEJ":U INITIAL NO 
     VIEW-AS FILL-IN 
     SIZE 4 BY 1
       NO-UNDO.
DEFINE SHARED VARIABLE FILL-IN-REDTRAKT AS LOGICAL FORMAT "JA/NEJ":U INITIAL NO 
     LABEL "5. Reducerat traktamente                         ?" 
     VIEW-AS FILL-IN 
     SIZE 6 BY 1
       NO-UNDO.  
DEFINE SHARED VARIABLE FILL-IN-3MAN AS LOGICAL FORMAT "JA/NEJ":U INITIAL NO 
     VIEW-AS FILL-IN 
     SIZE 4 BY 1 NO-UNDO.
    

   
DEFINE VARIABLE maltid LIKE TIDREGITAB.LONTILLANTAL NO-UNDO.
DEFINE VARIABLE skatt LIKE TIDREGITAB.LONTILLANTAL NO-UNDO.
DEFINE VARIABLE skfri LIKE TIDREGITAB.LONTILLANTAL NO-UNDO.


DEFINE BUFFER lontillbuff FOR LONTILL.

     
FIND respers WHERE RECID(respers) = resrec NO-LOCK NO-ERROR.
FIND PERSONALTAB WHERE RECID(PERSONALTAB) = persrec NO-LOCK NO-ERROR.
FIND FIRST ANSTFORMTAB WHERE ANSTFORMTAB.ANSTALLNING = PERSONALTAB.ANSTALLNING
USE-INDEX ANSTF NO-LOCK NO-ERROR.
IF foslut = TRUE THEN ASSIGN reslut = 24.
IF fostart = TRUE THEN ASSIGN restart = 00.
IF respers.DATUM = bdatum THEN DO:
   IF fostart = TRUE AND bdatum = avdatum  THEN persrec = persrec.
   ELSE DO:   
      hjrec = RECID(respers).                  
      IF FILL-IN-REDTRAKT = TRUE AND FILL-IN-3MAN = TRUE
      AND  respers.DATUM GE reddatum THEN DO:
          /* 3 MÅNADER långtidsförrättning*/
          FIND FIRST LONFLER WHERE LONFLER.DAGTYP = "3MLANG" AND
          LONFLER.TRAAVTAL = PERSONALTAB.TRAAVTAL USE-INDEX FLON NO-LOCK NO-ERROR.
          IF NOT AVAILABLE LONFLER THEN DO:        
             FIND FIRST LONFLER WHERE LONFLER.TRAAVTAL = PERSONALTAB.TRAAVTAL AND
             LONFLER.RESSTART LE respers.SLUT AND
             LONFLER.RESSTART2 GE respers.SLUT AND LONFLER.DAGTYP = "UTRESA"
             USE-INDEX FLON NO-LOCK NO-ERROR.
         END.  
      END.
      ELSE IF FILL-IN-REDTRAKT = TRUE AND FILL-IN-3MAN = TRUE
      AND  respers.DATUM < reddatum THEN DO:
          /* 3 MÅNADER korttidsförrättning*/
          FIND FIRST LONFLER WHERE LONFLER.DAGTYP = "UTRESAR" AND
          LONFLER.TRAAVTAL = PERSONALTAB.TRAAVTAL AND LONFLER.RESSTART LE respers.SLUT AND
          LONFLER.RESSTART2 GE respers.SLUT USE-INDEX FLON NO-LOCK NO-ERROR.
          IF NOT AVAILABLE LONFLER THEN DO:        
             FIND FIRST LONFLER WHERE LONFLER.TRAAVTAL = PERSONALTAB.TRAAVTAL AND
             LONFLER.RESSTART LE restart AND
             LONFLER.RESSTART2 GE restart AND LONFLER.DAGTYP = "UTRESA"
             USE-INDEX FLON NO-LOCK NO-ERROR.
         END.  
      END.
      ELSE IF FILL-IN-REDTRAKT = TRUE AND FILL-IN-3MAN = FALSE
      AND  respers.DATUM GE reddatum THEN DO:
         /*långtidsförrättning*/
          FIND FIRST LONFLER WHERE LONFLER.DAGTYP = "REDUCER" AND
          LONFLER.TRAAVTAL = PERSONALTAB.TRAAVTAL USE-INDEX FLON NO-LOCK NO-ERROR.
          IF NOT AVAILABLE LONFLER THEN DO:        
             FIND FIRST LONFLER WHERE LONFLER.TRAAVTAL = PERSONALTAB.TRAAVTAL AND
             LONFLER.RESSTART LE restart AND
             LONFLER.RESSTART2 GE restart AND LONFLER.DAGTYP = "UTRESA"
             USE-INDEX FLON NO-LOCK NO-ERROR.
         END.  
      END. 
      ELSE DO:       
         IF FILL-IN-3MAN = TRUE THEN DO:
            /*3 MÅNADER korttidsförrättning*/
            FIND FIRST LONFLER WHERE LONFLER.TRAAVTAL = PERSONALTAB.TRAAVTAL AND
            LONFLER.RESSTART LE restart AND
            LONFLER.RESSTART2 GE restart AND LONFLER.DAGTYP = "UTRESAR"
            USE-INDEX FLON NO-LOCK NO-ERROR.
         END.
         ELSE DO:  
            FIND FIRST LONFLER WHERE LONFLER.TRAAVTAL = PERSONALTAB.TRAAVTAL AND
            LONFLER.RESSTART LE restart AND
            LONFLER.RESSTART2 GE restart AND  LONFLER.DAGTYP = "UTRESA"
            USE-INDEX FLON NO-LOCK NO-ERROR.
         END.   
      END.
      IF AVAILABLE LONFLER THEN DO:         
         CREATE TIDREGITAB.
         ASSIGN TIDREGITAB.PERSONALKOD = PERSONALTAB.PERSONALKOD
         SUBSTRING(TIDREGITAB.PROGRAM,1,158) = "FLLON2N" + STRING(TODAY) + STRING(TIME,"HH:MM") + Guru.Konstanter:globanv         
         TIDREGITAB.DAG = respers.DAG
         TIDREGITAB.VECKONUMMER = respers.VECKONUMMER
         TIDREGITAB.START = 7.00
         TIDREGITAB.SLUT = 7.00
         TIDREGITAB.TIDLOG = FALSE
         TIDREGITAB.LONTILLAGG = LONFLER.LONTILLAGG
         TIDREGITAB.LONTILLANTAL = LONFLER.LONTILLANTAL
         TIDREGITAB.AONR = respers.AONR
         TIDREGITAB.DELNR = respers.DELNR
         TIDREGITAB.BILFORARE = respers.BILFORARE
         TIDREGITAB.ENFLERDAGS = respers.ENFLERDAGS
         TIDREGITAB.DATUM = respers.DATUM.        
         FIND respers WHERE RECID(respers) = resrec NO-LOCK NO-ERROR.               
      END.      
   END.
END.
IF respers.DATUM > bdatum AND respers.DATUM < avdatum THEN DO:
   /* MELLANDAGAR */
   IF (Guru.Konstanter:globforetag = "GRAN")  AND FILL-IN-FRIMAT = TRUE THEN DO:
      FIND FIRST LONFLER WHERE LONFLER.DAGTYP = "FRIMAT" AND
      LONFLER.TRAAVTAL = PERSONALTAB.TRAAVTAL USE-INDEX FLON NO-LOCK NO-ERROR.
   END.  
   ELSE IF FILL-IN-REDTRAKT = TRUE AND FILL-IN-3MAN = TRUE
    AND  respers.DATUM GE reddatum THEN DO:
      /* 3 MÅNADER långtidsförrättning*/
      FIND FIRST LONFLER WHERE LONFLER.DAGTYP = "3MLANG" AND
      LONFLER.TRAAVTAL = PERSONALTAB.TRAAVTAL USE-INDEX FLON NO-LOCK NO-ERROR.
      IF NOT AVAILABLE LONFLER THEN DO:
         FIND FIRST LONFLER WHERE LONFLER.DAGTYP = "HELDAG" AND
         LONFLER.TRAAVTAL = PERSONALTAB.TRAAVTAL USE-INDEX FLON NO-LOCK NO-ERROR.
      END.   
   END.     
   ELSE IF FILL-IN-REDTRAKT = TRUE AND FILL-IN-3MAN = TRUE
   AND  respers.DATUM < reddatum THEN DO:
      /* 3 MÅNADER korttidsförrättning*/
      FIND FIRST LONFLER WHERE LONFLER.DAGTYP = "HELDAGR" AND
      LONFLER.TRAAVTAL = PERSONALTAB.TRAAVTAL USE-INDEX FLON NO-LOCK NO-ERROR.
      IF NOT AVAILABLE LONFLER THEN DO:
         FIND FIRST LONFLER WHERE LONFLER.DAGTYP = "HELDAG" AND
         LONFLER.TRAAVTAL = PERSONALTAB.TRAAVTAL USE-INDEX FLON NO-LOCK NO-ERROR.
      END.   
   END.
   ELSE IF FILL-IN-REDTRAKT = TRUE AND FILL-IN-3MAN = FALSE
    AND  respers.DATUM GE reddatum THEN DO:
      /*långtidsförrättning*/
      FIND FIRST LONFLER WHERE LONFLER.DAGTYP = "REDUCER" AND
      LONFLER.TRAAVTAL = PERSONALTAB.TRAAVTAL USE-INDEX FLON NO-LOCK NO-ERROR.
      IF NOT AVAILABLE LONFLER THEN DO:
         FIND FIRST LONFLER WHERE LONFLER.DAGTYP = "HELDAG" AND
         LONFLER.TRAAVTAL = PERSONALTAB.TRAAVTAL USE-INDEX FLON NO-LOCK NO-ERROR.
      END.   
   END.   
   ELSE DO:
      IF FILL-IN-3MAN = TRUE THEN DO:
         FIND FIRST LONFLER WHERE LONFLER.DAGTYP = "HELDAGR" AND
         LONFLER.TRAAVTAL = PERSONALTAB.TRAAVTAL USE-INDEX FLON NO-LOCK NO-ERROR.
      END.
      ELSE DO:
         FIND FIRST LONFLER WHERE LONFLER.DAGTYP = "HELDAG" AND
         LONFLER.TRAAVTAL = PERSONALTAB.TRAAVTAL USE-INDEX FLON NO-LOCK NO-ERROR.
      END.   
   END.   
   IF NOT AVAILABLE LONFLER THEN persrec = persrec.
   ELSE DO:
      FIND FIRST LONTILL WHERE LONTILL.KOD = ANSTFORMTAB.KOD AND 
      LONTILL.LONTILLAGG = LONFLER.LONTILLAGG NO-LOCK NO-ERROR.
      IF AVAILABLE LONTILL THEN DO:   
         CREATE TIDREGITAB.	
         ASSIGN TIDREGITAB.PERSONALKOD = PERSONALTAB.PERSONALKOD
         SUBSTRING(TIDREGITAB.PROGRAM,1,158) = "FLLON2N" + STRING(TODAY) + STRING(TIME,"HH:MM") + Guru.Konstanter:globanv
         TIDREGITAB.DAG = respers.DAG
         TIDREGITAB.VECKONUMMER = respers.VECKONUMMER
         TIDREGITAB.START = 7.00
         TIDREGITAB.SLUT = 7.00
         TIDREGITAB.TIDLOG = FALSE
         TIDREGITAB.LONTILLAGG = LONFLER.LONTILLAGG
         TIDREGITAB.LONTILLANTAL = LONFLER.LONTILLANTAL
         TIDREGITAB.AONR = respers.AONR
         TIDREGITAB.DELNR = respers.DELNR
         TIDREGITAB.BILFORARE = respers.BILFORARE
         TIDREGITAB.ENFLERDAGS = respers.ENFLERDAGS
         TIDREGITAB.DATUM = respers.DATUM.     
      END.           
   END.
END.        

IF respers.DATUM = avdatum THEN DO:   
   IF foslut = TRUE AND bdatum = avdatum  THEN persrec = persrec.
   ELSE DO:         
      IF FILL-IN-REDTRAKT = TRUE AND FILL-IN-3MAN = TRUE AND foslut = TRUE THEN DO:
          /* 3 MÅNADER långtidsförrättning*/
          FIND FIRST LONFLER WHERE LONFLER.DAGTYP = "3MLANG" AND
          LONFLER.TRAAVTAL = PERSONALTAB.TRAAVTAL USE-INDEX FLON NO-LOCK NO-ERROR.
          IF NOT AVAILABLE LONFLER THEN DO: 
             FIND FIRST LONFLER WHERE LONFLER.TRAAVTAL = PERSONALTAB.TRAAVTAL AND             
             LONFLER.RESSTART LE reslut AND
             LONFLER.RESSTART2 GE reslut AND LONFLER.DAGTYP = "HEMRESA"
             USE-INDEX FLON NO-LOCK NO-ERROR.
         END.
      END.
      ELSE IF FILL-IN-REDTRAKT = TRUE AND FILL-IN-3MAN = FALSE AND foslut = TRUE  THEN DO:
          /*långtidsförrättning*/
          FIND FIRST LONFLER WHERE LONFLER.DAGTYP = "REDUCER" AND
          LONFLER.TRAAVTAL = PERSONALTAB.TRAAVTAL USE-INDEX FLON NO-LOCK NO-ERROR.
          IF NOT AVAILABLE LONFLER THEN DO: 
             FIND FIRST LONFLER WHERE LONFLER.TRAAVTAL = PERSONALTAB.TRAAVTAL AND      
             LONFLER.RESSTART LE reslut AND
             LONFLER.RESSTART2 GE reslut AND  LONFLER.DAGTYP = "HEMRESA"
             USE-INDEX FLON NO-LOCK NO-ERROR.
         END.
      END.
      ELSE IF FILL-IN-REDTRAKT = TRUE AND FILL-IN-3MAN = TRUE THEN DO:
          /*HEMRESA > 3 MÅNADER INNAN 19?????????*/       
          FIND FIRST LONFLER WHERE LONFLER.DAGTYP = "3MLANGH" AND
          LONFLER.RESSTART LE reslut AND
          LONFLER.RESSTART2 GE reslut AND          
          LONFLER.TRAAVTAL = PERSONALTAB.TRAAVTAL USE-INDEX FLON NO-LOCK NO-ERROR.                
      END.
      ELSE IF FILL-IN-REDTRAKT = TRUE AND FILL-IN-3MAN = FALSE THEN DO:
          FIND FIRST LONFLER WHERE LONFLER.DAGTYP = "REDHEM" AND
          LONFLER.RESSTART LE reslut AND
          LONFLER.RESSTART2 GE reslut AND          
          LONFLER.TRAAVTAL = PERSONALTAB.TRAAVTAL USE-INDEX FLON NO-LOCK NO-ERROR.
          IF NOT AVAILABLE LONFLER THEN DO: 
             FIND FIRST LONFLER WHERE LONFLER.TRAAVTAL = PERSONALTAB.TRAAVTAL AND
             LONFLER.RESSTART LE reslut AND
             LONFLER.RESSTART2 GE reslut AND LONFLER.DAGTYP = "HEMRESA"
             USE-INDEX FLON NO-LOCK NO-ERROR.
         END.
      END.
      ELSE DO:       
         IF FILL-IN-3MAN = TRUE THEN DO:
            FIND FIRST LONFLER WHERE LONFLER.TRAAVTAL = PERSONALTAB.TRAAVTAL AND
            LONFLER.RESSTART LE reslut AND
            LONFLER.RESSTART2 GE reslut AND LONFLER.DAGTYP = "HEMRESAR"
            USE-INDEX FLON NO-LOCK NO-ERROR.
         END.
         ELSE DO:
            FIND FIRST LONFLER WHERE LONFLER.TRAAVTAL = PERSONALTAB.TRAAVTAL AND
            LONFLER.RESSTART LE reslut AND
            LONFLER.RESSTART2 GE reslut AND LONFLER.DAGTYP = "HEMRESA"
            USE-INDEX FLON NO-LOCK NO-ERROR.
         END.   
      END.   
      IF AVAILABLE LONFLER THEN DO:
         CREATE TIDREGITAB.
         ASSIGN TIDREGITAB.PERSONALKOD = PERSONALTAB.PERSONALKOD
         SUBSTRING(TIDREGITAB.PROGRAM,1,158) = "FLLON2N" + STRING(TODAY) + STRING(TIME,"HH:MM") + Guru.Konstanter:globanv
         TIDREGITAB.DAG = respers.DAG
         TIDREGITAB.VECKONUMMER = respers.VECKONUMMER
         TIDREGITAB.START = 7.00
         TIDREGITAB.SLUT = 7.00
         TIDREGITAB.TIDLOG = FALSE
         TIDREGITAB.LONTILLAGG = LONFLER.LONTILLAGG
         TIDREGITAB.LONTILLANTAL = LONFLER.LONTILLANTAL
         TIDREGITAB.AONR = respers.AONR
         TIDREGITAB.DELNR = respers.DELNR
         TIDREGITAB.BILFORARE = respers.BILFORARE
         TIDREGITAB.ENFLERDAGS = respers.ENFLERDAGS
         TIDREGITAB.DATUM = respers.DATUM.        
      END.      
   END.
END.
