/*FLTRAKT.P FLERDYGNSTRAKTAMENTE */
/*DEFINE SHARED VARIABLE globanv LIKE ANVANDARE.ANVANDARE NO-UNDO.*/
DEFINE SHARED VARIABLE regdatum LIKE TIDREGITAB.DATUM NO-UNDO.
DEFINE SHARED VARIABLE regvnr LIKE TIDREGITAB.VECKONUMMER NO-UNDO.
DEFINE SHARED VARIABLE tidtabrec AS RECID  NO-UNDO.
DEFINE SHARED VARIABLE persrec AS RECID NO-UNDO.
DEFINE SHARED VARIABLE bdatum LIKE TIDREGITAB.DATUM NO-UNDO.
DEFINE SHARED VARIABLE avdatum LIKE TIDREGITAB.DATUM NO-UNDO.
DEFINE SHARED VARIABLE enflerdygns AS LOGICAL FORMAT "ENDAGS/FLERDYGNS" NO-UNDO.
DEFINE SHARED VARIABLE bilforare AS LOGICAL FORMAT "JA/NEJ" NO-UNDO.
DEFINE SHARED VARIABLE nattrakt AS LOGICAL FORMAT "JA/NEJ" NO-UNDO.
DEFINE SHARED VARIABLE reddatum LIKE TIDREGITAB.DATUM NO-UNDO.

DEFINE VARIABLE skilln LIKE TIDREGITAB.START NO-UNDO.
DEFINE BUFFER tidbuff FOR TIDREGITAB.
DEFINE SHARED VARIABLE FILL-IN-REDTRAKT AS LOGICAL FORMAT "JA/NEJ":U INITIAL NO 
     LABEL "5. Reducerat traktamente                         ?" 
     VIEW-AS FILL-IN 
     SIZE 6 BY 1
       NO-UNDO.
DEFINE SHARED VARIABLE FILL-IN-3MAN AS LOGICAL FORMAT "JA/NEJ":U INITIAL NO 
     VIEW-AS FILL-IN 
     SIZE 4 BY 1 NO-UNDO.
DEFINE SHARED VARIABLE FILL-IN-FRIMAT AS LOGICAL FORMAT "JA/NEJ":U INITIAL NO 
     VIEW-AS FILL-IN 
     SIZE 4 BY 1
       NO-UNDO.       
FIND tidbuff WHERE RECID(tidbuff) = tidtabrec NO-LOCK NO-ERROR.
FIND PERSONALTAB WHERE RECID(PERSONALTAB) = persrec NO-LOCK NO-ERROR.

IF tidbuff.DATUM = bdatum THEN DO:   
   IF FILL-IN-REDTRAKT = TRUE AND FILL-IN-3MAN = TRUE  AND  tidbuff.DATUM GE reddatum THEN DO:
       /* 3 MÅNADER långtidsförrättning*/   
       FIND FIRST TRAKTFLER WHERE TRAKTFLER.DAGTYP = "3MLANG" AND
       TRAKTFLER.TRAAVTAL = PERSONALTAB.TRAAVTAL USE-INDEX FLTRAKT NO-LOCK NO-ERROR.
       IF NOT AVAILABLE TRAKTFLER THEN DO: 
          FIND FIRST TRAKTFLER WHERE TRAKTFLER.TRAAVTAL = PERSONALTAB.TRAAVTAL AND
          TRAKTFLER.RESSTART LE tidbuff.START AND
          TRAKTFLER.RESSTART2 GE tidbuff.START AND TRAKTFLER.DAGTYP = "UTRESA"
          USE-INDEX FLTRAKT NO-LOCK NO-ERROR.
      END.
   END.
   ELSE IF FILL-IN-REDTRAKT = TRUE AND FILL-IN-3MAN = TRUE  AND 
   tidbuff.DATUM < reddatum THEN DO:
       /* 3 MÅNADER korttidsförrättning*/   
       FIND FIRST TRAKTFLER WHERE TRAKTFLER.DAGTYP = "UTRESAR" AND
       TRAKTFLER.TRAAVTAL = PERSONALTAB.TRAAVTAL AND
       TRAKTFLER.RESSTART LE tidbuff.START AND TRAKTFLER.RESSTART2 GE tidbuff.START
       USE-INDEX FLTRAKT NO-LOCK NO-ERROR.
   END.
   ELSE IF FILL-IN-REDTRAKT = TRUE AND FILL-IN-3MAN = FALSE  AND 
   tidbuff.DATUM GE reddatum THEN DO:
       /*långtidsförrättning*/
       FIND FIRST TRAKTFLER WHERE TRAKTFLER.DAGTYP = "REDUCER" AND
       TRAKTFLER.TRAAVTAL = PERSONALTAB.TRAAVTAL USE-INDEX FLTRAKT NO-LOCK NO-ERROR.
       IF NOT AVAILABLE TRAKTFLER THEN DO: 
          FIND FIRST TRAKTFLER WHERE TRAKTFLER.TRAAVTAL = PERSONALTAB.TRAAVTAL AND
          TRAKTFLER.RESSTART LE tidbuff.START AND
          TRAKTFLER.RESSTART2 GE tidbuff.START AND TRAKTFLER.DAGTYP = "UTRESA"
          USE-INDEX FLTRAKT NO-LOCK NO-ERROR.
      END.
   END.
   ELSE DO:
      IF FILL-IN-3MAN = TRUE THEN DO:
         /*3 MÅNADER korttidsförrättning*/
         FIND FIRST TRAKTFLER WHERE TRAKTFLER.TRAAVTAL = PERSONALTAB.TRAAVTAL AND
         TRAKTFLER.RESSTART LE tidbuff.START AND
         TRAKTFLER.RESSTART2 GE tidbuff.START AND TRAKTFLER.DAGTYP = "UTRESAR"
         USE-INDEX FLTRAKT NO-LOCK NO-ERROR.
      END.
      ELSE DO:
         FIND FIRST TRAKTFLER WHERE TRAKTFLER.TRAAVTAL = PERSONALTAB.TRAAVTAL AND
         TRAKTFLER.RESSTART LE tidbuff.START AND
         TRAKTFLER.RESSTART2 GE tidbuff.START AND TRAKTFLER.DAGTYP = "UTRESA"
         USE-INDEX FLTRAKT NO-LOCK NO-ERROR.
      END.   
   END.   
   IF NOT AVAILABLE TRAKTFLER THEN persrec = persrec.
   ELSE DO:
      IF TRAKTFLER.TRAKTKOD NE '' THEN DO:
         CREATE TIDREGITAB.  
         ASSIGN TIDREGITAB.PERSONALKOD = PERSONALTAB.PERSONALKOD
         SUBSTRING(TIDREGITAB.PROGRAM,1,158) = "FLTRAKT" + STRING(TODAY) + STRING(TIME,"HH:MM") + Guru.Konstanter:globanv
         TIDREGITAB.DAG = tidbuff.DAG
         TIDREGITAB.VECKONUMMER = tidbuff.VECKONUMMER
         TIDREGITAB.START = 7.00
         TIDREGITAB.SLUT = 7.00
         TIDREGITAB.TIDLOG = FALSE
         TIDREGITAB.TRAKTAUTO = FALSE 
         TIDREGITAB.TRAKTKOD = TRAKTFLER.TRAKTKOD
         TIDREGITAB.TRAKTANTAL = TRAKTFLER.TRAKTANTAL 
         TIDREGITAB.AONR = tidbuff.AONR
         TIDREGITAB.DELNR = tidbuff.DELNR
         TIDREGITAB.BILFORARE = tidbuff.BILFORARE
         TIDREGITAB.ENFLERDAGS = tidbuff.ENFLERDAGS
         TIDREGITAB.DATUM = tidbuff.DATUM.         
      END.  
   END.
   IF nattrakt = TRUE THEN DO:
      FIND FIRST TRAKTFLER WHERE TRAKTFLER.TRAAVTAL = PERSONALTAB.TRAAVTAL AND
      TRAKTFLER.DAGTYP = "NATT" AND TRAKTFLER.ARBTIDMIN = 0
      USE-INDEX FLTRAKT NO-LOCK NO-ERROR.
      IF NOT AVAILABLE TRAKTFLER THEN persrec = persrec.
      ELSE DO:
         IF TRAKTFLER.TRAKTKOD NE '' THEN DO:
	    CREATE TIDREGITAB.  
            ASSIGN TIDREGITAB.PERSONALKOD = PERSONALTAB.PERSONALKOD
            SUBSTRING(TIDREGITAB.PROGRAM,1,158) = "FLTRAKT" + STRING(TODAY) + STRING(TIME,"HH:MM") + Guru.Konstanter:globanv
            TIDREGITAB.DAG = tidbuff.DAG
            TIDREGITAB.VECKONUMMER = tidbuff.VECKONUMMER
            TIDREGITAB.START = 7.00
            TIDREGITAB.SLUT = 7.00
            TIDREGITAB.TIDLOG = FALSE
            TIDREGITAB.TRAKTAUTO = FALSE 
            TIDREGITAB.TRAKTKOD = TRAKTFLER.TRAKTKOD
            TIDREGITAB.TRAKTANTAL = TRAKTFLER.TRAKTANTAL 
            TIDREGITAB.AONR = tidbuff.AONR
            TIDREGITAB.DELNR = tidbuff.DELNR
            TIDREGITAB.BILFORARE = tidbuff.BILFORARE
            TIDREGITAB.ENFLERDAGS = tidbuff.ENFLERDAGS
            TIDREGITAB.DATUM = tidbuff.DATUM.	    
         END. 
      END.
   END.
END.  

IF tidbuff.DATUM > bdatum AND tidbuff.DATUM < avdatum THEN DO:
   /* MELLANDAGAR */
   IF FILL-IN-REDTRAKT = TRUE AND FILL-IN-3MAN = TRUE AND tidbuff.DATUM GE reddatum THEN DO:
      /* 3 MÅNADER långtidsförrättning*/
      FIND FIRST TRAKTFLER WHERE TRAKTFLER.DAGTYP = "3MLANG" AND
      TRAKTFLER.TRAAVTAL = PERSONALTAB.TRAAVTAL USE-INDEX FLTRAKT NO-LOCK NO-ERROR.
      IF NOT AVAILABLE TRAKTFLER THEN DO:
         FIND FIRST TRAKTFLER WHERE TRAKTFLER.DAGTYP = "HELDAG" AND
         TRAKTFLER.TRAAVTAL = PERSONALTAB.TRAAVTAL USE-INDEX FLTRAKT NO-LOCK NO-ERROR.
      END.   
   END.
   ELSE IF FILL-IN-REDTRAKT = TRUE AND FILL-IN-3MAN = TRUE AND 
   tidbuff.DATUM < reddatum THEN DO:
      /* 3 MÅNADER korttidsförrättning*/
      FIND FIRST TRAKTFLER WHERE TRAKTFLER.DAGTYP = "HELDAGR" AND
      TRAKTFLER.TRAAVTAL = PERSONALTAB.TRAAVTAL USE-INDEX FLTRAKT NO-LOCK NO-ERROR.
      IF NOT AVAILABLE TRAKTFLER THEN DO:
         FIND FIRST TRAKTFLER WHERE TRAKTFLER.DAGTYP = "HELDAG" AND
         TRAKTFLER.TRAAVTAL = PERSONALTAB.TRAAVTAL USE-INDEX FLTRAKT NO-LOCK NO-ERROR.
      END.   
   END.
   ELSE IF FILL-IN-REDTRAKT = TRUE AND FILL-IN-3MAN = FALSE AND 
   tidbuff.DATUM GE reddatum THEN DO:
      /*långtidsförrättning*/
      FIND FIRST TRAKTFLER WHERE TRAKTFLER.DAGTYP = "REDUCER" AND
      TRAKTFLER.TRAAVTAL = PERSONALTAB.TRAAVTAL USE-INDEX FLTRAKT NO-LOCK NO-ERROR.
      IF NOT AVAILABLE TRAKTFLER THEN DO:
         FIND FIRST TRAKTFLER WHERE TRAKTFLER.DAGTYP = "HELDAG" AND
         TRAKTFLER.TRAAVTAL = PERSONALTAB.TRAAVTAL USE-INDEX FLTRAKT NO-LOCK NO-ERROR.
      END.   
   END.  
   ELSE DO:
      IF FILL-IN-3MAN = TRUE THEN DO:
         FIND FIRST TRAKTFLER WHERE TRAKTFLER.TRAAVTAL = PERSONALTAB.TRAAVTAL AND
         TRAKTFLER.DAGTYP = "HELDAGR"
         USE-INDEX FLTRAKT NO-LOCK NO-ERROR.
      END.
      ELSE DO:
         FIND FIRST TRAKTFLER WHERE TRAKTFLER.DAGTYP = "HELDAG" AND
         TRAKTFLER.TRAAVTAL = PERSONALTAB.TRAAVTAL USE-INDEX FLTRAKT NO-LOCK NO-ERROR.
      END.   
   END.   
   IF NOT AVAILABLE TRAKTFLER THEN persrec = persrec.
   ELSE DO:
      CREATE TIDREGITAB.     
      ASSIGN TIDREGITAB.PERSONALKOD = PERSONALTAB.PERSONALKOD
      SUBSTRING(TIDREGITAB.PROGRAM,1,158) = "FLTRAKT" + STRING(TODAY) + STRING(TIME,"HH:MM") + Guru.Konstanter:globanv
      TIDREGITAB.DAG = tidbuff.DAG
      TIDREGITAB.VECKONUMMER = tidbuff.VECKONUMMER
      TIDREGITAB.START = 7.00
      TIDREGITAB.SLUT = 7.00
      TIDREGITAB.TIDLOG = FALSE
      TIDREGITAB.TRAKTAUTO = FALSE 
      TIDREGITAB.TRAKTKOD = TRAKTFLER.TRAKTKOD
      TIDREGITAB.TRAKTANTAL = TRAKTFLER.TRAKTANTAL 
      TIDREGITAB.AONR = tidbuff.AONR
      TIDREGITAB.DELNR = tidbuff.DELNR
      TIDREGITAB.BILFORARE = tidbuff.BILFORARE
      TIDREGITAB.ENFLERDAGS = tidbuff.ENFLERDAGS
      TIDREGITAB.DATUM = tidbuff.DATUM.      
   END.   
   IF nattrakt = TRUE THEN DO:
      FIND FIRST TRAKTFLER WHERE TRAKTFLER.TRAAVTAL = PERSONALTAB.TRAAVTAL AND
      TRAKTFLER.DAGTYP = "NATT" AND TRAKTFLER.ARBTIDMIN = 0
      USE-INDEX FLTRAKT NO-LOCK NO-ERROR.
      IF NOT AVAILABLE TRAKTFLER THEN persrec = persrec.
      ELSE DO:
         IF TRAKTFLER.TRAKTKOD NE '' THEN DO:
            CREATE TIDREGITAB.
 	     ASSIGN TIDREGITAB.PERSONALKOD = PERSONALTAB.PERSONALKOD
            SUBSTRING(TIDREGITAB.PROGRAM,1,158) = "FLTRAKT" + STRING(TODAY) + STRING(TIME,"HH:MM") + Guru.Konstanter:globanv
            TIDREGITAB.DAG = tidbuff.DAG
            TIDREGITAB.VECKONUMMER = tidbuff.VECKONUMMER
            TIDREGITAB.START = 7.00
            TIDREGITAB.SLUT = 7.00
            TIDREGITAB.TIDLOG = FALSE
            TIDREGITAB.TRAKTAUTO = FALSE 
            TIDREGITAB.TRAKTKOD = TRAKTFLER.TRAKTKOD
            TIDREGITAB.TRAKTANTAL = TRAKTFLER.TRAKTANTAL 
            TIDREGITAB.AONR = tidbuff.AONR
            TIDREGITAB.DELNR = tidbuff.DELNR
            TIDREGITAB.BILFORARE = tidbuff.BILFORARE
            TIDREGITAB.ENFLERDAGS = tidbuff.ENFLERDAGS
            TIDREGITAB.DATUM = tidbuff.DATUM.	 	
	  END.
      END.
   END.
   IF tidbuff.START < 5.00 AND tidbuff.SLUT > tidbuff.START THEN DO:
      skilln = tidbuff.SLUT - tidbuff.START.
      IF skilln > 1 THEN DO:
	  FIND FIRST TRAKTFLER WHERE TRAKTFLER.TRAAVTAL = PERSONALTAB.TRAAVTAL AND
	  TRAKTFLER.RESSTART LE tidbuff.START AND
	  TRAKTFLER.RESSTART2 GE tidbuff.START AND
	  TRAKTFLER.DAGTYP = "NATT" AND TRAKTFLER.ARBTIDMIN > 0
         USE-INDEX FLTRAKT NO-LOCK NO-ERROR.
	  IF NOT AVAILABLE TRAKTFLER THEN persrec = persrec.
	  ELSE DO:
	     IF TRAKTFLER.TRAKTKOD NE '' THEN DO:
	        CREATE TIDREGITAB.
	        ASSIGN TIDREGITAB.PERSONALKOD = PERSONALTAB.PERSONALKOD
               SUBSTRING(TIDREGITAB.PROGRAM,1,158) = "FLTRAKT" + STRING(TODAY) + STRING(TIME,"HH:MM") + Guru.Konstanter:globanv
               TIDREGITAB.DAG = tidbuff.DAG
               TIDREGITAB.VECKONUMMER = tidbuff.VECKONUMMER
               TIDREGITAB.START = 7.00
               TIDREGITAB.SLUT = 7.00
               TIDREGITAB.TIDLOG = FALSE
               TIDREGITAB.TRAKTAUTO = FALSE 
               TIDREGITAB.TRAKTKOD = TRAKTFLER.TRAKTKOD
               TIDREGITAB.TRAKTANTAL = TRAKTFLER.TRAKTANTAL 
               TIDREGITAB.AONR = tidbuff.AONR
               TIDREGITAB.DELNR = tidbuff.DELNR
               TIDREGITAB.BILFORARE = tidbuff.BILFORARE
               TIDREGITAB.ENFLERDAGS = tidbuff.ENFLERDAGS
               TIDREGITAB.DATUM = tidbuff.DATUM.		
	     END.
         END.
      END.
   END.
END.
IF tidbuff.DATUM = avdatum THEN DO:   
   IF FILL-IN-REDTRAKT = TRUE AND FILL-IN-3MAN = TRUE AND tidbuff.START = tidbuff.SLUT AND tidbuff.START = 24.00 THEN DO:
       /* 3 MÅNADER långtidsförrättning*/ 
       FIND FIRST TRAKTFLER WHERE TRAKTFLER.DAGTYP = "3MLANG" AND
       TRAKTFLER.TRAAVTAL = PERSONALTAB.TRAAVTAL USE-INDEX FLTRAKT NO-LOCK NO-ERROR.
       IF NOT AVAILABLE TRAKTFLER THEN DO: 
          FIND FIRST TRAKTFLER WHERE TRAKTFLER.TRAAVTAL = PERSONALTAB.TRAAVTAL AND
          TRAKTFLER.RESSTART LE tidbuff.SLUT AND
          TRAKTFLER.RESSTART2 GE tidbuff.SLUT AND TRAKTFLER.DAGTYP = "HEMRESA"
          USE-INDEX FLTRAKT NO-LOCK NO-ERROR.
      END.
   END.
   ELSE IF FILL-IN-REDTRAKT = TRUE AND FILL-IN-3MAN = FALSE AND
   tidbuff.START = tidbuff.SLUT AND tidbuff.START = 24.00 THEN DO:
      /*långtidsförrättning*/
       FIND FIRST TRAKTFLER WHERE TRAKTFLER.DAGTYP = "REDUCER" AND
       TRAKTFLER.TRAAVTAL = PERSONALTAB.TRAAVTAL USE-INDEX FLTRAKT NO-LOCK NO-ERROR.
       IF NOT AVAILABLE TRAKTFLER THEN DO: 
          FIND FIRST TRAKTFLER WHERE TRAKTFLER.TRAAVTAL = PERSONALTAB.TRAAVTAL AND
          TRAKTFLER.RESSTART LE tidbuff.SLUT AND
          TRAKTFLER.RESSTART2 GE tidbuff.SLUT AND TRAKTFLER.DAGTYP = "HEMRESA"
          USE-INDEX FLTRAKT NO-LOCK NO-ERROR.
      END.
   END.
   ELSE IF FILL-IN-REDTRAKT = TRUE AND FILL-IN-3MAN = TRUE THEN DO:
      /*HEMRESA > 3 MÅNADER INNAN 19?????????*/
      FIND FIRST TRAKTFLER WHERE TRAKTFLER.DAGTYP = "3MLANGH" AND
      TRAKTFLER.RESSTART LE tidbuff.SLUT AND
      TRAKTFLER.RESSTART2 GE tidbuff.SLUT AND
      TRAKTFLER.TRAAVTAL = PERSONALTAB.TRAAVTAL USE-INDEX FLTRAKT NO-LOCK NO-ERROR.
   END.
   ELSE IF FILL-IN-REDTRAKT = TRUE AND FILL-IN-3MAN = FALSE THEN DO:
      FIND FIRST TRAKTFLER WHERE TRAKTFLER.DAGTYP = "REDHEM" AND
      TRAKTFLER.RESSTART LE tidbuff.SLUT AND
      TRAKTFLER.RESSTART2 GE tidbuff.SLUT AND
      TRAKTFLER.TRAAVTAL = PERSONALTAB.TRAAVTAL USE-INDEX FLTRAKT NO-LOCK NO-ERROR.
      IF NOT AVAILABLE TRAKTFLER THEN DO: 
          FIND FIRST TRAKTFLER WHERE TRAKTFLER.TRAAVTAL = PERSONALTAB.TRAAVTAL AND
          TRAKTFLER.RESSTART LE tidbuff.SLUT AND
          TRAKTFLER.RESSTART2 GE tidbuff.SLUT AND TRAKTFLER.DAGTYP = "HEMRESA"
          USE-INDEX FLTRAKT NO-LOCK NO-ERROR.
      END.
   END.
   ELSE DO:
      IF FILL-IN-3MAN = TRUE THEN DO:
         FIND FIRST TRAKTFLER WHERE TRAKTFLER.TRAAVTAL = PERSONALTAB.TRAAVTAL AND
         TRAKTFLER.RESSTART LE tidbuff.START AND
         TRAKTFLER.RESSTART2 GE tidbuff.START AND TRAKTFLER.DAGTYP = "HEMRESAR"
         USE-INDEX FLTRAKT NO-LOCK NO-ERROR.
      END.
      ELSE DO:  
         FIND FIRST TRAKTFLER WHERE TRAKTFLER.TRAAVTAL = PERSONALTAB.TRAAVTAL AND
         TRAKTFLER.RESSTART LE tidbuff.SLUT AND
         TRAKTFLER.RESSTART2 GE tidbuff.SLUT AND TRAKTFLER.DAGTYP = "HEMRESA"
         USE-INDEX FLTRAKT NO-LOCK NO-ERROR.
      END.   
   END.   
   IF NOT AVAILABLE TRAKTFLER THEN persrec = persrec.
   ELSE DO:
      IF TRAKTFLER.TRAKTKOD NE '' THEN DO:
         CREATE TIDREGITAB.
         ASSIGN TIDREGITAB.PERSONALKOD = PERSONALTAB.PERSONALKOD
         SUBSTRING(TIDREGITAB.PROGRAM,1,158) = "FLTRAKT" + STRING(TODAY) + STRING(TIME,"HH:MM") + Guru.Konstanter:globanv
         TIDREGITAB.DAG = tidbuff.DAG
         TIDREGITAB.VECKONUMMER = tidbuff.VECKONUMMER
         TIDREGITAB.START = 7.00
         TIDREGITAB.SLUT = 7.00
         TIDREGITAB.TIDLOG = FALSE
         TIDREGITAB.TRAKTAUTO = FALSE 
         TIDREGITAB.TRAKTKOD = TRAKTFLER.TRAKTKOD
         TIDREGITAB.TRAKTANTAL = TRAKTFLER.TRAKTANTAL 
         TIDREGITAB.AONR = tidbuff.AONR
         TIDREGITAB.DELNR = tidbuff.DELNR
         TIDREGITAB.BILFORARE = tidbuff.BILFORARE
         TIDREGITAB.ENFLERDAGS = tidbuff.ENFLERDAGS
         TIDREGITAB.DATUM = tidbuff.DATUM.       
      END.
   END.                                                            
   IF nattrakt = TRUE AND tidbuff.START = tidbuff.SLUT AND 
   tidbuff.START = 24.00 THEN DO:  
      FIND FIRST TRAKTFLER WHERE TRAKTFLER.TRAAVTAL = PERSONALTAB.TRAAVTAL AND
      TRAKTFLER.DAGTYP = "NATT" AND TRAKTFLER.ARBTIDMIN = 0
      USE-INDEX FLTRAKT NO-LOCK NO-ERROR.
      IF NOT AVAILABLE TRAKTFLER THEN persrec = persrec.
      ELSE DO:
         IF TRAKTFLER.TRAKTKOD NE '' THEN DO:
            CREATE TIDREGITAB.
	     ASSIGN TIDREGITAB.PERSONALKOD = PERSONALTAB.PERSONALKOD
            SUBSTRING(TIDREGITAB.PROGRAM,1,158) = "FLTRAKT" + STRING(TODAY) + STRING(TIME,"HH:MM") + Guru.Konstanter:globanv
            TIDREGITAB.DAG = tidbuff.DAG
            TIDREGITAB.VECKONUMMER = tidbuff.VECKONUMMER
            TIDREGITAB.START = 7.00
            TIDREGITAB.SLUT = 7.00
            TIDREGITAB.TIDLOG = FALSE
            TIDREGITAB.TRAKTAUTO = FALSE 
            TIDREGITAB.TRAKTKOD = TRAKTFLER.TRAKTKOD
            TIDREGITAB.TRAKTANTAL = TRAKTFLER.TRAKTANTAL 
            TIDREGITAB.AONR = tidbuff.AONR
            TIDREGITAB.DELNR = tidbuff.DELNR
            TIDREGITAB.BILFORARE = tidbuff.BILFORARE
            TIDREGITAB.ENFLERDAGS = tidbuff.ENFLERDAGS      
            TIDREGITAB.DATUM = tidbuff.DATUM.	 	
         END.
      END.
   END.
END.
