/*GODKOLLA.P*/
&Scoped-define NEW NEW
{GLOBVAR2DEL1.I}

DEFINE INPUT PARAMETER pkod AS CHARACTER NO-UNDO.
DEFINE INPUT PARAMETER regdatum AS DATE NO-UNDO.
DEFINE OUTPUT PARAMETER tillochmeddatum2 AS DATE NO-UNDO.
DEFINE OUTPUT PARAMETER TABLE FOR felmeddtemp.
FIND FIRST FORETAG NO-LOCK NO-ERROR.
FIND FIRST GODKOLL WHERE GODKOLL.PERSONALKOD = pkod AND
GODKOLL.DATAR = YEAR(regdatum) AND GODKOLL.DATMAN = MONTH(regdatum)
USE-INDEX PKODAR NO-LOCK NO-ERROR.            
IF FORETAG.FORETAG = "GKAL" OR FORETAG.FORETAG = "LULE" OR FORETAG.FORETAG = "SUND" OR FORETAG.FORETAG = "SNAT" OR FORETAG.FORETAG = "MISV"  OR FORETAG.FORETAG = "ELPA" THEN tillochmeddatum = tillochmeddatum.
ELSE IF AVAILABLE GODKOLL AND GODKOLL.DATUM GE regdatum THEN DO:
   CREATE felmeddtemp.
   felmeddtemp.FELMEDD = "Tidsedeln är godkänd/färdigrapporterad till och med " + STRING(GODKOLL.DATUM).
END.
IF AVAILABLE GODKOLL THEN tillochmeddatum = GODKOLL.DATUM.
ELSE tillochmeddatum = ?.
tillochmeddatum2 = tillochmeddatum.
       
