/*HITTATID.P*/
DEFINE INPUT PARAMETER tidtabrec AS RECID NO-UNDO.
DEFINE INPUT PARAMETER vadgora AS INTEGER NO-UNDO.
IF vadgora = 1 THEN DO:
   FIND TIDREGITAB WHERE RECID(TIDREGITAB) = tidtabrec NO-LOCK NO-ERROR.      
   IF AVAILABLE TIDREGITAB THEN DO:
   END.
END.
