/*KOSTAV2.P  MALTIDSAVDRAG 
om sverigedel på utlandsresa */
/*DEFINE SHARED VARIABLE globanv LIKE ANVANDARE.ANVANDARE NO-UNDO.*/
DEFINE SHARED VARIABLE regdatum LIKE TIDREGITAB.DATUM NO-UNDO.
DEFINE SHARED VARIABLE regvnr LIKE TIDREGITAB.VECKONUMMER NO-UNDO.
DEFINE SHARED VARIABLE tidtabrec AS RECID  NO-UNDO.
DEFINE SHARED VARIABLE persrec AS RECID NO-UNDO.
DEFINE SHARED VARIABLE bdatum LIKE TIDREGITAB.DATUM NO-UNDO.
DEFINE SHARED VARIABLE avdatum LIKE TIDREGITAB.DATUM NO-UNDO.
DEFINE SHARED VARIABLE resrec AS RECID NO-UNDO.
DEFINE SHARED VARIABLE enflerdygns AS LOGICAL FORMAT "ENDAGS/FLERDYGNS" NO-UNDO.
DEFINE SHARED VARIABLE bilforare AS LOGICAL FORMAT "JA/NEJ" NO-UNDO.
DEFINE SHARED VARIABLE nattrakt AS LOGICAL FORMAT "JA/NEJ" NO-UNDO.

DEFINE SHARED VARIABLE startresa LIKE TIDREGITAB.START NO-UNDO.
DEFINE SHARED VARIABLE slutresa LIKE TIDREGITAB.START NO-UNDO.
DEFINE VARIABLE koll1 AS INTEGER NO-UNDO.
&Scoped-define NEW
{RESDEF.I}
   
DEFINE SHARED VARIABLE FILL-IN-FRIMAT AS LOGICAL FORMAT "JA/NEJ":U INITIAL NO 
     VIEW-AS FILL-IN 
     SIZE 4 BY 1
       NO-UNDO.
        
DEFINE BUFFER tidbuff FOR TIDREGITAB.

  

FIND respers WHERE RECID(respers) = resrec NO-LOCK NO-ERROR.
FIND PERSONALTAB WHERE RECID(PERSONALTAB) = persrec NO-LOCK NO-ERROR.

FIND FIRST kostfil WHERE kostfil.MDATUM = respers.DATUM NO-LOCK NO-ERROR.
IF NOT AVAILABLE kostfil THEN RETURN.
IF respers.DATUM = bdatum THEN DO:
   FIND FIRST AVDRAGMALTID WHERE AVDRAGMALTID.RESSTART LE startresa AND
   AVDRAGMALTID.RESSTART2 GE startresa AND 
   AVDRAGMALTID.DAGTYP = "UTRESA" AND AVDRAGMALTID.ENFLER = enflerdygns 
   USE-INDEX MALTID NO-LOCK NO-ERROR.
   IF AVAILABLE AVDRAGMALTID  THEN DO:
      IF AVDRAGMALTID.AVDRAGSTYP NE 0 THEN DO:
         REPEAT:
	    FIND NEXT KFORMAN WHERE KFORMAN.TRAAVTAL = PERSONALTAB.TRAAVTAL AND
	    KFORMAN.FRUKOST = kostfil.MFRU AND KFORMAN.LUNCH = kostfil.MLUN AND
	    KFORMAN.MIDDAG = kostfil.MMID AND KFORMAN.ENFLER = enflerdygns AND 
	    KFORMAN.HEL = AVDRAGMALTID.AVDRAGSTYP
	    USE-INDEX KFORMAN NO-LOCK NO-ERROR.
	    IF NOT AVAILABLE KFORMAN THEN LEAVE.
	    CREATE TIDREGITAB.
	    IF enflerdygns = TRUE THEN ASSIGN TIDREGITAB.ENFLERDAGS = "Endag".
	    IF enflerdygns = FALSE THEN ASSIGN TIDREGITAB.ENFLERDAGS = "Flerdag".
	    ASSIGN TIDREGITAB.PERSONALKOD = PERSONALTAB.PERSONALKOD
	    SUBSTRING(TIDREGITAB.PROGRAM,1,158) = "kostAV2" + STRING(TODAY) + STRING(TIME,"HH:MM") + Guru.Konstanter:globanv	    
	    TIDREGITAB.DAG = respers.DAG
	    TIDREGITAB.VECKONUMMER = respers.VECKONUMMER
	    TIDREGITAB.DATUM = respers.DATUM
	    TIDREGITAB.START = 7.00
	    TIDREGITAB.SLUT = 7.00
	    TIDREGITAB.TIDLOG = FALSE
	    TIDREGITAB.LONTILLAGG = KFORMAN.AVDRAGSKOD      
	    TIDREGITAB.LONTILLANTAL = KFORMAN.AVANTAL
	    TIDREGITAB.AONR = respers.AONR
	    TIDREGITAB.DELNR = respers.DELNR
	    TIDREGITAB.BILFORARE = respers.BILFORARE.	     
         END.
      END.
   END.
END.
IF respers.DATUM > bdatum AND respers.DATUM < avdatum THEN DO:
   IF  Guru.Konstanter:globforetag = "GKAL"  AND FILL-IN-FRIMAT = TRUE THEN bdatum = bdatum.
   ELSE DO:
      koll1 = 1.
      /* MELLANDAGAR */
      FIND FIRST kostfil WHERE kostfil.MDATUM = respers.DATUM NO-LOCK NO-ERROR.
      IF NOT AVAILABLE kostfil THEN persrec = persrec.
      ELSE DO:
         FIND FIRST AVDRAGMALTID WHERE AVDRAGMALTID.DAGTYP = "HELDAG" AND
         AVDRAGMALTID.ENFLER = enflerdygns USE-INDEX MALTID NO-LOCK NO-ERROR.   
         IF AVDRAGMALTID.AVDRAGSTYP NE 0 THEN DO:
    	     block1:
	     REPEAT:
	        IF koll1 = 1 THEN DO:
	           FIND FIRST KFORMAN WHERE 
	           KFORMAN.TRAAVTAL = PERSONALTAB.TRAAVTAL AND
	 	    KFORMAN.FRUKOST = kostfil.MFRU AND
		    KFORMAN.LUNCH = kostfil.MLUN AND
	 	    KFORMAN.MIDDAG = kostfil.MMID AND
		    KFORMAN.ENFLER = enflerdygns AND 
		    KFORMAN.HEL = AVDRAGMALTID.AVDRAGSTYP
	 	    USE-INDEX KFORMAN NO-LOCK NO-ERROR.
		    IF NOT AVAILABLE KFORMAN THEN LEAVE block1.
	           koll1 = 0.
	        END.
	        ELSE DO:
	           FIND NEXT KFORMAN WHERE KFORMAN.TRAAVTAL = PERSONALTAB.TRAAVTAL AND
	           KFORMAN.FRUKOST = kostfil.MFRU AND
	           KFORMAN.LUNCH = kostfil.MLUN AND
	           KFORMAN.MIDDAG = kostfil.MMID AND
	           KFORMAN.ENFLER = enflerdygns AND 
	           KFORMAN.HEL = AVDRAGMALTID.AVDRAGSTYP
	           USE-INDEX KFORMAN NO-LOCK NO-ERROR.
	           IF NOT AVAILABLE KFORMAN THEN LEAVE block1.
	        END.
	        CREATE TIDREGITAB.
	        IF enflerdygns = TRUE THEN ASSIGN TIDREGITAB.ENFLERDAGS = "Endag".
	        IF enflerdygns = FALSE THEN ASSIGN TIDREGITAB.ENFLERDAGS = "Flerdag".
	        ASSIGN 
	        TIDREGITAB.PERSONALKOD = PERSONALTAB.PERSONALKOD
	        SUBSTRING(TIDREGITAB.PROGRAM,1,158) = "kostAV2" + STRING(TODAY) + STRING(TIME,"HH:MM") + Guru.Konstanter:globanv
	        TIDREGITAB.DAG = respers.DAG
	        TIDREGITAB.VECKONUMMER = respers.VECKONUMMER
	        TIDREGITAB.DATUM = respers.DATUM
	        TIDREGITAB.START = 7.00
	        TIDREGITAB.SLUT = 7.00
	        TIDREGITAB.TIDLOG = FALSE
	        TIDREGITAB.LONTILLAGG = KFORMAN.AVDRAGSKOD      
	        TIDREGITAB.LONTILLANTAL = KFORMAN.AVANTAL
	        TIDREGITAB.AONR = respers.AONR
	        TIDREGITAB.DELNR = respers.DELNR
	        TIDREGITAB.BILFORARE = respers.BILFORARE.	     
	     END. /*block1*/
	     koll1 = 1.
         END.     
      END.
   END.   
END.
koll1 = 1.
IF respers.DATUM = avdatum  AND avdatum > bdatum THEN DO:          
   FIND FIRST kostfil WHERE kostfil.MDATUM = respers.DATUM NO-LOCK NO-ERROR.
   IF NOT AVAILABLE kostfil THEN RETURN.
   FIND FIRST AVDRAGMALTID WHERE AVDRAGMALTID.RESSTART LE slutresa AND
   AVDRAGMALTID.RESSTART2 GE slutresa AND AVDRAGMALTID.DAGTYP = "HEMRESA" AND
   AVDRAGMALTID.ENFLER = enflerdygns USE-INDEX MALTID NO-LOCK NO-ERROR.
   IF NOT AVAILABLE AVDRAGMALTID THEN RETURN.
   IF AVDRAGMALTID.AVDRAGSTYP NE 0 THEN DO:   
      REPEAT:
 	  IF koll1 = 1 THEN DO:
	     FIND FIRST KFORMAN WHERE KFORMAN.TRAAVTAL = PERSONALTAB.TRAAVTAL AND
	     KFORMAN.FRUKOST = kostfil.MFRU AND
	     KFORMAN.LUNCH = kostfil.MLUN AND
	     KFORMAN.MIDDAG = kostfil.MMID AND
	     KFORMAN.ENFLER = enflerdygns AND KFORMAN.HEL = AVDRAGMALTID.AVDRAGSTYP
            USE-INDEX KFORMAN NO-LOCK NO-ERROR.
	     IF NOT AVAILABLE KFORMAN THEN LEAVE.
	     koll1 = 0.
	  END.
	  ELSE DO:
	     FIND NEXT KFORMAN WHERE KFORMAN.TRAAVTAL = PERSONALTAB.TRAAVTAL AND
	     KFORMAN.FRUKOST = kostfil.MFRU AND
	     KFORMAN.LUNCH = kostfil.MLUN AND
	     KFORMAN.MIDDAG = kostfil.MMID AND
	     KFORMAN.ENFLER = enflerdygns AND KFORMAN.HEL = AVDRAGMALTID.AVDRAGSTYP
	     USE-INDEX KFORMAN NO-LOCK NO-ERROR.
	     IF NOT AVAILABLE KFORMAN THEN LEAVE.
	  END.
	  CREATE TIDREGITAB.
	  IF enflerdygns = TRUE THEN ASSIGN TIDREGITAB.ENFLERDAGS = "Endag".
         IF enflerdygns = FALSE THEN ASSIGN TIDREGITAB.ENFLERDAGS = "Flerdag".
	  ASSIGN TIDREGITAB.PERSONALKOD = PERSONALTAB.PERSONALKOD
	  SUBSTRING(TIDREGITAB.PROGRAM,1,158) = "kostAV2" + STRING(TODAY) + STRING(TIME,"HH:MM") + Guru.Konstanter:globanv
	  TIDREGITAB.DAG = respers.DAG
	  TIDREGITAB.VECKONUMMER = respers.VECKONUMMER
	  TIDREGITAB.DATUM = respers.DATUM
	  TIDREGITAB.START = 7.00
	  TIDREGITAB.SLUT = 7.00
	  TIDREGITAB.TIDLOG = FALSE
	  TIDREGITAB.LONTILLAGG = KFORMAN.AVDRAGSKOD      
	  TIDREGITAB.LONTILLANTAL = KFORMAN.AVANTAL
	  TIDREGITAB.AONR = respers.AONR
	  TIDREGITAB.DELNR = respers.DELNR
	  TIDREGITAB.BILFORARE = respers.BILFORARE.	
      END.
   END.
END.
