/* LAGBAS.P KONTROLL */
DEFINE SHARED VARIABLE persrec AS RECID NO-UNDO.  
DEFINE SHARED VARIABLE tidtabrec AS RECID NO-UNDO.        
DEFINE SHARED VARIABLE regdatum AS DATE NO-UNDO.
DEFINE QUERY tidq FOR TIDREGITAB.
MESSAGE "LAGBAS"
VIEW-AS ALERT-BOX.
FIND PERSONALTAB WHERE RECID(PERSONALTAB) = persrec NO-LOCK NO-ERROR.
FIND FIRST ANSTFORMTAB WHERE
ANSTFORMTAB.ANSTALLNING = PERSONALTAB.ANSTALLNING 
USE-INDEX ANSTF NO-LOCK NO-ERROR.
FIND FIRST LAGBAS WHERE LAGBAS.KOD = ANSTFORMTAB.KOD USE-INDEX LAGBAS NO-LOCK NO-ERROR.
IF NOT AVAILABLE LAGBAS THEN LEAVE.                   
FIND FIRST TIDREGITAB WHERE  TIDREGITAB.PERSONALKOD = PERSONALTAB.PERSONALKOD AND
TIDREGITAB.DATUM = regdatum AND TIDREGITAB.LONTILLAGG = LAGBAS.LAGBASKOD AND
TIDREGITAB.LONAUTO = FALSE USE-INDEX PSTART NO-LOCK NO-ERROR.
IF AVAILABLE TIDREGITAB THEN regdatum = regdatum.
ELSE DO:
   OPEN QUERY tidq FOR EACH TIDREGITAB WHERE 
   TIDREGITAB.PERSONALKOD = PERSONALTAB.PERSONALKOD AND 
   TIDREGITAB.DATUM = regdatum AND
   TIDREGITAB.TIDLOG = TRUE NO-LOCK.
   GET FIRST tidq EXCLUSIVE-LOCK.
   DO WHILE AVAILABLE(TIDREGITAB): 
      FIND FIRST AONRTAB WHERE AONRTAB.AONR = TIDREGITAB.AONR 
      AND AONRTAB.DELNR = TIDREGITAB.DELNR USE-INDEX AONR NO-LOCK NO-ERROR.    
      IF NOT AVAILABLE AONRTAB THEN regdatum = regdatum.
      ELSE IF AONRTAB.OMRADE = "" THEN DO:
         IF TIDREGITAB.LONTILLAGG = LAGBAS.LAGBASKOD AND TIDREGITAB.LONTILLANTAL > 0 THEN DO:
            ASSIGN TIDREGITAB.LONTILLAGG = "" TIDREGITAB.LONTILLANTAL = 0.
         END.
      END.          
      ELSE IF TIDREGITAB.PRISTYP = "TOT.PRIS." THEN DO:
         ASSIGN                              
         TIDREGITAB.LAGBAS = TRUE
         TIDREGITAB.LONTILLAGG = LAGBAS.LAGBASKOD
         TIDREGITAB.LONTILLANTAL = TIDREGITAB.TOTALT
         TIDREGITAB.LONAUTO = TRUE.
      END.  
      GET NEXT tidq EXCLUSIVE-LOCK.
   END.
END.   

