/*LONKODHMT.P*/
{LONTILLAGG.I}
DEFINE INPUT PARAMETER pkod AS CHARACTER NO-UNDO.
DEFINE OUTPUT PARAMETER TABLE FOR lontilltemp.
DEFINE OUTPUT PARAMETER TABLE FOR lonkorttemp.
FIND FIRST PERSONALTAB WHERE PERSONALTAB.PERSONALKOD = pkod NO-LOCK NO-ERROR.
FIND FIRST ANSTFORMTAB WHERE ANSTFORMTAB.ANSTALLNING = PERSONALTAB.ANSTALLNING
USE-INDEX ANSTF NO-LOCK NO-ERROR.
OPEN QUERY bq FOR EACH LONTILL WHERE LONTILL.KOD = ANSTFORMTAB.KOD
AND LONTILL.VALBAR = TRUE NO-LOCK.
GET FIRST bq NO-LOCK.
DO WHILE AVAILABLE(LONTILL): 
   CREATE lontilltemp.
   BUFFER-COPY LONTILL TO lontilltemp.
   GET NEXT bq NO-LOCK.
END.
FOR EACH lontilltemp:
   FIND FIRST ERSATTNING WHERE ERSATTNING.KOD = ANSTFORMTAB.KOD AND
   ERSATTNING.LONTILLAGG = lontilltemp.LONTILLAGG USE-INDEX ERS NO-LOCK NO-ERROR.
   IF AVAILABLE ERSATTNING THEN DO:
      ASSIGN
      lontilltemp.MOMS = ERSATTNING.MOMS
      lontilltemp.ERSFINNS = TRUE.
   END.
   ELSE lontilltemp.ERSFINNS = FALSE.
END.
OPEN QUERY lkq FOR EACH LONKORT NO-LOCK.
GET FIRST lkq NO-LOCK.
DO WHILE AVAILABLE(LONKORT): 
   CREATE lonkorttemp.
   BUFFER-COPY LONKORT TO lonkorttemp.
   GET NEXT lkq NO-LOCK.
END.

