/*OBTID.P  TAR REDA PÅ ORDINARIE ARBETSTID EN GIVEN DAG      */
DEFINE SHARED VARIABLE regslut LIKE TIDREGITAB.SLUT NO-UNDO.
DEFINE SHARED VARIABLE regstart LIKE TIDREGITAB.START NO-UNDO.
DEFINE SHARED VARIABLE persrec AS RECID NO-UNDO.
DEFINE SHARED VARIABLE regdatum AS DATE NO-UNDO.

DEFINE SHARED VARIABLE slutar1 LIKE TIDREGITAB.SLUT NO-UNDO.
DEFINE SHARED VARIABLE startar1 LIKE TIDREGITAB.START NO-UNDO.
DEFINE SHARED VARIABLE slutar2 LIKE TIDREGITAB.SLUT NO-UNDO.
DEFINE SHARED VARIABLE startar2 LIKE TIDREGITAB.START NO-UNDO.
DEFINE SHARED VARIABLE slutar3 LIKE TIDREGITAB.SLUT NO-UNDO.
DEFINE SHARED VARIABLE startar3 LIKE TIDREGITAB.START NO-UNDO.
DEFINE SHARED VARIABLE obkod1 LIKE TIDREGITAB.LONTILLAGG NO-UNDO. 
DEFINE SHARED VARIABLE obkod2 LIKE TIDREGITAB.LONTILLAGG NO-UNDO.
DEFINE SHARED VARIABLE obkod3 LIKE TIDREGITAB.LONTILLAGG NO-UNDO.

DEFINE VARIABLE vschemat LIKE VECKOARBAV.VECKOSCHEMA NO-UNDO.

DEFINE TEMP-TABLE obavtemp
FIELD KOD AS CHARACTER
FIELD START AS DECIMAL
FIELD SLUT AS DECIMAL
FIELD LONTILLAGG AS CHARACTER
FIELD DATUM AS DATE
INDEX OBAV KOD DATUM START SLUT.

DEFINE TEMP-TABLE obttemp
FIELD KOD AS CHARACTER
FIELD DAGNR AS INTEGER
FIELD START AS DECIMAL
FIELD SLUT AS DECIMAL
FIELD LONTILLAGG AS CHARACTER
INDEX OBT KOD DAGNR START SLUT.

 


FIND PERSONALTAB WHERE RECID(PERSONALTAB) = persrec NO-LOCK NO-ERROR.
FIND FIRST ANSTFORMTAB WHERE ANSTFORMTAB.ANSTALLNING = PERSONALTAB.ANSTALLNING
USE-INDEX ANSTF NO-LOCK NO-ERROR.
ASSIGN
startar1 = 0
slutar1 = 0
obkod1= "" 
startar2 = 0
slutar2 = 0 
obkod2 = ""
startar3 = 0
slutar3 = 0
obkod3 = "".
/*lENA 20120222 index i tabell lart före start slut. blir fel måndagar med flera projekt. lösning temptabell med nytt index*/
EMPTY TEMP-TABLE obavtemp NO-ERROR.
EMPTY TEMP-TABLE obttemp NO-ERROR.  
FOR EACH OBAVTAB WHERE OBAVTAB.KOD = ANSTFORMTAB.KOD AND 
OBAVTAB.DATUM = regdatum NO-LOCK:
   CREATE obavtemp.
   BUFFER-COPY OBAVTAB TO obavtemp.   
END.
FOR EACH OBTAB WHERE OBTAB.KOD = ANSTFORMTAB.KOD AND 
OBTAB.DAGNR = WEEKDAY(regdatum) NO-LOCK:
   CREATE obttemp.
   BUFFER-COPY OBTAB TO obttemp.      
END.

            
FIND FIRST obavtemp WHERE obavtemp.KOD = ANSTFORMTAB.KOD AND 
obavtemp.DATUM = regdatum USE-INDEX OBAV NO-LOCK NO-ERROR.
IF NOT AVAILABLE obavtemp THEN DO:
   FIND FIRST obttemp WHERE obttemp.KOD = ANSTFORMTAB.KOD AND 
   obttemp.DAGNR = WEEKDAY(regdatum) USE-INDEX OBT NO-LOCK NO-ERROR.
   IF NOT AVAILABLE obttemp THEN RETURN.
   ELSE DO:
      ASSIGN
      startar1 = obttemp.START
      slutar1 = obttemp.SLUT
      obkod1 = obttemp.LONTILLAGG.
   END.
   FIND NEXT obttemp WHERE 
   obttemp.KOD = ANSTFORMTAB.KOD AND obttemp.DAGNR = WEEKDAY(regdatum)
   USE-INDEX OBT NO-LOCK NO-ERROR.
   IF NOT AVAILABLE obttemp THEN RETURN.
   ELSE DO:
      ASSIGN
      startar2 = obttemp.START
      slutar2 = obttemp.SLUT
      obkod2 = obttemp.LONTILLAGG.
   END.
   FIND NEXT obttemp WHERE 
   obttemp.KOD = ANSTFORMTAB.KOD AND obttemp.DAGNR = WEEKDAY(regdatum)
   USE-INDEX OBT NO-LOCK NO-ERROR.
   IF NOT AVAILABLE obttemp THEN RETURN.
   ELSE DO:
      ASSIGN
      startar3 = obttemp.START
      slutar3 = obttemp.SLUT
      obkod3 = obttemp.LONTILLAGG.
   END.
   
END. 
ELSE DO: 
   ASSIGN 
   startar1 = obavtemp.START
   slutar1 = obavtemp.SLUT
   obkod1 = obavtemp.LONTILLAGG.
   FIND NEXT obavtemp WHERE 
   obavtemp.KOD = ANSTFORMTAB.KOD AND obavtemp.DATUM = regdatum
   USE-INDEX OBAV NO-LOCK NO-ERROR.
   IF NOT AVAILABLE obavtemp THEN RETURN.
   ELSE DO:
      ASSIGN 
      startar2 = obavtemp.START
      slutar2 = obavtemp.SLUT
      obkod2 = obavtemp.LONTILLAGG.
   END.
   FIND NEXT obavtemp WHERE 
   obavtemp.KOD = ANSTFORMTAB.KOD AND obavtemp.DATUM = regdatum
   USE-INDEX OBAV NO-LOCK NO-ERROR.
   IF NOT AVAILABLE obavtemp THEN RETURN.
   ELSE DO:
      ASSIGN
      startar3 = obavtemp.START
      slutar3 = obavtemp.SLUT
      obkod3 = obavtemp.LONTILLAGG.
   END.
END.  
