/*OMRSKAPW.P*/

&Scoped-define NEW NEW
{VARFORETYP.I}
{OMRTEMPW.I}
DEFINE INPUT  PARAMETER globanv AS CHARACTER NO-UNDO.
DEFINE OUTPUT PARAMETER TABLE FOR omrtemp .
 

FIND FIRST FORETAG USE-INDEX FORETAG NO-LOCK NO-ERROR.   
RUN STYREAPP.P (INPUT FORETAG.FORETAG, INPUT-OUTPUT varforetypval, INPUT-OUTPUT varforetypchar, INPUT FALSE).
{STYREAPPLADD.I}
OPEN QUERY oq FOR EACH OMRADETAB WHERE OMRADETAB.ELVOMRKOD = 0 USE-INDEX OMR NO-LOCK.
GET FIRST oq NO-LOCK.
DO WHILE AVAILABLE(OMRADETAB):
   CREATE omrtemp.
   ASSIGN
   omrtemp.OMRADE = OMRADETAB.OMRADE
   omrtemp.NAMN = OMRADETAB.NAMN  
   omrtemp.AVDELNINGNR = OMRADETAB.AVDELNINGNR.
   GET NEXT oq NO-LOCK.
END.
 
IF Guru.Konstanter:globanv = CHR(69) + CHR(76) + CHR(80) + CHR(65) + CHR(79)   THEN RETURN.
IF Guru.Konstanter:globanv = "" THEN RETURN.
IF Guru.Konstanter:varforetypchar[4] = "ja" THEN DO:
   FOR EACH omrtemp:
      IF omrtemp.OMRADE = "" THEN.
      ELSE DO: 
         FIND FIRST OFFERT WHERE OFFERT.OFFNR = 1 AND OFFERT.OFFANV = Guru.Konstanter:globanv AND OFFERT.OMRADE = omrtemp.OMRADE NO-LOCK NO-ERROR.
         IF NOT AVAILABLE OFFERT THEN DO:
            DELETE omrtemp.
         END.
      END.   
   END.
END.
  
