/*OMRSKAPC.P*/
&Scoped-define STATIC 
{OMRTEMPC.I}
DEFINE OUTPUT PARAMETER TABLE FOR omrtemp .

FIND FIRST FORETAG USE-INDEX FORETAG NO-LOCK NO-ERROR.   
OPEN QUERY oq FOR EACH OMRADETAB WHERE OMRADETAB.ELVOMRKOD = 0 USE-INDEX OMR NO-LOCK.
GET FIRST oq NO-LOCK.
DO WHILE AVAILABLE(OMRADETAB):
   CREATE omrtemp.
   BUFFER-COPY OMRADETAB TO omrtemp.
      
   GET NEXT oq NO-LOCK.
END.

  
