/*OVEKODHMT.P*/
{OVERKODER.I}
DEFINE INPUT PARAMETER pkod AS CHARACTER NO-UNDO.
DEFINE OUTPUT PARAMETER TABLE FOR overkodtemp.
FIND FIRST PERSONALTAB WHERE PERSONALTAB.PERSONALKOD = pkod NO-LOCK NO-ERROR.
FIND FIRST ANSTFORMTAB WHERE ANSTFORMTAB.ANSTALLNING = PERSONALTAB.ANSTALLNING
USE-INDEX ANSTF NO-LOCK NO-ERROR.
OPEN QUERY bq FOR EACH OVERKOD WHERE OVERKOD.KOD = ANSTFORMTAB.KOD
NO-LOCK.
GET FIRST bq NO-LOCK.
DO WHILE AVAILABLE(OVERKOD): 
   CREATE overkodtemp.
   BUFFER-COPY OVERKOD TO overkodtemp.
   GET NEXT bq NO-LOCK.
END.

