/* OVEREG.P*/
&Scoped-define NEW NEW
{TIDALLT.I}
DEFINE INPUT PARAMETER ganv AS CHARACTER NO-UNDO.
DEFINE INPUT PARAMETER vadgora AS INTEGER NO-UNDO.
DEFINE INPUT PARAMETER pkod AS CHARACTER NO-UNDO.
DEFINE INPUT PARAMETER TABLE FOR extratidallt.
DEFINE OUTPUT PARAMETER placerarec AS RECID.
DEFINE OUTPUT PARAMETER TABLE FOR overtemp.
DEFINE NEW SHARED VARIABLE regdatum AS DATE NO-UNDO.
DEFINE NEW SHARED VARIABLE tidtabrec AS RECID  NO-UNDO.
/*DEFINE NEW SHARED VARIABLE globanv LIKE ANVANDARE.ANVANDARE NO-UNDO.*/

IF vadgora = 1 THEN DO:
   FIND FIRST PERSONALTAB WHERE PERSONALTAB.PERSONALKOD = pkod NO-LOCK NO-ERROR.
   FIND FIRST ANSTFORMTAB WHERE ANSTFORMTAB.ANSTALLNING = PERSONALTAB.ANSTALLNING
   USE-INDEX ANSTF NO-LOCK NO-ERROR.
   FOR EACH extratidallt:
      regdatum = extratidallt.DATUM.
      DO TRANSACTION:
         IF extratidallt.RECTIDVIS = ? THEN DO: 
            CREATE TIDREGITAB.
            BUFFER-COPY extratidallt EXCEPT extratidallt.RECTIDVIS TO TIDREGITAB.
            ASSIGN
            TIDREGITAB.OVERTIDTILL = ""
            SUBSTRING(TIDREGITAB.PROGRAM,1,158) = "ANDOVER" + STRING(TODAY) + STRING(TIME,"HH:MM") + Guru.Konstanter:globanv            
            TIDREGITAB.PERSONALKOD = PERSONALTAB.PERSONALKOD.     
         END.
         ELSE DO:
            FIND FIRST TIDREGITAB WHERE RECID(TIDREGITAB) = extratidallt.RECTIDVIS NO-ERROR.
            BUFFER-COPY extratidallt EXCEPT extratidallt.RECTIDVIS TO TIDREGITAB.
            TIDREGITAB.PERSONALKOD = PERSONALTAB.PERSONALKOD.     
            ASSIGN 
            TIDREGITAB.OVERTIDTILL = ""
            TIDREGITAB.TIDLOG = FALSE
            SUBSTRING(TIDREGITAB.PROGRAM,1,158) = "ANDOVER" + STRING(TODAY) + STRING(TIME,"HH:MM") + Guru.Konstanter:globanv
            TIDREGITAB.SLUT = 7.00
            TIDREGITAB.START = 7.00          
            TIDREGITAB.OVERANTAL = 0
            TIDREGITAB.OST1 = 00.00
            TIDREGITAB.OSL1 = 00.00
            TIDREGITAB.OKOD2 = " "
            TIDREGITAB.OANT2 = 00.00
            TIDREGITAB.OST2 = 00.00
            TIDREGITAB.OSL2 = 00.00
            TIDREGITAB.OKOD3 = " "
            TIDREGITAB.OANT3 = 00.00
            TIDREGITAB.OST3 = 00.00
            TIDREGITAB.OSL3 = 00.00
            TIDREGITAB.OVERAUTO = FALSE.    
         END.        
      END.  
      
      placerarec = RECID(TIDREGITAB).
      CREATE overtemp.
      ASSIGN
      overtemp.PERSONALKOD = ""
      tidtabrec = RECID(TIDREGITAB)
      overtemp.RECTIDVIS = RECID(TIDREGITAB).      
      DELETE extratidallt.
      
   END.
END.
