/*RESTJAND.P*/
&Scoped-define NEW NEW
{GLOBVAR2DEL1.I}

DEFINE INPUT PARAMETER vadgora AS INTEGER NO-UNDO.
DEFINE INPUT PARAMETER pkod AS CHARACTER NO-UNDO.
DEFINE INPUT PARAMETER bdatum AS DATE NO-UNDO.
DEFINE INPUT PARAMETER enfle AS CHARACTER NO-UNDO.
DEFINE OUTPUT PARAMETER varaonr AS CHARACTER NO-UNDO.
DEFINE OUTPUT PARAMETER vardelnr AS INTEGER NO-UNDO.
DEFINE INPUT-OUTPUT PARAMETER hjstart AS DECIMAL NO-UNDO.
DEFINE VARIABLE regdatum AS DATE NO-UNDO.
IF vadgora = 1 THEN DO:
   FIND FIRST PERSONALTAB WHERE PERSONALTAB.PERSONALKOD = pkod NO-LOCK NO-ERROR.
   FIND FIRST TIDREGITAB WHERE TIDREGITAB.PERSONALKOD = PERSONALTAB.PERSONALKOD AND
   TIDREGITAB.DATUM = bdatum AND TIDREGITAB.ENFLERDAGS = enfle AND 
   TIDREGITAB.GODKAND = '' AND TIDREGITAB.LONTILLAGG NE "" AND 
   TIDREGITAB.PROGRAM BEGINS "FLLON" 
   USE-INDEX PSTART NO-LOCK NO-ERROR.
   IF AVAILABLE TIDREGITAB THEN DO:
      FIND FIRST LONFLER WHERE LONFLER.TRAAVTAL = PERSONALTAB.TRAAVTAL AND
      LONFLER.LONTILLAGG = TIDREGITAB.LONTILLAGG AND 
      LONFLER.DAGTYP = "UTRESA" USE-INDEX FLON NO-LOCK NO-ERROR.
      IF AVAILABLE LONFLER THEN DO:
         IF LONFLER.RESSTART GE 12.00 THEN ASSIGN hjstart = 12.00.
      END.
   END.
   IF NOT AVAILABLE TIDREGITAB THEN DO:
      FIND FIRST TIDREGITAB WHERE TIDREGITAB.PERSONALKOD = PERSONALTAB.PERSONALKOD AND
      TIDREGITAB.DATUM = bdatum AND TIDREGITAB.ENFLERDAGS = enfle AND 
      TIDREGITAB.GODKAND = '' AND TIDREGITAB.TRAKTKOD NE "" AND 
      TIDREGITAB.PROGRAM BEGINS "FLTRA" USE-INDEX PSTART NO-LOCK NO-ERROR.
      IF AVAILABLE TIDREGITAB THEN DO:
         FIND FIRST TRAKTFLER WHERE TRAKTFLER.TRAAVTAL = PERSONALTAB.TRAAVTAL AND
         TRAKTFLER.TRAKTKOD = TIDREGITAB.TRAKTKOD AND 
         TRAKTFLER.DAGTYP = "UTRESA" USE-INDEX FLTRAKT NO-LOCK NO-ERROR.
         IF AVAILABLE TRAKTFLER THEN DO:
            IF TRAKTFLER.RESSTART GE 12.00 THEN ASSIGN hjstart = 12.00.
         END.
      END.
   END.
END.
IF vadgora = 2 THEN DO:
   FIND FIRST TIDREGITAB WHERE TIDREGITAB.PERSONALKOD = pkod AND
   TIDREGITAB.DATUM = regdatum AND TIDREGITAB.ENFLERDAGS = enfle AND 
   TIDREGITAB.GODKAND = '' USE-INDEX PSTART NO-LOCK NO-ERROR.
   IF AVAILABLE TIDREGITAB THEN DO:
      ASSIGN
      varaonr = TIDREGITAB.AONR
      vardelnr = TIDREGITAB.DELNR.
   END.
   ELSE varaonr = "".
END.
