/*TIDSLUT.P*/
DEFINE SHARED TEMP-TABLE felmeddtemp 
     FIELD FELMEDD AS CHARACTER
     FIELD VAL AS INTEGER.
DEFINE SHARED VARIABLE regstart LIKE TIDREGITAB.START NO-UNDO. 
DEFINE SHARED VARIABLE regslut LIKE TIDREGITAB.SLUT NO-UNDO.
DEFINE SHARED VARIABLE regvnr AS INTEGER FORMAT "999" NO-UNDO.
DEFINE SHARED VARIABLE regdagnamn AS CHARACTER FORMAT "X(3)" NO-UNDO.        
DEFINE SHARED VARIABLE regdatum AS DATE NO-UNDO.
DEFINE SHARED VARIABLE persrec AS RECID NO-UNDO.
DEFINE  SHARED VARIABLE musz AS LOGICAL NO-UNDO.
DEFINE SHARED VARIABLE vart AS CHARACTER FORMAT "X(3)" NO-UNDO. 
DEFINE SHARED VARIABLE tidtabrec AS RECID NO-UNDO.         
FIND PERSONALTAB WHERE RECID(PERSONALTAB) = persrec NO-LOCK NO-ERROR.
IF musz = FALSE THEN DO:                /*EJ DYGNSBRYT*/
   musz = FALSE.
   FIND FIRST TIDREGITAB WHERE 
   TIDREGITAB.PERSONAL = PERSONALTAB.PERSONALKOD AND
   TIDREGITAB.DATUM = regdatum AND TIDREGITAB.START < regslut AND
   TIDREGITAB.SLUT >= regslut AND TIDREGITAB.TIDLOG = TRUE 
   USE-INDEX PSTART NO-LOCK NO-ERROR.   
   IF NOT AVAILABLE TIDREGITAB THEN DO: 
      FIND FIRST TIDREGITAB WHERE 
      TIDREGITAB.PERSONAL = PERSONALTAB.PERSONALKOD AND
      TIDREGITAB.DATUM = regdatum AND TIDREGITAB.START > regstart AND
      TIDREGITAB.SLUT < regslut AND TIDREGITAB.TIDLOG = TRUE AND
      TIDREGITAB.RECTIDVIS NE tidtabrec
      USE-INDEX PSTART NO-LOCK NO-ERROR.        
      IF NOT AVAILABLE TIDREGITAB THEN DO:    
         musz = FALSE.
         RETURN.   
      END.  
      ELSE DO:
         RUN dubbel_UI.
         RETURN.          
      END.
   END.  
   ELSE DO:
      RUN dubbel_UI.
      RETURN. 
   END.   
END.   
ELSE DO:
   musz = FALSE.
   FIND FIRST TIDREGITAB WHERE 
   TIDREGITAB.PERSONAL = PERSONALTAB.PERSONALKOD AND
   TIDREGITAB.DATUM = regdatum AND TIDREGITAB.START GE regstart AND
   TIDREGITAB.SLUT LE 24.00 AND TIDREGITAB.TIDLOG = TRUE 
   USE-INDEX PSTART NO-LOCK NO-ERROR.
   IF NOT AVAILABLE TIDREGITAB THEN DO:
      musz = FALSE.   
      FIND FIRST TIDREGITAB WHERE 
      TIDREGITAB.PERSONAL = PERSONALTAB.PERSONALKOD AND
      TIDREGITAB.DATUM = (regdatum + 1) AND TIDREGITAB.START GE 00.00 AND
      TIDREGITAB.SLUT LE regslut AND TIDREGITAB.TIDLOG = TRUE 
      USE-INDEX PSTART NO-LOCK NO-ERROR.
      IF NOT AVAILABLE TIDREGITAB THEN DO:
         musz = FALSE.      
         RETURN.
      END.
      ELSE DO:
         RUN dubbel_UI.
         RETURN. 
      END.    
   END.  
   ELSE DO:
      RUN dubbel_UI.  
      RETURN.           
   END.     
END.                
PROCEDURE dubbel_UI. 
   IF vart = "AND" OR vart = "NYA" THEN IF RECID(TIDREGITAB) = tidtabrec THEN RETURN.
   musz = TRUE.
   CREATE felmeddtemp. 
   felmeddtemp.felmedd = "Det finns redan en registrering med start " +
   STRING(TIDREGITAB.START) + " och slut" + STRING(TIDREGITAB.SLUT) + " den " + 
   STRING(TIDREGITAB.DATUM) + "!".     
END PROCEDURE. 
