/*TIDSTART.P*/
DEFINE SHARED TEMP-TABLE felmeddtemp 
     FIELD FELMEDD AS CHARACTER
     FIELD VAL AS INTEGER.
DEFINE SHARED VARIABLE regstart LIKE TIDREGITAB.START NO-UNDO. 
DEFINE SHARED VARIABLE regslut LIKE TIDREGITAB.SLUT NO-UNDO.
DEFINE SHARED VARIABLE regvnr AS INTEGER FORMAT "999" NO-UNDO.
DEFINE SHARED VARIABLE regdagnamn AS CHARACTER FORMAT "X(3)" NO-UNDO.        
DEFINE SHARED VARIABLE regdatum AS DATE NO-UNDO.
DEFINE SHARED VARIABLE persrec AS RECID NO-UNDO.
DEFINE SHARED VARIABLE musz AS LOGICAL NO-UNDO.  
DEFINE SHARED VARIABLE vart AS CHARACTER FORMAT "X(3)" NO-UNDO. 
DEFINE SHARED VARIABLE tidtabrec AS RECID NO-UNDO.
FIND PERSONALTAB WHERE RECID(PERSONALTAB) = persrec NO-LOCK NO-ERROR. 
FIND FIRST TIDREGITAB WHERE 
TIDREGITAB.PERSONAL = PERSONALTAB.PERSONALKOD AND
TIDREGITAB.DATUM = regdatum AND TIDREGITAB.START LE regstart AND
TIDREGITAB.SLUT > regstart AND TIDREGITAB.TIDLOG = TRUE 
USE-INDEX PSTART NO-LOCK NO-ERROR.
IF NOT AVAILABLE TIDREGITAB THEN DO:
   musz = FALSE.
   RETURN.
END.
ELSE DO:    

   IF vart = "AND" OR vart = "NYA"  THEN IF RECID(TIDREGITAB) = tidtabrec THEN RETURN.
   musz = TRUE.
   CREATE felmeddtemp. 
   felmeddtemp.felmedd = "Det finns redan en registrering med start " +
   STRING(TIDREGITAB.START) + " och slut" + STRING(TIDREGITAB.SLUT) + " den " + 
   STRING(TIDREGITAB.DATUM) + "!".  
  
   RETURN.
END.                
 
