/*TIDSEDH.P*/
DEFINE INPUT PARAMETER sok0 AS INTEGER NO-UNDO.
DEFINE INPUT-OUTPUT PARAMETER sok1 AS CHARACTER NO-UNDO .
DEFINE INPUT-OUTPUT PARAMETER sok2 AS INTEGER NO-UNDO.
DEFINE INPUT-OUTPUT PARAMETER sok3 AS DECIMAL NO-UNDO.
DEFINE INPUT-OUTPUT PARAMETER sok4 AS DATE NO-UNDO.
DEFINE VARIABLE sokhjalp AS DECIMAL EXTENT 10 NO-UNDO.
DEFINE VARIABLE sokhjalp2 AS LOGICAL NO-UNDO.
DEFINE VARIABLE testdatum AS DATE NO-UNDO.
IF sok0 = 1 THEN DO:
END.
