/*TIDSISTA.P*/    
DEFINE SHARED VARIABLE persrec AS RECID NO-UNDO. 
DEFINE SHARED VARIABLE tidtabrec AS RECID NO-UNDO.
DEFINE SHARED VARIABLE vart AS CHARACTER FORMAT "X(3)" NO-UNDO.
DEFINE SHARED VARIABLE regvnr AS INTEGER FORMAT "999" NO-UNDO.
DEFINE SHARED VARIABLE regdagnamn AS CHARACTER FORMAT "X(3)" NO-UNDO.        
DEFINE SHARED VARIABLE regdatum AS DATE NO-UNDO.
DEFINE SHARED VARIABLE musz AS LOGICAL NO-UNDO.
IF vart = "OVE" THEN DO:
   IF WEEKDAY(TODAY) = 1 THEN regdatum = TODAY - 2.
   ELSE IF WEEKDAY(TODAY) = 2 THEN regdatum = TODAY - 3.
   ELSE IF WEEKDAY(TODAY) = 3 THEN regdatum = TODAY - 1.
   ELSE IF WEEKDAY(TODAY) = 4 THEN regdatum = TODAY - 1.
   ELSE IF WEEKDAY(TODAY) = 5 THEN regdatum = TODAY - 1. 
   ELSE IF WEEKDAY(TODAY) = 6 THEN regdatum = TODAY - 1.
   ELSE IF WEEKDAY(TODAY) = 7 THEN regdatum = TODAY - 1. 
END. 
ELSE IF vart = "TID" THEN regdatum = regdatum.   
ELSE regdatum = TODAY.
FIND PERSONALTAB WHERE RECID(PERSONALTAB) = persrec 
NO-LOCK NO-ERROR.
FIND LAST TIDREGITAB WHERE TIDREGITAB.PERSONAL = PERSONALTAB.PERSONALKOD AND
TIDREGITAB.DATUM = regdatum AND TIDREGITAB.TIDLOG = TRUE
USE-INDEX PSTART NO-LOCK NO-ERROR.
IF NOT AVAILABLE TIDREGITAB THEN DO:
   FIND LAST TIDREGITAB WHERE TIDREGITAB.PERSONAL = PERSONALTAB.PERSONALKOD AND 
   TIDREGITAB.DATUM <= regdatum AND TIDREGITAB.TIDLOG = TRUE USE-INDEX PSTART NO-LOCK NO-ERROR.
   IF NOT AVAILABLE TIDREGITAB THEN DO:
      musz = TRUE.
      RETURN.
   END.  
END.   
tidtabrec = RECID(TIDREGITAB).
RETURN.
