/*TJHAMT.P*/
&Scoped-define NEW NEW
{TIDALLT.I}
DEFINE INPUT PARAMETER pkod AS CHARACTER NO-UNDO.
DEFINE INPUT PARAMETER brwbdatum AS DATE NO-UNDO.
DEFINE INPUT PARAMETER brwavdatum AS DATE NO-UNDO.
DEFINE INPUT PARAMETER enfle AS CHARACTER NO-UNDO.
DEFINE OUTPUT PARAMETER TABLE FOR restidallt.
OPEN QUERY tidq 
FOR EACH TIDREGITAB WHERE TIDREGITAB.PERSONALKOD = pkod AND
TIDREGITAB.DATUM >= brwbdatum AND TIDREGITAB.DATUM <= brwavdatum AND
TIDREGITAB.ENFLERDAGS = enfle AND TIDREGITAB.GODKAND = '' 
USE-INDEX PSTART NO-LOCK.
GET FIRST tidq NO-LOCK.
DO WHILE AVAILABLE(TIDREGITAB):
   CREATE restidallt.
   BUFFER-COPY TIDREGITAB TO restidallt.
   restidallt.RECTIDVIS = RECID(TIDREGITAB).
   GET NEXT tidq NO-LOCK.
END.
