/*TRAKODHMT.p*/
{TRAKTTILLAGG.I}
DEFINE INPUT PARAMETER pkod AS CHARACTER NO-UNDO.
DEFINE OUTPUT PARAMETER TABLE FOR traktatabtemp.
FIND FIRST PERSONALTAB WHERE PERSONALTAB.PERSONALKOD = pkod NO-LOCK NO-ERROR.
OPEN QUERY bq FOR EACH TRAKTATAB WHERE TRAKTATAB.TRAAVTAL = PERSONALTAB.TRAAVTAL
AND TRAKTATAB.VALBAR = TRUE NO-LOCK.
GET FIRST bq NO-LOCK.
DO WHILE AVAILABLE(TRAKTATAB): 
   CREATE traktatabtemp.
   BUFFER-COPY TRAKTATAB TO traktatabtemp.
   GET NEXT bq NO-LOCK.
END.
