/*TRAKTBER.P  ENDAGSTRAKTAMENTE */  
DEFINE NEW SHARED VARIABLE maxzon LIKE TRAKTASTART.MAXVARDEZON NO-UNDO.
DEFINE NEW SHARED VARIABLE avslut LIKE TIDREGITAB.SLUT NO-UNDO.
/*DEFINE SHARED VARIABLE globanv LIKE ANVANDARE.ANVANDARE NO-UNDO.*/
DEFINE SHARED VARIABLE nytid AS DECIMAL FORMAT "99.99" NO-UNDO.
DEFINE SHARED VARIABLE sekunder AS INTEGER NO-UNDO.
DEFINE SHARED VARIABLE regdatum AS DATE NO-UNDO.   
DEFINE SHARED VARIABLE bdatum AS DATE NO-UNDO.
DEFINE SHARED VARIABLE avdatum AS DATE NO-UNDO.
DEFINE SHARED VARIABLE persrec AS RECID NO-UNDO.
DEFINE SHARED VARIABLE tidtabrec AS RECID  NO-UNDO.
DEFINE VARIABLE smaxav  AS INTEGER NO-UNDO.
DEFINE VARIABLE s2400 AS INTEGER NO-UNDO.
DEFINE VARIABLE starttiden AS INTEGER NO-UNDO.
DEFINE VARIABLE sluttiden AS INTEGER NO-UNDO.
DEFINE VARIABLE totalt AS INTEGER NO-UNDO.
DEFINE VARIABLE borjsek AS INTEGER NO-UNDO.
DEFINE VARIABLE slutsek AS INTEGER NO-UNDO.
DEFINE VARIABLE traktadatum AS DATE NO-UNDO.
DEFINE VARIABLE odatum AS DATE NO-UNDO.         
DEFINE VARIABLE kolldatum AS DATE NO-UNDO.                
DEFINE VARIABLE tesp LIKE PERSONALTAB.PERSONALKOD NO-UNDO.
DEFINE VARIABLE maxav LIKE TRAKTASTART.MAXAVBROTT NO-UNDO.
DEFINE VARIABLE t2400 LIKE TRAKTASTART.MAXAVBROTT NO-UNDO.
DEFINE VARIABLE sistast LIKE TIDREGITAB.START NO-UNDO.
DEFINE VARIABLE sistasl LIKE TIDREGITAB.SLUT NO-UNDO.
DEFINE VARIABLE bstart LIKE TIDREGITAB.START NO-UNDO.
DEFINE VARIABLE bslut LIKE TIDREGITAB.SLUT NO-UNDO.
DEFINE VARIABLE avstart LIKE TIDREGITAB.START NO-UNDO.
DEFINE VARIABLE midnatt LIKE TIDREGITAB.SLUT NO-UNDO.
DEFINE VARIABLE trakod LIKE TIDREGITAB.TRAKTKOD NO-UNDO.
DEFINE VARIABLE traantal LIKE TIDREGITAB.TRAKTANTAL NO-UNDO.


DEFINE NEW SHARED TEMP-TABLE traktafil
   FIELD TSTART LIKE TIDREGITAB.START
   FIELD TSLUT LIKE TIDREGITAB.SLUT
   FIELD TTRAKTAMENTE LIKE TIDREGITAB.TRAKTAMENTE
   FIELD TZON LIKE TIDREGITAB.TRAKTAMENTE
   FIELD TTRAKTTOT LIKE TIDREGITAB.TRAKTTOT
   FIELD TSTRAKTTOT AS INTEGER
   FIELD TDATUM LIKE TIDREGITAB.DATUM.

DEFINE QUERY tra2q FOR TIDREGITAB.
FIND PERSONALTAB WHERE RECID(PERSONALTAB) = persrec NO-LOCK NO-ERROR.
FIND FIRST TRAKTASTART WHERE TRAKTASTART.TRAAVTAL = PERSONALTAB.TRAAVTAL
USE-INDEX TSTART NO-LOCK NO-ERROR.
 

IF NOT AVAILABLE TRAKTASTART THEN DO:   
   CREATE FELTEXT.
   ASSIGN 
   FELTEXT.ANVANDARE = Guru.Konstanter:globanv                      
   FELTEXT.FELTEXT = 'Det är något fel på din traktamentesdatabas kontakta ansvarig!'
   FELTEXT.PROGRAM = "TRAKTBER" + STRING(TODAY) + STRING(TIME,"HH:MM") + Guru.Konstanter:globanv.
   RETURN.
END.        
ASSIGN
maxzon = TRAKTASTART.MAXVARDEZON
nytid = TRAKTASTART.MAXAVBROTT
maxav = TRAKTASTART.MAXAVBROTT.
RUN TIMSEK.P. 
ASSIGN
s2400 = 24.00 * 3600 - sekunder
sekunder = s2400.
RUN SEKTIM.P.
ASSIGN
t2400 = nytid         /* 24.00 - maxav*/
nytid = maxav.
RUN TIMSEK.P.
smaxav = sekunder.
FIND TIDREGITAB WHERE RECID(TIDREGITAB) = tidtabrec NO-LOCK NO-ERROR.
ASSIGN
regdatum = TIDREGITAB.DATUM
traktadatum = regdatum.
   /*KOLL OM DET FINNS MANUELLA TRAKTA*/
FIND FIRST TIDREGITAB WHERE TIDREGITAB.PERSONALKOD = PERSONALTAB.PERSONALKOD AND
TIDREGITAB.DATUM = regdatum AND TIDREGITAB.TRAKTAUTO = FALSE
USE-INDEX PSTART NO-LOCK NO-ERROR.
IF NOT AVAILABLE TIDREGITAB THEN DO:  
  /*INGA MANUELLA*/
   FIND TIDREGITAB WHERE RECID(TIDREGITAB) = tidtabrec NO-LOCK NO-ERROR.      
   ASSIGN
   bstart = TIDREGITAB.START
   bslut = TIDREGITAB.SLUT
   bdatum = TIDREGITAB.DATUM
   avstart = TIDREGITAB.START
   avslut = TIDREGITAB.SLUT
   avdatum = TIDREGITAB.DATUM           
   nytid = TIDREGITAB.START.     
   RUN TIMSEK.P.
   ASSIGN
   borjsek = sekunder
   nytid = TIDREGITAB.SLUT.
   RUN TIMSEK.P.
   slutsek = sekunder.
   REPEAT:
      IF TIDREGITAB.START <= 00.00 + maxav THEN DO:
         FIND LAST TIDREGITAB WHERE
         TIDREGITAB.PERSONALKOD = PERSONALTAB.PERSONALKOD AND
         TIDREGITAB.DATUM = (traktadatum - 1) AND
         TIDREGITAB.TRAKTAUTO = TRUE AND TIDREGITAB.TIDLOG = TRUE AND
         TIDREGITAB.GODKAND = '' USE-INDEX PSTART NO-LOCK NO-ERROR.
         IF NOT AVAILABLE TIDREGITAB THEN LEAVE.
         IF TIDREGITAB.TRAKTAUTO = FALSE THEN LEAVE.
         IF TIDREGITAB.SLUT >= t2400 THEN traktadatum = TIDREGITAB.DATUM.
         ELSE LEAVE.
         nytid = TIDREGITAB.START.
         RUN TIMSEK.P.
         borjsek = sekunder.
      END.
      ELSE DO:
         FIND PREV TIDREGITAB WHERE TIDREGITAB.PERSONALKOD =
         PERSONALTAB.PERSONALKOD AND
         TIDREGITAB.DATUM = traktadatum AND TIDREGITAB.TIDLOG = TRUE
         USE-INDEX PSTART NO-LOCK NO-ERROR.
         IF NOT AVAILABLE TIDREGITAB THEN LEAVE.
         nytid = TIDREGITAB.SLUT.
         RUN TIMSEK.P.
         IF sekunder <= borjsek - smaxav THEN LEAVE. /*TIMMARMIN*/
         nytid = TIDREGITAB.START.
         RUN TIMSEK.P.
         borjsek = sekunder.
      END.
      IF TIDREGITAB.TRAKTAMENTE = 00 THEN DO:
         IF TIDREGITAB.TOTALT >= maxav THEN LEAVE.
      END.            
      ASSIGN
      bstart = TIDREGITAB.START
      bslut = TIDREGITAB.SLUT
      bdatum = TIDREGITAB.DATUM.
   END.         /*START PUNKT OK*/
   /*HITTA DEN SISTA*/
   traktadatum = regdatum.
   FIND TIDREGITAB WHERE RECID(TIDREGITAB) = tidtabrec NO-LOCK NO-ERROR.
   REPEAT:
      IF TIDREGITAB.SLUT >= t2400 THEN DO:
         FIND FIRST TIDREGITAB WHERE 
         TIDREGITAB.PERSONALKOD = PERSONALTAB.PERSONALKOD AND
         TIDREGITAB.DATUM = (traktadatum + 1) AND
         TIDREGITAB.TRAKTAUTO = TRUE AND TIDREGITAB.TIDLOG = TRUE AND
         TIDREGITAB.GODKAND = '' USE-INDEX PSTART NO-LOCK NO-ERROR.
         IF NOT AVAILABLE TIDREGITAB THEN LEAVE.
         IF TIDREGITAB.TRAKTAUTO = FALSE THEN LEAVE.
         IF TIDREGITAB.START <= 00.00 + maxav THEN 
         traktadatum = TIDREGITAB.DATUM.
         ELSE LEAVE.
         nytid = TIDREGITAB.SLUT.
         RUN TIMSEK.P.
         slutsek = sekunder.
      END.
      ELSE DO:
         FIND NEXT TIDREGITAB WHERE 
         TIDREGITAB.PERSONALKOD = PERSONALTAB.PERSONALKOD AND
         TIDREGITAB.DATUM = traktadatum AND TIDREGITAB.TIDLOG = TRUE
         USE-INDEX PSTART NO-LOCK NO-ERROR.
         IF NOT AVAILABLE TIDREGITAB THEN LEAVE.
         nytid = TIDREGITAB.START.
         RUN TIMSEK.P.
         IF sekunder >= slutsek + smaxav THEN LEAVE. /*TIMMARMIN*/
         nytid = TIDREGITAB.SLUT.
         RUN TIMSEK.P.
         slutsek = sekunder.
      END.
      IF TIDREGITAB.TRAKTAMENTE = 00 THEN DO:
         IF TIDREGITAB.TOTALT >= maxav THEN LEAVE.
      END.                     
      ASSIGN
      avstart = TIDREGITAB.START
      avslut = TIDREGITAB.SLUT
      avdatum = TIDREGITAB.DATUM.
   END.
      /* TOTAL TRAKTAMENTESTID PER REGISTRERING*/
   kolldatum = bdatum.
   REPEAT:   
      IF kolldatum > avdatum THEN LEAVE.
      OPEN QUERY tra2q
      FOR EACH TIDREGITAB WHERE 
      TIDREGITAB.PERSONALKOD = PERSONALTAB.PERSONALKOD AND
      TIDREGITAB.DATUM = kolldatum AND TIDREGITAB.TIDLOG = TRUE 
      NO-LOCK USE-INDEX PSTART.      
      GET FIRST tra2q EXCLUSIVE-LOCK.
      DO WHILE AVAILABLE(TIDREGITAB):
         IF TIDREGITAB.TRAKTAMENTE = 00 THEN ASSIGN TIDREGITAB.TRAKTTOT = 0.
         ELSE DO:
            nytid = TIDREGITAB.SLUT.
            RUN TIMSEK.P.
            ASSIGN
            sluttiden = sekunder
            nytid = TIDREGITAB.START.
            RUN TIMSEK.P.     
            ASSIGN
            starttiden = sekunder
            totalt = sluttiden - starttiden
            sekunder = totalt.
            RUN SEKTIM.P.
            ASSIGN TIDREGITAB.TRAKTTOT = nytid.
         END.         
         IF bdatum = avdatum THEN DO:              
            IF TIDREGITAB.START >= bstart AND TIDREGITAB.SLUT <= avslut THEN DO:
               /*TAR BORT ALLA TIDIGARE KODERG*/
               ASSIGN TIDREGITAB.TRAKTKOD = ' ' TIDREGITAB.TRAKTANTAL = 0.
               CREATE traktafil.
               ASSIGN traktafil.TSTART = TIDREGITAB.START
               traktafil.TSLUT = TIDREGITAB.SLUT
               traktafil.TTRAKTAMENTE = TIDREGITAB.TRAKTAMENTE
               traktafil.TTRAKTTOT = TIDREGITAB.TRAKTTOT
               traktafil.TDATUM = TIDREGITAB.DATUM.
            END.
         END.        
         IF bdatum NE avdatum THEN DO:
            IF TIDREGITAB.DATUM = avdatum AND TIDREGITAB.SLUT <= avslut THEN DO:
               /*TAR BORT ALLA TIDIGARE KODERG*/
               ASSIGN TIDREGITAB.TRAKTKOD = ' ' TIDREGITAB.TRAKTANTAL = 0.
               CREATE traktafil.
               ASSIGN traktafil.TSTART = TIDREGITAB.START
               traktafil.TSLUT = TIDREGITAB.SLUT
               traktafil.TTRAKTAMENTE = TIDREGITAB.TRAKTAMENTE
               traktafil.TTRAKTTOT = TIDREGITAB.TRAKTTOT
               traktafil.TDATUM = TIDREGITAB.DATUM.
            END.
            IF TIDREGITAB.DATUM = bdatum AND TIDREGITAB.START >= bstart THEN DO:
               /*TAR BORT ALLA TIDIGARE KODERG*/
               ASSIGN TIDREGITAB.TRAKTKOD = ' ' TIDREGITAB.TRAKTANTAL = 0.
               CREATE traktafil.
               ASSIGN traktafil.TSTART = TIDREGITAB.START
               traktafil.TSLUT = TIDREGITAB.SLUT
               traktafil.TTRAKTAMENTE = TIDREGITAB.TRAKTAMENTE
               traktafil.TTRAKTTOT = TIDREGITAB.TRAKTTOT
               traktafil.TDATUM = TIDREGITAB.DATUM.
            END.
            IF TIDREGITAB.DATUM > bdatum AND TIDREGITAB.DATUM < avdatum THEN DO:
               /*TAR BORT ALLA TIDIGARE KODERG*/
               ASSIGN TIDREGITAB.TRAKTKOD = ' ' TIDREGITAB.TRAKTANTAL = 0.
               CREATE traktafil.
               ASSIGN traktafil.TSTART = TIDREGITAB.START
               traktafil.TSLUT = TIDREGITAB.SLUT
               traktafil.TTRAKTAMENTE = TIDREGITAB.TRAKTAMENTE
               traktafil.TTRAKTTOT = TIDREGITAB.TRAKTTOT
               traktafil.TDATUM = TIDREGITAB.DATUM.
            END.
         END.    
         GET NEXT tra2q EXCLUSIVE-LOCK.      
      END.         
      CLOSE QUERY tra2q.
      kolldatum = kolldatum + 1.   
   END.
   FIND LAST traktafil WHERE traktafil.TTRAKTAMENTE NE 0 NO-LOCK NO-ERROR.
   IF AVAILABLE traktafil THEN DO:
      ASSIGN
      avstart = traktafil.TSTART
      avslut = traktafil.TSLUT
      avdatum = traktafil.TDATUM.
   END.   
   RUN TRZONUTF.P.   
END. /*SLUT  INGA MANUELLA*/
ELSE DO:
   /*MANUELLA*/
   persrec = persrec.
END.
