 /*TRMANS2.P ANROP VIA TRAKMAN OCH TRAKANDRIG RB*/
/*REGISTRERING MANUELL TRAK OCH EV TILL*/
/* FINNS INTE AONR AKTUELLT DATUM BLIR START OCH SLUT TID LIKA*/
/*DEFINE SHARED VARIABLE globanv LIKE ANVANDARE.ANVANDARE NO-UNDO.*/
DEFINE SHARED VARIABLE tidtabrec AS RECID  NO-UNDO.
DEFINE SHARED VARIABLE regdatum AS DATE NO-UNDO.
DEFINE SHARED VARIABLE persrec AS RECID NO-UNDO.
DEFINE SHARED VARIABLE bdatum AS DATE NO-UNDO.
DEFINE SHARED VARIABLE avdatum AS DATE NO-UNDO.
DEFINE SHARED VARIABLE nytid AS DECIMAL FORMAT "99.99" NO-UNDO.
DEFINE SHARED VARIABLE sekunder AS INTEGER NO-UNDO.
DEFINE SHARED VARIABLE resrec AS RECID NO-UNDO.

DEFINE VARIABLE tidtabrecspar AS RECID  NO-UNDO.
DEFINE VARIABLE regdatumspar AS DATE NO-UNDO.
DEFINE VARIABLE bdatumspar AS DATE NO-UNDO.
DEFINE VARIABLE avdatumspar AS DATE NO-UNDO.
DEFINE VARIABLE maxav LIKE TRAKTASTART.MAXAVBROTT NO-UNDO.
DEFINE VARIABLE t2400 LIKE TRAKTASTART.MAXAVBROTT NO-UNDO.
DEFINE VARIABLE s2400 AS INTEGER NO-UNDO.
DEFINE VARIABLE smaxav AS INTEGER NO-UNDO.

DEFINE QUERY traktq FOR TIDREGITAB.   
&Scoped-define NEW
{RESDEF.I}
/*DEFINE SHARED TEMP-TABLE respers    
   FIELD AONR LIKE TIDREGITAB.AONR
   FIELD DELNR LIKE TIDREGITAB.DELNR
   FIELD VECKONUMMER LIKE TIDREGITAB.VECKONUMMER
   FIELD DATUM LIKE TIDREGITAB.DATUM
   FIELD DAG LIKE TIDREGITAB.DAG
   FIELD START LIKE TIDREGITAB.START
   FIELD SLUT LIKE TIDREGITAB.SLUT 
   FIELD PRIS AS DECIMAL  
   FIELD PRISTYP AS CHARACTER
   FIELD NATTRAKT AS LOGICAL FORMAT "JA/NEJ" LABEL "NATT TRAKT"
   FIELD OVERTIDUTTAG LIKE PERSONALTAB.OVERTIDUTTAG 
   FIELD BILFORARE LIKE TIDREGITAB.BILFORARE
   FIELD ENFLERDAGS LIKE TIDREGITAB.ENFLERDAGS  
   FIELD TIDREC AS RECID
   INDEX RESPERS IS PRIMARY DATUM START SLUT ASCENDING.*/

FIND PERSONALTAB WHERE RECID(PERSONALTAB) = persrec NO-LOCK NO-ERROR.
FIND FIRST TRAKTASTART WHERE TRAKTASTART.TRAAVTAL = PERSONALTAB.TRAAVTAL
USE-INDEX TSTART NO-LOCK NO-ERROR.
IF NOT AVAILABLE TRAKTASTART THEN DO TRANSACTION:
   CREATE FELTEXT.
   ASSIGN 
   FELTEXT.ANVANDARE = Guru.Konstanter:globanv         
   FELTEXT.FELTEXT = 'Det är något fel på din traktamentesdatabas kontakta ansvarig!'
   FELTEXT.PROGRAM = "TRMANS2" + STRING(TODAY) + STRING(TIME,"HH:MM") + Guru.Konstanter:globanv.  
   RETURN.
END.
ASSIGN
nytid = TRAKTASTART.MAXAVBROTT
maxav = TRAKTASTART.MAXAVBROTT.
RUN TIMSEK.P.
s2400 = 24.00 * 3600 - sekunder.
sekunder = s2400.
RUN SEKTIM.P.
t2400 = nytid.         /* 24.00 - maxav*/
nytid = maxav.
RUN TIMSEK.P.
smaxav = sekunder.
FIND respers WHERE RECID(respers) = resrec NO-LOCK NO-ERROR.
   /*KOLL OM DET FINNS MANUELLA TRAKTA*/
FIND FIRST TIDREGITAB WHERE TIDREGITAB.PERSONALKOD = PERSONALTAB.PERSONALKOD AND
TIDREGITAB.TIDLOG = TRUE AND TIDREGITAB.DATUM = respers.DATUM AND 
TIDREGITAB.TRAKTAUTO = FALSE USE-INDEX PSTART NO-LOCK NO-ERROR.
IF NOT AVAILABLE TIDREGITAB THEN DO TRANSACTION:
   /*INGA MANUELLA FINNS DENNA DAG*/
   OPEN QUERY traktq FOR EACH TIDREGITAB WHERE TIDREGITAB.PERSONALKOD = PERSONALTAB.PERSONALKOD AND
   TIDREGITAB.DATUM = respers.DATUM AND
   TIDREGITAB.TRAKTAUTO = TRUE NO-LOCK USE-INDEX PSTART.     
   GET FIRST traktq EXCLUSIVE-LOCK.
   DO WHILE AVAILABLE(TIDREGITAB):                     
      IF TIDREGITAB.GODKAND NE '' THEN RETURN.
      ASSIGN TIDREGITAB.TRAKTKOD = ' ' TIDREGITAB.TRAKTANTAL = 0
      TIDREGITAB.TRAKTAUTO = FALSE.     
      GET NEXT traktq EXCLUSIVE-LOCK.
   END. 
   GET FIRST traktq EXCLUSIVE-LOCK.      
   IF NOT AVAILABLE TIDREGITAB THEN RETURN.   
   IF TIDREGITAB.TRAKTAMENTE = 00 THEN DO:
      REPEAT:
         GET NEXT traktq EXCLUSIVE-LOCK.
         IF NOT AVAILABLE TIDREGITAB THEN RETURN.                    
         IF TIDREGITAB.TRAKTAMENTE NE 00 THEN LEAVE.
      END.                                          
   END.         
   IF TIDREGITAB.START <= 00.00 + maxav THEN DO:
      /* OM SISTA REG R 00.00 */
      FIND LAST TIDREGITAB WHERE TIDREGITAB.PERSONALKOD = PERSONALTAB.PERSONALKOD AND
      TIDREGITAB.DATUM = (respers.DATUM - 1) AND TIDREGITAB.TRAKTAUTO = TRUE AND
      TIDREGITAB.TRAKTAMENTE NE 00 AND TIDREGITAB.TIDLOG = TRUE AND
      TIDREGITAB.GODKAND = '' USE-INDEX PSTART NO-LOCK NO-ERROR.
      IF NOT AVAILABLE TIDREGITAB THEN persrec = persrec.
      ELSE IF TIDREGITAB.SLUT >= t2400 THEN DO:
         ASSIGN
         tidtabrecspar = tidtabrec
         regdatumspar = regdatum
         bdatumspar = bdatum
         avdatumspar = avdatum.    
         tidtabrec = RECID(TIDREGITAB).
         RUN TRAKTBER.P. 
         ASSIGN
	  tidtabrec = tidtabrecspar
         regdatum = regdatumspar
         bdatum = bdatumspar
         avdatum = avdatumspar.    
      END.      
   END. 
   GET LAST traktq EXCLUSIVE-LOCK.                  
   IF TIDREGITAB.TRAKTAMENTE = 00 THEN persrec = persrec.
   ELSE IF TIDREGITAB.GODKAND NE '' THEN persrec = persrec.
   ELSE IF TIDREGITAB.SLUT >= t2400 THEN DO:
      /*OM SISTA REG SLUTAR 24.00 */                     
      FIND FIRST TIDREGITAB WHERE TIDREGITAB.PERSONALKOD = PERSONALTAB.PERSONALKOD AND
      TIDREGITAB.DATUM = (respers.DATUM + 1) AND TIDREGITAB.TRAKTAUTO = TRUE AND
      TIDREGITAB.TRAKTAMENTE NE 00 AND TIDREGITAB.TIDLOG = TRUE AND
      TIDREGITAB.GODKAND = '' USE-INDEX PSTART NO-LOCK NO-ERROR.
      IF NOT AVAILABLE TIDREGITAB THEN persrec = persrec. 
      ELSE IF TIDREGITAB.START <= 00.00 + maxav THEN DO:
	  ASSIGN
	  tidtabrecspar = tidtabrec
         regdatumspar = regdatum
         bdatumspar = bdatum
         avdatumspar = avdatum.    
         tidtabrec = RECID(TIDREGITAB).
	  RUN TRAKTBER.P. 
	  ASSIGN
	  tidtabrec = tidtabrecspar
         regdatum = regdatumspar
         bdatum = bdatumspar
         avdatum = avdatumspar.    
      END.
   END.  
   CLOSE QUERY traktq.          
END.
