/*TRMANSUM0.P*/

&Scoped-define NEW NEW
{TIDALLT.I}
DEFINE INPUT PARAMETER ganv AS CHARACTER NO-UNDO.
DEFINE INPUT PARAMETER pkod AS CHARACTER NO-UNDO.
DEFINE INPUT PARAMETER TABLE FOR extratidallt.
DEFINE OUTPUT PARAMETER placerarec AS RECID.
DEFINE OUTPUT PARAMETER TABLE FOR tidallt.
DEFINE NEW SHARED VARIABLE regstart LIKE TIDREGITAB.START NO-UNDO. 
DEFINE NEW SHARED VARIABLE regslut LIKE TIDREGITAB.SLUT NO-UNDO.      
DEFINE NEW SHARED VARIABLE regdatum AS DATE NO-UNDO.
DEFINE NEW SHARED VARIABLE bdatum AS DATE NO-UNDO.
DEFINE NEW SHARED VARIABLE avdatum AS DATE NO-UNDO. 
DEFINE NEW SHARED VARIABLE nytid AS DECIMAL FORMAT "99.99" NO-UNDO.
DEFINE NEW SHARED VARIABLE sekunder AS INTEGER FORMAT "-9999999" NO-UNDO.
DEFINE NEW SHARED VARIABLE persrec AS RECID NO-UNDO.
DEFINE NEW SHARED VARIABLE persrec2 AS RECID NO-UNDO.
DEFINE NEW SHARED VARIABLE vart AS CHARACTER FORMAT "X(3)" NO-UNDO.
DEFINE NEW SHARED VARIABLE musz AS LOGICAL NO-UNDO.
/*DEFINE NEW SHARED VARIABLE globanv LIKE ANVANDARE.ANVANDARE NO-UNDO.*/
DEFINE NEW SHARED VARIABLE tidtabrec AS RECID  NO-UNDO.


FIND FIRST PERSONALTAB WHERE PERSONALTAB.PERSONALKOD = pkod NO-LOCK NO-ERROR.
persrec = RECID(PERSONALTAB).
FOR EACH extratidallt:
   regdatum = extratidallt.DATUM.
   DO TRANSACTION:
      IF extratidallt.RECTIDVIS = ? THEN DO: 
         CREATE TIDREGITAB.
      END.
      ELSE DO:
         FIND TIDREGITAB WHERE RECID(TIDREGITAB) = extratidallt.RECTIDVIS EXCLUSIVE-LOCK NO-ERROR.
      END.
      BUFFER-COPY extratidallt EXCEPT extratidallt.RECTIDVIS TO TIDREGITAB.
      TIDREGITAB.PERSONALKOD = PERSONALTAB.PERSONALKOD.     
   END.
   CREATE tidallt.
   ASSIGN
   tidallt.PERSONALKOD = ""
   tidtabrec = RECID(TIDREGITAB)
   tidallt.RECTIDVIS = RECID(TIDREGITAB).
   RUN TRMANSUM.P.
   RUN coptider_UI.
   DELETE extratidallt.
END.

{GDPRLOGGCLIENT.I}
PROCEDURE coptider_UI :   
   FOR EACH tidallt WHERE tidallt.PERSONALKOD = "":
      FIND TIDREGITAB WHERE RECID(TIDREGITAB) = tidallt.RECTIDVIS NO-LOCK NO-ERROR.
      IF AVAILABLE TIDREGITAB THEN DO:
         BUFFER-COPY TIDREGITAB TO tidallt.
         Guru.GlobalaVariabler:GDPRvem = Guru.GlobalaVariabler:GDPRvem + "," + TIDREGITAB.PERSONALKOD.
         tidallt.RECTIDVIS = RECID(TIDREGITAB).
         IF tidallt.LONTILLAGG NE "" THEN DO:
            FIND FIRST LONTILL WHERE LONTILL.KOD = ANSTFORMTAB.KOD AND 
            LONTILL.LONTILLAGG = tidallt.LONTILLAGG NO-LOCK NO-ERROR.
            IF AVAILABLE LONTILL THEN DO:
               tidallt.VILART = LONTILL.VILART. 
            END.
            tidallt.TYP = "LON".
         END.
         IF tidallt.BEREDSKAP NE "" THEN DO:
            FIND FIRST BERKOD WHERE BERKOD.BEREDSKAPSAVTAL = PERSONALTAB.BEREDSKAPSAVTAL AND
            BERKOD.BEREDSKAP = tidallt.BEREDSKAP NO-LOCK NO-ERROR.
            IF AVAILABLE BERKOD THEN DO:
               tidallt.VILART = BERKOD.VILART. 
            END.
            tidallt.TYP = "BER".
         END.
         IF tidallt.TRAKTKOD NE "" THEN DO:
            FIND FIRST TRAKTATAB WHERE TRAKTATAB.TRAAVTAL = PERSONALTAB.TRAAVTAL AND 
            TRAKTATAB.TRAKTKOD = tidallt.TRAKTKOD NO-LOCK NO-ERROR.    
            IF AVAILABLE TRAKTATAB THEN DO:
               tidallt.VILART = TRAKTATAB.VILART. 
            END.
            tidallt.TYP = "TRA".        
         END.
      END.
      ELSE DELETE tidallt.
      placerarec = RECID(TIDREGITAB).
   END.
END PROCEDURE.

