/*UPPGHMT.P*/
&Scoped-define NEW NEW
{UPPGHMT.I}

DEFINE OUTPUT PARAMETER TABLE FOR automregtemp.
DEFINE OUTPUT PARAMETER TABLE FOR befattningstemp.
DEFINE OUTPUT PARAMETER TABLE FOR overkodtemp.
DEFINE OUTPUT PARAMETER TABLE FOR beredskapstarttemp.
DEFINE OUTPUT PARAMETER TABLE FOR beredskaptabtemp.

RUN AUOTOMRHMT.P (OUTPUT TABLE automregtemp).

RUN BEFHMT.P (OUTPUT TABLE befattningstemp).

OPEN QUERY oq FOR EACH OVERKOD NO-LOCK.
GET FIRST oq NO-LOCK.
DO WHILE AVAILABLE(OVERKOD):
   CREATE overkodtemp.
   BUFFER-COPY OVERKOD TO overkodtemp.
   GET NEXT oq NO-LOCK.
END.      
OPEN QUERY bsq FOR EACH BEREDSKAPSTART NO-LOCK.
GET FIRST bsq NO-LOCK.
DO WHILE AVAILABLE(BEREDSKAPSTART):
   CREATE beredskapstarttemp.
   BUFFER-COPY BEREDSKAPSTART TO beredskapstarttemp.
   GET NEXT bsq NO-LOCK.
END.
OPEN QUERY beq FOR EACH BEREDSKAPTAB NO-LOCK.
GET FIRST beq NO-LOCK.
DO WHILE AVAILABLE(BEREDSKAPTAB):
   CREATE beredskaptabtemp.
   BUFFER-COPY BEREDSKAPTAB TO beredskaptabtemp.
   GET NEXT beq NO-LOCK.
END.
