/*VECKAPP.P*/
&Scoped-define NEW NEW
{GLOBVAR2DEL1.I}

{REGVAR.I}
&Scoped-define SHARED SHARED
{DHMT.I}
{VHMT.I}
DEFINE INPUT PARAMETER vart AS INTEGER.
DEFINE INPUT PARAMETER arbtk AS INTEGER.
DEFINE INPUT PARAMETER vesch AS INTEGER.
DEFINE INPUT-OUTPUT PARAMETER felvar AS LOGICAL.
DEFINE OUTPUT PARAMETER TABLE FOR felmeddtemp.
DEFINE INPUT-OUTPUT PARAMETER TABLE FOR veckoarbtemp.
DEFINE INPUT-OUTPUT PARAMETER TABLE FOR arbtidtemp.
DEFINE VARIABLE tidsummasek AS INTEGER NO-UNDO.

/*ny*/
IF vart = 1 THEN DO:
   RUN andra_UI. 
   RETURN.
END.

/*andra*/
IF vart = 2 THEN DO:
   RUN andra_UI.
   RETURN.
END.  
/*bort*/
IF vart = 3 THEN DO:
   FIND FIRST PERSONALTAB WHERE PERSONALTAB.VECKOSCHEMA = vesch
   USE-INDEX PERSONALKOD NO-LOCK NO-ERROR.
   IF AVAILABLE PERSONALTAB THEN DO:
      CREATE felmeddtemp.
      felmeddtemp.FELMEDD = "Detta veckoschema används av en eller flera personer och kan ej tas bort!".
      RETURN.
   END.    
   FIND FIRST VECKOARBAV WHERE VECKOARBAV.VECKOSCHEMA = vesch
   USE-INDEX VECKOSCHEMA NO-LOCK NO-ERROR.
   IF AVAILABLE VECKOARBAV THEN DO:
      CREATE felmeddtemp.
      felmeddtemp.FELMEDD = "Detta veckoschema används av en eller flera personer och kan ej tas bort!".
      RETURN.
   END.
   OPEN QUERY fq FOR EACH VECKOARBETID WHERE VECKOARBETID.VECKOSCHEMA = vesch NO-LOCK.
   GET FIRST fq NO-LOCK.
   DO WHILE AVAILABLE(VECKOARBETID):
      DO TRANSACTION:
         GET CURRENT fq EXCLUSIVE-LOCK.
         FIND FIRST veckoarbtemp WHERE veckoarbtemp.VECKOSCHEMA = vesch NO-ERROR.
         IF AVAILABLE veckoarbtemp THEN DELETE veckoarbtemp.
         DELETE VECKOARBETID.
      END. 
      GET NEXT fq NO-LOCK.
   END.
   CLOSE QUERY fq.
   RETURN.
END.

/*ladda*/
IF vart = 4 THEN DO:
   EMPTY TEMP-TABLE arbtidtemp NO-ERROR.    
   OPEN QUERY gq FOR EACH ARBETSTIDTAB USE-INDEX ARBTIDKOD NO-LOCK.
   GET FIRST gq NO-LOCK.
   DO WHILE AVAILABLE(ARBETSTIDTAB):
      CREATE arbtidtemp.                        
      BUFFER-COPY ARBETSTIDTAB TO arbtidtemp.   
      GET NEXT gq NO-LOCK.                      
   END.
   CLOSE QUERY gq.
   EMPTY TEMP-TABLE veckoarbtemp NO-ERROR.    
   OPEN QUERY hq FOR EACH VECKOARBETID USE-INDEX VECKOSCHEMA NO-LOCK.
   GET FIRST hq NO-LOCK.
   DO WHILE AVAILABLE(VECKOARBETID):
      CREATE veckoarbtemp.
      BUFFER-COPY VECKOARBETID TO veckoarbtemp.
      GET NEXT hq NO-LOCK.
   END.
   CLOSE QUERY hq.
   RETURN.
END.


PROCEDURE andra_UI.
   FIND FIRST veckoarbtemp WHERE veckoarbtemp.VECKOSCHEMA = vesch
   NO-LOCK NO-ERROR.
   FIND FIRST VECKOARBETID WHERE VECKOARBETID.VECKOSCHEMA = vesch 
   NO-LOCK NO-ERROR.
   DO TRANSACTION:
      IF NOT AVAILABLE VECKOARBETID THEN DO:
         CREATE VECKOARBETID.
      END.
      FIND CURRENT VECKOARBETID EXCLUSIVE-LOCK NO-ERROR.
      BUFFER-COPY veckoarbtemp TO VECKOARBETID.   
   END.   
END PROCEDURE.
