/*ALLSIAP.P*/
DEFINE TEMP-TABLE sista
   FIELD PERSONALKOD AS CHARACTER
   FIELD FORNAMN AS CHARACTER
   FIELD EFTERNAMN AS CHARACTER
   FIELD DATUM AS DATE
   FIELD TID AS DECIMAL
   FIELD KNAPP AS CHARACTER
   INDEX PERSONALKOD IS PRIMARY PERSONALKOD ASCENDING.

DEFINE INPUT  PARAMETER pkod AS CHARACTER NO-UNDO.
DEFINE OUTPUT PARAMETER TABLE FOR sista.
FIND FIRST FORETAG WHERE NO-LOCK NO-ERROR.
IF FORETAG.FORETAG = "SNAT" THEN DO:
   FIND FIRST PERSONALTAB WHERE PERSONALTAB.PERSONALKOD = pkod NO-LOCK NO-ERROR.
   FIND FIRST  FLEXAVT WHERE PERSONALTAB.PERSONALKOD = FLEXAVT.PERSONALKOD AND  FLEXAVT.FLEXTID = TRUE NO-LOCK NO-ERROR .
   IF AVAILABLE FLEXAVT THEN DO:
      FIND LAST FLEXTID WHERE FLEXTID.PERSONALKOD = FLEXAVT.PERSONALKOD USE-INDEX FLEX NO-LOCK NO-ERROR.
      IF AVAILABLE FLEXTID THEN DO:   
         CREATE sista.
         ASSIGN sista.PERSONALKOD = FLEXTID.PERSONALKOD
         sista.FORNAMN = PERSONALTAB.FORNAMN
         sista.EFTERNAMN = PERSONALTAB.EFTERNAMN
         sista.DATUM = FLEXTID.DATUM
         sista.TID = FLEXTID.TID
         sista.KNAPP = FLEXTID.KNAPP.
         Guru.GlobalaVariabler:GDPRvem = Guru.GlobalaVariabler:GDPRvem + "," + FLEXTID.PERSONALKOD.
      END.
   END.  
END.
ELSE DO:    
   FIND FIRST ANVANDARE WHERE ANVANDARE.PERSONALKOD = pkod NO-LOCK NO-ERROR.
   OPEN QUERY allq FOR EACH PERSONALTAB WHERE PERSONALTAB.AKTIV = TRUE NO-LOCK,
   EACH FLEXAVT WHERE FLEXAVT.PERSONALKOD = PERSONALTAB.PERSONALKOD AND
   FLEXAVT.FLEXTID = TRUE NO-LOCK.
   GET FIRST allq NO-LOCK.
   DO WHILE AVAILABLE(FLEXAVT).
      FIND FIRST TIDSEK WHERE TIDSEK.ANVANDARE = ANVANDARE.ANVANDARE AND
      TIDSEK.PERSONALKOD = PERSONALTAB.PERSONALKOD  USE-INDEX TIDSEK NO-ERROR.
      IF AVAILABLE TIDSEK THEN DO:
         FIND LAST FLEXTID WHERE FLEXTID.PERSONALKOD = FLEXAVT.PERSONALKOD USE-INDEX FLEX NO-LOCK NO-ERROR.
         IF AVAILABLE FLEXTID THEN DO:   
            CREATE sista.
            ASSIGN sista.PERSONALKOD = FLEXTID.PERSONALKOD
            sista.FORNAMN = PERSONALTAB.FORNAMN
            sista.EFTERNAMN = PERSONALTAB.EFTERNAMN
            sista.DATUM = FLEXTID.DATUM
            sista.TID = FLEXTID.TID
            sista.KNAPP = FLEXTID.KNAPP.
            Guru.GlobalaVariabler:GDPRvem = Guru.GlobalaVariabler:GDPRvem + "," + FLEXTID.PERSONALKOD.
         END.
      END.   
      GET NEXT allq NO-LOCK.
   END.
   CLOSE QUERY allq.
END.   
         

{GDPRLOGGCLIENT.I}



   