/*AUTOFLEX.P*/



&Scoped-define NEW NEW
{TIDPERS.I}

EMPTY TEMP-TABLE tidpers  NO-ERROR. 
OPEN QUERY peq FOR EACH PERSONALTAB WHERE PERSONALTAB.AKTIV = TRUE    
USE-INDEX PERSONALKOD NO-LOCK,
EACH FLEXAVT WHERE FLEXAVT.PERSONALKOD = PERSONALTAB.PERSONALKOD AND
FLEXAVT.FLEXTID = TRUE NO-LOCK.
GET FIRST peq NO-LOCK.
DO WHILE AVAILABLE(PERSONALTAB):     
   DO TRANSACTION: 
      CREATE tidpers.
      ASSIGN 
      tidpers.ANSVARIGTIDR = PERSONALTAB.ANSVARIGTIDR
      tidpers.OMRADE = PERSONALTAB.OMRADE
      tidpers.TIDPERSREC = RECID(PERSONALTAB)
      tidpers.PERSONALKOD = PERSONALTAB.PERSONALKOD
      tidpers.EFTERNAMN = PERSONALTAB.EFTERNAMN   
      tidpers.FORNAMN = PERSONALTAB.FORNAMN. 
   END.   
   GET NEXT peq NO-LOCK.    
END.
IF Guru.Konstanter:appcon THEN DO:                           
   RUN NATTMAN.P ON Guru.Konstanter:apphand TRANSACTION DISTINCT 
   (INPUT TABLE tidpers).
END.
ELSE DO:
    RUN NATTMAN.P 
    (INPUT TABLE tidpers).                  
END.
