/*FLEXTIDH.P*/
DEFINE INPUT PARAMETER sok0 AS INTEGER NO-UNDO.
DEFINE INPUT-OUTPUT PARAMETER sok1 AS CHARACTER NO-UNDO.
DEFINE INPUT-OUTPUT PARAMETER sok2 AS INTEGER NO-UNDO.
DEFINE INPUT-OUTPUT PARAMETER sok3 AS CHARACTER NO-UNDO.
DEFINE INPUT-OUTPUT PARAMETER sok4 AS CHARACTER NO-UNDO.
DEFINE INPUT-OUTPUT PARAMETER sok5 AS DECIMAL NO-UNDO.
DEFINE VARIABLE sokhjalp AS DECIMAL NO-UNDO.
DEFINE VARIABLE sokhjalp1 AS DECIMAL NO-UNDO.
DEFINE VARIABLE sokhjalp2 AS LOGICAL NO-UNDO.
DEFINE VARIABLE hjomr AS CHARACTER NO-UNDO.
DEFINE VARIABLE testdatum AS DATE NO-UNDO.
DEFINE VARIABLE kompapph AS HANDLE NO-UNDO.
DEFINE VARIABLE acckompvman  AS DECIMAL NO-UNDO.
DEFINE VARIABLE acckompvmandat AS DATE NO-UNDO.
DEFINE VARIABLE acckompsenast AS DECIMAL NO-UNDO.
DEFINE VARIABLE acckompsenasttot AS DECIMAL NO-UNDO.
DEFINE VARIABLE acckompsenastdat AS DATE NO-UNDO.
DEFINE VARIABLE komputtag AS DECIMAL NO-UNDO.
DEFINE VARIABLE antmult AS DECIMAL NO-UNDO.
DEFINE VARIABLE hjdatum AS DATE NO-UNDO.
DEFINE VARIABLE totarbkort AS DECIMAL NO-UNDO.
DEFINE VARIABLE kvaratk AS DECIMAL NO-UNDO.
DEFINE VARIABLE foremaxarbkort AS DECIMAL NO-UNDO.


FUNCTION klock100 RETURNS DECIMAL
  ( INPUT ber60 AS DECIMAL ):
/*------------------------------------------------------------------------------
  Purpose:  
    Notes:  
------------------------------------------------------------------------------*/

  RETURN  (TRUNCATE(ber60,0) * 3600 + (ber60 - TRUNCATE(ber60,0)) * 100 * 60) / 3600.

END FUNCTION.
FUNCTION klock60 RETURNS DECIMAL
  ( INPUT ber100 AS DECIMAL ):
/*------------------------------------------------------------------------------
  Purpose:  
    Notes:  
------------------------------------------------------------------------------*/

  RETURN  TRUNCATE(ber100,0) + ((ber100 - TRUNCATE(ber100,0)) * 60 / 100 ).

END FUNCTION.
IF sok0 = 1 THEN DO:
   hjomr = "".
   FIND FIRST FORETAG  NO-LOCK NO-ERROR.
   IF FORETAG.FORETAG = "SUND" OR FORETAG.FORETAG = "SNAT" OR FORETAG.FORETAG = "ELPA" THEN DO:         
      FIND FIRST PERSONALTAB WHERE PERSONALTAB.PERSONALKOD = sok3 NO-LOCK NO-ERROR.
      IF AVAILABLE PERSONALTAB THEN DO:      
         IF PERSONALTAB.ANSTALLNING = "Ej tidskrivande personal" THEN sok1 = sok1.
         ELSE IF PERSONALTAB.OMRADE = "1111" THEN sok1 = sok1.
         ELSE IF PERSONALTAB.OMRADE = "1311" THEN sok1 = sok1.
         ELSE IF PERSONALTAB.OMRADE = "1411" THEN sok1 = sok1.                 
         ELSE IF PERSONALTAB.OMRADE = "1511" THEN sok1 = sok1.         
         ELSE IF PERSONALTAB.OMRADE = "1611" THEN sok1 = sok1.
         ELSE IF PERSONALTAB.OMRADE = "1711" THEN sok1 = sok1.
         ELSE IF PERSONALTAB.OMRADE = "1811" THEN sok1 = sok1.
         ELSE IF PERSONALTAB.OMRADE = "8800" THEN sok1 = sok1.
         ELSE IF PERSONALTAB.OMRADE = "8613" THEN sok1 = sok1.
         ELSE IF PERSONALTAB.OMRADE = "2230" THEN sok1 = sok1.
         ELSE hjomr = PERSONALTAB.OMRADE.         
      END.
   END.
   IF FORETAG.FORETAG = "MISV" OR FORETAG.FORETAG = "ELPA" THEN DO:         
      /*skall föreslå senast skrivna projekt oavsett område*/
   END.
   IF hjomr = "" THEN DO:   
      FIND LAST TIDREGITAB WHERE TIDREGITAB.PERSONALKOD = sok3 AND 
      TIDREGITAB.PRISTYP NE "FRÅNVARO." AND TIDREGITAB.PRISTYP NE "RESTID.." AND 
      TIDREGITAB.TIDLOG = TRUE USE-INDEX PKOD NO-LOCK NO-ERROR.
      IF AVAILABLE TIDREGITAB THEN DO:
         ASSIGN
         sok1 = TIDREGITAB.AONR
         sok2 = TIDREGITAB.DELNR.
      END.
      ELSE sok1 = "FINNS EJ".         
   END.
   ELSE DO:
      /* sök sista tidskrivningen på eget område för Korsta. för segt används inte*/
      FIND LAST TIDREGITAB WHERE TIDREGITAB.PERSONALKOD = sok3 AND 
      TIDREGITAB.PRISTYP NE "FRÅNVARO." AND TIDREGITAB.PRISTYP NE "RESTID.." AND 
      TIDREGITAB.TIDLOG = TRUE USE-INDEX PKOD NO-LOCK NO-ERROR.
      IF AVAILABLE TIDREGITAB THEN DO:
         FIND FIRST ANVAOTAB WHERE ANVAOTAB.ANVANDARE = sok3 + "$" + "AONRE" 
         AND ANVAOTAB.AONR = TIDREGITAB.AONR AND ANVAOTAB.DELNR = TIDREGITAB.DELNR NO-LOCK NO-ERROR.
         IF AVAILABLE ANVAOTAB THEN DO:
            ASSIGN
            sok1 = TIDREGITAB.AONR
            sok2 = TIDREGITAB.DELNR.
         END.
         ELSE DO:         
             FIND FIRST AONRTAB WHERE AONRTAB.AONR = TIDREGITAB.AONR AND AONRTAB.DELNR = TIDREGITAB.DELNR 
             AND AONRTAB.OMRADE = hjomr NO-LOCK NO-ERROR.
             IF NOT AVAILABLE AONRTAB THEN DO:
                FIND FIRST AONRTAB WHERE AONRTAB.OMRADE = hjomr AND AONRTAB.AONRAVDATUM = 01/01/1991
                AND AONRTAB.FASTAAONR = TRUE  NO-LOCK NO-ERROR.
                IF NOT AVAILABLE AONRTAB THEN DO:
                   FIND FIRST AONRTAB WHERE AONRTAB.OMRADE = hjomr AND AONRTAB.AONRAVDATUM = 01/01/1991
                   AND AONRTAB.FASTAAONR = FALSE  NO-LOCK NO-ERROR. 
                END.
                IF AVAILABLE AONRTAB THEN DO:
                   ASSIGN
                   sok1 = AONRTAB.AONR
                   sok2 = AONRTAB.DELNR.
                END.
                ELSE sok1 = "FINNS EJ".         
             END.
             ELSE DO:        
                ASSIGN
                sok1 = TIDREGITAB.AONR
                sok2 = TIDREGITAB.DELNR.
             END.
         END.
      END.
      ELSE sok1 = "FINNS EJ".         
   END.
   
END.
ELSE IF sok0 = 2 THEN DO:
   FIND FIRST AONRTAB WHERE AONRTAB.AONR = sok1 AND AONRTAB.DELNR = sok2
   NO-LOCK NO-ERROR.
   ASSIGN
   sok2 = AONRTAB.TRAKTAMENTE 
   sok3 = AONRTAB.PRISTYP. 
   IF AVAILABLE AONRTAB THEN DO:   
      FIND FIRST TIMKOSTNADSTAB WHERE TIMKOSTNADSTAB.PERSONALKOD = sok4 AND
      TIMKOSTNADSTAB.PRISTYP = AONRTAB.PRISTYP
      NO-LOCK NO-ERROR.
      IF AVAILABLE TIMKOSTNADSTAB THEN sok5 = TIMKOSTNADSTAB.PRISA.
      ELSE sok5 = 0.
   END.   
END.
ELSE IF sok0 = 3 THEN DO:
   FIND FIRST TIMKOSTNADSTAB WHERE TIMKOSTNADSTAB.PERSONALKOD = sok4 AND
   TIMKOSTNADSTAB.PRISTYP = sok3
   NO-LOCK NO-ERROR.
   IF AVAILABLE TIMKOSTNADSTAB THEN sok5 = TIMKOSTNADSTAB.PRISA.
   ELSE sok5 = ?.
END.
ELSE IF sok0 = 4 THEN DO:
   sok2 = 0.
   FIND LAST FLEXTID WHERE FLEXTID.PERSONALKOD = sok1 AND
   FLEXTID.DATUM = TODAY
   USE-INDEX FLEX NO-LOCK NO-ERROR.     
   IF NOT AVAILABLE FLEXTID THEN DO:
      sok2 = 1.
   END.
END.
ELSE IF sok0 = 5 THEN DO:
   sok2 = 0.
   FIND FIRST ORDARB WHERE ORDARB.ANSTALLNING = sok1 NO-LOCK NO-ERROR.    
   IF NOT AVAILABLE ORDARB THEN DO:
      sok2 = 1.
   END.
   ELSE sok5 = ORDARB.START1.
END.
ELSE IF sok0 = 6 THEN DO:
   sok2 = 0.   
   sok4 = " ".
   FIND FIRST ORDARB WHERE ORDARB.ANSTALLNING = sok1 NO-LOCK NO-ERROR.    
   IF NOT AVAILABLE ORDARB THEN DO:
      sok2 = 1.
   END.
   ELSE DO: 
      sok4 = ORDARB.OBKOD.
      sok5 = ORDARB.STOPP1.
   END.   
END.
ELSE IF sok0 = 7 THEN DO:
   sok2 = 0.
   FIND FIRST OVERAVTAB WHERE OVERAVTAB.DATUM = DATE(sok4) AND 
   OVERAVTAB.KOD = sok1 USE-INDEX ODATUM NO-LOCK NO-ERROR.
   IF AVAILABLE OVERAVTAB AND OVERAVTAB.DAGEQ = "HAL"  THEN DO:
      sok2 = 1.      
   END.    
   ELSE sok2 = 0.
END.
ELSE IF sok0 = 8 THEN DO:
   sok2 = 0.
   FIND FIRST OVERAVTAB WHERE OVERAVTAB.DATUM = DATE(sok4) AND 
   OVERAVTAB.KOD = sok1 USE-INDEX ODATUM NO-LOCK NO-ERROR.
   IF NOT AVAILABLE OVERAVTAB THEN DO:
      sok2 = 0.      
   END.    
   ELSE sok2 = OVERAVTAB.EQDAG. 
END.
ELSE IF sok0 = 9 THEN DO:
   testdatum = DATE(sok4).
   FIND FIRST GODKOLL WHERE GODKOLL.PERSONALKOD = sok1 AND
   GODKOLL.DATAR = YEAR(testdatum) AND GODKOLL.DATMAN = MONTH(testdatum)
   USE-INDEX PKODAR NO-LOCK NO-ERROR.         
   IF AVAILABLE GODKOLL THEN DO:
      sok4 = STRING(GODKOLL.DATUM).
   END.
   ELSE DO:
      sok4 = "".
   END.
END.
ELSE IF sok0 = 10 THEN DO:
   FIND LAST FLEXTID WHERE FLEXTID.PERSONALKOD = sok4
   AND FLEXTID.AONR NE "" AND FLEXTID.AUTO = "AUTO" NO-LOCK NO-ERROR.
   IF AVAILABLE FLEXTID THEN DO:
      ASSIGN
      sok1 = FLEXTID.AONR
      sok2 = FLEXTID.DELNR.
   END.
END.
ELSE IF sok0 = 11 THEN DO:
   FIND LAST FLEXTID WHERE FLEXTID.PERSONALKOD = sok4 USE-INDEX FLEX NO-LOCK NO-ERROR.  
   IF AVAILABLE FLEXTID THEN DO:      
      ASSIGN
      sok1 = FLEXTID.AONR
      sok2 = FLEXTID.DELNR
      sok4 = STRING(FLEXTID.DATUM)
      sok5 = FLEXTID.TID  
      sok3 = FLEXTID.KNAPP.      
   END.
   ELSE sok1 = "X". 
END.
ELSE IF sok0 = 12 THEN DO:
   sok2 = TIME.   
END.
ELSE IF sok0 = 13 THEN DO:
   FIND FIRST FLEXTID WHERE FLEXTID.PERSONALKOD = sok1 AND FLEXTID.DATUM = DATE(sok3)
   USE-INDEX FLEX NO-LOCK NO-ERROR.  
   IF AVAILABLE FLEXTID THEN DO:      
      ASSIGN
      sok1 = FLEXTID.AONR
      sok2 = FLEXTID.DELNR
      sok4 = STRING(FLEXTID.DATUM)
      sok5 = FLEXTID.TID  
      sok3 = FLEXTID.KNAPP.      
   END.
   ELSE sok1 = "X". 
END.
ELSE IF sok0 = 14 THEN DO:
   FIND FIRST FLEXTID WHERE FLEXTID.PERSONALKOD = sok1 AND
   FLEXTID.DATUM = DATE(sok4) AND FLEXTID.ORSAK NE "" NO-LOCK NO-ERROR.
   IF AVAILABLE FLEXTID THEN DO:      
      sok1 = FLEXTID.ORSAK.      
   END.
   ELSE sok1 = "". 
END.
ELSE IF sok0 = 15 THEN DO:
   FIND FIRST VKORN USE-INDEX VKORN NO-LOCK NO-ERROR.
   IF AVAILABLE VKORN THEN DO:
      IF VKORN.VECKOK = TRUE THEN sok1 = "KOR".      
      ELSE sok1 = "".
   END.
   ELSE sok1 = "". 
END.
ELSE IF sok0 = 16 THEN DO:   
   FIND FIRST AONRTAB WHERE AONRTAB.AONR = sok1 AND AONRTAB.DELNR = sok2
   NO-LOCK NO-ERROR.
   IF AVAILABLE AONRTAB THEN DO:   
      ASSIGN 
      sok1 = AONRTAB.PRISTYP
      sok2 = AONRTAB.TRAKTAMENTE
      sok3 = AONRTAB.ARBUPPG[1].
      IF AONRTAB.UTRYCKNING = TRUE THEN sok3 = "1".
      IF AONRTAB.UTRYCKNING = FALSE THEN sok3 = "2".
      IF sok4 NE "" THEN DO:
         FIND FIRST TIMKOSTNADSTAB WHERE TIMKOSTNADSTAB.PERSONALKOD = sok4 AND
         TIMKOSTNADSTAB.PRISTYP = AONRTAB.PRISTYP
         NO-LOCK NO-ERROR.
         ASSIGN
         sok1 = AONRTAB.PRISTYP.
         IF AVAILABLE TIMKOSTNADSTAB THEN sok5 = TIMKOSTNADSTAB.PRISA.
         ELSE sok5 = 0.         
      END.
   END.
   ELSE DO:
      ASSIGN
      sok1 = ""
      sok3 = "".    
   END.
END.
ELSE IF sok0 = 17 THEN DO:   
   sok2 = 0.
   FIND FIRST FLEXDAG WHERE FLEXDAG.PERSONALKOD = sok1 AND FLEXDAG.DATUM = DATE(sok4) 
   NO-LOCK NO-ERROR.
   IF AVAILABLE FLEXDAG THEN DO:
      IF FLEXDAG.START = sok5 THEN DO:                
         sok2 = 1.
      END.
   END.     
END.
ELSE IF sok0 = 18 THEN DO:   
   sok2 = 0.
   FIND FIRST FLEXDAG WHERE FLEXDAG.PERSONALKOD = sok1 AND FLEXDAG.DATUM = DATE(sok4) 
   NO-LOCK NO-ERROR.
   IF AVAILABLE FLEXDAG THEN DO:
      IF FLEXDAG.SLUT = sok5 THEN DO:                
         sok2 = 1.
      END.
   END.      
END.
ELSE IF sok0 = 19 THEN DO:   
   sok2 = 0.
   FIND FIRST LONTILL WHERE LONTILL.KOD = sok1 AND LONTILL.LONTILLAGG = sok4
   NO-LOCK NO-ERROR.
   IF AVAILABLE LONTILL THEN DO:
      ASSIGN
      sok1 = LONTILL.ENHET
      sok3 = LONTILL.LONKODTEXT
      sok2 = 1.   
   END.      
END.
ELSE IF sok0 = 20 THEN DO:   
   FIND FIRST AONRTAB WHERE AONRTAB.AONR = sok1 AND AONRTAB.DELNR = sok2
   NO-LOCK NO-ERROR.
   IF AVAILABLE AONRTAB THEN DO:   
      ASSIGN 
      sok3 = AONRTAB.ARBUPPG[1].      
   END.
   ELSE sok3 = "".      
END.
ELSE IF sok0 = 21 THEN DO:   
   FIND FIRST PERSONALTAB WHERE PERSONALTAB.PERSONALKOD = sok1 NO-LOCK NO-ERROR.
   FIND FIRST BEREDSKAPTAB WHERE BEREDSKAPTAB.BEREDSKAP = sok3 AND 
   BEREDSKAPTAB.BEREDSKAPSAVTAL = PERSONALTAB.BEREDSKAPSAVTAL 
   USE-INDEX BERED NO-LOCK NO-ERROR.
   IF AVAILABLE BEREDSKAPTAB THEN DO:
      sok2 = BEREDSKAPTAB.BERANTAL.
   END.
   ELSE sok3 = "xxx".            
END.
ELSE IF sok0 = 22 THEN DO:   
   FIND FIRST PERSONALTAB WHERE PERSONALTAB.PERSONALKOD = sok1 NO-LOCK NO-ERROR.
   FIND FIRST BEREDSKAPAV WHERE BEREDSKAPAV.BEREDSKAP = sok3 AND 
   BEREDSKAPAV.BEREDSKAPSAVTAL = PERSONALTAB.BEREDSKAPSAVTAL 
   USE-INDEX BERAV NO-LOCK NO-ERROR.
   IF AVAILABLE BEREDSKAPAV THEN DO:            
      sok2 = BEREDSKAPAV.BERANTAL.
   END.
   ELSE sok3 = "xxx".            
END.
ELSE IF sok0 = 23 THEN DO:   
   FIND FIRST PERSONALTAB WHERE PERSONALTAB.PERSONALKOD = sok1 NO-LOCK NO-ERROR.
   FIND FIRST BEREDSKAPTAB WHERE 
   BEREDSKAPTAB.BEREDSKAPSAVTAL = PERSONALTAB.BEREDSKAPSAVTAL 
   USE-INDEX BERED NO-LOCK NO-ERROR.
   IF AVAILABLE BEREDSKAPTAB THEN DO:
      sok2 = BEREDSKAPTAB.BERANTAL.
   END.
   ELSE sok3 = "xxx".            
END.
ELSE IF sok0 = 24 THEN DO:   
   sok2 = 0.
   FIND FIRST LONFLER WHERE LONFLER.TRAAVTAL = sok1 AND
   LONFLER.DAGTYP = "REDUCER" NO-LOCK NO-ERROR.
   IF AVAILABLE LONFLER THEN sok2 = 1.
   FIND FIRST TRAKTFLER WHERE TRAKTFLER.TRAAVTAL = sok1 AND
   TRAKTFLER.DAGTYP = "REDUCER" NO-LOCK NO-ERROR.
   IF AVAILABLE TRAKTFLER THEN sok2 = 1.            
END.
ELSE IF sok0 = 25 THEN DO:   
   FIND FIRST TRAKTFLER WHERE TRAKTFLER.TRAAVTAL = sok1 AND
   TRAKTFLER.DAGTYP = "HELDAGR" NO-LOCK NO-ERROR.
   IF AVAILABLE TRAKTFLER THEN sok2 = 1.            
   ELSE sok2 = 0.
END.
ELSE IF sok0 = 26 THEN DO:   
   FIND FIRST BILFORARE NO-LOCK NO-ERROR.
   IF BILFORARE.BILFOR = TRUE THEN sok2 = 1.
   ELSE sok2 = 0.
END.
ELSE IF sok0 = 27 THEN DO:   
   FIND FIRST RESTIDTAB WHERE RESTIDTAB.KOD = sok1 AND
   RESTIDTAB.ENFL = sok3 NO-LOCK NO-ERROR.
   IF NOT AVAILABLE RESTIDTAB THEN sok2 = 1.
   ELSE sok2 = 0.
END.
ELSE IF sok0 = 28 THEN DO:
   sok2 = 0.
   FIND FIRST TIDREGITAB WHERE TIDREGITAB.PERSONALKOD = sok1 AND
   TIDREGITAB.DATUM = DATE(sok4) AND TIDREGITAB.TIDLOG = TRUE 
   USE-INDEX PSTART NO-LOCK NO-ERROR.
   IF AVAILABLE TIDREGITAB THEN DO:
      IF TIDREGITAB.START < sok5 THEN DO:
         sok2 = 1.
      END.      
   END.  
END.
ELSE IF sok0 = 29 THEN DO:
   sok2 = 0.
   FIND LAST TIDREGITAB WHERE TIDREGITAB.PERSONALKOD = sok1 AND
   TIDREGITAB.DATUM = DATE(sok4) AND TIDREGITAB.TIDLOG = TRUE 
   USE-INDEX PSTART NO-LOCK NO-ERROR.
   IF AVAILABLE TIDREGITAB THEN DO:
      IF TIDREGITAB.SLUT > sok5 THEN DO:
         sok2 = 1.
      END.      
   END.  
END.

ELSE IF sok0 = 30 THEN DO:
   sok2 = 0.
   FIND FIRST ERSATTNING NO-LOCK NO-ERROR.
   IF AVAILABLE ERSATTNING THEN DO:
      sok2 = 1.      
   END.  
END.
ELSE IF sok0 = 31 THEN DO:
   sok2 = 0.
   FIND FIRST TIDREGITAB WHERE TIDREGITAB.PERSONALKOD = sok1 AND
   TIDREGITAB.DATUM = DATE(sok4) AND
   TIDREGITAB.START LE sok5 AND
   TIDREGITAB.SLUT > sok5 AND TIDREGITAB.TIDLOG = TRUE AND 
   TIDREGITAB.PRISTYP NE sok3 
   USE-INDEX PSTART NO-LOCK NO-ERROR.
   IF NOT AVAILABLE TIDREGITAB THEN DO:
      sok3 = "xxx".      
   END.  
   ELSE DO:
      ASSIGN
      sok2 = TIDREGITAB.START * 100
      sok5 = TIDREGITAB.SLUT. 
   END.
END.
ELSE IF sok0 = 32 THEN DO:
   sokhjalp = sok2 / 100.
   FIND FIRST TIDREGITAB WHERE 
   TIDREGITAB.PERSONALKOD = sok1 AND
   TIDREGITAB.DATUM = DATE(sok4) AND TIDREGITAB.START < sok5 AND
   TIDREGITAB.SLUT >= sok5 AND TIDREGITAB.TIDLOG = TRUE AND
   TIDREGITAB.PRISTYP NE sok3
   USE-INDEX PSTART NO-LOCK NO-ERROR.   
   IF NOT AVAILABLE TIDREGITAB THEN DO: 
      FIND FIRST TIDREGITAB WHERE 
      TIDREGITAB.PERSONALKOD = sok1 AND
      TIDREGITAB.DATUM = DATE(sok4) AND TIDREGITAB.START > sokhjalp AND
      TIDREGITAB.SLUT < sok5 AND TIDREGITAB.TIDLOG = TRUE AND
      TIDREGITAB.PRISTYP NE "RESTID..."
      USE-INDEX PSTART NO-LOCK NO-ERROR.  
   END.
   IF NOT AVAILABLE TIDREGITAB THEN DO:
      sok3 = "xxx".
   END.
   ELSE DO:
      ASSIGN
      sok2 = TIDREGITAB.START * 100
      sok5 = TIDREGITAB.SLUT. 
   END.
END.
ELSE IF sok0 = 33 THEN DO:
   sokhjalp = sok2 / 100.
   FIND FIRST TIDREGITAB WHERE 
   TIDREGITAB.PERSONALKOD = sok1 AND
   TIDREGITAB.DATUM = DATE(sok4) AND TIDREGITAB.START GE sokhjalp AND
   TIDREGITAB.SLUT LE 24.00 AND TIDREGITAB.TIDLOG = TRUE AND
   TIDREGITAB.PRISTYP NE sok3
   USE-INDEX PSTART NO-LOCK NO-ERROR.
   IF NOT AVAILABLE TIDREGITAB THEN DO:
      FIND FIRST TIDREGITAB WHERE 
      TIDREGITAB.PERSONALKOD = PERSONALTAB.PERSONALKOD AND
      TIDREGITAB.DATUM = (DATE(sok4) + 1) AND TIDREGITAB.START GE 00.00 AND
      TIDREGITAB.SLUT LE sok5 AND TIDREGITAB.TIDLOG = TRUE AND
      TIDREGITAB.PRISTYP NE "RESTID..."
      USE-INDEX PSTART NO-LOCK NO-ERROR.
   END.
   IF NOT AVAILABLE TIDREGITAB THEN DO:
      sok3 = "xxx".
   END.
   ELSE DO:
      ASSIGN
      sok2 = TIDREGITAB.START * 100
      sok5 = TIDREGITAB.SLUT. 
   END.
END.
ELSE IF sok0 = 34 THEN DO:
   sokhjalp = sok2 / 100.
   FIND FIRST TIDREGITAB WHERE 
   TIDREGITAB.PERSONALKOD = sok1 AND
   TIDREGITAB.DATUM = DATE(sok4) AND TIDREGITAB.START LE sokhjalp AND
   TIDREGITAB.SLUT > sokhjalp AND TIDREGITAB.TIDLOG = TRUE 
   USE-INDEX PSTART NO-LOCK NO-ERROR.              
   IF NOT AVAILABLE TIDREGITAB THEN DO:
      sok3 = "xxx".
   END.
   ELSE DO:
      ASSIGN
      sok3 = ""
      sok2 = TIDREGITAB.START * 100
      sok5 = TIDREGITAB.SLUT. 
   END.
END.

ELSE IF sok0 = 35 THEN DO:
   sok4 = "".
   IF sok2 = 1 THEN sokhjalp2 = TRUE.
   IF sok2 = 0 THEN sokhjalp2 = FALSE.
   FIND FIRST MALTAB WHERE MALTAB.AVDRAGSKOD = sok1 AND
   MALTAB.TRAAVTAL = sok3 AND MALTAB.HEL = 1.00 AND 
   MALTAB.FRUKOST = FALSE AND MALTAB.ENFLER = sokhjalp2 
   USE-INDEX MALTAB NO-LOCK NO-ERROR.
   IF NOT AVAILABLE MALTAB THEN DO:
      SUBSTRING(sok4,1,1) = "T".             
   END.
   ELSE SUBSTRING(sok4,1,1) = "F".             
   FIND FIRST MALTAB WHERE MALTAB.AVDRAGSKOD = sok1 AND
   MALTAB.TRAAVTAL = sok3 AND MALTAB.HEL = 1.00 AND 
   MALTAB.LUNCH = FALSE AND MALTAB.ENFLER = sokhjalp2 
   USE-INDEX MALTAB NO-LOCK NO-ERROR.
   IF NOT AVAILABLE MALTAB THEN DO:
      SUBSTRING(sok4,2,1) = "T".             
   END.
   ELSE SUBSTRING(sok4,2,1) = "F".  
   FIND FIRST MALTAB WHERE MALTAB.AVDRAGSKOD = sok1 AND
   MALTAB.TRAAVTAL = sok3 AND MALTAB.HEL = 1.00 AND 
   MALTAB.MIDDAG = FALSE AND MALTAB.ENFLER = sokhjalp2 
   USE-INDEX MALTAB NO-LOCK NO-ERROR.
   IF NOT AVAILABLE MALTAB THEN DO:
      SUBSTRING(sok4,3,1) = "T".             
   END.
   ELSE SUBSTRING(sok4,3,1) = "F".
END.
ELSE IF sok0 = 36 THEN DO:
   sok4 = "".
   IF sok2 = 1 THEN sokhjalp2 = TRUE.
   IF sok2 = 0 THEN sokhjalp2 = FALSE.
   FIND FIRST KFORMAN WHERE KFORMAN.AVDRAGSKOD = sok1 AND
   KFORMAN.TRAAVTAL = sok3 AND KFORMAN.HEL = 1.00 AND 
   KFORMAN.FRUKOST = FALSE AND KFORMAN.ENFLER = sokhjalp2 
   USE-INDEX KFORMAN NO-LOCK NO-ERROR.
   IF NOT AVAILABLE KFORMAN THEN DO:
      SUBSTRING(sok4,1,1) = "T".             
   END.
   ELSE SUBSTRING(sok4,1,1) = "F".             
   FIND FIRST KFORMAN WHERE KFORMAN.AVDRAGSKOD = sok1 AND
   KFORMAN.TRAAVTAL = sok3 AND KFORMAN.HEL = 1.00 AND 
   KFORMAN.LUNCH = FALSE AND KFORMAN.ENFLER = sokhjalp2 
   USE-INDEX KFORMAN NO-LOCK NO-ERROR.
   IF NOT AVAILABLE KFORMAN THEN DO:
      SUBSTRING(sok4,2,1) = "T".             
   END.
   ELSE SUBSTRING(sok4,2,1) = "F".  
   FIND FIRST KFORMAN WHERE KFORMAN.AVDRAGSKOD = sok1 AND
   KFORMAN.TRAAVTAL = sok3 AND KFORMAN.HEL = 1.00 AND 
   KFORMAN.MIDDAG = FALSE AND KFORMAN.ENFLER = sokhjalp2 
   USE-INDEX KFORMAN NO-LOCK NO-ERROR.
   IF NOT AVAILABLE KFORMAN THEN DO:
      SUBSTRING(sok4,3,1) = "T".             
   END.
   ELSE SUBSTRING(sok4,3,1) = "F".
END.                 
ELSE IF sok0 = 37 THEN DO:
   FIND FIRST TIMKOSTNADSTAB WHERE TIMKOSTNADSTAB.PERSONALKOD = sok1 AND
   TIMKOSTNADSTAB.PRISTYP = sok3 USE-INDEX PRISPERS NO-LOCK NO-ERROR.
   ASSIGN  
   sok5 = TIMKOSTNADSTAB.PRISA. 
   FIND FIRST TIMKOSTNADSTAB WHERE TIMKOSTNADSTAB.PERSONALKOD = sok1 AND
   TIMKOSTNADSTAB.PRISTYP = sok4 USE-INDEX PRISPERS NO-LOCK NO-ERROR.
   IF AVAILABLE TIMKOSTNADSTAB THEN sok2 = TIMKOSTNADSTAB.PRISA * 100.
   ELSE sok2 = 0.   
END.
ELSE IF sok0 = 38 THEN DO:   
   FIND FIRST RESTIDTAB WHERE RESTIDTAB.KOD = sok1 AND
   RESTIDTAB.DAGNR = 3 AND RESTIDTAB.ENFL = sok3 NO-LOCK NO-ERROR.
   IF NOT AVAILABLE RESTIDTAB THEN sok2 = 1.
   ELSE DO: 
      sok2 = 0.
      sok4 = RESTIDTAB.LONTILLAGG.
   END.
END.
ELSE IF sok0 = 39 THEN DO:   
   FIND FIRST TIDREGITAB WHERE TIDREGITAB.PERSONALKOD = sok1 AND
   TIDREGITAB.DATUM = DATE(sok4) AND TIDREGITAB.PRISTYP =  "RESTID.." AND 
   TIDREGITAB.TIDLOG = TRUE USE-INDEX PKOD NO-LOCK NO-ERROR.
   IF AVAILABLE TIDREGITAB THEN DO:
      ASSIGN
      sok5 = TIDREGITAB.START.     
   END.   
   ELSE ASSIGN sok5 = 0.
END.
ELSE IF sok0 = 40 THEN DO:   
   FIND LAST TIDREGITAB WHERE TIDREGITAB.PERSONALKOD = sok1 AND
   TIDREGITAB.DATUM = DATE(sok4) AND TIDREGITAB.PRISTYP =  "RESTID.." AND 
   TIDREGITAB.TIDLOG = TRUE USE-INDEX PKOD NO-LOCK NO-ERROR.
   IF AVAILABLE TIDREGITAB THEN DO:
      ASSIGN
      sok5 = TIDREGITAB.SLUT.     
   END.   
   ELSE ASSIGN sok5 = 0.
END.
ELSE IF sok0 = 41 THEN DO:
   sokhjalp = sok2 / 100.
   FIND FIRST TIDREGITAB WHERE 
   TIDREGITAB.PERSONALKOD = sok1 AND
   TIDREGITAB.DATUM = DATE(sok4) AND TIDREGITAB.START < sok5 AND
   TIDREGITAB.SLUT >= sok5 AND TIDREGITAB.TIDLOG = TRUE 
   USE-INDEX PSTART NO-LOCK NO-ERROR.   
   IF NOT AVAILABLE TIDREGITAB THEN DO: 
      FIND FIRST TIDREGITAB WHERE 
      TIDREGITAB.PERSONALKOD = sok1 AND
      TIDREGITAB.DATUM = DATE(sok4) AND TIDREGITAB.START > sokhjalp AND
      TIDREGITAB.SLUT < sok5 AND TIDREGITAB.TIDLOG = TRUE       
      USE-INDEX PSTART NO-LOCK NO-ERROR.              
   END.
   IF NOT AVAILABLE TIDREGITAB THEN DO:
      sok3 = "xxx".
   END.
   ELSE DO:
      ASSIGN
      sok3 = ""
      sok2 = TIDREGITAB.START * 100
      sok5 = TIDREGITAB.SLUT. 
   END.            
END.
ELSE IF sok0 = 42 THEN DO:
   sokhjalp = sok2 / 100.
   FIND FIRST TIDREGITAB WHERE 
   TIDREGITAB.PERSONALKOD = sok1 AND
   TIDREGITAB.DATUM = DATE(sok4) AND TIDREGITAB.START GE sokhjalp AND
   TIDREGITAB.START < sok5 AND
   TIDREGITAB.SLUT > TIDREGITAB.START  AND TIDREGITAB.TIDLOG = TRUE 
   USE-INDEX PSTART NO-LOCK NO-ERROR.      
   IF NOT AVAILABLE TIDREGITAB THEN DO:
      sok3 = "xxx".
   END.
   ELSE DO:
      ASSIGN
      sok3 = ""
      sok2 = TIDREGITAB.START * 100
      sok5 = TIDREGITAB.SLUT. 
   END.            
END.
ELSE IF sok0 = 43 THEN DO:
   sokhjalp = sok2 / 100.
   FIND FIRST TIDREGITAB WHERE 
   TIDREGITAB.PERSONALKOD = sok1 AND
   TIDREGITAB.DATUM = DATE(sok4) AND TIDREGITAB.START < sokhjalp AND
   TIDREGITAB.SLUT > sok5 AND
   TIDREGITAB.SLUT > TIDREGITAB.START  AND TIDREGITAB.TIDLOG = TRUE 
   USE-INDEX PSTART NO-LOCK NO-ERROR.      
   IF NOT AVAILABLE TIDREGITAB THEN DO:
      sok3 = "xxx".
   END.
   ELSE DO:
      ASSIGN
      sok3 = ""
      sok2 = TIDREGITAB.START * 100
      sok5 = TIDREGITAB.SLUT. 
   END.            
END.
ELSE IF sok0 = 44 THEN DO:   
   sok5 = 0.
   FOR EACH TIDREGITAB WHERE 
   TIDREGITAB.PERSONALKOD = sok1 AND
   TIDREGITAB.DATUM = DATE(sok4) AND TIDREGITAB.PRISTYP = sok3 
   USE-INDEX PSTART NO-LOCK:
      ASSIGN      
      sok5 = sok5 + klock100(TIDREGITAB.TOTALT).      
   END.            
END.
ELSE IF sok0 = 45 THEN DO:   
   sok2 = 0.
   FIND FIRST TIDREGITAB WHERE TIDREGITAB.PERSONALKOD = sok1 AND TIDREGITAB.DATUM = DATE(sok4) 
   AND TIDREGITAB.TIDLOG = TRUE NO-LOCK NO-ERROR.
   IF AVAILABLE TIDREGITAB THEN DO:      
      sok2 = TIDREGITAB.LAGANTAL.     
   END.     
END.
ELSE IF sok0 = 46 THEN DO:   
   sokhjalp = klock100(sok5).
   sok5 = 0.
   FIND FIRST PERSONALTAB WHERE PERSONALTAB.PERSONALKOD = sok1 NO-LOCK NO-ERROR.
   IF PERSONALTAB.BEREDSKAPSAVTAL = "I" THEN DO:   
      FOR EACH TIDREGITAB WHERE TIDREGITAB.PERSONALKOD = sok1 AND TIDREGITAB.DATUM = DATE(sok4) 
      AND TIDREGITAB.TIDLOG = TRUE AND TIDREGITAB.OVERTIDUTTAG = "F" NO-LOCK:
         IF TIDREGITAB.AONR = "155" OR TIDREGITAB.AONR = "160" OR TIDREGITAB.AONR = "170" THEN sok1 = sok1.
         ELSE DO:      
            sok5 = sok5 + klock100(TIDREGITAB.TOTALT).      
         END.
      END.     
      IF sok5 GE sokhjalp THEN sok2 = 0.
      ELSE DO:
          sok2 = 1.
          sok5 = klock60(sokhjalp - sok5).
      END.    
   END.
   ELSE sok2 = 0.    
END.
ELSE IF sok0 = 47 THEN DO:   
   sok2 = 0.
   FIND FIRST FLEXDAG WHERE FLEXDAG.PERSONALKOD = sok1 AND FLEXDAG.DATUM = DATE(sok4) 
   NO-LOCK NO-ERROR.
   IF AVAILABLE FLEXDAG THEN DO:            
      sok2 = (klock60( klock100(FLEXDAG.PLUS) + klock100(FLEXDAG.FLARB) + klock100(FLEXDAG.OVUTPLUS))) * 100.            
   END.     
END.
ELSE IF sok0 = 48 THEN DO:      
   sok2 = 0.
   FIND FIRST TIDREGITAB WHERE 
   TIDREGITAB.PERSONAL = sok1 AND
   TIDREGITAB.DATUM = DATE(sok4) AND TIDREGITAB.START < sok5 AND
   TIDREGITAB.SLUT >= sok5 AND TIDREGITAB.TIDLOG = TRUE 
   USE-INDEX PSTART NO-LOCK NO-ERROR.   
   IF NOT AVAILABLE TIDREGITAB THEN DO: 
      FIND FIRST TIDREGITAB WHERE 
      TIDREGITAB.PERSONAL = sok1 AND
      TIDREGITAB.DATUM = DATE(sok4) AND TIDREGITAB.SLUT < sok5 AND TIDREGITAB.TIDLOG = TRUE 
      USE-INDEX PSTART NO-LOCK NO-ERROR.        
   END.
   IF AVAILABLE TIDREGITAB THEN DO:      
      sok2 = 1.
   END.
      
END.
ELSE IF sok0 = 49 THEN DO:      
   ASSIGN
   sokhjalp = klock100(sok5)
   sokhjalp1 = 0
   sok5 = 0
   sok3 = ""
   sok2 = 0.
   FIND FIRST FLEXDAG WHERE FLEXDAG.PERSONALKOD = sok1 AND FLEXDAG.DATUM = DATE(sok4)NO-LOCK NO-ERROR.
   IF AVAILABLE FLEXDAG THEN DO:
      sok2 = 100 * FLEXDAG.SLUT .
   END.
   FIND FIRST PERSONALTAB WHERE PERSONALTAB.PERSONALKOD = sok1 NO-LOCK NO-ERROR.
   sok3 = PERSONALTAB.BEREDSKAPSAVTAL.   
   FOR EACH TIDREGITAB WHERE TIDREGITAB.PERSONALKOD = sok1 AND TIDREGITAB.DATUM = DATE(sok4) 
   AND TIDREGITAB.TIDLOG = TRUE AND TIDREGITAB.OVERTIDUTTAG = "F" NO-LOCK:
      IF TIDREGITAB.AONR = "155" OR TIDREGITAB.AONR = "160" OR TIDREGITAB.AONR = "170" THEN sok1 = sok1.
      ELSE DO:      
         sokhjalp1 = sokhjalp1 + klock100(TIDREGITAB.TOTALT).      
      END.
   END.     
   IF sokhjalp1 GE sokhjalp THEN sok5 = 0.
   ELSE IF sokhjalp = 0 THEN sok5 = 0.
   ELSE sok5 = 1.       
END.
ELSE IF sok0 = 50 THEN DO:
   sok1 = "".
   FIND FIRST FLEXTID WHERE FLEXTID.PERSONALKOD = sok4 AND  FLEXTID.DATUM = DATE(sok4) AND  FLEXTID.TID = sok5 USE-INDEX FLEX NO-LOCK NO-ERROR.  
   IF AVAILABLE FLEXTID THEN DO:      
      sok1 = "X".   
   END.    
END.

ELSE IF sok0 = 51 THEN DO:

   IF NOT VALID-HANDLE(kompapph) THEN RUN KOMPSMANTAB.P PERSISTENT SET kompapph.
   IF VALID-HANDLE(kompapph) THEN DO:
      DEBUGGER:SET-BREAK().
      FIND FIRST PERSONALTAB WHERE PERSONALTAB.PERSONALKOD = sok1 NO-LOCK NO-ERROR.
      FIND FIRST ANSTFORMTAB WHERE ANSTFORMTAB.ANSTALLNING = PERSONALTAB.ANSTALLNING
      USE-INDEX ANSTF NO-LOCK NO-ERROR.
      hjdatum  = DATE((MONTH(TODAY) + 1),01,YEAR(TODAY)) - 1.
      RUN viskompsal IN kompapph (INPUT PERSONALTAB.PERSONALKOD, INPUT hjdatum, OUTPUT acckompvman, OUTPUT acckompvmandat, OUTPUT acckompsenast,  OUTPUT acckompsenastdat).
      komputtag = 0.
      OPEN QUERY toUq FOR EACH TIDREGITAB WHERE TIDREGITAB.PERSONALKOD = PERSONALTAB.PERSONALKOD AND TIDREGITAB.VECKOKORD = ""
      AND TIDREGITAB.DATUM LE hjdatum AND TIDREGITAB.AONR = "170"  NO-LOCK.
      GET FIRST touq NO-LOCK.
      DO WHILE AVAILABLE (TIDREGITAB):
         komputtag = komputtag + klock100(TIDREGITAB.TOTALT).
         GET NEXT touq NO-LOCK. 
      END.         
      antmult = 0.
      OPEN QUERY toq FOR EACH TIDREGITAB WHERE TIDREGITAB.PERSONALKOD = PERSONALTAB.PERSONALKOD AND TIDREGITAB.VECKOKORD = ""
      AND TIDREGITAB.DATUM LE hjdatum AND  TIDREGITAB.OVERTIDUTTAG = "K"  NO-LOCK.
      GET FIRST toq NO-LOCK.
      DO WHILE AVAILABLE (TIDREGITAB):
         IF TIDREGITAB.OKOD1 = "" AND TIDREGITAB.OKOD2 = "" AND TIDREGITAB.OKOD3 = "" THEN.
         ELSE DO:                                 
            IF TIDREGITAB.OANT1 > 0  THEN DO:
               FIND FIRST OVERKOD WHERE OVERKOD.OVERTIDTILL = TIDREGITAB.OKOD1 AND OVERKOD.KOD = ANSTFORMTAB.KOD USE-INDEX OVER NO-LOCK NO-ERROR.
               IF AVAILABLE  OVERKOD THEN DO:                                
                  antmult = antmult + ((1 + OVERKOD.ERSATTNING) * klock100(TIDREGITAB.OANT1)).
               END.
            END.
            IF TIDREGITAB.OANT2 > 0  THEN DO:
               FIND FIRST OVERKOD WHERE OVERKOD.OVERTIDTILL = TIDREGITAB.OKOD2 AND OVERKOD.KOD = ANSTFORMTAB.KOD USE-INDEX OVER NO-LOCK NO-ERROR.
               IF AVAILABLE  OVERKOD THEN DO:                                
                  antmult = antmult + ((1 + OVERKOD.ERSATTNING) * klock100(TIDREGITAB.OANT2)).
               END.
            END.  
            IF TIDREGITAB.OANT3 > 0  THEN DO:
               FIND FIRST OVERKOD WHERE OVERKOD.OVERTIDTILL = TIDREGITAB.OKOD3 AND OVERKOD.KOD = ANSTFORMTAB.KOD USE-INDEX OVER NO-LOCK NO-ERROR.
               IF AVAILABLE  OVERKOD THEN DO:                                
                  antmult = antmult + ((1 + OVERKOD.ERSATTNING) * klock100(TIDREGITAB.OANT3)).
               END.
            END. 
         END.
         GET NEXT toq NO-LOCK.
      END.         
             
      /*berdskapstolkning när veckvila inträffar under klämdag genererar lart 260 = Fyllnadslön mot ledighet vid beredskap Lena 20190611*/      
      OPEN QUERY tblq FOR EACH TIDREGITAB WHERE
      TIDREGITAB.PERSONALKOD = PERSONALTAB.PERSONALKOD AND TIDREGITAB.VECKOKORD = "" AND  TIDREGITAB.DATUM LE hjdatum  AND
      TIDREGITAB.LONTILLAGG = "260"  USE-INDEX PSTART NO-LOCK.   
      GET FIRST tblq NO-LOCK.
      DO WHILE AVAILABLE(TIDREGITAB):
         antmult = antmult +  klock100(TIDREGITAB.LONTILLANTAL).              
         GET NEXT tblq NO-LOCK.      
      END.
      /*berdskapstolkning klämdagar halvdagar genererar lart 260 = Fyllnadslön mot ledighet vid beredksp Lena 20190611*/      
      OPEN QUERY tbq FOR EACH TIDREGITAB WHERE
      TIDREGITAB.PERSONALKOD = PERSONALTAB.PERSONALKOD AND TIDREGITAB.VECKOKORD = "" AND  TIDREGITAB.DATUM LE hjdatum AND
      TIDREGITAB.BEREDSKAP = "260"  USE-INDEX PSTART NO-LOCK.   
      GET FIRST tbq NO-LOCK.
      DO WHILE AVAILABLE(TIDREGITAB):
         antmult = antmult +  klock100(TIDREGITAB.BERANTAL).               
         GET NEXT tbq NO-LOCK.      
      END.               
                                              
      acckompsenasttot  = klock60( acckompsenast + antmult - komputtag ).
      
      sok5 = acckompsenasttot.              
                    
   END.
END.         
ELSE IF sok0 = 52 THEN DO:
      
   sok5 = 0.
   FIND FIRST PERSONALTAB WHERE PERSONALTAB.PERSONALKOD = sok1 NO-LOCK NO-ERROR.
   IF PERSONALTAB.OMREGTID = 0 THEN DO:
      totarbkort = 0.
      FOR EACH TIDREGITAB WHERE TIDREGITAB.PERSONALKOD = PERSONALTAB.PERSONALKOD AND TIDREGITAB.AONR = "160" AND TIDREGITAB.DELNR = 0
      AND YEAR(TIDREGITAB.DATUM) = YEAR(TODAY) AND TIDREGITAB.TIDLOG = TRUE NO-LOCK:
         totarbkort = totarbkort + klock100(TIDREGITAB.TOTALT).
      END.               
      FOR EACH TIDREGITAB WHERE TIDREGITAB.PERSONALKOD = PERSONALTAB.PERSONALKOD AND TIDREGITAB.AONR = "161"
      AND YEAR(TIDREGITAB.DATUM) = YEAR(TODAY) AND TIDREGITAB.TIDLOG = TRUE NO-LOCK:
         totarbkort = totarbkort + klock100(TIDREGITAB.TOTALT).
      END.               
      totarbkort = klock60(totarbkort).
      RUN atkgrans_UI (OUTPUT foremaxarbkort ).          
      FIND FIRST EXTRADATA  WHERE EXTRADATA.HUVUDCH = PERSONALTAB.PERSONALKOD   AND EXTRADATA.PROGRAM = "AVAFOR"  NO-LOCK NO-ERROR.           
      IF AVAILABLE EXTRADATA THEN DO:            
         IF  EXTRADATA.SOKINT[1] > 0 THEN kvaratk = klock60(EXTRADATA.SOKINT[1] - klock100(totarbkort)).
         ELSE kvaratk = klock60(foremaxarbkort - klock100(ROUND(totarbkort,2))).
      END.   
      ELSE kvaratk = klock60(foremaxarbkort - klock100(ROUND(totarbkort,2))).
             
      sok5 = kvaratk.   
   END.
   ELSE IF sok0 = 53 THEN DO:   
      sok2 = 0.
      FIND FIRST FLEXTID WHERE FLEXTID.PERSONALKOD = sok1 AND FLEXTID.DATUM = DATE(sok4)  AND FLEXTID.KNAPP = "In"    NO-LOCK NO-ERROR.
      IF NOT AVAILABLE  FLEXTID THEN DO:
         FIND FIRST FLEXTID WHERE FLEXTID.PERSONALKOD = sok1 AND FLEXTID.DATUM = DATE(sok4)  AND FLEXTID.KNAPP = "Flex In"   NO-LOCK NO-ERROR.
         IF NOT AVAILABLE  FLEXTID THEN DO:
            FIND FIRST FLEXTID WHERE FLEXTID.PERSONALKOD = sok1 AND FLEXTID.DATUM = DATE(sok4)  AND FLEXTID.KNAPP = "Annat In"   NO-LOCK NO-ERROR.
            IF NOT AVAILABLE  FLEXTID THEN DO:
               sok2 = 1.
            END.
         END.                  
      END.           
   END.       
END.     

PROCEDURE atkgrans_UI :     
   DEFINE OUTPUT PARAMETER foremaxarbkort  AS INTEGER NO-UNDO.
   /*finns även i phmtapp.P*/
   FIND FIRST FORETAG  NO-LOCK NO-ERROR.
   IF FORETAG.FORETAG = "gkal" THEN foremaxarbkort = 63.
   ELSE IF FORETAG.FORETAG = "sund" THEN foremaxarbkort = 54.
   ELSE IF FORETAG.FORETAG = "misv" THEN foremaxarbkort = 27.
   ELSE IF FORETAG.FORETAG = "snat" THEN foremaxarbkort = 63.
   ELSE IF FORETAG.FORETAG = "LULE" THEN foremaxarbkort = 63.
   ELSE foremaxarbkort = 63.
      
END PROCEDURE.