/*FLNATTGAM.p*/ 
/*INNEVARANDE DAG*/
DEFINE NEW SHARED VARIABLE fnytid AS DECIMAL FORMAT "-99.99" NO-UNDO.
DEFINE NEW SHARED VARIABLE regvnr AS INTEGER FORMAT "999" NO-UNDO.     
DEFINE NEW SHARED VARIABLE regdatum AS DATE NO-UNDO.
DEFINE NEW SHARED VARIABLE nytid AS DECIMAL FORMAT "99.99" NO-UNDO.
DEFINE NEW SHARED VARIABLE sekunder AS INTEGER NO-UNDO.    
DEFINE NEW SHARED VARIABLE regstartsek AS INTEGER NO-UNDO.
DEFINE NEW SHARED VARIABLE regslutsek AS INTEGER NO-UNDO.
DEFINE NEW SHARED VARIABLE persrec AS RECID NO-UNDO.
DEFINE VARIABLE regtotalt LIKE TIDREGITAB.TOTALT NO-UNDO.
DEFINE VARIABLE frustarten AS DECIMAL NO-UNDO.
DEFINE VARIABLE fruslutet AS DECIMAL NO-UNDO.
DEFINE VARIABLE kaffestart AS DECIMAL NO-UNDO.
DEFINE VARIABLE kaffeslut AS DECIMAL NO-UNDO.
DEFINE VARIABLE lunchstarten AS DECIMAL NO-UNDO.
DEFINE VARIABLE lunchslutet AS DECIMAL NO-UNDO.
DEFINE VARIABLE minlu AS INTEGER NO-UNDO.    
DEFINE VARIABLE lusta AS INTEGER NO-UNDO.
DEFINE VARIABLE luslu AS INTEGER NO-UNDO.
DEFINE VARIABLE dagnr AS INTEGER NO-UNDO. 
DEFINE VARIABLE vschemat LIKE VECKOARBAV.VECKOSCHEMA NO-UNDO.  
DEFINE VARIABLE total AS INTEGER NO-UNDO. 
DEFINE VARIABLE plus AS INTEGER NO-UNDO. 
DEFINE VARIABLE flexrec AS RECID NO-UNDO. 
DEFINE VARIABLE fltid AS INTEGER NO-UNDO. 
DEFINE VARIABLE fldrec AS RECID NO-UNDO. 
DEFINE VARIABLE flexkvst LIKE TIDREGITAB.START NO-UNDO.  
DEFINE VARIABLE flrec AS RECID NO-UNDO.

DEFINE VARIABLE regstart LIKE TIDREGITAB.START NO-UNDO. 
DEFINE VARIABLE regslut LIKE TIDREGITAB.SLUT NO-UNDO.
 
DEFINE BUFFER flexbuff FOR FLEXTID.         
DEFINE QUERY persq FOR PERSONALTAB.   

FIND FIRST FORETAG NO-LOCK NO-ERROR.
IF AVAILABLE FORETAG THEN Guru.Konstanter:globforetag = FORETAG.FORETAG.
regdatum = TODAY - 1.
RUN REGVEC.P.
OPEN QUERY persq FOR EACH PERSONALTAB WHERE PERSONALTAB.AKTIV = TRUE 
USE-INDEX PERSONALKOD NO-LOCK.
GET FIRST persq NO-LOCK.
DO WHILE AVAILABLE(PERSONALTAB):                      
   DO TRANSACTION:                
      persrec = RECID(PERSONALTAB).
      RUN GAMKOLL.P.
   END.     
   GET NEXT persq NO-LOCK.
END.     
RUN EJKSALDO.P. 
