/*SLFLARBW.P  */ 
&Scoped-define NEW NEW
{GLOBVAR2DEL1.I}

DEFINE INPUT-OUTPUT PARAMETER pkod AS CHARACTER NO-UNDO.
DEFINE INPUT-OUTPUT PARAMETER regstart AS DECIMAL NO-UNDO. 
DEFINE INPUT-OUTPUT PARAMETER regslut AS DECIMAL NO-UNDO.
DEFINE INPUT-OUTPUT PARAMETER regvnr AS INTEGER FORMAT "999" NO-UNDO.
DEFINE INPUT-OUTPUT PARAMETER regdagnamn AS CHARACTER FORMAT "X(3)" NO-UNDO.        
DEFINE INPUT-OUTPUT PARAMETER regdatum AS DATE NO-UNDO.
DEFINE INPUT-OUTPUT PARAMETER regtotalt AS DECIMAL NO-UNDO.
DEFINE INPUT-OUTPUT PARAMETER frustarten AS DECIMAL NO-UNDO.
DEFINE INPUT-OUTPUT PARAMETER fruslutet AS DECIMAL NO-UNDO.
DEFINE INPUT-OUTPUT PARAMETER kaffestart AS DECIMAL NO-UNDO.
DEFINE INPUT-OUTPUT PARAMETER kaffeslut AS DECIMAL NO-UNDO.
DEFINE INPUT-OUTPUT PARAMETER lunchstarten AS DECIMAL NO-UNDO.
DEFINE INPUT-OUTPUT PARAMETER lunchslutet AS DECIMAL NO-UNDO.
DEFINE INPUT-OUTPUT PARAMETER nytid AS DECIMAL FORMAT "99.99" NO-UNDO.
DEFINE INPUT-OUTPUT PARAMETER sekunder AS INTEGER NO-UNDO.    

DEFINE VARIABLE dagnr AS INTEGER NO-UNDO. 
DEFINE VARIABLE vschemat LIKE VECKOARBAV.VECKOSCHEMA NO-UNDO.  
DEFINE VARIABLE arregvnr AS INTEGER NO-UNDO.
FIND FIRST FORETAG NO-LOCK NO-ERROR.
Guru.Konstanter:globforetag = FORETAG.FORETAG.
FIND PERSONALTAB WHERE PERSONALTAB.PERSONALKOD = pkod NO-LOCK NO-ERROR.
{ARBETSTIDER.I}

