/*TEJKSIS.P  UPPDATERAR FLEXSALDO MED EJ KORD FLEXTID TOM SISTA FOREGAENDE MANAD*/ 
DEFINE SHARED VARIABLE fnytid AS DECIMAL FORMAT "-99.99" NO-UNDO.
DEFINE SHARED VARIABLE nytid AS DECIMAL FORMAT "99.99" NO-UNDO.
DEFINE SHARED VARIABLE sekunder AS INTEGER NO-UNDO.    
DEFINE VARIABLE arrsum1 AS INTEGER NO-UNDO.  
DEFINE VARIABLE arrsum2 AS INTEGER NO-UNDO. 
DEFINE VARIABLE hjdat AS DATE NO-UNDO.
&Scoped-define NEW
{TIDPERS.I}
DEFINE TEMP-TABLE fldag
   FIELD PERSONALKOD AS CHARACTER
   FIELD SPLUS AS INTEGER
   FIELD STOTALT AS INTEGER
   FIELD MANAD AS INTEGER FORMAT "99"
   INDEX PKOD IS PRIMARY PERSONALKOD ASCENDING
   INDEX MANAD MANAD ASCENDING. 
DEFINE TEMP-TABLE flsum
   FIELD PERSONALKOD AS CHARACTER
   FIELD SPLUS AS INTEGER
   FIELD STOTALT AS INTEGER
   INDEX PKOD IS PRIMARY PERSONALKOD ASCENDING.    
DEFINE BUFFER flexbuff FOR FLEXTID.         
DEFINE QUERY persfq FOR PERSONALTAB.   
hjdat = DATE(MONTH(TODAY),01,YEAR(TODAY)).
OPEN QUERY flsal FOR EACH tidpers,
EACH FLEXDAG WHERE FLEXDAG.PERSONALKOD = tidpers.PERSONALKOD AND FLEXDAG.KORD = 01/01/97 AND
FLEXDAG.KONTROLL = "KONTROLL" AND FLEXDAG.DATUM < hjdat USE-INDEX KONTROLL NO-LOCK.
GET FIRST flsal NO-LOCK.
DO WHILE AVAILABLE(FLEXDAG):                     
   CREATE fldag.
   ASSIGN          
   fldag.PERSONALKOD = FLEXDAG.PERSONALKOD
   fldag.MANAD = MONTH(FLEXDAG.DATUM)
   nytid = FLEXDAG.PLUS.
   RUN TIMSEK.P.
   ASSIGN
   fldag.SPLUS = sekunder
   nytid = FLEXDAG.OVUTPLUS.
   RUN TIMSEK.P.
   ASSIGN
   fldag.SPLUS = fldag.SPLUS + sekunder
   nytid = FLEXDAG.FLARB.
   RUN TIMSEK.P.
   ASSIGN
   fldag.SPLUS = fldag.SPLUS + sekunder
   nytid = FLEXDAG.TOTALT.
   RUN TIMSEK.P.
   ASSIGN
   fldag.STOTALT = sekunder. 
   GET NEXT flsal NO-LOCK. 
END.   
CLOSE QUERY flsal.        
ASSIGN
arrsum1 = 0
arrsum2  = 0.
FOR EACH fldag  BREAK BY fldag.PERSONALKOD:    
   ACCUMULATE fldag.SPLUS(TOTAL BY fldag.PERSONALKOD).   
   ACCUMULATE fldag.STOTALT(TOTAL  BY fldag.PERSONALKOD).       
   IF LAST-OF(fldag.PERSONALKOD) THEN DO:
      CREATE flsum.                    
      ASSIGN          
      flsum.PERSONALKOD = fldag.PERSONALKOD                                                
      flsum.SPLUS = (ACCUM TOTAL fldag.SPLUS) - arrsum1                  
      arrsum1 = ACCUM TOTAL fldag.SPLUS    
      flsum.STOTALT = (ACCUM TOTAL fldag.STOTALT) - arrsum2                  
      arrsum2 = ACCUM TOTAL fldag.STOTALT.                                        
   END.
END.     
FOR EACH flsum:
   DO TRANSACTION:
      FIND FIRST FLEXSALDO WHERE FLEXSALDO.PERSONALKOD = flsum.PERSONALKOD
      USE-INDEX PKOD EXCLUSIVE-LOCK NO-ERROR. 
      IF NOT AVAILABLE FLEXSALDO THEN DO:
         CREATE FLEXSALDO.
         ASSIGN  FLEXSALDO.PERSONALKOD = flsum.PERSONALKOD.
      END.
      sekunder = flsum.SPLUS.
      RUN FSEKTIM.P.
      ASSIGN FLEXSALDO.EJKFLSISTA = fnytid.   
   END.   
END.   


