 /*KONTVAL2APP.P*/
&Scoped-define NEW NEW
&Scoped-define SHARED SHARED
{GLOBVAR2DEL1.I}
{REGVAR.I}

{AVTPLANTEMP.I}

DEFINE NEW SHARED TEMP-TABLE kontkod   
   FIELD KONTO LIKE KONTO.KONTO
   FIELD KONTONR LIKE KONTO.KONTONR 
   FIELD BENAMNING LIKE KONTO.BENAMNING
   INDEX KNR IS PRIMARY KONTONR ASCENDING. 

DEFINE NEW SHARED TEMP-TABLE orgkod   
   FIELD KONTO AS CHARACTER 
   FIELD KONTONR AS CHARACTER 
   FIELD BENAMNING AS CHARACTER 
   INDEX KNR IS PRIMARY KONTONR ASCENDING.

DEFINE INPUT PARAMETER kto AS CHARACTER NO-UNDO.
DEFINE OUTPUT PARAMETER TABLE FOR kontkod.
DEFINE OUTPUT PARAMETER TABLE FOR orgkod.
DEFINE QUERY kontq FOR KONTO. 

kto = "K1". 
EMPTY TEMP-TABLE orgkod NO-ERROR. 
OPEN QUERY kontq FOR EACH KONTO WHERE KONTO.KONTO = kto USE-INDEX KONTO NO-LOCK.  
GET FIRST kontq NO-LOCK.   
DO WHILE AVAILABLE(KONTO):      
  CREATE orgkod.   
  ASSIGN
  orgkod.KONTO = kto
  orgkod.KONTONR = KONTO.KONTONR
  orgkod.BENAMNING = KONTO.BENAMNING.         
  GET NEXT kontq NO-LOCK.      
END.
CLOSE QUERY kontq.                     
   
kto = "K2".
EMPTY TEMP-TABLE kontkod NO-ERROR. 
OPEN QUERY kontq FOR EACH KONTO WHERE KONTO.KONTO = kto USE-INDEX KONTO NO-LOCK.  
GET FIRST kontq NO-LOCK.   
DO WHILE AVAILABLE(KONTO):      
  CREATE kontkod.   
  ASSIGN
  kontkod.KONTO = kto
  kontkod.KONTONR = KONTO.KONTONR
  kontkod.BENAMNING = KONTO.BENAMNING.         
  GET NEXT kontq NO-LOCK.      
END.
CLOSE QUERY kontq. 
