/*PANSBER.P*/

&Scoped-define NEW NEW
&Scoped-define SHARED SHARED
{ANSVPLANTEMP.I}
DEFINE OUTPUT PARAMETER TABLE FOR ansvplantemp. 
FIND FIRST FORETAG USE-INDEX FORETAG NO-LOCK NO-ERROR.
Guru.Konstanter:globforetag = FORETAG.FORETAG.
/*TIDFORE*/

IF Guru.Konstanter:globforetag = "GRAN" OR Guru.Konstanter:globforetag = "SUND" OR Guru.Konstanter:globforetag = "SNAT" OR Guru.Konstanter:globforetag = "ELPA" OR Guru.Konstanter:globforetag = "GKAL" THEN DO:
   OPEN QUERY BRW_ARBAN FOR EACH ANSVAONR NO-LOCK, 
   EACH PERSONALTAB WHERE PERSONALTAB.PERSONALKOD = ANSVAONR.PERSONALKOD AND 
   PERSONALTAB.AKTIV = TRUE NO-LOCK.
END.
ELSE DO:   
   OPEN QUERY BRW_ARBAN FOR EACH ANSVAONR NO-LOCK, 
   EACH PERSONALTAB WHERE PERSONALTAB.PERSONALKOD = ANSVAONR.PERSONALKOD 
   NO-LOCK.    
END.

GET FIRST BRW_ARBAN NO-LOCK.
DO WHILE AVAILABLE(ANSVAONR):
   CREATE ansvplantemp.
   ASSIGN 
   ansvplantemp.NAMN = PERSONALTAB.EFTERNAMN + " " + PERSONALTAB.FORNAMN 
   ansvplantemp.EFTERNAMN = PERSONALTAB.EFTERNAMN 
   ansvplantemp.FORNAMN = PERSONALTAB.FORNAMN      
   ansvplantemp.PERSONALKOD  = ANSVAONR.PERSONALKOD.
   Guru.GlobalaVariabler:GDPRvem = Guru.GlobalaVariabler:GDPRvem + "," + PERSONALTAB.PERSONALKOD.
   GET NEXT BRW_ARBAN NO-LOCK.
END.

{GDPRLOGGCLIENT.I}

