/*PLANAOHMT.P*/ 
&Scoped-define NEW NEW
&Scoped-define SHARED SHARED
{GLOBVAR2DEL1.I}
{REGVAR.I}

{AVTPLANTEMP.I}
/* {AONRTEMP.I} */
{AONRDEF.I}
      
DEFINE INPUT PARAMETER vartvar AS INTEGER NO-UNDO.
DEFINE INPUT PARAMETER omrvar AS CHARACTER NO-UNDO.
DEFINE OUTPUT PARAMETER TABLE FOR aonrtemp. 

IF vartvar = 1 THEN DO:
   EMPTY TEMP-TABLE aonrtemp NO-ERROR.    
   OPEN QUERY ao FOR EACH AONRTAB WHERE AONRTAB.OMRADE = omrvar AND
   AONRTAB.PLANNR = ? OR AONRTAB.PLANNR = ""
      USE-INDEX OMRADE EXCLUSIVE-LOCK.
   GET FIRST ao NO-LOCK.
   DO WHILE AVAILABLE(AONRTAB):
      CREATE aonrtemp.
      BUFFER-COPY AONRTAB TO aonrtemp.
      GET NEXT ao NO-LOCK.
   END.
   CLOSE QUERY ao.
END.


