/*PURVALAPP.P*/
&Scoped-define NEW NEW
&Scoped-define SHARED SHARED
{GLOBVAR2DEL1.I}
{REGVAR.I}

{ANSVPLANTEMP.I}
{AUTOMREGTEMP.I}

DEFINE OUTPUT PARAMETER TABLE FOR ansvplantemp.
DEFINE OUTPUT PARAMETER TABLE FOR automregtemp.

/*Ladda*/ 
EMPTY TEMP-TABLE automregtemp NO-ERROR. 
OPEN QUERY auq FOR EACH AUTOMREG USE-INDEX PRISTYPER NO-LOCK.
GET FIRST auq NO-LOCK.
DO WHILE AVAILABLE(AUTOMREG):
  CREATE automregtemp.
  BUFFER-COPY AUTOMREG TO automregtemp.
  GET NEXT auq NO-LOCK.         
END.
CLOSE QUERY auq.
EMPTY TEMP-TABLE ansvplantemp NO-ERROR. 
OPEN QUERY ansq FOR EACH ANSVAONR NO-LOCK,
EACH PERSONALTAB WHERE PERSONALTAB.PERSONALKOD = ANSVAONR.PERSONALKOD NO-LOCK.
GET FIRST ansq NO-LOCK.
DO WHILE AVAILABLE(ANSVAONR):
  CREATE ansvplantemp.
  ASSIGN 
  ansvplantemp.NAMN = PERSONALTAB.EFTERNAMN + " " + PERSONALTAB.FORNAMN
  ansvplantemp.FORNAMN = PERSONALTAB.FORNAMN 
  ansvplantemp.EFTERNAMN = PERSONALTAB.EFTERNAMN 
  ansvplantemp.PERSONALKOD = ANSVAONR.PERSONALKOD.
  Guru.GlobalaVariabler:GDPRvem = Guru.GlobalaVariabler:GDPRvem + "," + PERSONALTAB.PERSONALKOD. 
  GET NEXT ansq NO-LOCK.
END.
CLOSE QUERY ansq.

   {GDPRLOGGCLIENT.I}
RETURN. 

