/*SPROJAPP.P*/
DEFINE TEMP-TABLE kalaonr
   FIELD AONR LIKE AONRTAB.AONR
   FIELD DELNR LIKE AONRTAB.DELNR
   FIELD OMRADE LIKE AONRTAB.OMRADE
   FIELD ORT LIKE AONRTAB.ORT
   FIELD FASTKALK LIKE AONRTAB.FASTKALK
   FIELD KALKNR LIKE AONRTAB.KALKNR
   FIELD ARBANSVARIG LIKE AONRTAB.ARBANSVARIG
   FIELD FASTAAONR LIKE AONRTAB.FASTAAONR
   INDEX AONR AONR DELNR FASTAAONR ASCENDING
   INDEX ARB ARBANSVARIG AONR DELNR FASTAAONR ASCENDING
   INDEX OMR OMRADE AONR DELNR FASTAAONR ASCENDING.   
   
DEFINE OUTPUT PARAMETER TABLE FOR kalaonr.   
   
   OPEN QUERY aoq FOR EACH AONRTAB WHERE AONRTAB.AONRAVDATUM = 01/01/1991 AND
   AONRTAB.FASTKALK = TRUE /*OR AONRTAB.KALKNR NE ?)*/ NO-LOCK.
   GET FIRST aoq NO-LOCK.
   DO WHILE AVAILABLE(AONRTAB):
      FIND FIRST KALENDER WHERE KALENDER.AONR = AONRTAB.AONR AND
      KALENDER.DELNR = AONRTAB.DELNR USE-INDEX AONR NO-LOCK NO-ERROR.
      IF NOT AVAILABLE KALENDER THEN DO:
         RUN skapa_UI.
      END.
      GET NEXT aoq NO-LOCK.
   END.      
   CLOSE QUERY aoq.
   /*
   OPEN QUERY succq FOR EACH SUCCAONR WHERE SUCCAONR.EA > 0 
   USE-INDEX AONR NO-LOCK.
   GET FIRST succq NO-LOCK.
   DO WHILE AVAILABLE(SUCCAONR):
      FIND FIRST KALENDER WHERE KALENDER.AONR = SUCCAONR.AONR AND
      KALENDER.DELNR = SUCCAONR.DELNR USE-INDEX AONR NO-LOCK NO-ERROR.
      IF NOT AVAILABLE KALENDER THEN DO:
         FIND FIRST kalaonr WHERE kalaonr.AONR = SUCCAONR.AONR AND
         kalaonr.DELNR = SUCCAONR.DELNR USE-INDEX AONR NO-LOCK NO-ERROR.
         IF NOT AVAILABLE kalaonr THEN DO:
            FIND FIRST AONRTAB WHERE AONRTAB.AONR = SUCCAONR.AONR AND
            AONRTAB.DELNR = SUCCAONR.DELNR USE-INDEX AONR NO-LOCK NO-ERROR.
            IF AVAILABLE AONRTAB THEN DO:
               IF AONRTAB.AONRAVDATUM = 01/01/1991 THEN
               RUN skapa_UI.
            END.   
         END.
      END.
      GET NEXT succq NO-LOCK.
   END.
   CLOSE QUERY succq.
   */
   
PROCEDURE skapa_UI.
   CREATE kalaonr.  
   ASSIGN
   kalaonr.AONR = AONRTAB.AONR
   kalaonr.DELNR = AONRTAB.DELNR
   kalaonr.OMRADE = AONRTAB.OMRADE
   kalaonr.ORT = AONRTAB.ORT
   kalaonr.ARBANSVARIG = AONRTAB.ARBANSVARIG
   kalaonr.FASTKALK = AONRTAB.FASTKALK    
   kalaonr.KALKNR = AONRTAB.KALKNR
   kalaonr.FASTAAONR = AONRTAB.FASTAAONR.
END PROCEDURE.
