DEFINE VARIABLE Field1 AS CHARACTER INITIAL "Hello".
DEFINE VARIABLE Field2 AS CHARACTER INITIAL "PROGRESS".
DEFINE VARIABLE Field3 AS CHARACTER INITIAL "World!".

DISPLAY SKIP(3) Field1 SKIP(2) Field2 SKIP(2) Field3 
	WITH SIDE-LABELS NO-BOX CENTERED THREE-D.
	
ENABLE Field1 Field2 Field3.

ON ENTRY OF Field3
DO:
	MESSAGE "Press RETURN in Field3 to exit the procedure.".
END.

WAIT-FOR RETURN OF Field3.



