DEFINE RECTANGLE Rect1 SIZE-CHARS 12 BY 8 NO-FILL EDGE-CHARS 2.
DEFINE BUTTON btn-Exit LABEL "Exit".
DEFINE BUTTON btn-Rect LABEL "Display Rectangle".

ENABLE SKIP(1) btn-Rect SKIP(1) btn-Exit SKIP(1)
    WITH SIDE-LABELS NO-BOX THREE-D.

ON CHOOSE of btn-Rect
DO:
    DISPLAY Rect1 WITH NO-BOX THREE-D.
END.

WAIT-FOR CHOOSE OF btn-Exit.



