DEFINE INPUT PARAMETER Paris AS CHARACTER FORMAT "x(20)".
DEFINE BUTTON btn-Exit LABEL "Exit".

DEFINE FRAME Frame1 
    SKIP(1)
    Paris SKIP(1)
    btn-Exit
        WITH SIDE-LABELS NO-BOX CENTERED THREE-D.
        
DISPLAY paris WITH FRAME Frame1.
ENABLE ALL WITH FRAME Frame1.
WAIT-FOR CHOOSE OF btn-Exit.

