/*NewGuruStart.p
RUN GURUSTART\NEWGURUSTART.P.
*/

DEFINE INPUT PARAMETER cmdline AS CHARACTER INITIAL FALSE NO-UNDO.

DEFINE NEW SHARED VARIABLE appcon  AS LOGICAL NO-UNDO.
DEFINE NEW SHARED VARIABLE apphand AS HANDLE  NO-UNDO.

DEFINE            VARIABLE musz    AS LOGICAL NO-UNDO.



SESSION:DEBUG-ALERT = YES.
RUN modules/global/startclass.p.
RUN modules/global/startloginclass.p (INPUT 2, OUTPUT musz).
IF musz = TRUE THEN QUIT.
DEFINE VARIABLE r AS Guru.Root NO-UNDO.
r = NEW Guru.Root().
/*kalyl spec*/
DEFINE VARIABLE kalknr AS INTEGER   NO-UNDO.
DEFINE VARIABLE omrvar AS CHARACTER NO-UNDO.
/*921371,"0910"*/
r:CustomInit(cmdline).
DELETE OBJECT r NO-ERROR.
