/*GrundKalkBerSch.p */
{KalkylimportTT.I}
DEFINE TEMP-TABLE sumhdschtprot NO-UNDO LIKE HDSCHAKTPROT.
DEFINE INPUT PARAMETER BernrVar AS INTEGER NO-UNDO.
DEFINE INPUT PARAMETER valomrade AS CHARACTER NO-UNDO.
DEFINE INPUT PARAMETER valnum AS INTEGER NO-UNDO.
DEFINE INPUT PARAMETER valsid AS INTEGER NO-UNDO.
DEFINE OUTPUT PARAMETER TABLE FOR KalkylimportTT.
DEFINE VARIABLE forsta AS LOGICAL NO-UNDO.
EMPTY TEMP-TABLE KalkylimportTT NO-ERROR. 
FUNCTION Antalkalkyl RETURNS DECIMAL
  ( INPUT ordvar AS INTEGER ) FORWARD.
IF valnum > 0 THEN DO:
   forsta = TRUE.
   FOR EACH BERVAL WHERE BERVAL.AONR = STRING(BernrVar) AND BERVAL.OMRADE = valomrade AND BERVAL.NUM = valnum AND BERVAL.NUM = valnum NO-LOCK  :
      RUN valkalk_UI.
   END.
END. 

IF valsid > 0 THEN DO:
   FOR EACH HDSCHAKT WHERE HDSCHAKT.BERNR = BernrVar AND HDSCHAKT.OMRADE = valomrade AND HDSCHAKT.SID = valsid NO-LOCK: 
      RUN hdvalkal_UI.
   END.
END.
PROCEDURE hdvalkal_UI :       
   FOR EACH HDSCHAKTPROT WHERE HDSCHAKTPROT.BERNR = BernrVar AND 
   HDSCHAKTPROT.OMRADE = valomrade AND HDSCHAKTPROT.SID = HDSCHAKT.SID NO-LOCK BREAK BY HDSCHAKTPROT.SID :
      ACCUMULATE HDSCHAKTPROT.DEC1 (TOTAL BY HDSCHAKTPROT.SID). 
      ACCUMULATE HDSCHAKTPROT.DEC2 (TOTAL BY HDSCHAKTPROT.SID). 
      ACCUMULATE HDSCHAKTPROT.DEC3 (TOTAL BY HDSCHAKTPROT.SID). 
      ACCUMULATE HDSCHAKTPROT.DEC4 (TOTAL BY HDSCHAKTPROT.SID). 
      ACCUMULATE HDSCHAKTPROT.DEC5 (TOTAL BY HDSCHAKTPROT.SID). 
      ACCUMULATE HDSCHAKTPROT.DEC6 (TOTAL BY HDSCHAKTPROT.SID). 
      ACCUMULATE HDSCHAKTPROT.DEC7 (TOTAL BY HDSCHAKTPROT.SID). 
      ACCUMULATE HDSCHAKTPROT.DEC8 (TOTAL BY HDSCHAKTPROT.SID). 
      ACCUMULATE HDSCHAKTPROT.DEC9 (TOTAL BY HDSCHAKTPROT.SID). 
      ACCUMULATE HDSCHAKTPROT.DEC10 (TOTAL BY HDSCHAKTPROT.SID). 
      ACCUMULATE HDSCHAKTPROT.DEC11 (TOTAL BY HDSCHAKTPROT.SID). 
      ACCUMULATE HDSCHAKTPROT.DEC12 (TOTAL BY HDSCHAKTPROT.SID). 
      ACCUMULATE HDSCHAKTPROT.DEC13 (TOTAL BY HDSCHAKTPROT.SID). 
      ACCUMULATE HDSCHAKTPROT.DEC14 (TOTAL BY HDSCHAKTPROT.SID). 
      ACCUMULATE HDSCHAKTPROT.DEC15 (TOTAL BY HDSCHAKTPROT.SID). 
      ACCUMULATE HDSCHAKTPROT.DEC16 (TOTAL BY HDSCHAKTPROT.SID). 
      ACCUMULATE HDSCHAKTPROT.DEC17 (TOTAL BY HDSCHAKTPROT.SID). 
      ACCUMULATE HDSCHAKTPROT.DEC18 (TOTAL BY HDSCHAKTPROT.SID). 
      ACCUMULATE HDSCHAKTPROT.DEC19 (TOTAL BY HDSCHAKTPROT.SID).
      ACCUMULATE HDSCHAKTPROT.DEC20 (TOTAL BY HDSCHAKTPROT.SID). 
      ACCUMULATE HDSCHAKTPROT.DEC21 (TOTAL BY HDSCHAKTPROT.SID). 
      ACCUMULATE HDSCHAKTPROT.DEC22 (TOTAL BY HDSCHAKTPROT.SID). 
      ACCUMULATE HDSCHAKTPROT.DEC23 (TOTAL BY HDSCHAKTPROT.SID). 
      ACCUMULATE HDSCHAKTPROT.DEC24 (TOTAL BY HDSCHAKTPROT.SID). 
      ACCUMULATE HDSCHAKTPROT.DEC25 (TOTAL BY HDSCHAKTPROT.SID). 
      ACCUMULATE HDSCHAKTPROT.DEC26 (TOTAL BY HDSCHAKTPROT.SID). 
      ACCUMULATE HDSCHAKTPROT.DEC27 (TOTAL BY HDSCHAKTPROT.SID). 
      ACCUMULATE HDSCHAKTPROT.DEC28 (TOTAL BY HDSCHAKTPROT.SID). 
      ACCUMULATE HDSCHAKTPROT.DEC29 (TOTAL BY HDSCHAKTPROT.SID). 
      ACCUMULATE HDSCHAKTPROT.DEC30 (TOTAL BY HDSCHAKTPROT.SID). 
      ACCUMULATE HDSCHAKTPROT.DEC31 (TOTAL BY HDSCHAKTPROT.SID). 
      ACCUMULATE HDSCHAKTPROT.DEC32 (TOTAL BY HDSCHAKTPROT.SID). 
      ACCUMULATE HDSCHAKTPROT.DEC33 (TOTAL BY HDSCHAKTPROT.SID). 
      ACCUMULATE HDSCHAKTPROT.DEC34 (TOTAL BY HDSCHAKTPROT.SID). 
      ACCUMULATE HDSCHAKTPROT.DEC35 (TOTAL BY HDSCHAKTPROT.SID). 
      ACCUMULATE HDSCHAKTPROT.DEC36 (TOTAL BY HDSCHAKTPROT.SID). 
      ACCUMULATE HDSCHAKTPROT.DEC37 (TOTAL BY HDSCHAKTPROT.SID). 
      ACCUMULATE HDSCHAKTPROT.DEC38 (TOTAL BY HDSCHAKTPROT.SID). 
      ACCUMULATE HDSCHAKTPROT.DEC39 (TOTAL BY HDSCHAKTPROT.SID).
      ACCUMULATE HDSCHAKTPROT.DEC40 (TOTAL BY HDSCHAKTPROT.SID). 
      IF LAST-OF(HDSCHAKTPROT.SID) THEN DO:
         CREATE sumhdschtprot.      
         BUFFER-COPY HDSCHAKTPROT TO sumhdschtprot.       
         sumhdschtprot.DEC1 = (ACCUM TOTAL BY HDSCHAKTPROT.SID HDSCHAKTPROT.DEC1 ). 
         sumhdschtprot.DEC2 = (ACCUM TOTAL BY HDSCHAKTPROT.SID HDSCHAKTPROT.DEC2 ). 
         sumhdschtprot.DEC3 = (ACCUM TOTAL BY HDSCHAKTPROT.SID HDSCHAKTPROT.DEC3 ). 
         sumhdschtprot.DEC4 = (ACCUM TOTAL BY HDSCHAKTPROT.SID HDSCHAKTPROT.DEC4 ). 
         sumhdschtprot.DEC5 = (ACCUM TOTAL BY HDSCHAKTPROT.SID HDSCHAKTPROT.DEC5 ). 
         sumhdschtprot.DEC6 = (ACCUM TOTAL BY HDSCHAKTPROT.SID HDSCHAKTPROT.DEC6 ). 
         sumhdschtprot.DEC7 = (ACCUM TOTAL BY HDSCHAKTPROT.SID HDSCHAKTPROT.DEC7 ). 
         sumhdschtprot.DEC8 = (ACCUM TOTAL BY HDSCHAKTPROT.SID HDSCHAKTPROT.DEC8 ). 
         sumhdschtprot.DEC9 = (ACCUM TOTAL BY HDSCHAKTPROT.SID HDSCHAKTPROT.DEC9 ). 
         sumhdschtprot.DEC10 = (ACCUM TOTAL BY HDSCHAKTPROT.SID HDSCHAKTPROT.DEC10). 
         sumhdschtprot.DEC11 = (ACCUM TOTAL BY HDSCHAKTPROT.SID HDSCHAKTPROT.DEC11). 
         sumhdschtprot.DEC12 = (ACCUM TOTAL BY HDSCHAKTPROT.SID HDSCHAKTPROT.DEC12). 
         sumhdschtprot.DEC13 = (ACCUM TOTAL BY HDSCHAKTPROT.SID HDSCHAKTPROT.DEC13). 
         sumhdschtprot.DEC14 = (ACCUM TOTAL BY HDSCHAKTPROT.SID HDSCHAKTPROT.DEC14). 
         sumhdschtprot.DEC15 = (ACCUM TOTAL BY HDSCHAKTPROT.SID HDSCHAKTPROT.DEC15). 
         sumhdschtprot.DEC16 = (ACCUM TOTAL BY HDSCHAKTPROT.SID HDSCHAKTPROT.DEC16). 
         sumhdschtprot.DEC17 = (ACCUM TOTAL BY HDSCHAKTPROT.SID HDSCHAKTPROT.DEC17). 
         sumhdschtprot.DEC18 = (ACCUM TOTAL BY HDSCHAKTPROT.SID HDSCHAKTPROT.DEC18). 
         sumhdschtprot.DEC19 = (ACCUM TOTAL BY HDSCHAKTPROT.SID HDSCHAKTPROT.DEC19).
         sumhdschtprot.DEC20 = (ACCUM TOTAL BY HDSCHAKTPROT.SID HDSCHAKTPROT.DEC20). 
         sumhdschtprot.DEC21 = (ACCUM TOTAL BY HDSCHAKTPROT.SID HDSCHAKTPROT.DEC21). 
         sumhdschtprot.DEC22 = (ACCUM TOTAL BY HDSCHAKTPROT.SID HDSCHAKTPROT.DEC22). 
         sumhdschtprot.DEC23 = (ACCUM TOTAL BY HDSCHAKTPROT.SID HDSCHAKTPROT.DEC23). 
         sumhdschtprot.DEC24 = (ACCUM TOTAL BY HDSCHAKTPROT.SID HDSCHAKTPROT.DEC24). 
         sumhdschtprot.DEC25 = (ACCUM TOTAL BY HDSCHAKTPROT.SID HDSCHAKTPROT.DEC25). 
         sumhdschtprot.DEC26 = (ACCUM TOTAL BY HDSCHAKTPROT.SID HDSCHAKTPROT.DEC26). 
         sumhdschtprot.DEC27 = (ACCUM TOTAL BY HDSCHAKTPROT.SID HDSCHAKTPROT.DEC27). 
         sumhdschtprot.DEC28 = (ACCUM TOTAL BY HDSCHAKTPROT.SID HDSCHAKTPROT.DEC28). 
         sumhdschtprot.DEC29 = (ACCUM TOTAL BY HDSCHAKTPROT.SID HDSCHAKTPROT.DEC29). 
         sumhdschtprot.DEC30 = (ACCUM TOTAL BY HDSCHAKTPROT.SID HDSCHAKTPROT.DEC30). 
         sumhdschtprot.DEC31 = (ACCUM TOTAL BY HDSCHAKTPROT.SID HDSCHAKTPROT.DEC31). 
         sumhdschtprot.DEC32 = (ACCUM TOTAL BY HDSCHAKTPROT.SID HDSCHAKTPROT.DEC32). 
         sumhdschtprot.DEC33 = (ACCUM TOTAL BY HDSCHAKTPROT.SID HDSCHAKTPROT.DEC33). 
         sumhdschtprot.DEC34 = (ACCUM TOTAL BY HDSCHAKTPROT.SID HDSCHAKTPROT.DEC34). 
         sumhdschtprot.DEC35 = (ACCUM TOTAL BY HDSCHAKTPROT.SID HDSCHAKTPROT.DEC35). 
         sumhdschtprot.DEC36 = (ACCUM TOTAL BY HDSCHAKTPROT.SID HDSCHAKTPROT.DEC36). 
         sumhdschtprot.DEC37 = (ACCUM TOTAL BY HDSCHAKTPROT.SID HDSCHAKTPROT.DEC37). 
         sumhdschtprot.DEC38 = (ACCUM TOTAL BY HDSCHAKTPROT.SID HDSCHAKTPROT.DEC38). 
         sumhdschtprot.DEC39 = (ACCUM TOTAL BY HDSCHAKTPROT.SID HDSCHAKTPROT.DEC39).
         sumhdschtprot.DEC40 = (ACCUM TOTAL BY HDSCHAKTPROT.SID HDSCHAKTPROT.DEC40).
      END.     
   END.
   FOR EACH sumhdschtprot:
      IF sumhdschtprot.DEC1 NE 0 THEN RUN hdkopp_UI (INPUT 1).
      IF sumhdschtprot.DEC2 NE 0 THEN RUN hdkopp_UI (INPUT 2).
      IF sumhdschtprot.DEC3 NE 0 THEN RUN hdkopp_UI (INPUT 3).
      IF sumhdschtprot.DEC4 NE 0 THEN RUN hdkopp_UI (INPUT 4).
      IF sumhdschtprot.DEC5 NE 0 THEN RUN hdkopp_UI (INPUT 5).
      IF sumhdschtprot.DEC6 NE 0 THEN RUN hdkopp_UI (INPUT 6).
      IF sumhdschtprot.DEC7 NE 0 THEN RUN hdkopp_UI (INPUT 7).
      IF sumhdschtprot.DEC8 NE 0 THEN RUN hdkopp_UI (INPUT 8).
      IF sumhdschtprot.DEC9 NE 0 THEN RUN hdkopp_UI (INPUT 9).
      IF sumhdschtprot.DEC10 NE 0 THEN RUN hdkopp_UI (INPUT 10). 
      IF sumhdschtprot.DEC11 NE 0 THEN RUN hdkopp_UI (INPUT 11). 
      IF sumhdschtprot.DEC12 NE 0 THEN RUN hdkopp_UI (INPUT 12). 
      IF sumhdschtprot.DEC13 NE 0 THEN RUN hdkopp_UI (INPUT 13). 
      IF sumhdschtprot.DEC14 NE 0 THEN RUN hdkopp_UI (INPUT 14). 
      IF sumhdschtprot.DEC15 NE 0 THEN RUN hdkopp_UI (INPUT 15). 
      IF sumhdschtprot.DEC16 NE 0 THEN RUN hdkopp_UI (INPUT 16). 
      IF sumhdschtprot.DEC17 NE 0 THEN RUN hdkopp_UI (INPUT 17). 
      IF sumhdschtprot.DEC18 NE 0 THEN RUN hdkopp_UI (INPUT 18). 
      IF sumhdschtprot.DEC19 NE 0 THEN RUN hdkopp_UI (INPUT 19). 
      IF sumhdschtprot.DEC20 NE 0 THEN RUN hdkopp_UI (INPUT 20). 
      IF sumhdschtprot.DEC21 NE 0 THEN RUN hdkopp_UI (INPUT 21). 
      IF sumhdschtprot.DEC22 NE 0 THEN RUN hdkopp_UI (INPUT 22). 
      IF sumhdschtprot.DEC23 NE 0 THEN RUN hdkopp_UI (INPUT 23). 
      IF sumhdschtprot.DEC24 NE 0 THEN RUN hdkopp_UI (INPUT 24). 
      IF sumhdschtprot.DEC25 NE 0 THEN RUN hdkopp_UI (INPUT 25). 
      IF sumhdschtprot.DEC26 NE 0 THEN RUN hdkopp_UI (INPUT 26). 
      IF sumhdschtprot.DEC27 NE 0 THEN RUN hdkopp_UI (INPUT 27). 
      IF sumhdschtprot.DEC28 NE 0 THEN RUN hdkopp_UI (INPUT 28). 
      IF sumhdschtprot.DEC29 NE 0 THEN RUN hdkopp_UI (INPUT 29). 
      IF sumhdschtprot.DEC30 NE 0 THEN RUN hdkopp_UI (INPUT 30). 
      IF sumhdschtprot.DEC31 NE 0 THEN RUN hdkopp_UI (INPUT 31). 
      IF sumhdschtprot.DEC32 NE 0 THEN RUN hdkopp_UI (INPUT 32). 
      IF sumhdschtprot.DEC33 NE 0 THEN RUN hdkopp_UI (INPUT 33). 
      IF sumhdschtprot.DEC34 NE 0 THEN RUN hdkopp_UI (INPUT 34). 
      IF sumhdschtprot.DEC35 NE 0 THEN RUN hdkopp_UI (INPUT 35). 
      IF sumhdschtprot.DEC36 NE 0 THEN RUN hdkopp_UI (INPUT 36). 
      IF sumhdschtprot.DEC37 NE 0 THEN RUN hdkopp_UI (INPUT 37). 
      IF sumhdschtprot.DEC38 NE 0 THEN RUN hdkopp_UI (INPUT 38). 
      IF sumhdschtprot.DEC39 NE 0 THEN RUN hdkopp_UI (INPUT 39). 
      IF sumhdschtprot.DEC40 NE 0 THEN RUN hdkopp_UI (INPUT 40). 
   END. 
   
END PROCEDURE.

PROCEDURE hdkopp_UI :
   DEFINE INPUT PARAMETER ovar AS INTEGER NO-UNDO.
   FIND FIRST HDPROTKOPPBER WHERE HDPROTKOPPBER.BERNR = sumhdschtprot.BERNR AND 
   HDPROTKOPPBER.OMRADE = sumhdschtprot.OMRADE AND 
   HDPROTKOPPBER.ORDNING = ovar AND HDPROTKOPPBER.SID = sumhdschtprot.SID NO-LOCK.
   FOR EACH HDKKOPP WHERE HDKKOPP.ID = HDPROTKOPPBER.ID AND HDKKOPP.TYP = HDPROTKOPPBER.TYP NO-LOCK:
      CREATE KalkylimportTT.
      ASSIGN
      KalkylimportTT.TTRECID = RECID(KalkylimportTT) 
      KalkylimportTT.MATRIS = 1
      KalkylimportTT.ARBKOD = HDKKOPP.ARBKOD 
      KalkylimportTT.LOPNR = HDKKOPP.LOPNR
      KalkylimportTT.SID = HDPROTKOPPBER.SID. 
      KalkylimportTT.ANTAL     = 1 * Antalkalkyl(ovar).
      IF HDKKOPP.TYP = "F" THEN DO:
         KalkylimportTT.ANTAL     =  HDKKOPP.ANTAL * Antalkalkyl(ovar).     
      END. 
      IF HDKKOPP.TYP = "PH" THEN DO:
         IF KalkylimportTT.ANTAL NE 0 THEN DO:
            KalkylimportTT.ANTAL =  KalkylimportTT.ANTAL * HDKKOPP.ANTAL.
         END.
      END.  
      FIND LAST KALKYLLOPPOSTER WHERE KALKYLLOPPOSTER.ARBKOD = KalkylimportTT.ARBKOD AND KALKYLLOPPOSTER.LOPNR = KalkylimportTT.LOPNR USE-INDEX LOPNR NO-LOCK NO-ERROR.
      IF AVAILABLE KALKYLLOPPOSTER THEN DO:
         IF KALKYLLOPPOSTER.ENHET = "KM" THEN KalkylimportTT.ANTAL = KalkylimportTT.ANTAL / 1000.
      END.
   END.  
             
END PROCEDURE.  

PROCEDURE HdKoppImport_UI :
   
   DEFINE INPUT PARAMETER ovar AS INTEGER NO-UNDO.
   FOR EACH HDKKOPP WHERE HDKKOPP.ID = HDPROTKOPPBER.ID AND HDKKOPP.TYP = HDPROTKOPPBER.TYP NO-LOCK:
      CREATE KalkylimportTT.
      ASSIGN
      KalkylimportTT.TTRECID = RECID(KalkylimportTT) 
      KalkylimportTT.KALKNR = KALKHUV.KALKNR
      KalkylimportTT.OMRADE = KALKHUV.OMRADE
      KalkylimportTT.MATRIS = 1
      KalkylimportTT.ARBKOD = HDKKOPP.ARBKOD 
      KalkylimportTT.LOPNR = HDKKOPP.LOPNR
      KalkylimportTT.SID = HDPROTKOPPBER.SID. 
      KalkylimportTT.ANTAL     = 1 * Antalkalkyl(ovar).
       
      IF HDKKOPP.TYP = "F" THEN DO:
         KalkylimportTT.ANTAL     =  HDKKOPP.ANTAL * Antalkalkyl(ovar).     
      END. 
      IF HDKKOPP.TYP = "PH" THEN DO:
         IF KalkylimportTT.ANTAL NE 0 THEN DO:
            KalkylimportTT.ANTAL =  KalkylimportTT.ANTAL * HDKKOPP.ANTAL.
         END.
      END.  
      FIND LAST KALKYLLOPPOSTER WHERE KALKYLLOPPOSTER.ARBKOD = KalkylimportTT.ARBKOD AND KALKYLLOPPOSTER.LOPNR = KalkylimportTT.LOPNR USE-INDEX LOPNR NO-LOCK NO-ERROR.
      IF AVAILABLE KALKYLLOPPOSTER THEN DO:
         IF KALKYLLOPPOSTER.ENHET = "KM" THEN KalkylimportTT.ANTAL = KalkylimportTT.ANTAL / 1000.
      END.
   END. 
END PROCEDURE.
PROCEDURE valkalk_UI.

   IF forsta = TRUE THEN DO:      
      /*HÄMTA KODER SOM LIGGER DIREKT PÅ KONSTRUKTIONEN ENDAST EN GÅNG*/
      OPEN QUERY kalkbq FOR EACH KALKBER WHERE KALKBER.KTYPKOD = BERVAL.KTYPKOD AND
      KALKBER.F1 = "" AND KALKBER.F2 = " " AND KALKBER.F3 = " " AND
      KALKBER.F4 = " " AND KALKBER.F5 = " " USE-INDEX AR NO-LOCK. 
      GET FIRST kalkbq NO-LOCK.
      DO WHILE AVAILABLE(KALKBER):
         RUN skapakalk_UI.
         GET NEXT kalkbq NO-LOCK. 
      END.
      CLOSE QUERY kalkbq.
      forsta = FALSE.      
   END.      
   IF BERVAL.F2 NE "" THEN DO: 
      OPEN QUERY kalkbq FOR EACH KALKBER WHERE KALKBER.KTYPKOD = BERVAL.KTYPKOD AND
      KALKBER.F1 = BERVAL.F2 AND KALKBER.F2 = " " AND KALKBER.F3 = " " AND
      KALKBER.F4 = " " AND KALKBER.F5 = " " USE-INDEX AR NO-LOCK. 
      GET FIRST kalkbq NO-LOCK.
      DO WHILE AVAILABLE(KALKBER):
         RUN skapakalk_UI.
         GET NEXT kalkbq NO-LOCK. 
      END.
      CLOSE QUERY kalkbq.      
   END.     
   IF BERVAL.F3 NE "" THEN DO: 
      OPEN QUERY kalkbq FOR EACH KALKBER WHERE KALKBER.KTYPKOD = BERVAL.KTYPKOD AND
      KALKBER.F2 = BERVAL.F3 AND KALKBER.F1 = " " AND KALKBER.F3 = " " AND
      KALKBER.F4 = " " AND KALKBER.F5 = " " USE-INDEX AR NO-LOCK. 
      GET FIRST kalkbq NO-LOCK.
      DO WHILE AVAILABLE(KALKBER):
         RUN skapakalk_UI.
         GET NEXT kalkbq NO-LOCK. 
      END.
      CLOSE QUERY kalkbq.      
   END.   
   IF BERVAL.F4 NE "" THEN DO: 
      OPEN QUERY kalkbq FOR EACH KALKBER WHERE KALKBER.KTYPKOD = BERVAL.KTYPKOD AND
      KALKBER.F3 = BERVAL.F4 AND KALKBER.F1 = " " AND KALKBER.F2 = " " AND
      KALKBER.F4 = " " AND KALKBER.F5 = " " USE-INDEX AR NO-LOCK. 
      GET FIRST kalkbq NO-LOCK.
      DO WHILE AVAILABLE(KALKBER):
         RUN skapakalk_UI.
         GET NEXT kalkbq NO-LOCK. 
      END.
      CLOSE QUERY kalkbq.      
   END.   
   IF BERVAL.F5 NE "" THEN DO: 
      OPEN QUERY kalkbq FOR EACH KALKBER WHERE KALKBER.KTYPKOD = BERVAL.KTYPKOD AND
      KALKBER.F4 = BERVAL.F5 AND KALKBER.F1 = " " AND KALKBER.F2 = " " AND
      KALKBER.F3 = " " AND KALKBER.F5 = " " USE-INDEX AR NO-LOCK. 
      GET FIRST kalkbq NO-LOCK.
      DO WHILE AVAILABLE(KALKBER):
         RUN skapakalk_UI.
         GET NEXT kalkbq NO-LOCK. 
      END.
      CLOSE QUERY kalkbq.      
   END.   
   IF BERVAL.F6 NE "" THEN DO: 
      OPEN QUERY kalkbq FOR EACH KALKBER WHERE KALKBER.KTYPKOD = BERVAL.KTYPKOD AND
      KALKBER.F5 = BERVAL.F6 AND KALKBER.F1 = " " AND KALKBER.F2 = " " AND
      KALKBER.F3 = " " AND KALKBER.F4 = " " USE-INDEX AR NO-LOCK. 
      GET FIRST kalkbq NO-LOCK.
      DO WHILE AVAILABLE(KALKBER):
         RUN skapakalk_UI.
         GET NEXT kalkbq NO-LOCK. 
      END.
      CLOSE QUERY kalkbq.      
   END.      
END PROCEDURE.  
   

PROCEDURE skapakalk_UI : 
      CREATE KalkylimportTT.
      ASSIGN
      KalkylimportTT.TTRECID = RECID(KalkylimportTT) 
      KalkylimportTT.MATRIS = 1
      KalkylimportTT.ARBKOD = KALKBER.ARBKOD 
      KalkylimportTT.LOPNR = KALKBER.LOPNR
      KalkylimportTT.ANTAL = KALKBER.ANTAL
      KalkylimportTT.SID = valsid
      KalkylimportTT.BERNUM = valnum.
            
END PROCEDURE.      
FUNCTION Antalkalkyl RETURNS DECIMAL
  ( INPUT ordvar AS INTEGER):
   IF ordvar = 1 THEN RETURN sumhdschtprot.DEC1.
   IF ordvar = 2 THEN RETURN sumhdschtprot.DEC2. 
   IF ordvar = 3 THEN RETURN sumhdschtprot.DEC3. 
   IF ordvar = 4 THEN RETURN sumhdschtprot.DEC4. 
   IF ordvar = 5 THEN RETURN sumhdschtprot.DEC5. 
   IF ordvar = 6 THEN RETURN sumhdschtprot.DEC6. 
   IF ordvar = 7 THEN RETURN sumhdschtprot.DEC7. 
   IF ordvar = 8 THEN RETURN sumhdschtprot.DEC8. 
   IF ordvar = 9 THEN RETURN sumhdschtprot.DEC9. 
   IF ordvar = 10 THEN RETURN sumhdschtprot.DEC10.
   IF ordvar = 11 THEN RETURN sumhdschtprot.DEC11.
   IF ordvar = 12 THEN RETURN sumhdschtprot.DEC12.
   IF ordvar = 13 THEN RETURN sumhdschtprot.DEC13.
   IF ordvar = 14 THEN RETURN sumhdschtprot.DEC14.
   IF ordvar = 15 THEN RETURN sumhdschtprot.DEC15.
   IF ordvar = 16 THEN RETURN sumhdschtprot.DEC16.
   IF ordvar = 17 THEN RETURN sumhdschtprot.DEC17.
   IF ordvar = 18 THEN RETURN sumhdschtprot.DEC18.
   IF ordvar = 19 THEN RETURN sumhdschtprot.DEC19.
   IF ordvar = 20 THEN RETURN sumhdschtprot.DEC20.
   IF ordvar = 21 THEN RETURN sumhdschtprot.DEC21.
   IF ordvar = 22 THEN RETURN sumhdschtprot.DEC22.
   IF ordvar = 23 THEN RETURN sumhdschtprot.DEC23.
   IF ordvar = 24 THEN RETURN sumhdschtprot.DEC24.
   IF ordvar = 25 THEN RETURN sumhdschtprot.DEC25.
   IF ordvar = 26 THEN RETURN sumhdschtprot.DEC26.
   IF ordvar = 27 THEN RETURN sumhdschtprot.DEC27.
   IF ordvar = 28 THEN RETURN sumhdschtprot.DEC28.
   IF ordvar = 29 THEN RETURN sumhdschtprot.DEC29.
   IF ordvar = 30 THEN RETURN sumhdschtprot.DEC30.
   IF ordvar = 31 THEN RETURN sumhdschtprot.DEC31.
   IF ordvar = 32 THEN RETURN sumhdschtprot.DEC32.
   IF ordvar = 33 THEN RETURN sumhdschtprot.DEC33.
   IF ordvar = 34 THEN RETURN sumhdschtprot.DEC34.
   IF ordvar = 35 THEN RETURN sumhdschtprot.DEC35.
   IF ordvar = 36 THEN RETURN sumhdschtprot.DEC36.
   IF ordvar = 37 THEN RETURN sumhdschtprot.DEC37.
   IF ordvar = 38 THEN RETURN sumhdschtprot.DEC38.
   IF ordvar = 39 THEN RETURN sumhdschtprot.DEC39.
   IF ordvar = 40 THEN RETURN sumhdschtprot.DEC40.

END FUNCTION.  