
/*------------------------------------------------------------------------
    File        : KOLLVOLYMSTART.I
    Purpose     : 

    Syntax      :

    Description : 

    Author(s)   : 
    Created     : Thu Aug 12 13:25:19 CEST 2021
    Notes       :
  ----------------------------------------------------------------------*/

RUN KollVolymStart_UI (OUTPUT vstartad).
   IF vstartad = TRUE THEN RETURN.
