/*
               KSV Editor
    Copyright: (C) 2000-2003 Serguey Klimoff (bulkl0DD)
     Filename: SCHAKTADB.P
      Comment: Skriver till databas för schakta.w // schaktit.p
   Parameters:
         Uses:
      Used by:
      Created: 2008.08.21 10:25 ELPAO   
     Modified: 
*/


{SCADMIN.I}

/* lägger till en kabellinjepost, fungerar med till schakt samt till punkt. */
PROCEDURE addkab_UI :
   DEFINE INPUT PARAMETER BENAMNING AS CHARACTER NO-UNDO.
   DEFINE INPUT PARAMETER KABID    AS INTEGER NO-UNDO.
   DEFINE INPUT PARAMETER KLID     AS INTEGER NO-UNDO.
   DEFINE INPUT PARAMETER BERNR    AS INTEGER NO-UNDO.
   DEFINE INPUT PARAMETER OMRADE   AS CHARACTER NO-UNDO.
   DEFINE INPUT PARAMETER SID      AS INTEGER NO-UNDO.
   DEFINE INPUT PARAMETER PID      AS INTEGER NO-UNDO.
   DEFINE INPUT PARAMETER START    AS LOGICAL NO-UNDO.
   DEFINE INPUT PARAMETER AVSLUTAD AS LOGICAL NO-UNDO.
   DEFINE INPUT PARAMETER ORDNING  AS INTEGER NO-UNDO.
   DEFINE INPUT PARAMETER SLUT     AS LOGICAL NO-UNDO.


   DO TRANSACTION:
      CREATE HDKABELLINJE.
      ASSIGN
      HDKABELLINJE.BENAMNING =   BENAMNING
      HDKABELLINJE.KABID     =   KABID    
      HDKABELLINJE.KLID      =   KLID     
      HDKABELLINJE.BERNR     =   BERNR    
      HDKABELLINJE.OMRADE    =   OMRADE   
      HDKABELLINJE.SID       =   SID      
      HDKABELLINJE.PID       =   PID      
      HDKABELLINJE.START     =   START    
      HDKABELLINJE.AVSLUTAD  =   AVSLUTAD 
      HDKABELLINJE.ORDNING   =   ORDNING  
      HDKABELLINJE.SLUT      =   SLUT.     

      RETURN.
   END.  

RELEASE HDKABELLINJE.

END PROCEDURE.

/* tar bort kabel från en punkt samt ur alla punkter med större ordning än markerad punkt */
PROCEDURE remkab_UI :
  DEFINE INPUT PARAMETER inbernr AS INTEGER NO-UNDO.
  DEFINE INPUT PARAMETER inomrade AS CHARACTER NO-UNDO.
  DEFINE INPUT PARAMETER insid AS INTEGER NO-UNDO.
  DEFINE INPUT PARAMETER inklid AS INTEGER NO-UNDO.
  DEFINE INPUT PARAMETER inordning AS INTEGER NO-UNDO.
  DEFINE INPUT PARAMETER inpid AS INTEGER NO-UNDO.
  
  DO TRANSACTION:
      /*FIND HDKABELLINJE WHERE KLID = inklid AND PID = inpid EXCLUSIVE-LOCK NO-ERROR.*/
      
      FOR EACH HDKABELLINJE WHERE HDKABELLINJE.BERNR = inbernr AND HDKABELLINJE.OMRADE = inomrade AND HDKABELLINJE.KLID = inklid AND HDKABELLINJE.ORDNING >= inordning EXCLUSIVE-LOCK:
         DELETE HDKABELLINJE.
      END.

   END.


   RELEASE HDKABELLINJE.

END PROCEDURE.

/* uppdaterar en HDSCHAKTFOR-post, tar in område, bernr, sid och hittar posten, sedan uppdateras 
   BREDD, DJUP, YTBELAGG, LAGID */   
PROCEDURE updatesf_UI :
   /* för att välja sid */
   DEFINE INPUT PARAMETER inbernr AS INTEGER NO-UNDO.
   DEFINE INPUT PARAMETER inomrade AS CHARACTER NO-UNDO.
   DEFINE INPUT PARAMETER insid AS INTEGER NO-UNDO.
   
   /* värden som kan uppdateras */
   DEFINE INPUT PARAMETER inbredd AS INTEGER NO-UNDO.
   DEFINE INPUT PARAMETER indjup AS INTEGER NO-UNDO.
   DEFINE INPUT PARAMETER inytbelagg AS CHARACTER NO-UNDO.
   DEFINE INPUT PARAMETER inlagid AS CHARACTER NO-UNDO.

   DO TRANSACTION:
      FIND HDSCHAKTFOR WHERE HDSCHAKTFOR.BERNR = inbernr AND HDSCHAKTFOR.OMRADE = inomrade AND HDSCHAKTFOR.SID = insid.
      
      ASSIGN
      HDSCHAKTFOR.BREDD = inbredd
      HDSCHAKTFOR.DJUP = indjup
      HDSCHAKTFOR.YTBELAGG = inytbelagg
      HDSCHAKTFOR.LAGID = inlagid.
   END.
END PROCEDURE.



PROCEDURE addsf_UI :
   DEFINE INPUT PARAMETER inbernr AS INTEGER NO-UNDO.
   DEFINE INPUT PARAMETER inomrade AS CHARACTER NO-UNDO.
   DEFINE INPUT PARAMETER insid AS INTEGER NO-UNDO.
   DEFINE INPUT PARAMETER infid AS INTEGER NO-UNDO.
   DEFINE INPUT PARAMETER inpid1 AS INTEGER NO-UNDO.
   DEFINE INPUT PARAMETER inpid2 AS INTEGER NO-UNDO.
   DEFINE INPUT PARAMETER inlangd AS INTEGER NO-UNDO.

   DO TRANSACTION:
      CREATE HDSCHAKTFOR.
      ASSIGN
      HDSCHAKTFOR.BERNR = inbernr    
      HDSCHAKTFOR.OMRADE = inomrade   
      HDSCHAKTFOR.PID1 = inpid1     
      HDSCHAKTFOR.PID2 = inpid2     
      HDSCHAKTFOR.SID = insid      
      HDSCHAKTFOR.FID = infid.
      /*HDSCHAKTFOR.YTBELAGG  
      HDSCHAKTFOR.LAGID
      HDSCHAKTFOR.DJUP 
      HDSCHAKTFOR.BREDD
      HDSCHAKTFOR.LANGD*/
      RETURN.

   END.


   RELEASE HDSCHAKTFOR.
END PROCEDURE.


PROCEDURE remsf_UI :
END PROCEDURE.


   
   
   
   
   
   
   
   
   
   


