/*AVTUUPG.P*/
{OAVTEMP.I}
{FORETEMP.I}
DEFINE VARIABLE extabh AS HANDLE NO-UNDO.  /* EXTRATABHMT.P*/
DEFINE VARIABLE exdatah AS HANDLE NO-UNDO. /*EXTRADATAHMT.P*/



PROCEDURE ftghmt_UI:
   DEFINE OUTPUT PARAMETER TABLE FOR foretemp.
   FIND FIRST FORETAG NO-LOCK NO-ERROR.
   CREATE foretemp.
   ASSIGN
   foretemp.ATRHOME = FORETAG.ATRHOME 
   foretemp.FORETAG = FORETAG.FORETAG 
   foretemp.GRAFTECK = FORETAG.GRAFTECK
   foretemp.PROGRAM  = FORETAG.PROGRAM 
   foretemp.VERSION  = FORETAG.VERSION.
       
END PROCEDURE.
PROCEDURE oavhmt_UI:
   DEFINE OUTPUT PARAMETER TABLE FOR oavtemp.
   
   EMPTY TEMP-TABLE oavtemp NO-ERROR. 
   FOR EACH OVERAVTAB   NO-LOCK:
     CREATE oavtemp.
     BUFFER-COPY OVERAVTAB TO oavtemp.
   END.   
       
END PROCEDURE.