DEFINE BUFFER A FOR BEREDSKAPTAB.
FOR EACH BEREDSKAPTAB WHERE BEREDSKAPSAVTAL = "T":
CREATE A.
     
ASSIGN
A.BEREDSKAPSAVTAL = "T1"
A.BEREDSKAP = BEREDSKAPTAB.BEREDSKAP
A.BERSTART1 = BEREDSKAPTAB.BERSTART1
A.BERSTOPP1 = BEREDSKAPTAB.BERSTOPP1
A.DAGNR = BEREDSKAPTAB.DAGNR
A.BERANTAL = BEREDSKAPTAB.BERANTAL.
