/*SKBEAV.P UTSKRIFT AV BEREDSKAPAVIKELSE BEREDSKAPAV*/
     
OUTPUT TO PRINTER PAGE-SIZE 73
   CONVERT TARGET "iso8859-1".
PUT SKIP (2).
FOR EACH BEREDSKAPAV:
   PUT BEREDSKAPAV.BEREDSKAPSAVTAL AT 6  BEREDSKAPAV.DATUM AT 10 BEREDSKAPAV.BEREDSKAP AT 20
   BEREDSKAPAV.BERSTART1 AT 28 BEREDSKAPAV.BERSTOPP1 AT 33  BEREDSKAPAV.BERANTAL AT 40.   
       
END.  
OUTPUT CLOSE.
