DEFINE VARIABLE A AS CHARACTER. 
DEFINE VARIABLE B AS CHARACTER.
DEFINE VARIABLE C AS CHARACTER.
FOR EACH OVERAVTAB WHERE YEAR(DATUM) = 1996:
  A = "1997".                 
  B = SUBSTRING(STRING(DATUM,"99999999"),5,2).
  C = SUBSTRING(STRING(DATUM,"99999999"),7,2).
  ASSIGN OVERAVTAB.DATUM = DATE(INTEGER(B),INTEGER(C),INTEGER(A)).

END.  