/*ANDDA.P SENASTE ANDRING */
DEFINE SHARED VARIABLE regvnr LIKE TIDREGITAB.VECKONUMMER NO-UNDO.
DEFINE SHARED VARIABLE persrec AS RECID  NO-UNDO.
DEFINE SHARED VARIABLE nytid AS DECIMAL NO-UNDO.
DEFINE SHARED VARIABLE sekunder AS INTEGER NO-UNDO.   
FIND PERSONALTAB WHERE RECID(PERSONALTAB) = persrec NO-LOCK NO-ERROR.
DO TRANSACTION:
   FIND FIRST ANDDA WHERE ANDDA.PERSONALKOD = PERSONALTAB.PERSONALKOD AND
   ANDDA.VECKONUMMER = regvnr USE-INDEX ANDDA EXCLUSIVE-LOCK NO-ERROR.
   IF NOT AVAILABLE ANDDA THEN DO:
      sekunder = TIME.
      RUN SEKTIM.P.
      CREATE ANDDA.
      ASSIGN ANDDA.PERSONALKOD = PERSONALTAB.PERSONALKOD 
      ANDDA.VECKONUMMER = regvnr
      ANDDA.RDATUM = TODAY ANDDA.TID = nytid.
   END.
   ELSE DO:
      sekunder = TIME.
      RUN SEKTIM.P.
      ASSIGN ANDDA.RDATUM = TODAY ANDDA.TID = nytid.
   END.
END.
