/*PROGRAMMET TAR BORT KALKYLUPPLÄGG FÖR ETT GIVET ÅR*/

DEFINE VARIABLE valar LIKE P1.KATAR NO-UNDO.
FIND FIRST FORETAG WHERE NO-LOCK NO-ERROR.
/*IF FORETAG.FORETAG = "GRAN" THEN valar = 2017.
ELSE valar = 2016.*/

ASSIGN
valar = 2018.

/*  DO WHILE valar < 2005: */
   OPEN QUERY kq FOR EACH P1 WHERE P1.KATAR = valar NO-LOCK.
   GET FIRST kq EXCLUSIVE-LOCK.
   DO WHILE AVAILABLE(P1):
      DELETE P1.
      GET NEXT kq EXCLUSIVE-LOCK.
   END.
   CLOSE QUERY kq.

   OPEN QUERY kq2 FOR EACH P2 WHERE P2.KATAR = valar NO-LOCK.
   GET FIRST kq2 EXCLUSIVE-LOCK.
   DO WHILE AVAILABLE(P2):
      DELETE P2.
      GET NEXT kq2 EXCLUSIVE-LOCK.
   END.
   CLOSE QUERY kq2.

   OPEN QUERY kq3 FOR EACH P3 WHERE P3.KATAR = valar NO-LOCK.
   GET FIRST kq3 EXCLUSIVE-LOCK.
   DO WHILE AVAILABLE(P3):
      DELETE P3.
      GET NEXT kq3 EXCLUSIVE-LOCK.
   END.
   CLOSE QUERY kq3.

   OPEN QUERY kq35 FOR EACH P5 WHERE P5.KATAR = valar NO-LOCK.
   GET FIRST kq35 EXCLUSIVE-LOCK.
   DO WHILE AVAILABLE(P5):
      DELETE P5.
      GET NEXT kq35 EXCLUSIVE-LOCK.
   END.
   CLOSE QUERY kq35.

   OPEN QUERY kq4 FOR EACH LOP1 WHERE LOP1.KATAR = valar NO-LOCK.
   GET FIRST kq4 EXCLUSIVE-LOCK.
   DO WHILE AVAILABLE(LOP1):
      DELETE LOP1.
      GET NEXT kq4 EXCLUSIVE-LOCK.
   END.
   CLOSE QUERY kq4.
   
   OPEN QUERY kq5 FOR EACH LOP2 WHERE LOP2.KATAR = valar NO-LOCK.
   GET FIRST kq5 EXCLUSIVE-LOCK.
   DO WHILE AVAILABLE(LOP2):
      DELETE LOP2.
      GET NEXT kq5 EXCLUSIVE-LOCK.
   END.
   CLOSE QUERY kq5.
   
   OPEN QUERY kq6 FOR EACH LOP3 WHERE LOP3.KATAR = valar NO-LOCK.
   GET FIRST kq6 EXCLUSIVE-LOCK.
   DO WHILE AVAILABLE(LOP3):
      DELETE LOP3.
      GET NEXT kq6 EXCLUSIVE-LOCK.
   END.
   CLOSE QUERY kq6.

   OPEN QUERY kq65 FOR EACH LOP5 WHERE LOP5.KATAR = valar NO-LOCK.
   GET FIRST kq65 EXCLUSIVE-LOCK.
   DO WHILE AVAILABLE(LOP5):
      DELETE LOP5.
      GET NEXT kq65 EXCLUSIVE-LOCK.
   END.
   CLOSE QUERY kq65.

   OPEN QUERY kq7 FOR EACH FREKVENS WHERE FREKVENS.KATAR = valar NO-LOCK.
   GET FIRST kq7 EXCLUSIVE-LOCK.
   DO WHILE AVAILABLE(FREKVENS):
      DELETE FREKVENS.
      GET NEXT kq7 EXCLUSIVE-LOCK.
   END.
   CLOSE QUERY kq7.

   /*OPEN QUERY kq8 FOR EACH EBRPRIS WHERE EBRPRIS.ARTAL = valar NO-LOCK.
   GET FIRST kq8 EXCLUSIVE-LOCK.
   DO WHILE AVAILABLE(EBRPRIS):
      DELETE EBRPRIS.
      GET NEXT kq8 EXCLUSIVE-LOCK.
   END.
   CLOSE QUERY kq8.*/

   OPEN QUERY kq85 FOR EACH SEBRPRIS WHERE SEBRPRIS.ARTAL = valar NO-LOCK.
   GET FIRST kq85 EXCLUSIVE-LOCK.
   DO WHILE AVAILABLE(SEBRPRIS):
      DELETE SEBRPRIS.
      GET NEXT kq85 EXCLUSIVE-LOCK.
   END.
   CLOSE QUERY kq85.

   /*OPEN QUERY kq9 FOR EACH KALKBEF WHERE KALKBEF.KATAR = valar AND
   KALKBEF.KALKNR = 0 NO-LOCK.
   GET FIRST kq9 EXCLUSIVE-LOCK.
   DO WHILE AVAILABLE(KALKBEF):
      DELETE KALKBEF.
      GET NEXT kq9 EXCLUSIVE-LOCK.
   END.
   CLOSE QUERY kq9.*/
   
/*     valar = valar + 1.  */
/*  END.                   */
   FIND FIRST FORETAG NO-LOCK NO-ERROR.
   IF FORETAG.FORETAG = "VSYD" OR FORETAG.FORETAG = "VORD" OR
   FORETAG.FORETAG = "VAST"  OR FORETAG.FORETAG = "VOST" THEN DO:
      OUTPUT TO e:\delad\pro9\guru\koll.txt APPEND.
      PUT "Borttag av kalkylupplägg klart. " substring(FORETAG.FORETAG,1,10) SKIP.
      OUTPUT CLOSE.
   END.
   ELSE IF FORETAG.FORETAG = "GRAN" THEN DO:
      OUTPUT TO d:\elpool\delad\pro9\wrk\koll.txt APPEND.
      PUT "Borttag av kalkylupplägg klart. " substring(FORETAG.FORETAG,1,10) SKIP.
      OUTPUT CLOSE.
   END.
   ELSE IF FORETAG.FORETAG = "GKAL" THEN DO:
      OUTPUT TO D:\DELAD\klient\PRO9\koll.txt APPEND.
      PUT "Borttag av kalkylupplägg klart. " substring(FORETAG.FORETAG,1,10) SKIP.
      OUTPUT CLOSE.
   END.
         
