/*DEPAITS.p*/
DEFINE NEW SHARED VARIABLE quotervar AS CHARACTER FORMAT "X(256)" NO-UNDO.



DEFINE VARIABLE musz AS LOGICAL NO-UNDO.

DEFINE VARIABLE rad AS INTEGER NO-UNDO.
DEFINE VARIABLE prognamn AS CHARACTER FORMAT "X(20)" NO-UNDO.
DEFINE VARIABLE prognamndat AS CHARACTER FORMAT "X(20)" NO-UNDO.
DEFINE VARIABLE prognamnque AS CHARACTER FORMAT "X(20)" NO-UNDO.                
DEFINE VARIABLE words AS CHARACTER FORMAT "X(132)" NO-UNDO.
DEFINE VARIABLE kommando AS CHARACTER FORMAT "X(132)" NO-UNDO.
DEFINE VARIABLE kommandoprog AS CHARACTER FORMAT "X(20)" NO-UNDO.
DEFINE VARIABLE satsvar AS CHARACTER FORMAT "X(11)" NO-UNDO.
DEFINE VARIABLE enrvar AS CHARACTER FORMAT "X(11)" NO-UNDO.
DEFINE VARIABLE melvar AS INTEGER NO-UNDO.
DEFINE VARIABLE melvar2 AS INTEGER NO-UNDO.
DEFINE VARIABLE langd AS INTEGER NO-UNDO.
DEFINE VARIABLE pos1 AS INTEGER NO-UNDO. 

DEFINE BUFFER mtrlbuff FOR MTRL.

DEFINE TEMP-TABLE tidin
   FIELD ENR                AS CHARACTER  
   FIELD BENAMNING          AS CHARACTER    
   FIELD ENHET              AS CHARACTER
   FIELD BPRIS              AS DECIMAL
   FIELD NPRIS              AS DECIMAL
   INDEX ENR IS PRIMARY ENR.  
   
{muswait.i}      
  {AMERICANEUROPEAN.I}


   FOR EACH tidin:
      DELETE tidin.
   END.       
   INPUT FROM \\pc112\delad\elpool\elpnj\graninge\its\depa.skv NO-ECHO.
   REPEAT:
      DO TRANSACTION: 
         CREATE tidin.
         ASSIGN.
         IMPORT DELIMITER ";" tidin   NO-ERROR.
      END.               
   END.
   FOR EACH tidin WHERE tidin.ENR = "":
      DELETE tidin.
   END.
   RUN skapaenr_UI.
{EUROPEANAMERICAN.I}
PROCEDURE skapaenr_UI:   
   FOR EACH tidin:
      CREATE MTRLDEP.
      ASSIGN
      MTRLDEP.DEPNR = 2
      MTRLDEP.ENR = tidin.ENR
      MTRLDEP.BENAMNING = tidin.BENAMNING
      MTRLDEP.ENHET = tidin.ENHET
      MTRLDEP.BPRIS = tidin.BPRIS / 100
      MTRLDEP.NPRIS = tidin.NPRIS / 100     
      MTRLDEP.BESTKVANT = 0
      MTRLDEP.BESTPUNKT = 0
      MTRLDEP.INVANT = 0
      MTRLDEP.INVDATUM = TODAY      
      MTRLDEP.OMSATT = 0
      MTRLDEP.LEVKOD = "2"
      MTRLDEP.SALDO = 0
      MTRLDEP.LAGER = TRUE.
   END.
END PROCEDURE.   
