/*EGENBENA.P.*/
{GURUTEXTERTT.I}
&Scoped-define NEW NEW
{FORETEMP.I}
DEFINE OUTPUT PARAMETER TABLE FOR tesxttemp.
DEFINE OUTPUT PARAMETER TABLE FOR foretemp.
FIND FIRST FORETAG NO-LOCK NO-ERROR.
CREATE foretemp.
ASSIGN
foretemp.ATRHOME = FORETAG.ATRHOME 
foretemp.FORETAG = FORETAG.FORETAG 
foretemp.GRAFTECK = FORETAG.GRAFTECK
foretemp.PROGRAM  = FORETAG.PROGRAM. 
/*
foretemp.VERSION  = FORETAG.VERSION.
*/

{GURUTEXTER.I}
