 /*EMEDPRSU.P*/
DEFINE VARIABLE str AS CHARACTER NO-UNDO.
DEFINE VARIABLE prmeddel AS CHARACTER FORMAT "X(255)" NO-UNDO.
DEFINE VARIABLE skick AS LOGICAL NO-UNDO.
DEFINE VARIABLE efel AS CHARACTER FORMAT "X(30)" NO-UNDO.
DEFINE NEW SHARED VARIABLE musz AS LOGICAL NO-UNDO.

DEFINE INPUT PARAMETER aonrrec AS RECID NO-UNDO.
DEFINE INPUT PARAMETER globanv LIKE ANVANDARE.ANVANDARE NO-UNDO.
DEFINE INPUT PARAMETER globforetag LIKE FORETAG.FORETAG NO-UNDO.
DEFINE INPUT PARAMETER aoort AS CHARACTER NO-UNDO.
   

DEFINE NEW SHARED VARIABLE appcon AS LOGICAL NO-UNDO.


IF globforetag = "SUND"  OR globforetag = "SNAT" THEN DO:
   FIND FIRST AONRTAB WHERE RECID(AONRTAB) = aonrrec NO-LOCK NO-ERROR.
   IF AVAILABLE AONRTAB THEN DO:   
      RUN emedd_UI (INPUT "siv.spjut@serva.se").
   END.

END.
ELSE IF globforetag = "ELPA" THEN DO:
   FIND FIRST AONRTAB WHERE RECID(AONRTAB) = aonrrec NO-LOCK NO-ERROR.
   IF AVAILABLE AONRTAB THEN DO:   
      RUN emedd_UI (INPUT "lena@elpool.se").
   END.

END.


PROCEDURE emedd_UI.
   DEFINE INPUT PARAMETER medpers LIKE  MEDDELANDE.MOTTAGARE.
   FIND FIRST KBENAMNING USE-INDEX KBEN NO-LOCK NO-ERROR.

   prmeddel= "Nya/ändrade kontosträngar på " + CAPS(Guru.Konstanter:gaok) + " " + AONRTAB.AONR + " " + STRING(AONRTAB.DELNR,"9999") + " " + aoort + " " + " från GURU"  + CHR(10).        
   OPEN QUERY aq FOR EACH AONRKONTKOD WHERE AONRKONTKOD.AONR = AONRTAB.AONR AND AONRKONTKOD.DELNR = AONRTAB.DELNR NO-LOCK.
   GET FIRST aq NO-LOCK.
   DO WHILE AVAILABLE(AONRKONTKOD):        
      prmeddel = prmeddel + KBENAMNING.K1 + ": "  + AONRKONTKOD.K1 + " " + CAPS(Guru.Konstanter:gaok) + ": " + AONRTAB.AONR + " " + STRING(AONRTAB.DELNR,"9999") + " " + KBENAMNING.K2 + ": " + AONRKONTKOD.K2 + " Procent: " + STRING(AONRKONTKOD.SATS%) + CHR(10).
      GET NEXT aq NO-LOCK. 
   END.   
   RUN EPOST.P (INPUT "", INPUT medpers, INPUT "Nya/ändrade kontosträngar på " + CAPS(Guru.Konstanter:gaok) + " " + AONRTAB.AONR + " " + STRING(AONRTAB.DELNR,"9999") + " från GURU", 
   INPUT prmeddel, INPUT "", INPUT "",INPUT globforetag, OUTPUT skick, OUTPUT efel).
   
END PROCEDURE.  

RETURN.
