/* FREKIN.p INLÄSNING AV FREKVENSTABELL P1 TILL P2 VITA KATALOGEN EXCEL            */
/*4 decimaler på antal                                                */ 
/* TÄNK PÅ ATT DET ÄR MINUS PÅ ANTAL FÖR RETURER I FILEN              */
/* GÖR ANTALSKOLUMNEN UTAN - TECKEN GENOM ATT VÄLJA MINUS MED RÖD FÄRG*/
/* SÄTT VARIABELN ARVAR TILL RÄTT KATALOG ÅR                          */

DEFINE NEW SHARED VARIABLE quotervar AS CHARACTER FORMAT "X(256)" NO-UNDO.



DEFINE VARIABLE musz AS LOGICAL NO-UNDO.

DEFINE VARIABLE rad AS INTEGER NO-UNDO.
DEFINE VARIABLE prognamn AS CHARACTER FORMAT "X(20)" NO-UNDO.
DEFINE VARIABLE prognamndat AS CHARACTER FORMAT "X(20)" NO-UNDO.
DEFINE VARIABLE prognamnque AS CHARACTER FORMAT "X(20)" NO-UNDO.                
DEFINE VARIABLE words AS CHARACTER FORMAT "X(132)" NO-UNDO.
DEFINE VARIABLE kommando AS CHARACTER FORMAT "X(132)" NO-UNDO.
DEFINE VARIABLE kommandoprog AS CHARACTER FORMAT "X(20)" NO-UNDO.
DEFINE VARIABLE satsvar AS CHARACTER FORMAT "X(11)" NO-UNDO.
DEFINE VARIABLE enrvar AS CHARACTER FORMAT "X(11)" NO-UNDO.
DEFINE VARIABLE melvar AS INTEGER NO-UNDO.
DEFINE VARIABLE melvar2 AS INTEGER NO-UNDO.
DEFINE VARIABLE langd AS INTEGER NO-UNDO.
DEFINE VARIABLE pos1 AS INTEGER NO-UNDO.
DEFINE VARIABLE arvar AS INTEGER NO-UNDO.
DEFINE VARIABLE filnamn AS CHARACTER NO-UNDO.

DEFINE TEMP-TABLE tidin
   FIELD P1                 AS CHARACTER FORMAT "X(6)" 
   FIELD B1                 AS CHARACTER FORMAT "X(10)" 
   FIELD P2                 AS CHARACTER FORMAT "X(5)"
   FIELD B2                 AS CHARACTER FORMAT "X(10)" 
   FIELD ANTAL              AS DECIMAL FORMAT ">>>>>9.9999".

DEFINE TEMP-TABLE infil
   FIELD PROGNAMN AS CHARACTER FORMAT "X(78)" 
   INDEX PRO IS PRIMARY PROGNAMN.
DEFINE TEMP-TABLE intid
   FIELD TIN AS CHARACTER FORMAT "X(78)" .

{muswait.i}        
   ASSIGN
   
   arvar = 2013.
   filnamn = "\\server05\d\elpool\elplo\kalk\2012\skv\Vp1p212.skv".
   EMPTY TEMP-TABLE intid NO-ERROR. 
   EMPTY TEMP-TABLE tidin NO-ERROR. 
   {AMERICANEUROPEAN.I}   
   INPUT FROM VALUE(filnamn) NO-ECHO.
   REPEAT:
      DO TRANSACTION: 
         CREATE tidin.
         ASSIGN.
         IMPORT DELIMITER ";" tidin   NO-ERROR.
      END.               
   END.
   
   RUN skapasats_UI.
   {EUROPEANAMERICAN.I}           
{musarrow.i}

PROCEDURE skapasats_UI:   
   FOR EACH tidin NO-LOCK:                                
      DO TRANSACTION:
         CREATE FREKVENS.         
         ASSIGN
         FREKVENS.ARBKOD = SUBSTRING(tidin.P1,1,1) +  " " + SUBSTRING(tidin.P1,2,2)
         FREKVENS.LOPNR = INTEGER(SUBSTRING(tidin.P1,4,2))
         FREKVENS.FREKOD = " " + SUBSTRING(tidin.P2,1,2)
         FREKVENS.FREKNR = INTEGER(SUBSTRING(tidin.P2,3,2))
         FREKVENS.ANTAL = tidin.ANTAL / 10000         
         FREKVENS.KATAR = arvar.                  
         FIND FIRST LOP2 WHERE LOP2.ARBKOD = FREKVENS.FREKOD AND
         LOP2.LOPNR = FREKVENS.FREKNR AND LOP2.KATAR = arvar NO-LOCK NO-ERROR.
         IF AVAILABLE LOP2 THEN DO:
            ASSIGN
            FREKVENS.BENAMNING = LOP2.BENAMNING
            FREKVENS.ENHET = LOP2.ENHET.            
         END. 
         ELSE DO:
            ASSIGN
            FREKVENS.BENAMNING = tidin.B2.
         END.
      END.                           
   END.      
END PROCEDURE.   

                
