  /*GRFEEKO.P rattningsrutin*/
{LESAMMAN.I}  
DEFINE INPUT PARAMETER vkdatum AS DATE NO-UNDO.
RUN sammut_UI (INPUT 1).
DEFINE NEW SHARED VARIABLE musz AS LOGICAL NO-UNDO.
DEFINE NEW SHARED VARIABLE nytid AS DECIMAL FORMAT "99.99" NO-UNDO.
DEFINE NEW SHARED VARIABLE sekunder AS INTEGER FORMAT "-9999999" NO-UNDO. 
DEFINE NEW SHARED VARIABLE persrec AS RECID NO-UNDO. 
DEFINE VARIABLE ekrid AS RECID EXTENT 50 NO-UNDO.
DEFINE VARIABLE aoomrade LIKE AONRTAB.OMRADE NO-UNDO.          
DEFINE VARIABLE timtid AS DECIMAL FORMAT "99.99" NO-UNDO. 
DEFINE VARIABLE multi AS DECIMAL FORMAT "99.99" NO-UNDO.
DEFINE VARIABLE berkostnad AS DECIMAL FORMAT "99.99" NO-UNDO.

DEFINE VARIABLE reskod LIKE TIDFEL.LONTILLAGG NO-UNDO. 
DEFINE VARIABLE resantal LIKE TIDFEL.LONTILLANTAL NO-UNDO.
DEFINE VARIABLE resbelopp LIKE EKRAPPRESULT.ELONBELOPP NO-UNDO. 
DEFINE VARIABLE ovkod LIKE TIDFEL.OVERTIDTILL NO-UNDO. 
DEFINE VARIABLE ovantal LIKE TIDFEL.OVERANTAL NO-UNDO.
DEFINE VARIABLE ovbelopp LIKE EKRAPPRESULT.EOVERBELOPP NO-UNDO. 
DEFINE VARIABLE trakod LIKE TIDFEL.TRAKTKOD NO-UNDO. 
DEFINE VARIABLE traantal LIKE TIDFEL.TRAKTANTAL NO-UNDO.
DEFINE VARIABLE trabelopp LIKE EKRAPPRESULT.ETRAKTBELOPP NO-UNDO. 
DEFINE VARIABLE lonkod LIKE TIDFEL.LONTILLAGG NO-UNDO. 
DEFINE VARIABLE lonantal LIKE TIDFEL.LONTILLANTAL NO-UNDO.
DEFINE VARIABLE lonbelopp LIKE EKRAPPRESULT.ELONBELOPP NO-UNDO. 
DEFINE VARIABLE berkodvar LIKE TIDFEL.BEREDSKAP NO-UNDO. 
DEFINE VARIABLE bbantal LIKE TIDFEL.BERANTAL NO-UNDO.
DEFINE VARIABLE berbelopp LIKE EKRAPPRESULT.EBERBELOPP NO-UNDO.
DEFINE VARIABLE pkod LIKE PERSONALTAB.PERSONALKOD NO-UNDO.
DEFINE VARIABLE typover LIKE EKRAPPRESULT.ERESULTENH NO-UNDO. 
DEFINE VARIABLE typdatum LIKE EKRAPPRESULT.ETRANSDATUM NO-UNDO. 
DEFINE VARIABLE kodanst LIKE ANSTFORMTAB.KOD NO-UNDO.
DEFINE TEMP-TABLE ekoforst
   FIELD ENY LIKE EKRAPPRESULT.ENY 
   FIELD EPERSONALKOD LIKE EKRAPPRESULT.EPERSONALKOD 
   FIELD EPROJEKT LIKE EKRAPPRESULT.EPROJEKT 
   FIELD EORG LIKE EKRAPPRESULT.EORG  
   FIELD EGEO LIKE EKRAPPRESULT.EGEO 
   FIELD FELDEBKRED AS LOGICAL
   FIELD ETRANSDATUM LIKE EKRAPPRESULT.ETRANSDATUM
   FIELD EOVERJA LIKE EKRAPPRESULT.EOVERJA
   FIELD ERESULTENH LIKE EKRAPPRESULT.ERESULTENH 
   FIELD EBELOPP LIKE  EKRAPPRESULT.EBELOPP 
   FIELD EANTAL  LIKE EKRAPPRESULT.EANTAL 	       
   FIELD ELONTILLAGG LIKE EKRAPPRESULT.ELONTILLAGG 
   FIELD ELONTILLANTAL LIKE EKRAPPRESULT.ELONTILLANTAL    
   FIELD ELONBELOPP LIKE EKRAPPRESULT.ELONBELOPP         
   INDEX PERSORG IS PRIMARY EPERSONALKOD EORG EGEO EPROJEKT ASCENDING.

/* OM FRÅNVARO AONR ANVÄDS STYR PRISTYPEN*/
pkod = "".
OPEN QUERY persq FOR EACH PERSONALTAB WHERE PERSONALTAB.BRAVO = TRUE 
USE-INDEX PERSONALKOD NO-LOCK.
GET FIRST persq NO-LOCK.
DO WHILE AVAILABLE(PERSONALTAB):
   musz = FALSE.
   aoomrade = "".
   persrec = RECID(PERSONALTAB).   
   IF pkod NE PERSONALTAB.PERSONALKOD THEN DO:
      pkod = PERSONALTAB.PERSONALKOD.        
      persrec = RECID(PERSONALTAB).
      FIND FIRST ANSTFORMTAB WHERE
      ANSTFORMTAB.ANSTALLNING = PERSONALTAB.ANSTALLNING
      USE-INDEX ANSTF NO-LOCK NO-ERROR.  
      /*OBS ! ÄNDRING TJÄNSTEMÄN SKA ÖVER OM DE SKRIVER PÅ "DEB.TJM."
      IF ANSTFORMTAB.KOD = 'T' OR  
         ANSTFORMTAB.KOD = 'T1' OR 
         ANSTFORMTAB.KOD = 'T2' OR 
         ANSTFORMTAB.KOD = 'T3' OR 
         ANSTFORMTAB.KOD = 'T4' OR 
         ANSTFORMTAB.KOD = 'T5' THEN DO:
         IF PERSONALTAB.BEFATTNING = "DRIFTTEKNIKER" OR 
            PERSONALTAB.BEFATTNING = "MÄTTEKNIKER" OR
            PERSONALTAB.BEFATTNING = "BEREDARE"  THEN musz = musz.
         ELSE musz = TRUE.
      END.*/
      kodanst = ANSTFORMTAB.KOD.
   END.
   IF musz = FALSE THEN DO:       
      OPEN QUERY tidq FOR EACH TIDFEL WHERE
      TIDFEL.PERSONALKOD = PERSONALTAB.PERSONALKOD AND
      TIDFEL.SKICKA = TRUE AND TIDFEL.FELKORD = "" /*AND
      TIDFEL.PRISTYP NE "FRÅNVARO."*/ AND TIDFEL.DATUM <= vkdatum
      USE-INDEX PKOD NO-LOCK. 
      GET FIRST tidq NO-LOCK.
      DO WHILE AVAILABLE(TIDFEL):                            
         musz = FALSE.   
         IF TIDFEL.PRISTYP = 'RESTID...' THEN DO: 
 	         musz = TRUE.	        	      	       
	      END.
         /*"EJ DEBI.."*/
	      ELSE IF TIDFEL.PRISTYP = 'EJ DEBI..' THEN DO: 
            musz = TRUE.
            /*
           IF ANSTFORMTAB.KOD BEGINS 'T' THEN DO:
	        IF PERSONALTAB.BEFATTNING = "DRIFTTEKNIKER" OR 
           PERSONALTAB.BEFATTNING = "MÄTTEKNIKER" OR
           PERSONALTAB.BEFATTNING = "BEREDARE" 
           THEN DO:
              /* Dessa personer ska bara över på tot.pris och beredare*/
              IF TIDFEL.PRISTYP = "TOT.PRIS." THEN musz = musz.
              ELSE IF TIDFEL.PRISTYP = "BEREDARE." THEN musz = musz.
              ELSE IF TIDFEL.PRISTYP = "DRIFTCENT" THEN musz = musz.
              ELSE IF TIDFEL.PRISTYP = "ARBETSLED" THEN musz = TRUE.
              ELSE IF TIDFEL.PRISTYP = "PROJEKTÖR" THEN musz = TRUE.
              ELSE IF TIDFEL.PRISTYP = "EJ DEBI.." THEN musz = TRUE.
              ELSE musz = TRUE.               
           END.
           ELSE DO:   
              /*övriga tjänstemän ska bara över på  "deb.tjm."*/
              IF TIDFEL.PRISTYP = "TOT.PRIS." THEN musz = TRUE.	 
              ELSE IF TIDFEL.PRISTYP = "DRIFTCENT" THEN musz = musz.
	           ELSE IF TIDFEL.PRISTYP = "DEB.TJM.." THEN musz = musz.
	           ELSE IF TIDFEL.PRISTYP = "EJ DEBI.." THEN musz = TRUE.  
	           ELSE musz = TRUE.     	      	       
	        END.
           */   
	      END.             
	      IF musz = FALSE THEN DO:           
            FIND FIRST AONRTAB WHERE AONRTAB.AONR = TIDFEL.AONR AND
            AONRTAB.DELNR = TIDFEL.DELNR USE-INDEX AONR NO-LOCK NO-ERROR.
            IF NOT AVAILABLE AONRTAB THEN DO:
               aoomrade = PERSONALTAB.OMRADE. 
               IF TIDFEL.AONR = "" THEN aoomrade = PERSONALTAB.OMRADE. 
              ELSE DO:
                 MESSAGE CAPS(Guru.Konstanter:gaol) TIDFEL.AONR TIDFEL.DELNR "FINNS EJ! KONTAKTA ELPOOL"
                 VIEW-AS ALERT-BOX.
              END.
           END.    
           ELSE DO:
              aoomrade = AONRTAB.OMRADE.   
              IF AONRTAB.OMRADE = "" THEN aoomrade = PERSONALTAB.OMRADE.                  
           END.                      	 	 
           typdatum = DATE(MONTH(TIDFEL.DATUM),01,YEAR(TIDFEL.DATUM)).  
           FIND FIRST ekoforst WHERE ekoforst.ENY = FALSE AND
           ekoforst.EPERSONALKOD = TIDFEL.PERSONALKOD AND 
           ekoforst.EORG = PERSONALTAB.OMRADE AND 
           ekoforst.EGEO = aoomrade AND
           ekoforst.EPROJEKT = TIDFEL.AONR AND         
           ekoforst.ETRANSDATUM = typdatum AND
           ekoforst.FELDEBKRED = TIDFEL.DEBET
           USE-INDEX PERSORG NO-LOCK NO-ERROR.
           IF NOT AVAILABLE ekoforst THEN DO TRANSACTION:
              CREATE ekoforst.
	           ASSIGN 
	           ekoforst.ENY = FALSE
	           ekoforst.EPERSONALKOD = TIDFEL.PERSONALKOD
	           ekoforst.EPROJEKT = TIDFEL.AONR 
	           ekoforst.EORG = PERSONALTAB.OMRADE  
              ekoforst.FELDEBKRED = TIDFEL.DEBET
   	        ekoforst.EGEO = aoomrade 	    	    
	           ekoforst.ETRANSDATUM = typdatum.
           END.                                             
           ekrid[1] = RECID(ekoforst).
	           /*TIDREGISTRERING*/	          	       
	           /*TIMMAR OCH PENNGAR*/  
	        DO TRANSACTION:
	           FIND ekoforst WHERE RECID(ekoforst) = ekrid[1]
	           EXCLUSIVE-LOCK NO-ERROR.                                    
	           ASSIGN ekoforst.EOVERJA = FALSE. 	       
	           IF ekoforst.EOVERJA = FALSE AND TIDFEL.TOTALT > 0 THEN DO:		  
  	 	           nytid = TIDFEL.TOTALT.
		           RUN TIMSEK.P.
		           timtid = (sekunder / 3600).
		           ASSIGN ekoforst.EBELOPP = ekoforst.EBELOPP +
  		           (TIDFEL.PRIS * timtid)
		           ekoforst.EANTAL = ekoforst.EANTAL + timtid.
	           END.
	        END.	    
	     END.
	     GET NEXT tidq NO-LOCK.
      END.
   END.  /*ELSE DO*/
   GET NEXT persq NO-LOCK.
END.   /*FOR EACH*/     

RUN GRFANEKOUT.P (INPUT vkdatum,INPUT TABLE ekoforst).   
RUN sammut_UI (INPUT 2). 
