DEFINE INPUT PARAMETER leverant LIKE LEVERANTOR.LEVKOD NO-UNDO.
  
   OPEN QUERY kq FOR EACH MTRLBER WHERE MTRLBER.LEVKOD = leverant
   NO-LOCK.
   DO TRANSACTION:
      GET FIRST kq EXCLUSIVE-LOCK.
      FIND FIRST SATS WHERE SATS.SATS = TRUE AND SATS.LEVKOD = leverant AND
      SATS.ENR = MTRLBER.ENR USE-INDEX KOD NO-LOCK NO-ERROR.
      IF AVAILABLE SATS THEN MTRLBER.SATS = TRUE.
   END.
   REPEAT:
      DO TRANSACTION:
         GET NEXT kq EXCLUSIVE-LOCK.
         IF NOT AVAILABLE MTRLBER THEN LEAVE.
         ELSE DO:
            FIND FIRST SATS WHERE SATS.SATS = TRUE AND SATS.LEVKOD = leverant AND
            SATS.ENR = MTRLBER.ENR USE-INDEX KOD NO-LOCK NO-ERROR.
            IF AVAILABLE SATS THEN MTRLBER.SATS = TRUE.
         END.
      END.
   END.           
   OPEN QUERY bq FOR EACH BERMTRL WHERE BERMTRL.LEVKOD = leverant
   AND BERMTRL.INKOP = FALSE NO-LOCK.
   DO TRANSACTION:
      GET FIRST bq EXCLUSIVE-LOCK.
      FIND FIRST SATS WHERE SATS.SATS = TRUE AND SATS.LEVKOD = leverant AND
      SATS.ENR = BERMTRL.ENR USE-INDEX KOD NO-LOCK NO-ERROR.
      IF AVAILABLE SATS THEN BERMTRL.SATS = TRUE.
   END.
   REPEAT:
      DO TRANSACTION:
         GET NEXT bq EXCLUSIVE-LOCK.
         IF NOT AVAILABLE BERMTRL THEN LEAVE.
         ELSE DO:
            FIND FIRST SATS WHERE SATS.SATS = TRUE AND SATS.LEVKOD = leverant AND
            SATS.ENR = BERMTRL.ENR USE-INDEX KOD NO-LOCK NO-ERROR.
            IF AVAILABLE SATS THEN BERMTRL.SATS = TRUE.
         END.
      END.
   END.
