/*NIVAPP.P körs inte*/
DEFINE VARIABLE xhop2 LIKE XGURU.MENYVART NO-UNDO.
DEFINE BUFFER menyguru FOR XGURU.
DEFINE INPUT PARAMETER FILL-IN_AV-LEVEL LIKE ANVANDARE.AV-LEVEL NO-UNDO.
DEFINE INPUT PARAMETER FILL-IN_AV-LEVEL-2 LIKE ANVANDARE.AV-LEVEL NO-UNDO.
DEFINE INPUT PARAMETER forordnr LIKE XFOREORDNING.ORDNING NO-UNDO.
DEFINE INPUT PARAMETER globforetag LIKE FORETAG.FORETAG NO-UNDO.
DEFINE INPUT PARAMETER vad AS INTEGER NO-UNDO.
IF vad = 1 THEN DO:
   OPEN QUERY xsekq FOR EACH XSEK WHERE XSEK.AV-LEVEL = FILL-IN_AV-LEVEL 
   USE-INDEX XSEK NO-LOCK.
   DO TRANSACTION:      
      GET FIRST xsekq EXCLUSIVE-LOCK.
      DO WHILE AVAILABLE(XSEK):
         DELETE XSEK.
         GET NEXT xsekq EXCLUSIVE-LOCK.
      END.      
   END.                      
   OPEN QUERY xguruq FOR EACH XGURU WHERE XGURU.AV-LEVEL = FILL-IN_AV-LEVEL 
   USE-INDEX AV-LEVEL NO-LOCK.
   DO TRANSACTION:      
      GET FIRST xguruq EXCLUSIVE-LOCK.
      DO WHILE AVAILABLE(XGURU):
         DELETE XGURU.
         GET NEXT xguruq EXCLUSIVE-LOCK.
      END.      
   END.
END.
IF vad = 2 THEN DO:
   FOR EACH menyguru WHERE menyguru.AV-LEVEL = FILL-IN_AV-LEVEL-2 
   USE-INDEX AV-LEVEL NO-LOCK.
      CREATE XGURU.
      ASSIGN XGURU.AV-LEVEL = FILL-IN_AV-LEVEL
      XGURU.KOPPLING = menyguru.KOPPLING
      XGURU.MEDOK = menyguru.MEDOK
      XGURU.MENY = menyguru.MENY
      XGURU.MENYOK = menyguru.MENYOK
      XGURU.MENYVART = menyguru.MENYVART
      XGURU.ORDNING = menyguru.ORDNING
      XGURU.STORKOPPLING = menyguru.STORKOPPLING.
   END.       
   xhop2 = "".
   OPEN QUERY xlabelq FOR EACH XLABEL WHERE XLABEL.FORETAG[forordnr] = globforetag NO-LOCK.
   GET FIRST xlabelq NO-LOCK.
   NYAMENY:     
   REPEAT:  
      IF NOT AVAILABLE XLABEL THEN LEAVE.
      NASTA:
      REPEAT:
         IF NOT AVAILABLE XLABEL THEN LEAVE.
         ELSE IF XLABEL.MENYVART = xhop2 THEN GET NEXT xlabelq NO-LOCK.
         ELSE DO:
            xhop2 = XLABEL.MENYVART.
            LEAVE.
         END. 
      END.                                      
      OPEN QUERY xguruq
      FOR EACH XGURU WHERE XGURU.MENYVART = xhop2 AND 
      XGURU.AV-LEVEL = FILL-IN_AV-LEVEL 
      USE-INDEX ORDNING NO-LOCK.
      DO TRANSACTION:       
         GET FIRST xguruq NO-LOCK.
         CREATE XSEK.    
         DO WHILE AVAILABLE(XGURU):            
            ASSIGN XSEK.MENYVART = XGURU.MENYVART  
            XSEK.AV-LEVEL = XGURU.AV-LEVEL
            XSEK.SEK[XGURU.ORDNING] = XGURU.MENYOK. 
            GET NEXT xguruq NO-LOCK.
         END. 
      END.
      GET NEXT xlabelq NO-LOCK.    
   END.
END.   
