
/* RABATTITS.P INLÄSNING AV PRISFIL AHLSELL*/       
DEFINE NEW SHARED VARIABLE quotervar AS CHARACTER FORMAT "X(256)" NO-UNDO.



DEFINE VARIABLE musz AS LOGICAL NO-UNDO.

DEFINE VARIABLE rad AS INTEGER NO-UNDO.
DEFINE VARIABLE prognamn AS CHARACTER FORMAT "X(20)" NO-UNDO.
DEFINE VARIABLE prognamndat AS CHARACTER FORMAT "X(20)" NO-UNDO.
DEFINE VARIABLE prognamnque AS CHARACTER FORMAT "X(20)" NO-UNDO.                
DEFINE VARIABLE words AS CHARACTER FORMAT "X(132)" NO-UNDO.
DEFINE VARIABLE kommando AS CHARACTER FORMAT "X(132)" NO-UNDO.
DEFINE VARIABLE kommandoprog AS CHARACTER FORMAT "X(20)" NO-UNDO.
DEFINE VARIABLE satsvar AS CHARACTER FORMAT "X(11)" NO-UNDO.
DEFINE VARIABLE enrvar AS CHARACTER FORMAT "X(11)" NO-UNDO.
DEFINE VARIABLE melvar AS INTEGER NO-UNDO.
DEFINE VARIABLE melvar2 AS INTEGER NO-UNDO.
DEFINE VARIABLE langd AS INTEGER NO-UNDO.
DEFINE VARIABLE pos1 AS INTEGER NO-UNDO. 

DEFINE BUFFER mtrlbuff FOR MTRL.

DEFINE TEMP-TABLE tidin
   FIELD ENR                AS CHARACTER  
   FIELD PROCENT            AS INTEGER    
   INDEX ENR IS PRIMARY ENR.  
{AMERICANEUROPEAN.I}   
{muswait.i}      
   EMPTY TEMP-TABLE tidin NO-ERROR.    
   INPUT FROM \\pc112\delad\elpool\elpnj\graninge\its\13077.skv NO-ECHO.
   REPEAT:
      DO TRANSACTION: 
         CREATE tidin.
         ASSIGN.
         IMPORT DELIMITER ";" tidin   NO-ERROR.
      END.               
   END.
       
   RUN skapaenr_UI.
{EUROPEANAMERICAN.I}
PROCEDURE skapaenr_UI:   
   OPEN QUERY MQ FOR EACH MTRL WHERE MTRL.LEVKOD = "2" AND MTRL.KALKNR = 0
   NO-LOCK.
   DO TRANSACTION:
      GET FIRST MQ EXCLUSIVE-LOCK.
      FIND FIRST tidin WHERE tidin.ENR = SUBSTRING(MTRL.ENR,1,4) NO-LOCK NO-ERROR.
      IF AVAILABLE tidin THEN DO:      
         MTRL.NPRIS = MTRL.NPRIS - (MTRL.NPRIS * (tidin.PROCENT / 100)).
      END.
   END.
   REPEAT:
      DO TRANSACTION:
         GET NEXT MQ EXCLUSIVE-LOCK.
         IF AVAILABLE MTRL THEN DO:
            FIND FIRST tidin WHERE tidin.ENR = SUBSTRING(MTRL.ENR,1,4) NO-LOCK NO-ERROR.
            IF AVAILABLE tidin THEN DO:      
               MTRL.NPRIS = MTRL.NPRIS - (MTRL.NPRIS * (tidin.PROCENT / 100)).
            END.
         END.
         ELSE LEAVE.
      END.
   END.   
END PROCEDURE.   
