/*RMF.P*/
{AMERICANEUROPEAN.I}
OUTPUT TO mtrlber.d convert target "iso8859-1" source "iso8859-1" append.
OPEN QUERY kq FOR EACH KONSTRUKTION WHERE KONSTRUKTION.KONSKOD = 15 NO-LOCK.
GET FIRST kq NO-LOCK.
DO WHILE AVAILABLE(KONSTRUKTION):
   OPEN QUERY kq2 FOR EACH MTRLBER WHERE MTRLBER.KTYPKOD = KONSTRUKTION.KTYPKOD AND
   MTRLBER.F1 = "  RMF 25" NO-LOCK.
   GET FIRST kq2 NO-LOCK.
   DO WHILE AVAILABLE(MTRLBER):
      EXPORT MTRLBER.
      GET NEXT kq2 NO-LOCK.
   END.
   CLOSE QUERY kq2.
   OPEN QUERY kq2 FOR EACH MTRLBER WHERE MTRLBER.KTYPKOD = KONSTRUKTION.KTYPKOD AND
   MTRLBER.F1 = "  RMF 50" NO-LOCK.
   GET FIRST kq2 NO-LOCK.
   DO WHILE AVAILABLE(MTRLBER):
      EXPORT MTRLBER.
      GET NEXT kq2 NO-LOCK.
   END.
   CLOSE QUERY kq2.
   GET NEXT kq NO-LOCK.
END.      
{EUROPEANAMERICAN.I}