DEFINE INPUT PARAMETER pkod AS CHARACTER NO-UNDO.
DEFINE INPUT PARAMETER hjdat AS DATE NO-UNDO.
DEFINE INPUT PARAMETER hjstart AS DECIMAL NO-UNDO.
DEFINE INPUT PARAMETER hjslut AS DECIMAL NO-UNDO.
DEFINE INPUT PARAMETER anr AS CHARACTER NO-UNDO.
DEFINE INPUT PARAMETER dnr AS INTEGER NO-UNDO.
DEFINE INPUT PARAMETER gfor AS CHARACTER NO-UNDO.

FIND FIRST PERSONALTAB WHERE PERSONALTAB.PERSONALKOD = pkod NO-LOCK NO-ERROR.
IF anr = "110" AND dnr = 0 THEN DO TRANSACTION:      
   IF gfor = "gran" THEN DO:   
      FIND FIRST MEDDELANDE WHERE MEDDELANDE.SANDARE = "SJUKDOM" AND 
      MEDDELANDE.MOTTAGARE = "MARIEL" AND MEDDELANDE.EMOTAGET = FALSE EXCLUSIVE-LOCK NO-ERROR.
      IF NOT AVAILABLE MEDDELANDE THEN DO:
         CREATE MEDDELANDE.
         ASSIGN               
         MEDDELANDE.SANDARE = "SJUKDOM"
         MEDDELANDE.EMOTAGET = FALSE
         MEDDELANDE.MOTTAGARE = "MARIEL"
         MEDDELANDE.SDATUM = TODAY.
         MEDDELANDE.MEDD = "Personer som tidskrivit på sjukdom:" + CHR(10).        
         MEDDELANDE.MEDD = MEDDELANDE.MEDD  + pkod + " " + STRING(hjdat) + " " + STRING(hjstart)+ "-" + STRING(hjslut) + CHR(10).
      END.
      ELSE DO:
         MEDDELANDE.MEDD = MEDDELANDE.MEDD  + pkod + " " + STRING(hjdat) + " " + STRING(hjstart)+ "-" + STRING(hjslut) + CHR(10).
      END.   
   END.
   ELSE IF gfor = "elpa" THEN DO:   
      FIND FIRST MEDDELANDE WHERE MEDDELANDE.SANDARE = "SJUKDOM" AND 
      MEDDELANDE.MOTTAGARE = "rofo" AND MEDDELANDE.EMOTAGET = FALSE EXCLUSIVE-LOCK NO-ERROR.
      IF NOT AVAILABLE MEDDELANDE THEN DO:
         CREATE MEDDELANDE.
         ASSIGN               
         MEDDELANDE.SANDARE = "SJUKDOM"
         MEDDELANDE.EMOTAGET = FALSE
         MEDDELANDE.MOTTAGARE = "rofo"
         MEDDELANDE.SDATUM = TODAY.
         MEDDELANDE.MEDD = "Personer som tidskrivit på sjukdom:" + CHR(10).        
         MEDDELANDE.MEDD = MEDDELANDE.MEDD  + pkod + " " + STRING(hjdat) + " " + STRING(hjstart)+ "-" + STRING(hjslut) + CHR(10).
      END.
      ELSE DO:
         MEDDELANDE.MEDD = MEDDELANDE.MEDD  + pkod + " " + STRING(hjdat) + " " + STRING(hjstart)+ "-" + STRING(hjslut) + CHR(10).
      END.
   END.
END.
