/*SPECMTRLG1.I*/
DEFINE {&NEW} SHARED TEMP-TABLE spec_mtrl 
    FIELD KALKNR AS INTEGER
    FIELD ENR AS CHARACTER
    FIELD BENAMNING AS CHARACTER
    FIELD ENHET AS CHARACTER
    FIELD NPRIS AS DECIMAL 
    FIELD BPRIS AS DECIMAL
    FIELD SUMMA AS DECIMAL
    FIELD BERKVANT AS DECIMAL    
    FIELD LEVKOD AS CHARACTER
    FIELD MARK AS LOGICAL. 
DEFINE TEMP-TABLE espec_mtrl NO-UNDO LIKE spec_mtrl.
