/*STEG5.P*/
{AMERICANEUROPEAN.I}
DEFINE BUFFER MBUFF FOR MTRLDEP.
OPEN QUERY IQ FOR EACH MTRLDEP WHERE MTRLDEP.IBDATUM = 09/15/06 AND MTRLDEP.INVDATUM NE ? NO-LOCK.
DO TRANSACTION:
   GET FIRST IQ EXCLUSIVE-LOCK.
   FIND FIRST MBUFF WHERE MBUFF.IBDATUM = ? AND MBUFF.ENR = MTRLDEP.ENR NO-LOCK NO-ERROR.
   IF AVAILABLE MBUFF THEN DO:
      ASSIGN
      MTRLDEP.NPRIS = MBUFF.NPRIS
      MTRLDEP.BPRIS = MBUFF.BPRIS.
   END.
END.
REPEAT :
   DO TRANSACTION:
      GET NEXT IQ EXCLUSIVE-LOCK.
      IF AVAILABLE MTRLDEP THEN DO:
         FIND FIRST MBUFF WHERE MBUFF.IBDATUM = ? AND MBUFF.ENR = MTRLDEP.ENR NO-LOCK NO-ERROR.
         IF AVAILABLE MBUFF THEN DO:
            ASSIGN
            MTRLDEP.NPRIS = MBUFF.NPRIS
            MTRLDEP.BPRIS = MBUFF.BPRIS.
         END.
      END.
      ELSE LEAVE.
   END.
END. 

OUTPUT TO D:\ELPOOL\DELAD\PRO9\koll.txt APPEND.
PUT "Speckörning klart. " SKIP.
OUTPUT CLOSE.
{EUROPEANAMERICAN.I}