/*SUNDKALK.p*/
OPEN QUERY FQ FOR EACH FASTSPEC NO-LOCK.
GET FIRST FQ NO-LOCK.
DO WHILE AVAILABLE(FASTSPEC):
   IF FASTSPEC.KALKNR NE 0 THEN DO:
      OPEN QUERY KQ FOR EACH FASTKALK WHERE FASTKALK.KALKNR = FASTSPEC.KALKNR
      NO-LOCK.
      DO TRANSACTION:
         GET FIRST KQ EXCLUSIVE-LOCK.
         IF AVAILABLE FASTKALK THEN DO:
            FASTKALK.OMRADE = FASTSPEC.OMRADE.
         END.
      END.
      REPEAT:
         DO TRANSACTION:
            GET NEXT KQ EXCLUSIVE-LOCK.
            IF AVAILABLE FASTKALK THEN DO:
               FASTKALK.OMRADE = FASTSPEC.OMRADE.
            END.
            ELSE LEAVE.
         END.
      END.
      OPEN QUERY SQ FOR EACH FAKTOR WHERE FAKTOR.KALKNR = FASTSPEC.KALKNR
      NO-LOCK.
      DO TRANSACTION:
         GET FIRST SQ EXCLUSIVE-LOCK.
         IF AVAILABLE FAKTOR THEN DO:
            FAKTOR.OMRADE = FASTSPEC.OMRADE.
         END.
      END.
      REPEAT:
         DO TRANSACTION:
            GET NEXT SQ EXCLUSIVE-LOCK.
            IF AVAILABLE FAKTOR THEN DO:
               FAKTOR.OMRADE = FASTSPEC.OMRADE.
            END.
            ELSE LEAVE.
         END.
      END.
      OPEN QUERY PQ FOR EACH KALKBEF WHERE KALKBEF.KALKNR = FASTSPEC.KALKNR
      NO-LOCK.
      DO TRANSACTION:
         GET FIRST PQ EXCLUSIVE-LOCK.
         IF AVAILABLE KALKBEF THEN DO:
            KALKBEF.OMRADE = FASTSPEC.OMRADE.
         END.
      END.
      REPEAT:
         DO TRANSACTION:
            GET NEXT PQ EXCLUSIVE-LOCK.
            IF AVAILABLE KALKBEF THEN DO:
               KALKBEF.OMRADE = FASTSPEC.OMRADE.
            END.
            ELSE LEAVE.
         END.
      END.
   END.
   GET NEXT FQ NO-LOCK.
END.
