/* TIDGODE.P ENDAST FÖR EJAUREG KOLL OM GODKÄND DENNA VECKA. */
DEFINE SHARED VARIABLE gvisatidpermanad AS LOGICAL NO-UNDO.
DEFINE SHARED VARIABLE regvnr AS INTEGER FORMAT "999" NO-UNDO.
DEFINE SHARED VARIABLE persrec AS RECID NO-UNDO. 
DEFINE SHARED VARIABLE musz AS LOGICAL NO-UNDO.   
DEFINE SHARED VARIABLE regdatum AS DATE NO-UNDO.

FIND PERSONALTAB WHERE RECID(PERSONALTAB) = persrec NO-LOCK NO-ERROR.
IF gvisatidpermanad = TRUE THEN DO:
   FIND FIRST GODKOLL WHERE GODKOLL.PERSONALKOD = PERSONALTAB.PERSONALKOD AND
   GODKOLL.DATAR = YEAR(regdatum) AND GODKOLL.DATMAN = MONTH(regdatum) 
   USE-INDEX PKODAR NO-LOCK NO-ERROR.
   IF NOT AVAILABLE GODKOLL THEN DO:
      musz = FALSE.
      RETURN.
   END.
   ELSE DO:        
      IF GODKOLL.DATUM < regdatum THEN DO:
         musz = FALSE.
         RETURN.
      END.
      ELSE DO:
         musz = TRUE.
         RETURN.
      END.
   END.
END.
ELSE DO:
   FIND FIRST TIDREGITAB WHERE 
   TIDREGITAB.PERSONALKOD = PERSONALTAB.PERSONALKOD AND
   TIDREGITAB.VECKONUMMER = regvnr USE-INDEX PVNR NO-LOCK NO-ERROR.
   IF NOT AVAILABLE TIDREGITAB THEN DO:
      musz = FALSE.
      RETURN.
   END.
   ELSE DO:        
      IF TIDREGITAB.GODKAND = "" THEN DO:
         musz = FALSE.
         RETURN.
      END.
      ELSE DO:
         musz = TRUE.
         RETURN.
      END.
   END.
END.
