/*UPPPRISLULE.P INLÄSNING AV SEMIKOLONFIL FÖR IMPORT AV KONSTRUKTION*/       
DEFINE NEW SHARED VARIABLE quotervar AS CHARACTER FORMAT "X(256)" NO-UNDO.





DEFINE VARIABLE musz AS LOGICAL NO-UNDO.

DEFINE VARIABLE rad AS INTEGER NO-UNDO.
DEFINE VARIABLE prognamn AS CHARACTER FORMAT "X(20)" NO-UNDO.
DEFINE VARIABLE prognamndat AS CHARACTER FORMAT "X(20)" NO-UNDO.
DEFINE VARIABLE prognamnque AS CHARACTER FORMAT "X(20)" NO-UNDO.                
DEFINE VARIABLE words AS CHARACTER FORMAT "X(132)" NO-UNDO.
DEFINE VARIABLE kommando AS CHARACTER FORMAT "X(132)" NO-UNDO.
DEFINE VARIABLE kommandoprog AS CHARACTER FORMAT "X(20)" NO-UNDO.
DEFINE VARIABLE satsvar AS CHARACTER FORMAT "X(11)" NO-UNDO.
DEFINE VARIABLE enrvar AS CHARACTER FORMAT "X(11)" NO-UNDO.
DEFINE VARIABLE melvar AS INTEGER NO-UNDO.
DEFINE VARIABLE melvar2 AS INTEGER NO-UNDO.
DEFINE VARIABLE langd AS INTEGER NO-UNDO.
DEFINE VARIABLE pos1 AS INTEGER NO-UNDO. 
DEFINE VARIABLE svar AS LOGICAL NO-UNDO.
DEFINE VARIABLE var2 AS CHARACTER NO-UNDO.


DEFINE TEMP-TABLE tidin   
   FIELD ENR                AS CHARACTER 
   FIELD BENAMNING          AS CHARACTER    
   FIELD NPRIS              AS DECIMAL.   
   

DEFINE TEMP-TABLE infil
   FIELD PROGNAMN AS CHARACTER FORMAT "X(78)" 
   INDEX PRO IS PRIMARY PROGNAMN.
DEFINE TEMP-TABLE intid
   FIELD TIN AS CHARACTER FORMAT "X(78)" .
   
DEFINE VARIABLE filnamn AS CHARACTER NO-UNDO.   
DEFINE VARIABLE leverant AS CHARACTER NO-UNDO.   
{muswait.i}    
{AMERICANEUROPEAN.I}  
   EMPTY TEMP-TABLE intid NO-ERROR. 
   EMPTY TEMP-TABLE tidin NO-ERROR.    
   filnamn = "D:\ELPOOL\DELAD\PRO9\AHLSELLVERKTYG.skv".
   /*filnamn = "C:\AHLSELLVERKTYG.skv".*/
   INPUT FROM VALUE(filnamn) NO-ECHO.
   REPEAT:
      DO TRANSACTION: 
         CREATE tidin.
         ASSIGN.
         IMPORT DELIMITER ";" tidin   NO-ERROR.
      END.               
   END.
   /*FOR EACH TIDIN:                                                                     
       MESSAGE TIDIN.ENR TIDIN.F1 TIDIN.F2 TIDIN.NPRIS.
   END.*/                                                                                
   FOR EACH tidin WHERE tidin.ENR = "":
      DELETE tidin.
   END.     
   RUN skapaenr_UI.
/*    OS-DELETE VALUE(wtidvar). */

{EUROPEANAMERICAN.I}
PROCEDURE skapaenr_UI:         
    FOR EACH tidin:    
       FIND FIRST MTRL WHERE MTRL.ENR = tidin.ENR AND MTRL.LEVKOD = "5" AND
       MTRL.KALKNR = 0 NO-LOCK NO-ERROR.
       IF NOT AVAILABLE MTRL THEN DO TRANSACTION:
          CREATE MTRL.
          ASSIGN
          MTRL.ENR = tidin.ENR
          MTRL.BENAMNING = tidin.BENAMNING
          MTRL.ENHET = "ST"
          MTRL.KALKNR = 0
          MTRL.LEVKOD = "4"
          MTRL.NPRIS = tidin.NPRIS / 100
          MTRL.BPRIS = tidin.NPRIS / 100.
          {MTRLCREATE.I} 
       END.
    END.
END PROCEDURE.   

                
