 /*VATTVE1.P*/
/*UNIX VERSION KOMMUN*/
/* skapar filen pa90hj som är veckans körning .Denna lägges till pa90veck.d*/
/*SKAPAR FILEN PA90VECK.P */
/*ALLA TILLÄGG SOM EKONOMI- OCH LÖNESAMMANSTÄLLS FÅR EN EGEN RAD I DENNA RAPPORT*/
/*RAPPORTEN LIGGER TILL GRUND FÖR MÅNADSKÖRNIING */
DEFINE INPUT PARAMETER kordatum AS DATE NO-UNDO.
DEFINE INPUT PARAMETER koranv LIKE ANVANDARE.ANVANDARE NO-UNDO.
DEFINE NEW SHARED VARIABLE fnytid AS DECIMAL FORMAT "-99.99" NO-UNDO.
DEFINE NEW SHARED VARIABLE vkdatum AS DATE NO-UNDO.
DEFINE NEW SHARED VARIABLE regvnr AS INTEGER FORMAT "999" NO-UNDO.     
DEFINE NEW SHARED VARIABLE regdatum AS DATE NO-UNDO.
DEFINE NEW SHARED VARIABLE regstart LIKE TIDREGITAB.START NO-UNDO. 
DEFINE NEW SHARED VARIABLE regslut LIKE TIDREGITAB.SLUT NO-UNDO.
DEFINE NEW SHARED VARIABLE persrec AS RECID NO-UNDO.
/*DEFINE NEW SHARED VARIABLE globanv LIKE ANVANDARE.ANVANDARE NO-UNDO.*/

DEFINE NEW SHARED VARIABLE regdagnamn AS CHARACTER FORMAT "X(3)" NO-UNDO.        
DEFINE NEW SHARED VARIABLE regtotalt LIKE TIDREGITAB.TOTALT NO-UNDO.
DEFINE NEW SHARED VARIABLE frustarten AS DECIMAL NO-UNDO.
DEFINE NEW SHARED VARIABLE fruslutet AS DECIMAL NO-UNDO.
DEFINE NEW SHARED VARIABLE kaffestart AS DECIMAL NO-UNDO.
DEFINE NEW SHARED VARIABLE kaffeslut AS DECIMAL NO-UNDO.
DEFINE NEW SHARED VARIABLE lunchstarten AS DECIMAL NO-UNDO.
DEFINE NEW SHARED VARIABLE lunchslutet AS DECIMAL NO-UNDO.
DEFINE NEW SHARED VARIABLE nytid AS DECIMAL FORMAT "99.99" NO-UNDO.
DEFINE NEW SHARED VARIABLE sekunder AS INTEGER NO-UNDO.    

DEFINE VARIABLE antal LIKE TIDREGITAB.LONTILLANTAL NO-UNDO.   /*LÖN*/
DEFINE VARIABLE antalet LIKE PHJALP.PPAR8 NO-UNDO.   /*LÖN*/
DEFINE VARIABLE personal LIKE PERSONALTAB.PERSONALKOD.      /*LÖN*/
DEFINE VARIABLE pnr LIKE PERSONALTAB.PERSONNUMMER.      /*LÖN*/
DEFINE VARIABLE vecknr LIKE TIDREGITAB.VECKONUMMER.      /*LÖN*/
DEFINE VARIABLE overrapp1 AS CHARACTER FORMAT "X(70)".      /*LÖN*/
DEFINE VARIABLE overrapp2 AS CHARACTER FORMAT "X(70)".      /*ÖVERTID*/
DEFINE VARIABLE overrapp3 AS CHARACTER FORMAT "X(70)".      /*BEREEDSKAP*/
DEFINE VARIABLE overrapp4 AS CHARACTER FORMAT "X(70)".      /*TRAKTAMENTE*/
DEFINE VARIABLE rapphj1 AS CHARACTER FORMAT "X(9)".      /*HJÄLP ANTAL*/
DEFINE VARIABLE rapphj2 AS CHARACTER FORMAT "X(11)".      /*HJÄLP belopp*/
DEFINE VARIABLE datrapphj1 AS DATE FORMAT "999999".      /*HJÄLP datum*/
DEFINE VARIABLE rec AS RECID.
DEFINE VARIABLE para AS LOGICAL NO-UNDO.
DEFINE VARIABLE avtal1 LIKE PERSONALTAB.ANSTALLNING NO-UNDO.
DEFINE VARIABLE avtal LIKE ANSTFORMTAB.KOD NO-UNDO.  
DEFINE VARIABLE oversum AS INTEGER NO-UNDO. 
DEFINE VARIABLE total AS INTEGER NO-UNDO.
DEFINE VARIABLE oa1 AS INTEGER NO-UNDO.
DEFINE VARIABLE oa2 AS INTEGER NO-UNDO.
DEFINE VARIABLE oa3 AS INTEGER NO-UNDO.
DEFINE VARIABLE t2 AS INTEGER NO-UNDO.
DEFINE VARIABLE t3 AS INTEGER NO-UNDO.
DEFINE VARIABLE bryt AS LOGICAL NO-UNDO.
DEFINE VARIABLE nod AS LOGICAL NO-UNDO.
DEFINE VARIABLE seku AS INTEGER NO-UNDO.
DEFINE NEW SHARED TEMP-TABLE pa90fil
   FIELD PPERSONNUMMER LIKE PERSONALTAB.PERSONNUMMER
   FIELD PLONTILLAGG LIKE TIDREGITAB.LONTILLAGG
   FIELD PLONTILLANTAL LIKE TIDREGITAB.LONTILLANTAL
   FIELD POVERTIDTILL LIKE TIDREGITAB.OVERTIDTILL
   FIELD POVERANTAL LIKE TIDREGITAB.OVERANTAL
   FIELD PTRAKTKOD LIKE TIDREGITAB.TRAKTKOD
   FIELD PTRAKTANTAL LIKE TIDREGITAB.TRAKTANTAL
   FIELD PBEREDSKAP LIKE TIDREGITAB.BEREDSKAP
   FIELD PBERANTAL LIKE TIDREGITAB.BERANTAL
   FIELD PDATUM LIKE TIDREGITAB.DATUM
   FIELD PVECKONUMMER LIKE TIDREGITAB.VECKONUMMER
   FIELD MANAD AS INTEGER
   FIELD PSORT AS CHARACTER FORMAT "XX"
   FIELD PPAR8 AS DECIMAL FORMAT "-99.99"
   FIELD PANSTNR LIKE PERSONALTAB.ANSTNR
   FIELD AONR LIKE TIDREGITAB.AONR
   FIELD DELNR LIKE TIDREGITAB.DELNR
   FIELD PAVTAL AS CHARACTER
   INDEX PPERSONNUMMER IS PRIMARY PPERSONNUMMER ASCENDING.
{AMERICANEUROPEAN.I}   
FOR EACH pa90fil:
  DELETE pa90fil.
END.
FIND FIRST FORETAG USE-INDEX FORETAG NO-LOCK NO-ERROR.
Guru.Konstanter:globforetag = FORETAG.FORETAG.
vkdatum = kordatum.
OPEN QUERY pq FOR EACH PERSONALTAB WHERE PERSONALTAB.PERSMASK = TRUE
USE-INDEX PERSONALKOD NO-LOCK.
GET FIRST pq NO-LOCK.
DO WHILE AVAILABLE(PERSONALTAB):
   personal = PERSONALTAB.PERSONALKOD.
   avtal1 = PERSONALTAB.ANSTALLNING.
   FIND FIRST ANSTFORMTAB WHERE ANSTFORMTAB.ANSTALLNING = avtal1
   USE-INDEX ANSTF NO-LOCK NO-ERROR.
   avtal = ANSTFORMTAB.KOD.
   FIND FIRST UTRYCKNING WHERE UTRYCKNING.KOD = avtal USE-INDEX UT
   NO-LOCK NO-ERROR.
   IF NOT AVAILABLE UTRYCKNING THEN para = FALSE.
   ELSE para = UTRYCKNING.PARA8.
   OPEN QUERY tq FOR EACH TIDREGITAB WHERE
   TIDREGITAB.PERSONALKOD = PERSONALTAB.PERSONALKOD AND
   TIDREGITAB.GODKAND BEGINS "G" AND TIDREGITAB.VECKOKORD = "" AND
   TIDREGITAB.DATUM <= vkdatum
   USE-INDEX PSTART NO-LOCK.   
   GET FIRST tq NO-LOCK.
   DO WHILE AVAILABLE(TIDREGITAB):
      IF (TIDREGITAB.TRAKTKOD = " "  OR TIDREGITAB.TRAKTANTAL = 0) AND
      (TIDREGITAB.LONTILLAGG = " "  OR TIDREGITAB.LONTILLANTAL = 0) AND
      (TIDREGITAB.OKOD1 = " " OR TIDREGITAB.OANT1 = 0) AND
      (TIDREGITAB.OKOD2 = " " OR TIDREGITAB.OANT2 = 0) AND
      (TIDREGITAB.OKOD3 = " " OR TIDREGITAB.OANT3 = 0) AND
      (TIDREGITAB.BEREDSKAP = " " OR TIDREGITAB.BERANTAL = 0)
      THEN DO:         
         /*IF PERSONALTAB.BEFATTNING = "TIMANSTÄLLD" AND TIDREGITAB.TOTALT > 0 THEN DO:                                                                     
	     IF TIDREGITAB.PRISTYP = "FRÅNVARO." THEN nytid = nytid.
	     ELSE DO:
	        CREATE pa90fil.
	        ASSIGN pa90fil.PPERSONNUMMER = PERSONALTAB.PERSONNUMMER
	        pa90fil.PLONTILLAGG = "010"
	        pa90fil.PLONTILLANTAL = TIDREGITAB.TOTALT
	        pa90fil.PDATUM = TIDREGITAB.DATUM
	        pa90fil.PVECKONUMMER = TIDREGITAB.VECKONUMMER
	        pa90fil.AONR = TIDREGITAB.AONR
	        pa90fil.DELNR = TIDREGITAB.DELNR
	        pa90fil.MANAD = MONTH(TIDREGITAB.DATUM)
	        pa90fil.PAVTAL = avtal.
	     END.   
	  END.
         ELSE IF PERSONALTAB.BEFATTNING = "TIMANS.+SEM TJ" AND TIDREGITAB.TOTALT > 0 THEN DO:                                                                     
	     IF TIDREGITAB.PRISTYP = "FRÅNVARO." THEN nytid = nytid.
	     ELSE DO:
	        CREATE pa90fil.  /* VILART = 011*/
	        ASSIGN pa90fil.PPERSONNUMMER = PERSONALTAB.PERSONNUMMER
	        pa90fil.PLONTILLAGG = "040"
	        pa90fil.PLONTILLANTAL = TIDREGITAB.TOTALT
	        pa90fil.PDATUM = TIDREGITAB.DATUM
	        pa90fil.PVECKONUMMER = TIDREGITAB.VECKONUMMER
	        pa90fil.AONR = TIDREGITAB.AONR
	        pa90fil.DELNR = TIDREGITAB.DELNR
	        pa90fil.MANAD = MONTH(TIDREGITAB.DATUM)
	        pa90fil.PAVTAL = avtal.
	     END.   
	  END.
         ELSE IF PERSONALTAB.BEFATTNING = "TIMANS.+SEM KOLL" AND TIDREGITAB.TOTALT > 0 THEN DO:                                                                     
	     IF TIDREGITAB.PRISTYP = "FRÅNVARO." THEN nytid = nytid.
	     ELSE DO:
	        CREATE pa90fil.  /* VILART = 011*/
	        ASSIGN pa90fil.PPERSONNUMMER = PERSONALTAB.PERSONNUMMER
	        pa90fil.PLONTILLAGG = "030"
	        pa90fil.PLONTILLANTAL = TIDREGITAB.TOTALT
	        pa90fil.PDATUM = TIDREGITAB.DATUM
	        pa90fil.PVECKONUMMER = TIDREGITAB.VECKONUMMER
	        pa90fil.AONR = TIDREGITAB.AONR
	        pa90fil.DELNR = TIDREGITAB.DELNR
	        pa90fil.MANAD = MONTH(TIDREGITAB.DATUM)
	        pa90fil.PAVTAL = avtal.
	     END.   
	  END.*/
	  /* om flextid skall räknas ut*/ 
      END.
      ELSE DO :    
	  IF TIDREGITAB.LONTILLAGG NE " " AND TIDREGITAB.LONTILLANTAL NE 0 THEN DO TRANSACTION:
	     CREATE pa90fil.
	     ASSIGN pa90fil.PPERSONNUMMER = PERSONALTAB.PERSONNUMMER
	     pa90fil.PLONTILLAGG = TIDREGITAB.LONTILLAGG
	     pa90fil.PLONTILLANTAL = TIDREGITAB.LONTILLANTAL
	     pa90fil.PDATUM = TIDREGITAB.DATUM
	     pa90fil.PVECKONUMMER = TIDREGITAB.VECKONUMMER
	     pa90fil.AONR = TIDREGITAB.AONR
            pa90fil.DELNR = TIDREGITAB.DELNR
            pa90fil.MANAD = MONTH(TIDREGITAB.DATUM)
            pa90fil.PAVTAL = avtal.
	  END.          
         IF TIDREGITAB.OANT1 NE 0 OR TIDREGITAB.OANT2 NE 0 OR TIDREGITAB.OANT3 NE 0
	  THEN DO TRANSACTION:                                                      
	     nytid = TIDREGITAB.OANT1.
	     RUN TIMSEK.P.
	     oa1 = sekunder.  
	     nytid = TIDREGITAB.OANT2.
	     RUN TIMSEK.P. 
	     oa2 = sekunder.
	     oversum = oa1 + sekunder.
	     nytid = TIDREGITAB.OANT3.
	     RUN TIMSEK.P.
	     oa3 = sekunder.
	     oversum = oversum + sekunder.
	     nytid = TIDREGITAB.TOTALT.
	     RUN TIMSEK.P.
	     total = sekunder.  
	     IF TIDREGITAB.OVERAUTO = FALSE OR TIDREGITAB.UTRYCKNING = FALSE OR
            oversum LE total THEN DO:                                               
	        IF OKOD1 NE "" THEN DO:
	           CREATE pa90fil.
	           ASSIGN pa90fil.PPERSONNUMMER = PERSONALTAB.PERSONNUMMER
	           pa90fil.POVERTIDTILL = TIDREGITAB.OKOD1
	           pa90fil.POVERANTAL = TIDREGITAB.OANT1
	           pa90fil.PDATUM = TIDREGITAB.DATUM
	           pa90fil.PVECKONUMMER = TIDREGITAB.VECKONUMMER
	           pa90fil.AONR = TIDREGITAB.AONR
                  pa90fil.DELNR = TIDREGITAB.DELNR
                  pa90fil.MANAD = MONTH(TIDREGITAB.DATUM)
                  pa90fil.PAVTAL = avtal.
	        END.    
	        IF OKOD2 NE "" THEN DO:
	           CREATE pa90fil.
	           ASSIGN pa90fil.PPERSONNUMMER = PERSONALTAB.PERSONNUMMER
	           pa90fil.POVERTIDTILL = TIDREGITAB.OKOD2
	           pa90fil.POVERANTAL = TIDREGITAB.OANT2
	           pa90fil.PDATUM = TIDREGITAB.DATUM
	           pa90fil.PVECKONUMMER = TIDREGITAB.VECKONUMMER
	           pa90fil.AONR = TIDREGITAB.AONR
	           pa90fil.DELNR = TIDREGITAB.DELNR
	           pa90fil.MANAD = MONTH(TIDREGITAB.DATUM)
	           pa90fil.PAVTAL = avtal.
	           
	        END.   
	        IF OKOD3 NE "" THEN DO:
	           CREATE pa90fil.
	           ASSIGN pa90fil.PPERSONNUMMER = PERSONALTAB.PERSONNUMMER
	           pa90fil.POVERTIDTILL = TIDREGITAB.OKOD3
	           pa90fil.POVERANTAL = TIDREGITAB.OANT3
	           pa90fil.PDATUM = TIDREGITAB.DATUM
	           pa90fil.PVECKONUMMER = TIDREGITAB.VECKONUMMER
	           pa90fil.AONR = TIDREGITAB.AONR
	           pa90fil.DELNR = TIDREGITAB.DELNR
	           pa90fil.MANAD = MONTH(TIDREGITAB.DATUM)
	           pa90fil.PAVTAL = avtal.
	        END.                                    
	     END.     
            ELSE IF oversum > total AND TIDREGITAB.OVERAUTO = TRUE
            AND TIDREGITAB.UTRYCKNING = TRUE THEN DO:                            
	        nod = FALSE.
	        IF TIDREGITAB.OANT3 > 0 THEN DO:
	           oversum = oversum - oa3.
	           IF oversum > total THEN DO:	  
                     CREATE pa90fil.
	              ASSIGN pa90fil.PPERSONNUMMER = PERSONALTAB.PERSONNUMMER
	              pa90fil.POVERTIDTILL = TIDREGITAB.OKOD3
	              pa90fil.POVERANTAL = TIDREGITAB.OANT3
	              pa90fil.PDATUM = TIDREGITAB.DATUM
	              pa90fil.PVECKONUMMER = TIDREGITAB.VECKONUMMER
	              pa90fil.AONR = TIDREGITAB.AONR
                     pa90fil.DELNR = TIDREGITAB.DELNR
                     pa90fil.MANAD = MONTH(TIDREGITAB.DATUM)
                     pa90fil.PAVTAL = avtal.
	              CREATE pa90fil.
	              ASSIGN pa90fil.PPERSONNUMMER = PERSONALTAB.PERSONNUMMER
	              pa90fil.POVERTIDTILL = "9008"
	              pa90fil.POVERANTAL = TIDREGITAB.OANT3
	              pa90fil.PDATUM = TIDREGITAB.DATUM
	              pa90fil.PVECKONUMMER = TIDREGITAB.VECKONUMMER
	              pa90fil.AONR = TIDREGITAB.AONR
                     pa90fil.DELNR = TIDREGITAB.DELNR
                     pa90fil.MANAD = MONTH(TIDREGITAB.DATUM)
                     pa90fil.PAVTAL = avtal.
	           END.
	           ELSE DO:
	              t2 = total - oa1 - oa2. 
	              sekunder = t2.
	              RUN SEKTIM.P.	             
	              CREATE pa90fil.
	              ASSIGN pa90fil.PPERSONNUMMER = PERSONALTAB.PERSONNUMMER
	              pa90fil.POVERTIDTILL = TIDREGITAB.OKOD3
	              pa90fil.POVERANTAL = TIDREGITAB.OANT3
	              pa90fil.PDATUM = TIDREGITAB.DATUM
	              pa90fil.PVECKONUMMER = TIDREGITAB.VECKONUMMER
	              pa90fil.AONR = TIDREGITAB.AONR
	              pa90fil.DELNR = TIDREGITAB.DELNR
	              pa90fil.MANAD = MONTH(TIDREGITAB.DATUM)
	              pa90fil.PAVTAL = avtal.
	              t3 = oa3 - t2.
	              sekunder = t3.
	              RUN SEKTIM.P.	                      
	              CREATE pa90fil.
	              ASSIGN pa90fil.PPERSONNUMMER = PERSONALTAB.PERSONNUMMER
	              pa90fil.POVERTIDTILL = "9008"
	              pa90fil.POVERANTAL = nytid
	              pa90fil.PDATUM = TIDREGITAB.DATUM
	              pa90fil.PVECKONUMMER = TIDREGITAB.VECKONUMMER
	              pa90fil.AONR = TIDREGITAB.AONR
 	              pa90fil.DELNR = TIDREGITAB.DELNR
 	              pa90fil.MANAD = MONTH(TIDREGITAB.DATUM)
 	              pa90fil.PAVTAL = avtal.
	              bryt = TRUE.   
	           END.
	        END.
	        IF TIDREGITAB.OANT2 > 0 THEN DO:
	           oversum = oversum - oa2.
	           IF oversum > total THEN DO:
	              CREATE pa90fil.
	              ASSIGN pa90fil.PPERSONNUMMER = PERSONALTAB.PERSONNUMMER
	              pa90fil.POVERTIDTILL = TIDREGITAB.OKOD2
	              pa90fil.POVERANTAL = TIDREGITAB.OANT2
	              pa90fil.PDATUM = TIDREGITAB.DATUM
	              pa90fil.PVECKONUMMER = TIDREGITAB.VECKONUMMER
	              pa90fil.AONR = TIDREGITAB.AONR
	              pa90fil.DELNR = TIDREGITAB.DELNR
	              pa90fil.MANAD = MONTH(TIDREGITAB.DATUM)
	              pa90fil.PAVTAL = avtal.
	              CREATE pa90fil.
	              ASSIGN pa90fil.PPERSONNUMMER = PERSONALTAB.PERSONNUMMER
	              pa90fil.POVERTIDTILL = "9008"
	              pa90fil.POVERANTAL = TIDREGITAB.OANT2
	              pa90fil.PDATUM = TIDREGITAB.DATUM
	              pa90fil.PVECKONUMMER = TIDREGITAB.VECKONUMMER
	              pa90fil.AONR = TIDREGITAB.AONR
	              pa90fil.DELNR = TIDREGITAB.DELNR
	              pa90fil.MANAD = MONTH(TIDREGITAB.DATUM)
	              pa90fil.PAVTAL = avtal.
	           END.
	           ELSE IF bryt = TRUE THEN DO:
	              CREATE pa90fil.
	              ASSIGN pa90fil.PPERSONNUMMER = PERSONALTAB.PERSONNUMMER
	              pa90fil.POVERTIDTILL = TIDREGITAB.OKOD2
	              pa90fil.POVERANTAL = TIDREGITAB.OANT2
	              pa90fil.PDATUM = TIDREGITAB.DATUM
	              pa90fil.PVECKONUMMER = TIDREGITAB.VECKONUMMER
	              pa90fil.AONR = TIDREGITAB.AONR
                     pa90fil.DELNR = TIDREGITAB.DELNR
                     pa90fil.MANAD = MONTH(TIDREGITAB.DATUM)
                     pa90fil.PAVTAL = avtal.
	           END.                                      
	           ELSE DO:
	              t2 = total - oa1. 
	              sekunder = t2.
	              RUN SEKTIM.P.
	              CREATE pa90fil.
	              ASSIGN pa90fil.PPERSONNUMMER = PERSONALTAB.PERSONNUMMER
	              pa90fil.POVERTIDTILL = TIDREGITAB.OKOD2
	              pa90fil.POVERANTAL = TIDREGITAB.OANT2
	              pa90fil.PDATUM = TIDREGITAB.DATUM
	              pa90fil.PVECKONUMMER = TIDREGITAB.VECKONUMMER
	              pa90fil.AONR = TIDREGITAB.AONR
	              pa90fil.DELNR = TIDREGITAB.DELNR
	              pa90fil.MANAD = MONTH(TIDREGITAB.DATUM)
	              pa90fil.PAVTAL = avtal.
	              t3 = oa2 - t2.
	              sekunder = t3.
	              RUN SEKTIM.P.	                    
	              CREATE pa90fil.
	              ASSIGN pa90fil.PPERSONNUMMER = PERSONALTAB.PERSONNUMMER   
     	              pa90fil.POVERTIDTILL = "9008"
	              pa90fil.POVERANTAL = nytid
	              pa90fil.PDATUM = TIDREGITAB.DATUM
	              pa90fil.PVECKONUMMER = TIDREGITAB.VECKONUMMER
	              pa90fil.AONR = TIDREGITAB.AONR
	              pa90fil.DELNR = TIDREGITAB.DELNR
	              pa90fil.MANAD = MONTH(TIDREGITAB.DATUM)
	              pa90fil.PAVTAL = avtal.    
	              bryt = TRUE.
	           END.
	        END.   
	        IF TIDREGITAB.OANT1 > 0 THEN DO:
	           IF bryt = TRUE THEN DO:
	              CREATE pa90fil.
	              ASSIGN pa90fil.PPERSONNUMMER = PERSONALTAB.PERSONNUMMER
	              pa90fil.POVERTIDTILL = TIDREGITAB.OKOD1
	              pa90fil.POVERANTAL = TIDREGITAB.OANT1
   	              pa90fil.PDATUM = TIDREGITAB.DATUM
	              pa90fil.PVECKONUMMER = TIDREGITAB.VECKONUMMER
	              pa90fil.AONR = TIDREGITAB.AONR
	              pa90fil.DELNR = TIDREGITAB.DELNR
	              pa90fil.MANAD = MONTH(TIDREGITAB.DATUM)
	              pa90fil.PAVTAL = avtal.
	           END .                                      
	           ELSE DO:
	              t3 = oa1 - total.
	              sekunder = t3.
	              RUN SEKTIM.P.
	              CREATE pa90fil.
	              ASSIGN pa90fil.PPERSONNUMMER = PERSONALTAB.PERSONNUMMER
	              pa90fil.POVERTIDTILL = TIDREGITAB.OKOD1
	              pa90fil.POVERANTAL = TIDREGITAB.OANT1
	              pa90fil.PDATUM = TIDREGITAB.DATUM  
	              pa90fil.PVECKONUMMER = TIDREGITAB.VECKONUMMER
	              pa90fil.AONR = TIDREGITAB.AONR
 	              pa90fil.DELNR = TIDREGITAB.DELNR
 	              pa90fil.MANAD = MONTH(TIDREGITAB.DATUM)
 	              pa90fil.PAVTAL = avtal. 	                   
	              CREATE pa90fil.
	              ASSIGN pa90fil.PPERSONNUMMER = PERSONALTAB.PERSONNUMMER
	              pa90fil.POVERTIDTILL = "9008"
	              pa90fil.POVERANTAL = nytid
	              pa90fil.PDATUM = TIDREGITAB.DATUM
	              pa90fil.PVECKONUMMER = TIDREGITAB.VECKONUMMER
	              pa90fil.AONR = TIDREGITAB.AONR
    	              pa90fil.DELNR = TIDREGITAB.DELNR
    	              pa90fil.MANAD = MONTH(TIDREGITAB.DATUM)
    	              pa90fil.PAVTAL = avtal.    
	           END.
	        END.                                     
	        bryt = FALSE.
	     END.	                                                 	     
         END.
         IF TIDREGITAB.TRAKTKOD NE " " AND TIDREGITAB.TRAKTANTAL NE 0
	  THEN DO TRANSACTION:
	     CREATE pa90fil.
	     ASSIGN pa90fil.PPERSONNUMMER = PERSONALTAB.PERSONNUMMER
	     pa90fil.PTRAKTKOD = TIDREGITAB.TRAKTKOD
	     pa90fil.PTRAKTANTAL = TIDREGITAB.TRAKTANTAL
	     pa90fil.PDATUM = TIDREGITAB.DATUM
	     pa90fil.PVECKONUMMER = TIDREGITAB.VECKONUMMER
	     pa90fil.AONR = TIDREGITAB.AONR
            pa90fil.DELNR = TIDREGITAB.DELNR
            pa90fil.MANAD = MONTH(TIDREGITAB.DATUM)
            pa90fil.PAVTAL = PERSONALTAB.TRAAVTAL.
	  END.
	  IF TIDREGITAB.BEREDSKAP NE " " AND TIDREGITAB.BERANTAL NE 0
	  THEN DO TRANSACTION:
	     CREATE pa90fil.
	     ASSIGN pa90fil.PPERSONNUMMER = PERSONALTAB.PERSONNUMMER
	     pa90fil.PBEREDSKAP = TIDREGITAB.BEREDSKAP
	     pa90fil.PBERANTAL = TIDREGITAB.BERANTAL
	     pa90fil.PDATUM = TIDREGITAB.DATUM
	     pa90fil.PVECKONUMMER = TIDREGITAB.VECKONUMMER
	     pa90fil.AONR = TIDREGITAB.AONR
            pa90fil.DELNR = TIDREGITAB.DELNR
            pa90fil.MANAD = MONTH(TIDREGITAB.DATUM)
            pa90fil.PAVTAL = PERSONALTAB.BEREDSKAPSAVTAL.
	  END.                    
	  /*IF PERSONALTAB.BEFATTNING = "TIMANSTÄLLD" AND TIDREGITAB.TOTALT > 0 THEN DO:
	     IF TIDREGITAB.PRISTYP = "FRÅNVARO." THEN nytid = nytid.
	     ELSE DO:
	        CREATE pa90fil.
	        ASSIGN pa90fil.PPERSONNUMMER = PERSONALTAB.PERSONNUMMER
	        pa90fil.PLONTILLAGG = "010"
	        pa90fil.PLONTILLANTAL = TIDREGITAB.TOTALT
	        pa90fil.PDATUM = TIDREGITAB.DATUM
	        pa90fil.PVECKONUMMER = TIDREGITAB.VECKONUMMER
	        pa90fil.AONR = TIDREGITAB.AONR
	        pa90fil.DELNR = TIDREGITAB.DELNR
	        pa90fil.MANAD = MONTH(TIDREGITAB.DATUM)
	        pa90fil.PAVTAL = avtal.
	     END.   
	  END.
	  ELSE IF PERSONALTAB.BEFATTNING = "TIMANS.+SEM TJ" AND TIDREGITAB.TOTALT > 0 THEN DO:                                                                     
	     IF TIDREGITAB.PRISTYP = "FRÅNVARO." THEN nytid = nytid.
	     ELSE DO:
	        CREATE pa90fil.  /* VILART = 011*/
	        ASSIGN pa90fil.PPERSONNUMMER = PERSONALTAB.PERSONNUMMER
	        pa90fil.PLONTILLAGG = "040"
	        pa90fil.PLONTILLANTAL = TIDREGITAB.TOTALT
	        pa90fil.PDATUM = TIDREGITAB.DATUM
	        pa90fil.PVECKONUMMER = TIDREGITAB.VECKONUMMER
	        pa90fil.AONR = TIDREGITAB.AONR
	        pa90fil.DELNR = TIDREGITAB.DELNR
	        pa90fil.MANAD = MONTH(TIDREGITAB.DATUM)
	        pa90fil.PAVTAL = avtal.
	     END.   
	  END.
         ELSE IF PERSONALTAB.BEFATTNING = "TIMANS.+SEM KOLL" AND TIDREGITAB.TOTALT > 0 THEN DO:                                                                     
	     IF TIDREGITAB.PRISTYP = "FRÅNVARO." THEN nytid = nytid.
	     ELSE DO:
	        CREATE pa90fil.  /*VILART = 011*/
	        ASSIGN pa90fil.PPERSONNUMMER = PERSONALTAB.PERSONNUMMER
	        pa90fil.PLONTILLAGG = "030"
	        pa90fil.PLONTILLANTAL = TIDREGITAB.TOTALT
	        pa90fil.PDATUM = TIDREGITAB.DATUM
	        pa90fil.PVECKONUMMER = TIDREGITAB.VECKONUMMER
	        pa90fil.AONR = TIDREGITAB.AONR
	        pa90fil.DELNR = TIDREGITAB.DELNR
	        pa90fil.MANAD = MONTH(TIDREGITAB.DATUM)
	        pa90fil.PAVTAL = avtal.
	     END.   
         END.       
         /* om flextid skall räknas ut*/*/
      END.
      GET NEXT tq.
   END.
   GET NEXT pq.
END.
FOR EACH pa90fil WHERE pa90fil.PPERSONNUMMER = " ":
  DELETE pa90fil.
END.

FOR EACH pa90fil where pa90fil.PLONTILLAGG NE "":
   FIND FIRST LONTILL WHERE LONTILL.LONTILLAGG = pa90fil.PLONTILLAGG
   AND LONTILL.KOD = pa90fil.PAVTAL USE-INDEX LON NO-LOCK NO-ERROR.
   IF AVAILABLE LONTILL THEN ASSIGN pa90fil.PLONTILLAGG = LONTILL.VILART.
END.
FOR EACH pa90fil where pa90fil.POVERTIDTILL NE "":
   FIND FIRST OVERKOD WHERE OVERKOD.OVERTIDTILL = pa90fil.POVERTIDTILL
   AND OVERKOD.KOD = pa90fil.PAVTAL USE-INDEX OVER NO-LOCK NO-ERROR.
   IF AVAILABLE OVERKOD THEN ASSIGN pa90fil.POVERTIDTILL = OVERKOD.VILART.
END.
FOR EACH pa90fil where pa90fil.PBEREDSKAP NE "":
   FIND FIRST BERKOD WHERE BERKOD.BEREDSKAP = pa90fil.PBEREDSKAP 
   AND BERKOD.BEREDSKAPSAVTAL = pa90fil.PAVTAL USE-INDEX BERE NO-LOCK NO-ERROR.
   IF AVAILABLE BERKOD THEN ASSIGN pa90fil.PBEREDSKAP = BERKOD.VILART.
END.
FOR EACH pa90fil where pa90fil.PTRAKTKOD NE "":
   FIND FIRST TRAKTATAB WHERE TRAKTATAB.TRAKTKOD = pa90fil.PTRAKTKOD
   AND TRAKTATAB.TRAAVTAL = pa90fil.PAVTAL USE-INDEX TRAAV NO-LOCK NO-ERROR.
   IF AVAILABLE TRAKTATAB THEN ASSIGN pa90fil.PTRAKTKOD = TRAKTATAB.VILART.
END.
if Guru.Konstanter:globforetag = "elpa" then DO:
   OUTPUT TO D:\delad\pro8\GURU\apptemp\pa90fil.d.
   for each pa90fil BY pa90fil.Ppersonnummer BY pa90fil.PLONTILLAGG:
     display pa90fil.
   end.  
END.
  
{EUROPEANAMERICAN.I}  
   
RUN VATTVE3.P.      /* summerar veckans skörd till tidigare */
