DEFINE BUFFER A FOR OVERKOD.
DEFINE BUFFER B FOR LONTILL.
DEFINE BUFFER C FOR OVERTIDTAB.
DEFINE BUFFER D FOR RESTIDTAB.
 
FOR EACH OVERKOD WHERE KOD = "T":
CREATE A.
ASSIGN
         
A.KOD = "L"
A.OVERTIDTILL = OVERKOD.OVERTIDTILL
A.VILART = OVERKOD.VILART
A.OVERTIDUTTAG = OVERKOD.OVERTIDUTTAG
A.ENHET = OVERKOD.ENHET
A.ERSATTNING = OVERKOD.ERSATTNING
A.LONKODTEXT = OVERKOD.LONKODTEXT
A.MULTIP = OVERKOD.MULTIP
A.VALBAR = OVERKOD.VALBAR
A.ENKEL = OVERKOD.ENKEL.

FOR EACH LONTILL WHERE KOD = "K":
CREATE B.
ASSIGN 
          
B.KOD = "T4"
B.LONTILLAGG = LONTILL.LONTILLAGG
B.LONKODTEXT = LONTILL.LONKODTEXT
B.LONTILLANTAL = LONTILL.LONTILLANTAL
B.VILART = LONTILL.VILART
B.TYPKOD = LONTILL.TYPKOD
B.AONROBL = LONTILL.AONROBL
B.ENHET = LONTILL.ENHET
B.MULTIP = LONTILL.MULTIP
B.VALBAR = LONTILL.VALBAR
B.ERSATTNING = LONTILL.ERSATTNING.

FOR EACH OVERTIDTAB WHERE KOD = "K":
CREATE C.
ASSIGN
                  
C.KOD = "T4"
C.OVERTIDTILL = OVERTIDTAB.OVERTIDTILL
C.DAGNR = OVERTIDTAB.DAGNR
C.OVERTIDUTTAG = OVERTIDTAB.OVERTIDUTTAG
C.ARBSLUT = OVERTIDTAB.ARBSLUT
C.ARBSTART = OVERTIDTAB.ARBSTART
C.FORKL = OVERTIDTAB.FORKL
C.START1 = OVERTIDTAB.START1
C.START2 = OVERTIDTAB.START2
C.STOPP1 = OVERTIDTAB.STOPP1
C.STOPP2 = OVERTIDTAB.STOPP2.


FOR EACH RESTIDTAB WHERE KOD = "K":
CREATE D.
ASSIGN
       
D.KOD = "T4"
D.LONTILLAGG = RESTIDTAB.LONTILLAGG
D.DAGNR = RESTIDTAB.DAGNR
D.ENFL = RESTIDTAB.ENFL
D.START1 = RESTIDTAB.START1
D.START2 = RESTIDTAB.START2
D.STOPP1 = RESTIDTAB.STOPP1
D.STOPP2 = RESTIDTAB.STOPP2
