/*
DEFINE VARIABLE numint AS INTEGER NO-UNDO.
FOR EACH BEREDNING WHERE NO-LOCK:
   numint = 0.
   FOR EACH BERKALK WHERE BERKALK.AONR = STRING(BEREDNING.BERNR) AND BERKALK.OMRADE = BEREDNING.OMRADE EXCLUSIVE-LOCK:
      numint = numint + 1.
      BERKALK.BKID = numint.
   END.
   numint = 0.
   FOR EACH HDKALK WHERE HDKALK.BERNR = BEREDNING.BERNR AND HDKALK.OMRADE = BEREDNING.OMRADE EXCLUSIVE-LOCK:
      numint = numint + 1.
      HDKALK.HKID = numint.
   END.
END.
*/

FOR EACH BERKALKOPPLA WHERE BERKALKOPPLA.bernr = 1132 NO-LOCK:
      DISPLAY BERKALKOPPLA.
     /*
      FOR EACH HDKALK WHERE HDKALK.BERNR = BERKALKOPPLA.BERNR AND HDKALK.OMRADE = BERKALKOPPLA.OMRADE :
          
          DISPLAY HDKALK.SID HDKALK.ARBKOD HDKALK.LOPNR HDKALK.ANTAL HDKALK.HKID HDKALK.KALKNUM.
         HDKALK.hKID = 0. HDKALK.KALKNUM = 0. 

      END.
      */
      /*HDKALK.hKID = 0. HDKALK.KALKNUM = 0.
       BERKALK.bKID = 0. BERKALK.KALKNUM = 0.

      for each KALKBEFB WHERE  KALKBEFB.BERNR = BERKALKOPPLA.BERNR AND KALKBEFB.OMRADE = BERKALKOPPLA.OMRADE:
      display KALKBEFB.
      end.
      */
      FOR EACH BERKALK WHERE BERKALK.AONR = BERKALKOPPLA.AONR AND BERKALK.OMRADE = BERKALKOPPLA.OMRADE BY ARBKOD BY LOPNR:
      DISPLAY BERKALK.NUM BERKALK.ARBKOD BERKALK.LOPNR BERKALK.ANTAL BERKALK.BKID BERKALK.KALKNUM.
       BERKALK.bKID = 0. BERKALK.KALKNUM = 0.

     END.
   END.  
   
   FOR EACH KALKBEFB WHERE KALKBEFB.BERNR = 1132 AND KALKBEFB.OMRADE =  "0910" AND KALKBEFB.ARBKOD = "EGEN" :
DISPLAY  arbkod KALKBEFB.LOPNR SID NUM MATERIEL.
 
END.

FOR EACH KALKBEFB WHERE KALKBEFB.BERNR = 1132 AND KALKBEFB.OMRADE =  "0910" AND KALKBEFB.ARBKOD = "EGEN" :
DISPLAY  arbkod KALKBEFB.LOPNR SID NUM MATERIEL.
 
END.


/*   
   FOR EACH KALKNUM  WHERE KALKNUM.KALKNR = 100886 :
      display KALKNUM.ARBKOD KALKNUM.LOPNR kALKNUM.TOTKOST.
      
   END.
*/
   /*
   FOR EACH KALKNUM  WHERE KALKNUM.KALKNR = 100886 NO-LOCK:
      display KALKNUM.ARBKOD KALKNUM.LOPNR kALKNUM.num.
   END.
   FOR EACH KALKNUMsub  WHERE KALKNUMsub.KALKNR = 100886 NO-LOCK:
      display KALKNUMsub.num KALKNUMsub.numsub.
   END.
   */