DEFINE VARIABLE vknummer AS CHARACTER NO-UNDO. 
vknummer = "L" + STRING(20130331,"99999999").
OPEN QUERY tq FOR EACH TIDREGITAB WHERE  TIDREGITAB.DATUM > 12/31/2012 AND     
SUBSTRING(TIDREGITAB.VECKOKORD,1,9) NE "" USE-INDEX PSTART NO-LOCK.   
GET FIRST tq NO-LOCK.
DO WHILE AVAILABLE(TIDREGITAB):
   DO TRANSACTION: 
      GET CURRENT tq EXCLUSIVE-LOCK.      
      ASSIGN SUBSTRING(TIDREGITAB.VECKOKORD,10,9) = vknummer.
   END.   
   GET NEXT tq NO-LOCK.
END.
      
