
/*------------------------------------------------------------------------
    File        : sundfakt.p
    Purpose     : 

    Syntax      :

    Description : 

    Author(s)   : 
    Created     : Tue Mar 01 12:09:36 CET 2016
    Notes       :
  ----------------------------------------------------------------------*/

FOR EACH FASTSPEC WHERE FASTSPEC.FAKTOR = TRUE NO-LOCK:
   FIND FIRST GURUDEFAULTS WHERE GURUDEFAULTS.PROGRAM = "KALKYL" AND GURUDEFAULTS.HUVUDINT = FASTSPEC.KALKNR AND GURUDEFAULTS.HUVUDCHAR = FASTSPEC.OMRADE AND
   GURUDEFAULTS.TOOLKEY = "VisFaktorer"  NO-ERROR.
   IF NOT AVAILABLE GURUDEFAULTS THEN DO:
      CREATE GURUDEFAULTS.
   END.
   ASSIGN 
   GURUDEFAULTS.PROGRAM = "KALKYL"   
   GURUDEFAULTS.HUVUDINT = FASTSPEC.KALKNR
   GURUDEFAULTS.HUVUDCHAR = FASTSPEC.OMRADE
   GURUDEFAULTS.TOOLGROUP = "Visningsinställningar"
   GURUDEFAULTS.TOOLKEY = "VisFaktorer"
   GURUDEFAULTS.TOOLVALUE = "yes" 
   GURUDEFAULTS.TOOLTYPE = "Infragistics.Win.UltraWinToolbars.StateButtonTool" 
   GURUDEFAULTS.VALIDTOOLVALUE = GURUDEFAULTS.TOOLVALUE.
END.
FOR EACH FASTSPEC WHERE FASTSPEC.EGETPRIS = TRUE  NO-LOCK:
   FIND FIRST GURUDEFAULTS WHERE GURUDEFAULTS.PROGRAM = "KALKYL" AND GURUDEFAULTS.HUVUDINT = FASTSPEC.KALKNR AND GURUDEFAULTS.HUVUDCHAR = FASTSPEC.OMRADE AND
   GURUDEFAULTS.TOOLKEY = "VisEgnaPriser"  NO-ERROR.
   IF NOT AVAILABLE GURUDEFAULTS THEN DO:
      CREATE GURUDEFAULTS.
   END.
   ASSIGN 
   GURUDEFAULTS.PROGRAM = "KALKYL"   
   GURUDEFAULTS.HUVUDINT = FASTSPEC.KALKNR
   GURUDEFAULTS.HUVUDCHAR = FASTSPEC.OMRADE
   GURUDEFAULTS.TOOLGROUP = "Visningsinställningar"
   GURUDEFAULTS.TOOLKEY = "VisEgnaPriser"
   GURUDEFAULTS.TOOLVALUE = "yes" 
   GURUDEFAULTS.TOOLTYPE = "Infragistics.Win.UltraWinToolbars.StateButtonTool"
   GURUDEFAULTS.VALIDTOOLVALUE = GURUDEFAULTS.TOOLVALUE.
END.
FOR EACH FASTSPEC WHERE FASTSPEC.EGETPRIS = TRUE NO-LOCK:
   FIND FIRST GURUDEFAULTS WHERE GURUDEFAULTS.PROGRAM = "KALKYL" AND GURUDEFAULTS.HUVUDINT = FASTSPEC.KALKNR AND GURUDEFAULTS.HUVUDCHAR = FASTSPEC.OMRADE AND
   GURUDEFAULTS.TOOLKEY = "VisPriser"  NO-ERROR.
   IF NOT AVAILABLE GURUDEFAULTS THEN DO:
      CREATE GURUDEFAULTS.
   END.
   ASSIGN 
   GURUDEFAULTS.PROGRAM = "KALKYL"   
   GURUDEFAULTS.HUVUDINT = FASTSPEC.KALKNR
   GURUDEFAULTS.HUVUDCHAR = FASTSPEC.OMRADE
   GURUDEFAULTS.TOOLGROUP = "Visningsinställningar"
   GURUDEFAULTS.TOOLKEY = "VisPriser"
   GURUDEFAULTS.TOOLVALUE = "1" 
   GURUDEFAULTS.TOOLTYPE = "Infragistics.Win.UltraWinToolbars.ComboBoxTool"
   GURUDEFAULTS.VALIDTOOLVALUE = GURUDEFAULTS.TOOLVALUE.
END.

