   /*VIEWANM.I ANMÄRKNING*/
   IF anmenable = FALSE THEN DO:
      ENABLE ED_ANM FILL-IN-TEXT BRW_ANM BTN_FAST 
      WITH FRAME {&FRAME-NAME}.
      DISPLAY FILL-IN-TEXT WITH FRAME {&FRAME-NAME}.
      anmenable = TRUE.
   END.
   ASSIGN   
   ED_ANM:HIDDEN IN FRAME {&FRAME-NAME} = FALSE
   FILL-IN-TEXT:HIDDEN IN FRAME {&FRAME-NAME} = FALSE
   BRW_ANM:HIDDEN IN FRAME {&FRAME-NAME} = FALSE
   BTN_FAST:HIDDEN IN FRAME {&FRAME-NAME} = FALSE.
