/* VLSKRIAN.P */
DEFINE SHARED VARIABLE andra AS LOGICAL FORMAT "AN/EJAN" NO-UNDO.
DEFINE SHARED VARIABLE bort LIKE TIDREGITAB.UTRYCKNING NO-UNDO.
DEFINE SHARED VARIABLE titta AS RECID NO-UNDO.
DEFINE SHARED VARIABLE vart AS CHARACTER FORMAT "XXX" NO-UNDO.
DEFINE SHARED VARIABLE raknare AS INTEGER NO-UNDO.
DEFINE SHARED VARIABLE j AS INTEGER NO-UNDO.
DEFINE SHARED VARIABLE rid3 AS RECID EXTENT 50 NO-UNDO.
DEFINE VARIABLE upper AS INTEGER NO-UNDO.
DEFINE SHARED VARIABLE fy AS INTEGER NO-UNDO.
DEFINE SHARED VARIABLE fy1 AS INTEGER NO-UNDO.
DEFINE SHARED VARIABLE fy4 AS INTEGER NO-UNDO.
DEFINE SHARED VARIABLE framed3 AS INTEGER NO-UNDO.
DEFINE SHARED VARIABLE fymax AS INTEGER NO-UNDO.
DEFINE SHARED VARIABLE fymin AS INTEGER NO-UNDO.
DEFINE SHARED VARIABLE visa AS INTEGER NO-UNDO.
DEFINE SHARED VARIABLE rader AS INTEGER NO-UNDO.
DEFINE SHARED VARIABLE svar AS CHARACTER FORMAT "XXX" NO-UNDO.
DEFINE SHARED VARIABLE meny AS CHARACTER EXTENT 3 FORMAT "X(5)" INITIAL
		["Ny", "Žndra", "Bort"] NO-UNDO.
DEFINE SHARED VARIABLE hjupp AS INTEGER NO-UNDO.
DEFINE VARIABLE kollraknare AS INTEGER NO-UNDO.
DEFINE VARIABLE nyrader AS INTEGER NO-UNDO.

DEFINE VARIABLE rundraknare AS INTEGER NO-UNDO.

rundraknare = 2.
FIND FIRST SKRIVARDEF USE-INDEX SKRIVARE NO-LOCK NO-ERROR.
IF RECID(SKRIVARDEF) = rid3[framed3 + 5] THEN rid3[1] = rid3[framed3 + 5].
REPEAT:
   FIND NEXT SKRIVARDEF USE-INDEX SKRIVARE NO-LOCK NO-ERROR.
   IF NOT AVAILABLE SKRIVARDEF THEN DO:
      LEAVE.
   END.
   IF RECID(SKRIVARDEF) = rid3[framed3 + 5] THEN DO:
      LEAVE.
   END.
   ELSE DO:
      rundraknare = rundraknare + 1.
   END.
   IF rundraknare > framed3 THEN LEAVE.
END.
IF rundraknare <= framed3 THEN DO:
/*de ”versta i en frame*/
   FIND FIRST SKRIVARDEF USE-INDEX SKRIVARE NO-LOCK NO-ERROR.
   rid3[1] = RECID(SKRIVARDEF).
END.
ELSE DO:
/*EJ DE ™VERSTA*/
   FIND SKRIVARDEF WHERE RECID(SKRIVARDEF) = rid3[framed3 + 5]
   NO-LOCK NO-ERROR.
   rundraknare = 2.
   REPEAT:
      FIND PREV SKRIVARDEF USE-INDEX SKRIVARE NO-LOCK NO-ERROR.
      /*HITTA DEN F™RSTA INOM FRAMEN*/
      IF NOT AVAILABLE SKRIVARDEF THEN DO:
	 LEAVE.
      END.
      IF rundraknare = framed3 THEN DO:
	 rid3[1] = RECID(SKRIVARDEF).
	 LEAVE.
      END.
      rundraknare = rundraknare + 1.
   END.
END.
