/*WSTARTST.P*/

DEFINE VARIABLE nyaprog AS LOGICAL NO-UNDO.
{HKEYSTART.I}
nyaprog = TRUE.
/*
REPEAT:
   RUN WSTART.W (INPUT "",INPUT "",INPUT-OUTPUT nyaprog).
   IF nyaprog = FALSE THEN LEAVE.
END.
*/
RUN WSTART.W (INPUT "",INPUT "",INPUT-OUTPUT nyaprog).