
   
   /*xakeakalkinlas.p*/       
DEFINE NEW SHARED VARIABLE quotervar AS CHARACTER FORMAT "X(256)" NO-UNDO.



DEFINE VARIABLE gurubilder AS CHARACTER NO-UNDO.

DEFINE VARIABLE musz AS LOGICAL NO-UNDO.

DEFINE VARIABLE rad AS INTEGER NO-UNDO.
DEFINE VARIABLE prognamn AS CHARACTER FORMAT "X(20)" NO-UNDO.
DEFINE VARIABLE prognamndat AS CHARACTER FORMAT "X(20)" NO-UNDO.
DEFINE VARIABLE prognamnque AS CHARACTER FORMAT "X(20)" NO-UNDO.                
DEFINE VARIABLE words AS CHARACTER FORMAT "X(132)" NO-UNDO.
DEFINE VARIABLE kommando AS CHARACTER  NO-UNDO.
DEFINE VARIABLE kommando2 AS CHARACTER  NO-UNDO.
DEFINE VARIABLE kommandoprog AS CHARACTER FORMAT "X(20)" NO-UNDO.
DEFINE VARIABLE satsvar AS CHARACTER FORMAT "X(11)" NO-UNDO.
DEFINE VARIABLE enrvar AS CHARACTER FORMAT "X(11)" NO-UNDO.
DEFINE VARIABLE melvar AS INTEGER NO-UNDO.
DEFINE VARIABLE melvar2 AS INTEGER NO-UNDO.
DEFINE VARIABLE langd AS INTEGER NO-UNDO.
DEFINE VARIABLE pos1 AS INTEGER NO-UNDO. 
DEFINE VARIABLE hjenr AS CHARACTER NO-UNDO.
DEFINE VARIABLE vald_depa  AS INTEGER NO-UNDO.
DEFINE VARIABLE timehjalp AS INTEGER NO-UNDO.
DEFINE VARIABLE trnr AS INTEGER NO-UNDO.

DEFINE TEMP-TABLE tidinah   
   FIELD ej              AS character
   FIELD benamning              AS character
   FIELD enhet                AS CHARACTER                
   FIELD NPRIS              AS DECIMAL
   FIELD KVID AS INTEGER   
   FIELD KOMMENTAR AS character
   FIELD ordnr AS INTEGER    
   INDEX ordnr IS PRIMARY ordnr.
   

DEFINE TEMP-TABLE infil
   FIELD PROGNAMN AS CHARACTER FORMAT "X(78)" 
   INDEX PRO IS PRIMARY PROGNAMN.
DEFINE TEMP-TABLE intid
   FIELD TIN AS CHARACTER FORMAT "X(78)" .
   
DEFINE VARIABLE filnamn AS CHARACTER NO-UNDO.   
DEFINE VARIABLE leverant LIKE LEVERANTOR.LEVKOD NO-UNDO.
DEFINE BUFFER KALKYLKATALOGSUBbuff FOR KALKYLKATALOGSUB.
DEFINE VARIABLE hjraknare AS INTEGER NO-UNDO.
FIND FIRST FORETAG NO-LOCK NO-ERROR.
 

/*ATS*/
   filnamn = "C:\AKEA\inläsPrislista ATS-Tjänster EBR-19 2019-08-20.skv".
   /*filnamn = "\\SERVER05\d\elpool\elplo\AKEA\Prislistor\FIX\inläsPrislista ATS-Tjänster EBR-19 2019-08-20.skv".*/
   EMPTY TEMP-TABLE tidinah  NO-ERROR.     
   RUN in_UI.
   FOR EACH tidinah:
      IF tidinah.NPRIS > 0 THEN tidinah.NPRIS = tidinah.NPRIS / 100.
   END.   

   FIND LAST KALKYLKATALOGSUBbuff USE-INDEX KLOGSUBID NO-LOCK NO-ERROR.
   IF AVAILABLE KALKYLKATALOGSUBbuff THEN DO:
      hjraknare = KALKYLKATALOGSUBbuff.KLOGSUBID + 1.
   END.
   ELSE hjraknare = hjraknare + 1.

   CREATE KALKYLKATALOGSUB.
   ASSIGN
   KALKYLKATALOGSUB.KLOGSUBID = hjraknare
   KALKYLKATALOGSUB.KLOGID = ?
   KALKYLKATALOGSUB.BENAMNING = "ATS EBR 2019"
   KALKYLKATALOGSUB.INDATUM = TODAY.
   
   CREATE KALKYLARBKODER.
   assign
   KALKYLARBKODER.KLOGSUBID = KALKYLKATALOGSUB.KLOGSUBID   
   KALKYLARBKODER.arbkod = "ATS" 
   KALKYLARBKODER.BENAMNING = "ATS EBR 2019"
   KALKYLARBKODER.typkalk = 2.
     
  RUN skapaposter_UI (INPUT KALKYLKATALOGSUB.KLOGSUBID, INPUT KALKYLARBKODER.arbkod ).

   filnamn = "C:\AKEA\inläsPrislista ATS-Tjänster EBR-18 2019-06-25.SKV".
   /*filnamn = "\\SERVER05\d\elpool\elplo\AKEA\Prislistor\FIX\inläsPrislista ATS-Tjänster EBR-18 2019-06-25.SKV".*/
   EMPTY TEMP-TABLE tidinah  NO-ERROR.    
   RUN in_UI.
   FOR EACH tidinah:
      IF tidinah.NPRIS > 0 THEN tidinah.NPRIS = tidinah.NPRIS / 100.
   END.   

   FIND LAST KALKYLKATALOGSUBbuff USE-INDEX KLOGSUBID NO-LOCK NO-ERROR.
   IF AVAILABLE KALKYLKATALOGSUBbuff THEN DO:
      hjraknare = KALKYLKATALOGSUBbuff.KLOGSUBID + 1.
   END.
   ELSE hjraknare = hjraknare + 1.

   CREATE KALKYLKATALOGSUB.
   ASSIGN
   KALKYLKATALOGSUB.KLOGSUBID = hjraknare
   KALKYLKATALOGSUB.KLOGID = ?
   KALKYLKATALOGSUB.BENAMNING = "ATS EBR 2018"
   KALKYLKATALOGSUB.INDATUM = TODAY.
   
   CREATE KALKYLARBKODER.
   assign
   KALKYLARBKODER.KLOGSUBID = KALKYLKATALOGSUB.KLOGSUBID   
   KALKYLARBKODER.arbkod = "ATS" 
   KALKYLARBKODER.BENAMNING = "ATS EBR 2018"
   KALKYLARBKODER.typkalk = 2.
     
  RUN skapaposter_UI (INPUT KALKYLKATALOGSUB.KLOGSUBID, INPUT KALKYLARBKODER.arbkod ).
  filnamn = "C:\AKEA\inläsPrislista ATS-Tjänster EBR-17 2018-01-24.SKV".
  /*filnamn = "\\SERVER05\d\elpool\elplo\AKEA\Prislistor\FIX\inläsPrislista ATS-Tjänster EBR-17 2018-01-24.SKV".*/
   EMPTY TEMP-TABLE tidinah  NO-ERROR.    
   RUN in_UI.
   FOR EACH tidinah:
      IF tidinah.NPRIS > 0 THEN tidinah.NPRIS = tidinah.NPRIS / 100.
   END.   

   FIND LAST KALKYLKATALOGSUBbuff USE-INDEX KLOGSUBID NO-LOCK NO-ERROR.
   IF AVAILABLE KALKYLKATALOGSUBbuff THEN DO:
      hjraknare = KALKYLKATALOGSUBbuff.KLOGSUBID + 1.
   END.
   ELSE hjraknare = hjraknare + 1.

   CREATE KALKYLKATALOGSUB.
   ASSIGN
   KALKYLKATALOGSUB.KLOGSUBID = hjraknare
   KALKYLKATALOGSUB.KLOGID = ?
   KALKYLKATALOGSUB.BENAMNING = "ATS EBR 2017"
   KALKYLKATALOGSUB.INDATUM = TODAY.
   
   CREATE KALKYLARBKODER.
   assign
   KALKYLARBKODER.KLOGSUBID = KALKYLKATALOGSUB.KLOGSUBID   
   KALKYLARBKODER.arbkod = "ATS" 
   KALKYLARBKODER.BENAMNING = "ATS EBR 2017"
   KALKYLARBKODER.typkalk = 2.
     
  RUN skapaposter_UI (INPUT KALKYLKATALOGSUB.KLOGSUBID, INPUT KALKYLARBKODER.arbkod ).
  
   /*Kraftringen*/
   filnamn = "C:\AKEA\inläsPrislista Kraftringen EBR-19 2019-10-17.skv".
   /*filnamn = "\\SERVER05\d\elpool\elplo\AKEA\Prislistor\FIX\inläsPrislista Kraftringen EBR-19 2019-10-17.skv".*/
   EMPTY TEMP-TABLE tidinah  NO-ERROR.     
   RUN in_UI.
   FOR EACH tidinah:
      IF tidinah.NPRIS > 0 THEN tidinah.NPRIS = tidinah.NPRIS / 100.
   END.   

   FIND LAST KALKYLKATALOGSUBbuff USE-INDEX KLOGSUBID NO-LOCK NO-ERROR.
   IF AVAILABLE KALKYLKATALOGSUBbuff THEN DO:
      hjraknare = KALKYLKATALOGSUBbuff.KLOGSUBID + 1.
   END.
   ELSE hjraknare = hjraknare + 1.

   CREATE KALKYLKATALOGSUB.
   ASSIGN
   KALKYLKATALOGSUB.KLOGSUBID = hjraknare
   KALKYLKATALOGSUB.KLOGID = ?
   KALKYLKATALOGSUB.BENAMNING = "Kraftringen EBR 2019"
   KALKYLKATALOGSUB.INDATUM = TODAY.
   
   CREATE KALKYLARBKODER.
   assign
   KALKYLARBKODER.KLOGSUBID = KALKYLKATALOGSUB.KLOGSUBID   
   KALKYLARBKODER.arbkod = "Kring" 
   KALKYLARBKODER.BENAMNING = "Kraftringen EBR 2019"
   KALKYLARBKODER.typkalk = 2.
     
  RUN skapaposter_UI (INPUT KALKYLKATALOGSUB.KLOGSUBID, INPUT KALKYLARBKODER.arbkod ).

   filnamn = "C:\AKEA\inläsPrislista Kraftringen EBR-18 2018-07-03.skv".
   /*filnamn = "\\SERVER05\d\elpool\elplo\AKEA\Prislistor\FIX\inläsPrislista Kraftringen EBR-18 2018-07-03.skv".*/
   EMPTY TEMP-TABLE tidinah  NO-ERROR.    
   RUN in_UI.
   FOR EACH tidinah:
      IF tidinah.NPRIS > 0 THEN tidinah.NPRIS = tidinah.NPRIS / 100.
   END.   

   FIND LAST KALKYLKATALOGSUBbuff USE-INDEX KLOGSUBID NO-LOCK NO-ERROR.
   IF AVAILABLE KALKYLKATALOGSUBbuff THEN DO:
      hjraknare = KALKYLKATALOGSUBbuff.KLOGSUBID + 1.
   END.
   ELSE hjraknare = hjraknare + 1.

   CREATE KALKYLKATALOGSUB.
   ASSIGN
   KALKYLKATALOGSUB.KLOGSUBID = hjraknare
   KALKYLKATALOGSUB.KLOGID = ?
   KALKYLKATALOGSUB.BENAMNING = "Kraftringen EBR 2018"
   KALKYLKATALOGSUB.INDATUM = TODAY.
   
   CREATE KALKYLARBKODER.
   assign
   KALKYLARBKODER.KLOGSUBID = KALKYLKATALOGSUB.KLOGSUBID   
   KALKYLARBKODER.arbkod = "Kring" 
   KALKYLARBKODER.BENAMNING = "Kraftringen EBR 2018"
   KALKYLARBKODER.typkalk = 2.
     
  RUN skapaposter_UI (INPUT KALKYLKATALOGSUB.KLOGSUBID, INPUT KALKYLARBKODER.arbkod ).
  filnamn = "C:\AKEA\inläsPrislista Kraftringen EBR-17 2018-10-01.skv". 
  /*filnamn = "\\SERVER05\d\elpool\elplo\AKEA\Prislistor\FIX\inläsPrislista Kraftringen EBR-17 2018-10-01.skv".*/
   EMPTY TEMP-TABLE tidinah  NO-ERROR.    
   RUN in_UI.
   FOR EACH tidinah:
      IF tidinah.NPRIS > 0 THEN tidinah.NPRIS = tidinah.NPRIS / 100.
   END.   

   FIND LAST KALKYLKATALOGSUBbuff USE-INDEX KLOGSUBID NO-LOCK NO-ERROR.
   IF AVAILABLE KALKYLKATALOGSUBbuff THEN DO:
      hjraknare = KALKYLKATALOGSUBbuff.KLOGSUBID + 1.
   END.
   ELSE hjraknare = hjraknare + 1.

   CREATE KALKYLKATALOGSUB.
   ASSIGN
   KALKYLKATALOGSUB.KLOGSUBID = hjraknare
   KALKYLKATALOGSUB.KLOGID = ?
   KALKYLKATALOGSUB.BENAMNING = "Kraftringen EBR 2017"
   KALKYLKATALOGSUB.INDATUM = TODAY.
   
   CREATE KALKYLARBKODER.
   assign
   KALKYLARBKODER.KLOGSUBID = KALKYLKATALOGSUB.KLOGSUBID   
   KALKYLARBKODER.arbkod = "Kring" 
   KALKYLARBKODER.BENAMNING = "Kraftringen EBR 2017"
   KALKYLARBKODER.typkalk = 2.
     
  RUN skapaposter_UI (INPUT KALKYLKATALOGSUB.KLOGSUBID, INPUT KALKYLARBKODER.arbkod ).

/*Landskrona*/

   filnamn = "C:\AKEA\inläsPrislista Landskrona Energi EBR-19 2019-10-10.skv".
   /*filnamn = "\\SERVER05\d\elpool\elplo\AKEA\Prislistor\FIX\inläsPrislista Landskrona Energi EBR-19 2019-10-10.skv".*/
   EMPTY TEMP-TABLE tidinah  NO-ERROR.     
   RUN in_UI.
   FOR EACH tidinah:
      IF tidinah.NPRIS > 0 THEN tidinah.NPRIS = tidinah.NPRIS / 100.
   END.   

   FIND LAST KALKYLKATALOGSUBbuff USE-INDEX KLOGSUBID NO-LOCK NO-ERROR.
   IF AVAILABLE KALKYLKATALOGSUBbuff THEN DO:
      hjraknare = KALKYLKATALOGSUBbuff.KLOGSUBID + 1.
   END.
   ELSE hjraknare = hjraknare + 1.

   CREATE KALKYLKATALOGSUB.
   ASSIGN
   KALKYLKATALOGSUB.KLOGSUBID = hjraknare
   KALKYLKATALOGSUB.KLOGID = ?
   KALKYLKATALOGSUB.BENAMNING = "Landskrona EBR 2019"
   KALKYLKATALOGSUB.INDATUM = TODAY.
   
   CREATE KALKYLARBKODER.
   assign
   KALKYLARBKODER.KLOGSUBID = KALKYLKATALOGSUB.KLOGSUBID   
   KALKYLARBKODER.arbkod = "Lkron" 
   KALKYLARBKODER.BENAMNING = "Landskrona EBR 2019"
   KALKYLARBKODER.typkalk = 2.
     
  RUN skapaposter_UI (INPUT KALKYLKATALOGSUB.KLOGSUBID, INPUT KALKYLARBKODER.arbkod ).

   filnamn = "C:\AKEA\inläsPrislista Landskrona Energi EBR-18 2019-05-07.skv".
   /*filnamn = "\\SERVER05\d\elpool\elplo\AKEA\Prislistor\FIX\inläsPrislista Landskrona Energi EBR-18 2019-05-07.skv".*/
   EMPTY TEMP-TABLE tidinah  NO-ERROR.    
   RUN in_UI.
   FOR EACH tidinah:
      IF tidinah.NPRIS > 0 THEN tidinah.NPRIS = tidinah.NPRIS / 100.
   END.   

   FIND LAST KALKYLKATALOGSUBbuff USE-INDEX KLOGSUBID NO-LOCK NO-ERROR.
   IF AVAILABLE KALKYLKATALOGSUBbuff THEN DO:
      hjraknare = KALKYLKATALOGSUBbuff.KLOGSUBID + 1.
   END.
   ELSE hjraknare = hjraknare + 1.

   CREATE KALKYLKATALOGSUB.
   ASSIGN
   KALKYLKATALOGSUB.KLOGSUBID = hjraknare
   KALKYLKATALOGSUB.KLOGID = ?
   KALKYLKATALOGSUB.BENAMNING = "Landskrona EBR 2018"
   KALKYLKATALOGSUB.INDATUM = TODAY.
   
   CREATE KALKYLARBKODER.
   assign
   KALKYLARBKODER.KLOGSUBID = KALKYLKATALOGSUB.KLOGSUBID   
   KALKYLARBKODER.arbkod = "Lkron" 
   KALKYLARBKODER.BENAMNING = "Landskrona EBR 2018"
   KALKYLARBKODER.typkalk = 2.
     
  RUN skapaposter_UI (INPUT KALKYLKATALOGSUB.KLOGSUBID, INPUT KALKYLARBKODER.arbkod ).

   /*Höganäs*/
   filnamn = "C:\AKEA\inläsHöganäs Energi 19-01-01.skv".
   /*filnamn = "\\SERVER05\d\elpool\elplo\AKEA\Prislistor\FIX\inläsHöganäs Energi 19-01-01.skv".*/
   EMPTY TEMP-TABLE tidinah  NO-ERROR.    
   RUN in_UI.
   FOR EACH tidinah:
      IF tidinah.NPRIS > 0 THEN tidinah.NPRIS = tidinah.NPRIS / 100.
   END.   

   FIND LAST KALKYLKATALOGSUBbuff USE-INDEX KLOGSUBID NO-LOCK NO-ERROR.
   IF AVAILABLE KALKYLKATALOGSUBbuff THEN DO:
      hjraknare = KALKYLKATALOGSUBbuff.KLOGSUBID + 1.
   END.
   ELSE hjraknare = hjraknare + 1.

   CREATE KALKYLKATALOGSUB.
   ASSIGN
   KALKYLKATALOGSUB.KLOGSUBID = hjraknare
   KALKYLKATALOGSUB.KLOGID = ?
   KALKYLKATALOGSUB.BENAMNING = "Höganäs 2019"
   KALKYLKATALOGSUB.INDATUM = TODAY.
   
   CREATE KALKYLARBKODER.
   assign
   KALKYLARBKODER.KLOGSUBID = KALKYLKATALOGSUB.KLOGSUBID   
   KALKYLARBKODER.arbkod = "Höga" 
   KALKYLARBKODER.BENAMNING = "Höganäs 2019"
   KALKYLARBKODER.typkalk = 2.
     
  RUN skapaposter_UI (INPUT KALKYLKATALOGSUB.KLOGSUBID, INPUT KALKYLARBKODER.arbkod ).

   
   
   
      
PROCEDURE in_UI: 
   EMPTY TEMP-TABLE intid NO-ERROR.
   EMPTY TEMP-TABLE tidinah NO-ERROR.
   DEF VAR ordnnr AS INTEGER.
   ordnnr = 1.
   INPUT FROM VALUE(filnamn) NO-ECHO.
   REPEAT:
      DO TRANSACTION: 
         CREATE tidinah.
         ASSIGN.
         IMPORT DELIMITER ";" tidinah   NO-ERROR.
         tidinah.ordnr = ordnnr.
         ordnnr = ordnnr + 1.
      END.               
   END.


   /*FOR EACH tidinah :
      IF SUBSTRING(tidinah.TRUMMANAMN,1,1) = "E" OR SUBSTRING(tidinah.TRUMMANAMN,1,1) = "D" OR SUBSTRING(tidinah.TRUMMANAMN,1,1) = "F"  OR SUBSTRING(tidinah.TRUMMANAMN,1,1) = "G" THEN.
      ELSE tidinah.TRUMMANAMN = "E" + tidinah.TRUMMANAMN.
   END.     
   

   RUN skapaenr_UI.*/           

   
END PROCEDURE.

PROCEDURE skapaposter_UI:
   DEFINE INPUT PARAMETER KGID AS INTEGER NO-UNDO.
   DEFINE INPUT PARAMETER AKOD AS CHARACTER NO-UNDO.
   

   FOR EACH tidinah NO-LOCK:
      CREATE KALKYLPRISER.
      ASSIGN 
      KALKYLPRISER.KLOGSUBID = KGID
      KALKYLPRISER.BENAMNING = tidinah.BENAMNING
      KALKYLPRISER.EGENKODUPP  = TRUE
      KALKYLPRISER.EGENPRISUPP = FALSE
      KALKYLPRISER.KPID = tidinah.ORDNR
      KALKYLPRISER.KVID = tidinah.KVID
      KALKYLPRISER.PRIS = tidinah.NPRIS
      KALKYLPRISER.SOKBENAMNING = "PRIS" + STRING(KPID).
      
      CREATE KALKYLLOPPOSTER.
      ASSIGN
      KALKYLLOPPOSTER.KLOGSUBID = KGID
      KALKYLLOPPOSTER.ARBKOD = AKOD
      KALKYLLOPPOSTER.LOPNR = tidinah.ORDNR
      KALKYLLOPPOSTER.BENAMNING = tidinah.BENAMNING
      KALKYLLOPPOSTER.KOMMENTAR = tidinah.KOMMENTAR
      KALKYLLOPPOSTER.ENHET = tidinah.ENHET
      KALKYLLOPPOSTER.TYPKALK = 2.
      CREATE KALKYLLOPSUB.
      ASSIGN 
      KALKYLLOPSUB.KLOGSUBID = KGID
      KALKYLLOPSUB.ARBKOD = AKOD
      KALKYLLOPSUB.LOPNR = tidinah.ORDNR
      KALKYLLOPSUB.KPID = tidinah.ORDNR.
      IF tidinah.ENHET = "TIM" THEN DO:
         KALKYLLOPSUB.TIMMAR = 1.
     END.
     ELSE DO:
        KALKYLLOPSUB.KOSTNAD = tidinah.NPRIS.        
     END.       
      
      
      
      
   END.  
END PROCEDURE.
   

=======
   
   /*xakeakalkinlas.p*/       
DEFINE NEW SHARED VARIABLE quotervar AS CHARACTER FORMAT "X(256)" NO-UNDO.



DEFINE VARIABLE gurubilder AS CHARACTER NO-UNDO.

DEFINE VARIABLE musz AS LOGICAL NO-UNDO.

DEFINE VARIABLE rad AS INTEGER NO-UNDO.
DEFINE VARIABLE prognamn AS CHARACTER FORMAT "X(20)" NO-UNDO.
DEFINE VARIABLE prognamndat AS CHARACTER FORMAT "X(20)" NO-UNDO.
DEFINE VARIABLE prognamnque AS CHARACTER FORMAT "X(20)" NO-UNDO.                
DEFINE VARIABLE words AS CHARACTER FORMAT "X(132)" NO-UNDO.
DEFINE VARIABLE kommando AS CHARACTER  NO-UNDO.
DEFINE VARIABLE kommando2 AS CHARACTER  NO-UNDO.
DEFINE VARIABLE kommandoprog AS CHARACTER FORMAT "X(20)" NO-UNDO.
DEFINE VARIABLE satsvar AS CHARACTER FORMAT "X(11)" NO-UNDO.
DEFINE VARIABLE enrvar AS CHARACTER FORMAT "X(11)" NO-UNDO.
DEFINE VARIABLE melvar AS INTEGER NO-UNDO.
DEFINE VARIABLE melvar2 AS INTEGER NO-UNDO.
DEFINE VARIABLE langd AS INTEGER NO-UNDO.
DEFINE VARIABLE pos1 AS INTEGER NO-UNDO. 
DEFINE VARIABLE hjenr AS CHARACTER NO-UNDO.
DEFINE VARIABLE vald_depa  AS INTEGER NO-UNDO.
DEFINE VARIABLE timehjalp AS INTEGER NO-UNDO.
DEFINE VARIABLE trnr AS INTEGER NO-UNDO.

DEFINE TEMP-TABLE tidinah   
   FIELD ej              AS character
   FIELD benamning              AS character
   FIELD enhet                AS CHARACTER                
   FIELD NPRIS              AS DECIMAL
   FIELD KVID AS INTEGER   
   FIELD KOMMENTAR AS character
   FIELD ordnr AS INTEGER    
   INDEX ordnr IS PRIMARY ordnr.
   

DEFINE TEMP-TABLE infil
   FIELD PROGNAMN AS CHARACTER FORMAT "X(78)" 
   INDEX PRO IS PRIMARY PROGNAMN.
DEFINE TEMP-TABLE intid
   FIELD TIN AS CHARACTER FORMAT "X(78)" .
   
DEFINE VARIABLE filnamn AS CHARACTER NO-UNDO.   
DEFINE VARIABLE leverant LIKE LEVERANTOR.LEVKOD NO-UNDO.
DEFINE BUFFER KALKYLKATALOGSUBbuff FOR KALKYLKATALOGSUB.
DEFINE VARIABLE hjraknare AS INTEGER NO-UNDO.
FIND FIRST FORETAG NO-LOCK NO-ERROR.
 

/*ATS*/
   filnamn = "C:\AKEA\inläsPrislista ATS-Tjänster EBR-19 2019-08-20.skv".
   /*filnamn = "\\SERVER05\d\elpool\elplo\AKEA\Prislistor\FIX\inläsPrislista ATS-Tjänster EBR-19 2019-08-20.skv".*/
   EMPTY TEMP-TABLE tidinah  NO-ERROR.     
   RUN in_UI.
   FOR EACH tidinah:
      IF tidinah.NPRIS > 0 THEN tidinah.NPRIS = tidinah.NPRIS / 100.
   END.   

   FIND LAST KALKYLKATALOGSUBbuff USE-INDEX KLOGSUBID NO-LOCK NO-ERROR.
   IF AVAILABLE KALKYLKATALOGSUBbuff THEN DO:
      hjraknare = KALKYLKATALOGSUBbuff.KLOGSUBID + 1.
   END.
   ELSE hjraknare = hjraknare + 1.

   CREATE KALKYLKATALOGSUB.
   ASSIGN
   KALKYLKATALOGSUB.KLOGSUBID = hjraknare
   KALKYLKATALOGSUB.KLOGID = ?
   KALKYLKATALOGSUB.BENAMNING = "ATS EBR 2019"
   KALKYLKATALOGSUB.INDATUM = TODAY.
   
   CREATE KALKYLARBKODER.
   assign
   KALKYLARBKODER.KLOGSUBID = KALKYLKATALOGSUB.KLOGSUBID   
   KALKYLARBKODER.arbkod = "ATS" 
   KALKYLARBKODER.BENAMNING = "ATS EBR 2019"
   KALKYLARBKODER.typkalk = 2.
     
  RUN skapaposter_UI (INPUT KALKYLKATALOGSUB.KLOGSUBID, INPUT KALKYLARBKODER.arbkod ).

   filnamn = "C:\AKEA\inläsPrislista ATS-Tjänster EBR-18 2019-06-25.SKV".
   /*filnamn = "\\SERVER05\d\elpool\elplo\AKEA\Prislistor\FIX\inläsPrislista ATS-Tjänster EBR-18 2019-06-25.SKV".*/
   EMPTY TEMP-TABLE tidinah  NO-ERROR.    
   RUN in_UI.
   FOR EACH tidinah:
      IF tidinah.NPRIS > 0 THEN tidinah.NPRIS = tidinah.NPRIS / 100.
   END.   

   FIND LAST KALKYLKATALOGSUBbuff USE-INDEX KLOGSUBID NO-LOCK NO-ERROR.
   IF AVAILABLE KALKYLKATALOGSUBbuff THEN DO:
      hjraknare = KALKYLKATALOGSUBbuff.KLOGSUBID + 1.
   END.
   ELSE hjraknare = hjraknare + 1.

   CREATE KALKYLKATALOGSUB.
   ASSIGN
   KALKYLKATALOGSUB.KLOGSUBID = hjraknare
   KALKYLKATALOGSUB.KLOGID = ?
   KALKYLKATALOGSUB.BENAMNING = "ATS EBR 2018"
   KALKYLKATALOGSUB.INDATUM = TODAY.
   
   CREATE KALKYLARBKODER.
   assign
   KALKYLARBKODER.KLOGSUBID = KALKYLKATALOGSUB.KLOGSUBID   
   KALKYLARBKODER.arbkod = "ATS" 
   KALKYLARBKODER.BENAMNING = "ATS EBR 2018"
   KALKYLARBKODER.typkalk = 2.
     
  RUN skapaposter_UI (INPUT KALKYLKATALOGSUB.KLOGSUBID, INPUT KALKYLARBKODER.arbkod ).
  filnamn = "C:\AKEA\inläsPrislista ATS-Tjänster EBR-17 2018-01-24.SKV".
  /*filnamn = "\\SERVER05\d\elpool\elplo\AKEA\Prislistor\FIX\inläsPrislista ATS-Tjänster EBR-17 2018-01-24.SKV".*/
   EMPTY TEMP-TABLE tidinah  NO-ERROR.    
   RUN in_UI.
   FOR EACH tidinah:
      IF tidinah.NPRIS > 0 THEN tidinah.NPRIS = tidinah.NPRIS / 100.
   END.   

   FIND LAST KALKYLKATALOGSUBbuff USE-INDEX KLOGSUBID NO-LOCK NO-ERROR.
   IF AVAILABLE KALKYLKATALOGSUBbuff THEN DO:
      hjraknare = KALKYLKATALOGSUBbuff.KLOGSUBID + 1.
   END.
   ELSE hjraknare = hjraknare + 1.

   CREATE KALKYLKATALOGSUB.
   ASSIGN
   KALKYLKATALOGSUB.KLOGSUBID = hjraknare
   KALKYLKATALOGSUB.KLOGID = ?
   KALKYLKATALOGSUB.BENAMNING = "ATS EBR 2017"
   KALKYLKATALOGSUB.INDATUM = TODAY.
   
   CREATE KALKYLARBKODER.
   assign
   KALKYLARBKODER.KLOGSUBID = KALKYLKATALOGSUB.KLOGSUBID   
   KALKYLARBKODER.arbkod = "ATS" 
   KALKYLARBKODER.BENAMNING = "ATS EBR 2017"
   KALKYLARBKODER.typkalk = 2.
     
  RUN skapaposter_UI (INPUT KALKYLKATALOGSUB.KLOGSUBID, INPUT KALKYLARBKODER.arbkod ).
  
   /*Kraftringen*/
   filnamn = "C:\AKEA\inläsPrislista Kraftringen EBR-19 2019-10-17.skv".
   /*filnamn = "\\SERVER05\d\elpool\elplo\AKEA\Prislistor\FIX\inläsPrislista Kraftringen EBR-19 2019-10-17.skv".*/
   EMPTY TEMP-TABLE tidinah  NO-ERROR.     
   RUN in_UI.
   FOR EACH tidinah:
      IF tidinah.NPRIS > 0 THEN tidinah.NPRIS = tidinah.NPRIS / 100.
   END.   

   FIND LAST KALKYLKATALOGSUBbuff USE-INDEX KLOGSUBID NO-LOCK NO-ERROR.
   IF AVAILABLE KALKYLKATALOGSUBbuff THEN DO:
      hjraknare = KALKYLKATALOGSUBbuff.KLOGSUBID + 1.
   END.
   ELSE hjraknare = hjraknare + 1.

   CREATE KALKYLKATALOGSUB.
   ASSIGN
   KALKYLKATALOGSUB.KLOGSUBID = hjraknare
   KALKYLKATALOGSUB.KLOGID = ?
   KALKYLKATALOGSUB.BENAMNING = "Kraftringen EBR 2019"
   KALKYLKATALOGSUB.INDATUM = TODAY.
   
   CREATE KALKYLARBKODER.
   assign
   KALKYLARBKODER.KLOGSUBID = KALKYLKATALOGSUB.KLOGSUBID   
   KALKYLARBKODER.arbkod = "Kring" 
   KALKYLARBKODER.BENAMNING = "Kraftringen EBR 2019"
   KALKYLARBKODER.typkalk = 2.
     
  RUN skapaposter_UI (INPUT KALKYLKATALOGSUB.KLOGSUBID, INPUT KALKYLARBKODER.arbkod ).

   filnamn = "C:\AKEA\inläsPrislista Kraftringen EBR-18 2018-07-03.skv".
   /*filnamn = "\\SERVER05\d\elpool\elplo\AKEA\Prislistor\FIX\inläsPrislista Kraftringen EBR-18 2018-07-03.skv".*/
   EMPTY TEMP-TABLE tidinah  NO-ERROR.    
   RUN in_UI.
   FOR EACH tidinah:
      IF tidinah.NPRIS > 0 THEN tidinah.NPRIS = tidinah.NPRIS / 100.
   END.   

   FIND LAST KALKYLKATALOGSUBbuff USE-INDEX KLOGSUBID NO-LOCK NO-ERROR.
   IF AVAILABLE KALKYLKATALOGSUBbuff THEN DO:
      hjraknare = KALKYLKATALOGSUBbuff.KLOGSUBID + 1.
   END.
   ELSE hjraknare = hjraknare + 1.

   CREATE KALKYLKATALOGSUB.
   ASSIGN
   KALKYLKATALOGSUB.KLOGSUBID = hjraknare
   KALKYLKATALOGSUB.KLOGID = ?
   KALKYLKATALOGSUB.BENAMNING = "Kraftringen EBR 2018"
   KALKYLKATALOGSUB.INDATUM = TODAY.
   
   CREATE KALKYLARBKODER.
   assign
   KALKYLARBKODER.KLOGSUBID = KALKYLKATALOGSUB.KLOGSUBID   
   KALKYLARBKODER.arbkod = "Kring" 
   KALKYLARBKODER.BENAMNING = "Kraftringen EBR 2018"
   KALKYLARBKODER.typkalk = 2.
     
  RUN skapaposter_UI (INPUT KALKYLKATALOGSUB.KLOGSUBID, INPUT KALKYLARBKODER.arbkod ).
  filnamn = "C:\AKEA\inläsPrislista Kraftringen EBR-17 2018-10-01.skv". 
  /*filnamn = "\\SERVER05\d\elpool\elplo\AKEA\Prislistor\FIX\inläsPrislista Kraftringen EBR-17 2018-10-01.skv".*/
   EMPTY TEMP-TABLE tidinah  NO-ERROR.    
   RUN in_UI.
   FOR EACH tidinah:
      IF tidinah.NPRIS > 0 THEN tidinah.NPRIS = tidinah.NPRIS / 100.
   END.   

   FIND LAST KALKYLKATALOGSUBbuff USE-INDEX KLOGSUBID NO-LOCK NO-ERROR.
   IF AVAILABLE KALKYLKATALOGSUBbuff THEN DO:
      hjraknare = KALKYLKATALOGSUBbuff.KLOGSUBID + 1.
   END.
   ELSE hjraknare = hjraknare + 1.

   CREATE KALKYLKATALOGSUB.
   ASSIGN
   KALKYLKATALOGSUB.KLOGSUBID = hjraknare
   KALKYLKATALOGSUB.KLOGID = ?
   KALKYLKATALOGSUB.BENAMNING = "Kraftringen EBR 2017"
   KALKYLKATALOGSUB.INDATUM = TODAY.
   
   CREATE KALKYLARBKODER.
   assign
   KALKYLARBKODER.KLOGSUBID = KALKYLKATALOGSUB.KLOGSUBID   
   KALKYLARBKODER.arbkod = "Kring" 
   KALKYLARBKODER.BENAMNING = "Kraftringen EBR 2017"
   KALKYLARBKODER.typkalk = 2.
     
  RUN skapaposter_UI (INPUT KALKYLKATALOGSUB.KLOGSUBID, INPUT KALKYLARBKODER.arbkod ).

/*Landskrona*/

   filnamn = "C:\AKEA\inläsPrislista Landskrona Energi EBR-19 2019-10-10.skv".
   /*filnamn = "\\SERVER05\d\elpool\elplo\AKEA\Prislistor\FIX\inläsPrislista Landskrona Energi EBR-19 2019-10-10.skv".*/
   EMPTY TEMP-TABLE tidinah  NO-ERROR.     
   RUN in_UI.
   FOR EACH tidinah:
      IF tidinah.NPRIS > 0 THEN tidinah.NPRIS = tidinah.NPRIS / 100.
   END.   

   FIND LAST KALKYLKATALOGSUBbuff USE-INDEX KLOGSUBID NO-LOCK NO-ERROR.
   IF AVAILABLE KALKYLKATALOGSUBbuff THEN DO:
      hjraknare = KALKYLKATALOGSUBbuff.KLOGSUBID + 1.
   END.
   ELSE hjraknare = hjraknare + 1.

   CREATE KALKYLKATALOGSUB.
   ASSIGN
   KALKYLKATALOGSUB.KLOGSUBID = hjraknare
   KALKYLKATALOGSUB.KLOGID = ?
   KALKYLKATALOGSUB.BENAMNING = "Landskrona EBR 2019"
   KALKYLKATALOGSUB.INDATUM = TODAY.
   
   CREATE KALKYLARBKODER.
   assign
   KALKYLARBKODER.KLOGSUBID = KALKYLKATALOGSUB.KLOGSUBID   
   KALKYLARBKODER.arbkod = "Lkron" 
   KALKYLARBKODER.BENAMNING = "Landskrona EBR 2019"
   KALKYLARBKODER.typkalk = 2.
     
  RUN skapaposter_UI (INPUT KALKYLKATALOGSUB.KLOGSUBID, INPUT KALKYLARBKODER.arbkod ).

   filnamn = "C:\AKEA\inläsPrislista Landskrona Energi EBR-18 2019-05-07.skv".
   /*filnamn = "\\SERVER05\d\elpool\elplo\AKEA\Prislistor\FIX\inläsPrislista Landskrona Energi EBR-18 2019-05-07.skv".*/
   EMPTY TEMP-TABLE tidinah  NO-ERROR.    
   RUN in_UI.
   FOR EACH tidinah:
      IF tidinah.NPRIS > 0 THEN tidinah.NPRIS = tidinah.NPRIS / 100.
   END.   

   FIND LAST KALKYLKATALOGSUBbuff USE-INDEX KLOGSUBID NO-LOCK NO-ERROR.
   IF AVAILABLE KALKYLKATALOGSUBbuff THEN DO:
      hjraknare = KALKYLKATALOGSUBbuff.KLOGSUBID + 1.
   END.
   ELSE hjraknare = hjraknare + 1.

   CREATE KALKYLKATALOGSUB.
   ASSIGN
   KALKYLKATALOGSUB.KLOGSUBID = hjraknare
   KALKYLKATALOGSUB.KLOGID = ?
   KALKYLKATALOGSUB.BENAMNING = "Landskrona EBR 2018"
   KALKYLKATALOGSUB.INDATUM = TODAY.
   
   CREATE KALKYLARBKODER.
   assign
   KALKYLARBKODER.KLOGSUBID = KALKYLKATALOGSUB.KLOGSUBID   
   KALKYLARBKODER.arbkod = "Lkron" 
   KALKYLARBKODER.BENAMNING = "Landskrona EBR 2018"
   KALKYLARBKODER.typkalk = 2.
     
  RUN skapaposter_UI (INPUT KALKYLKATALOGSUB.KLOGSUBID, INPUT KALKYLARBKODER.arbkod ).

   /*Höganäs*/
   filnamn = "C:\AKEA\inläsHöganäs Energi 19-01-01.skv".
   /*filnamn = "\\SERVER05\d\elpool\elplo\AKEA\Prislistor\FIX\inläsHöganäs Energi 19-01-01.skv".*/
   EMPTY TEMP-TABLE tidinah  NO-ERROR.    
   RUN in_UI.
   FOR EACH tidinah:
      IF tidinah.NPRIS > 0 THEN tidinah.NPRIS = tidinah.NPRIS / 100.
   END.   

   FIND LAST KALKYLKATALOGSUBbuff USE-INDEX KLOGSUBID NO-LOCK NO-ERROR.
   IF AVAILABLE KALKYLKATALOGSUBbuff THEN DO:
      hjraknare = KALKYLKATALOGSUBbuff.KLOGSUBID + 1.
   END.
   ELSE hjraknare = hjraknare + 1.

   CREATE KALKYLKATALOGSUB.
   ASSIGN
   KALKYLKATALOGSUB.KLOGSUBID = hjraknare
   KALKYLKATALOGSUB.KLOGID = ?
   KALKYLKATALOGSUB.BENAMNING = "Höganäs 2019"
   KALKYLKATALOGSUB.INDATUM = TODAY.
   
   CREATE KALKYLARBKODER.
   assign
   KALKYLARBKODER.KLOGSUBID = KALKYLKATALOGSUB.KLOGSUBID   
   KALKYLARBKODER.arbkod = "Höga" 
   KALKYLARBKODER.BENAMNING = "Höganäs 2019"
   KALKYLARBKODER.typkalk = 2.
     
  RUN skapaposter_UI (INPUT KALKYLKATALOGSUB.KLOGSUBID, INPUT KALKYLARBKODER.arbkod ).

   
   
   
      
PROCEDURE in_UI: 
   EMPTY TEMP-TABLE intid NO-ERROR.
   EMPTY TEMP-TABLE tidinah NO-ERROR.
   DEF VAR ordnnr AS INTEGER.
   ordnnr = 1.
   INPUT FROM VALUE(filnamn) NO-ECHO.
   REPEAT:
      DO TRANSACTION: 
         CREATE tidinah.
         ASSIGN.
         IMPORT DELIMITER ";" tidinah   NO-ERROR.
         tidinah.ordnr = ordnnr.
         ordnnr = ordnnr + 1.
      END.               
   END.


   /*FOR EACH tidinah :
      IF SUBSTRING(tidinah.TRUMMANAMN,1,1) = "E" OR SUBSTRING(tidinah.TRUMMANAMN,1,1) = "D" OR SUBSTRING(tidinah.TRUMMANAMN,1,1) = "F"  OR SUBSTRING(tidinah.TRUMMANAMN,1,1) = "G" THEN.
      ELSE tidinah.TRUMMANAMN = "E" + tidinah.TRUMMANAMN.
   END.     
   

   RUN skapaenr_UI.*/           

   
END PROCEDURE.

PROCEDURE skapaposter_UI:
   DEFINE INPUT PARAMETER KGID AS INTEGER NO-UNDO.
   DEFINE INPUT PARAMETER AKOD AS CHARACTER NO-UNDO.
   

   FOR EACH tidinah NO-LOCK:
      CREATE KALKYLPRISER.
      ASSIGN 
      KALKYLPRISER.KLOGSUBID = KGID
      KALKYLPRISER.BENAMNING = tidinah.BENAMNING
      KALKYLPRISER.EGENKODUPP  = TRUE
      KALKYLPRISER.EGENPRISUPP = FALSE
      KALKYLPRISER.KPID = tidinah.ORDNR
      KALKYLPRISER.KVID = tidinah.KVID
      KALKYLPRISER.PRIS = tidinah.NPRIS
      KALKYLPRISER.SOKBENAMNING = "PRIS" + STRING(KPID).
      
      CREATE KALKYLLOPPOSTER.
      ASSIGN
      KALKYLLOPPOSTER.KLOGSUBID = KGID
      KALKYLLOPPOSTER.ARBKOD = AKOD
      KALKYLLOPPOSTER.LOPNR = tidinah.ORDNR
      KALKYLLOPPOSTER.BENAMNING = tidinah.BENAMNING
      KALKYLLOPPOSTER.KOMMENTAR = tidinah.KOMMENTAR
      KALKYLLOPPOSTER.ENHET = tidinah.ENHET
      KALKYLLOPPOSTER.TYPKALK = 2.
      CREATE KALKYLLOPSUB.
      ASSIGN 
      KALKYLLOPSUB.KLOGSUBID = KGID
      KALKYLLOPSUB.ARBKOD = AKOD
      KALKYLLOPSUB.LOPNR = tidinah.ORDNR
      KALKYLLOPSUB.KPID = tidinah.ORDNR.
      IF tidinah.ENHET = "TIM" THEN DO:
         KALKYLLOPSUB.TIMMAR = 1.
     END.
     ELSE DO:
        KALKYLLOPSUB.KOSTNAD = tidinah.NPRIS.        
     END.       
      
      
      
      
   END.  
END PROCEDURE.
   

>>>>>>> branch 'master' of file:///\\server05\delad\REMOTEGURU\GuruRemote.git
