/*XALLLART.P*/
DEFINE TEMP-TABLE LART
    FIELD TILLAGG AS CHARACTER
    FIELD LTEXT AS CHARACTER
    FIELD ENHET AS CHARACTER
    FIELD ERSATTNING AS DECIMAL.
 FOR EACH LONTILL WHERE LONTILL.KOD = "T1":
    
     CREATE LART.
     ASSIGN LART.TILLAGG = LONTILL.LONTILLAGG
     LART.LTEXT = LONTILL.LONKODTEXT
     LART.ENHET = LONTILL.ENHET
     LART.ERSATTNING = LONTILL.ERSATTNING.
 END.

 FOR EACH TRAKTATAB WHERE TRAKTATAB.TRAAVTAL = "K":
  
     CREATE LART.
     ASSIGN LART.TILLAGG = TRAKTATAB.TRAKTKOD
     LART.LTEXT = TRAKTATAB.FORKL
     LART.ENHET = "ST"
     LART.ERSATTNING = TRAKTATAB.ERSATTNING.
 
 END.
 FOR EACH OVERKOD WHERE OVERKOD.KOD = "T":
     CREATE LART.
     ASSIGN LART.TILLAGG = OVERKOD.OVERTIDTILL
     LART.LTEXT = OVERKOD.LONKODTEXT
     LART.ENHET = OVERKOD.ENHET
     LART.ERSATTNING = OVERKOD.ERSATTNING.
 
 END.
 FOR EACH BERKOD WHERE BERKOD.BEREDSKAPSAVTAL = "T1":
     CREATE LART.
     ASSIGN LART.TILLAGG = BERKOD.BEREDSKAP
     LART.LTEXT = BERKOD.LONKODTEXT
     LART.ENHET = BERKOD.ENHET
     LART.ERSATTNING = BERKOD.ERSATTNING.
 
 END.
 FOR EACH FVARO:
     
     FIND FIRST AONRTAB WHERE AONRTAB.AONR = FVARO.AONR AND AONRTAB.DELNR = 0 NO-LOCK NO-ERROR.
     CREATE LART.
     ASSIGN LART.TILLAGG = FVARO.FRKOD
     LART.LTEXT = AONRTAB.ORT
     LART.ENHET = "TI"
     LART.ERSATTNING = 0. 
 END.
 OUTPUT TO A:\LARTER.D.
FOR EACH LART BY LART.TILLAGG:
   DISPLAY LART.TILLAGG LART.LTEXT FORMAT "X(30)" LART.ENHET LART.ERSATTNING.
END.


            

