OPEN QUERY AOQ FOR EACH AONRTAB WHERE AONRTAB.BESTID = "101" NO-LOCK.
DO TRANSACTION:
   GET FIRST AOQ EXCLUSIVE-LOCK.
   AONRTAB.BESTID = "1".
END.
REPEAT:
   DO TRANSACTION:
      GET NEXT AOQ EXCLUSIVE-LOCK.
      IF AVAILABLE AONRTAB THEN AONRTAB.BESTID = "1".
      ELSE LEAVE.
   END.
END.

OPEN QUERY PLQ FOR EACH PLANNRTAB WHERE PLANNRTAB.BESTID = "101" NO-LOCK.
DO TRANSACTION:
   GET FIRST PLQ EXCLUSIVE-LOCK.
   PLANNRTAB.BESTID = "1".
END.
REPEAT:
   DO TRANSACTION:
      GET NEXT PLQ EXCLUSIVE-LOCK.
      IF AVAILABLE PLANNRTAB THEN PLANNRTAB.BESTID = "1".
      ELSE LEAVE.
   END.
END.

OPEN QUERY KAQ FOR EACH FASTSPEC WHERE FASTSPEC.BESTID = "101" NO-LOCK.
DO TRANSACTION:
   GET FIRST KAQ EXCLUSIVE-LOCK.
   FASTSPEC.BESTID = "1".
END.
REPEAT:
   DO TRANSACTION:
      GET NEXT KAQ EXCLUSIVE-LOCK.
      IF AVAILABLE FASTSPEC THEN FASTSPEC.BESTID = "1".
      ELSE LEAVE.
   END.
END.
