&ANALYZE-SUSPEND _VERSION-NUMBER UIB_v7r11 GUI
&ANALYZE-RESUME
/* Connected Databases 
          RT               PROGRESS
*/
&Scoped-define WINDOW-NAME    DIALOG-2
&Scoped-define FRAME-NAME     DIALOG-2
&ANALYZE-SUSPEND _UIB-CODE-BLOCK _CUSTOM _DEFINITIONS DIALOG-2 
/*------------------------------------------------------------------------

  File: 

  Description: 

  Input Parameters:
      <none>

  Output Parameters:
      <none>

  Author: 

  Created: 95/05/03 -  9:26 am

------------------------------------------------------------------------*/
/*          This .W file was created with the Progress UIB.             */
/*----------------------------------------------------------------------*/

/* ***************************  Definitions  ************************** */

/* Parameters Definitions ---                                           */

/* Local Variable Definitions ---                                       */
&Scoped-define NEW 
DEFINE SHARED VARIABLE globforetag LIKE FORETAG.FORETAG NO-UNDO.
DEFINE SHARED VARIABLE aonrrec AS RECID NO-UNDO.
DEFINE SHARED VARIABLE musz AS LOGICAL NO-UNDO.
DEFINE SHARED VARIABLE regvnr AS INTEGER FORMAT "999" NO-UNDO.
DEFINE SHARED VARIABLE regdagnamn AS CHARACTER FORMAT "X(3)" NO-UNDO.        
DEFINE SHARED VARIABLE regdatum AS DATE NO-UNDO.
DEFINE VARIABLE status-ok AS LOGICAL NO-UNDO.
DEFINE VARIABLE org LIKE OMRADETAB.OMRADE NO-UNDO.
DEFINE VARIABLE my1hand AS WIDGET-HANDL NO-UNDO.
DEFINE BUFFER aonrbuff FOR AONRTAB.
DEFINE TEMP-TABLE besttemp
   FIELD BBESTID LIKE BESTTAB.BESTID
   FIELD BBESTNAMN LIKE BESTTAB.BESTNAMN 
   INDEX BBEST IS PRIMARY BBESTID ASCENDING
   INDEX BBESTN BBESTNAMN ASCENDING.
DEFINE QUERY aq FOR AUTOMREG.
DEFINE QUERY bq FOR BESTTAB.
DEFINE QUERY oq FOR OMRADETAB.
/* _UIB-CODE-BLOCK-END */
&ANALYZE-RESUME



/* ********************  Preprocessor Definitions  ******************** */

/* Name of first Frame and/or Browse (alphabetically)                   */
&Scoped-define FRAME-NAME  DIALOG-2
&Scoped-define BROWSE-NAME BRW_ANL

/* Custom List Definitions                                              */
&Scoped-define LIST-1 
&Scoped-define LIST-2 
&Scoped-define LIST-3 

/* Definitions for BROWSE BRW_ANL                                       */
&Scoped-define FIELDS-IN-QUERY-BRW_ANL ANLAGGNING.ANLNR ~
ANLAGGNING.BENAMNING 
&Scoped-define OPEN-QUERY-BRW_ANL OPEN QUERY BRW_ANL FOR EACH ANLAGGNING NO-LOCK INDEXED-REPOSITION.
&Scoped-define FIRST-TABLE-IN-QUERY-BRW_ANL ANLAGGNING
&Scoped-define TABLES-IN-QUERY-BRW_ANL ANLAGGNING 

/* Definitions for BROWSE BRW_ARBAN                                     */
&Scoped-define FIELDS-IN-QUERY-BRW_ARBAN PERSONALTAB.PERSONALKOD ~
PERSONALTAB.EFTERNAMN 
&Scoped-define OPEN-QUERY-BRW_ARBAN OPEN QUERY BRW_ARBAN FOR EACH PERSONALTAB NO-LOCK INDEXED-REPOSITION.
&Scoped-define FIRST-TABLE-IN-QUERY-BRW_ARBAN PERSONALTAB
&Scoped-define TABLES-IN-QUERY-BRW_ARBAN PERSONALTAB 

/* Definitions for BROWSE BRW_ARBART                                    */
&Scoped-define FIELDS-IN-QUERY-BRW_ARBART ARBETSART.ARBARTKOD ~
ARBETSART.ARBBENAMNING 
&Scoped-define OPEN-QUERY-BRW_ARBART OPEN QUERY BRW_ARBART FOR EACH ARBETSART NO-LOCK INDEXED-REPOSITION.
&Scoped-define FIRST-TABLE-IN-QUERY-BRW_ARBART ARBETSART
&Scoped-define TABLES-IN-QUERY-BRW_ARBART ARBETSART 

/* Definitions for BROWSE BRW_BERED                                     */
&Scoped-define FIELDS-IN-QUERY-BRW_BERED PERSONALTAB.PERSONALKOD ~
PERSONALTAB.EFTERNAMN 
&Scoped-define OPEN-QUERY-BRW_BERED OPEN QUERY BRW_BERED FOR EACH PERSONALTAB NO-LOCK INDEXED-REPOSITION.
&Scoped-define FIRST-TABLE-IN-QUERY-BRW_BERED PERSONALTAB
&Scoped-define TABLES-IN-QUERY-BRW_BERED PERSONALTAB 

/* Definitions for BROWSE BRW_PRIO                                      */
&Scoped-define FIELDS-IN-QUERY-BRW_PRIO PRIORITET.PKOD ~
PRIORITET.P-BENAMNING 
&Scoped-define OPEN-QUERY-BRW_PRIO OPEN QUERY BRW_PRIO FOR EACH PRIORITET NO-LOCK INDEXED-REPOSITION.
&Scoped-define FIRST-TABLE-IN-QUERY-BRW_PRIO PRIORITET
&Scoped-define TABLES-IN-QUERY-BRW_PRIO PRIORITET 

/* Definitions for DIALOG-BOX DIALOG-2                                  */
&Scoped-define FIELDS-IN-QUERY-DIALOG-2 
&Scoped-define ENABLED-FIELDS-IN-QUERY-DIALOG-2 
&Scoped-define OPEN-BROWSERS-IN-QUERY-DIALOG-2 ~
    ~{&OPEN-QUERY-BRW_ANL}~
    ~{&OPEN-QUERY-BRW_ARBAN}~
    ~{&OPEN-QUERY-BRW_ARBART}~
    ~{&OPEN-QUERY-BRW_BERED}~
    ~{&OPEN-QUERY-BRW_PRIO}

/* ***********************  Control Definitions  ********************** */

/* Define a dialog box                                                  */

/* Definitions of the field level widgets                               */
DEFINE BUTTON BTN_AVB AUTO-END-KEY 
     LABEL "Avbryt":L 
     SIZE 12 BY 2.

DEFINE BUTTON BTN_FVE 
     LABEL "-" 
     SIZE 2.5 BY .77.

DEFINE BUTTON BTN_FVE-2 
     LABEL "-" 
     SIZE 2.5 BY .77.

DEFINE BUTTON BTN_NVE 
     LABEL "+" 
     SIZE 2.5 BY .77.

DEFINE BUTTON BTN_NVE-2 
     LABEL "+" 
     SIZE 2.5 BY .77.

DEFINE BUTTON BTN_OK AUTO-GO 
     LABEL "Ok":L 
     SIZE 12 BY 2.

DEFINE VARIABLE CMB_BESORG AS CHARACTER FORMAT "X(16)":U 
     LABEL "BESTÄLLARE/KUND" 
     VIEW-AS COMBO-BOX INNER-LINES 5
     LIST-ITEMS "","" 
     SIZE 20 BY 1
     BGCOLOR 8  NO-UNDO.

DEFINE VARIABLE CMB_DEBPR AS CHARACTER FORMAT "X(9)":U 
     LABEL "DEBITERING" 
     VIEW-AS COMBO-BOX INNER-LINES 5
     LIST-ITEMS "","" 
     SIZE 12 BY 1
     BGCOLOR 8  NO-UNDO.

DEFINE VARIABLE CMB_OMR AS CHARACTER FORMAT "X(256)":U 
     LABEL "UTFÖRANDE OMR" 
     VIEW-AS COMBO-BOX INNER-LINES 5
     LIST-ITEMS "","" 
     SIZE 22.5 BY 1
     BGCOLOR 8  NO-UNDO.

DEFINE VARIABLE CMB_SLDAG AS CHARACTER FORMAT "X(3)":U 
     LABEL "DAG" 
     VIEW-AS COMBO-BOX INNER-LINES 5
     LIST-ITEMS "MÅN","TIS","ONS","TOR","FRE","LÖR","SÖN" 
     SIZE 7 BY 1
     BGCOLOR 8  NO-UNDO.

DEFINE VARIABLE CMB_STDAG AS CHARACTER FORMAT "X(3)":U 
     LABEL "DAG" 
     VIEW-AS COMBO-BOX INNER-LINES 5
     LIST-ITEMS "MÅN ","TIS","ONS","TOR","FRE","LÖR","SÖN" 
     SIZE 7 BY 1
     BGCOLOR 8  NO-UNDO.

DEFINE VARIABLE CMB_TRAK AS INTEGER FORMAT "9":U INITIAL 0 
     LABEL "TRAKT.ZON" 
     VIEW-AS COMBO-BOX INNER-LINES 5
     LIST-ITEMS "0","1" 
     SIZE 5.13 BY 1
     BGCOLOR 8  NO-UNDO.

DEFINE VARIABLE FILL-IN_ANLNR AS CHARACTER FORMAT "X.XX.XXX.XXXX.XXXXX" 
     LABEL "ANL.NR." 
     VIEW-AS FILL-IN 
     SIZE 20 BY 1
     BGCOLOR 8 .

DEFINE VARIABLE FILL-IN_AONR AS CHARACTER FORMAT "X(6)" 
     LABEL "AONR" 
     VIEW-AS FILL-IN 
     SIZE 7 BY 1
     BGCOLOR 8 .

DEFINE VARIABLE FILL-IN_ARBANSVARIG AS CHARACTER FORMAT "x(5)" 
     LABEL "ARBETSANSVARIG" 
     VIEW-AS FILL-IN 
     SIZE 6 BY 1
     BGCOLOR 8 .

DEFINE VARIABLE FILL-IN_ARBARTKOD AS INTEGER FORMAT ">>" INITIAL 0 
     LABEL "ARBETSART" 
     VIEW-AS FILL-IN 
     SIZE 3 BY 1
     BGCOLOR 8 .

DEFINE VARIABLE FILL-IN_ARBUPPG AS CHARACTER FORMAT "x(25)" 
     LABEL "ARBETSUPPGIFT" 
     VIEW-AS FILL-IN 
     SIZE 26 BY 1
     BGCOLOR 8 .

DEFINE VARIABLE FILL-IN_ARBUPPG-2 AS CHARACTER FORMAT "x(25)" 
     VIEW-AS FILL-IN 
     SIZE 26 BY 1
     BGCOLOR 8 .

DEFINE VARIABLE FILL-IN_BEREDARE AS CHARACTER FORMAT "x(5)" 
     LABEL "BEREDARE/PROJEKTÖR" 
     VIEW-AS FILL-IN 
     SIZE 6 BY 1
     BGCOLOR 8 .

DEFINE VARIABLE FILL-IN_DELNR AS INTEGER FORMAT "999" INITIAL 0 
     LABEL "DELNR" 
     VIEW-AS FILL-IN 
     SIZE 4 BY 1
     BGCOLOR 8 .

DEFINE VARIABLE FILL-IN_ORT AS CHARACTER FORMAT "x(40)" 
     LABEL "ORT/BENÄMNING" 
     VIEW-AS FILL-IN 
     SIZE 41 BY 1
     BGCOLOR 8 .

DEFINE VARIABLE FILL-IN_PKOD AS INTEGER FORMAT ">>" INITIAL 0 
     LABEL "PRIORITET" 
     VIEW-AS FILL-IN 
     SIZE 3 BY 1
     BGCOLOR 8 .

DEFINE VARIABLE FILL-IN_SLUTVNR AS INTEGER FORMAT "999" INITIAL 0 
     LABEL "SLUT  VNR" 
     VIEW-AS FILL-IN 
     SIZE 4 BY 1
     BGCOLOR 8 .

DEFINE VARIABLE FILL-IN_STARTVNR AS INTEGER FORMAT "999" INITIAL 0 
     LABEL "START VNR" 
     VIEW-AS FILL-IN 
     SIZE 4 BY 1
     BGCOLOR 8 .

DEFINE VARIABLE FILL-IN_TRAKTAMENTE AS INTEGER FORMAT "99" INITIAL 0 
     LABEL "TRAKT.ZON" 
     VIEW-AS FILL-IN 
     SIZE 3 BY 1
     BGCOLOR 8 .

DEFINE VARIABLE FILL-IN_UTRYCKNING AS LOGICAL FORMAT "JA/NEJ" INITIAL NO 
     LABEL "UTRYCKNING" 
     VIEW-AS FILL-IN 
     SIZE 4 BY 1
     BGCOLOR 8 .

DEFINE {&NEW} SHARED VARIABLE RAD_FAST AS LOGICAL 
     VIEW-AS RADIO-SET HORIZONTAL
     RADIO-BUTTONS 
          "Tillfälliga Aonr", no,
"Fasta Aonr", yes
     SIZE 33 BY 1
     BGCOLOR 8  NO-UNDO.

DEFINE RECTANGLE RECT-11
     EDGE-PIXELS 4 GRAPHIC-EDGE  
     SIZE 76.5 BY 2
     BGCOLOR 8 .

DEFINE RECTANGLE RECT-12
     EDGE-PIXELS 4 GRAPHIC-EDGE  
     SIZE 43.5 BY 1.5
     BGCOLOR 8 .

DEFINE RECTANGLE RECT-14
     EDGE-PIXELS 4 GRAPHIC-EDGE  
     SIZE 43.5 BY 1.5
     BGCOLOR 8 .

DEFINE RECTANGLE RECT-15
     EDGE-PIXELS 4 GRAPHIC-EDGE  
     SIZE 43.5 BY 1.5
     BGCOLOR 8 .

DEFINE RECTANGLE RECT-16
     EDGE-PIXELS 4 GRAPHIC-EDGE  
     SIZE 43.5 BY 4.09
     BGCOLOR 8 .

DEFINE RECTANGLE RECT-17
     EDGE-PIXELS 4 GRAPHIC-EDGE  
     SIZE 76.5 BY 2
     BGCOLOR 8 .

DEFINE RECTANGLE RECT-21
     EDGE-PIXELS 4 GRAPHIC-EDGE  
     SIZE 76.5 BY 2.95
     BGCOLOR 8 .

DEFINE RECTANGLE RECT-22
     EDGE-PIXELS 4 GRAPHIC-EDGE  
     SIZE 33 BY 8.55
     BGCOLOR 8 .

DEFINE RECTANGLE RECT-6
     EDGE-PIXELS 4 GRAPHIC-EDGE  
     SIZE 76.5 BY 3
     BGCOLOR 8 .

DEFINE RECTANGLE RECT-9
     EDGE-PIXELS 4 GRAPHIC-EDGE  
     SIZE 76.5 BY 4.5
     BGCOLOR 8 .


/* Query definitions                                                    */
DEFINE QUERY BRW_ANL FOR ANLAGGNING SCROLLING.
DEFINE QUERY BRW_ARBAN FOR PERSONALTAB SCROLLING.
DEFINE QUERY BRW_ARBART FOR ARBETSART SCROLLING.
DEFINE QUERY BRW_BERED FOR PERSONALTAB SCROLLING.
DEFINE QUERY BRW_PRIO FOR PRIORITET SCROLLING.

/* Browse definitions                                                   */
DEFINE BROWSE BRW_ANL QUERY BRW_ANL NO-LOCK DISPLAY 
      ANLAGGNING.ANLNR
      ANLAGGNING.BENAMNING
    WITH SIZE 48.38 BY 8.91
         BGCOLOR 8 
         TITLE BGCOLOR 8 "VÄLJ ANLÄGGNING".

DEFINE BROWSE BRW_ARBAN QUERY BRW_ARBAN NO-LOCK DISPLAY 
      PERSONALTAB.PERSONALKOD
      PERSONALTAB.EFTERNAMN
    WITH SIZE 31 BY 7.64
         BGCOLOR 8 
         TITLE BGCOLOR 8 "VÄLJ ARBETSANSVARIG".

DEFINE BROWSE BRW_ARBART QUERY BRW_ARBART NO-LOCK DISPLAY 
      ARBETSART.ARBARTKOD
      ARBETSART.ARBBENAMNING
    WITH SIZE 31 BY 7.64
         BGCOLOR 8 
         TITLE BGCOLOR 8 "VÄLJ ARBETSART".

DEFINE BROWSE BRW_BERED QUERY BRW_BERED NO-LOCK DISPLAY 
      PERSONALTAB.PERSONALKOD
      PERSONALTAB.EFTERNAMN
    WITH SIZE 30.5 BY 7.64
         BGCOLOR 8 
         TITLE BGCOLOR 8 "VÄLJ BEREDARE".

DEFINE BROWSE BRW_PRIO QUERY BRW_PRIO NO-LOCK DISPLAY 
      PRIORITET.PKOD
      PRIORITET.P-BENAMNING
    WITH SIZE 31 BY 7.64
         BGCOLOR 8 
         TITLE BGCOLOR 8 "VÄLJ PRIORITET".


/* ************************  Frame Definitions  *********************** */

DEFINE FRAME DIALOG-2
     CMB_OMR AT ROW 1.27 COL 17 COLON-ALIGNED
     BRW_ANL AT ROW 1.36 COL 14.75
     FILL-IN_AONR AT ROW 2.5 COL 17 COLON-ALIGNED
     FILL-IN_DELNR AT ROW 2.5 COL 35.25 COLON-ALIGNED
     FILL-IN_ORT AT ROW 4.5 COL 17 COLON-ALIGNED
     FILL-IN_ARBUPPG AT ROW 6 COL 17 COLON-ALIGNED
     FILL-IN_ARBUPPG-2 AT ROW 7 COL 17 COLON-ALIGNED NO-LABEL
     CMB_BESORG AT ROW 9 COL 17 COLON-ALIGNED
     CMB_DEBPR AT ROW 9 COL 50 COLON-ALIGNED
     FILL-IN_ANLNR AT ROW 10.77 COL 17 COLON-ALIGNED
     BRW_ARBAN AT ROW 11 COL 45.5
     BRW_ARBART AT ROW 11 COL 45.5
     BRW_BERED AT ROW 11 COL 45.5
     BRW_PRIO AT ROW 11 COL 45.5
     CMB_TRAK AT ROW 12.18 COL 17 COLON-ALIGNED
     FILL-IN_UTRYCKNING AT ROW 12.27 COL 35.25 COLON-ALIGNED
     FILL-IN_PKOD AT ROW 13.73 COL 35.25 COLON-ALIGNED
     FILL-IN_ARBARTKOD AT ROW 13.77 COL 17 COLON-ALIGNED
     BTN_NVE AT ROW 15.3 COL 23.88
     FILL-IN_STARTVNR AT ROW 15.55 COL 17 COLON-ALIGNED
     CMB_STDAG AT ROW 15.55 COL 34 COLON-ALIGNED
     BTN_FVE AT ROW 16.2 COL 23.88
     BTN_NVE-2 AT ROW 17.14 COL 23.88
     FILL-IN_SLUTVNR AT ROW 17.27 COL 16.88 COLON-ALIGNED
     CMB_SLDAG AT ROW 17.27 COL 33.88 COLON-ALIGNED
     BTN_FVE-2 AT ROW 17.95 COL 23.88
     FILL-IN_BEREDARE AT ROW 19.55 COL 20 COLON-ALIGNED
     FILL-IN_ARBANSVARIG AT ROW 19.55 COL 50 COLON-ALIGNED
     FILL-IN_TRAKTAMENTE AT ROW 21 COL 70.75 COLON-ALIGNED
     BTN_OK AT ROW 21.55 COL 15.63
     BTN_AVB AT ROW 21.55 COL 48.63
     RAD_FAST AT ROW 23 COL 1 NO-LABEL
     RECT-6 AT ROW 1 COL 1
     RECT-9 AT ROW 4 COL 1
     RECT-11 AT ROW 8.5 COL 1
     RECT-12 AT ROW 10.5 COL 1
     RECT-22 AT ROW 10.5 COL 44.5
     RECT-14 AT ROW 12 COL 1
     RECT-15 AT ROW 13.5 COL 1
     RECT-16 AT ROW 15 COL 1
     RECT-17 AT ROW 19.05 COL 1
     RECT-21 AT ROW 21.05 COL 1
     SPACE(0.50) SKIP(0.00)
    WITH VIEW-AS DIALOG-BOX KEEP-TAB-ORDER 
         SIDE-LABELS NO-UNDERLINE THREE-D SCROLLABLE 
         TITLE "Ändra arbetsorder":L.

 


/* ***************  Runtime Attributes and UIB Settings  ************** */

&ANALYZE-SUSPEND _RUN-TIME-ATTRIBUTES
ASSIGN 
       FRAME DIALOG-2:SCROLLABLE       = FALSE.

ASSIGN 
       BRW_ANL:HIDDEN  IN FRAME DIALOG-2            = TRUE.

ASSIGN 
       BRW_ARBAN:HIDDEN  IN FRAME DIALOG-2            = TRUE
       BRW_ARBAN:MAX-DATA-GUESS IN FRAME DIALOG-2     = 300.

ASSIGN 
       BRW_ARBART:HIDDEN  IN FRAME DIALOG-2            = TRUE.

ASSIGN 
       BRW_BERED:HIDDEN  IN FRAME DIALOG-2            = TRUE
       BRW_BERED:MAX-DATA-GUESS IN FRAME DIALOG-2     = 300.

ASSIGN 
       BRW_PRIO:HIDDEN  IN FRAME DIALOG-2            = TRUE.

/* SETTINGS FOR FILL-IN FILL-IN_AONR IN FRAME DIALOG-2
   NO-ENABLE                                                            */
/* SETTINGS FOR FILL-IN FILL-IN_DELNR IN FRAME DIALOG-2
   NO-ENABLE                                                            */
/* SETTINGS FOR FILL-IN FILL-IN_TRAKTAMENTE IN FRAME DIALOG-2
   NO-DISPLAY NO-ENABLE                                                 */
ASSIGN 
       FILL-IN_TRAKTAMENTE:HIDDEN IN FRAME DIALOG-2           = TRUE.

/* SETTINGS FOR RADIO-SET RAD_FAST IN FRAME DIALOG-2
   NO-DISPLAY SHARED NO-ENABLE                                          */
ASSIGN 
       RAD_FAST:HIDDEN IN FRAME DIALOG-2           = TRUE.

/* _RUN-TIME-ATTRIBUTES-END */
&ANALYZE-RESUME


/* Setting information for Queries and Browse Widgets fields            */

&ANALYZE-SUSPEND _QUERY-BLOCK BROWSE BRW_ANL
/* Query rebuild information for BROWSE BRW_ANL
     _TblList          = "rt.ANLAGGNING"
     _Options          = "NO-LOCK INDEXED-REPOSITION"
     _OrdList          = ""
     _FldNameList[1]   = rt.ANLAGGNING.ANLNR
     _FldNameList[2]   = rt.ANLAGGNING.BENAMNING
     _Query            is OPENED
*/  /* BROWSE BRW_ANL */
&ANALYZE-RESUME

&ANALYZE-SUSPEND _QUERY-BLOCK BROWSE BRW_ARBAN
/* Query rebuild information for BROWSE BRW_ARBAN
     _TblList          = "rt.PERSONALTAB"
     _Options          = "NO-LOCK INDEXED-REPOSITION"
     _OrdList          = ""
     _FldNameList[1]   = rt.PERSONALTAB.PERSONALKOD
     _FldNameList[2]   = rt.PERSONALTAB.EFTERNAMN
     _Query            is OPENED
*/  /* BROWSE BRW_ARBAN */
&ANALYZE-RESUME

&ANALYZE-SUSPEND _QUERY-BLOCK BROWSE BRW_ARBART
/* Query rebuild information for BROWSE BRW_ARBART
     _TblList          = "rt.ARBETSART"
     _Options          = "NO-LOCK INDEXED-REPOSITION"
     _OrdList          = ""
     _FldNameList[1]   = rt.ARBETSART.ARBARTKOD
     _FldNameList[2]   = rt.ARBETSART.ARBBENAMNING
     _Query            is OPENED
*/  /* BROWSE BRW_ARBART */
&ANALYZE-RESUME

&ANALYZE-SUSPEND _QUERY-BLOCK BROWSE BRW_BERED
/* Query rebuild information for BROWSE BRW_BERED
     _TblList          = "rt.PERSONALTAB"
     _Options          = "NO-LOCK INDEXED-REPOSITION"
     _OrdList          = ""
     _FldNameList[1]   = rt.PERSONALTAB.PERSONALKOD
     _FldNameList[2]   = rt.PERSONALTAB.EFTERNAMN
     _Query            is OPENED
*/  /* BROWSE BRW_BERED */
&ANALYZE-RESUME

&ANALYZE-SUSPEND _QUERY-BLOCK BROWSE BRW_PRIO
/* Query rebuild information for BROWSE BRW_PRIO
     _TblList          = "rt.PRIORITET"
     _Options          = "NO-LOCK INDEXED-REPOSITION"
     _OrdList          = ""
     _FldNameList[1]   = rt.PRIORITET.PKOD
     _FldNameList[2]   = rt.PRIORITET.P-BENAMNING
     _Query            is OPENED
*/  /* BROWSE BRW_PRIO */
&ANALYZE-RESUME

&ANALYZE-SUSPEND _QUERY-BLOCK DIALOG-BOX DIALOG-2
/* Query rebuild information for DIALOG-BOX DIALOG-2
     _TblList          = ""
     _Options          = "NO-LOCK"
     _OrdList          = ""
     _Query            is NOT OPENED
*/  /* DIALOG-BOX DIALOG-2 */
&ANALYZE-RESUME

 



/* ************************  Control Triggers  ************************ */

&Scoped-define SELF-NAME DIALOG-2
&ANALYZE-SUSPEND _UIB-CODE-BLOCK _CONTROL DIALOG-2 DIALOG-2
ON END-ERROR OF FRAME DIALOG-2 /* Ändra arbetsorder */
DO:
   musz = TRUE.
   RETURN.
END.

/* _UIB-CODE-BLOCK-END */
&ANALYZE-RESUME


&ANALYZE-SUSPEND _UIB-CODE-BLOCK _CONTROL DIALOG-2 DIALOG-2
ON ENDKEY OF FRAME DIALOG-2 /* Ändra arbetsorder */
DO:
   musz = TRUE.
   RETURN.
END.

/* _UIB-CODE-BLOCK-END */
&ANALYZE-RESUME


&Scoped-define BROWSE-NAME BRW_ANL
&Scoped-define SELF-NAME BRW_ANL
&ANALYZE-SUSPEND _UIB-CODE-BLOCK _CONTROL BRW_ANL DIALOG-2
ON LEAVE OF BRW_ANL IN FRAME DIALOG-2 /* VÄLJ ANLÄGGNING */
DO:
   ASSIGN FILL-IN_ANLNR = INPUT FILL-IN_ANLNR.
   FIND FIRST ANLAGGNING WHERE ANLAGGNING.ANLNR = FILL-IN_ANLNR 
   USE-INDEX ANLAGGNING NO-LOCK NO-ERROR.
   IF NOT AVAILABLE ANLAGGNING THEN DO:
      MESSAGE 
      "INGEN ANLÄGGNING MED NR " FILL-IN_ANLNR " FINNS I REGISTRET!" VIEW-AS ALERT-BOX.
      RETURN NO-APPLY.
   END.  
   ASSIGN
   CMB_BESORG:HIDDEN = FALSE 
   CMB_DEBPR:HIDDEN = FALSE 
   FILL-IN_ARBUPPG:HIDDEN = FALSE 
   FILL-IN_ARBUPPG-2:HIDDEN = FALSE 
   FILL-IN_ORT:HIDDEN = FALSE
   BRW_ANL:HIDDEN = TRUE. 
END.

/* _UIB-CODE-BLOCK-END */
&ANALYZE-RESUME


&ANALYZE-SUSPEND _UIB-CODE-BLOCK _CONTROL BRW_ANL DIALOG-2
ON VALUE-CHANGED OF BRW_ANL IN FRAME DIALOG-2 /* VÄLJ ANLÄGGNING */
DO: 
   status-ok = BRW_ANL:SELECT-FOCUSED-ROW() IN FRAME {&FRAME-NAME}.
   ASSIGN FILL-IN_ANLNR  = ANLAGGNING.ANLNR.
   DISPLAY FILL-IN_ANLNR WITH FRAME {&FRAME-NAME}.
END.

/* _UIB-CODE-BLOCK-END */
&ANALYZE-RESUME


&Scoped-define BROWSE-NAME BRW_ARBAN
&Scoped-define SELF-NAME BRW_ARBAN
&ANALYZE-SUSPEND _UIB-CODE-BLOCK _CONTROL BRW_ARBAN DIALOG-2
ON LEAVE OF BRW_ARBAN IN FRAME DIALOG-2 /* VÄLJ ARBETSANSVARIG */
DO:
   ASSIGN FILL-IN_ARBANSVARIG = INPUT FILL-IN_ARBANSVARIG.
   FIND FIRST PERSONALTAB WHERE PERSONALTAB.PERSONALKOD = FILL-IN_ARBANSVARIG 
   USE-INDEX PERSONALKOD NO-LOCK NO-ERROR.
   IF NOT AVAILABLE PERSONALTAB THEN DO:
      MESSAGE 
      "INGEN ANSVARIG MED ENHET " FILL-IN_ARBANSVARIG " FINNS I REGISTRET!" VIEW-AS ALERT-BOX.
      RETURN NO-APPLY.
   END.       
   BRW_ARBAN:HIDDEN = TRUE. 
END.

/* _UIB-CODE-BLOCK-END */
&ANALYZE-RESUME


&ANALYZE-SUSPEND _UIB-CODE-BLOCK _CONTROL BRW_ARBAN DIALOG-2
ON VALUE-CHANGED OF BRW_ARBAN IN FRAME DIALOG-2 /* VÄLJ ARBETSANSVARIG */
DO:
   status-ok = BRW_ARBAN:SELECT-FOCUSED-ROW() IN FRAME {&FRAME-NAME}.
   ASSIGN FILL-IN_ARBANSVARIG  = PERSONALTAB.PERSONALKOD.
   DISPLAY FILL-IN_ARBANSVARIG WITH FRAME {&FRAME-NAME}.
END.

/* _UIB-CODE-BLOCK-END */
&ANALYZE-RESUME


&Scoped-define BROWSE-NAME BRW_ARBART
&Scoped-define SELF-NAME BRW_ARBART
&ANALYZE-SUSPEND _UIB-CODE-BLOCK _CONTROL BRW_ARBART DIALOG-2
ON LEAVE OF BRW_ARBART IN FRAME DIALOG-2 /* VÄLJ ARBETSART */
DO:
   ASSIGN FILL-IN_ARBARTKOD = INPUT FILL-IN_ARBARTKOD.
   FIND FIRST ARBETSART WHERE ARBETSART.ARBARTKOD = FILL-IN_ARBARTKOD 
   USE-INDEX ARB NO-LOCK NO-ERROR.
   IF NOT AVAILABLE ARBETSART THEN DO:
      MESSAGE 
      "INGEN ARBETSART MED NR " FILL-IN_ARBARTKOD " FINNS I REGISTRET!" VIEW-AS ALERT-BOX.
      RETURN NO-APPLY.
   END.      
   BRW_ARBART:HIDDEN = TRUE. 
END.

/* _UIB-CODE-BLOCK-END */
&ANALYZE-RESUME


&ANALYZE-SUSPEND _UIB-CODE-BLOCK _CONTROL BRW_ARBART DIALOG-2
ON VALUE-CHANGED OF BRW_ARBART IN FRAME DIALOG-2 /* VÄLJ ARBETSART */
DO:                     
   status-ok = BRW_ARBART:SELECT-FOCUSED-ROW() IN FRAME {&FRAME-NAME}.
   ASSIGN FILL-IN_ARBARTKOD  = ARBETSART.ARBARTKOD.
   DISPLAY FILL-IN_ARBARTKOD WITH FRAME {&FRAME-NAME}.
END.

/* _UIB-CODE-BLOCK-END */
&ANALYZE-RESUME


&Scoped-define BROWSE-NAME BRW_BERED
&Scoped-define SELF-NAME BRW_BERED
&ANALYZE-SUSPEND _UIB-CODE-BLOCK _CONTROL BRW_BERED DIALOG-2
ON LEAVE OF BRW_BERED IN FRAME DIALOG-2 /* VÄLJ BEREDARE */
DO:
   ASSIGN FILL-IN_BEREDARE = INPUT FILL-IN_BEREDARE.
   FIND FIRST PERSONALTAB WHERE PERSONALTAB.PERSONALKOD = FILL-IN_BEREDARE 
   USE-INDEX PERSONALKOD NO-LOCK NO-ERROR.
   IF NOT AVAILABLE PERSONALTAB THEN DO:
      MESSAGE 
      "INGEN BEREDARE/PROJEKTÖR MED ENHET " FILL-IN_BEREDARE " FINNS I REGISTRET!" 
      VIEW-AS ALERT-BOX.
      RETURN NO-APPLY.
   END.       
   BRW_BERED:HIDDEN = TRUE. 
END.

/* _UIB-CODE-BLOCK-END */
&ANALYZE-RESUME


&ANALYZE-SUSPEND _UIB-CODE-BLOCK _CONTROL BRW_BERED DIALOG-2
ON VALUE-CHANGED OF BRW_BERED IN FRAME DIALOG-2 /* VÄLJ BEREDARE */
DO:
   status-ok = BRW_BERED:SELECT-FOCUSED-ROW() IN FRAME {&FRAME-NAME}.
   ASSIGN FILL-IN_BEREDARE  = PERSONALTAB.PERSONALKOD.
   DISPLAY FILL-IN_BEREDARE WITH FRAME {&FRAME-NAME}.
END.

/* _UIB-CODE-BLOCK-END */
&ANALYZE-RESUME


&Scoped-define BROWSE-NAME BRW_PRIO
&Scoped-define SELF-NAME BRW_PRIO
&ANALYZE-SUSPEND _UIB-CODE-BLOCK _CONTROL BRW_PRIO DIALOG-2
ON LEAVE OF BRW_PRIO IN FRAME DIALOG-2 /* VÄLJ PRIORITET */
DO:
   ASSIGN FILL-IN_PKOD = INPUT FILL-IN_PKOD.
   FIND FIRST PRIORITET WHERE PRIORITET.PKOD = FILL-IN_PKOD 
   USE-INDEX PRI NO-LOCK NO-ERROR.
   IF NOT AVAILABLE PRIORITET THEN DO:
      MESSAGE 
      "INGEN PRIORITET MED NR " FILL-IN_PKOD " FINNS I REGISTRET!" VIEW-AS ALERT-BOX.
      RETURN NO-APPLY.
   END.       
   BRW_PRIO:HIDDEN = TRUE. 
END.

/* _UIB-CODE-BLOCK-END */
&ANALYZE-RESUME


&ANALYZE-SUSPEND _UIB-CODE-BLOCK _CONTROL BRW_PRIO DIALOG-2
ON VALUE-CHANGED OF BRW_PRIO IN FRAME DIALOG-2 /* VÄLJ PRIORITET */
DO:
   status-ok = BRW_PRIO:SELECT-FOCUSED-ROW() IN FRAME {&FRAME-NAME}.
   ASSIGN FILL-IN_PKOD  = PRIORITET.PKOD.
   DISPLAY FILL-IN_PKOD WITH FRAME {&FRAME-NAME}.
END.

/* _UIB-CODE-BLOCK-END */
&ANALYZE-RESUME


&Scoped-define SELF-NAME BTN_AVB
&ANALYZE-SUSPEND _UIB-CODE-BLOCK _CONTROL BTN_AVB DIALOG-2
ON CHOOSE OF BTN_AVB IN FRAME DIALOG-2 /* Avbryt */
DO:   
   musz = TRUE.
   RETURN.
END.

/* _UIB-CODE-BLOCK-END */
&ANALYZE-RESUME


&Scoped-define SELF-NAME BTN_FVE
&ANALYZE-SUSPEND _UIB-CODE-BLOCK _CONTROL BTN_FVE DIALOG-2
ON CHOOSE OF BTN_FVE IN FRAME DIALOG-2 /* - */
DO: 
   DEFINE VARIABLE regdd AS CHARACTER NO-UNDO.
   ASSIGN
   FILL-IN_STARTVNR = INPUT FILL-IN_STARTVNR      
   regdd = regdagnamn
   regdagnamn = "ONS"
   regvnr = FILL-IN_STARTVNR.
   RUN VECODAT.P.
   ASSIGN
   regdagnamn = regdd
   regdatum = regdatum - 7.   
   RUN REGVEC.P.
   FILL-IN_STARTVNR = regvnr.
   DISPLAY FILL-IN_STARTVNR WITH FRAME {&FRAME-NAME}.       
END.

/* _UIB-CODE-BLOCK-END */
&ANALYZE-RESUME


&Scoped-define SELF-NAME BTN_FVE-2
&ANALYZE-SUSPEND _UIB-CODE-BLOCK _CONTROL BTN_FVE-2 DIALOG-2
ON CHOOSE OF BTN_FVE-2 IN FRAME DIALOG-2 /* - */
DO: 
   DEFINE VARIABLE regdd AS CHARACTER NO-UNDO.
   ASSIGN
   FILL-IN_SLUTVNR = INPUT FILL-IN_SLUTVNR       
   regdd = regdagnamn
   regdagnamn = "ONS"
   regvnr = FILL-IN_SLUTVNR.
   RUN VECODAT.P.
   ASSIGN
   regdagnamn = regdd
   regdatum = regdatum - 7.   
   RUN REGVEC.P.
   FILL-IN_SLUTVNR = regvnr.
   DISPLAY FILL-IN_SLUTVNR WITH FRAME {&FRAME-NAME}.       
END.

/* _UIB-CODE-BLOCK-END */
&ANALYZE-RESUME


&Scoped-define SELF-NAME BTN_NVE
&ANALYZE-SUSPEND _UIB-CODE-BLOCK _CONTROL BTN_NVE DIALOG-2
ON CHOOSE OF BTN_NVE IN FRAME DIALOG-2 /* + */
DO:
   DEFINE VARIABLE regdd AS CHARACTER NO-UNDO.
   ASSIGN
   FILL-IN_STARTVNR = INPUT FILL-IN_STARTVNR      
   regdd = regdagnamn
   regdagnamn = "ONS"
   regvnr = FILL-IN_STARTVNR.
   RUN VECODAT.P.
   ASSIGN
   regdagnamn = regdd
   regdatum = regdatum + 7.   
   RUN REGVEC.P.
   FILL-IN_STARTVNR = regvnr.
   DISPLAY FILL-IN_STARTVNR WITH FRAME {&FRAME-NAME}.       
END.

/* _UIB-CODE-BLOCK-END */
&ANALYZE-RESUME


&Scoped-define SELF-NAME BTN_NVE-2
&ANALYZE-SUSPEND _UIB-CODE-BLOCK _CONTROL BTN_NVE-2 DIALOG-2
ON CHOOSE OF BTN_NVE-2 IN FRAME DIALOG-2 /* + */
DO:
   DEFINE VARIABLE regdd AS CHARACTER NO-UNDO.
   ASSIGN
   FILL-IN_SLUTVNR = INPUT FILL-IN_SLUTVNR       
   regdd = regdagnamn
   regdagnamn = "ONS"
   regvnr = FILL-IN_SLUTVNR.
   RUN VECODAT.P.
   ASSIGN
   regdagnamn = regdd
   regdatum = regdatum + 7.   
   RUN REGVEC.P.
   FILL-IN_SLUTVNR = regvnr.
   DISPLAY FILL-IN_SLUTVNR WITH FRAME {&FRAME-NAME}.       
END.

/* _UIB-CODE-BLOCK-END */
&ANALYZE-RESUME


&Scoped-define SELF-NAME BTN_OK
&ANALYZE-SUSPEND _UIB-CODE-BLOCK _CONTROL BTN_OK DIALOG-2
ON CHOOSE OF BTN_OK IN FRAME DIALOG-2 /* Ok */
DO:  
   ASSIGN
   musz = FALSE
   CMB_BESORG = INPUT CMB_BESORG
   CMB_DEBPR = INPUT CMB_DEBPR
   CMB_OMR = INPUT CMB_OMR
   CMB_SLDAG = INPUT CMB_SLDAG
   CMB_STDAG = INPUT CMB_STDAG
   FILL-IN_ANLNR = INPUT FILL-IN_ANLNR 
   FILL-IN_AONR = INPUT FILL-IN_AONR 
   FILL-IN_ARBANSVARIG = INPUT FILL-IN_ARBANSVARIG
   FILL-IN_ARBARTKOD = INPUT FILL-IN_ARBARTKOD
   FILL-IN_ARBUPPG = INPUT FILL-IN_ARBUPPG
   FILL-IN_ARBUPPG-2 = INPUT FILL-IN_ARBUPPG-2
   FILL-IN_BEREDARE = INPUT FILL-IN_BEREDARE
   FILL-IN_DELNR = INPUT FILL-IN_DELNR
   FILL-IN_ORT = INPUT FILL-IN_ORT
   FILL-IN_PKOD = INPUT FILL-IN_PKOD 
   FILL-IN_SLUTVNR = INPUT FILL-IN_SLUTVNR
   FILL-IN_STARTVNR = INPUT FILL-IN_STARTVNR
   FILL-IN_TRAKTAMENTE = INPUT CMB_TRAK
   FILL-IN_UTRYCKNING = INPUT FILL-IN_UTRYCKNING. 
     
   FIND FIRST besttemp WHERE besttemp.BBESTNAMN = CMB_BESORG 
   USE-INDEX BBEST NO-LOCK NO-ERROR.
   IF NOT AVAILABLE besttemp THEN DO:
      FIND FIRST besttemp WHERE besttemp.BBESTID = org 
      USE-INDEX BBEST NO-LOCK NO-ERROR.
   END.
   IF FILL-IN_ARBARTKOD = ? OR FILL-IN_ARBARTKOD = 0 THEN DO:
      FIND FIRST ARBETSART USE-INDEX ARB NO-LOCK NO-ERROR.
      ASSIGN FILL-IN_ARBARTKOD = ARBETSART.ARBARTKOD.
   END.   
   IF FILL-IN_PKOD = ? OR FILL-IN_PKOD = 0 THEN DO:
      FIND FIRST PRIORITET USE-INDEX PRI NO-LOCK NO-ERROR.
      ASSIGN FILL-IN_PKOD = PRIORITET.PKOD.
   END.   
   IF FILL-IN_ANLNR = "" THEN DO:
      FIND FIRST ANLAGGNING USE-INDEX ANLAGGNING NO-LOCK NO-ERROR.
      ASSIGN FILL-IN_ANLNR = ANLAGGNING.ANLNR.
   END.     
   DO TRANSACTION:
      FIND AONRTAB WHERE RECID(AONRTAB) = aonrrec EXCLUSIVE-LOCK NO-ERROR.
      ASSIGN AONRTAB.FASTAAONR = RAD_FAST
      AONRTAB.AUTOREG = TRUE
      AONRTAB.ANLNR = FILL-IN_ANLNR
      AONRTAB.AONR = FILL-IN_AONR
      AONRTAB.ARBANSVARIG = FILL-IN_ARBANSVARIG
      AONRTAB.ARBARTKOD = FILL-IN_ARBARTKOD
      AONRTAB.ARBUPPG[1] = FILL-IN_ARBUPPG
      AONRTAB.ARBUPPG[2] = FILL-IN_ARBUPPG-2
      AONRTAB.BEREDARE = FILL-IN_BEREDARE 
      AONRTAB.DELNR = FILL-IN_DELNR
      AONRTAB.OMRADE = org
      AONRTAB.ORT = FILL-IN_ORT
      AONRTAB.PKOD = FILL-IN_PKOD
      AONRTAB.PRISTYP = CMB_DEBPR
      AONRTAB.SLUTDAG = CMB_SLDAG
      AONRTAB.SLUTVNR = FILL-IN_SLUTVNR
      AONRTAB.STARTDAG = CMB_STDAG 
      AONRTAB.STARTVNR = FILL-IN_STARTVNR 
      AONRTAB.TRAKTAMENTE = FILL-IN_TRAKTAMENTE   
      AONRTAB.UTRYCKNING = FILL-IN_UTRYCKNING.  
      IF AVAILABLE besttemp THEN ASSIGN AONRTAB.BESTID = besttemp.BBESTID.
   END.   
   {muswait.i}
 /*  RUN ANMARK.W. */
   FRAME DIALOG-2:HIDDEN = TRUE.
   RETURN. 
END.

/* _UIB-CODE-BLOCK-END */
&ANALYZE-RESUME


&Scoped-define SELF-NAME CMB_BESORG
&ANALYZE-SUSPEND _UIB-CODE-BLOCK _CONTROL CMB_BESORG DIALOG-2
ON LEAVE OF CMB_BESORG IN FRAME DIALOG-2 /* BESTÄLLARE/KUND */
DO:
   CMB_BESORG = INPUT CMB_BESORG.    
END.

/* _UIB-CODE-BLOCK-END */
&ANALYZE-RESUME


&Scoped-define SELF-NAME CMB_DEBPR
&ANALYZE-SUSPEND _UIB-CODE-BLOCK _CONTROL CMB_DEBPR DIALOG-2
ON LEAVE OF CMB_DEBPR IN FRAME DIALOG-2 /* DEBITERING */
DO:
   ASSIGN CMB_DEBPR = INPUT CMB_DEBPR.   
END.

/* _UIB-CODE-BLOCK-END */
&ANALYZE-RESUME


&Scoped-define SELF-NAME CMB_OMR
&ANALYZE-SUSPEND _UIB-CODE-BLOCK _CONTROL CMB_OMR DIALOG-2
ON LEAVE OF CMB_OMR IN FRAME DIALOG-2 /* UTFÖRANDE OMR */
DO:
   CMB_OMR = INPUT CMB_OMR.
   IF CMB_OMR = "" THEN org = "".
   ELSE DO:
      FIND FIRST OMRADETAB WHERE OMRADETAB.NAMN = CMB_OMR USE-INDEX OMRNAMN NO-LOCK NO-ERROR.
      IF NOT AVAILABLE OMRADETAB THEN org = "".
      ELSE org = OMRADETAB.OMRADE.
   END.    
END.

/* _UIB-CODE-BLOCK-END */
&ANALYZE-RESUME


&Scoped-define SELF-NAME CMB_SLDAG
&ANALYZE-SUSPEND _UIB-CODE-BLOCK _CONTROL CMB_SLDAG DIALOG-2
ON ENTRY OF CMB_SLDAG IN FRAME DIALOG-2 /* DAG */
DO:
   RUN goma_UI.
END.

/* _UIB-CODE-BLOCK-END */
&ANALYZE-RESUME


&ANALYZE-SUSPEND _UIB-CODE-BLOCK _CONTROL CMB_SLDAG DIALOG-2
ON LEAVE OF CMB_SLDAG IN FRAME DIALOG-2 /* DAG */
DO:
   ASSIGN CMB_SLDAG = INPUT CMB_SLDAG.  
END.

/* _UIB-CODE-BLOCK-END */
&ANALYZE-RESUME


&Scoped-define SELF-NAME CMB_STDAG
&ANALYZE-SUSPEND _UIB-CODE-BLOCK _CONTROL CMB_STDAG DIALOG-2
ON ENTRY OF CMB_STDAG IN FRAME DIALOG-2 /* DAG */
DO:
   RUN goma_UI.
END.

/* _UIB-CODE-BLOCK-END */
&ANALYZE-RESUME


&ANALYZE-SUSPEND _UIB-CODE-BLOCK _CONTROL CMB_STDAG DIALOG-2
ON LEAVE OF CMB_STDAG IN FRAME DIALOG-2 /* DAG */
DO:
   ASSIGN CMB_STDAG = INPUT CMB_STDAG.
   
END.

/* _UIB-CODE-BLOCK-END */
&ANALYZE-RESUME


&Scoped-define SELF-NAME CMB_TRAK
&ANALYZE-SUSPEND _UIB-CODE-BLOCK _CONTROL CMB_TRAK DIALOG-2
ON VALUE-CHANGED OF CMB_TRAK IN FRAME DIALOG-2 /* TRAKT.ZON */
DO:
   CMB_TRAK = INPUT CMB_TRAK.
   FILL-IN_TRAKTAMENTE = CMB_TRAK.
END.

/* _UIB-CODE-BLOCK-END */
&ANALYZE-RESUME


&Scoped-define SELF-NAME FILL-IN_ANLNR
&ANALYZE-SUSPEND _UIB-CODE-BLOCK _CONTROL FILL-IN_ANLNR DIALOG-2
ON ENTRY OF FILL-IN_ANLNR IN FRAME DIALOG-2 /* ANL.NR. */
DO:
   ASSIGN
   CMB_BESORG:HIDDEN = TRUE
   CMB_DEBPR:HIDDEN = TRUE 
   FILL-IN_ARBUPPG:HIDDEN = TRUE 
   FILL-IN_ARBUPPG-2:HIDDEN = TRUE 
   FILL-IN_ORT:HIDDEN = TRUE
   BRW_ANL:HIDDEN = FALSE
   BRW_ARBAN:HIDDEN = TRUE     
   BRW_ARBART:HIDDEN = TRUE            
   BRW_BERED:HIDDEN = TRUE     
   BRW_PRIO:HIDDEN = TRUE.   
   BRW_ANL:MAX-DATA-GUESS IN FRAME {&FRAME-NAME} = 100.
   FIND FIRST ANLAGGNING WHERE ANLAGGNING.ANLNR = FILL-IN_ANLNR 
   USE-INDEX ANL NO-LOCK NO-ERROR.
  IF NOT AVAILABLE ANLAGGNING THEN DO:
      /*APPLY "HOME" TO BRW_ANL.
      status-ok = BRW_ANL:SELECT-FOCUSED-ROW().*/
   END.
   ELSE DO:
      REPOSITION BRW_ANL TO RECID RECID(ANLAGGNING).
   END.  
END.

/* _UIB-CODE-BLOCK-END */
&ANALYZE-RESUME


&ANALYZE-SUSPEND _UIB-CODE-BLOCK _CONTROL FILL-IN_ANLNR DIALOG-2
ON LEAVE OF FILL-IN_ANLNR IN FRAME DIALOG-2 /* ANL.NR. */
DO:
    ASSIGN FILL-IN_ANLNR = INPUT FILL-IN_ANLNR.
END.

/* _UIB-CODE-BLOCK-END */
&ANALYZE-RESUME


&Scoped-define SELF-NAME FILL-IN_ARBANSVARIG
&ANALYZE-SUSPEND _UIB-CODE-BLOCK _CONTROL FILL-IN_ARBANSVARIG DIALOG-2
ON ENTRY OF FILL-IN_ARBANSVARIG IN FRAME DIALOG-2 /* ARBETSANSVARIG */
DO:
   RUN goma_UI.
   ASSIGN
   BRW_ANL:HIDDEN = TRUE 
   BRW_ARBAN:HIDDEN = FALSE
   BRW_ARBART:HIDDEN = TRUE            
   BRW_BERED:HIDDEN = TRUE     
   BRW_PRIO:HIDDEN = TRUE.  
   BRW_ARBAN:MAX-DATA-GUESS IN FRAME {&FRAME-NAME} = 300. 
   FIND FIRST PERSONALTAB WHERE 
   PERSONALTAB.PERSONALKOD = FILL-IN_ARBANSVARIG 
   USE-INDEX PERSONALKOD NO-LOCK NO-ERROR.
   IF NOT AVAILABLE PERSONALTAB THEN DO:
      /*APPLY "HOME" TO BRW_ARBAN.
      status-ok = BRW_ARBAN:SELECT-FOCUSED-ROW().*/
   END.
   ELSE DO:                               
      REPOSITION BRW_ARBAN TO RECID RECID(PERSONALTAB).
   END.       
END.

/* _UIB-CODE-BLOCK-END */
&ANALYZE-RESUME


&ANALYZE-SUSPEND _UIB-CODE-BLOCK _CONTROL FILL-IN_ARBANSVARIG DIALOG-2
ON LEAVE OF FILL-IN_ARBANSVARIG IN FRAME DIALOG-2 /* ARBETSANSVARIG */
DO:
   ASSIGN FILL-IN_ARBANSVARIG = INPUT FILL-IN_ARBANSVARIG.
END.

/* _UIB-CODE-BLOCK-END */
&ANALYZE-RESUME


&Scoped-define SELF-NAME FILL-IN_ARBARTKOD
&ANALYZE-SUSPEND _UIB-CODE-BLOCK _CONTROL FILL-IN_ARBARTKOD DIALOG-2
ON ENTRY OF FILL-IN_ARBARTKOD IN FRAME DIALOG-2 /* ARBETSART */
DO:                       
   ASSIGN
   BRW_ANL:HIDDEN = TRUE 
   BRW_ARBAN:HIDDEN = TRUE     
   BRW_ARBART:HIDDEN = FALSE      
   BRW_BERED:HIDDEN = TRUE     
   BRW_PRIO:HIDDEN = TRUE.   
   FIND FIRST ARBETSART WHERE ARBETSART.ARBARTKOD = FILL-IN_ARBARTKOD
   USE-INDEX ARB NO-LOCK NO-ERROR.
   IF NOT AVAILABLE ARBETSART  THEN DO:
      /*APPLY "HOME" TO BRW_ARBART.
      status-ok = BRW_ARBART:SELECT-FOCUSED-ROW().*/
   END.
   ELSE DO:                        
      REPOSITION BRW_ARBART TO RECID RECID(ARBETSART).
   END.
END.

/* _UIB-CODE-BLOCK-END */
&ANALYZE-RESUME


&ANALYZE-SUSPEND _UIB-CODE-BLOCK _CONTROL FILL-IN_ARBARTKOD DIALOG-2
ON LEAVE OF FILL-IN_ARBARTKOD IN FRAME DIALOG-2 /* ARBETSART */
DO:
   ASSIGN FILL-IN_ARBARTKOD = INPUT FILL-IN_ARBARTKOD.
END.

/* _UIB-CODE-BLOCK-END */
&ANALYZE-RESUME


&Scoped-define SELF-NAME FILL-IN_ARBUPPG-2
&ANALYZE-SUSPEND _UIB-CODE-BLOCK _CONTROL FILL-IN_ARBUPPG-2 DIALOG-2
ON LEAVE OF FILL-IN_ARBUPPG-2 IN FRAME DIALOG-2
DO:
  ASSIGN FILL-IN_ARBUPPG = INPUT FILL-IN_ARBUPPG 
  FILL-IN_ARBUPPG-2 = INPUT FILL-IN_ARBUPPG-2.
 
END.

/* _UIB-CODE-BLOCK-END */
&ANALYZE-RESUME


&Scoped-define SELF-NAME FILL-IN_BEREDARE
&ANALYZE-SUSPEND _UIB-CODE-BLOCK _CONTROL FILL-IN_BEREDARE DIALOG-2
ON ENTRY OF FILL-IN_BEREDARE IN FRAME DIALOG-2 /* BEREDARE/PROJEKTÖR */
DO:                       
   RUN goma_UI.
   ASSIGN
   BRW_ANL:HIDDEN = TRUE 
   BRW_ARBAN:HIDDEN = TRUE     
   BRW_ARBART:HIDDEN = TRUE            
   BRW_BERED:HIDDEN = FALSE 
   BRW_PRIO:HIDDEN = TRUE.   
   FIND FIRST PERSONALTAB WHERE 
   PERSONALTAB.PERSONALKOD = FILL-IN_BEREDARE 
   USE-INDEX PERSONALKOD NO-LOCK NO-ERROR.   
   IF NOT AVAILABLE PERSONALTAB THEN DO:
      /*APPLY "HOME" TO BRW_BERED.
      status-ok = BRW_BERED:SELECT-FOCUSED-ROW().*/
   END.
   ELSE DO:                                  
      
      REPOSITION BRW_BERED TO RECID RECID(PERSONALTAB).
   END.
END.

/* _UIB-CODE-BLOCK-END */
&ANALYZE-RESUME


&ANALYZE-SUSPEND _UIB-CODE-BLOCK _CONTROL FILL-IN_BEREDARE DIALOG-2
ON LEAVE OF FILL-IN_BEREDARE IN FRAME DIALOG-2 /* BEREDARE/PROJEKTÖR */
DO:
   ASSIGN FILL-IN_BEREDARE = INPUT FILL-IN_BEREDARE.
END.

/* _UIB-CODE-BLOCK-END */
&ANALYZE-RESUME


&Scoped-define SELF-NAME FILL-IN_ORT
&ANALYZE-SUSPEND _UIB-CODE-BLOCK _CONTROL FILL-IN_ORT DIALOG-2
ON LEAVE OF FILL-IN_ORT IN FRAME DIALOG-2 /* ORT/BENÄMNING */
DO:
   ASSIGN FILL-IN_ORT = INPUT FILL-IN_ORT. 
   DISPLAY FILL-IN_ORT WITH FRAME {&FRAME-NAME}.
END.

/* _UIB-CODE-BLOCK-END */
&ANALYZE-RESUME


&Scoped-define SELF-NAME FILL-IN_PKOD
&ANALYZE-SUSPEND _UIB-CODE-BLOCK _CONTROL FILL-IN_PKOD DIALOG-2
ON ENTRY OF FILL-IN_PKOD IN FRAME DIALOG-2 /* PRIORITET */
DO:
   RUN goma_UI.                      
   ASSIGN
   BRW_ANL:HIDDEN = TRUE 
   BRW_ARBAN:HIDDEN = TRUE     
   BRW_ARBART:HIDDEN = TRUE            
   BRW_BERED:HIDDEN = TRUE     
   BRW_PRIO:HIDDEN = FALSE. 
   BRW_PRIO:MAX-DATA-GUESS IN FRAME {&FRAME-NAME} = 100.  
   FIND FIRST PRIORITET WHERE PRIORITET.PKOD = FILL-IN_PKOD USE-INDEX PRI 
   NO-LOCK NO-ERROR.
   IF NOT AVAILABLE PRIORITET THEN DO: 
      musz = musz.
      /*APPLY "HOME" TO BRW_PRIO.
      status-ok = BRW_PRIO:SELECT-FOCUSED-ROW().*/
   END.
   ELSE DO:         
      REPOSITION BRW_PRIO TO RECID RECID(PRIORITET).
   END.   
END.

/* _UIB-CODE-BLOCK-END */
&ANALYZE-RESUME


&ANALYZE-SUSPEND _UIB-CODE-BLOCK _CONTROL FILL-IN_PKOD DIALOG-2
ON LEAVE OF FILL-IN_PKOD IN FRAME DIALOG-2 /* PRIORITET */
DO:
   ASSIGN FILL-IN_PKOD = INPUT FILL-IN_PKOD.
END.

/* _UIB-CODE-BLOCK-END */
&ANALYZE-RESUME


&Scoped-define SELF-NAME FILL-IN_SLUTVNR
&ANALYZE-SUSPEND _UIB-CODE-BLOCK _CONTROL FILL-IN_SLUTVNR DIALOG-2
ON ENTRY OF FILL-IN_SLUTVNR IN FRAME DIALOG-2 /* SLUT  VNR */
DO:
   RUN goma_UI.
END.

/* _UIB-CODE-BLOCK-END */
&ANALYZE-RESUME


&ANALYZE-SUSPEND _UIB-CODE-BLOCK _CONTROL FILL-IN_SLUTVNR DIALOG-2
ON LEAVE OF FILL-IN_SLUTVNR IN FRAME DIALOG-2 /* SLUT  VNR */
DO:
   ASSIGN FILL-IN_SLUTVNR = INPUT FILL-IN_SLUTVNR.
   regvnr = FILL-IN_SLUTVNR.
   RUN VECOKOLL.P.
   IF musz = TRUE THEN DO:
      musz = FALSE.
      RETURN NO-APPLY.
   END.   
   
     
END.

/* _UIB-CODE-BLOCK-END */
&ANALYZE-RESUME


&ANALYZE-SUSPEND _UIB-CODE-BLOCK _CONTROL FILL-IN_SLUTVNR DIALOG-2
ON MOUSE-MENU-CLICK OF FILL-IN_SLUTVNR IN FRAME DIALOG-2 /* SLUT  VNR */
DO:
   ASSIGN
   FILL-IN_SLUTVNR = INPUT FILL-IN_SLUTVNR
   regvnr = INPUT FILL-IN_SLUTVNR
   regdagnamn = CMB_SLDAG.
   RUN VECOKOLL.P.
   regvnr = FILL-IN_SLUTVNR.
   IF musz = TRUE THEN DO:
      musz = FALSE.
      RETURN NO-APPLY.
   END.
   RUN KALENDERN.W.
   FILL-IN_SLUTVNR = regvnr.
   DISPLAY FILL-IN_SLUTVNR WITH FRAME {&FRAME-NAME}.
END.

/* _UIB-CODE-BLOCK-END */
&ANALYZE-RESUME


&Scoped-define SELF-NAME FILL-IN_STARTVNR
&ANALYZE-SUSPEND _UIB-CODE-BLOCK _CONTROL FILL-IN_STARTVNR DIALOG-2
ON ENTRY OF FILL-IN_STARTVNR IN FRAME DIALOG-2 /* START VNR */
DO:
   RUN goma_UI.
END.

/* _UIB-CODE-BLOCK-END */
&ANALYZE-RESUME


&ANALYZE-SUSPEND _UIB-CODE-BLOCK _CONTROL FILL-IN_STARTVNR DIALOG-2
ON LEAVE OF FILL-IN_STARTVNR IN FRAME DIALOG-2 /* START VNR */
DO:
   ASSIGN FILL-IN_STARTVNR = INPUT FILL-IN_STARTVNR.
   regvnr = FILL-IN_STARTVNR.
   RUN VECOKOLL.P.
   IF musz = TRUE THEN DO:
      musz = FALSE.
      RETURN NO-APPLY.
   END.   
   
   
END.

/* _UIB-CODE-BLOCK-END */
&ANALYZE-RESUME


&ANALYZE-SUSPEND _UIB-CODE-BLOCK _CONTROL FILL-IN_STARTVNR DIALOG-2
ON MOUSE-MENU-CLICK OF FILL-IN_STARTVNR IN FRAME DIALOG-2 /* START VNR */
DO:
   ASSIGN
   FILL-IN_STARTVNR = INPUT FILL-IN_STARTVNR
   regvnr = INPUT FILL-IN_STARTVNR
   regdagnamn = CMB_STDAG.
   RUN VECOKOLL.P.
   regvnr = FILL-IN_STARTVNR.
   IF musz = TRUE THEN DO:
      musz = FALSE.
      RETURN NO-APPLY.
   END.
   RUN KALENDERN.W.
   FILL-IN_STARTVNR = regvnr.
   DISPLAY FILL-IN_STARTVNR WITH FRAME {&FRAME-NAME}.
END.

/* _UIB-CODE-BLOCK-END */
&ANALYZE-RESUME


&Scoped-define SELF-NAME FILL-IN_TRAKTAMENTE
&ANALYZE-SUSPEND _UIB-CODE-BLOCK _CONTROL FILL-IN_TRAKTAMENTE DIALOG-2
ON ENTRY OF FILL-IN_TRAKTAMENTE IN FRAME DIALOG-2 /* TRAKT.ZON */
DO:                       
   RUN goma_UI.
END.

/* _UIB-CODE-BLOCK-END */
&ANALYZE-RESUME


&ANALYZE-SUSPEND _UIB-CODE-BLOCK _CONTROL FILL-IN_TRAKTAMENTE DIALOG-2
ON LEAVE OF FILL-IN_TRAKTAMENTE IN FRAME DIALOG-2 /* TRAKT.ZON */
DO:
   ASSIGN FILL-IN_TRAKTAMENTE = INPUT FILL-IN_TRAKTAMENTE.
END.

/* _UIB-CODE-BLOCK-END */
&ANALYZE-RESUME


&Scoped-define SELF-NAME FILL-IN_UTRYCKNING
&ANALYZE-SUSPEND _UIB-CODE-BLOCK _CONTROL FILL-IN_UTRYCKNING DIALOG-2
ON ENTRY OF FILL-IN_UTRYCKNING IN FRAME DIALOG-2 /* UTRYCKNING */
DO:
   RUN goma_UI.
END.

/* _UIB-CODE-BLOCK-END */
&ANALYZE-RESUME


&ANALYZE-SUSPEND _UIB-CODE-BLOCK _CONTROL FILL-IN_UTRYCKNING DIALOG-2
ON LEAVE OF FILL-IN_UTRYCKNING IN FRAME DIALOG-2 /* UTRYCKNING */
DO:
   ASSIGN FILL-IN_UTRYCKNING = INPUT FILL-IN_UTRYCKNING.       
END.

/* _UIB-CODE-BLOCK-END */
&ANALYZE-RESUME


&ANALYZE-SUSPEND _UIB-CODE-BLOCK _CONTROL FILL-IN_UTRYCKNING DIALOG-2
ON MOUSE-SELECT-CLICK OF FILL-IN_UTRYCKNING IN FRAME DIALOG-2 /* UTRYCKNING */
DO:
  IF INPUT FILL-IN_UTRYCKNING = FALSE THEN ASSIGN FILL-IN_UTRYCKNING = TRUE.
  IF INPUT FILL-IN_UTRYCKNING = TRUE THEN ASSIGN FILL-IN_UTRYCKNING = FALSE.
  DISPLAY FILL-IN_UTRYCKNING WITH FRAME {&FRAME-NAME}.

END.

/* _UIB-CODE-BLOCK-END */
&ANALYZE-RESUME


&Scoped-define BROWSE-NAME BRW_ANL
&UNDEFINE SELF-NAME

&ANALYZE-SUSPEND _UIB-CODE-BLOCK _CUSTOM _MAIN-BLOCK DIALOG-2 


/* ***************************  Main Block  *************************** */

/* Parent the dialog-box to the ACTIVE-WINDOW, if there is no parent.   */
IF VALID-HANDLE(ACTIVE-WINDOW) AND FRAME {&FRAME-NAME}:PARENT eq ?
THEN FRAME {&FRAME-NAME}:PARENT = ACTIVE-WINDOW.

/* Add Trigger to equate WINDOW-CLOSE to END-ERROR                      */
ON WINDOW-CLOSE OF FRAME {&FRAME-NAME} APPLY "END-ERROR":U TO SELF.

/* Now enable the interface and wait for the exit condition.            */
/* (NOTE: handle ERROR and END-KEY so cleanup code will always fire.    */
MAIN-BLOCK:
DO ON ERROR   UNDO MAIN-BLOCK, LEAVE MAIN-BLOCK
   ON END-KEY UNDO MAIN-BLOCK, LEAVE MAIN-BLOCK TRANSACTION:
   {muswait.i}
   FIND AONRTAB WHERE RECID(AONRTAB) = aonrrec NO-LOCK NO-ERROR.  
   OPEN QUERY bq FOR EACH BESTTAB USE-INDEX BEST NO-LOCK.
   GET FIRST bq NO-LOCK.
   DO WHILE AVAILABLE(BESTTAB):
      CREATE besttemp.
      ASSIGN besttemp.BBESTID = BESTTAB.BESTID 
      besttemp.BBESTNAMN = BESTTAB.BESTNAMN.
      GET NEXT bq NO-LOCK.
   END.
   FOR EACH TIDREGITAB:
      musz = musz.
   END. FOR EACH TIDREGITAB:
      musz = musz.
   END. FOR EACH TIDREGITAB:
      musz = musz.
   END. FOR EACH TIDREGITAB:
      musz = musz.
   END. FOR EACH TIDREGITAB:
      musz = musz.
   END. FOR EACH TIDREGITAB:
      musz = musz.
   END. FOR EACH TIDREGITAB:
      musz = musz.
   END. FOR EACH TIDREGITAB:
      musz = musz.
   END. FOR EACH TIDREGITAB:
      musz = musz.
   END. FOR EACH TIDREGITAB:
      musz = musz.
   END. 
   FOR EACH TIDREGITAB:
      musz = musz.
   END. FOR EACH TIDREGITAB:
      musz = musz.
   END. FOR EACH TIDREGITAB:
      musz = musz.
   END. FOR EACH TIDREGITAB:
      musz = musz.
   END. FOR EACH TIDREGITAB:
      musz = musz.
   END. FOR EACH TIDREGITAB:
      musz = musz.
   END. FOR EACH TIDREGITAB:
      musz = musz.
   END. FOR EACH TIDREGITAB:
      musz = musz.
   END. FOR EACH TIDREGITAB:
      musz = musz.
   END. FOR EACH TIDREGITAB:
      musz = musz.
   END. FOR EACH TIDREGITAB:
      musz = musz.
   END. FOR EACH TIDREGITAB:
      musz = musz.
   END. FOR EACH TIDREGITAB:
      musz = musz.
   END. 
   FOR EACH TIDREGITAB:
      musz = musz.
   END. FOR EACH TIDREGITAB:
      musz = musz.
   END. FOR EACH TIDREGITAB:
      musz = musz.
   END. FOR EACH TIDREGITAB:
      musz = musz.
   END. FOR EACH TIDREGITAB:
      musz = musz.
   END. FOR EACH TIDREGITAB:
      musz = musz.
   END. FOR EACH TIDREGITAB:
      musz = musz.
   END. FOR EACH TIDREGITAB:
      musz = musz.
   END. FOR EACH TIDREGITAB:
      musz = musz.
   END. FOR EACH TIDREGITAB:
      musz = musz.
   END. FOR EACH TIDREGITAB:
      musz = musz.
   END. FOR EACH TIDREGITAB:
      musz = musz.
   END. FOR EACH TIDREGITAB:
      musz = musz.
   END. 
   IF RAD_FAST = TRUE THEN  status-ok = CMB_OMR:ADD-LAST(" ").
   OPEN QUERY oq FOR EACH OMRADETAB USE-INDEX OMR NO-LOCK.
   GET FIRST oq NO-LOCK.
   DO WHILE AVAILABLE(OMRADETAB):
      IF Guru.Konstanter:globforetag = "NORD" THEN Guru.Konstanter:globforetag = globforetag.
      ELSE DO:
         CREATE besttemp.
         ASSIGN besttemp.BBESTID = OMRADETAB.OMRADE 
         besttemp.BBESTNAMN = OMRADETAB.NAMN.
      END.
      status-ok = CMB_OMR:ADD-LAST(OMRADETAB.NAMN).
      GET NEXT oq NO-LOCK.
   END.  
  
   FOR EACH besttemp USE-INDEX BBEST NO-LOCK:
      status-ok = CMB_BESORG:ADD-LAST(besttemp.BBESTNAMN).
   END.  
   OPEN QUERY aq FOR EACH AUTOMREG USE-INDEX PRISTYP NO-LOCK.
   GET FIRST aq NO-LOCK.
   DO WHILE AVAILABLE(AUTOMREG):
      status-ok = CMB_DEBPR:ADD-LAST(AUTOMREG.PRISTYP).
      GET NEXT aq NO-LOCK.
   END. 
   ASSIGN  CMB_DEBPR:SCREEN-VALUE = AONRTAB.PRISTYP.
   IF RAD_FAST = FALSE THEN DO:  
      FIND FIRST OMRADETAB WHERE OMRADETAB.OMRADE = AONRTAB.OMRADE
      USE-INDEX OMR NO-LOCK NO-ERROR.
      org = OMRADETAB.OMRADE.
      ASSIGN  CMB_OMR:SCREEN-VALUE = OMRADETAB.NAMN.    
      FIND FIRST besttemp WHERE besttemp.BBESTID = AONRTAB.BESTID 
      USE-INDEX BBEST NO-LOCK NO-ERROR.
      IF AVAILABLE besttemp THEN DO:
         ASSIGN  CMB_BESORG:SCREEN-VALUE = besttemp.BBESTNAMN. 
      END.
   END.
   ELSE DO:
      IF AONRTAB.OMRADE = "" THEN DO:
         ASSIGN  CMB_OMR:SCREEN-VALUE = "".
         org = "".
      END.
      ELSE DO:
          FIND FIRST OMRADETAB WHERE OMRADETAB.OMRADE = AONRTAB.OMRADE
          USE-INDEX OMR NO-LOCK NO-ERROR.
          org = OMRADETAB.OMRADE.
          ASSIGN  CMB_OMR:SCREEN-VALUE = OMRADETAB.NAMN. 
      END.     
   END.                                                 
   ASSIGN
   FILL-IN_ANLNR = AONRTAB.ANLNR 
   FILL-IN_AONR = AONRTAB.AONR 
   FILL-IN_ARBANSVARIG = AONRTAB.ARBANSVARIG
   FILL-IN_ARBARTKOD = AONRTAB.ARBARTKOD
   FILL-IN_ARBUPPG = AONRTAB.ARBUPPG[1]
   FILL-IN_ARBUPPG-2 = AONRTAB.ARBUPPG[2]
   FILL-IN_BEREDARE = AONRTAB.BEREDARE
   FILL-IN_DELNR = AONRTAB.DELNR
   FILL-IN_ORT = AONRTAB.ORT
   FILL-IN_PKOD = AONRTAB.PKOD 
   FILL-IN_SLUTVNR = AONRTAB.SLUTVNR
   FILL-IN_STARTVNR = AONRTAB.STARTVNR      
   FILL-IN_TRAKTAMENTE = AONRTAB.TRAKTAMENTE
   FILL-IN_UTRYCKNING = AONRTAB.UTRYCKNING.
   IF Guru.Konstanter:globforetag = "SOLE" THEN DO:
      status-ok = CMB_TRAK:ADD-LAST("2").
   END.
   ASSIGN  
   CMB_TRAK:SCREEN-VALUE = STRING(AONRTAB.TRAKTAMENTE)
   CMB_STDAG:SCREEN-VALUE = AONRTAB.STARTDAG 
   CMB_SLDAG:SCREEN-VALUE = AONRTAB.SLUTDAG.
   CMB_TRAK = INPUT CMB_TRAK.   
   RUN enable_UI.
   IF RAD_FAST = TRUE THEN DO:
      DISABLE CMB_BESORG WITH FRAME {&FRAME-NAME}.
      /*CMB_OMR:HIDDEN = TRUE.*/
      CMB_BESORG:HIDDEN = TRUE.
   END.        
   ASSIGN
   BRW_ANL:HIDDEN = TRUE
   BRW_ARBAN:HIDDEN = TRUE     
   BRW_ARBART:HIDDEN = TRUE            
   BRW_BERED:HIDDEN = TRUE     
   BRW_PRIO:HIDDEN = TRUE.  
   my1hand = FILL-IN_ANLNR:HANDLE IN FRAME {&FRAME-NAME}.
   status-ok = BRW_ANL:MOVE-AFTER-TAB-ITEM(my1hand).
   my1hand = BRW_ANL:HANDLE IN FRAME {&FRAME-NAME}.
   status-ok = FILL-IN_TRAKTAMENTE:MOVE-AFTER-TAB-ITEM(my1hand).
   my1hand = FILL-IN_ARBARTKOD:HANDLE IN FRAME {&FRAME-NAME}.
   status-ok = BRW_ARBART:MOVE-AFTER-TAB-ITEM(my1hand).
   my1hand = BRW_ARBART:HANDLE IN FRAME {&FRAME-NAME}.
   status-ok = FILL-IN_PKOD:MOVE-AFTER-TAB-ITEM(my1hand).
   my1hand = FILL-IN_PKOD:HANDLE IN FRAME {&FRAME-NAME}.
   status-ok = BRW_PRIO:MOVE-AFTER-TAB-ITEM(my1hand).
   my1hand = BRW_PRIO:HANDLE IN FRAME {&FRAME-NAME}.
   status-ok = FILL-IN_STARTVNR:MOVE-AFTER-TAB-ITEM(my1hand).
   my1hand = CMB_SLDAG:HANDLE IN FRAME {&FRAME-NAME}.
   status-ok = FILL-IN_BEREDARE:MOVE-AFTER-TAB-ITEM(my1hand).
   my1hand = FILL-IN_BEREDARE:HANDLE IN FRAME {&FRAME-NAME}.
   status-ok = BRW_BERED:MOVE-AFTER-TAB-ITEM(my1hand).
   my1hand = BRW_BERED:HANDLE IN FRAME {&FRAME-NAME}.
   status-ok = FILL-IN_ARBANSVARIG:MOVE-AFTER-TAB-ITEM(my1hand).
   my1hand = FILL-IN_ARBANSVARIG:HANDLE IN FRAME {&FRAME-NAME}.
   status-ok = BRW_ARBAN:MOVE-AFTER-TAB-ITEM(my1hand).
  
   {musarrow.i}
   WAIT-FOR GO OF FRAME {&FRAME-NAME}.
END.
RUN disable_UI.

/* _UIB-CODE-BLOCK-END */
&ANALYZE-RESUME


/* **********************  Internal Procedures  *********************** */

&ANALYZE-SUSPEND _UIB-CODE-BLOCK _PROCEDURE disable_UI DIALOG-2 _DEFAULT-DISABLE
PROCEDURE disable_UI :
/* --------------------------------------------------------------------
  Purpose:     DISABLE the User Interface
  Parameters:  <none>
  Notes:       Here we clean-up the user-interface by deleting
               dynamic widgets we have created and/or hide 
               frames.  This procedure is usually called when
               we are ready to "clean-up" after running.
   -------------------------------------------------------------------- */
  /* Hide all frames. */
  HIDE FRAME DIALOG-2.
END PROCEDURE.

/* _UIB-CODE-BLOCK-END */
&ANALYZE-RESUME


&ANALYZE-SUSPEND _UIB-CODE-BLOCK _PROCEDURE enable_UI DIALOG-2 _DEFAULT-ENABLE
PROCEDURE enable_UI :
/* --------------------------------------------------------------------
  Purpose:     ENABLE the User Interface
  Parameters:  <none>
  Notes:       Here we display/view/enable the widgets in the
               user-interface.  In addition, OPEN all queries
               associated with each FRAME and BROWSE.
               These statements here are based on the "Other 
               Settings" section of the widget Property Sheets.
   -------------------------------------------------------------------- */
  DISPLAY CMB_OMR FILL-IN_AONR FILL-IN_DELNR FILL-IN_ORT FILL-IN_ARBUPPG 
          FILL-IN_ARBUPPG-2 CMB_BESORG CMB_DEBPR FILL-IN_ANLNR CMB_TRAK 
          FILL-IN_UTRYCKNING FILL-IN_PKOD FILL-IN_ARBARTKOD FILL-IN_STARTVNR 
          CMB_STDAG FILL-IN_SLUTVNR CMB_SLDAG FILL-IN_BEREDARE 
          FILL-IN_ARBANSVARIG 
      WITH FRAME DIALOG-2.
  ENABLE RECT-6 CMB_OMR BRW_ANL RECT-9 FILL-IN_ORT FILL-IN_ARBUPPG 
         FILL-IN_ARBUPPG-2 RECT-11 CMB_BESORG CMB_DEBPR RECT-12 RECT-22 
         FILL-IN_ANLNR BRW_BERED BRW_PRIO BRW_ARBAN BRW_ARBART RECT-14 CMB_TRAK 
         FILL-IN_UTRYCKNING RECT-15 FILL-IN_PKOD FILL-IN_ARBARTKOD RECT-16 
         BTN_NVE FILL-IN_STARTVNR CMB_STDAG BTN_FVE BTN_NVE-2 FILL-IN_SLUTVNR 
         CMB_SLDAG BTN_FVE-2 RECT-17 FILL-IN_BEREDARE FILL-IN_ARBANSVARIG 
         RECT-21 BTN_OK BTN_AVB 
      WITH FRAME DIALOG-2.
  {&OPEN-BROWSERS-IN-QUERY-DIALOG-2}
END PROCEDURE.

/* _UIB-CODE-BLOCK-END */
&ANALYZE-RESUME


&ANALYZE-SUSPEND _UIB-CODE-BLOCK _PROCEDURE goma_UI DIALOG-2 
PROCEDURE goma_UI :
/* -----------------------------------------------------------
  Purpose:     
  Parameters:  <none>
  Notes:       
-------------------------------------------------------------*/
   ASSIGN
   BRW_ANL:HIDDEN IN FRAME {&FRAME-NAME} = TRUE 
   CMB_BESORG:HIDDEN = FALSE 
   CMB_DEBPR:HIDDEN = FALSE 
   CMB_OMR:HIDDEN = FALSE  
   FILL-IN_ARBUPPG:HIDDEN = FALSE 
   FILL-IN_ARBUPPG-2:HIDDEN = FALSE 
   FILL-IN_ORT:HIDDEN = FALSE
   FILL-IN_AONR:HIDDEN = FALSE       
   FILL-IN_DELNR:HIDDEN = FALSE.          
END PROCEDURE.

/* _UIB-CODE-BLOCK-END */
&ANALYZE-RESUME


&UNDEFINE BROWSE-NAME
&UNDEFINE FRAME-NAME
&UNDEFINE WINDOW-NAME
