DEFINE VARIABLE musz AS LOGICAL NO-UNDO.
DEFINE VARIABLE chdatvar AS CHARACTER NO-UNDO.
DEFINE VARIABLE indatvar AS INTEGER NO-UNDO.

DEFINE VARIABLE rad AS INTEGER NO-UNDO.
DEFINE VARIABLE progrest AS CHARACTER FORMAT "X(20)" NO-UNDO.
DEFINE VARIABLE prognamnold AS CHARACTER FORMAT "X(20)" NO-UNDO.
DEFINE VARIABLE prognamndat AS CHARACTER FORMAT "X(20)" NO-UNDO.
DEFINE VARIABLE prognamnque AS CHARACTER FORMAT "X(20)" NO-UNDO.                
DEFINE VARIABLE words AS CHARACTER FORMAT "X(132)" NO-UNDO.
DEFINE VARIABLE kommando AS CHARACTER FORMAT "X(132)" NO-UNDO.
DEFINE VARIABLE kommandoprog AS CHARACTER FORMAT "X(20)" NO-UNDO.
DEFINE TEMP-TABLE tidin
   /*    
           BOLAG DATABAS  FÖRKL 
   ENHET   408 ESNORD   NS GAMLA TAS BORT 
           409=ETA      ETA
           414=ETA      ETA TRAFIKSYSTEM 
           905=ESMAL    ES MÄLARDALEN
           401=ESADM    ES AB ADMIN  
           402=ESADM    ESNORD NYA
              */        
   FIELD ENHET              AS INTEGER FORMAT "999"             
   FIELD AONR               AS CHARACTER FORMAT "X(8)" 
   FIELD AOBENAMNING        AS CHARACTER FORMAT "X(25)" 
   FIELD UPPLDATUM          AS CHARACTER FORMAT "9999999999999" 
   FIELD REDOVISNINGSTYP    AS INTEGER FORMAT "9" 
   FIELD GILTDATUMFROM      AS CHARACTER FORMAT "9999999999999" /*PLAN START*/
   FIELD GILTDATUMTOM       AS CHARACTER FORMAT "9999999999999" 
   FIELD EKAVSLDATUM        AS CHARACTER FORMAT "9999999999999" 
   FIELD TEKNAVSLDATUM      AS CHARACTER FORMAT "9999999999999" /*AVSLUT*/
   FIELD AOTYP              AS CHARACTER FORMAT "X(1)" 
   FIELD ANDRDATUM          AS CHARACTER FORMAT "9999999999999" 
   FIELD HUVUDAONR          AS CHARACTER FORMAT "X(6)" 
   FIELD PRODUKT            AS CHARACTER FORMAT "X(2)" 
   FIELD PROJEKTLEDARE      AS INTEGER FORMAT "9999"  /*OM 8 TA EJ DENNA*/
   FIELD ASTATUS            AS CHARACTER FORMAT "X(1)" 
   FIELD KATEGORI           AS CHARACTER FORMAT "X(2)" 
   FIELD EKAVRAKNTIDPUNKT   AS CHARACTER FORMAT "9999999999999" 
   FIELD PROJEKT            AS CHARACTER FORMAT "X(3)" 
   FIELD AKTIVITET          AS CHARACTER FORMAT "X(1)" 
   FIELD HUVUDKUNDNR        AS INTEGER FORMAT "999999" 
   FIELD ANSVAR             AS INTEGER FORMAT "9999" 
   FIELD INTERNKOD          AS CHARACTER FORMAT "X(3)" 
   FIELD FORLUSTPROJ        AS INTEGER FORMAT "9"
   FIELD TEKNAVSLTIDPUNKT   AS CHARACTER FORMAT "9999999999999" /*AVSLUT*/
   FIELD ANLAGGNING         AS CHARACTER FORMAT "X(40)" 
   FIELD OBJEKT             AS CHARACTER FORMAT "X(40)" 
   FIELD OBJEKTDEL          AS CHARACTER FORMAT "X(40)" 
   FIELD ARBETSPLATS        AS INTEGER FORMAT "9999" 
   FIELD BESTALLARE         AS CHARACTER FORMAT "X(20)" 
   FIELD KUNDEREF           AS CHARACTER FORMAT "X(20)" 
   FIELD KUNDNAMN           AS CHARACTER FORMAT "X(25)" 
   FIELD KUNDADR1           AS CHARACTER FORMAT "X(25)" 
   FIELD KUNDADR2           AS CHARACTER FORMAT "X(25)" 
   FIELD KUNDADR3           AS CHARACTER FORMAT "X(25)" 
   FIELD POSTNR             AS INTEGER FORMAT "99999" 
   FIELD POSTADR            AS CHARACTER FORMAT "X(13)" 
   FIELD AOARBPLATS         AS CHARACTER FORMAT "X(25)" 
   FIELD ARBOMFATT          AS CHARACTER VIEW-AS EDITOR SCROLLBAR-VERTICAL SIZE 68 BY 6     
   FIELD GROSSISTPRISLISTA  AS INTEGER FORMAT "9" 
   FIELD KUNDPRISLISTA      AS INTEGER FORMAT "9"
   FIELD ANBUDSSUMMA        AS INTEGER FORMAT "999999999" 
   FIELD KUNDTYP            AS INTEGER FORMAT "9"
   INDEX AONR IS PRIMARY AONR
   INDEX ENHET ENHET.
run skapaao_UI.
PROCEDURE skapaao_UI:   
      /*     
         BOLAG DATABAS  FÖRKL 
   ENHET   408 ESNORD   NS GAMLA TAS BORT 
           409=ETA      ETA
           414=ETA      ETA TRAFIKSYSTEM 
           905=ESMAL    ES MÄLARDALEN
           401=ESADM    ES AB ADMIN  
           402=ESADM    ESNORD NYA
            
           */
   musz = FALSE.
   /*TA IN RÄTT POSTER TILL RÄTT DATABAS*/
   FOR EACH tidin:
      DELETE tidin.
   END.     
   kommando = SEARCH("c:\delad\pro8\guru\komp\402.dat").
   IF kommando NE ? THEN DO:          
      INPUT FROM "c:\delad\pro8\guru\komp\402.dat".
      REPEAT:
         DO TRANSACTION: 
            CREATE tidin.
            ASSIGN.
            IMPORT tidin NO-ERROR.
         END.               
      END.
      INPUT CLOSE.   
      FIND FIRST tidin WHERE tidin.ENHET = 402 NO-LOCK NO-ERROR.
      IF AVAILABLE tidin THEN DO:
         IF NOT CONNECTED("esadm") THEN DO :               
            CONNECT -db esadm -S esadmd8 -H elpaso.sydkraft.se -N tcp -U CHR(69) + CHR(76) + CHR(80) + CHR(65) + CHR(79) -P "KAGGEN" NO-ERROR. 
         END.
         IF CONNECTED("esadm") THEN DO:
            CREATE ALIAS RT8 FOR DATABASE esadm NO-ERROR.
            RUN ESSKAPAO.P (INPUT 402,INPUT TABLE tidin).  
            FOR EACH tidin WHERE tidin.ENHET = 402:
               DELETE tidin.
            END.
            DELETE ALIAS RT8.
            DISCONNECT esadm NO-ERROR.            
         END.
      END.
   END.
END PROCEDURE.   
