/*xAUTOGRAN.P*/
DEFINE VARIABLE filename AS CHARACTER NO-UNDO.
DEFINE VARIABLE prognamn AS CHARACTER FORMAT "X(50)" NO-UNDO.                
DEFINE VARIABLE musz AS LOGICAL NO-UNDO.


prognamn = "\\GRANGURU\guru_ser\server\PRO9S\granadm9.CSH".
CONNECT -db granadm9 -S 2503 -H granguru -N tcp NO-ERROR.    
IF CONNECTED("granadm9") THEN DO:
   SAVE CACHE COMPLETE VALUE(LDBNAME(1)) TO VALUE(prognamn).
   DISCONNECT granadm9 NO-ERROR. 
END.              
prognamn = "\\GRANGURU\guru_ser\server\PRO9S\GRANNORD.CSH".
CONNECT -db GRANNORD -S 2501 -H granguru -N tcp NO-ERROR.
IF CONNECTED("GRANNORD") THEN DO:
   SAVE CACHE COMPLETE VALUE(LDBNAME(1)) TO VALUE(prognamn).
   DISCONNECT GRANNORD NO-ERROR. 
END.
prognamn = "\\GRANGURU\guru_ser\server\PRO9S\GRANIT.CSH".
CONNECT -db GRANIT -S 2502 -H granguru -N tcp NO-ERROR. 
IF CONNECTED("GRANIT") THEN DO : 
   SAVE CACHE COMPLETE VALUE(LDBNAME(1)) TO VALUE(prognamn).
   DISCONNECT GRANIT NO-ERROR. 
END.
prognamn = "\\GRANGURU\guru_ser\server\PRO9S\GRANSOL.CSH".
CONNECT -db GRANSOL -S 2504 -H granguru -N TCP NO-ERROR. 
IF CONNECTED("GRANSOL") THEN DO :               
   SAVE CACHE COMPLETE VALUE(LDBNAME(1)) TO VALUE(prognamn).
   DISCONNECT GRANSOL NO-ERROR. 
END.

