DEFINE VARIABLE franvar AS CHARACTER NO-UNDO.
DEFINE VARIABLE franvar2 AS CHARACTER NO-UNDO.
DEFINE VARIABLE tillvar AS CHARACTER NO-UNDO.

/*"\\dokument1.graninge.com\DOKUMENT\NÄT (N)\"*/
/*"\\DOKUGRAN\DOKUMENT\NÄT (N)\"*/
/*"\\SRV00486\APPL\"*/

franvar = "\\dokument1.graninge.com\DOKUMENT\NÄT (N)\".
franvar2 = "\\DOKUGRAN\DOKUMENT\NÄT (N)\".
tillvar = "\\SRV00486\APPL\".

OPEN QUERY AQ FOR EACH AVTAL NO-LOCK.
DO TRANSACTION:
   GET FIRST AQ EXCLUSIVE-LOCK.
   IF AVAILABLE AVTAL THEN DO:
      AVTAL.FILNAM = REPLACE(AVTAL.FILNAM,franvar,tillvar).      
      AVTAL.FILNAM = REPLACE(AVTAL.FILNAM,franvar2,tillvar).      
   END.
END.
REPEAT:
   DO TRANSACTION:
      GET NEXT AQ EXCLUSIVE-LOCK.
      IF AVAILABLE AVTAL THEN DO:
         AVTAL.FILNAM = REPLACE(AVTAL.FILNAM,franvar,tillvar).         
         AVTAL.FILNAM = REPLACE(AVTAL.FILNAM,franvar2,tillvar).         
      END.
      ELSE LEAVE.
   END.
END.
CLOSE QUERY AQ.
OPEN QUERY BQ FOR EACH AOTIDLKOPP NO-LOCK.
DO TRANSACTION:
   GET FIRST BQ EXCLUSIVE-LOCK.
   IF AVAILABLE AOTIDLKOPP THEN DO:
      AOTIDLKOPP.FILNAM = REPLACE(AOTIDLKOPP.FILNAM,franvar,tillvar).  
      AOTIDLKOPP.FILNAM = REPLACE(AOTIDLKOPP.FILNAM,franvar2,tillvar).  
   END.
END.
REPEAT:
   DO TRANSACTION:
      GET NEXT BQ EXCLUSIVE-LOCK.
      IF AVAILABLE AOTIDLKOPP THEN DO:
         AOTIDLKOPP.FILNAM = REPLACE(AOTIDLKOPP.FILNAM,franvar,tillvar).
         AOTIDLKOPP.FILNAM = REPLACE(AOTIDLKOPP.FILNAM,franvar2,tillvar).  
      END.
      ELSE LEAVE.
   END.
END.
CLOSE QUERY BQ.
OPEN QUERY CQ FOR EACH AVTAONR NO-LOCK.
DO TRANSACTION:
   GET FIRST CQ EXCLUSIVE-LOCK.
   IF AVAILABLE AVTAONR THEN DO:
      AVTAONR.FILNAM = REPLACE(AVTAONR.FILNAM,franvar,tillvar).      
      AVTAONR.FILNAM = REPLACE(AVTAONR.FILNAM,franvar2,tillvar).      
   END.
END.
REPEAT:
   DO TRANSACTION:
      GET NEXT CQ EXCLUSIVE-LOCK.
      IF AVAILABLE AVTAONR THEN DO:
         AVTAONR.FILNAM = REPLACE(AVTAONR.FILNAM,franvar,tillvar).
         AVTAONR.FILNAM = REPLACE(AVTAONR.FILNAM,franvar2,tillvar).      
      END.
      ELSE LEAVE.
   END.
END.
CLOSE QUERY CQ.
