DEFINE QUERY kalkq FOR KALKYL.

OPEN QUERY kalkq FOR EACH KALKYL WHERE KALKYL.BEFATTNING = "MATERIAL" NO-LOCK. 
DO TRANSACTION:
   GET FIRST kalkq EXCLUSIVE-LOCK.
END.
DO WHILE AVAILABLE(KALKYL):
   DO TRANSACTION:
      KALKYL.BEFATTNING = "MATERIEL".
      GET NEXT kalkq EXCLUSIVE-LOCK.  
   END.
END.
CLOSE QUERY kalkq.