OPEN QUERY pq FOR EACH PERSONALTAB USE-INDEX personalkod NO-LOCK.
DO TRANSACTION:  
   GET FIRST pq EXCLUSIVE-LOCK.
   IF PERSONALTAB.OMRADE BEGINS "15" THEN .
   ELSE ASSIGN PERSONALTAB.OMRADE = "".
END.
DO WHILE AVAILABLE(PERSONALTAB): 
   DO TRANSACTION:
       GET NEXT pq EXCLUSIVE-LOCK.
       IF PERSONALTAB.OMRADE BEGINS "15" THEN .
       ELSE ASSIGN PERSONALTAB.OMRADE = "".
   END.
END.

