/*XBYTOMRSU.P   byt verkamhet på gamla projekt .Flytta även kalkyler och uppföljning. SUNDSVALL*/
DEFINE VARIABLE prognamn5 AS CHARACTER NO-UNDO.
DEFINE VARIABLE prognamn3 AS CHARACTER NO-UNDO.
DEFINE VARIABLE omradespar AS CHARACTER NO-UNDO.
DEFINE VARIABLE anr AS CHARACTER NO-UNDO.
DEFINE VARIABLE dnr AS INTEGER NO-UNDO.
DEFINE VARIABLE nomr AS CHARACTER NO-UNDO.
DEFINE VARIABLE nbestid AS CHARACTER NO-UNDO.
DEFINE TEMP-TABLE bytvht NO-UNDO
FIELD FRAN AS CHARACTER
FIELD TILL AS CHARACTER
INDEX FRAN IS PRIMARY FRAN TILL .

/*RUN skbyt_UI (INPUT "1170",INPUT "1111").
RUN skbyt_UI (INPUT "1190",INPUT "1111").  */

RUN skbyt_UI (INPUT "1320",INPUT "1611").
RUN skbyt_UI (INPUT "1321",INPUT "1611").
RUN skbyt_UI (INPUT "1322",INPUT "1611").
RUN skbyt_UI (INPUT "1323",INPUT "1611").
RUN skbyt_UI (INPUT "1324",INPUT "1611").

RUN skbyt_UI (INPUT "1331",INPUT "1811").
RUN skbyt_UI (INPUT "1332",INPUT "1811").
RUN skbyt_UI (INPUT "1333",INPUT "1811").
RUN skbyt_UI (INPUT "1340",INPUT "1811").
RUN skbyt_UI (INPUT "1350",INPUT "1811").
RUN skbyt_UI (INPUT "1360",INPUT "1811").
RUN skbyt_UI (INPUT "1370",INPUT "1811").
RUN skbyt_UI (INPUT "1380",INPUT "1811").

RUN skbyt_UI (INPUT "1390",INPUT "1311").

RUN skbyt_UI (INPUT "1440",INPUT "1611").
RUN skbyt_UI (INPUT "1471",INPUT "1611").
RUN skbyt_UI (INPUT "1472",INPUT "1611").

RUN skbyt_UI (INPUT "1512",INPUT "1511").
RUN skbyt_UI (INPUT "1513",INPUT "1511").
RUN skbyt_UI (INPUT "1516",INPUT "1511").
RUN skbyt_UI (INPUT "1517",INPUT "1511").
RUN skbyt_UI (INPUT "1518",INPUT "1511").
RUN skbyt_UI (INPUT "1519",INPUT "1511").

RUN skbyt_UI (INPUT "1520",INPUT "1611").
RUN skbyt_UI (INPUT "1521",INPUT "1611").
RUN skbyt_UI (INPUT "1522",INPUT "1611").
RUN skbyt_UI (INPUT "1523",INPUT "1611").
RUN skbyt_UI (INPUT "1524",INPUT "1611").
RUN skbyt_UI (INPUT "1526",INPUT "1611").
RUN skbyt_UI (INPUT "1527",INPUT "1611").
RUN skbyt_UI (INPUT "1529",INPUT "1611").

RUN skbyt_UI (INPUT "1531",INPUT "1811").
RUN skbyt_UI (INPUT "1532",INPUT "1811").
RUN skbyt_UI (INPUT "1533",INPUT "1811").
RUN skbyt_UI (INPUT "1534",INPUT "1811").
RUN skbyt_UI (INPUT "1536",INPUT "1811").
RUN skbyt_UI (INPUT "1537",INPUT "1811").
RUN skbyt_UI (INPUT "1539",INPUT "1811").

RUN skbyt_UI (INPUT "1540",INPUT "1711").
RUN skbyt_UI (INPUT "1541",INPUT "1711").
RUN skbyt_UI (INPUT "1542",INPUT "1711").
RUN skbyt_UI (INPUT "1544",INPUT "1711").
RUN skbyt_UI (INPUT "1547",INPUT "1711").
RUN skbyt_UI (INPUT "1548",INPUT "1711").
RUN skbyt_UI (INPUT "1549",INPUT "1711").

RUN skbyt_UI (INPUT "1560",INPUT "1511").
RUN skbyt_UI (INPUT "1580",INPUT "1511").
RUN skbyt_UI (INPUT "1590",INPUT "1511").

RUN skbyt_UI (INPUT "1720",INPUT "1711").
RUN skbyt_UI (INPUT "1731",INPUT "1711").
RUN skbyt_UI (INPUT "1732",INPUT "1711").
RUN skbyt_UI (INPUT "1740",INPUT "1711").
RUN skbyt_UI (INPUT "1750",INPUT "1711").
RUN skbyt_UI (INPUT "1760",INPUT "1711").
RUN skbyt_UI (INPUT "1780",INPUT "1711").
RUN skbyt_UI (INPUT "1790",INPUT "1711").



PROCEDURE skbyt_UI.
DEFINE INPUT PARAMETER vfran AS CHARACTER NO-UNDO.
DEFINE INPUT PARAMETER vtill AS CHARACTER NO-UNDO.

   CREATE bytvht.
   ASSIGN bytvht.FRAN = vfran
   bytvht.TILL = vtill.
END PROCEDURE.

prognamn5 = "D:\delad\server\pro9s\EXPORT\lon\".   
prognamn3 = prognamn5 + "bytevht.txt".
OUTPUT TO VALUE(prognamn3) APPEND.
/* Om området är bytt*/
FOR EACH bytvht :  
   OPEN QUERY aobq FOR  EACH AONRTAB WHERE AONRTAB.OMRADE = bytvht.FRAN NO-LOCK.
   GET FIRST aobq NO-LOCK.
   DO WHILE AVAILABLE(AONRTAB):            
      ASSIGN
      anr = AONRTAB.AONR
      dnr = AONRTAB.DELNR
      omradespar = AONRTAB.OMRADE.
      PUT UNFORMATTED AONRTAB.AONR " " AONRTAB.DELNR " " AONRTAB.OMRADE " " AONRTAB.BESTID " " bytvht.TILL SKIP.
      DO TRANSACTION:
         GET CURRENT aobq EXCLUSIVE-LOCK.
         IF AONRTAB.BESTID = AONRTAB.OMRADE THEN ASSIGN AONRTAB.BESTID =  bytvht.TILL.
         ASSIGN AONRTAB.OMRADE =  bytvht.TILL.
      END.
      ASSIGN
      nomr = AONRTAB.OMRADE 
      nbestid = AONRTAB.BESTID.
      RUN bytkopp_UI.
      GET NEXT aobq NO-LOCK.
   END.
END.
OUTPUT CLOSE.

PROCEDURE bytkopp_UI.
   FOR EACH KALKAONR WHERE KALKAONR.AONR = anr AND KALKAONR.DELNR = dnr NO-LOCK,
   EACH FASTSPEC WHERE FASTSPEC.KALKNR = KALKAONR.KALKNR EXCLUSIVE-LOCK.   
      PUT UNFORMATTED "fspec " FASTSPEC.KALKNR " "  FASTSPEC.OMRADE " " FASTSPEC.BESTID SKIP.      
      ASSIGN
      FASTSPEC.OMRADE = nomr
      FASTSPEC.BESTID = nbestid.      
   END.
   FOR EACH KALKAONR WHERE KALKAONR.AONR = anr AND KALKAONR.DELNR = dnr NO-LOCK,   
   EACH FASTKALK WHERE FASTKALK.OMRADE = KALKAONR.OMRADE AND FASTKALK.KALKNR = KALKAONR.KALKNR EXCLUSIVE-LOCK.
      PUT UNFORMATTED " fkalk " FASTKALK.KALKNR " " FASTKALK.OMRADE SKIP.      
      ASSIGN      
      FASTKALK.OMRADE = nomr.      
   END.
   FOR EACH KALKAONR WHERE KALKAONR.AONR = anr AND KALKAONR.DELNR = dnr EXCLUSIVE-LOCK:      
      PUT UNFORMATTED " kalkaonr " KALKAONR.KALKNR " " KALKAONR.OMRADE SKIP.      
      ASSIGN
      KALKAONR.OMRADE = nomr.
   END.
   /*FOR EACH KALKAONR WHERE KALKAONR.AONR = anr AND KALKAONR.DELNR = dnr EXCLUSIVE-LOCK,
   EACH FASTSPEC WHERE FASTSPEC.KALKNR = KALKAONR.KALKNR EXCLUSIVE-LOCK,
   EACH FASTKALK WHERE FASTKALK.OMRADE = FASTSPEC.OMRADE AND FASTKALK.KALKNR = KALKAONR.KALKNR EXCLUSIVE-LOCK.
      PUT "fspec " FASTSPEC.KALKNR " "  FASTSPEC.OMRADE " " FASTSPEC.BESTID " fkalk " FASTKALK.KALKNR " " FASTKALK.OMRADE  " kaonr " KALKAONR.KALKNR " "  KALKAONR.OMRADE SKIP.      
      ASSIGN
      FASTSPEC.OMRADE = nomr
      FASTSPEC.BESTID = nbestid
      FASTKALK.OMRADE = nomr
      KALKAONR.OMRADE = nomr.      
   END.*/


   /*OPEN QUERY kalkkq FOR EACH KALKAONR WHERE
   KALKAONR.AONR = anr AND
   KALKAONR.DELNR = dnr NO-LOCK,
   EACH FASTSPEC WHERE FASTSPEC.KALKNR = KALKAONR.KALKNR NO-LOCK,
   EACH FASTKALK WHERE FASTKALK.OMRADE = FASTSPEC.OMRADE AND FASTKALK.KALKNR = KALKAONR.KALKNR NO-LOCK.
   
   GET FIRST kalkkq NO-LOCK.
   DO WHILE AVAILABLE(FASTKALK):
      PUT "fspec " FASTSPEC.KALKNR " "  FASTSPEC.OMRADE " " FASTSPEC.BESTID " fkalk " FASTKALK.KALKNR " " FASTKALK.OMRADE SKIP.
      DO TRANSACTION:
         GET CURRENT kalkkq EXCLUSIVE-LOCK.
         ASSIGN
         FASTSPEC.OMRADE = nomr
         FASTSPEC.BESTID = nbestid
         FASTKALK.OMRADE = nomr.
      END.
      GET NEXT kalkkq NO-LOCK.
   END.
   CLOSE QUERY kalkkq.   */


   
   FOR EACH KALKSPEC WHERE KALKSPEC.AONR = anr AND
   KALKSPEC.DELNR = dnr EXCLUSIVE-LOCK:      
      PUT UNFORMATTED "kspec "   KALKSPEC.KALKNR " "  KALKSPEC.OMRADE " " KALKSPEC.BESTID  SKIP.
      ASSIGN
      KALKSPEC.OMRADE = nomr
      KALKSPEC.BESTID = nbestid.
   END.      


   /*OPEN QUERY fkalkq FOR EACH KALKSPEC WHERE
   KALKSPEC.AONR = anr AND
   KALKSPEC.DELNR = dnr NO-LOCK.
   GET FIRST fkalkq NO-LOCK.
   DO WHILE AVAILABLE(KALKSPEC):
      PUT "kspec "   KALKSPEC.KALKNR " "  KALKSPEC.OMRADE " " KALKSPEC.BESTID  SKIP.
      DO TRANSACTION:
         GET CURRENT fkalkq EXCLUSIVE-LOCK.
         ASSIGN
         KALKSPEC.OMRADE = nomr
         KALKSPEC.BESTID = nbestid.
      END.
      GET NEXT fkalkq NO-LOCK.
   END.
   CLOSE QUERY fkalkq. 
   
   DO TRANSACTION:
      FOR EACH KALKAONR WHERE KALKAONR.AONR = anr AND
      KALKAONR.DELNR = dnr EXCLUSIVE-LOCK.   
         PUT "kaonr " KALKAONR.KALKNR " "  KALKAONR.OMRADE  SKIP.
         ASSIGN KALKAONR.OMRADE = nomr.
      END.      
   END.                */
   
   /*OPEN QUERY kalkaoq FOR EACH KALKAONR WHERE
   KALKAONR.AONR = anr AND
   KALKAONR.DELNR = dnr NO-LOCK.
   GET FIRST kalkaoq NO-LOCK.
   DO WHILE AVAILABLE(KALKAONR):
      PUT "kaonr " KALKAONR.KALKNR " "  KALKAONR.OMRADE  SKIP.
      DO TRANSACTION:
         GET CURRENT kalkaoq EXCLUSIVE-LOCK.
         ASSIGN
         KALKAONR.OMRADE = nomr.
      END.
      GET NEXT kalkaoq NO-LOCK.
   END.
   CLOSE QUERY kalkaoq.*/
   

   
   FOR EACH SUMTIDDAG WHERE
   SUMTIDDAG.AONR = anr AND SUMTIDDAG.DELNR = dnr
   AND SUMTIDDAG.GEOMRADE = omradespar USE-INDEX BARAAONR EXCLUSIVE-LOCK:   
      ASSIGN  SUMTIDDAG.GEOMRADE = nomr.
   END.
   
   
   
   /*OPEN QUERY sumdq FOR EACH SUMTIDDAG WHERE
   SUMTIDDAG.AONR = anr AND SUMTIDDAG.DELNR = dnr
   AND SUMTIDDAG.GEOMRADE = omradespar USE-INDEX BARAAONR NO-LOCK.
   GET FIRST sumdq NO-LOCK.
   DO WHILE AVAILABLE(SUMTIDDAG):
      DO TRANSACTION:
         GET CURRENT sumdq EXCLUSIVE-LOCK.
         ASSIGN  SUMTIDDAG.GEOMRADE = nomr.
      END.
      GET NEXT sumdq NO-LOCK.
   END.
   CLOSE QUERY sumdq. */
      
      

END PROCEDURE.


   
