/*XBYTOMRSU2008.P   byt verkamhet på gamla projekt .Flytta även kalkyler och uppföljning. SUNDSVALL*/
DEFINE VARIABLE prognamn5 AS CHARACTER NO-UNDO.
DEFINE VARIABLE prognamn3 AS CHARACTER NO-UNDO.
DEFINE VARIABLE omradespar AS CHARACTER NO-UNDO.
DEFINE VARIABLE anr AS CHARACTER NO-UNDO.
DEFINE VARIABLE dnr AS INTEGER NO-UNDO.
DEFINE VARIABLE nomr AS CHARACTER NO-UNDO.
DEFINE VARIABLE nbestid AS CHARACTER NO-UNDO.
DEFINE TEMP-TABLE bytvht NO-UNDO
FIELD AONR AS CHARACTER
FIELD DELNR AS INTEGER
FIELD FRAN AS CHARACTER
FIELD TILL AS CHARACTER
INDEX FRAN IS PRIMARY FRAN TILL .

RUN skbyt_UI (INPUT "70213",INPUT "1940").
/*RUN skbyt_UI (INPUT "45007",INPUT "1933").

RUN skbyt_UI (INPUT "45002",INPUT "1931").

RUN skbyt_UI (INPUT "45003",INPUT "1932").

RUN skbyt_UI (INPUT "45004",INPUT "1950").

RUN skbyt_UI (INPUT "45005",INPUT "1960").

RUN skbyt_UI (INPUT "45006",INPUT "1971").

RUN skbyt_UI (INPUT "45007",INPUT "1933").

RUN skbyt_UI (INPUT "45008",INPUT "1972").

/*RUN skbyt_UI (INPUT "45012",INPUT "1911").*/

RUN skbyt_UI (INPUT "45013",INPUT "1915").

/*RUN skbyt_UI (INPUT "45015",INPUT "1911").

RUN skbyt_UI (INPUT "45022",INPUT "1911").

RUN skbyt_UI (INPUT "45023",INPUT "1911").

RUN skbyt_UI (INPUT "45030",INPUT "1911").
RUN skbyt_UI (INPUT "45044",INPUT "1911").*/
*/

PROCEDURE skbyt_UI.
DEFINE INPUT PARAMETER prnr AS CHARACTER NO-UNDO.
DEFINE INPUT PARAMETER vtill AS CHARACTER NO-UNDO.

   CREATE bytvht.
   ASSIGN
   bytvht.AONR = prnr   
   bytvht.TILL = vtill.
END PROCEDURE.



prognamn5 = "D:\delad\server\pro9s\EXPORT\lon\".   
prognamn3 = prognamn5 + "bytevht1833.txt".
OUTPUT TO VALUE(prognamn3) APPEND.

FOR EACH bytvht :  
   OPEN QUERY aobq FOR  EACH AONRTAB WHERE AONRTAB.AONR = bytvht.AONR NO-LOCK.
   GET FIRST aobq NO-LOCK.
   DO WHILE AVAILABLE(AONRTAB):            
      ASSIGN
      anr = AONRTAB.AONR
      dnr = AONRTAB.DELNR
      omradespar = AONRTAB.OMRADE.
      PUT UNFORMATTED AONRTAB.AONR " " AONRTAB.DELNR " " AONRTAB.OMRADE " " AONRTAB.BESTID " " bytvht.TILL SKIP.
      DO TRANSACTION:
         GET CURRENT aobq EXCLUSIVE-LOCK.
         IF AONRTAB.BESTID = AONRTAB.OMRADE THEN ASSIGN AONRTAB.BESTID =  bytvht.TILL.
         ASSIGN AONRTAB.OMRADE =  bytvht.TILL.
      END.
      ASSIGN
      nomr = AONRTAB.OMRADE 
      nbestid = AONRTAB.BESTID.
      RUN bytkopp_UI.
      GET NEXT aobq NO-LOCK.
   END.
END.
OUTPUT CLOSE.



PROCEDURE bytkopp_UI.
   FOR EACH KALKAONR WHERE KALKAONR.AONR = anr AND KALKAONR.DELNR = dnr NO-LOCK,
   EACH FASTSPEC WHERE FASTSPEC.KALKNR = KALKAONR.KALKNR EXCLUSIVE-LOCK.   
      PUT "fspec " FASTSPEC.KALKNR " "  FASTSPEC.OMRADE " " FASTSPEC.BESTID SKIP.      
      ASSIGN
      FASTSPEC.OMRADE = nomr
      FASTSPEC.BESTID = nbestid.      
   END.
   FOR EACH KALKAONR WHERE KALKAONR.AONR = anr AND KALKAONR.DELNR = dnr NO-LOCK,   
   EACH FASTKALK WHERE FASTKALK.OMRADE = KALKAONR.OMRADE AND FASTKALK.KALKNR = KALKAONR.KALKNR EXCLUSIVE-LOCK.
      PUT " fkalk " FASTKALK.KALKNR " " FASTKALK.OMRADE SKIP.      
      ASSIGN      
      FASTKALK.OMRADE = nomr.      
   END.
   FOR EACH KALKAONR WHERE KALKAONR.AONR = anr AND KALKAONR.DELNR = dnr EXCLUSIVE-LOCK:
      PUT " kalkaonr " KALKAONR.KALKNR " " KALKAONR.OMRADE SKIP.      
      ASSIGN
      KALKAONR.OMRADE = nomr.
   END.
   FOR EACH KALKSPEC WHERE KALKSPEC.AONR = anr AND
   KALKSPEC.DELNR = dnr EXCLUSIVE-LOCK:      
      PUT "kspec "   KALKSPEC.KALKNR " "  KALKSPEC.OMRADE " " KALKSPEC.BESTID  SKIP.
      ASSIGN
      KALKSPEC.OMRADE = nomr
      KALKSPEC.BESTID = nbestid.
   END.      
   FOR EACH SUMTIDDAG WHERE
   SUMTIDDAG.AONR = anr AND SUMTIDDAG.DELNR = dnr
   AND SUMTIDDAG.GEOMRADE = omradespar USE-INDEX BARAAONR EXCLUSIVE-LOCK:   
      ASSIGN  SUMTIDDAG.GEOMRADE = nomr.
   END.   
   FOR EACH FAKTAONR  WHERE FAKTAONR.AONR = anr AND
   FAKTAONR.DELNR = dnr EXCLUSIVE-LOCK:      
      PUT "FAKTAONR FAKTPLAN "   FAKTAONR.AONR " " FAKTAONR.DELNR " " FAKTAONR.FAKTNR " "  FAKTAONR.OMRADE   SKIP.
      FOR EACH FAKTPLAN  WHERE FAKTPLAN.FAKTNR = FAKTAONR.FAKTNR:         
         FAKTPLAN.OMRADE = nomr.  
      END.
      FAKTAONR.OMRADE = nomr.    
   END.              
   FOR EACH FAKTINTAKTKONT  WHERE FAKTINTAKTKONT.AONR = anr AND
   FAKTINTAKTKONT.DELNR = dnr EXCLUSIVE-LOCK:      
      PUT "FAKTINTAKTKONT "   FAKTINTAKTKONT.AONR " " FAKTINTAKTKONT.DELNR " " FAKTINTAKTKONT.FAKTNR " "  FAKTINTAKTKONT.OMRADE   SKIP.
      ASSIGN
      FAKTINTAKTKONT.OMRADE = nomr.
      
   END.      
   FOR EACH FAKTINTAKTKONTKRED  WHERE FAKTINTAKTKONT.AONR = anr AND
   FAKTINTAKTKONTKRED.DELNR = dnr EXCLUSIVE-LOCK:      
      PUT "FAKTINTAKTKONTKRED "   FAKTINTAKTKONTKRED.AONR " " FAKTINTAKTKONTKRED.DELNR " " FAKTINTAKTKONTKRED.FAKTNR " "  FAKTINTAKTKONTKRED.OMRADE   SKIP.
      ASSIGN
      FAKTINTAKTKONTKRED.OMRADE = nomr.
      
   END.      
   
END PROCEDURE.


   
