/*XBYTOMR.P BYTER OMRÅDESBETECKNINGAR*/

DEFINE INPUT PARAMETER valomr LIKE OMRADETAB.OMRADE NO-UNDO.
DEFINE INPUT PARAMETER bytomr LIKE OMRADETAB.OMRADE NO-UNDO.

{muswait.i}
/*BEREDNING*/
OPEN QUERY aq FOR EACH beredning WHERE BEREDNING.OMRADE = valomr
NO-LOCK.
DO TRANSACTION:
   GET FIRST aq EXCLUSIVE-LOCK.
   IF AVAILABLE BEREDNING THEN DO:
      BEREDNING.OMRADE = bytomr.
   END.
END.
REPEAT :
   DO TRANSACTION:
      GET NEXT aq EXCLUSIVE-LOCK.
      IF AVAILABLE BEREDNING THEN DO:
         BEREDNING.OMRADE = bytomr.
      END.
      ELSE LEAVE.
   END.
END.
CLOSE QUERY aq.
      
OPEN QUERY berqmtrl FOR EACH BERMTRL WHERE
BERMTRL.OMRADE = valomr NO-LOCK.
DO TRANSACTION:
   GET FIRST berqmtrl EXCLUSIVE-LOCK.
   IF AVAILABLE BERMTRL THEN DO:
      BERMTRL.OMRADE = bytomr.
   END.
END.
REPEAT:   
   DO TRANSACTION:
      GET NEXT berqmtrl EXCLUSIVE-LOCK.
      IF AVAILABLE BERMTRL THEN DO:
         BERMTRL.OMRADE = bytomr.
      END.
      ELSE LEAVE.
   END.
END.
CLOSE QUERY berqmtrl.

OPEN QUERY ordq FOR EACH BERORD WHERE
BERORD.OMRADE = valomr NO-LOCK.
DO TRANSACTION:
   GET FIRST ordq EXCLUSIVE-LOCK.
   IF AVAILABLE berord THEN DO:
      BERORD.OMRADE = bytomr.
   END.
END.
REPEAT:
   GET NEXT ordq EXCLUSIVE-LOCK.
   IF AVAILABLE berord THEN DO:
      BERORD.OMRADE = bytomr.
   END.
   ELSE LEAVE.
END.
CLOSE QUERY ordq.

OPEN QUERY berqlin FOR EACH BERLINKAB WHERE
BERLINKAB.OMRADE = valomr NO-LOCK.
DO TRANSACTION:
   GET FIRST berqlin EXCLUSIVE-LOCK.
   IF AVAILABLE BERLINKAB THEN DO:
      BERLINKAB.OMRADE = bytomr.
   END.
END.
REPEAT:
   GET NEXT berqlin EXCLUSIVE-LOCK.
   IF AVAILABLE BERLINKAB THEN DO:
      BERLINKAB.OMRADE = bytomr.
   END.
   ELSE LEAVE.
END.
CLOSE QUERY berqlin.

OPEN QUERY berqskydd FOR EACH KSKYDD WHERE
KSKYDD.OMRADE = valomr NO-LOCK.
DO TRANSACTION:
   GET FIRST berqskydd EXCLUSIVE-LOCK.
   IF AVAILABLE KSKYDD THEN DO:
      KSKYDD.OMRADE = bytomr.
   END.
END.
REPEAT:
   GET NEXT berqskydd EXCLUSIVE-LOCK.
   IF AVAILABLE KSKYDD THEN DO:
      KSKYDD.OMRADE = bytomr.
   END.
   ELSE LEAVE.
END.
CLOSE QUERY berqskydd.

OPEN QUERY berq FOR EACH BERVAL WHERE BERVAL.OMRADE = valomr
NO-LOCK.
DO TRANSACTION:
   GET FIRST berq EXCLUSIVE-LOCK.
   IF AVAILABLE BERVAL THEN DO:
      BERVAL.OMRADE = bytomr.
   END.
END.
REPEAT:
   GET NEXT berq EXCLUSIVE-LOCK.
   IF AVAILABLE BERVAL THEN DO:
      BERVAL.OMRADE = bytomr.
   END.
   ELSE LEAVE.
END.
CLOSE QUERY berq.

OPEN QUERY friq FOR EACH FRIKORT WHERE
FRIKORT.OMRADE = valomr
NO-LOCK.
DO TRANSACTION:
   GET FIRST friq EXCLUSIVE-LOCK.
   IF AVAILABLE FRIKORT THEN DO:
      FRIKORT.OMRADE = bytomr.
   END.
END.
REPEAT:
   GET NEXT friq EXCLUSIVE-LOCK.
   IF AVAILABLE FRIKORT THEN DO:
      FRIKORT.OMRADE = bytomr.
   END.
   ELSE LEAVE.
END.
CLOSE QUERY friq.

OPEN QUERY berqid FOR EACH BERID WHERE
BERID.OMRADE = valomr NO-LOCK.
DO TRANSACTION:
   GET FIRST berqid EXCLUSIVE-LOCK.
   IF AVAILABLE BERID THEN DO:
      BERID.OMRADE = bytomr.
   END.
END.
REPEAT:
   GET NEXT berqid EXCLUSIVE-LOCK.
   IF AVAILABLE BERID THEN DO:
      BERID.OMRADE = bytomr.
   END.
   ELSE LEAVE.
END.
CLOSE QUERY berqid.

OPEN QUERY berqschakt FOR EACH BERSCHAKT WHERE
BERSCHAKT.OMRADE = valomr NO-LOCK.
DO TRANSACTION:
   GET FIRST berqschakt EXCLUSIVE-LOCK.
   IF AVAILABLE BERSCHAKT THEN DO:
      BERSCHAKT.OMRADE = bytomr.
   END.
END.
REPEAT:
   GET NEXT berqschakt EXCLUSIVE-LOCK.
   IF AVAILABLE BERSCHAKT THEN DO:
      BERSCHAKT.OMRADE = bytomr.
   END.
   ELSE LEAVE.
END.
CLOSE QUERY berqschakt.

OPEN QUERY berqpunkt FOR EACH BERPUNKT WHERE
BERPUNKT.OMRADE = valomr NO-LOCK.
DO TRANSACTION:
   GET FIRST berqpunkt EXCLUSIVE-LOCK.
   IF AVAILABLE BERPUNKT THEN DO:
      BERPUNKT.OMRADE = bytomr.
   END.
END.
REPEAT:
   GET NEXT berqpunkt EXCLUSIVE-LOCK.
   IF AVAILABLE BERPUNKT THEN DO:
      BERPUNKT.OMRADE = bytomr.
   END.
   ELSE LEAVE.
END.
CLOSE QUERY berqpunkt.

OPEN QUERY berqkab FOR EACH SCHAKTKAB WHERE
SCHAKTKAB.OMRADE = valomr NO-LOCK.
DO TRANSACTION:
   GET FIRST berqkab EXCLUSIVE-LOCK.
   IF AVAILABLE SCHAKTKAB THEN DO:
      SCHAKTKAB.OMRADE = bytomr.
   END.
END.
REPEAT:
   GET NEXT berqkab EXCLUSIVE-LOCK.
   IF AVAILABLE SCHAKTKAB THEN DO:
      SCHAKTKAB.OMRADE = bytomr.
   END.
   ELSE LEAVE.
END.
CLOSE QUERY berqkab.

OPEN QUERY uppq FOR EACH BERUPP WHERE
BERUPP.OMRADE = valomr NO-LOCK.
DO TRANSACTION:
   GET FIRST uppq EXCLUSIVE-LOCK.
   IF AVAILABLE BERUPP THEN DO:
      BERUPP.OMRADE = bytomr.
   END.
END.
REPEAT:
   GET NEXT uppq EXCLUSIVE-LOCK.
   IF AVAILABLE BERUPP THEN DO:
      BERUPP.OMRADE = bytomr.
   END.
   ELSE LEAVE.
END.
CLOSE QUERY uppq.

OPEN QUERY kalkq FOR EACH BERKALK WHERE BERKALK.OMRADE = valomr
NO-LOCK.
DO TRANSACTION:
   GET FIRST kalkq EXCLUSIVE-LOCK.
   IF AVAILABLE BERKALK THEN DO:
      BERKALK.OMRADE = bytomr.
   END.
END.
REPEAT:
   GET NEXT kalkq EXCLUSIVE-LOCK.
   IF AVAILABLE BERKALK THEN DO:
      BERKALK.OMRADE = bytomr.
   END.
   ELSE LEAVE.
END.
CLOSE QUERY kalkq.

OPEN QUERY levq FOR EACH LEVTRP WHERE LEVTRP.OMRADE = valomr
NO-LOCK.
DO TRANSACTION:
   GET FIRST levq EXCLUSIVE-LOCK.
   IF AVAILABLE LEVTRP THEN DO:
      LEVTRP.OMRADE = bytomr.
   END.
END.
REPEAT:
   GET NEXT levq EXCLUSIVE-LOCK.
   IF AVAILABLE LEVTRP THEN DO:
      LEVTRP.OMRADE = bytomr.
   END.
   ELSE LEAVE.
END.
CLOSE QUERY levq.

OPEN QUERY levq2 FOR EACH LEVTRP2 WHERE
LEVTRP2.OMRADE = valomr NO-LOCK.
DO TRANSACTION:
   GET FIRST levq2 EXCLUSIVE-LOCK.
   IF AVAILABLE LEVTRP2 THEN DO:
      LEVTRP2.OMRADE = bytomr.
   END.
END.
REPEAT:
   GET NEXT levq2 EXCLUSIVE-LOCK.
   IF AVAILABLE LEVTRP2 THEN DO:
      LEVTRP2.OMRADE = bytomr.
   END.
   ELSE LEAVE.
END.
CLOSE QUERY levq2.

OPEN QUERY bestq FOR EACH BESTSTAT WHERE BESTSTAT.OMRADE = valomr
NO-LOCK.
DO TRANSACTION:
   GET FIRST bestq EXCLUSIVE-LOCK.
   IF AVAILABLE BESTSTAT THEN DO:
      BESTSTAT.OMRADE = bytomr.
   END.
END.
REPEAT:
   GET NEXT bestq EXCLUSIVE-LOCK.
   IF AVAILABLE BESTSTAT THEN DO:
      BESTSTAT.OMRADE = bytomr.
   END.
   ELSE LEAVE.
END.
CLOSE QUERY bestq.
/*SLUT BEREDNING*/

/*KALKYL*/
OPEN QUERY kkq FOR EACH FASTKALK WHERE FASTKALK.OMRADE = valomr
NO-LOCK.
DO TRANSACTION:
   GET FIRST kkq EXCLUSIVE-LOCK.
   IF AVAILABLE FASTKALK THEN DO:
      FASTKALK.OMRADE = bytomr.
   END.
END.
REPEAT:
   DO TRANSACTION:
      GET NEXT kkq EXCLUSIVE-LOCK.
      IF AVAILABLE FASTKALK THEN DO:
         FASTKALK.OMRADE = bytomr.
      END.
      ELSE LEAVE.
   END.
END.
CLOSE QUERY kkq.
OPEN QUERY befq FOR EACH KALKBEF WHERE KALKBEF.OMRADE = valomr
NO-LOCK.
DO TRANSACTION:
   GET FIRST befq EXCLUSIVE-LOCK.
   IF AVAILABLE KALKBEF THEN DO:
      KALKBEF.OMRADE = bytomr.
   END.
END.
REPEAT:
   DO TRANSACTION:
      GET NEXT befq EXCLUSIVE-LOCK.
      IF AVAILABLE KALKBEF THEN DO:
         KALKBEF.OMRADE = bytomr.
      END.
      ELSE LEAVE.
   END.
END.
CLOSE QUERY befq.

OPEN QUERY fq FOR EACH FAKTOR WHERE FAKTOR.OMRADE = valomr NO-LOCK.
DO TRANSACTION:
   GET FIRST fq EXCLUSIVE-LOCK.
   IF AVAILABLE FAKTOR THEN DO:
      FAKTOR.OMRADE = bytomr.
   END.
END.
REPEAT:
   GET NEXT fq EXCLUSIVE-LOCK.
   IF AVAILABLE FAKTOR THEN DO:
      FAKTOR.OMRADE = bytomr.
   END.
   ELSE LEAVE.
END.
CLOSE QUERY fq.

OPEN QUERY mtrlq FOR EACH FASTSPEC WHERE FASTSPEC.OMRADE = valomr
NO-LOCK.
DO TRANSACTION:
   GET FIRST mtrlq EXCLUSIVE-LOCK.
   IF AVAILABLE FASTSPEC THEN DO:
      FASTSPEC.OMRADE = bytomr.
   END.
END.
REPEAT:
   DO TRANSACTION:
      GET NEXT mtrlq EXCLUSIVE-LOCK.
      IF AVAILABLE FASTSPEC THEN DO:
         FASTSPEC.OMRADE = bytomr.
      END.
      ELSE LEAVE.
   END.
END.
/*SLUT KALKYL*/

/*MARKVÄRDERING*/
OPEN QUERY vardq FOR EACH VARDINT WHERE VARDINT.OMRADE = valomr
NO-LOCK.
DO TRANSACTION:
   GET FIRST vardq EXCLUSIVE-LOCK.
   IF AVAILABLE VARDINT THEN DO:
      VARDINT.OMRADE = bytomr.
   END.
END.
REPEAT:
   DO TRANSACTION:
      GET NEXT vardq EXCLUSIVE-LOCK.
      IF AVAILABLE VARDINT THEN DO:
         VARDINT.OMRADE = bytomr.
      END.
      ELSE LEAVE.
   END.
END.

OPEN QUERY vardq2 FOR EACH VARDERING WHERE VARDERING.OMRADE = valomr
NO-LOCK.
DO TRANSACTION:
   GET FIRST vardq2 EXCLUSIVE-LOCK.
   IF AVAILABLE VARDERING THEN DO:
      VARDERING.OMRADE = bytomr.
   END.
END.
REPEAT:
   DO TRANSACTION:
      GET NEXT vardq2 EXCLUSIVE-LOCK.
      IF AVAILABLE VARDERING THEN DO:
         VARDERING.OMRADE = bytomr.
      END.
      ELSE LEAVE.
   END.
END.

OPEN QUERY vardq3 FOR EACH OFFERT WHERE OFFERT.OMRADE = valomr
NO-LOCK.
DO TRANSACTION:
   GET FIRST vardq3 EXCLUSIVE-LOCK.
   IF AVAILABLE OFFERT THEN DO:
      OFFERT.OMRADE = bytomr.
   END.
END.
REPEAT:
   DO TRANSACTION:
      GET NEXT vardq3 EXCLUSIVE-LOCK.
      IF AVAILABLE OFFERT THEN DO:
         OFFERT.OMRADE = bytomr.
      END.
      ELSE LEAVE.
   END.
END.
/*SLUT MARKVÄRDERING*/

/*ANVANDARE & PERSONAL*/
OPEN QUERY persq FOR EACH PERSONALTAB WHERE PERSONALTAB.OMRADE = valomr
NO-LOCK.
DO TRANSACTION:
   GET FIRST persq EXCLUSIVE-LOCK.
   IF AVAILABLE PERSONALTAB THEN DO:
      PERSONALTAB.OMRADE = bytomr.
   END.
END.
REPEAT:
   DO TRANSACTION:
      GET NEXT persq EXCLUSIVE-LOCK.
      IF AVAILABLE PERSONALTAB THEN DO:
         PERSONALTAB.OMRADE = bytomr.
      END.
      ELSE LEAVE.
   END.
END.
/*SLUT ANVANDARE & PERSONAL*/

/*ARBETSORDER*/
OPEN QUERY aoq FOR EACH AONRTAB WHERE AONRTAB.OMRADE = valomr
NO-LOCK.
DO TRANSACTION:
   GET FIRST aoq EXCLUSIVE-LOCK.
   IF AVAILABLE AONRTAB THEN DO:
      AONRTAB.OMRADE = bytomr.
   END.
END.
REPEAT:
   DO TRANSACTION:
      GET NEXT aoq EXCLUSIVE-LOCK.
      IF AVAILABLE AONRTAB THEN DO:
         AONRTAB.OMRADE = bytomr.
      END.
      ELSE LEAVE.
   END.
END.
/*SLUT ARBETSORDER*/

/*OMRÅDE*/
OPEN QUERY omrq FOR EACH OMRADETAB WHERE OMRADETAB.OMRADE = valomr
NO-LOCK.
DO TRANSACTION:
   GET FIRST omrq EXCLUSIVE-LOCK.
   IF AVAILABLE OMRADETAB THEN DO:
      OMRADETAB.OMRADE = bytomr.
   END.
END.
REPEAT:
   DO TRANSACTION:
      GET NEXT omrq EXCLUSIVE-LOCK.
      IF AVAILABLE OMRADETAB THEN DO:
         OMRADETAB.OMRADE = bytomr.
      END.
      ELSE LEAVE.
   END.
END.
/*SLUT OMRÅDE*/
{musarrow.i}
