/*Lägger innehåll i databas i urklipp*/
CLIPBOARD:MULTIPLE = TRUE.
CLIPBOARD:ITEMS-PER-ROW = 2.
FOR EACH AVDELNING NO-LOCK:
   CLIPBOARD:VALUE = STRING(AVDELNING.AVDELNINGNR).
   CLIPBOARD:VALUE = AVDELNING.AVDELNINGNAMN.
END.    
CLIPBOARD:MULTIPLE = FALSE.

