OPEN QUERY SQ FOR EACH SATS WHERE SATS.LEVKOD = "5" NO-LOCK.
DO TRANSACTION:
   GET FIRST SQ EXCLUSIVE-LOCK.
   DELETE SATS.
END.
REPEAT:
   DO TRANSACTION:
      GET NEXT SQ EXCLUSIVE-LOCK.
      IF AVAILABLE SATS THEN DELETE SATS.
      ELSE LEAVE.
   END.
END.
