/*
     Filename: XDUMMYOK2.P
      Created: 2004.03.09 08:58ELPAO     
     Modified: 
*/

DEFINE SHARED TEMP-TABLE temp NO-UNDO
   FIELD DUMMY1 AS CHARACTER
   FIELD DUMMY2 AS INTEGER
   FIELD DUMMY3 AS CHARACTER
   FIELD DUMMY4 AS CHARACTER
   FIELD DUMMY5 AS DECIMAL 
   INDEX DUMMY DUMMY1 DUMMY2 ASCENDING.

DEFINE SHARED TEMP-TABLE temp2 NO-UNDO LIKE temp. 

FIND FIRST temp2 NO-LOCK NO-ERROR.
IF AVAILABLE temp2 THEN DO:
   DISP temp2 WITH 1 COL.
END.
