/*
     Filename: XDUMMYOK.P
      Created: 2004.03.09 08:57ELPAO     
     Modified: 
*/

DEFINE NEW SHARED TEMP-TABLE temp NO-UNDO
   FIELD DUMMY1 AS CHARACTER
   FIELD DUMMY2 AS INTEGER
   FIELD DUMMY3 AS CHARACTER
   FIELD DUMMY4 AS CHARACTER
   FIELD DUMMY5 AS DECIMAL 
   INDEX DUMMY DUMMY1 DUMMY2 ASCENDING.

DEFINE NEW SHARED TEMP-TABLE temp2 NO-UNDO LIKE temp.

CREATE temp2.
ASSIGN
temp2.DUMMY1 = "Dummy1"
temp2.DUMMY2 = 2
temp2.DUMMY3 = "Dummy3".
DISP temp2.
RUN XDUMMYOK2.P.

