DEFINE NEW SHARED VARIABLE filnamn AS CHARACTER NO-UNDO.
DEFINE NEW SHARED VARIABLE skrivut AS LOGICAL NO-UNDO.
DEFINE NEW SHARED VARIABLE musz AS LOGICAL NO-UNDO.         
DEFINE VARIABLE str AS CHARACTER FORMAT "X(86)" NO-UNDO. 
DEFINE VARIABLE ar AS INTEGER NO-UNDO. 
DEFINE VARIABLE fackvar LIKE MTRLDEP.FACKID NO-UNDO.  
DEFINE VARIABLE var1 AS CHARACTER FORMAT "X(6)" NO-UNDO.
DEFINE VARIABLE var2 AS CHARACTER FORMAT "X(2)" NO-UNDO.
DEFINE VARIABLE langd AS INTEGER NO-UNDO.     
DEFINE VARIABLE fackid AS CHARACTER FORMAT "X(8)" NO-UNDO. 
DEFINE VARIABLE words AS CHARACTER FORMAT "X(132)" NO-UNDO.
DEFINE TEMP-TABLE tidin
   FIELD TIN AS CHARACTER FORMAT "X(132)".  

DEFINE NEW SHARED TEMP-TABLE temp_lop 
   FIELD ARBKOD LIKE LOP1.ARBKOD 
   FIELD LOPNR LIKE LOP1.LOPNR
   FIELD BEREDARE LIKE LOP1.F1
   INDEX LOP ARBKOD LOPNR.   
   
DEFINE NEW SHARED TEMP-TABLE no_bered 
   FIELD ARBKOD LIKE LOP1.ARBKOD 
   FIELD LOPNR LIKE LOP1.LOPNR  
   INDEX LOP ARBKOD LOPNR.   

/*p1 80,5*/
/*p2 84,5*/
/*p3 69,7*/      
   
INPUT FROM F:\PRO8\GURU\IMPORT\P3.Q NO-ECHO
CONVERT TARGET "iso8859-1" SOURCE "swedish-7-bit".
REPEAT:
   SET words VIEW-AS EDITOR INNER-CHARS 50 INNER-LINES 3 WITH FRAME DDD WIDTH 80.   
   CREATE TIDIN.   
   ASSIGN TIDIN.TIN = words.   
END.
INPUT CLOSE.

FOR EACH TIDIN:   
   CREATE temp_lop.
   ASSIGN
   temp_lop.ARBKOD = SUBSTRING(TIDIN.TIN,1,3)   /*   obs G */
   temp_lop.LOPNR = INTEGER(SUBSTRING(TIDIN.TIN,5,2))
   temp_lop.BEREDARE = DECIMAL(SUBSTRING(TIDIN.TIN,69,7)).  
END.      

OPEN QUERY lopq FOR EACH LOP3 WHERE LOP3.KATAR = 1999
USE-INDEX AR NO-LOCK.
GET FIRST lopq EXCLUSIVE-LOCK.
DO WHILE AVAILABLE(LOP3):
   FIND FIRST temp_lop WHERE temp_lop.ARBKOD = LOP3.ARBKOD
   AND temp_lop.LOPNR = LOP3.LOPNR USE-INDEX LOP NO-LOCK NO-ERROR.
   IF AVAILABLE temp_lop THEN DO:
      ASSIGN
      LOP3.F1 = temp_lop.BEREDARE
      LOP3.EA = LOP3.EA + temp_lop.BEREDARE
      LOP3.ARBETE = LOP3.F1 * 415 + LOP3.F2 * 415.
   END.
   ELSE DO:
      CREATE no_bered.
      ASSIGN
      no_bered.ARBKOD = LOP3.ARBKOD
      no_bered.LOPNR = LOP3.LOPNR.
   END.
   GET NEXT lopq EXCLUSIVE-LOCK.
END.   

FOR EACH no_bered USE-INDEX LOP:
   DISPLAY no_bered.ARBKOD no_bered.LOPNR.
END.     
  
