
DEF VAR aa AS DEC.
FUNCTION klockan100 RETURNS DECIMAL
  ( INPUT ber60 AS DECIMAL ):


  RETURN  (TRUNCATE(ber60,0) * 3600 + (ber60 - TRUNCATE(ber60,0)) * 100 * 60) / 3600.

END FUNCTION.
DEF VAR CC AS DEC.
DEF BUFFER fb FOR FAKTTID.
DEF TEMP-TABLE eftab
   FIELD RECVAR AS RECID
   FIELD faktnr AS INTEGER
   FIELD AONR AS CHAR
   FIELD BEFATTNING AS CHAR
   FIELD TIMMAR AS DEC
   FIELD OTIMMAR AS DEC
   FIELD VFAKTNR AS INTEGER
   INDEX FV IS PRIMARY VFAKTNR faktnr AONR BEFATTNING
   INDEX AONR faktnr AONR BEFATTNING.
OUTPUT TO PRINTER.

FOR EACH FAKTTID WHERE fakTtid.aonr = "173003" NO-LOCK  BY PERSONALKOD BY DATUM.

   FIND FIRST eftab WHERE RECVAR = RECID(FAKTTID) NO-ERROR.
   IF NOT AVAILABLE eftab THEN DO:
      FIND FIRST fb WHERE fb.personalkod = fakttid.personalkod AND 
      fb.AONR = FAKTTID.AONR AND fb.datum = FAKTTID.DATUM AND 
      fb.start = fakttid.START AND 
      fb.slut  = fakttid.slut AND 
      fb.faktnr = FAKTTID.faktnR AND RECID(FB) NE RECID(FAKTTID)
      NO-LOCK NO-ERROR.
      IF AVAILABLE fb THEN DO:
         CREATE eftab.
         RECVAR = RECID(FB).
     END.
     AA = AA + FAKTTID.timmar + FAKTTID.otimmar.
/*
     DISPLAY FAKTTID.PERSONALKOD FAKTTID.DATUM FAKTTID.START LABEL "START" FORMAT ">9.99" 
     FAKTTID.SLUT LABEL "slut" FORMAT ">9.99" FAKTTID.TIMMAR FORMAT ">9.99" FAKTTID.OTIMMAR FORMAT ">9.99" 
     FAKTTID.vfaktnr LABEL "vnr".
  */
   END.
END.

OUTPUT CLOSE.
OUTPUT TO PRINTER.
FOR EACH TIDregitab WHERE TIDregitab.aonr = "173003" AND YEAR(datum) = 2002 AND TIDLOG = TRUE NO-LOCK  BY PERSONALKOD BY DATUM.
   /*IF TIDregitab.DATUM > 06/27/2002 THEN cc = cc.
   ELSE*/
    IF TIDregitab.DATUM < 02/07/2002 THEN cc = cc.
   ELSE IF TIDregitab.PRISTYP = "RESTID..." THEN cc = cc.
   ELSE IF TIDregitab.veckokord = "" THEN cc = cc.
   ELSE DO:
      CC = CC + klockan100(TOTALT).
    /*  
      DISPLAY TIDregitab.PERSONALKOD TIDregitab.DATUM TIDregitab.START LABEL "START" FORMAT ">9.99" 
      TIDregitab.SLUT LABEL "slut" FORMAT ">9.99" TIDregitab.totalt FORMAT ">9.99" 
      TIDregitab.veckokord LABEL "vk" FORMAT "x(10)".
      */
   END.
END.
OUTPUT CLOSE.
MESSAGE AA CC VIEW-AS ALERT-BOX.
