/*ESSKAPAO.P*/
DEFINE NEW SHARED VARIABLE regdagnamn AS CHARACTER FORMAT "X(3)" NO-UNDO.
DEFINE NEW SHARED VARIABLE regvnr AS INTEGER FORMAT "999" NO-UNDO.
DEFINE NEW SHARED VARIABLE regdatum AS DATE NO-UNDO.
DEFINE VARIABLE musz AS LOGICAL NO-UNDO.
DEFINE VARIABLE chdatvar AS CHARACTER NO-UNDO.
DEFINE VARIABLE aorec AS RECID NO-UNDO.
DEFINE BUFFER fakbuff FOR FAKTPLAN.

DEFINE TEMP-TABLE tidin
   /*      
           BOLAG DATABAS  FÖRKL 
   ENHET   408 ESNORD   NS GAMLA TAS BORT 
           409=ETA      ETA
           414=ETA      ETA TRAFIKSYSTEM 
           905=ESMAL    ES MÄLARDALEN
           401=ESADM    ES AB ADMIN  
           402=ESADM    ESNORD NYA
   */
   FIELD ENHET              AS INTEGER FORMAT "999"             
   FIELD AONR               AS CHARACTER FORMAT "X(8)" 
   FIELD AOBENAMNING        AS CHARACTER FORMAT "X(25)" 
   FIELD UPPLDATUM          AS CHARACTER FORMAT "9999999999999" 
   FIELD REDOVISNINGSTYP    AS INTEGER FORMAT "9" 
   FIELD GILTDATUMFROM      AS CHARACTER FORMAT "9999999999999" /*PLAN START*/
   FIELD GILTDATUMTOM       AS CHARACTER FORMAT "9999999999999" 
   FIELD EKAVSLDATUM        AS CHARACTER FORMAT "9999999999999" 
   FIELD TEKNAVSLDATUM      AS CHARACTER FORMAT "9999999999999" /*AVSLUT*/
   FIELD AOTYP              AS CHARACTER FORMAT "X(1)" 
   FIELD ANDRDATUM          AS CHARACTER FORMAT "9999999999999" 
   FIELD HUVUDAONR          AS CHARACTER FORMAT "X(6)" 
   FIELD PRODUKT            AS CHARACTER FORMAT "X(2)" 
   FIELD PROJEKTLEDARE      AS INTEGER FORMAT "9999"  /*OM 8 TA EJ DENNA*/
   FIELD ASTATUS            AS CHARACTER FORMAT "X(1)" 
   FIELD KATEGORI           AS CHARACTER FORMAT "X(2)" 
   FIELD EKAVRAKNTIDPUNKT   AS CHARACTER FORMAT "9999999999999" 
   FIELD PROJEKT            AS CHARACTER FORMAT "X(3)" 
   FIELD AKTIVITET          AS CHARACTER FORMAT "X(1)" 
   FIELD HUVUDKUNDNR        AS INTEGER FORMAT "999999" 
   FIELD ANSVAR             AS INTEGER FORMAT "9999" 
   FIELD INTERNKOD          AS CHARACTER FORMAT "X(3)" 
   FIELD FORLUSTPROJ        AS INTEGER FORMAT "9"
   FIELD TEKNAVSLTIDPUNKT   AS CHARACTER FORMAT "9999999999999" /*AVSLUT*/
   FIELD ANLAGGNING         AS CHARACTER FORMAT "X(40)" 
   FIELD OBJEKT             AS CHARACTER FORMAT "X(40)" 
   FIELD OBJEKTDEL          AS CHARACTER FORMAT "X(40)" 
   FIELD ARBETSPLATS        AS INTEGER FORMAT "9999" 
   FIELD BESTALLARE         AS CHARACTER FORMAT "X(20)" 
   FIELD KUNDEREF           AS CHARACTER FORMAT "X(20)" 
   FIELD KUNDNAMN           AS CHARACTER FORMAT "X(25)" 
   FIELD KUNDADR1           AS CHARACTER FORMAT "X(25)" 
   FIELD KUNDADR2           AS CHARACTER FORMAT "X(25)" 
   FIELD KUNDADR3           AS CHARACTER FORMAT "X(25)" 
   FIELD POSTNR             AS INTEGER FORMAT "99999" 
   FIELD POSTADR            AS CHARACTER FORMAT "X(13)" 
   FIELD AOARBPLATS         AS CHARACTER FORMAT "X(25)" 
   FIELD ARBOMFATT          AS CHARACTER VIEW-AS EDITOR SCROLLBAR-VERTICAL SIZE 68 BY 6     
   FIELD GROSSISTPRISLISTA  AS INTEGER FORMAT "9" 
   FIELD KUNDPRISLISTA      AS INTEGER FORMAT "9"
   FIELD ANBUDSSUMMA        AS INTEGER FORMAT "999999999" 
   FIELD KUNDTYP            AS INTEGER FORMAT "9"
   INDEX AONR IS PRIMARY AONR
   INDEX ENHET ENHET.

DEFINE INPUT PARAMETER indatvar AS INTEGER NO-UNDO.
DEFINE INPUT PARAMETER TABLE FOR tidin.

FOR EACH tidin WHERE tidin.ENHET = indatvar USE-INDEX AONR NO-LOCK:               
   DO TRANSACTION:                        
      FIND FIRST AONRTAB WHERE AONRTAB.AONR = SUBSTRING(tidin.AONR,1,6) AND 
      AONRTAB.DELNR = INTEGER(SUBSTRING(tidin.AONR,7,2))    
      USE-INDEX AONR EXCLUSIVE-LOCK NO-ERROR.
      IF NOT AVAILABLE AONRTAB THEN DO:
         CREATE AONRTAB.
         ASSIGN      
         AONRTAB.AONR = SUBSTRING(tidin.AONR,1,6)
         AONRTAB.DELNR = INTEGER(SUBSTRING(tidin.AONR,7,2))         
         AONRTAB.ARBARTKOD = 0
         AONRTAB.ARBBESKED = FALSE
         AONRTAB.ARTAL = ?            
         AONRTAB.BETNR = 0
         AONRTAB.ELVOMRKOD = 0
         AONRTAB.FAKTNR = 0
         AONRTAB.FASTKALK = FALSE
         AONRTAB.KALKNR = ?
         AONRTAB.PKOD = 0
         AONRTAB.PLANNR = ?
         AONRTAB.PRISTYP = "TOT.PRIS."
         AONRTAB.STARTDATUM = ?
         AONRTAB.TRAKTAMENTE = 0
         AONRTAB.UTFARDAT = ""
         AONRTAB.UTRYCKNING = FALSE.             
         IF SUBSTRING(STRING(tidin.PROJEKTLEDARE),1,1) = "8" THEN DO:
            AONRTAB.BEREDARE = SUBSTRING(STRING(tidin.PROJEKTLEDARE),2,3).                 
         END.   
         ELSE AONRTAB.BEREDARE = STRING(tidin.PROJEKTLEDARE).      
      END.
      ELSE NEXT.
      aorec = RECID(AONRTAB).
      ASSIGN
      AONRTAB.ANLNR = tidin.ANLAGGNING
      AONRTAB.ANM[1] = tidin.ARBOMFATT
     /* AONRTAB.ANM[2] = SUBSTRING(tidin.ARBOMFATT,69,68)
      AONRTAB.ANM[3] = SUBSTRING(tidin.ARBOMFATT,137,68) 
      AONRTAB.ANM[4] = SUBSTRING(tidin.ARBOMFATT,205,68) 
      AONRTAB.ANM[5] = SUBSTRING(tidin.ARBOMFATT,273,68)
      AONRTAB.ANM[6] = SUBSTRING(tidin.ARBOMFATT,341,68)  */                  
      AONRTAB.ARBUPPG[1] = tidin.AOARBPLATS
      AONRTAB.ARBUPPG[2] = tidin.KUNDNAMN                                                      
      AONRTAB.AUTOREG = TRUE
      AONRTAB.ORT = tidin.AOBENAMNING
      AONRTAB.ELVOMRKOD = 0.      
      IF tidin.KATEGORI = "ZA" THEN DO:
         AONRTAB.ELVOMRKOD = 1.
      END.
      IF tidin.KATEGORI = "ZB" THEN DO:
         AONRTAB.ELVOMRKOD = 3.
      END.
      IF tidin.KATEGORI = "ZC" THEN DO:
         AONRTAB.ELVOMRKOD = 2. 
      END.
      chdatvar = STRING(AONRTAB.ELVOMRKOD) + SUBSTRING(tidin.GILTDATUMTOM,1,8).
      AONRTAB.ELVOMRKOD = INTEGER(chdatvar).
      IF SUBSTRING(tidin.AONR,1,4) = "1099" THEN AONRTAB.OMRADE = "".
      ELSE DO: 
         IF tidin.KATEGORI = "ZC" THEN DO:
            FIND FIRST OMRADETAB WHERE OMRADETAB.ORGIDNUM = STRING(tidin.ANSVAR) NO-LOCK NO-ERROR.
            IF NOT AVAILABLE OMRADETAB THEN AONRTAB.OMRADE = "".
            ELSE AONRTAB.OMRADE = OMRADETAB.OMRADE.
         END.
         ELSE DO:
            FIND FIRST OMRADETAB WHERE 
            OMRADETAB.ORGIDNUM = STRING(tidin.ANSVAR) NO-LOCK NO-ERROR.
            IF NOT AVAILABLE OMRADETAB THEN DO:
               AONRTAB.OMRADE = STRING(tidin.ANSVAR).
              /* RUN medd_UI (INPUT "LOSU").*/
            END.
            ELSE AONRTAB.OMRADE = OMRADETAB.OMRADE.    
         END.      
      END.
      IF tidin.TEKNAVSLTIDPUNKT = "" AND tidin.EKAVRAKNTIDPUNKT = "" THEN DO:
         AONRTAB.AONRAVDATUM = 01/01/91.
      END.
      ELSE DO:
         IF tidin.TEKNAVSLTIDPUNKT NE "" THEN DO:
            IF MONTH(DATE(SUBSTRING(tidin.TEKNAVSLTIDPUNKT,1,8))) = 12 THEN 
            AONRTAB.AONRAVDATUM = 
            DATE(12,31,YEAR(DATE(SUBSTRING(TEKNAVSLTIDPUNKT,1,8)))).            
            ELSE AONRTAB.AONRAVDATUM = 
            DATE(MONTH(DATE(SUBSTRING(tidin.TEKNAVSLTIDPUNKT,1,8))) + 1,01,YEAR(DATE(SUBSTRING(tidin.TEKNAVSLTIDPUNKT,1,8)))) - 1.         
         END.
         ELSE DO:
            IF MONTH(DATE(SUBSTRING(tidin.EKAVRAKNTIDPUNKT,1,8))) = 12 THEN 
            AONRTAB.AONRAVDATUM = 
            DATE(12,31,YEAR(DATE(SUBSTRING(EKAVRAKNTIDPUNKT,1,8)))).            
            ELSE AONRTAB.AONRAVDATUM = 
            DATE(MONTH(DATE(SUBSTRING(tidin.EKAVRAKNTIDPUNKT,1,8))) + 1,01,YEAR(DATE(SUBSTRING(tidin.EKAVRAKNTIDPUNKT,1,8)))) - 1.         
         END.
      END.
     /*
      FIND FIRST PERSONALTAB WHERE PERSONALTAB.ANSTNR = STRING(tidin.PROJEKTLEDARE)
      NO-LOCK NO-ERROR.
      IF AVAILABLE PERSONALTAB THEN DO:
         FIND FIRST ANVANDARE WHERE 
         ANVANDARE.PERSONALKOD = PERSONALTAB.PERSONALKOD NO-LOCK NO-ERROR.
      END.
      */
     
      IF SUBSTRING(STRING(tidin.PROJEKTLEDARE),1,1) = "8" THEN DO:       
         FIND FIRST ANVANDARE WHERE 
         ANVANDARE.PERSONALKOD = SUBSTRING(STRING(tidin.PROJEKTLEDARE),2,3) 
         NO-LOCK NO-ERROR.
      END.
      ELSE DO:       
         FIND FIRST ANVANDARE WHERE 
         ANVANDARE.PERSONALKOD = STRING(tidin.PROJEKTLEDARE) NO-LOCK NO-ERROR.
      END.
     
      IF SUBSTRING(tidin.AONR,1,2) = "10" THEN AONRTAB.FASTAAONR = TRUE.      
      ELSE AONRTAB.FASTAAONR = FALSE.
      IF AVAILABLE PERSONALTAB THEN DO:
         AONRTAB.ARBANSVARIG = PERSONALTAB.PERSONALKOD.
      END.
      
      IF SUBSTRING(STRING(tidin.PROJEKTLEDARE),1,1) = "8" THEN DO:
         AONRTAB.ARBANSVARIG = SUBSTRING(STRING(tidin.PROJEKTLEDARE),2,3).                 
      END.   
      ELSE AONRTAB.ARBANSVARIG = STRING(tidin.PROJEKTLEDARE).
      
      regdatum = DATE(SUBSTRING(STRING(tidin.GILTDATUMFROM),1,8)).
      RUN REGDAG.P.
      RUN REGVEC.P.
      ASSIGN
      AONRTAB.STARTDAG = regdagnamn       
      AONRTAB.STARTVNR = regvnr.
      regdatum = DATE(SUBSTRING(tidin.GILTDATUMTOM,1,8)).
      RUN REGDAG.P.
      RUN REGVEC.P.         
      ASSIGN
      AONRTAB.SLUTDAG = regdagnamn       
      AONRTAB.SLUTVNR = regvnr.
   END. 
   DO TRANSACTION: 
      FIND AONRTAB WHERE RECID(AONRTAB) = aorec EXCLUSIVE-LOCK.
      IF AVAILABLE ANVANDARE THEN AONRTAB.ANVANDARE = ANVANDARE.ANVANDARE.   
      FIND FIRST BESTTAB WHERE BESTTAB.VIBESTID = STRING(tidin.HUVUDKUNDNR)
      NO-LOCK NO-ERROR.
      IF AVAILABLE BESTTAB THEN AONRTAB.BESTID = BESTTAB.BESTID. 
      ELSE AONRTAB.BESTID = "099".
      IF tidin.KATEGORI = "FK" OR tidin.KATEGORI = "FP" OR
      tidin.KATEGORI = "FT" THEN DO:               
         AONRTAB.FAKTTYP = "Fastpris". 
         RUN fakt_UI (INPUT AONRTAB.FAKTTYP).       
      END.
      IF tidin.KATEGORI = "UA" OR tidin.KATEGORI = "UF" THEN DO:
         AONRTAB.FAKTTYP = "Avtal". 
         RUN fakt_UI (INPUT AONRTAB.FAKTTYP).       
      END.
      ELSE IF tidin.KATEGORI = "LP" OR tidin.KATEGORI = "LT" OR
         tidin.KATEGORI = "TB" OR tidin.KATEGORI = "UL" THEN DO:                 
         AONRTAB.FAKTTYP = "Löpande räkning".
         RUN fakt_UI (INPUT AONRTAB.FAKTTYP).
      END.
      ELSE IF tidin.KATEGORI = "LX" OR tidin.KATEGORI = "GA" OR
         tidin.KATEGORI = "KK" THEN DO:               
         AONRTAB.FAKTTYP = "Faktureras ej".
      END.   
   END.   
   DO TRANSACTION:
      FIND FIRST AONRKONTKOD WHERE AONRKONTKOD.AONR = AONRTAB.AONR AND 
      AONRKONTKOD.DELNR = AONRTAB.DELNR 
      USE-INDEX AONRKONT EXCLUSIVE-LOCK NO-ERROR.
      IF NOT AVAILABLE AONRKONTKOD THEN DO:
         CREATE AONRKONTKOD.                   
         AONRKONTKOD.SATS% = 100. 
      END.
      ASSIGN  
      AONRKONTKOD.AONR = AONRTAB.AONR
      AONRKONTKOD.DELNR = AONRTAB.DELNR
      AONRKONTKOD.K1 = STRING(tidin.ANSVAR)
      AONRKONTKOD.K2 = tidin.AKTIVITET                                        
      AONRKONTKOD.K3 = tidin.KATEGORI  
      AONRKONTKOD.K4 = tidin.PRODUKT
      AONRKONTKOD.K5 = STRING(tidin.REDOVISNINGSTYP).
   END.
END.
PROCEDURE fakt_UI.
   IF indatvar = 401 OR indatvar = 402 OR indatvar = 403 OR indatvar = 404 THEN indatvar = indatvar.
   ELSE RETURN.
   DEFINE INPUT PARAMETER typfak AS CHARACTER NO-UNDO. 
   FIND FIRST BESTTAB WHERE BESTTAB.BESTID = AONRTAB.BESTID 
   USE-INDEX BEST NO-LOCK NO-ERROR. 
   IF NOT AVAILABLE BESTTAB THEN RETURN.
   IF AONRTAB.FAKTNR = 0 THEN DO:         
      FIND LAST fakbuff USE-INDEX FAKTNR NO-LOCK NO-ERROR.
      CREATE FAKTPLAN.      
      ASSIGN
      FAKTPLAN.NAMN = AONRTAB.ORT
      FAKTPLAN.OMRADE = AONRTAB.OMRADE
      FAKTPLAN.BESTID = BESTTAB.BESTID
      FAKTPLAN.VISAONR = AONRTAB.AONR + " " + STRING(AONRTAB.DELNR,">99").         
      /*
      FAKTPLAN.OFFERTPRIS = FILL-IN_TOTPRIS
      FAKTPLAN.TAKPRIS = FILL-IN_TAKPRIS.
      */
      IF AVAILABLE fakbuff THEN ASSIGN FAKTPLAN.FAKTNR = fakbuff.FAKTNR + 1.
      ELSE ASSIGN FAKTPLAN.FAKTNR = 1.
      ASSIGN 
      FAKTPLAN.FAKTTYP = typfak.
      AONRTAB.FAKTNR = FAKTPLAN.FAKTNR.
      FIND FIRST KUNDREGLER WHERE KUNDREGLER.BESTID = BESTTAB.BESTID 
      USE-INDEX KUNDREGLER NO-LOCK NO-ERROR.     
      IF AVAILABLE KUNDREGLER THEN DO:
         CREATE FAKTREGLER. 
         ASSIGN       
         FAKTREGLER.FAKTNR = FAKTPLAN.FAKTNR    
         FAKTREGLER.KOSTREGRGL = KUNDREGLER.KOSTREGRGL
         FAKTREGLER.LONRGL = KUNDREGLER.LONRGL 
         FAKTREGLER.MTRLRGL = KUNDREGLER.MTRLRGL 
         FAKTREGLER.OVERTIDRGL = KUNDREGLER.OVERTIDRGL
         FAKTREGLER.OVRKRGL = KUNDREGLER.OVRKRGL       
         FAKTREGLER.TIMRGL = KUNDREGLER.TIMRGL
         FAKTREGLER.TRAKTRGL = KUNDREGLER.TRAKTRGL 
         FAKTREGLER.FAKINT = KUNDREGLER.FAKINT   
         FAKTREGLER.ENTRAK = KUNDREGLER.ENTRAK 
         FAKTREGLER.FLERTRAK = KUNDREGLER.FLERTRAK 
         FAKTREGLER.MIL = KUNDREGLER.MIL
         FAKTREGLER.FRTJPA = KUNDREGLER.FRTJPA 
         FAKTREGLER.MTRLPA = KUNDREGLER.MTRLPA
         FAKTREGLER.FDAGAR = KUNDREGLER.FDAGAR
         FAKTREGLER.INTAKTID = KUNDREGLER.INTAKTID 
         FAKTREGLER.KUNDKONTOID = KUNDREGLER.KUNDKONTOID 
         FAKTREGLER.MOMSID = KUNDREGLER.MOMSID 
         FAKTREGLER.MOTPARTID = KUNDREGLER.MOTPARTID
         FAKTREGLER.FDAGAR = KUNDREGLER.FDAGAR
         FAKTREGLER.KUNDID = KUNDREGLER.KUNDID.             
      END.
      CREATE FAKTKOLL.
      ASSIGN
      FAKTKOLL.AONR = AONRTAB.AONR
      FAKTKOLL.DELNR = AONRTAB.DELNR
      FAKTKOLL.BESTID = FAKTPLAN.BESTID
      FAKTKOLL.FAKTNR = FAKTPLAN.FAKTNR
      FAKTKOLL.SENASTFAK = ?
      FAKTKOLL.SENASTTID = ?
      FAKTKOLL.SLUTFAKT = FALSE
      FAKTKOLL.VECKOKORD = "".      
      IF FAKTREGLER.OVERTIDRGL = "EGNA REGLER" THEN FAKTPLAN.EGNAOVR = TRUE.   
      CREATE FAKTAONR.
      ASSIGN
      FAKTAONR.FAKTNR = FAKTPLAN.FAKTNR 
      FAKTAONR.AONR = AONRTAB.AONR  
      FAKTAONR.DELNR = AONRTAB.DELNR
      FAKTAONR.OMRADE = AONRTAB.OMRADE
      FAKTAONR.GDATUM = AONRTAB.ELVOMRKOD.                   
      FIND FIRST KALKSPEC WHERE KALKSPEC.AONR = FAKTAONR.AONR AND 
      KALKSPEC.DELNR = FAKTAONR.DELNR
      USE-INDEX AONR NO-LOCK NO-ERROR.
      IF AVAILABLE KALKSPEC THEN DO:
         ASSIGN FAKTAONR.KALKPRIS = KALKSPEC.KALKPRIS.                       
      END.
   END.      
   FIND FIRST FAKTPLAN WHERE FAKTPLAN.FAKTNR = AONRTAB.FAKTNR EXCLUSIVE-LOCK NO-ERROR.
   FAKTPLAN.PROJEKTKOD = tidin.PROJEKT. 
   FIND FIRST FAKTNAMN WHERE FAKTNAMN.FAKTURNR = FAKTPLAN.FAKTNR EXCLUSIVE-LOCK NO-ERROR.
   IF NOT AVAILABLE FAKTNAMN THEN DO:
      CREATE FAKTNAMN.
      ASSIGN
      FAKTNAMN.FAKTURNR = FAKTPLAN.FAKTNR 
      FAKTNAMN.FDELNR = 0.
   END.   
   ASSIGN           
   FAKTNAMN.BESTNAMN = BESTTAB.BESTNAMN
   FAKTNAMN.FAKADRESS = BESTTAB.FAKADRESS
   FAKTNAMN.TEL = BESTTAB.TEL
   FAKTNAMN.FAKORT = BESTTAB.FAKORT 
   FAKTNAMN.FAKPNR = BESTTAB.FAKPNR
   FAKTNAMN.KONTAKT = BESTTAB.KONTAKT
   FAKTNAMN.BESTALLARE = tidin.BESTALLARE
   FAKTNAMN.ARBOMF = tidin.ARBOMFATT.
   IF AVAILABLE ANVANDARE THEN DO:
      ASSIGN
      FAKTPLAN.ANVANDARE = ANVANDARE.ANVANDARE
      FAKTNAMN.VARREF = ANVANDARE.AV-NAMN.
   END.
   ELSE DO:
      FIND FIRST FAKTURADM USE-INDEX ANDV NO-LOCK NO-ERROR.
      FAKTPLAN.ANVANDARE = FAKTURADM.ANVANDARE. 
   END.                     
END PROCEDURE.

PROCEDURE medd_UI.
   DEFINE INPUT PARAMETER medpers LIKE  MEDDELANDE.MOTTAGARE.
   DEFINE VARIABLE str AS CHARACTER NO-UNDO.
   FIND FIRST MEDDELANDE WHERE MEDDELANDE.SANDARE = "AOSYS" AND 
   MEDDELANDE.MOTTAGARE = medpers AND LENGTH(MEDDELANDE.MEDD,"CHARACTER") < 30000
   EXCLUSIVE-LOCK NO-ERROR.
   IF NOT AVAILABLE MEDDELANDE THEN DO:
      ASSIGN  
      SUBSTRING(str,1,6) = "AONR"
      SUBSTRING(str,8,9) = "BENÄMNING"
      SUBSTRING(str,37,6) = "ANSVAR".
      CREATE MEDDELANDE.
      ASSIGN               
      MEDDELANDE.SANDARE = "AOSYS"
      MEDDELANDE.EMOTAGET = FALSE
      MEDDELANDE.MOTTAGARE = medpers
      MEDDELANDE.SDATUM = TODAY.
      MEDDELANDE.MEDD = "FELAKTIGT ANSVAR" + CHR(10) +
      str + CHR(10).        
   END.     
   str = "".    
   ASSIGN  
   SUBSTRING(str,1,6) = AONRTAB.AONR
   SUBSTRING(str,8,9) = SUBSTRING(AONRTAB.ORT,1,27)
   SUBSTRING(str,37,6) = AONRTAB.OMRADE. 
   ASSIGN
   MEDDELANDE.MED = MEDDELANDE.MED + str + CHR(10).     
END PROCEDURE.
