/*XSTANSVA.P. STANSKÖRNING VATTENFALL*/
DEFINE NEW SHARED VARIABLE vkdatum AS DATE NO-UNDO.
DEFINE NEW SHARED VARIABLE globanv LIKE ANVANDARE.ANVANDARE NO-UNDO.

DEFINE NEW SHARED VARIABLE appcon AS LOGICAL NO-UNDO.

DEFINE NEW SHARED VARIABLE tperiod AS INTEGER FORMAT "999" NO-UNDO.
DEFINE NEW SHARED VARIABLE korlage AS CHARACTER FORMAT "X(50)" NO-UNDO.
DEFINE TEMP-TABLE pa90fil
   FIELD PPERSONNUMMER LIKE PERSONALTAB.PERSONNUMMER
   FIELD PLONTILLAGG LIKE TIDREGITAB.LONTILLAGG
   FIELD PLONTILLANTAL AS DECIMAL FORMAT "-999.99"
   FIELD POVERTIDTILL LIKE TIDREGITAB.OVERTIDTILL
   FIELD POVERANTAL LIKE TIDREGITAB.OVERANTAL
   FIELD PTRAKTKOD LIKE TIDREGITAB.TRAKTKOD
   FIELD PTRAKTANTAL LIKE TIDREGITAB.TRAKTANTAL
   FIELD PBEREDSKAP LIKE TIDREGITAB.BEREDSKAP
   FIELD PBERANTAL LIKE TIDREGITAB.BERANTAL
   FIELD PDATUM LIKE TIDREGITAB.DATUM
   FIELD PVECKONUMMER LIKE TIDREGITAB.VECKONUMMER
   FIELD PSORT AS CHARACTER FORMAT "XX"
   FIELD PPAR8 AS DECIMAL FORMAT "-99.99"
   FIELD PANSTNR LIKE PERSONALTAB.ANSTNR
   FIELD AONR LIKE TIDREGITAB.AONR
   FIELD DELNR LIKE TIDREGITAB.DELNR
   FIELD PAVTAL AS CHARACTER
   FIELD BOLAG AS CHARACTER FORMAT "X(2)"
   INDEX PANSTNR IS PRIMARY PANSTNR ASCENDING.

globanv = CHR(69) + CHR(76) + CHR(80) + CHR(65) + CHR(79).
vkdatum = 05/31/2001.

tperiod = 922.
CREATE SERVER Guru.Konstanter:apphand.
appcon = Guru.Konstanter:apphand:CONNECT("-S appesab -H elpaso.sydkraft.se -N TCP",CHR(69) + CHR(76) + CHR(80) + CHR(65) + CHR(79),"KAGGEN","") NO-ERROR. 

      korlage = "Nu startar lönesammanställning " + STRING(TIME,"HH:MM:SS").  
      DISPLAY korlage VIEW-AS TEXT  NO-LABELS.
      PAUSE 0.      
      RUN XSVE1.P ON Guru.Konstanter:apphand TRANSACTION DISTINCT (INPUT vkdatum, INPUT Guru.Konstanter:globanv, INPUT tperiod).     
      korlage = "Nu startar frånvarosammanställning " + STRING(TIME,"HH:MM:SS").
      DISPLAY  korlage VIEW-AS TEXT  NO-LABELS.
      PAUSE 0.      
      RUN XSFR1.P ON Guru.Konstanter:apphand TRANSACTION DISTINCT (INPUT vkdatum, INPUT Guru.Konstanter:globanv, INPUT tperiod).                 
     
      korlage = "Nu startar rättningssammanställning " + STRING(TIME,"HH:MM:SS").  
      DISPLAY korlage VIEW-AS TEXT  NO-LABELS.
      PAUSE 0.      
      RUN XSFE1.P ON Guru.Konstanter:apphand TRANSACTION DISTINCT (INPUT vkdatum, INPUT Guru.Konstanter:globanv, INPUT tperiod).  

IF Guru.Konstanter:appcon THEN Guru.Konstanter:appcon = Guru.Konstanter:apphand:DISCONNECT().
DELETE OBJECT Guru.Konstanter:apphand.
appcon = FALSE.
