 /*ESVE1.P*/
/*UNIX VERSION KOMMUN*/
/* skapar filen pa90hj som är veckans körning .Denna lägges till pa90veck.d*/
/*SKAPAR FILEN PA90VECK.P */
/*ALLA TILLÄGG SOM EKONOMI- OCH LÖNESAMMANSTÄLLS FÅR EN EGEN RAD I DENNA RAPPORT*/
/*RAPPORTEN LIGGER TILL GRUND FÖR MÅNADSKÖRNIING */
DEFINE INPUT PARAMETER kordatum AS DATE NO-UNDO.
DEFINE INPUT PARAMETER koranv LIKE ANVANDARE.ANVANDARE NO-UNDO.

DEFINE NEW SHARED VARIABLE fnytid AS DECIMAL FORMAT "-99.99" NO-UNDO.
DEFINE NEW SHARED VARIABLE vkdatum AS DATE NO-UNDO.
DEFINE NEW SHARED VARIABLE regvnr AS INTEGER FORMAT "999" NO-UNDO.     
DEFINE NEW SHARED VARIABLE regdatum AS DATE NO-UNDO.
DEFINE NEW SHARED VARIABLE regstart LIKE TIDREGITAB.START NO-UNDO. 
DEFINE NEW SHARED VARIABLE regslut LIKE TIDREGITAB.SLUT NO-UNDO.
DEFINE NEW SHARED VARIABLE persrec AS RECID NO-UNDO.
DEFINE NEW SHARED VARIABLE globanv LIKE ANVANDARE.ANVANDARE NO-UNDO.

DEFINE NEW SHARED VARIABLE globforetag LIKE FORETAG.FORETAG NO-UNDO.

DEFINE NEW SHARED VARIABLE regdagnamn AS CHARACTER FORMAT "X(3)" NO-UNDO.        
DEFINE NEW SHARED VARIABLE regtotalt LIKE TIDREGITAB.TOTALT NO-UNDO.
DEFINE NEW SHARED VARIABLE frustarten AS DECIMAL NO-UNDO.
DEFINE NEW SHARED VARIABLE fruslutet AS DECIMAL NO-UNDO.
DEFINE NEW SHARED VARIABLE kaffestart AS DECIMAL NO-UNDO.
DEFINE NEW SHARED VARIABLE kaffeslut AS DECIMAL NO-UNDO.
DEFINE NEW SHARED VARIABLE lunchstarten LIKE ARBETSTIDTAB.LUNCHSTART NO-UNDO.
DEFINE NEW SHARED VARIABLE lunchslutet LIKE ARBETSTIDTAB.LUNCHSLUT NO-UNDO.
DEFINE NEW SHARED VARIABLE nytid AS DECIMAL FORMAT "99.99" NO-UNDO.
DEFINE NEW SHARED VARIABLE sekunder AS INTEGER NO-UNDO.    


DEFINE VARIABLE antal LIKE TIDREGITAB.LONTILLANTAL NO-UNDO.   /*LÖN*/
DEFINE VARIABLE antalet LIKE PHJALP.PPAR8 NO-UNDO.   /*LÖN*/
DEFINE VARIABLE personal LIKE PERSONALTAB.PERSONALKOD.      /*LÖN*/
DEFINE VARIABLE pnr LIKE PERSONALTAB.PERSONNUMMER.      /*LÖN*/
DEFINE VARIABLE vecknr LIKE TIDREGITAB.VECKONUMMER.      /*LÖN*/
DEFINE VARIABLE overrapp1 AS CHARACTER FORMAT "X(70)".      /*LÖN*/
DEFINE VARIABLE overrapp2 AS CHARACTER FORMAT "X(70)".      /*ÖVERTID*/
DEFINE VARIABLE overrapp3 AS CHARACTER FORMAT "X(70)".      /*BEREEDSKAP*/
DEFINE VARIABLE overrapp4 AS CHARACTER FORMAT "X(70)".      /*TRAKTAMENTE*/
DEFINE VARIABLE rapphj1 AS CHARACTER FORMAT "X(9)".      /*HJÄLP ANTAL*/
DEFINE VARIABLE rapphj2 AS CHARACTER FORMAT "X(11)".      /*HJÄLP belopp*/
DEFINE VARIABLE datrapphj1 AS DATE FORMAT "999999".      /*HJÄLP datum*/
DEFINE VARIABLE rec AS RECID.
DEFINE VARIABLE para AS LOGICAL NO-UNDO.
DEFINE VARIABLE avtal1 LIKE PERSONALTAB.ANSTALLNING NO-UNDO.
DEFINE VARIABLE avtal LIKE ANSTFORMTAB.KOD NO-UNDO.  
DEFINE VARIABLE oversum AS INTEGER NO-UNDO. 
DEFINE VARIABLE total AS INTEGER NO-UNDO.
DEFINE VARIABLE oa1 AS INTEGER NO-UNDO.
DEFINE VARIABLE oa2 AS INTEGER NO-UNDO.
DEFINE VARIABLE oa3 AS INTEGER NO-UNDO.
DEFINE VARIABLE t2 AS INTEGER NO-UNDO.
DEFINE VARIABLE t3 AS INTEGER NO-UNDO.
DEFINE VARIABLE bryt AS LOGICAL NO-UNDO.
DEFINE VARIABLE nod AS LOGICAL NO-UNDO.
DEFINE VARIABLE flex AS LOGICAL NO-UNDO.
DEFINE VARIABLE fltid AS INTEGER NO-UNDO.
DEFINE VARIABLE seku AS INTEGER NO-UNDO.
DEFINE VARIABLE bolag AS CHARACTER FORMAT "X(2)" NO-UNDO.
DEFINE NEW SHARED TEMP-TABLE pa90fil
   FIELD PPERSONNUMMER LIKE PERSONALTAB.PERSONNUMMER
   FIELD PLONTILLAGG LIKE TIDREGITAB.LONTILLAGG
   FIELD PLONTILLANTAL LIKE TIDREGITAB.LONTILLANTAL
   FIELD POVERTIDTILL LIKE TIDREGITAB.OVERTIDTILL
   FIELD POVERANTAL LIKE TIDREGITAB.OVERANTAL
   FIELD PTRAKTKOD LIKE TIDREGITAB.TRAKTKOD
   FIELD PTRAKTANTAL LIKE TIDREGITAB.TRAKTANTAL
   FIELD PBEREDSKAP LIKE TIDREGITAB.BEREDSKAP
   FIELD PBERANTAL LIKE TIDREGITAB.BERANTAL
   FIELD PDATUM LIKE TIDREGITAB.DATUM
   FIELD PVECKONUMMER LIKE TIDREGITAB.VECKONUMMER
   FIELD PSORT AS CHARACTER FORMAT "XX"
   FIELD PPAR8 AS DECIMAL FORMAT "-99.99"
   FIELD PANSTNR LIKE PERSONALTAB.ANSTNR
   FIELD AONR LIKE TIDREGITAB.AONR
   FIELD DELNR LIKE TIDREGITAB.DELNR
   FIELD PAVTAL AS CHARACTER
   FIELD BOLAG AS CHARACTER FORMAT "X(2)"
   INDEX PANSTNR IS PRIMARY PANSTNR ASCENDING.
FIND FIRST FORETAG USE-INDEX FORETAG NO-LOCK NO-ERROR.
globforetag = FORETAG.FORETAG.
globanv = koranv.
vkdatum = kordatum.
FOR EACH pa90fil:
  DELETE pa90fil.
END.
OPEN QUERY pq FOR EACH PERSONALTAB WHERE PERSONALTAB.PERSMASK = TRUE
USE-INDEX PERSONALKOD NO-LOCK.
GET FIRST pq NO-LOCK.
DO WHILE AVAILABLE(PERSONALTAB):
   personal = PERSONALTAB.PERSONALKOD.
   avtal1 = PERSONALTAB.ANSTALLNING.
   persrec = RECID(PERSONALTAB).
   FIND FIRST ANSTFORMTAB WHERE ANSTFORMTAB.ANSTALLNING = avtal1
   USE-INDEX ANSTF NO-LOCK NO-ERROR.
   avtal = ANSTFORMTAB.KOD.
   IF globforetag = "NORD"  THEN ASSIGN bolag = "48".
   IF globforetag = "ETA" THEN DO:
      ASSIGN bolag = "49". 
      IF PERSONALTAB.OMRADE = "5800" THEN ASSIGN bolag = "55". /*ETA TRAFIK*/
      IF PERSONALTAB.OMRADE = "5810" THEN ASSIGN bolag = "55". /*ETA TRAFIK*/
   END.  
   IF globforetag = "ELPA" THEN DO:
      ASSIGN bolag = "49". 
      IF PERSONALTAB.OMRADE = "5800" THEN ASSIGN bolag = "55". /*ETA TRAFIK*/
      IF PERSONALTAB.OMRADE = "5810" THEN ASSIGN bolag = "55". /*ETA TRAFIK*/
   END. 
   IF globforetag = "ESAN" THEN DO:
      ASSIGN bolag = "50".
      IF PERSONALTAB.OMRADE = "1100" OR PERSONALTAB.OMRADE = "1100" OR PERSONALTAB.OMRADE = "1101"
      OR PERSONALTAB.OMRADE = "1102" OR PERSONALTAB.OMRADE = "1103" OR PERSONALTAB.OMRADE = "1104"
      OR PERSONALTAB.OMRADE = "1200" OR PERSONALTAB.OMRADE = "1201" OR PERSONALTAB.OMRADE = "1202"
      OR PERSONALTAB.OMRADE = "1203" OR PERSONALTAB.OMRADE = "1204" OR PERSONALTAB.OMRADE = "1205"
      THEN ASSIGN bolag = "41".
   END.   
   IF globforetag = "ESMA" THEN ASSIGN bolag = "51".   
   OPEN QUERY tq FOR EACH TIDREGITAB WHERE
   TIDREGITAB.PERSONALKOD = PERSONALTAB.PERSONALKOD AND
   TIDREGITAB.VECKOKORD NE "" USE-INDEX PSTART NO-LOCK. 
   GET FIRST tq NO-LOCK.
   DO WHILE AVAILABLE(TIDREGITAB):
      IF (TIDREGITAB.TRAKTKOD = " "  OR TIDREGITAB.TRAKTANTAL = 0)  THEN VKDATUM = VKDATUM.        
      ELSE DO :    	  
         IF TIDREGITAB.TRAKTKOD NE " " AND TIDREGITAB.TRAKTANTAL NE 0
	  THEN DO TRANSACTION:
	     IF globforetag = "ESAN" AND TIDREGITAB.AONR BEGINS "910" THEN nytid = nytid.
	     ELSE IF globforetag = "ESMA"  AND TIDREGITAB.AONR BEGINS "910" THEN nytid = nytid.
	     ELSE DO:
	        CREATE pa90fil.
	        ASSIGN pa90fil.PANSTNR = PERSONALTAB.ANSTNR
	        pa90fil.PTRAKTKOD = TIDREGITAB.TRAKTKOD
	        pa90fil.PTRAKTANTAL = TIDREGITAB.TRAKTANTAL
	        pa90fil.PDATUM = TIDREGITAB.DATUM
	        pa90fil.PVECKONUMMER = TIDREGITAB.VECKONUMMER
	        pa90fil.AONR = TIDREGITAB.AONR
               pa90fil.DELNR = TIDREGITAB.DELNR
               pa90fil.PAVTAL = PERSONALTAB.TRAAVTAL
               pa90fil.BOLAG = bolag.
            END.   
	  END.

      END.	  
      GET NEXT tq.
   END.
   GET NEXT pq.
END.
FOR EACH pa90fil WHERE pa90fil.PANSTNR = " ":
  DELETE pa90fil.
END.
FOR EACH pa90fil where pa90fil.PTRAKTKOD NE "":
   FIND FIRST TRAKTATAB WHERE TRAKTATAB.TRAKTKOD = pa90fil.PTRAKTKOD
   AND TRAKTATAB.TRAAVTAL = pa90fil.PAVTAL USE-INDEX TRAAV 
   NO-LOCK NO-ERROR.
   IF AVAILABLE TRAKTATAB THEN ASSIGN pa90fil.PTRAKTKOD = TRAKTATAB.VILART.
END.  

RUN ESVE3.P.      /* summerar veckans skörd till tidigare */
