   OPEN QUERY fpq FOR EACH rt9.FAKTPLAN WHERE rt9.FAKTPLAN.SLUTFAKT = FALSE AND 
   rt9.FAKTPLAN.FAKTTYP = "Takprisfakt." AND
   rt9.FAKTPLAN.FAKTTYPUNDER = 4 NO-LOCK BY rt9.FAKTPLAN.FAKTNR.
   GET FIRST fpq NO-LOCK.
   DO WHILE AVAILABLE(rt9.FAKTPLAN): 
      
      
      FOR EACH rt9.FAKTUPPARB WHERE rt9.FAKTUPPARB.FAKTNR = rt9.FAKTPLAN.FAKTNR:
         DELETE rt9.FAKTUPPARB.
      END.
      FOR EACH utbi.FAKTUPPARB.AONR FAKTUPPARB.UPPARB% FAKTUPPARB.UPPBELOPP WHERE utbi.FAKTUPPARB.FAKTNR = RT9.FAKTPLAN.FAKTNR:
         CREATE RT9.FAKTUPPARB.
         BUFFER-COPY utbi.FAKTUPPARB TO rt9.FAKTUPPARB.
      END.
      
      GET NEXT fpq NO-LOCK.
   END.
