/*ÖVERLÄSNING FRÅN EN DEPA TILL EN ANNAN*/


DEFINE QUERY mtrlq FOR MTRLDEP.
DEFINE BUFFER mtrlbuff FOR MTRLDEP.  
DEFINE QUERY depq FOR mtrlbuff.  

OPEN QUERY mtrlq FOR EACH MTRLDEP WHERE MTRLDEP.DEPNR = 731 
AND MTRLDEP.IBDATUM = ? AND MTRLDEP.LAGER = TRUE USE-INDEX DEPNR NO-LOCK. 
DO TRANSACTION:
GET FIRST mtrlq EXCLUSIVE-LOCK.
DO WHILE AVAILABLE(MTRLDEP):               
   DELETE MTRLDEP.
   GET NEXT mtrlq EXCLUSIVE-LOCK.  
END.
END.
CLOSE QUERY mtrlq.

OPEN QUERY depq FOR EACH mtrlbuff WHERE mtrlbuff.DEPNR = 71 
AND mtrlbuff.IBDATUM = ? AND mtrlbuff.LAGER = TRUE NO-LOCK.
GET FIRST depq NO-LOCK.
DO WHILE AVAILABLE(mtrlbuff):
   DO TRANSACTION:
      CREATE MTRLDEP.
      ASSIGN
      MTRLDEP.DEPNR = 731
      MTRLDEP.ENR = mtrlbuff.ENR
      MTRLDEP.BENAMNING = mtrlbuff.BENAMNING
      MTRLDEP.ENHET = mtrlbuff.ENHET
      MTRLDEP.BESTPUNKT = mtrlbuff.BESTPUNKT
      MTRLDEP.BESTKVANT = mtrlbuff.BESTKVANT   
      MTRLDEP.BPRIS = mtrlbuff.BPRIS
      MTRLDEP.NPRIS = mtrlbuff.NPRIS
      MTRLDEP.LEVKOD = mtrlbuff.LEVKOD 
      MTRLDEP.FACKID = mtrlbuff.FACKID
      MTRLDEP.OMSATT = mtrlbuff.OMSATT   
      MTRLDEP.INVDATUM = mtrlbuff.INVDATUM
      MTRLDEP.INVANT = 0.
   END.
   GET NEXT depq NO-LOCK.                         
END.
CLOSE QUERY depq.    
