/*G:\DELAD\PRO9\GURU\XFRKOR.P*/
DEFINE NEW SHARED VARIABLE globforetag LIKE FORETAG.FORETAG NO-UNDO.
 
DEFINE  VARIABLE appcon AS LOGICAL NO-UNDO.
FIND FIRST FORETAG USE-INDEX FORETAG NO-LOCK NO-ERROR.
globforetag = FORETAG.FORETAG.
{CONAPP.I}

RUN XGRFR2.P ON Guru.Konstanter:apphand TRANSACTION DISTINCT  
            (INPUT 07/31/2003, INPUT TRUE, INPUT "ELPA",INPUT 7).           .

IF Guru.Konstanter:appcon THEN Guru.Konstanter:appcon = Guru.Konstanter:apphand:DISCONNECT().
         DELETE OBJECT Guru.Konstanter:apphand.

