/*XSUKOR.P. STANSKÖRNING sundsvall*/
DEFINE NEW SHARED VARIABLE vkdatum AS DATE NO-UNDO.
DEFINE NEW SHARED VARIABLE globanv LIKE ANVANDARE.ANVANDARE NO-UNDO.

DEFINE NEW SHARED VARIABLE appcon AS LOGICAL NO-UNDO.


DEFINE TEMP-TABLE lonefil
   FIELD PPERSONNUMMER LIKE PERSONALTAB.PERSONNUMMER
   FIELD START LIKE TIDREGITAB.START
   FIELD SLUT LIKE TIDREGITAB.SLUT
   FIELD PLONTILLAGG LIKE TIDREGITAB.LONTILLAGG
   FIELD PLONTILLANTAL LIKE TIDREGITAB.LONTILLANTAL
   FIELD POVERTIDTILL LIKE TIDREGITAB.OVERTIDTILL
   FIELD POVERANTAL LIKE TIDREGITAB.OVERANTAL
   FIELD PTRAKTKOD LIKE TIDREGITAB.TRAKTKOD
   FIELD PTRAKTANTAL LIKE TIDREGITAB.TRAKTANTAL
   FIELD PBEREDSKAP LIKE TIDREGITAB.BEREDSKAP
   FIELD PBERANTAL LIKE TIDREGITAB.BERANTAL
   FIELD PDATUM LIKE TIDREGITAB.DATUM
   FIELD SLUTDATUM LIKE TIDREGITAB.DATUM INITIAL ?
   FIELD PVECKONUMMER LIKE TIDREGITAB.VECKONUMMER
   FIELD MANAD AS INTEGER
   FIELD PSORT AS CHARACTER FORMAT "XX"
   FIELD PPAR8 AS DECIMAL FORMAT "-99.99"
   FIELD AONR LIKE TIDREGITAB.AONR
   FIELD DELNR LIKE TIDREGITAB.DELNR
   FIELD PAVTAL AS CHARACTER
   FIELD TID AS LOGICAL
   FIELD BERKOLL AS LOGICAL INITIAL FALSE
   FIELD PROCENT AS DECIMAL FORMAT "999.9"
   FIELD NAMN AS CHARACTER
   FIELD RESMAL AS CHARACTER
   INDEX PPERSONNUMMER IS PRIMARY PPERSONNUMMER ASCENDING.

globanv = CHR(69) + CHR(76) + CHR(80) + CHR(65) + CHR(79).
vkdatum = 05/31/2002.
CREATE SERVER Guru.Konstanter:apphand.
appcon = Guru.Konstanter:apphand:CONNECT("-AppService appnsund -H 194.132.143.8 -S 2518",CHR(69) + CHR(76) + CHR(80) + CHR(65) + CHR(79),"KAGGEN","sundn9") NO-ERROR.     
/*RUN SUTILL1.P ON Guru.Konstanter:apphand TRANSACTION DISTINCT (INPUT vkdatum, INPUT Guru.Konstanter:globanv,OUTPUT TABLE lonefil).
MESSAGE "SUTILL1".
RUN SUFR1.P ON Guru.Konstanter:apphand TRANSACTION DISTINCT (INPUT vkdatum, INPUT Guru.Konstanter:globanv,INPUT TABLE lonefil).
MESSAGE "SUFR1".*/


/*RUN SUNDEKO.P ON Guru.Konstanter:apphand TRANSACTION DISTINCT (INPUT vkdatum).
RUN SUFEEKO.P ON Guru.Konstanter:apphand TRANSACTION DISTINCT (INPUT vkdatum).*/
/*RUN SUFEEKO.P (INPUT vkdatum).*/

/* kör redan veckokörd*/
RUN XSUTILL1.P ON Guru.Konstanter:apphand TRANSACTION DISTINCT (INPUT vkdatum, INPUT Guru.Konstanter:globanv,OUTPUT TABLE lonefil).
MESSAGE "XSUTILL1".
RUN XSUNFR1.P ON Guru.Konstanter:apphand TRANSACTION DISTINCT (INPUT vkdatum, INPUT Guru.Konstanter:globanv,INPUT TABLE lonefil).
MESSAGE "XSUNFR1". 


IF Guru.Konstanter:appcon THEN Guru.Konstanter:appcon = Guru.Konstanter:apphand:DISCONNECT().
DELETE OBJECT Guru.Konstanter:apphand.
appcon = FALSE.
