DEFINE TEMP-TABLE mtrl_test
   FIELD ENR LIKE MTRL.ENR.
DEFINE QUERY mtrlq FOR MTRL.
DEFINE QUERY depq FOR MTRLDEP.

OPEN QUERY mtrlq FOR EACH MTRL WHERE MTRL.LEVKOD = "11" NO-LOCK.
GET FIRST mtrlq NO-LOCK.
DO WHILE AVAILABLE(MTRL):
   FIND FIRST MTRLDEP WHERE MTRLDEP.DEPNR = 72 AND MTRLDEP.ENR = MTRL.ENR 
   EXCLUSIVE-LOCK NO-ERROR.
   IF AVAILABLE MTRLDEP THEN DO:
      ASSIGN
      MTRLDEP.LEVKOD = MTRL.LEVKOD
      MTRLDEP.ENHET = MTRL.ENHET.
   END.   
   GET NEXT mtrlq NO-LOCK.
END.
CLOSE QUERY mtrlq.

