/*XGRKOR.P. GRANINGE PROVKORNING*/
DEFINE NEW SHARED VARIABLE vkdatum AS DATE NO-UNDO.
DEFINE NEW SHARED VARIABLE globanv LIKE ANVANDARE.ANVANDARE NO-UNDO.
DEFINE NEW SHARED VARIABLE gvisatidpermanad AS LOGICAL NO-UNDO.

DEFINE NEW SHARED VARIABLE appcon AS LOGICAL NO-UNDO.


DEFINE TEMP-TABLE lonefil
   FIELD PPERSONNUMMER LIKE PERSONALTAB.PERSONNUMMER
   FIELD START LIKE TIDREGITAB.START
   FIELD SLUT LIKE TIDREGITAB.SLUT
   FIELD PLONTILLAGG LIKE TIDREGITAB.LONTILLAGG
   FIELD PLONTILLANTAL LIKE TIDREGITAB.LONTILLANTAL
   FIELD POVERTIDTILL LIKE TIDREGITAB.OVERTIDTILL
   FIELD POVERANTAL LIKE TIDREGITAB.OVERANTAL
   FIELD PTRAKTKOD LIKE TIDREGITAB.TRAKTKOD
   FIELD PTRAKTANTAL LIKE TIDREGITAB.TRAKTANTAL
   FIELD PBEREDSKAP LIKE TIDREGITAB.BEREDSKAP
   FIELD PBERANTAL LIKE TIDREGITAB.BERANTAL
   FIELD PDATUM LIKE TIDREGITAB.DATUM
   FIELD SLUTDATUM LIKE TIDREGITAB.DATUM INITIAL ?
   FIELD PVECKONUMMER LIKE TIDREGITAB.VECKONUMMER
   FIELD MANAD AS INTEGER
   FIELD PSORT AS CHARACTER FORMAT "XX"
   FIELD PPAR8 AS DECIMAL FORMAT "-99.99"
   FIELD AONR LIKE TIDREGITAB.AONR
   FIELD DELNR LIKE TIDREGITAB.DELNR
   FIELD PAVTAL AS CHARACTER
   FIELD TID AS LOGICAL
   FIELD BERKOLL AS LOGICAL INITIAL FALSE
   FIELD PROCENT AS DECIMAL FORMAT "999.9"
   FIELD NAMN AS CHARACTER
   FIELD RESMAL AS CHARACTER
   INDEX PPERSONNUMMER IS PRIMARY PPERSONNUMMER ASCENDING.





{CONAPP.I}
globanv = CHR(69) + CHR(76) + CHR(80) + CHR(65) + CHR(79).
vkdatum = 08/31/2002.    
gvisatidpermanad = TRUE.

RUN XGRANFR1.P  ON Guru.Konstanter:apphand TRANSACTION DISTINCT 
      (INPUT vkdatum, INPUT gvisatidpermanad, INPUT globforetag).

/*IF Guru.Konstanter:appcon THEN DO:
   RUN GRFEEKO.P ON Guru.Konstanter:apphand TRANSACTION DISTINCT (INPUT vkdatum).   
END.
ELSE DO:
   RUN GRFEEKO.P (INPUT vkdatum).   
END.
IF Guru.Konstanter:appcon THEN DO:
   RUN GRFEAOEK.P ON Guru.Konstanter:apphand TRANSACTION DISTINCT.   
END.
ELSE DO:   
   RUN GRFEAOEK.P.   
END.                 */
/*IF Guru.Konstanter:appcon THEN DO:
   RUN GRFEEKO.P ON Guru.Konstanter:apphand TRANSACTION DISTINCT (INPUT vkdatum).
   RUN GRFEAOEK.P ON Guru.Konstanter:apphand TRANSACTION DISTINCT.
END.
ELSE DO:
   RUN GRFEEKO.P (INPUT vkdatum).
   RUN GRFEAOEK.P.
END.         */

IF Guru.Konstanter:appcon THEN Guru.Konstanter:appcon = Guru.Konstanter:apphand:DISCONNECT().
DELETE OBJECT Guru.Konstanter:apphand.




