/*XISTRAS2.P*/                 
DEFINE VARIABLE istrans AS LOGICAL INITIAL YES.
DO ON ERROR UNDO:
   istrans = no.
   UNDO, LEAVE.
END.
OUTPUT TO C:DELAD\PRO8S\TRANS.TXT APPEND.
PUT "TRANSACTION AT" "{1}" istrans SKIP.
OUTPUT CLOSE.
