for each KALKYLKATALOG WHERE KLOGID = 16:
delete    KALKYLKATALOG .
end.
for each KALKYLKATALOGSUB WHERE KALKYLKATALOGSUB.KLOGSUBID = 31:
delete   KALKYLKATALOGSUB .
end.


for each KALKYLPRISER WHERE KALKYLPRISER.KLOGSUBID = 31:
delete   KALKYLPRISER .
end.

for each KALKYLARBKODER WHERE KALKYLARBKODER.KLOGSUBID = 31:
delete   KALKYLARBKODER .
end.

for each KALKYLLOPPOSTER WHERE KALKYLLOPPOSTER.KLOGSUBID = 31:
delete   KALKYLLOPPOSTER .
end.

for each KALKYLLOPSUB WHERE KALKYLLOPSUB.KLOGSUBID = 31:
delete   KALKYLLOPSUB .
end.
for each KALKYLKATALOG WHERE KLOGID = 16:
delete    KALKYLKATALOG .
end.
for each KALKYLKATALOGSUB WHERE KALKYLKATALOGSUB.KLOGSUBID = 32:
delete   KALKYLKATALOGSUB .
end.


for each KALKYLPRISER WHERE KALKYLPRISER.KLOGSUBID = 32:
delete   KALKYLPRISER .
end.

for each KALKYLARBKODER WHERE KALKYLARBKODER.KLOGSUBID = 32:
delete   KALKYLARBKODER .
end.

for each KALKYLLOPPOSTER WHERE KALKYLLOPPOSTER.KLOGSUBID = 32:
delete   KALKYLLOPPOSTER .
end.

for each KALKYLLOPSUB WHERE KALKYLLOPSUB.KLOGSUBID = 32:
delete   KALKYLLOPSUB .
end.
