/*XKOMPSATER.P.  ÅTERSTÄLLNING KOMPSALDO TILL FÖREGÅENDE KÖRNING*/
DEFINE NEW SHARED VARIABLE vkdatum AS DATE NO-UNDO.
DEFINE NEW SHARED VARIABLE forravkdatum AS DATE NO-UNDO.
DEFINE NEW SHARED VARIABLE korvar AS CHARACTER NO-UNDO.
DEFINE NEW SHARED VARIABLE globforetag LIKE FORETAG.FORETAG NO-UNDO.


DEFINE VARIABLE komplog AS LOGICAL NO-UNDO.



FIND FIRST FORETAG USE-INDEX FORETAG NO-LOCK NO-ERROR.
globforetag = FORETAG.FORETAG.
vkdatum = 04/30/2018.

RUN FINNSTABELL.P (INPUT "KOMPSALDO", OUTPUT komplog).
IF komplog = FALSE THEN RETURN.

RUN aterkompsaldo_UI.



PROCEDURE aterkompsaldo_UI.
  FOR EACH KOMPSALDO  EXCLUSIVE-LOCK USE-INDEX PKOD:
     DELETE KOMPSALDO.
  END.
  FOR EACH KPSALDOFOR NO-LOCK:
     CREATE KOMPSALDO.
     BUFFER-COPY KPSALDOFOR TO KOMPSALDO.
  END.
  FOR EACH KSALDMAN WHERE KSALDMAN.KORDTOM = vkdatum EXCLUSIVE-LOCK USE-INDEX PKOD: 
     DELETE KSALDMAN.
  END.    
   

   
END PROCEDURE.

