
OPEN QUERY SQ FOR EACH SUMTIDDAG WHERE AUTODATUM = 03/08/01 NO-LOCK.
GET FIRST SQ NO-LOCK.
DO  WHILE AVAILABLE(SUMTIDDAG):
    DO TRANSACTION:
        GET CURRENT SQ EXCLUSIVE-LOCK.
        DELETE SUMTIDDAG.
    END.
    GET NEXT SQ NO-LOCK.
END.
FOR EACH SUMTID:
   DELETE SUMTID.
END.
FOR EACH SUMEJLON:
   DELETE SUMEJLON.
END.
DEFINE BUFFER trabuff FOR SUMTRAKT.
FIND FIRST trabuff WHERE trabuff.VECKOKORD = "W20010308" NO-LOCK.
IF AVAILABLE trabuff THEN DO:
   FIND FIRST SUMTRAKT WHERE 
   SUMTRAKT.PERSONALKOD = trabuff.PERSONALKOD AND     
   SUMTRAKT.AONR = trabuff.AONR AND
   SUMTRAKT.DELNR = trabuff.DELNR AND
   SUMTRAKT.DATUM = trabuff.DATUM AND
   SUMTRAKT.VECKOKORD = trabuff.VECKOKORD AND
   SUMTRAKT.TRAKTKOD = trabuff.TRAKTKOD AND
   SUMTRAKT.TRAKTANTAL = trabuff.TRAKTANTAL AND
   RECID(SUMTRAKT) NE RECID(trabuff)
   NO-LOCK NO-ERROR.
   IF AVAILABLE SUMTRAKT THEN DO TRANSACTION:      
      FIND CURRENT SUMTRAKT EXCLUSIVE-LOCK NO-ERROR.
      DELETE SUMTRAKT.      
   END.
END.
REPEAT:
   FIND NEXT trabuff WHERE trabuff.VECKOKORD = "W20010308" NO-LOCK.
   IF AVAILABLE trabuff THEN DO:
      FIND FIRST SUMTRAKT WHERE 
      SUMTRAKT.PERSONALKOD = trabuff.PERSONALKOD AND     
      SUMTRAKT.AONR = trabuff.AONR AND
      SUMTRAKT.DELNR = trabuff.DELNR AND
      SUMTRAKT.DATUM = trabuff.DATUM AND
      SUMTRAKT.VECKOKORD = trabuff.VECKOKORD AND
      SUMTRAKT.TRAKTKOD = trabuff.TRAKTKOD AND
      SUMTRAKT.TRAKTANTAL = trabuff.TRAKTANTAL AND
      RECID(SUMTRAKT) NE RECID(trabuff)
      NO-LOCK NO-ERROR.
      IF AVAILABLE SUMTRAKT THEN DO TRANSACTION:      
         FIND CURRENT SUMTRAKT EXCLUSIVE-LOCK NO-ERROR.
         DELETE SUMTRAKT.      
      END.
   END.
   ELSE LEAVE.
END.
DEFINE BUFFER lonbuff FOR SUMLON.
FIND FIRST lonbuff WHERE lonbuff.VECKOKORD = "W20010308" NO-LOCK.
IF AVAILABLE lonbuff THEN DO:
   FIND FIRST SUMLON WHERE SUMLON.PERSONALKOD = lonbuff.PERSONALKOD AND     
   SUMLON.AONR = lonbuff.AONR AND
   SUMLON.DELNR = lonbuff.DELNR AND
   SUMLON.DATUM = lonbuff.DATUM AND
   SUMLON.VECKOKORD = lonbuff.VECKOKORD AND
   SUMLON.LONTILLAGG = lonbuff.LONTILLAGG AND
   SUMLON.LONTILLANTAL = lonbuff.LONTILLANTAL AND
   RECID(SUMLON) NE RECID(lonbuff)
   NO-LOCK NO-ERROR.
   IF AVAILABLE SUMLON THEN DO TRANSACTION:      
      FIND CURRENT SUMLON EXCLUSIVE-LOCK NO-ERROR.
      DELETE SUMLON.      
   END.
END.
REPEAT:
   FIND NEXT lonbuff WHERE lonbuff.VECKOKORD = "W20010308" NO-LOCK.
   IF AVAILABLE lonbuff THEN DO:
      FIND FIRST SUMLON WHERE SUMLON.PERSONALKOD = lonbuff.PERSONALKOD AND     
      SUMLON.AONR = lonbuff.AONR AND
      SUMLON.DELNR = lonbuff.DELNR AND
      SUMLON.DATUM = lonbuff.DATUM AND
      SUMLON.VECKOKORD = lonbuff.VECKOKORD AND
      SUMLON.LONTILLAGG = lonbuff.LONTILLAGG AND
      SUMLON.LONTILLANTAL = lonbuff.LONTILLANTAL AND
      RECID(SUMLON) NE RECID(lonbuff)
      NO-LOCK NO-ERROR.
      IF AVAILABLE SUMLON THEN DO TRANSACTION:      
         FIND CURRENT SUMLON EXCLUSIVE-LOCK NO-ERROR.
         DELETE SUMLON.      
      END.
   END.
   ELSE LEAVE.
END.
