DEFINE VARIABLE vem AS CHARACTER NO-UNDO.
DEFINE VARIABLE orgtabh AS HANDLE NO-UNDO.
CREATE BUFFER orgtabh FOR TABLE "PERSONALTAB".
vem = "eb". 
FIND FIRST PERSONALTAB WHERE personalkod = vem EXCLUSIVE-LOCK NO-ERROR. 
orgtabh:FIND-FIRST("WHERE  personalkod = " + quoter(vem), EXCLUSIVE-LOCK, NO-WAIT) NO-ERROR.
IF  orgtabh:LOCKED THEN DO:
   MESSAGE "låst"
   VIEW-AS ALERT-BOX.
END.
if locked(PERSONALTAB ) then MESSAGE "p låst"
   VIEW-AS ALERT-BOX.
   
   
orgtabh:BUFFER-FIELD("fornamn"):BUFFER-VALUE = orgtabh:BUFFER-FIELD("fornamn"):BUFFER-VALUE + "lås".
PERSONALTAB.EFTERNAMN = PERSONALTAB.EFTERNAMN + "p-lås".
MESSAGE PERSONALTAB.FORNAMN PERSONALTAB.EFTERNAMN
VIEW-AS ALERT-BOX.   


MESSAGE orgtabh:BUFFER-FIELD("fornamn"):BUFFER-VALUE  orgtabh:BUFFER-FIELD("EFTERNAMN"):BUFFER-VALUE 
VIEW-AS ALERT-BOX. 
