DEFINE BUFFER A FOR LEVTRP.
   DEFINE BUFFER B FOR LEVTRP.
      OUTPUT TO c:\kolllevtrpv.txt APPEND.
      DISP TODAY TIME.

   FOR EACH LEVTRP WHERE DATUM GE 01/01/2008 AND LEVTRP.BERNR > 0 AND LEVTRP.LEVKOD NE "0" NO-LOCK BY DATUM:
   

      FIND FIRST A WHERE A.OMRADE = LEVTRP.OMRADE  AND A.BERNR = LEVTRP.BERNR AND RECID(A) NE RECID(LEVTRP) 
      AND LEVTRP.BERBESTNR = A.BERBESTNR AND A.LEVKOD NE "0"  NO-LOCK NO-ERROR.
      IF AVAILABLE A THEN DO:
         DISP LEVTRP.BERNR LEVTRP.OMRADE LEVTRP.BESTNR LEVTRP.BERBESTNR LEVTRP.DATUM LEVTRP.LEVKOD  WITH FRAME CC .
            DISP A.BERNR A.OMRADE A.BESTNR A.BERBESTNR  A.DATUM A.LEVKOD WITH FRAME DD.
         /*FIND FIRST B WHERE B.OMRADE = A.OMRADE  AND B.BERNR = A.BERNR AND RECID(B) NE RECID(A ) 
         AND B.BESTALLD NE A.BESTALLD AND B.LEVKOD = A.LEVKOD AND B.BESTNR = A.BESTNR NO-LOCK NO-ERROR.
         IF NOT AVAILABLE B THEN DO:

            /*DISP BESTSTAT.BERNR BESTSTAT.OMRADE BESTSTAT.BESTNR BESTSTAT.BESTALLD BESTSTAT.DATUM BESTSTAT.ANVANDARE.*/
            DISP LEVTRP EXCEPT L1 WITH FRAME CC .
            DISP A  EXCEPT L1 WITH FRAME DD.
         END.*/
      END.
   
END
