MESSAGE "0".

open query lq FOR EACH LONTILL.
DO TRANSACTION:
   GET FIRST lq EXCLUSIVE-LOCK.
   IF AVAILABLE LONTILL THEN DO:
      ASSIGN LONTILL.VILART = LONTILL.LONTILLAGG.
      LONTILL.VALBAR = true.
   END.     
END.
REPEAT:
   GET NEXT lq EXCLUSIVE-LOCK.
   IF AVAILABLE LONTILL THEN DO:
      ASSIGN LONTILL.VILART = LONTILL.LONTILLAGG.
      LONTILL.VALBAR = true.
   END.
   ELSE LEAVE.
END.
close query lq.
MESSAGE "1".
open query tq FOR EACH TRAKTATAB.
DO TRANSACTION:
   GET FIRST tq EXCLUSIVE-LOCK.
   IF AVAILABLE TRAKTATAB THEN DO:
      ASSIGN TRAKTATAB.VILART = TRAKTATAB.TRAKTKOD.
      TRAKTATAB.VALBAR = true.
   END.     
END.
REPEAT:
   GET NEXT tq EXCLUSIVE-LOCK.
   IF AVAILABLE TRAKTATAB THEN DO:
      ASSIGN TRAKTATAB.VILART = TRAKTATAB.TRAKTKOD.
      TRAKTATAB.VALBAR = true.
   END.
   ELSE LEAVE.
END.
close query tq.

MESSAGE "2".
open query bq FOR EACH BERKOD.
DO TRANSACTION:
   GET FIRST bq EXCLUSIVE-LOCK.
   IF AVAILABLE BERKOD THEN DO:
      ASSIGN BERKOD.VILART = BERKOD.BEREDSKAP.
      BERKOD.VALBAR = true.
   END.     
END.
REPEAT:
   GET NEXT bq EXCLUSIVE-LOCK.
   IF AVAILABLE BERKOD THEN DO:
      ASSIGN BERKOD.VILART = BERKOD.BEREDSKAP.
      BERKOD.VALBAR = true.
   END.
   ELSE LEAVE.
END.
close query bq.

MESSAGE "3".
open query oq FOR EACH OVERKOD.
DO TRANSACTION:
   GET FIRST oq EXCLUSIVE-LOCK.
   IF AVAILABLE OVERKOD THEN DO:
      ASSIGN OVERKOD.VILART = OVERKOD.OVERTIDTILL.
      OVERKOD.VALBAR = true.
   END.     
END.
REPEAT:
   GET NEXT oq EXCLUSIVE-LOCK.
   IF AVAILABLE OVERKOD THEN DO:
      ASSIGN OVERKOD.VILART = OVERKOD.OVERTIDTILL.
      OVERKOD.VALBAR = true.
   END.
   ELSE LEAVE.
END.
close query oq.


MESSAGE "4".
FOR EACH BESTTAB:
   ASSIGN BESTTAB.VIBESTID = BESTTAB.VIBESTID.
END.      
MESSAGE "5".
 
