/*DEFINE TEMP-TABLE A NO-UNDO
   FIELD DD AS CHARACTER.
EMPTY TEMP-TABLE A NO-ERROR. */
FOR EACH KONSTVAL WHERE KONSTVAL.KONSKOD = 12 AND KONSTVAL.BB = "KABLAR" NO-LOCK:
 
    FIND FIRST KONSTRUKTION WHERE KONSTRUKTION.KONSKOD = 14 AND
    KONSTRUKTION.KTYPKOD =  LEFT-TRIM(KONSTVAL.KVALKOD) NO-LOCK NO-ERROR.
    IF NOT  AVAILABLE KONSTRUKTION THEN DO:       
       /*FIND FIRST A WHERE A.DD = KONSTVAL.KVALKOD NO-ERROR.
       IF NOT AVAILABLE A THEN DO:
          CREATE A.
          ASSIGN A.DD = KONSTVAL.KVALKOD.
       END.*/
       DISP KONSTVAL.KVALKOD.
       
    END.
END.
/*OUTPUT TO F:\ELPOOL\ELPLO\HSP.TXT.
FOR EACH A NO-LOCK:
   DISP A.
END.*/
