/*XMASKTES.P*/
DEFINE VARIABLE datumvar AS CHARACTER FORMAT "X(20)" NO-UNDO.
DEFINE VARIABLE starttid AS INTEGER NO-UNDO.
DEFINE VARIABLE sluttid AS INTEGER NO-UNDO.
DEFINE VARIABLE tid AS INTEGER NO-UNDO.
DEFINE VARIABLE raknare AS DECIMAL NO-UNDO.
raknare = 0.
ASSIGN
datumvar = STRING(TODAY) + " " + STRING(TIME,"HH:MM:SS") 
starttid = TIME.
OPEN QUERY stq FOR EACH SUMTIDDAG WHERE YEAR(SUMTIDDAG.DATUM) = 1998 AND MONTH(SUMTIDDAG.DATUM) = 12 NO-LOCK.
GET FIRST stq NO-LOCK.
DO WHILE AVAILABLE(SUMTIDDAG):
   raknare = raknare + SUMTIDDAG.TIMMAR.
   GET NEXT stq NO-LOCK.
END.
sluttid = TIME.
tid = sluttid - starttid.
OUTPUT TO /eko1/guru/masktest.txt APPEND.
/*OUTPUT TO A:\masktest.txt APPEND.*/
PUT datumvar starttid sluttid tid " " STRING(TIME,"HH:MM:SS") raknare SKIP.
OUTPUT CLOSE.  
