DEFINE QUERY menyq FOR XGURU.

OPEN QUERY menyq FOR EACH XGURU WHERE XGURU.MENYVART = "GURU" AND 
XGURU.MENY = "Materialhant." NO-LOCK.
DO TRANSACTION:
   GET FIRST menyq EXCLUSIVE-LOCK.
END.
DO WHILE AVAILABLE(XGURU):
   DO TRANSACTION:
      XGURU.MENY = "Materielhant.".
      GET NEXT menyq EXCLUSIVE-LOCK.  
   END.
END.
CLOSE QUERY menyq.
DEFINE QUERY kalkq FOR KALKYL.

OPEN QUERY kalkq FOR EACH KALKYL WHERE KALKYL.BEFATTNING = "MATERIAL" NO-LOCK. 
DO TRANSACTION:
   GET FIRST kalkq EXCLUSIVE-LOCK.
END.
DO WHILE AVAILABLE(KALKYL):
   DO TRANSACTION:
      KALKYL.BEFATTNING = "MATERIEL".
      GET NEXT kalkq EXCLUSIVE-LOCK.  
   END.
END.
CLOSE QUERY kalkq.
RUN XBEHORIG.P.