/*XMLIN.P.*/
DEFINE VARIABLE hDoc AS HANDLE.
DEFINE VARIABLE hRoot AS HANDLE.
DEFINE VARIABLE hTable AS HANDLE.
DEFINE VARIABLE hField AS HANDLE.
DEFINE VARIABLE hText AS HANDLE.
DEFINE VARIABLE hBuf AS HANDLE.
DEFINE VARIABLE hDBFld AS HANDLE.
DEFINE VARIABLE i AS INTEGER.
DEFINE VARIABLE j AS INTEGER.

DEFINE TEMP-TABLE ao_temp
  FIELD ANLNR       LIKE AONRTAB.ANLNR 
  FIELD ANVANDARE   LIKE AONRTAB.ANVANDARE 
  FIELD AONR        LIKE AONRTAB.AONR 
  FIELD AONRAVDATUM LIKE AONRTAB.AONRAVDATUM 
  FIELD ARBANSVARIG LIKE AONRTAB.ARBANSVARIG 
  FIELD ARBARTKOD   LIKE AONRTAB.ARBARTKOD 
  FIELD ARBBESKED   LIKE AONRTAB.ARBBESKED 
  FIELD ARTAL       LIKE AONRTAB.ARTAL 
  FIELD AUTOREG     LIKE AONRTAB.AUTOREG 
  FIELD BEREDARE    LIKE AONRTAB.BEREDARE 
  FIELD BESTID      LIKE AONRTAB.BESTID 
  FIELD BETNR       LIKE AONRTAB.BETNR 
  FIELD DELNR       LIKE AONRTAB.DELNR 
  FIELD ELVOMRKOD   LIKE AONRTAB.ELVOMRKOD 
  FIELD FAKTNR      LIKE AONRTAB.FAKTNR 
  FIELD FAKTTYP     LIKE AONRTAB.FAKTTYP 
  FIELD FASTAAONR   LIKE AONRTAB.FASTAAONR 
  FIELD FASTKALK    LIKE AONRTAB.FASTKALK 
  FIELD KALKNR      LIKE AONRTAB.KALKNR 
  FIELD OMRADE      LIKE AONRTAB.OMRADE 
  FIELD ORT         LIKE AONRTAB.ORT 
  FIELD PKOD        LIKE AONRTAB.PKOD 
  FIELD PLANNR      LIKE AONRTAB.PLANNR 
  FIELD PRISTYP     LIKE AONRTAB.PRISTYP 
  FIELD SLUTDAG     LIKE AONRTAB.SLUTDAG 
  FIELD SLUTVNR     LIKE AONRTAB.SLUTVNR 
  FIELD STARTDAG    LIKE AONRTAB.STARTDAG 
  FIELD STARTDATUM  LIKE AONRTAB.STARTDATUM 
  FIELD STARTVNR    LIKE AONRTAB.STARTVNR 
  FIELD TRAKTAMENTE LIKE AONRTAB.TRAKTAMENTE 
  FIELD UTFARDAT    LIKE AONRTAB.UTFARDAT 
  FIELD UTRYCKNING  LIKE AONRTAB.UTRYCKNING.
DEFINE TEMP-TABLE ptemp NO-UNDO LIKE PERSONALTAB.
CREATE X-DOCUMENT hDoc.
CREATE X-NODEREF hRoot.
CREATE X-NODEREF hTable.
CREATE X-NODEREF hField.
CREATE X-NODEREF hText.



hDoc:LOAD("file", "c:\protemp9\test.xml", FALSE).
hDoc:GET-DOCUMENT-ELEMENT(hRoot).

/*READ EACH AONR FROM THE ROOT*/
REPEAT i = 1 TO hRoot:NUM-CHILDREN:
   hRoot:GET-CHILD(hTable,i).
   IF hTable:NAME = "Projekt" THEN DO:
      hBUf = BUFFER ao_temp:HANDLE.
      CREATE ao_temp.
      /*GET FIELDS GIVEN AS ATTRIBUTES*/
      ao_temp.AONR = hTable:GET-ATTRIBUTE("Projnr").
      ao_temp.ORT = hTable:GET-ATTRIBUTE("Benämning").
   /*GET THE REMAINING FIELDS GIVEN AS ELEMENTS WITH TEXT*/
   END.
   ELSE DO:
      hBUf = BUFFER ptemp:HANDLE.
      CREATE ptemp.
      /*GET FIELDS GIVEN AS ATTRIBUTES*/
      ptemp.PERSONALKOD = hTable:GET-ATTRIBUTE("P-kod").      
   /*GET THE REMAINING FIELDS GIVEN AS ELEMENTS WITH TEXT*/

   END.
   REPEAT j = 1 TO hTable:NUM-CHILDREN:
      hTable:GET-CHILD(hField,j).
      IF hField:NUM-CHILDREN < 1 THEN NEXT.
      /*SKIP ANY NULL VALUE*/
      hDBFld = hBuf:BUFFER-FIELD(hField:NAME).
      hField:GET-CHILD(hText,1).
      /*GET THE TEXT VALUE OF THE FIELD*/
      hDBFld:BUFFER-VALUE = hText:NODE-VALUE.      
   END.
END.

DELETE OBJECT hDoc.
DELETE OBJECT hRoot.
DELETE OBJECT hTable.
DELETE OBJECT hField.
DELETE OBJECT hText.

FOR EACH ao_temp:
   DISPLAY ao_temp.AONR.
END.
FOR EACH ptemp:
   DISPLAY ptemp.PERSONALKOD.
END.
