/*
     Filename: XMLOUT.P
      Created: 2004.03.16 12:52ELPAO     
     Modified: 
*/

DEFINE VARIABLE hDoc AS HANDLE NO-UNDO.
DEFINE VARIABLE hRoot AS HANDLE NO-UNDO.
DEFINE VARIABLE hRow AS HANDLE NO-UNDO.
DEFINE VARIABLE hField AS HANDLE NO-UNDO.
DEFINE VARIABLE i AS INTEGER NO-UNDO.

CREATE X-DOCUMENT hDoc.
CREATE X-NODEREF hRoot.
CREATE X-NODEREF hRow.
CREATE X-NODEREF hField.

hDoc:CREATE-NODE(hRoot,"EBRPRIS","ELEMENT").
hDoc:APPEND-CHILD(hRoot).

FOR EACH EBRPRIS:
   hDoc:CREATE-NODE(hRow, "EBR", "ELEMENT").
   hRoot:APPEND-CHILD(hRow).
   hRow:SET-ATTRIBUTE("Årtal", STRING(ARTAL)).
   hDoc:CREATE-NODE(hField, "PRIS", "ELEMENT").
   hRow:APPEND-CHILD(hField).
   hField:SET-ATTRIBUTE("Mask1-Pris", STRING(MASK1)).
   hField:SET-ATTRIBUTE("Mask2-Pris", STRING(MASK2)).
   hField:SET-ATTRIBUTE("Mont-Pris", STRING(MONT)).
   hField:SET-ATTRIBUTE("Rörligt-Pris", STRING(RORLIG)).
END.
hDoc:SAVE("file","C:\protemp9\ebr.xml").

DELETE OBJECT hDoc.
DELETE OBJECT hRoot.
DELETE OBJECT hRow.
DELETE OBJECT hField.

