/*XMLUT.P*/
DEFINE VARIABLE hDoc AS HANDLE.
DEFINE VARIABLE hRoot AS HANDLE.
DEFINE VARIABLE hRow AS HANDLE.
DEFINE VARIABLE hField AS HANDLE.
DEFINE VARIABLE hText AS HANDLE.
DEFINE VARIABLE hBuf AS HANDLE.
DEFINE VARIABLE hDBFld AS HANDLE.
DEFINE VARIABLE antal AS INTEGER.

CREATE X-DOCUMENT hDoc.
CREATE X-NODEREF hRoot.
CREATE X-NODEREF hRow.
CREATE X-NODEREF hField.
CREATE X-NODEREF hText.

hBuf = BUFFER AONRTAB:HANDLE.

/*SET UP A ROOT NOD*/
hDoc:CREATE-NODE(hRoot,"Projektnummer","ELEMENT").
hDoc:APPEND-CHILD(hRoot).

FOR EACH AONRTAB WHERE AONRTAB.OMRADE = "2" AND 
AONRTAB.AONRAVDATUM = 01/01/91 NO-LOCK:
   hDoc:CREATE-NODE(hRow, "Projekt", "ELEMENT"). /*CREATE A ROW NODE*/
   hRoot:APPEND-CHILD(hRow).                   /*PUT THE ROW IN THE TREE*/
   hRow:SET-ATTRIBUTE("Projnr", AONRTAB.AONR).
   hRow:SET-ATTRIBUTE("Benämning", AONRTAB.ORT).
   /*ADD THE OTHER FIELDS AS TAGS IN THE XML*/
   REPEAT antal = 1 TO hBuf:NUM-FIELDS:
      hDBfld = hBuf:BUFFER-FIELD(antal).
      IF hDBFld:NAME = "AONR" OR hDBFld:NAME = "ORT" OR hDBFld:NAME = "ANM" OR hDBFld:NAME = "ARBUPPG" THEN NEXT.
      /*CREATE A TAG WITH THE FIELD NAME*/
      hDoc:CREATE-NODE(hField, hDBFld:NAME, "ELEMENT").
      
      /*PUT THE NEW FIELD AS NEXT CHILD OF ROW*/
      hRow:APPEND-CHILD(hField).
     
      /*ADD A NODE TO HOLD FIELD VALUE*/
      hDoc:CREATE-NODE(hText, "", "TEXT").
      
      /*ATTACH THE TEXT TO THE FIELD*/
      hField:APPEND-CHILD(hText).
      
      IF STRING(HDBFld:BUFFER-VALUE) NE ? THEN hText:NODE-VALUE = STRING(HDBFld:BUFFER-VALUE).
      
   END.
END.

hBuf = BUFFER PERSONALTAB:HANDLE.


FOR EACH PERSONALTAB NO-LOCK:
   hDoc:CREATE-NODE(hRow, "Personal", "ELEMENT"). /*CREATE A ROW NODE*/
   hRoot:APPEND-CHILD(hRow).                   /*PUT THE ROW IN THE TREE*/
   hRow:SET-ATTRIBUTE("P-kod", PERSONALTAB.PERSONALKOD).
   /*ADD THE OTHER FIELDS AS TAGS IN THE XML*/
   REPEAT antal = 1 TO hBuf:NUM-FIELDS:
      hDBfld = hBuf:BUFFER-FIELD(antal).
      IF hDBFld:NAME = "PERSONALKOD" THEN NEXT.
      /*CREATE A TAG WITH THE FIELD NAME*/
      hDoc:CREATE-NODE(hField, hDBFld:NAME, "ELEMENT").
      /*PUT THE NEW FIELD AS NEXT CHILD OF ROW*/
      hRow:APPEND-CHILD(hField).
      /*ADD A NODE TO HOLD FIELD VALUE*/
      hDoc:CREATE-NODE(hText, "", "TEXT").
      /*ATTACH THE TEXT TO THE FIELD*/
      hField:APPEND-CHILD(hText).
      IF STRING(HDBFld:BUFFER-VALUE) NE ? THEN
      hText:NODE-VALUE = STRING(HDBFld:BUFFER-VALUE).
   END.
END.

/*WRITE THE XML NOFDE TREE TO AN XML FILE*/
hDoc:SAVE("file","C:\PROTEMP9\test2.xml").

DELETE OBJECT hDoc.
DELETE OBJECT hRoot.
DELETE OBJECT hRow.
DELETE OBJECT hField.
DELETE OBJECT hText.
