 /*NORDVE2.P*/
 /*TEMP-TABLES*/
/*SUMMERAR VECKANS KORNING + foregaende korningar i pasumma.d    */
DEFINE VARIABLE personal LIKE PERSONALTAB.PERSONALKOD NO-UNDO.      /*LÖN*/
DEFINE VARIABLE losen AS CHARACTER FORMAT "X(6)" NO-UNDO.
DEFINE VARIABLE persnr LIKE PERSONALTAB.PERSONNUMMER NO-UNDO.     /*LÖN*/
DEFINE VARIABLE pnummer LIKE PERSONALTAB.PERSONNUMMER NO-UNDO.     /*LÖN*/
DEFINE VARIABLE sor LIKE LONTILL.ENHET NO-UNDO.    /*LÖN*/
DEFINE VARIABLE lon LIKE TIDREGITAB.LONTILLAGG NO-UNDO.     /*LÖN*/
DEFINE VARIABLE lone LIKE TIDREGITAB.LONTILLAGG NO-UNDO.     /*LÖN*/
DEFINE VARIABLE antal LIKE TIDREGITAB.LONTILLANTAL NO-UNDO.   /*LÖN*/
DEFINE VARIABLE persnummer AS CHARACTER FORMAT "X(10)" NO-UNDO.      /*LÖN*/
DEFINE VARIABLE datum AS CHARACTER FORMAT "X(6)" NO-UNDO.      /*LÖN*/
DEFINE VARIABLE regdat AS DATE NO-UNDO.      /*LÖN*/
DEFINE VARIABLE regdat1 AS DATE NO-UNDO.      /*LÖN*/
DEFINE SHARED VARIABLE sekunder AS INTEGER FORMAT "-9999999" NO-UNDO.
DEFINE SHARED VARIABLE nytid AS DECIMAL FORMAT "99.99" NO-UNDO.
DEFINE VARIABLE seku AS INTEGER FORMAT "-9999999" NO-UNDO.
DEFINE VARIABLE man AS INTEGER FORMAT "99" NO-UNDO.
DEFINE VARIABLE manad AS INTEGER FORMAT "99" NO-UNDO.
DEFINE VARIABLE beravt LIKE PERSONALTAB.BEREDSKAPSAVTAL NO-UNDO.
DEFINE VARIABLE svar AS LOGICAL FORMAT "JA/NEJ" INITIAL FALSE NO-UNDO.
DEFINE VARIABLE rec AS RECID NO-UNDO.
DEFINE SHARED TEMP-TABLE pa90fil
   FIELD PPERSONNUMMER LIKE PERSONALTAB.PERSONNUMMER
   FIELD PLONTILLAGG LIKE TIDREGITAB.LONTILLAGG
   FIELD PLONTILLANTAL LIKE TIDREGITAB.LONTILLANTAL
   FIELD POVERTIDTILL LIKE TIDREGITAB.OVERTIDTILL
   FIELD POVERANTAL LIKE TIDREGITAB.OVERANTAL
   FIELD PTRAKTKOD LIKE TIDREGITAB.TRAKTKOD
   FIELD PTRAKTANTAL LIKE TIDREGITAB.TRAKTANTAL
   FIELD PBEREDSKAP LIKE TIDREGITAB.BEREDSKAP
   FIELD PBERANTAL LIKE TIDREGITAB.BERANTAL
   FIELD PDATUM LIKE TIDREGITAB.DATUM
   FIELD PVECKONUMMER LIKE TIDREGITAB.VECKONUMMER
   FIELD PSORT AS CHARACTER FORMAT "XX"
   FIELD PPAR8 AS DECIMAL FORMAT "-99.99"
   FIELD PANSTNR LIKE PERSONALTAB.ANSTNR
   INDEX PPERSONNUMMER IS PRIMARY PPERSONNUMMER ASCENDING.
  /* FIELD PVECKONUMMER LIKE TIDREGITAB.VECKONUMMER
   FIELD PPAR8 AS DECIMAL FORMAT "-99.99".*/
DEFINE TEMP-TABLE pa90sum
   FIELD PPERSONNUMMER LIKE PERSONALTAB.PERSONNUMMER
   FIELD PLONTILLAGG LIKE TIDREGITAB.LONTILLAGG
   FIELD PLONTILLANTAL LIKE TIDREGITAB.LONTILLANTAL
   FIELD POVERTIDTILL LIKE TIDREGITAB.OVERTIDTILL
   FIELD POVERANTAL LIKE TIDREGITAB.OVERANTAL
   FIELD PTRAKTKOD LIKE TIDREGITAB.TRAKTKOD
   FIELD PTRAKTANTAL LIKE TIDREGITAB.TRAKTANTAL
   FIELD PBEREDSKAP LIKE TIDREGITAB.BEREDSKAP
   FIELD PBERANTAL AS DECIMAL FORMAT "999.99"
   FIELD PDATUM LIKE TIDREGITAB.DATUM
   FIELD PVECKONUMMER LIKE TIDREGITAB.VECKONUMMER
   FIELD PSORT AS CHARACTER FORMAT "XX"
   FIELD PPAR8 AS DECIMAL
   FIELD PANSTNR LIKE PERSONALTAB.ANSTNR.
  /* FIELD PVECKONUMMER LIKE TIDREGITAB.VECKONUMMER
   FIELD PPAR8 AS DECIMAL.*/
   DEFINE VARIABLE ST AS INTEGER.
/* filen pasumma.d sparas undan i pakopsum.d innan ny pasumma skapas */
IF OPSYS = "MSDOS" OR OPSYS = "WIN32" THEN DO:
 
     INPUT FROM P:\progress\pasumma.d NO-ECHO.
        
END.
REPEAT TRANSACTION:
  CREATE pa90fil.
  ASSIGN.
  IMPORT pa90fil.
END.
lon="".
antal = 0.
persnr = "".
manad = 0.
regdat1 = 01/01/93.
FOR EACH pa90fil BY pa90fil.PPERSONNUMMER BY pa90fil.PLONTILLAGG
BY pa90fil.PDATUM:
  rec = RECID(pa90fil).
  man = MONTH(pa90fil.PDATUM).
  pnummer = pa90fil.PPERSONNUMMER.
  regdat = pa90fil.PDATUM.
  IF pa90fil.PLONTILLAGG = "" THEN NEXT.
  lone = pa90fil.PLONTILLAGG.
  IF lon = lone AND persnr = pnummer AND manad = man THEN DO:
    FIND FIRST LONTILL WHERE LONTILL.LONTILLAGG = lon NO-LOCK NO-ERROR.
    IF NOT AVAILABLE LONTILL THEN DO:
	antal = antal + pa90fil.PLONTILLANTAL.
    END.
    ELSE DO:
      sor = LONTILL.ENHET.
      IF sor = "TI" THEN DO:
	nytid = antal.
	RUN TIMSEK.P.
	seku = sekunder.
	nytid = pa90fil.PLONTILLANTAL.
	RUN TIMSEK.P.
	sekunder = sekunder + seku.
	RUN SEKTIM.P.
	antal = nytid.
      END.
      ELSE DO:
	antal = antal + pa90fil.PLONTILLANTAL.
      END.
    END.
  END.
  ELSE DO:
    IF antal NE 0 THEN DO TRANSACTION:
      CREATE pa90sum.
      ASSIGN pa90sum.PPERSONNUMMER = persnr pa90sum.PDATUM = regdat1
      pa90sum.PLONTILLAGG = lon pa90sum.PLONTILLANTAL = antal. 
      FIND FIRST LONTILL WHERE LONTILL.LONTILLAGG = lon NO-LOCK NO-ERROR.
      IF NOT AVAILABLE LONTILL THEN DO:
         personal = personal.
      END.
      ELSE IF LONTILL.ENHET = "TI" THEN DO:
	ASSIGN pa90sum.PSORT = "TI".
      END.
    END.
    manad = man.
    antal = pa90fil.PLONTILLANTAL.
    lon = lone.
    persnr = pnummer.
    regdat1 =regdat.
  END.
END.
IF antal NE 0 THEN DO TRANSACTION:
    CREATE pa90sum.
    ASSIGN pa90sum.PPERSONNUMMER = persnr pa90sum.PDATUM = regdat1
    pa90sum.PLONTILLAGG = lon pa90sum.PLONTILLANTAL = antal.
    FIND FIRST LONTILL WHERE LONTILL.LONTILLAGG = lon NO-LOCK NO-ERROR.
    IF NOT AVAILABLE LONTILL THEN DO:
      personal = personal.
    END.
    ELSE IF LONTILL.ENHET = "TI" THEN DO:
      ASSIGN pa90sum.PSORT = "TI".
    END.
END.
lon="".
antal = 0.
persnr = "".
manad = 0.
regdat1 = 01/01/93.
FOR EACH pa90fil BY pa90fil.PPERSONNUMMER BY pa90fil.POVERTIDTILL
BY pa90fil.PDATUM:
  rec = RECID(pa90fil).
  man = MONTH(pa90fil.PDATUM).
  pnummer = pa90fil.PPERSONNUMMER.
  regdat =pa90fil.PDATUM.
  IF pa90fil.POVERTIDTILL = "" THEN NEXT.
  lone = pa90fil.POVERTIDTILL.
  IF lon = lone AND persnr = pnummer AND manad = man THEN DO:
      nytid = antal.
      RUN TIMSEK.P.
      seku = sekunder.
      nytid = pa90fil.POVERANTAL.
      RUN TIMSEK.P.
      sekunder = sekunder + seku.
      RUN SEKTIM.P.
      antal = nytid.
  END.
  ELSE DO:
    IF antal > 0 THEN DO TRANSACTION:
      CREATE pa90sum.
      ASSIGN pa90sum.PPERSONNUMMER = persnr pa90sum.PDATUM = regdat1
      pa90sum.POVERTIDTILL = lon pa90sum.POVERANTAL = antal
      pa90sum.PSORT = "TI".
    END.
    manad = man.
    antal = pa90fil.POVERANTAL.
    lon = lone.
    persnr = pnummer.
    regdat1 =regdat.
  END.
END.
IF antal > 0 THEN DO TRANSACTION:
    CREATE pa90sum.
    ASSIGN pa90sum.PPERSONNUMMER = persnr pa90sum.PDATUM = regdat1
    pa90sum.POVERTIDTILL = lon pa90sum.POVERANTAL = antal
    pa90sum.PSORT = "TI".
END.
lon="".
antal = 0.
persnr = "".
regdat1 = 01/01/93.
manad = 0.
FOR EACH pa90fil BY pa90fil.PPERSONNUMMER BY pa90fil.PTRAKTKOD
BY pa90fil.PDATUM:
  rec = RECID(pa90fil).
  man = MONTH(pa90fil.PDATUM).
  pnummer = pa90fil.PPERSONNUMMER.
  regdat = pa90fil.PDATUM.
  IF pa90fil.PTRAKTKOD = "" THEN NEXT.
  lone = pa90fil.PTRAKTKOD.
  IF lon = lone AND persnr = pnummer AND manad = man THEN DO:
    antal = antal + pa90fil.PTRAKTANTAL.
  END.
  ELSE DO:
    IF antal > 0 THEN DO TRANSACTION:
      CREATE pa90sum.
      ASSIGN pa90sum.PPERSONNUMMER = persnr pa90sum.PDATUM = regdat1
      pa90sum.PTRAKTKOD = lon pa90sum.PTRAKTANTAL = antal.
    END.
    manad = man.
    antal = pa90fil.PTRAKTANTAL.
    lon = lone.
    regdat1 = regdat.
    persnr = pnummer.
  END.
END.
IF antal > 0 THEN DO TRANSACTION:
     CREATE pa90sum.
     ASSIGN pa90sum.PPERSONNUMMER = persnr pa90sum.PDATUM = regdat1
     pa90sum.PTRAKTKOD = lon pa90sum.PTRAKTANTAL = antal.
END.
lon="".
antal = 0.
persnr = "".
regdat1 = 01/01/93.
manad = 0.
FOR EACH pa90fil BY pa90fil.PPERSONNUMMER BY pa90fil.PBEREDSKAP
BY pa90fil.PDATUM:
  rec = RECID(pa90fil).
  man = MONTH(pa90fil.PDATUM).
  pnummer = pa90fil.PPERSONNUMMER.
  regdat = pa90fil.PDATUM.
  lone = pa90fil.PBEREDSKAP.
  IF pa90fil.PBEREDSKAP = "" THEN NEXT.
  FIND FIRST PERSONALTAB WHERE PERSONALTAB.PERSONNUMMER = pnummer
  USE-INDEX PERSONALKOD NO-LOCK NO-ERROR.
  beravt = PERSONALTAB.BEREDSKAPSAVTAL.
  FIND FIRST BEREDSKAPTAB WHERE BEREDSKAPTAB.BEREDSKAPSAVTAL = beravt
  USE-INDEX BERED NO-LOCK NO-ERROR.
  IF lon = lone AND persnr = pnummer AND manad = man THEN DO:
    IF BEREDSKAPTAB.BERANTAL = 0 THEN DO:
      nytid = antal.
      RUN TIMSEK.P.
      seku = sekunder.
      nytid = pa90fil.PBERANTAL.
      RUN TIMSEK.P.
      sekunder = sekunder + seku.
      RUN SEKTIM.P.
      antal = nytid.
    END.
    ELSE IF BEREDSKAPTAB.BERANTAL > 0 THEN DO:
      antal = antal + pa90fil.PBERANTAL.
    END.
  END.
  ELSE DO:
    IF antal > 0 THEN DO TRANSACTION:
      CREATE pa90sum.
      ASSIGN pa90sum.PPERSONNUMMER = persnr pa90sum.PDATUM = regdat1
      pa90sum.PBEREDSKAP = lon pa90sum.PBERANTAL = antal.
      IF BEREDSKAPTAB.BERANTAL = 0 THEN DO:
	ASSIGN pa90sum.PSORT = "TI".
      END.
    END.
    manad = man.
    antal = pa90fil.PBERANTAL.
    lon = lone.
    persnr = pnummer.
    regdat1 = regdat.
  END.
END.
IF antal > 0 THEN DO TRANSACTION:
    CREATE pa90sum.
    ASSIGN pa90sum.PPERSONNUMMER = persnr pa90sum.PDATUM = regdat1
    pa90sum.PBEREDSKAP = lon pa90sum.PBERANTAL = antal.
    IF BEREDSKAPTAB.BERANTAL = 0 THEN DO:
      ASSIGN pa90sum.PSORT = "TI".
    END.
END.
FOR EACH pa90fil:
  DELETE pa90fil.
END.

IF OPSYS = "MSDOS" OR OPSYS = "WIN32" THEN DO:
  OUTPUT TO P:\progress\pasumma.d.        
END.
FOR EACH pa90sum
BY pa90sum.PPERSONNUMMER BY pa90sum.PLONTILLAGG BY pa90sum.POVERTIDTILL
BY pa90sum.PTRAKTKOD BY pa90sum.PBEREDSKAP:
  EXPORT pa90sum.
END.
FOR EACH pa90sum:
  DELETE pa90sum.
END.
