OPEN QUERY AQ FOR EACH AONRTAB WHERE (AONRTAB.AONR BEGINS "100" OR
AONRTAB.AONR BEGINS "101" OR AONRTAB.AONR BEGINS "102" OR AONRTAB.AONR BEGINS "103" OR
AONRTAB.AONR BEGINS "104") AND 
AONRTAB.OMRADE = "" AND AONRTAB.AONRAVDATUM = 01/01/91 AND
AONRTAB.FASTAAONR = TRUE NO-LOCK.
DO TRANSACTION:
   GET FIRST AQ EXCLUSIVE-LOCK.
   RUN omr_UI.
END.   
REPEAT:
   DO TRANSACTION:
      GET NEXT AQ EXCLUSIVE-LOCK.
      IF AVAILABLE AONRTAB THEN RUN omr_UI.
      ELSE LEAVE.
   END.   
END.
PROCEDURE omr_UI:
   FIND FIRST AONRKONTKOD WHERE AONRKONTKOD.AONR = AONRTAB.AONR AND
   AONRKONTKOD.DELNR = AONRTAB.DELNR NO-LOCK NO-ERROR.
   IF AVAILABLE AONRKONTKOD THEN DO:
      FIND FIRST OMRADETAB WHERE OMRADETAB.ORGIDNUM = AONRKONTKOD.K1 NO-LOCK NO-ERROR.
      IF AVAILABLE OMRADETAB THEN DO:
         AONRTAB.OMRADE = OMRADETAB.OMRADE.
         IF AONRTAB.FAKTNR NE 0 THEN DO:
            FIND FIRST FAKTPLAN WHERE FAKTPLAN.FAKTNR = AONRTAB.FAKTNR EXCLUSIVE-LOCK NO-ERROR.
            IF AVAILABLE FAKTPLAN THEN DO:
               FAKTPLAN.OMRADE = OMRADETAB.OMRADE.            
               FOR EACH FAKTAONR WHERE FAKTAONR.FAKTNR = AONRTAB.FAKTNR EXCLUSIVE-LOCK:                 
                  FAKTAONR.OMRADE = OMRADETAB.OMRADE.            
               END.
            END.
         END.
      END.
   END.
END PROCEDURE.
