
DEF TEMP-TABLE PV
   FIELD ANSTNR AS CHARACTER
   FIELD OMRADE AS CHARACTER
   FIELD ENAMN AS CHARACTER
   FIELD NAMN AS CHARACTER.
  
INPUT FROM f:/elplo/es/omrade-anstnr2.txt NO-ECHO.

REPEAT TRANSACTION:
   CREATE PV.
   ASSIGN.
   IMPORT PV.
END.
/*FOR EACH PV:
    FIND FIRST OMRADETAB WHERE OMRADETAB.OMRADE = PV.OMRADE NO-LOCK NO-ERROR.
    IF NOT AVAILABLE OMRADETAB THEN DO: 
        DISPLAY PV.ANSTNR PV.OMRADE pv.ENAMN pv.NAMN.
    END.
END.*/

for each pv:
   
   DO TRANSACTION:
      FIND FIRST PERSONALTAB WHERE PERSONALTAB.ANSTNR = pv.ANSTNR EXCLUSIVE-LOCK NO-ERROR.
      IF AVAILABLE PERSONALTAB THEN DO:
        assign PERSONALTAB.omrade = PV.omrade.
    /*     DISPLAY PERSONALTAB.PERSONALKOD NO-LABEL PERSONALTAB.ANSTNR NO-LABEL pv.omrade NO-LABEL pv.NAMN pv.ENAMN PERSONALTAB.EFTERNAMN  .*/
      END.   
     /* IF NOT AVAILABLE PERSONALTAB THEN DO:
         DISPLAY PV.ANSTNR pv.omrade pv.ENAMN pv.NAMN.
      END.   */
   END.   
      
end.

 
      
   
   
