   
   /*xonekontrollkonstgrupp.p*/
 DEFINE TEMP-TABLE BERTRAFF NO-UNDO  
   FIELD AONR AS CHAR
   FIELD DELNR AS INTEGER
   FIELD ORT AS CHARACTER
   FIELD BEREDARE AS CHARACTER
   FIELD DATUM AS DATE
   FIELD BENAMNING AS CHARACTER
   FIELD KTYPKOD AS CHARACTER
   FIELD KONSKOD AS INTEGER  
    
   INDEX KONSKOD KONSKOD AONR DELNR.                            
DEFINE VARIABLE AOANT AS INTEGER NO-UNDO.
DEFINE VARIABLE EXANT AS INTEGER NO-UNDO.            





OPEN QUERY atidlq FOR EACH AONRTIDLAGE WHERE AONRTIDLAGE.IDTIDLAG = "AOUPPLAGT" AND AONRTIDLAGE.DATUM1 >= 01/01/2020  NO-LOCK, 
EACH AONRTAB WHERE   
AONRTAB.AONR = AONRTIDLAGE.AONR AND
AONRTAB.DELNR = AONRTIDLAGE.DELNR      NO-LOCK.
 GET FIRST atidlq NO-LOCK.
   DO WHILE AVAILABLE(AONRTAB):   
      FIND FIRST BEREDNING  WHERE BEREDNING.AONR = AONRTAB.AONR AND BEREDNING.DELNR = AONRTAB.DELNR   NO-LOCK NO-ERROR.  
      IF AVAILABLE BEREDNING  THEN DO:    
         FOR each BERVAL WHERE (BERVAL.KONSKOD = 6 OR BERVAL.KONSKOD = 44 OR BERVAL.KONSKOD = 45 OR BERVAL.KONSKOD = 46 OR BERVAL.KONSKOD = 47 OR
         BERVAL.KONSKOD = 48 OR BERVAL.KONSKOD = 49 OR BERVAL.KONSKOD = 50 )  NO-LOCK BY BERVAL.KONSKOD:
            FIND FIRST KONSTGRUPP  WHERE KONSTGRUPP.KONSKOD = BERVAL.KONSKOD   NO-LOCK NO-ERROR.
            CREATE BERTRAFF.
            ASSIGN
            BERTRAFF.AONR = AONRTAB.aonr
            BERTRAFF.DELNR  = AONRTAB.DELNR
            BERTRAFF.ORT  = AONRTAB.ORT
            BERTRAFF.BEREDARE = AONRTAB.BEREDARE
            BERTRAFF.DATUM  = AONRTIDLAGE.DATUM1
            BERTRAFF.KONSKOD  = BERVAL.KONSKOD
            BERTRAFF.BENAMNING  =  KONSTGRUPP.BENAMNING
            BERTRAFF.KTYPKOD  = BERVAL.KTYPKOD. 
            
            
         END.      
      END.   
      GET NEXT atidlq NO-LOCK.
   END.
   OUTPUT TO c:\aa\traffkonstgrupp6.txt.
   FOR EACH BERTRAFF WHERE BERTRAFF.KONSKOD = 6 USE-INDEX KONSKOD NO-LOCK:
      PUT UNFORMATTED BERTRAFF.BENAMNING FORMAT "x(30)" "  " BERTRAFF.aonr " " STRING(BERTRAFF.DELNR) " " BERTRAFF.ORT " " BERTRAFF.BEREDARE " " BERTRAFF.DATUM  " " BERTRAFF.KTYPKOD FORMAT "x(25)" SKIP.
   END.
   OUTPUT CLOSE.
   OUTPUT TO c:\aa\traffkonstgrupp44.txt.
   FOR EACH BERTRAFF WHERE BERTRAFF.KONSKOD = 44 USE-INDEX KONSKOD NO-LOCK:
      PUT UNFORMATTED BERTRAFF.BENAMNING FORMAT "x(30)" "  " BERTRAFF.aonr " " STRING(BERTRAFF.DELNR) " " BERTRAFF.ORT " " BERTRAFF.BEREDARE " " BERTRAFF.DATUM  " " BERTRAFF.KTYPKOD FORMAT "x(25)" SKIP.
   END.
   OUTPUT CLOSE.
   OUTPUT TO c:\aa\traffkonstgrupp45.txt.
   FOR EACH BERTRAFF WHERE BERTRAFF.KONSKOD = 45 USE-INDEX KONSKOD NO-LOCK:
      PUT UNFORMATTED BERTRAFF.BENAMNING FORMAT "x(30)" "  " BERTRAFF.aonr " " STRING(BERTRAFF.DELNR) " " BERTRAFF.ORT " " BERTRAFF.BEREDARE " " BERTRAFF.DATUM  " " BERTRAFF.KTYPKOD FORMAT "x(25)" SKIP.
   END.
   OUTPUT CLOSE.
   OUTPUT TO c:\aa\traffkonstgrupp46.txt.
   FOR EACH BERTRAFF WHERE BERTRAFF.KONSKOD = 46 USE-INDEX KONSKOD NO-LOCK:
      PUT UNFORMATTED BERTRAFF.BENAMNING FORMAT "x(30)" "  " BERTRAFF.aonr " " STRING(BERTRAFF.DELNR) " " BERTRAFF.ORT " " BERTRAFF.BEREDARE " " BERTRAFF.DATUM  " " BERTRAFF.KTYPKOD FORMAT "x(25)" SKIP.
   END.
   OUTPUT CLOSE.
   OUTPUT TO c:\aa\traffkonstgrupp47.txt.
   FOR EACH BERTRAFF WHERE BERTRAFF.KONSKOD = 47 USE-INDEX KONSKOD NO-LOCK:
      PUT UNFORMATTED BERTRAFF.BENAMNING FORMAT "x(30)" "  " BERTRAFF.aonr " " STRING(BERTRAFF.DELNR) " " BERTRAFF.ORT " " BERTRAFF.BEREDARE " " BERTRAFF.DATUM  " " BERTRAFF.KTYPKOD FORMAT "x(25)" SKIP.
   END.
   OUTPUT CLOSE.
   OUTPUT TO c:\aa\traffkonstgrupp48.txt.
   FOR EACH BERTRAFF WHERE BERTRAFF.KONSKOD = 48 USE-INDEX KONSKOD NO-LOCK:
      PUT UNFORMATTED BERTRAFF.BENAMNING FORMAT "x(30)" "  " BERTRAFF.aonr " " STRING(BERTRAFF.DELNR) " " BERTRAFF.ORT " " BERTRAFF.BEREDARE " " BERTRAFF.DATUM  " " BERTRAFF.KTYPKOD FORMAT "x(25)" SKIP.
   END.
   OUTPUT CLOSE.
   OUTPUT TO c:\aa\traffkonstgrupp49.txt.
   FOR EACH BERTRAFF WHERE BERTRAFF.KONSKOD = 49 USE-INDEX KONSKOD NO-LOCK:
      PUT UNFORMATTED BERTRAFF.BENAMNING FORMAT "x(30)" "  " BERTRAFF.aonr " " STRING(BERTRAFF.DELNR) " " BERTRAFF.ORT " " BERTRAFF.BEREDARE " " BERTRAFF.DATUM  " " BERTRAFF.KTYPKOD FORMAT "x(25)" SKIP.
   END.
   OUTPUT CLOSE.
   OUTPUT TO c:\aa\traffkonstgrupp50.txt.
   FOR EACH BERTRAFF WHERE BERTRAFF.KONSKOD = 50 USE-INDEX KONSKOD NO-LOCK:
      PUT UNFORMATTED BERTRAFF.BENAMNING FORMAT "x(30)" "  " BERTRAFF.aonr " " STRING(BERTRAFF.DELNR) " " BERTRAFF.ORT " " BERTRAFF.BEREDARE " " BERTRAFF.DATUM  " " BERTRAFF.KTYPKOD FORMAT "x(25)" SKIP.
   END.
   
   
   OUTPUT CLOSE.





 
 
 
    
