
   
   /*xoneAONRDUB.p*/
 DEFINE TEMP-TABLE mtrltraff NO-UNDO  
   FIELD enr     AS  CHARACTER                            
   FIELD levkod    AS  CHARACTER
   FIELD anttraff AS INTEGER 
   INDEX ENR levkod ENR.                            
DEFINE VARIABLE AOANT AS INTEGER NO-UNDO.
DEFINE VARIABLE EXANT AS INTEGER NO-UNDO.            
define buffer AOBUFF for aonrtab.
/*output to c:\aa\MTRLEJTRAFFber.txt.*/
AOANT = 0.
EXANT = 0.
output to D:\elpool\AONRbort.txt.
EMPTY TEMP-TABLE mtrltraff  NO-ERROR. 
for each AONRTAB WHERE AONRTAB.AONRAVDATUM = 12/25/2020 NO-LOCK:
   FIND FIRST BEREDNING WHERE BEREDNING.AONR = AONRTAB.AONR AND BEREDNING.DELNR = AONRTAB.DELNR  NO-LOCK NO-ERROR.
   IF NOT AVAILABLE BEREDNING THEN DO TRANSACTION:   
      AOANT = AOANT + 1.
      FIND FIRST EXTRADATA WHERE EXTRADATA.PROGRAM = "AOREF" AND                   
      EXTRADATA.HUVUDCH = AONRTAB.AONR AND EXTRADATA.HUVUDINT = AONRTAB.DELNR 
      AND EXTRADATA.SOKCHAR[6] =  "Worktask" EXCLUSIVE-LOCK NO-ERROR.
      IF AVAILABLE EXTRADATA  THEN DO:
         EXANT = EXANT + 1.
         PUT  " " AONRTAB.AONR " " AONRTAB.DELNR  " " AONRTAB.AONRAVDATUM " " EXTRADATA.SOKCHAR[6]  " " EXTRADATA.SOKCHAR[7] SKIP.  
         DELETE EXTRADATA.
      END.
      FIND CURRENT  AONRTAB EXCLUSIVE-LOCK.
      DELETE AONRTAB.
   END.
END.        
output close.      
   
   

  
 
 
 
 
    
