/*XOUTPUTTOPRINT.P*/
DEFINE VARIABLE medd AS CHARACTER NO-UNDO.
medd = "Hej hopp".
OUTPUT TO PRINTER PAGE-SIZE VALUE(72) CONVERT TARGET "iso8859-1".  
PUT SKIP (2).   
PUT PAGE-NUMBER AT 120 SKIP.              /*RAD 3*/
PUT medd AT 6 SKIP.  
OUTPUT CLOSE.
