OUTPUT TO F:\ELPLO\ES\AVTALES2001.TXT.
OPEN QUERY PQ FOR EACH PERSONALTAB NO-LOCK BY PERSONALTAB.OMRADE BY PERSONALTAB.PERSONALKOD.
GET FIRST PQ NO-LOCK.
DO WHILE AVAILABLE (PERSONALTAB):
   FIND FIRST TRAAVTAB WHERE TRAAVTAB.TRAAVTAL = PERSONALTAB.TRAAVTAL NO-LOCK NO-ERROR.
   FIND FIRST BERTAB WHERE BERTAB.BEREDSKAPSAVTAL = PERSONALTAB.BEREDSKAPSAVTAL NO-LOCK NO-ERROR.
   IF PERSONALTAB.DELTID = TRUE THEN DO:
      PUT UNFORMATTED PERSONALTAB.OMRADE ";" PERSONALTAB.PERSONALKOD ";" PERSONALTAB.ANSTNR ";"PERSONALTAB.FORNAMN ";" PERSONALTAB.EFTERNAMN ";"
      PERSONALTAB.VECKOSCHEMA ";" PERSONALTAB.ANSTALLNING FORMAT "X(40)" ";" TRAAVTAB.FORKLARING FORMAT "X(40)" ";" BERTAB.FORKL FORMAT "X(40)" ";" PERSONALTAB.DELTID  SKIP.
   END.
   ELSE DO:
      PUT UNFORMATTED PERSONALTAB.OMRADE ";" PERSONALTAB.PERSONALKOD ";" PERSONALTAB.ANSTNR ";"PERSONALTAB.FORNAMN ";" PERSONALTAB.EFTERNAMN ";"
      PERSONALTAB.VECKOSCHEMA ";" PERSONALTAB.ANSTALLNING FORMAT "X(40)" ";" TRAAVTAB.FORKLARING FORMAT "X(40)" ";" BERTAB.FORKL FORMAT "X(40)"  SKIP.
   END.
   GET NEXT PQ NO-LOCK.
END.   
