DEFINE TEMP-TABLE pers
FIELD PERSONALKOD like PERSONALTAB.PERSONALKOD 
FIELD EFTERNAMN like PERSONALTAB.EFTERNAMN 
FIELD FORNAMN like PERSONALTAB.FORNAMN 
FIELD GATUADRESS like PERSONALTAB.GATUADRESS 
FIELD POSTNUMMER like PERSONALTAB.POSTNUMMER  
FIELD POSTADRESS like PERSONALTAB.POSTADRESS 
FIELD BOXEN like PERSONALTAB.BOXEN
FIELD TELEFON like PERSONALTAB.TELEFON 
FIELD TELEFON2 like PERSONALTAB.TELEFON2
FIELD TELEFONSEM like PERSONALTAB.TELEFONSEM
FIELD PERSONNUMMER like PERSONALTAB.PERSONNUMMER 
FIELD AKTIV like PERSONALTAB.AKTIV
fiELD ANSTALLNING like PERSONALTAB.ANSTALLNING 
FIELD BEFATTNING like PERSONALTAB.BEFATTNING
FIELD VECKOSCHEMA like PERSONALTAB.VECKOSCHEMA 
FIELD ANSVARIGTIDR like PERSONALTAB.ANSVARIGTIDR 
FIELD OVERTIDUTTAG like PERSONALTAB.OVERTIDUTTAG
FIELD BEREDSKAPSAVTAL like PERSONALTAB.BEREDSKAPSAVT
FIELD GODKAND like PERSONALTAB.GODKAND
FIELD TIDSGODK like PERSONALTAB.TIDSGODK
FIELD TRAAVTAL like PERSONALTAB.TRAAVTAL
FIELD LAGBAS like PERSONALTAB.LAGBAS 
FIELD OMREGTID like PERSONALTAB.omREGTID 
FIELD DELTID like PERSONALTAB.DELTID  
FIELD OMRADE like PERSONALTAB.OMRADE
FIELD PERSMASK like PERSONALTAB.PERSMASK
FIELD BRAVO like PERSONALTAB.BRAVO
FIELD ANSTNR like PERSONALTAB.ANSTNR
FIELD ORGCHEF like PERSONALTAB.ORGCHEF
FIELD MOBILTEL like PERSONALTAB.MOBILTEL
FIELD MOBILRADIO like PERSONALTAB.MOBILRADIO
FIELD PERSONSOK like PERSONALTAB.PERSONSOK.

FOR EACH PERSONALTAB NO-LOCK:
    CREATE  pers.
    ASSIGN
    
    pers.PERSONALKOD = PERSONALTAB.ANSTNR 
    pers.EFTERNAMN = PERSONALTAB.EFTERNAMN 
    pers.FORNAMN = PERSONALTAB.FORNAMN 
    pers.GATUADRESS = PERSONALTAB.GATUADRESS 
    pers.ANSVARIGTIDR = PERSONALTAB.ANSVARIGTIDR 
    pers.POSTADRESS = PERSONALTAB.POSTADRESS 
    pers.TELEFON = PERSONALTAB.TELEFON  
    pers.PERSONNUMMER = PERSONALTAB.PERSONNUMMER 
    pers.LAGBAS = PERSONALTAB.LAGBAS 
    pers.AKTIV = PERSONALTAB.AKTIV 
    pers.OMRADE = PERSONALTAB.OMRADE 
    pers.ANSTALLNING = PERSONALTAB.ANSTALLNING 
    pers.BEFATTNING = PERSONALTAB.BEFATTNING 
    pers.VECKOSCHEMA = PERSONALTAB.VECKOSCHEMA 
    pers.OMREGTID = PERSONALTAB.omREGTID 
    pers.TIDSGODK = PERSONALTAB.TIDSGODK 
    pers.OVERTIDUTTAG = PERSONALTAB.OVERTIDUTTAG 
    pers.BEREDSKAPSAVTAL = PERSONALTAB.BEREDSKAPSAVT
    pers.GODKAND = PERSONALTAB.GODKAND  
    pers.TRAAVTAL = PERSONALTAB.TRAAVTAL 
    pers.POSTNUMMER = PERSONALTAB.POSTNUMMER 
    pers.BOXEN = PERSONALTAB.BOXEN 
    pers.TELEFON2 = PERSONALTAB.TELEFON2
    pers.PERSMASK = PERSONALTAB.PERSMASK
    pers.BRAVO = PERSONALTAB.BRAVO
    pers.ANSTNR = PERSONALTAB.ANSTNR
    pers.ORGCHEF = PERSONALTAB.ORGCHEF
    pers.MOBILTEL = PERSONALTAB.MOBILTEL
    pers.MOBILRADIO = PERSONALTAB.MOBILRADIO
    pers.PERSONSOK = PERSONALTAB.PERSONSOK
    pers.DELTID = PERSONALTAB.DELTID   .

END.
FOR EACH pers:
    FIND FIRST PERSONALTAB WHERE PERSONALTAB.personalkod = pers.TIDSGODK
    NO-LOCK NO-ERROR.
    IF AVAILABLE PERSONALTAB THEN ASSIGN pers.TIDSGODK = PERSONALTAB.ANSTNR.
    FIND FIRST PERSONALTAB WHERE PERSONALTAB.personalkod = pers.ANSVARIGTIDR
    NO-LOCK NO-ERROR.
    IF AVAILABLE PERSONALTAB THEN ASSIGN pers.ANSVARIGTIDR = PERSONALTAB.ANSTNR.
END.
OUTPUT TO A:\personal2.d.
FOR EACH pers:
    EXPORT pers.
END.
