   DEFINE VARIABLE befvar AS CHARACTER NO-UNDO.
   DEFINE VARIABLE prisvar AS DECIMAL NO-UNDO.
   DEFINE VARIABLE musz AS LOGICAL NO-UNDO.
   DEFINE TEMP-TABLE TT NO-UNDO LIKE SUMTIDDAG.
   RUN TID_UI (INPUT "14315").
RUN TID_UI (INPUT "14504").
RUN TID_UI (INPUT "14512").
RUN TID_UI (INPUT "14526").
RUN TID_UI (INPUT "30033").
RUN TID_UI (INPUT "30034").

PROCEDURE TID_UI :
   DEFINE INPUT PARAMETER PCC AS CHARACTER NO-UNDO.
   OPEN QUERY CC FOR EACH PERSONALTAB WHERE PERSONALTAB.PERSONALKOD = PCC NO-LOCK,
   EACH TIDREGITAB WHERE TIDREGITAB.PERSONALKOD = PERSONALTAB.PERSONALKOD  AND tidregitab.tidlog = TRUE AND 
   TIDREGITAB.DATUM GE 01/01/2007 AND TIDREGITAB.OVERTIDTILL = "DRIFTOPERATÖR" no-LOCK.
   GET FIRST cc NO-LOCK.

   DO WHILE AVAILABLE tidregitab:
      IF tidregitab.pristyp = "FRÅNVARO." OR tidregitab.pristyp = "RESTID..." THEN .
      ELSE DO:
         PUT TIDREGITAB.personalkod TIDREGITAB.datum TIDREGITAB.START tidregitab.overtidtill TIDREGITAB.slut TIDREGITAB.aonr TIDREGITAB.pris prisvar SKIP.
         GET CURRENT cc EXCLUSIVE-LOCK.
         TIDREGITAB.pris =  275.
      END.
      GET NEXT cc NO-LOCK.
   END.
   OUTPUT CLOSE. 
   FOR EACH SUMTIDDAG WHERE SUMTIDDAG.PERSONALKOD = PCC AND SUMTIDDAG.DATUM GE 01/01/2007 AND SUMTIDDAG.BEFATTNING BEGINS "DRIFTOPERATÖR" EXCLUSIVE-LOCK:
      IF SUMTIDDAG.pristyp = "FRÅNVARO." OR SUMTIDDAG.pristyp = "RESTID..." THEN .
      ELSE DO:
         FIND FIRST TIDREGITAB WHERE TIDREGITAB.PERSONALKOD = SUMTIDDAG.PERSONALKOD AND TIDREGITAB.DATUM = SUMTIDDAG.DATUM AND TIDREGITAB.OKOD1 NE "" NO-LOCK NO-ERROR.
         IF AVAILABLE TIDREGITAB THEN DO:
            FIND FIRST PERSONALTAB WHERE PERSONALTAB.PERSONALKOD = TIDREGITAB.PERSONALKOD NO-LOCK NO-ERROR.
            FIND FIRST ANSTFORMTAB WHERE ANSTFORMTAB.ANSTALLNING = PERSONALTAB.ANSTALLNING  NO-LOCK NO-ERROR.
            FIND FIRST OVERKOD WHERE OVERKOD.KOD = ANSTFORMTAB.KOD AND OVERKOD.OVERTIDTILL = TIDREGITAB.OKOD1 NO-LOCK NO-ERROR.
            IF AVAILABLE OVERKOD  THEN DO:
               ASSIGN 
               SUMTIDDAG.AUTODATUM = TODAY
               SUMTIDDAG.PRIS = 275 
               SUMTIDDAG.OBELOPP = (275 + (275 * OVERKOD.MULTIP)) * SUMTIDDAG.OTIMMAR.    
            END.
         END.     
         ASSIGN 
         SUMTIDDAG.AUTODATUM = TODAY
         SUMTIDDAG.PRIS = 275 
         SUMTIDDAG.BELOPP = 275 * SUMTIDDAG.TIMMAR.
         IF SUMTIDDAG.VECKOKORD NE "" THEN DO:
            CREATE TT.
            BUFFER-COPY SUMTIDDAG TO TT.
         END.
      END.
   END.
      
 END PROCEDURE.
 DEFINE TEMP-TABLE TT2 NO-UNDO LIKE TT.
 FOR EACH TT BREAK BY TT.PERSONALKOD BY TT.AONR BY TT.DELNR:
    ACCUMULATE TT.BELOPP (TOTAL BY TT.PERSONALKOD BY TT.AONR BY TT.DELNR ). 
    ACCUMULATE TT.TIMMAR (TOTAL BY TT.PERSONALKOD BY TT.AONR BY TT.DELNR). 
    ACCUMULATE TT.OTIMMAR (TOTAL BY TT.PERSONALKOD BY TT.AONR BY TT.DELNR). 
    ACCUMULATE TT.OBELOPP (TOTAL BY TT.PERSONALKOD BY TT.AONR BY TT.DELNR).        
    IF LAST-OF(TT.DELNR) THEN DO:
      CREATE TT2.
      ASSIGN 
      TT2.AONR = TT.AONR
      TT2.DELNR = TT.DELNR
      TT2.PERSONALKOD = TT.PERSONALKOD
      TT2.BELOPP = (ACCUM TOTAL BY TT.DELNR TT.BELOPP)                      
      TT2.TIMMAR = (ACCUM TOTAL BY TT.DELNR TT.TIMMAR) 
      TT2.OTIMMAR = (ACCUM TOTAL BY TT.DELNR TT.OTIMMAR)
      TT2.OBELOPP = (ACCUM TOTAL BY TT.DELNR TT.OBELOPP).                         
   END.
 END.
 OUTPUT TO C:\PROTEMP9\DRIFT.TXT.
 FOR EACH TT2 BY TT.AONR BY TT.DELNR BY TT.PERSONALKOD:
    PUT TT2.AONR  
        TT2.DELNR 
        TT2.PERSONALKOD
        TT2.TIMMAR 
        TT2.BELOPP 
        TT2.OTIMMAR
        TT2.OBELOPP SKIP.
 END.
 OUTPUT CLOSE.
