   DEFINE VARIABLE befvar AS CHARACTER NO-UNDO.
   DEFINE VARIABLE prisvar AS DECIMAL NO-UNDO.
   DEFINE VARIABLE musz AS LOGICAL NO-UNDO.
   OUTPUT TO c:\temp\priskalmar.txt APPEND.
   OPEN QUERY cc FOR EACH PERSONALTAB WHERE PERSONALTAB.AKTIV = TRUE NO-LOCK,
   EACH TIDREGITAB WHERE TIDREGITAB.PERSONALKOD = PERSONALTAB.PERSONALKOD  AND tidregitab.tidlog = TRUE AND 
   TIDREGITAB.DATUM GE 02/01/2006 no-LOCK.
   GET FIRST cc NO-LOCK.

   DO WHILE AVAILABLE tidregitab:
      befvar = tidregitab.overtidtill.
      prisvar = 0.
      musz = FALSE.
      IF tidregitab.overtidtill  = "" THEN DO:
         befvar = PERSONALTAB.BEFATTNING.
      END.
      IF tidregitab.pristyp = "FRÅNVARO." OR tidregitab.pristyp = "RESTID..." THEN DO:
         FIND FIRST PERSONALPRIS WHERE 
         PERSONALPRIS.PERSONALKOD = PERSONALTAB.PERSONALKOD AND
         PERSONALPRIS.BEFATTNING = tidregitab.pristyp AND 
         PERSONALPRIS.STARTDATUM = 02/01/2006 
         NO-LOCK NO-ERROR.
         IF AVAILABLE PERSONALPRIS THEN DO:
            prisvar = PERSONALPRIS.PRIS.  
         END.
         ELSE musz = TRUE.
      END.
      ELSE DO:
         FIND FIRST PERSONALPRIS WHERE 
         PERSONALPRIS.PERSONALKOD = PERSONALTAB.PERSONALKOD AND
         PERSONALPRIS.BEFATTNING = befvar AND 
         PERSONALPRIS.STARTDATUM = 02/01/2006  NO-LOCK NO-ERROR.
         IF AVAILABLE PERSONALPRIS THEN DO:
            prisvar = PERSONALPRIS.PRIS.  
         END.            
         ELSE musz = TRUE.
      END.
      IF musz = FALSE THEN DO TRANSACTION:
         IF TIDREGITAB.pris NE prisvar THEN DO:
            PUT TIDREGITAB.personalkod TIDREGITAB.datum TIDREGITAB.START tidregitab.overtidtill TIDREGITAB.slut TIDREGITAB.aonr TIDREGITAB.pris prisvar SKIP.
            GET CURRENT cc EXCLUSIVE-LOCK.
            TIDREGITAB.pris =  prisvar.
         END.
      END.
      GET NEXT cc NO-LOCK.
   END.
   OUTPUT CLOSE.


   FOR EACH TIDREGITAB WHERE TIDREGITAB.DATUM GE 01/01/2006 AND TIDREGITAB.TIDLOG = TRUE 
   AND TIDREGITAB.OVERTIDTILL = "DRIFTOPERATÖR" EXCLUSIVE-LOCK:
      ASSIGN TIDREGITAB.PRIS = 260.

   END.

   FOR EACH SUMTIDDAG WHERE SUMTIDDAG.DATUM GE 01/01/2006 AND SUMTIDDAG.BEFATTNING BEGINS "DRIFTOPERATÖR" EXCLUSIVE-LOCK:
      FIND FIRST TIDREGITAB WHERE TIDREGITAB.PERSONALKOD = SUMTIDDAG.PERSONALKOD AND TIDREGITAB.DATUM = SUMTIDDAG.DATUM AND TIDREGITAB.OKOD1 NE "" NO-LOCK NO-ERROR.
      IF AVAILABLE TIDREGITAB THEN DO:
         FIND FIRST PERSONALTAB WHERE PERSONALTAB.PERSONALKOD = TIDREGITAB.PERSONALKOD NO-LOCK NO-ERROR.
         FIND FIRST ANSTFORMTAB WHERE ANSTFORMTAB.ANSTALLNING = PERSONALTAB.ANSTALLNING  NO-LOCK NO-ERROR.
         FIND FIRST OVERKOD WHERE OVERKOD.KOD = ANSTFORMTAB.KOD AND OVERKOD.OVERTIDTILL = TIDREGITAB.OKOD1 NO-LOCK NO-ERROR.
         IF AVAILABLE OVERKOD  THEN DO:
            ASSIGN SUMTIDDAG.PRIS = 260 
            SUMTIDDAG.OBELOPP = (260 + (260 * OVERKOD.MULTIP)) * SUMTIDDAG.OTIMMAR.    
         END.
      END.     
      ASSIGN SUMTIDDAG.PRIS = 260 
      SUMTIDDAG.BELOPP = 260 * SUMTIDDAG.TIMMAR.
      
   END.
