DEFINE VARIABLE persrec AS RECID NO-UNDO.
DO :
  OPEN QUERY persq FOR EACH PERSONALTAB WHERE PERSONALTAB.OMRADE BEGINS "1"
  NO-LOCK.
  GET FIRST persq NO-LOCK.
  DO WHILE AVAILABLE(PERSONALTAB):     
     persrec = RECID(PERSONALTAB).
     OPEN QUERY timq
     FOR EACH TIMKOSTNADSTAB WHERE TIMKOSTNADSTAB.PERSONALKOD = PERSONALTAB.PERSONALKOD
     USE-INDEX PRISPERS NO-LOCK.
     DO TRANSACTION:       
        GET FIRST timq EXCLUSIVE-LOCK.
        IF AVAILABLE TIMKOSTNADSTAB THEN DELETE TIMKOSTNADSTAB.    
     END.     
     REPEAT:       
        DO TRANSACTION:
           GET NEXT timq EXCLUSIVE-LOCK.
           IF AVAILABLE TIMKOSTNADSTAB THEN DELETE TIMKOSTNADSTAB.    
           ELSE LEAVE.            
        END.     
     END.                            
     CLOSE QUERY timq.
     
     OPEN QUERY psekq
     FOR EACH PERSEK WHERE PERSEK.PERSONALKOD = PERSONALTAB.PERSONALKOD 
     USE-INDEX PERSONALKOD NO-LOCK.
     DO TRANSACTION:       
        GET FIRST psekq EXCLUSIVE-LOCK.
        IF AVAILABLE PERSEK THEN DELETE PERSEK.    
     END.     
     REPEAT:       
        DO TRANSACTION:
           GET NEXT psekq EXCLUSIVE-LOCK.
           IF AVAILABLE PERSEK THEN DELETE PERSEK.    
           ELSE LEAVE.            
        END.     
     END.                  
     CLOSE QUERY psekq.
       
     OPEN QUERY tsekq
     FOR EACH TIDSEK WHERE TIDSEK.PERSONALKOD = PERSONALTAB.PERSONALKOD 
     USE-INDEX PERSONALKOD NO-LOCK.
     DO TRANSACTION:       
        GET FIRST tsekq EXCLUSIVE-LOCK.
        IF AVAILABLE TIDSEK THEN DELETE TIDSEK.    
     END.     
     REPEAT:       
        DO TRANSACTION:
           GET NEXT tsekq EXCLUSIVE-LOCK.
           IF AVAILABLE TIDSEK THEN DELETE TIDSEK.    
           ELSE LEAVE.            
        END.     
     END.                  
    
     CLOSE QUERY tsekq.                                 
     DO TRANSACTION:
        FIND FIRST ANSVARIGTAB WHERE ANSVARIGTAB.PERSONALKOD = PERSONALTAB.ANSVARIGTIDR
        USE-INDEX ANSVG EXCLUSIVE-LOCK NO-ERROR.     
        IF AVAILABLE ANSVARIGTAB THEN DO: 
           DELETE ANSVARIGTAB.
        END.
     END. 
     DO TRANSACTION:
        FIND FIRST GODKANNARTAB WHERE GODKANNARTAB.PERSONALKOD = PERSONALTAB.TIDSGODK 
        USE-INDEX GODK EXCLUSIVE-LOCK NO-ERROR.     
        IF AVAILABLE GODKANNARTAB THEN DO:
           DELETE GODKANNARTAB.
        END.
     END.      
     DO TRANSACTION:
        FIND FIRST BEREDAONR WHERE BEREDAONR.PERSONALKOD = PERSONALTAB.PERSONALKOD 
        USE-INDEX PERSONALKOD EXCLUSIVE-LOCK NO-ERROR. 
        IF AVAILABLE BEREDAONR THEN DO:
           DELETE BEREDAONR.
        END.
     END.   
     DO TRANSACTION:
        FIND FIRST ANSVAONR WHERE ANSVAONR.PERSONALKOD = PERSONALTAB.PERSONALKOD 
        USE-INDEX PERSONALKOD EXCLUSIVE-LOCK NO-ERROR.   
        IF AVAILABLE ANSVAONR THEN DO:
           DELETE ANSVAONR.
        END.           
     END.
     
     FIND FIRST ANVANDARE WHERE ANVANDARE.PERSONALKOD = PERSONALTAB.PERSONALKOD
     NO-LOCK NO-ERROR.   
    
     DEFINE QUERY persekq FOR PERSEK.
     OPEN QUERY persekq FOR EACH PERSEK WHERE PERSEK.ANVANDARE = ANVANDARE.ANVANDARE
     USE-INDEX PERSEK NO-LOCK.      
     DO TRANSACTION:       
        GET FIRST persekq EXCLUSIVE-LOCK.
        IF AVAILABLE PERSEK THEN DELETE PERSEK.    
     END.     
     REPEAT:       
        DO TRANSACTION:
           GET NEXT persekq EXCLUSIVE-LOCK.
           IF AVAILABLE PERSEK THEN DELETE PERSEK.    
           ELSE LEAVE.            
        END.     
     END.       
     DEFINE QUERY tidsekq FOR TIDSEK.
     OPEN QUERY tidsekq FOR EACH TIDSEK WHERE TIDSEK.ANVANDARE = ANVANDARE.ANVANDARE
     USE-INDEX TIDSEK NO-LOCK. 
     DO TRANSACTION:       
        GET FIRST tidsekq EXCLUSIVE-LOCK.
        IF AVAILABLE TIDSEK THEN DELETE TIDSEK.    
     END.
     REPEAT:  
        DO TRANSACTION:
           GET NEXT tidsekq EXCLUSIVE-LOCK.         
           IF AVAILABLE TIDSEK THEN DELETE TIDSEK.    
           ELSE LEAVE.      
        END.         
     END.                                                     
     DO TRANSACTION:
        FIND FIRST ANVANDARE WHERE ANVANDARE.PERSONALKOD = PERSONALTAB.PERSONALKOD
        EXCLUSIVE-LOCK NO-ERROR.   
        IF AVAILABLE ANVANDARE THEN DO:
           DELETE ANVANDARE.
        END.
     END.
     DO TRANSACTION:
        FIND PERSONALTAB WHERE RECID(PERSONALTAB) = persrec EXCLUSIVE-LOCK NO-ERROR.        
        DELETE PERSONALTAB.
     END.   
    
     GET NEXT persq NO-LOCK.
  END.   
END.  
DO :
  OPEN QUERY persq FOR EACH PERSONALTAB WHERE PERSONALTAB.OMRADE BEGINS "2"
  NO-LOCK.
  GET FIRST persq NO-LOCK.
  DO WHILE AVAILABLE(PERSONALTAB):     
     persrec = RECID(PERSONALTAB).
     OPEN QUERY timq
     FOR EACH TIMKOSTNADSTAB WHERE TIMKOSTNADSTAB.PERSONALKOD = PERSONALTAB.PERSONALKOD
     USE-INDEX PRISPERS NO-LOCK.
     DO TRANSACTION:       
        GET FIRST timq EXCLUSIVE-LOCK.
        IF AVAILABLE TIMKOSTNADSTAB THEN DELETE TIMKOSTNADSTAB.    
     END.     
     REPEAT:       
        DO TRANSACTION:
           GET NEXT timq EXCLUSIVE-LOCK.
           IF AVAILABLE TIMKOSTNADSTAB THEN DELETE TIMKOSTNADSTAB.    
           ELSE LEAVE.            
        END.     
     END.                            
     CLOSE QUERY timq.
     
     OPEN QUERY psekq
     FOR EACH PERSEK WHERE PERSEK.PERSONALKOD = PERSONALTAB.PERSONALKOD 
     USE-INDEX PERSONALKOD NO-LOCK.
     DO TRANSACTION:       
        GET FIRST psekq EXCLUSIVE-LOCK.
        IF AVAILABLE PERSEK THEN DELETE PERSEK.    
     END.     
     REPEAT:       
        DO TRANSACTION:
           GET NEXT psekq EXCLUSIVE-LOCK.
           IF AVAILABLE PERSEK THEN DELETE PERSEK.    
           ELSE LEAVE.            
        END.     
     END.                  
     CLOSE QUERY psekq.
       
     OPEN QUERY tsekq
     FOR EACH TIDSEK WHERE TIDSEK.PERSONALKOD = PERSONALTAB.PERSONALKOD 
     USE-INDEX PERSONALKOD NO-LOCK.
     DO TRANSACTION:       
        GET FIRST tsekq EXCLUSIVE-LOCK.
        IF AVAILABLE TIDSEK THEN DELETE TIDSEK.    
     END.     
     REPEAT:       
        DO TRANSACTION:
           GET NEXT tsekq EXCLUSIVE-LOCK.
           IF AVAILABLE TIDSEK THEN DELETE TIDSEK.    
           ELSE LEAVE.            
        END.     
     END.                  
    
     CLOSE QUERY tsekq.                                 
     DO TRANSACTION:
        FIND FIRST ANSVARIGTAB WHERE ANSVARIGTAB.PERSONALKOD = PERSONALTAB.ANSVARIGTIDR
        USE-INDEX ANSVG EXCLUSIVE-LOCK NO-ERROR.     
        IF AVAILABLE ANSVARIGTAB THEN DO: 
           DELETE ANSVARIGTAB.
        END.
     END. 
     DO TRANSACTION:
        FIND FIRST GODKANNARTAB WHERE GODKANNARTAB.PERSONALKOD = PERSONALTAB.TIDSGODK 
        USE-INDEX GODK EXCLUSIVE-LOCK NO-ERROR.     
        IF AVAILABLE GODKANNARTAB THEN DO:
           DELETE GODKANNARTAB.
        END.
     END.      
     DO TRANSACTION:
        FIND FIRST BEREDAONR WHERE BEREDAONR.PERSONALKOD = PERSONALTAB.PERSONALKOD 
        USE-INDEX PERSONALKOD EXCLUSIVE-LOCK NO-ERROR. 
        IF AVAILABLE BEREDAONR THEN DO:
           DELETE BEREDAONR.
        END.
     END.   
     DO TRANSACTION:
        FIND FIRST ANSVAONR WHERE ANSVAONR.PERSONALKOD = PERSONALTAB.PERSONALKOD 
        USE-INDEX PERSONALKOD EXCLUSIVE-LOCK NO-ERROR.   
        IF AVAILABLE ANSVAONR THEN DO:
           DELETE ANSVAONR.
        END.           
     END.
     
     FIND FIRST ANVANDARE WHERE ANVANDARE.PERSONALKOD = PERSONALTAB.PERSONALKOD
     NO-LOCK NO-ERROR.   
         
     OPEN QUERY persekq FOR EACH PERSEK WHERE PERSEK.ANVANDARE = ANVANDARE.ANVANDARE
     USE-INDEX PERSEK NO-LOCK.      
     DO TRANSACTION:       
        GET FIRST persekq EXCLUSIVE-LOCK.
        IF AVAILABLE PERSEK THEN DELETE PERSEK.    
     END.     
     REPEAT:       
        DO TRANSACTION:
           GET NEXT persekq EXCLUSIVE-LOCK.
           IF AVAILABLE PERSEK THEN DELETE PERSEK.    
           ELSE LEAVE.            
        END.     
     END.       
     
     OPEN QUERY tidsekq FOR EACH TIDSEK WHERE TIDSEK.ANVANDARE = ANVANDARE.ANVANDARE
     USE-INDEX TIDSEK NO-LOCK. 
     DO TRANSACTION:       
        GET FIRST tidsekq EXCLUSIVE-LOCK.
        IF AVAILABLE TIDSEK THEN DELETE TIDSEK.    
     END.
     REPEAT:  
        DO TRANSACTION:
           GET NEXT tidsekq EXCLUSIVE-LOCK.         
           IF AVAILABLE TIDSEK THEN DELETE TIDSEK.    
           ELSE LEAVE.      
        END.         
     END.                                                     
     DO TRANSACTION:
        FIND FIRST ANVANDARE WHERE ANVANDARE.PERSONALKOD = PERSONALTAB.PERSONALKOD
        EXCLUSIVE-LOCK NO-ERROR.   
        IF AVAILABLE ANVANDARE THEN DO:
           DELETE ANVANDARE.
        END.
     END.
     DO TRANSACTION:
        FIND PERSONALTAB WHERE RECID(PERSONALTAB) = persrec EXCLUSIVE-LOCK NO-ERROR.        
        DELETE PERSONALTAB.
     END.   
    
     GET NEXT persq NO-LOCK.
  END.   
END.  
DO :
  OPEN QUERY persq FOR EACH PERSONALTAB WHERE PERSONALTAB.OMRADE BEGINS "3"
  NO-LOCK.
  GET FIRST persq NO-LOCK.
  DO WHILE AVAILABLE(PERSONALTAB):     
     persrec = RECID(PERSONALTAB).
     OPEN QUERY timq
     FOR EACH TIMKOSTNADSTAB WHERE TIMKOSTNADSTAB.PERSONALKOD = PERSONALTAB.PERSONALKOD
     USE-INDEX PRISPERS NO-LOCK.
     DO TRANSACTION:       
        GET FIRST timq EXCLUSIVE-LOCK.
        IF AVAILABLE TIMKOSTNADSTAB THEN DELETE TIMKOSTNADSTAB.    
     END.     
     REPEAT:       
        DO TRANSACTION:
           GET NEXT timq EXCLUSIVE-LOCK.
           IF AVAILABLE TIMKOSTNADSTAB THEN DELETE TIMKOSTNADSTAB.    
           ELSE LEAVE.            
        END.     
     END.                            
     CLOSE QUERY timq.
     
     OPEN QUERY psekq
     FOR EACH PERSEK WHERE PERSEK.PERSONALKOD = PERSONALTAB.PERSONALKOD 
     USE-INDEX PERSONALKOD NO-LOCK.
     DO TRANSACTION:       
        GET FIRST psekq EXCLUSIVE-LOCK.
        IF AVAILABLE PERSEK THEN DELETE PERSEK.    
     END.     
     REPEAT:       
        DO TRANSACTION:
           GET NEXT psekq EXCLUSIVE-LOCK.
           IF AVAILABLE PERSEK THEN DELETE PERSEK.    
           ELSE LEAVE.            
        END.     
     END.                  
     CLOSE QUERY psekq.
       
     OPEN QUERY tsekq
     FOR EACH TIDSEK WHERE TIDSEK.PERSONALKOD = PERSONALTAB.PERSONALKOD 
     USE-INDEX PERSONALKOD NO-LOCK.
     DO TRANSACTION:       
        GET FIRST tsekq EXCLUSIVE-LOCK.
        IF AVAILABLE TIDSEK THEN DELETE TIDSEK.    
     END.     
     REPEAT:       
        DO TRANSACTION:
           GET NEXT tsekq EXCLUSIVE-LOCK.
           IF AVAILABLE TIDSEK THEN DELETE TIDSEK.    
           ELSE LEAVE.            
        END.     
     END.                  
    
     CLOSE QUERY tsekq.                                 
     DO TRANSACTION:
        FIND FIRST ANSVARIGTAB WHERE ANSVARIGTAB.PERSONALKOD = PERSONALTAB.ANSVARIGTIDR
        USE-INDEX ANSVG EXCLUSIVE-LOCK NO-ERROR.     
        IF AVAILABLE ANSVARIGTAB THEN DO: 
           DELETE ANSVARIGTAB.
        END.
     END. 
     DO TRANSACTION:
        FIND FIRST GODKANNARTAB WHERE GODKANNARTAB.PERSONALKOD = PERSONALTAB.TIDSGODK 
        USE-INDEX GODK EXCLUSIVE-LOCK NO-ERROR.     
        IF AVAILABLE GODKANNARTAB THEN DO:
           DELETE GODKANNARTAB.
        END.
     END.      
     DO TRANSACTION:
        FIND FIRST BEREDAONR WHERE BEREDAONR.PERSONALKOD = PERSONALTAB.PERSONALKOD 
        USE-INDEX PERSONALKOD EXCLUSIVE-LOCK NO-ERROR. 
        IF AVAILABLE BEREDAONR THEN DO:
           DELETE BEREDAONR.
        END.
     END.   
     DO TRANSACTION:
        FIND FIRST ANSVAONR WHERE ANSVAONR.PERSONALKOD = PERSONALTAB.PERSONALKOD 
        USE-INDEX PERSONALKOD EXCLUSIVE-LOCK NO-ERROR.   
        IF AVAILABLE ANSVAONR THEN DO:
           DELETE ANSVAONR.
        END.           
     END.
     
     FIND FIRST ANVANDARE WHERE ANVANDARE.PERSONALKOD = PERSONALTAB.PERSONALKOD
     NO-LOCK NO-ERROR.   
    
     
     OPEN QUERY persekq FOR EACH PERSEK WHERE PERSEK.ANVANDARE = ANVANDARE.ANVANDARE
     USE-INDEX PERSEK NO-LOCK.      
     DO TRANSACTION:       
        GET FIRST persekq EXCLUSIVE-LOCK.
        IF AVAILABLE PERSEK THEN DELETE PERSEK.    
     END.     
     REPEAT:       
        DO TRANSACTION:
           GET NEXT persekq EXCLUSIVE-LOCK.
           IF AVAILABLE PERSEK THEN DELETE PERSEK.    
           ELSE LEAVE.            
        END.     
     END.       
     
     OPEN QUERY tidsekq FOR EACH TIDSEK WHERE TIDSEK.ANVANDARE = ANVANDARE.ANVANDARE
     USE-INDEX TIDSEK NO-LOCK. 
     DO TRANSACTION:       
        GET FIRST tidsekq EXCLUSIVE-LOCK.
        IF AVAILABLE TIDSEK THEN DELETE TIDSEK.    
     END.
     REPEAT:  
        DO TRANSACTION:
           GET NEXT tidsekq EXCLUSIVE-LOCK.         
           IF AVAILABLE TIDSEK THEN DELETE TIDSEK.    
           ELSE LEAVE.      
        END.         
     END.                                                     
     DO TRANSACTION:
        FIND FIRST ANVANDARE WHERE ANVANDARE.PERSONALKOD = PERSONALTAB.PERSONALKOD
        EXCLUSIVE-LOCK NO-ERROR.   
        IF AVAILABLE ANVANDARE THEN DO:
           DELETE ANVANDARE.
        END.
     END.
     DO TRANSACTION:
        FIND PERSONALTAB WHERE RECID(PERSONALTAB) = persrec EXCLUSIVE-LOCK NO-ERROR.        
        DELETE PERSONALTAB.
     END.   
    
     GET NEXT persq NO-LOCK.
  END.   
END.  
RUN XRENS.P.
