DEFINE VARIABLE persrec AS RECID NO-UNDO.
DO :
  OPEN QUERY persq FOR EACH PERSONALTAB WHERE PERSONALTAB.OMRADE BEGINS "1"
  NO-LOCK.
  DO TRANSACTION:
     GET FIRST persq EXCLUSIVE-LOCK.
     OPEN QUERY timq
     FOR EACH TIMKOSTNADSTAB WHERE TIMKOSTNADSTAB.PERSONALKOD = PERSONALTAB.PERSONALKOD
     USE-INDEX PRISPERS NO-LOCK.
     DO TRANSACTION:       
        GET FIRST timq EXCLUSIVE-LOCK.
        IF AVAILABLE TIMKOSTNADSTAB THEN DELETE TIMKOSTNADSTAB.    
     END.     
     REPEAT:       
        DO TRANSACTION:
           GET NEXT timq EXCLUSIVE-LOCK.
           IF AVAILABLE TIMKOSTNADSTAB THEN DELETE TIMKOSTNADSTAB.    
           ELSE LEAVE.            
        END.     
     END.                            
     CLOSE QUERY timq.
     OPEN QUERY psekq
     FOR EACH PERSEK WHERE PERSEK.PERSONALKOD = PERSONALTAB.PERSONALKOD 
     USE-INDEX PERSONALKOD NO-LOCK.
     DO TRANSACTION:       
        GET FIRST psekq EXCLUSIVE-LOCK.
        IF AVAILABLE PERSEK THEN DELETE PERSEK.    
     END.     
     REPEAT:       
        DO TRANSACTION:
           GET NEXT psekq EXCLUSIVE-LOCK.
           IF AVAILABLE PERSEK THEN DELETE PERSEK.    
           ELSE LEAVE.            
        END.     
     END.                  
     CLOSE QUERY psekq.
    
     OPEN QUERY tsekq
     FOR EACH TIDSEK WHERE TIDSEK.PERSONALKOD = PERSONALTAB.PERSONALKOD 
     USE-INDEX PERSONALKOD NO-LOCK.
     DO TRANSACTION:       
        GET FIRST tsekq EXCLUSIVE-LOCK.
        IF AVAILABLE TIDSEK THEN DELETE TIDSEK.    
     END.     
     REPEAT:       
        DO TRANSACTION:
           GET NEXT tsekq EXCLUSIVE-LOCK.
           IF AVAILABLE TIDSEK THEN DELETE TIDSEK.    
           ELSE LEAVE.            
        END.     
     END.                  
    
     CLOSE QUERY tsekq.                                 
     
     FIND FIRST ANSVARIGTAB WHERE ANSVARIGTAB.PERSONALKOD = PERSONALTAB.ANSVARIGTIDR
     USE-INDEX ANSVG EXCLUSIVE-LOCK NO-ERROR.     
     IF AVAILABLE ANSVARIGTAB THEN DO TRANSACTION:
        DELETE ANSVARIGTAB.
     END. 
   
     FIND FIRST GODKANNARTAB WHERE GODKANNARTAB.PERSONALKOD = PERSONALTAB.TIDSGODK 
     USE-INDEX GODK EXCLUSIVE-LOCK NO-ERROR.     
     IF AVAILABLE GODKANNARTAB THEN DO TRANSACTION:
        DELETE GODKANNARTAB.
     END.      
     FIND FIRST BEREDAONR WHERE BEREDAONR.PERSONALKOD = PERSONALTAB.PERSONALKOD 
     USE-INDEX PERSONALKOD EXCLUSIVE-LOCK NO-ERROR. 
     IF AVAILABLE BEREDAONR THEN DO TRANSACTION:
        DELETE BEREDAONR.
     END.   
     FIND FIRST ANSVAONR WHERE ANSVAONR.PERSONALKOD = PERSONALTAB.PERSONALKOD 
     USE-INDEX PERSONALKOD EXCLUSIVE-LOCK NO-ERROR.   
     IF AVAILABLE ANSVAONR THEN DO TRANSACTION:
        DELETE ANSVAONR.
     END.
     FIND FIRST ANVANDARE WHERE ANVANDARE.PERSONALKOD = PERSONALTAB.PERSONALKOD
     NO-LOCK NO-ERROR.   
    
     DEFINE QUERY persekq FOR PERSEK.
     OPEN QUERY persekq FOR EACH PERSEK WHERE PERSEK.ANVANDARE = ANVANDARE.ANVANDARE
     USE-INDEX PERSEK NO-LOCK.      
     DO TRANSACTION:       
        GET FIRST persekq EXCLUSIVE-LOCK.
        IF AVAILABLE PERSEK THEN DELETE PERSEK.    
     END.     
     REPEAT:       
        DO TRANSACTION:
           GET NEXT persekq EXCLUSIVE-LOCK.
           IF AVAILABLE PERSEK THEN DELETE PERSEK.    
           ELSE LEAVE.            
        END.     
     END.       
     DEFINE QUERY tidsekq FOR TIDSEK.
     OPEN QUERY tidsekq FOR EACH TIDSEK WHERE TIDSEK.ANVANDARE = ANVANDARE.ANVANDARE
     USE-INDEX TIDSEK NO-LOCK. 
     DO TRANSACTION:       
        GET FIRST tidsekq EXCLUSIVE-LOCK.
        IF AVAILABLE TIDSEK THEN DELETE TIDSEK.    
     END.
     REPEAT:  
        DO TRANSACTION:
           GET NEXT tidsekq EXCLUSIVE-LOCK.         
           IF AVAILABLE TIDSEK THEN DELETE TIDSEK.    
           ELSE LEAVE.      
        END.         
     END.                                                     
     FIND FIRST ANVANDARE WHERE ANVANDARE.PERSONALKOD = PERSONALTAB.PERSONALKOD
     EXCLUSIVE-LOCK NO-ERROR.   
     IF AVAILABLE ANVANDARE THEN DO TRANSACTION:
        DELETE ANVANDARE.
     END.     
     DO TRANSACTION:
        DELETE PERSONALTAB.
     END.   
  END.
  REPEAT:       
     DO TRANSACTION:   
        GET NEXT persq EXCLUSIVE-LOCK.
        OPEN QUERY timq
        FOR EACH TIMKOSTNADSTAB WHERE TIMKOSTNADSTAB.PERSONALKOD = PERSONALTAB.PERSONALKOD
        USE-INDEX PRISPERS NO-LOCK.
        DO TRANSACTION:       
           GET FIRST timq EXCLUSIVE-LOCK.
           IF AVAILABLE TIMKOSTNADSTAB THEN DELETE TIMKOSTNADSTAB.    
        END.     
        REPEAT:       
           DO TRANSACTION:
              GET NEXT timq EXCLUSIVE-LOCK.
              IF AVAILABLE TIMKOSTNADSTAB THEN DELETE TIMKOSTNADSTAB.    
              ELSE LEAVE.            
           END.     
        END.                            
        CLOSE QUERY timq.
        OPEN QUERY psekq
        FOR EACH PERSEK WHERE PERSEK.PERSONALKOD = PERSONALTAB.PERSONALKOD 
        USE-INDEX PERSONALKOD NO-LOCK.
        DO TRANSACTION:       
           GET FIRST psekq EXCLUSIVE-LOCK.
           IF AVAILABLE PERSEK THEN DELETE PERSEK.    
        END.     
        REPEAT:       
           DO TRANSACTION:
              GET NEXT psekq EXCLUSIVE-LOCK.
              IF AVAILABLE PERSEK THEN DELETE PERSEK.    
              ELSE LEAVE.            
           END.     
        END.                  
        CLOSE QUERY psekq.
    
        OPEN QUERY tsekq
        FOR EACH TIDSEK WHERE TIDSEK.PERSONALKOD = PERSONALTAB.PERSONALKOD 
        USE-INDEX PERSONALKOD NO-LOCK.
        DO TRANSACTION:       
           GET FIRST tsekq EXCLUSIVE-LOCK.
           IF AVAILABLE TIDSEK THEN DELETE TIDSEK.    
        END.     
        REPEAT:       
           DO TRANSACTION:
              GET NEXT tsekq EXCLUSIVE-LOCK.
              IF AVAILABLE TIDSEK THEN DELETE TIDSEK.    
              ELSE LEAVE.            
           END.     
        END.                     
        CLOSE QUERY tsekq.                                     
        FIND FIRST ANSVARIGTAB WHERE ANSVARIGTAB.PERSONALKOD = PERSONALTAB.ANSVARIGTIDR
        USE-INDEX ANSVG EXCLUSIVE-LOCK NO-ERROR.     
        IF AVAILABLE ANSVARIGTAB THEN DO TRANSACTION:
           DELETE ANSVARIGTAB.
        END.    
        FIND FIRST GODKANNARTAB WHERE GODKANNARTAB.PERSONALKOD = PERSONALTAB.TIDSGODK 
        USE-INDEX GODK EXCLUSIVE-LOCK NO-ERROR.     
        IF AVAILABLE GODKANNARTAB THEN DO TRANSACTION:
           DELETE GODKANNARTAB.
        END.      
        FIND FIRST BEREDAONR WHERE BEREDAONR.PERSONALKOD = PERSONALTAB.PERSONALKOD 
        USE-INDEX PERSONALKOD EXCLUSIVE-LOCK NO-ERROR. 
        IF AVAILABLE BEREDAONR THEN DO TRANSACTION:
           DELETE BEREDAONR.
        END.   
        FIND FIRST ANSVAONR WHERE ANSVAONR.PERSONALKOD = PERSONALTAB.PERSONALKOD 
        USE-INDEX PERSONALKOD EXCLUSIVE-LOCK NO-ERROR.   
        IF AVAILABLE ANSVAONR THEN DO TRANSACTION:
           DELETE ANSVAONR.
        END.
        FIND FIRST ANVANDARE WHERE ANVANDARE.PERSONALKOD = PERSONALTAB.PERSONALKOD
        NO-LOCK NO-ERROR.      
        DEFINE QUERY persekq2 FOR PERSEK.
        OPEN QUERY persekq2 FOR EACH PERSEK WHERE PERSEK.ANVANDARE = ANVANDARE.ANVANDARE
        USE-INDEX PERSEK NO-LOCK.      
        DO TRANSACTION:       
           GET FIRST persekq2 EXCLUSIVE-LOCK.
           IF AVAILABLE PERSEK THEN DELETE PERSEK.    
        END.     
        REPEAT:       
           DO TRANSACTION:
              GET NEXT persekq2 EXCLUSIVE-LOCK.
              IF AVAILABLE PERSEK THEN DELETE PERSEK.    
              ELSE LEAVE.            
           END.     
        END.       
        DEFINE QUERY tidsekq2 FOR TIDSEK.
        OPEN QUERY tidsekq2 FOR EACH TIDSEK WHERE TIDSEK.ANVANDARE = ANVANDARE.ANVANDARE
        USE-INDEX TIDSEK NO-LOCK. 
        DO TRANSACTION:       
           GET FIRST tidsekq2 EXCLUSIVE-LOCK.
           IF AVAILABLE TIDSEK THEN DELETE TIDSEK.    
        END.
        REPEAT:  
           DO TRANSACTION:
              GET NEXT tidsekq2 EXCLUSIVE-LOCK.         
              IF AVAILABLE TIDSEK THEN DELETE TIDSEK.    
              ELSE LEAVE.      
           END.         
        END.                                                     
        FIND FIRST ANVANDARE WHERE ANVANDARE.PERSONALKOD = PERSONALTAB.PERSONALKOD
        EXCLUSIVE-LOCK NO-ERROR.   
        IF AVAILABLE ANVANDARE THEN DO TRANSACTION:
           DELETE ANVANDARE.
        END.     
        DO TRANSACTION:
           DELETE PERSONALTAB.
        END.   
     END.   
  END.        
END.  
