OPEN QUERY sumq FOR EACH SUMTID WHERE YEAR(SUMTID.DATUM) = 1999 NO-LOCK.
DO TRANSACTION:
   GET FIRST sumq EXCLUSIVE-LOCK.
   IF AVAILABLE SUMTID THEN DELETE SUMTID.      
END.                                             
REPEAT:
   DO TRANSACTION:
      GET NEXT sumq EXCLUSIVE-LOCK.
      IF AVAILABLE SUMTID THEN DELETE SUMTID. 
      ELSE LEAVE.
   END.    
END.
OPEN QUERY sumtq FOR EACH SUMTIDDAG WHERE YEAR(SUMTIDdag.DATUM) = 1999 NO-LOCK.
DO TRANSACTION:
   GET FIRST sumtq EXCLUSIVE-LOCK.
   IF AVAILABLE SUMTIDDAG THEN DELETE SUMTIDDAG.      
END.                                             
REPEAT:
   DO TRANSACTION:
      GET NEXT sumtq EXCLUSIVE-LOCK.
      IF AVAILABLE SUMTIDDAG THEN DELETE SUMTIDDAG. 
      ELSE LEAVE.
   END.    
END.
