/*xrensMSV.P*/
/*manuellt :
tidslagen
avtal*/
OUTPUT TO c:\LOGRENS.TXT APPEND.
FOR EACH personaltab NO-LOCK:
   FIND FIRST OMRADETAB WHERE OMRADETAB.OMRADE = PERSONALTAB.OMRADE NO-LOCK NO-ERROR.
   FIND FIRST AVDELNING WHERE AVDELNING.AVDELNINGNR = OMRADETAB.AVDELNINGNR NO-LOCK NO-ERROR.
   FIND FIRST JURPERS WHERE JURPERS.JUDID = AVDELNING.POSTANST NO-LOCK NO-ERROR.
   IF JURPERS.VIJUDID =  "ELNÄT" OR JURPERS.VIJUDID =  "SEAB" OR JURPERS.VIJUDID =  "ServaNet" THEN DO:
      /* TIDREGITAB */
      OPEN QUERY tidq FOR EACH TIDREGITAB WHERE TIDREGITAB.PERSONALKOD = personaltab.PERSONALKOD NO-LOCK. 
      DO TRANSACTION:       
         GET FIRST tidq EXCLUSIVE-LOCK.
         IF AVAILABLE TIDREGITAB THEN DELETE TIDREGITAB.    
      END.
      REPEAT:  
         DO TRANSACTION:
            GET NEXT tidq EXCLUSIVE-LOCK.
            IF AVAILABLE TIDREGITAB THEN DELETE TIDREGITAB.    
            ELSE LEAVE.      
         END.         
      END.   
      CLOSE QUERY tidq .
      PUT "TIDREGITAB " personaltab.PERSONALKOD TODAY " " STRING(TIME,"HH:MM:SS") SKIP.

      /* FLEXTID */
      OPEN QUERY flexq FOR EACH FLEXTID WHERE FLEXTID.PERSONALKOD = personaltab.PERSONALKOD NO-LOCK. 
      DO TRANSACTION:       
         GET FIRST flexq EXCLUSIVE-LOCK.
         IF AVAILABLE FLEXTID THEN DELETE FLEXTID.    
      END.
      REPEAT:  
         DO TRANSACTION:
            GET NEXT flexq EXCLUSIVE-LOCK.
            IF AVAILABLE FLEXTID THEN DELETE FLEXTID.    
            ELSE LEAVE.      
         END.         
      END.   
      CLOSE QUERY flexq.
      PUT "FLEXTID " personaltab.PERSONALKOD TODAY " " STRING(TIME,"HH:MM:SS") SKIP.
      /* FLEXDAG */
      OPEN QUERY fldq FOR EACH FLEXDAG WHERE FLEXDAG.PERSONALKOD = personaltab.PERSONALKOD NO-LOCK. 
      DO TRANSACTION:       
         GET FIRST fldq EXCLUSIVE-LOCK.
         IF AVAILABLE FLEXDAG THEN DELETE FLEXDAG.    
      END.
      REPEAT:  
         DO TRANSACTION:
            GET NEXT fldq EXCLUSIVE-LOCK.
            IF AVAILABLE FLEXDAG THEN DELETE FLEXDAG.    
            ELSE LEAVE.      
         END.         
      END.   
      CLOSE QUERY fldq.
      PUT "FLEXDAG " personaltab.PERSONALKOD TODAY " " STRING(TIME,"HH:MM:SS") SKIP.
      /* FLBET */
      OPEN QUERY flbq FOR EACH FLBET WHERE FLBET.PERSONALKOD = personaltab.PERSONALKOD NO-LOCK. 
      DO TRANSACTION:       
         GET FIRST flbq EXCLUSIVE-LOCK.
         IF AVAILABLE FLBET THEN DELETE FLBET.    
      END.
      REPEAT:  
         DO TRANSACTION:
            GET NEXT flbq EXCLUSIVE-LOCK.
            IF AVAILABLE FLBET THEN DELETE FLBET.    
            ELSE LEAVE.      
         END.         
      END.   
      CLOSE QUERY flbq.
      PUT "FLBET " personaltab.PERSONALKOD  TODAY " " STRING(TIME,"HH:MM:SS") SKIP.
      /* FLEXSALDO */
      OPEN QUERY fsalq FOR EACH FLEXSALDO WHERE FLEXSALDO.PERSONALKOD = personaltab.PERSONALKOD NO-LOCK. 
      DO TRANSACTION:       
         GET FIRST fsalq EXCLUSIVE-LOCK.
         IF AVAILABLE FLEXSALDO THEN DELETE FLEXSALDO.    
      END.
      REPEAT:  
         DO TRANSACTION:
            GET NEXT fsalq EXCLUSIVE-LOCK.
            IF AVAILABLE FLEXSALDO THEN DELETE FLEXSALDO.    
            ELSE LEAVE.      
         END.         
      END.   
      CLOSE QUERY fsalq .
      PUT "FLEXSALDO " personaltab.PERSONALKOD TODAY " " STRING(TIME,"HH:MM:SS") SKIP.
      /* FSALDMAN*/
      OPEN QUERY fsalmq FOR EACH FSALDMAN WHERE FSALDMAN.PERSONALKOD = personaltab.PERSONALKOD NO-LOCK. 
      DO TRANSACTION:       
         GET FIRST fsalmq EXCLUSIVE-LOCK.
         IF AVAILABLE FSALDMAN THEN DELETE FSALDMAN.    
      END.
      REPEAT:  
         DO TRANSACTION:
            GET NEXT fsalmq EXCLUSIVE-LOCK.
            IF AVAILABLE FSALDMAN THEN DELETE FSALDMAN.    
            ELSE LEAVE.      
         END.         
      END.   
      CLOSE QUERY fsalmq.
      PUT "FSALDMAN " personaltab.PERSONALKOD TODAY " " STRING(TIME,"HH:MM:SS") SKIP.
      /* FLEXAVT*/
      OPEN QUERY favtq FOR EACH FLEXAVT WHERE FLEXAVT.PERSONALKOD = personaltab.PERSONALKOD NO-LOCK. 
      DO TRANSACTION:       
         GET FIRST favtq EXCLUSIVE-LOCK.
         IF AVAILABLE FLEXAVT THEN DELETE FLEXAVT.    
      END.
      REPEAT:  
         DO TRANSACTION:
            GET NEXT favtq EXCLUSIVE-LOCK.
            IF AVAILABLE FLEXAVT THEN DELETE FLEXAVT.    
            ELSE LEAVE.      
         END.         
      END.   
      CLOSE QUERY favtq.
      PUT "FLEXAVT " personaltab.PERSONALKOD TODAY " " STRING(TIME,"HH:MM:SS") SKIP.
      /* GODKOLL */
      OPEN QUERY godq FOR EACH GODKOLL WHERE GODKOLL.PERSONALKOD = personaltab.PERSONALKOD NO-LOCK. 
      DO TRANSACTION:       
         GET FIRST godq EXCLUSIVE-LOCK.
         IF AVAILABLE GODKOLL THEN DELETE GODKOLL.    
      END.
      REPEAT:  
         DO TRANSACTION:
            GET NEXT godq EXCLUSIVE-LOCK.
            IF AVAILABLE GODKOLL THEN DELETE GODKOLL.    
            ELSE LEAVE.      
         END.         
      END.   
      CLOSE QUERY godq.
      PUT "GODKOLL " personaltab.PERSONALKOD TODAY " " STRING(TIME,"HH:MM:SS") SKIP.
      /* SUMTIDDAG */
      OPEN QUERY sumq FOR EACH SUMTIDDAG WHERE SUMTIDDAG.PERSONALKOD = personaltab.PERSONALKOD NO-LOCK. 
      DO TRANSACTION:       
         GET FIRST sumq EXCLUSIVE-LOCK.
         IF AVAILABLE SUMTIDDAG THEN DELETE SUMTIDDAG.    
      END.
      REPEAT:  
         DO TRANSACTION:
            GET NEXT sumq EXCLUSIVE-LOCK.
            IF AVAILABLE SUMTIDDAG THEN DELETE SUMTIDDAG.    
            ELSE LEAVE.      
         END.         
      END.   
      CLOSE QUERY sumq .
      PUT "SUMTIDDAG " personaltab.PERSONALKOD TODAY " " STRING(TIME,"HH:MM:SS") SKIP.
      FIND FIRST ANVANDARE WHERE ANVANDARE.PERSONALKOD = personaltab.PERSONALKOD NO-LOCK NO-ERROR.
      IF AVAILABLE ANVANDARE  THEN DO:
         /*PERSEK*/
         OPEN QUERY persekq FOR EACH PERSEK WHERE PERSEK.ANVANDARE = ANVANDARE.ANVANDARE
         USE-INDEX PERSEK NO-LOCK. 
         DO TRANSACTION:       
            GET FIRST persekq EXCLUSIVE-LOCK.
            IF AVAILABLE PERSEK THEN DELETE PERSEK.    
         END.
         REPEAT:  
            DO TRANSACTION:
               GET NEXT persekq EXCLUSIVE-LOCK.
               IF AVAILABLE PERSEK THEN DELETE PERSEK.    
               ELSE LEAVE.      
            END.         
         END.   
         CLOSE QUERY persekq.
         PUT "PERSEK " personaltab.PERSONALKOD TODAY " " STRING(TIME,"HH:MM:SS") SKIP.
         /*TIDSEK*/
         OPEN QUERY tidsekq FOR EACH TIDSEK WHERE TIDSEK.ANVANDARE = ANVANDARE.ANVANDARE
         USE-INDEX TIDSEK NO-LOCK. 
         DO TRANSACTION:       
            GET FIRST tidsekq EXCLUSIVE-LOCK.
            IF AVAILABLE TIDSEK THEN DELETE TIDSEK.    
         END.
         REPEAT:  
            DO TRANSACTION:
               GET NEXT tidsekq EXCLUSIVE-LOCK.
               IF AVAILABLE TIDSEK THEN DELETE TIDSEK.    
               ELSE LEAVE.      
            END.         
         END.   
         CLOSE QUERY tidsekq .
         PUT "TIDSEK " personaltab.PERSONALKOD TODAY " " STRING(TIME,"HH:MM:SS") SKIP.
      END.
      /*PERSONALPRIS*/
      OPEN QUERY pprisq FOR EACH PERSONALPRIS WHERE PERSONALPRIS.PERSONALKOD = PERSONALTAB.PERSONALKOD NO-LOCK. 
      DO TRANSACTION:       
         GET FIRST pprisq EXCLUSIVE-LOCK.
         IF AVAILABLE PERSONALPRIS THEN DELETE PERSONALPRIS.    
      END.
      REPEAT:  
         DO TRANSACTION:
            GET NEXT pprisq EXCLUSIVE-LOCK.
            IF AVAILABLE PERSONALPRIS THEN DELETE PERSONALPRIS.    
            ELSE LEAVE.      
         END.         
      END.   
      CLOSE QUERY pprisq.
      PUT "PERSONALPRIS " personaltab.PERSONALKOD TODAY " " STRING(TIME,"HH:MM:SS") SKIP.
      /*TIMKOSTNADSTAB*/
      OPEN QUERY timq FOR EACH TIMKOSTNADSTAB WHERE TIMKOSTNADSTAB.PERSONALKOD = PERSONALTAB.PERSONALKOD NO-LOCK. 
      DO TRANSACTION:       
         GET FIRST timq EXCLUSIVE-LOCK.
         IF AVAILABLE TIMKOSTNADSTAB THEN DELETE TIMKOSTNADSTAB.    
      END.
      REPEAT:  
         DO TRANSACTION:
            GET NEXT timq EXCLUSIVE-LOCK.
            IF AVAILABLE TIMKOSTNADSTAB THEN DELETE TIMKOSTNADSTAB.    
            ELSE LEAVE.      
         END.         
      END.         
      CLOSE QUERY timq.
      PUT "TIMKOSTNADSTAB " personaltab.PERSONALKOD TODAY " " STRING(TIME,"HH:MM:SS") SKIP.
      /*VECKOARBAV*/
      OPEN QUERY vaavq FOR EACH VECKOARBAV WHERE VECKOARBAV.PERSONALKOD = PERSONALTAB.PERSONALKOD NO-LOCK. 
      DO TRANSACTION:       
         GET FIRST vaavq EXCLUSIVE-LOCK.
         IF AVAILABLE VECKOARBAV THEN DELETE VECKOARBAV.    
      END.
      REPEAT:  
         DO TRANSACTION:
            GET NEXT vaavq EXCLUSIVE-LOCK.
            IF AVAILABLE VECKOARBAV THEN DELETE VECKOARBAV.    
            ELSE LEAVE.      
         END.         
      END.
      CLOSE QUERY vaavq.
      PUT "VECKOARBAV " personaltab.PERSONALKOD TODAY " " STRING(TIME,"HH:MM:SS") SKIP.
      
      /*RULLPERS*/
      OPEN QUERY rullpq FOR EACH RULLPERS WHERE RULLPERS.PERSONALKOD = PERSONALTAB.PERSONALKOD NO-LOCK. 
      DO TRANSACTION:       
         GET FIRST rullpq EXCLUSIVE-LOCK.
         IF AVAILABLE RULLPERS THEN DELETE RULLPERS.    
      END.
      REPEAT:  
         DO TRANSACTION:
            GET NEXT rullpq EXCLUSIVE-LOCK.
            IF AVAILABLE RULLPERS THEN DELETE RULLPERS.    
            ELSE LEAVE.      
         END.         
      END.
      CLOSE QUERY rullpq.
      PUT "RULLPERS " personaltab.PERSONALKOD TODAY " " STRING(TIME,"HH:MM:SS") SKIP.
      /*ANVAOTAB */
      DO TRANSACTION:       
         FOR EACH ANVAOTAB WHERE ANVAOTAB.ANVANDARE BEGINS PERSONALTAB.PERSONALKOD EXCLUSIVE-LOCK:
            DELETE ANVAOTAB.
         END.
         FOR EACH ANVAOTAB WHERE ANVAOTAB.ANVANDARE BEGINS ANVANDARE.ANVANDARE EXCLUSIVE-LOCK:
            DELETE ANVAOTAB .
         END.
      END.
      
      /* ANVANDARE */
      DO TRANSACTION:
         FIND CURRENT ANVANDARE EXCLUSIVE-LOCK NO-ERROR.
         IF AVAILABLE ANVANDARE THEN DO:
            DELETE ANVANDARE.      
         END.
      END.
      DO TRANSACTION:
         FIND FIRST BEREDAONR WHERE BEREDAONR.PERSONALKOD = PERSONALTAB.PERSONALKOD 
         USE-INDEX PERSONALKOD EXCLUSIVE-LOCK NO-ERROR. 
         IF AVAILABLE BEREDAONR THEN DO:
            DELETE BEREDAONR.
         END.   
         FIND FIRST ANSVAONR WHERE ANSVAONR.PERSONALKOD = PERSONALTAB.PERSONALKOD 
         USE-INDEX PERSONALKOD EXCLUSIVE-LOCK NO-ERROR.   
         IF AVAILABLE ANSVAONR THEN DO:
            DELETE ANSVAONR.
         END.
         FIND FIRST EXTRADATA WHERE EXTRADATA.HUVUDCH = PERSONALTAB.PERSONALKOD
         AND EXTRADATA.PROGRAM = "OTBEORD" USE-INDEX HCH EXCLUSIVE-LOCK NO-ERROR.   
         IF AVAILABLE EXTRADATA THEN DO:
            DELETE EXTRADATA.
         END.
         OPEN QUERY ppq FOR EACH PERSONALPROJEKT WHERE 
         PERSONALPROJEKT.PERSONALKOD = PERSONALTAB.PERSONALKOD NO-LOCK.
         GET FIRST ppq EXCLUSIVE-LOCK.
         DO WHILE AVAILABLE(PERSONALPROJEKT):
            DELETE PERSONALPROJEKT.
            GET NEXT ppq EXCLUSIVE-LOCK.
         END.   
         
      END.
      PUT "ANVANDARE" TODAY " " STRING(TIME,"HH:MM:SS") SKIP.

   END.
END.

/*RULLSCHEMA*/
OPEN QUERY rullsq FOR EACH RULLSCHEMA  NO-LOCK. 
DO TRANSACTION:       
   GET FIRST rullsq EXCLUSIVE-LOCK.
   IF AVAILABLE RULLSCHEMA THEN DELETE RULLSCHEMA.    
END.
REPEAT:  
   DO TRANSACTION:
      GET NEXT rullsq EXCLUSIVE-LOCK.
      IF AVAILABLE RULLSCHEMA THEN DELETE RULLSCHEMA.    
      ELSE LEAVE.      
   END.         
END.
CLOSE QUERY rullsq.
PUT "RULLSCHEMA " TODAY " " STRING(TIME,"HH:MM:SS") SKIP.
/*RULLVECKO*/
OPEN QUERY rullvq FOR EACH RULLVECKO  NO-LOCK. 
DO TRANSACTION:       
   GET FIRST rullvq EXCLUSIVE-LOCK.
   IF AVAILABLE RULLVECKO THEN DELETE RULLVECKO.    
END.
REPEAT:  
   DO TRANSACTION:
      GET NEXT rullvq EXCLUSIVE-LOCK.
      IF AVAILABLE RULLVECKO THEN DELETE RULLVECKO.    
      ELSE LEAVE.      
   END.         
END.
CLOSE QUERY rullvq.
PUT "RULLVECKO " TODAY " " STRING(TIME,"HH:MM:SS") SKIP.

OPEN QUERY pq FOR EACH PERSONALTAB NO-LOCK. 
DO TRANSACTION:       
   GET FIRST pq EXCLUSIVE-LOCK.
   IF AVAILABLE PERSONALTAB THEN DO:
      FIND FIRST OMRADETAB WHERE OMRADETAB.OMRADE = PERSONALTAB.OMRADE NO-LOCK NO-ERROR.
      FIND FIRST AVDELNING WHERE AVDELNING.AVDELNINGNR = OMRADETAB.AVDELNINGNR NO-LOCK NO-ERROR.
      FIND FIRST JURPERS WHERE JURPERS.JUDID = AVDELNING.POSTANST NO-LOCK NO-ERROR.
      IF JURPERS.VIJUDID =  "ELNÄT" OR JURPERS.VIJUDID =  "SEAB" OR JURPERS.VIJUDID =  "ServaNet" THEN DO:
         FIND FIRST GODKANNARTAB WHERE GODKANNARTAB.PERSONALKOD = PERSONALTAB.TIDSGODK 
         USE-INDEX GODK EXCLUSIVE-LOCK NO-ERROR.     
         IF AVAILABLE GODKANNARTAB THEN DO:
            DELETE GODKANNARTAB.
         END.
         DELETE PERSONALTAB.
      END.
   END.
END.
REPEAT:  
   DO TRANSACTION:
      GET NEXT pq EXCLUSIVE-LOCK.
      IF AVAILABLE PERSONALTAB THEN DO:
         FIND FIRST OMRADETAB WHERE OMRADETAB.OMRADE = PERSONALTAB.OMRADE NO-LOCK NO-ERROR.
         FIND FIRST AVDELNING WHERE AVDELNING.AVDELNINGNR = OMRADETAB.AVDELNINGNR NO-LOCK NO-ERROR.
         FIND FIRST JURPERS WHERE JURPERS.JUDID = AVDELNING.POSTANST NO-LOCK NO-ERROR.
         IF JURPERS.VIJUDID =  "ELNÄT" OR JURPERS.VIJUDID =  "SEAB" OR JURPERS.VIJUDID =  "ServaNet" THEN DO:
            FIND FIRST GODKANNARTAB WHERE GODKANNARTAB.PERSONALKOD = PERSONALTAB.TIDSGODK 
            USE-INDEX GODK EXCLUSIVE-LOCK NO-ERROR.     
            IF AVAILABLE GODKANNARTAB THEN DO:
               DELETE GODKANNARTAB.
            END.
            DELETE PERSONALTAB.
         END.
      END.   
      ELSE LEAVE.      
   END.         
END.  
PUT "PERSONALTAB" TODAY " " STRING(TIME,"HH:MM:SS") SKIP.


 
FOR EACH AONRTAB NO-LOCK:
   FIND FIRST OMRADETAB WHERE OMRADETAB.OMRADE = AONRTAB.OMRADE NO-LOCK NO-ERROR.
   FIND FIRST AVDELNING WHERE AVDELNING.AVDELNINGNR = OMRADETAB.AVDELNINGNR NO-LOCK NO-ERROR.
   FIND FIRST JURPERS WHERE JURPERS.JUDID = AVDELNING.POSTANST NO-LOCK NO-ERROR.
   IF JURPERS.VIJUDID =  "ELNÄT" OR JURPERS.VIJUDID =  "SEAB" OR JURPERS.VIJUDID =  "ServaNet" THEN DO:
      /* AONRKONTKOD */
      OPEN QUERY aokq FOR EACH AONRKONTKOD WHERE AONRKONTKOD.AONR = AONRTAB.AONR AND AONRKONTKOD.DELNR = AONRTAB.DELNR NO-LOCK. 
      DO TRANSACTION:       
         GET FIRST aokq EXCLUSIVE-LOCK.
         IF AVAILABLE AONRKONTKOD THEN DELETE AONRKONTKOD.    
      END.
      REPEAT:  
         DO TRANSACTION:
            GET NEXT aokq EXCLUSIVE-LOCK.
            IF AVAILABLE AONRKONTKOD THEN DELETE AONRKONTKOD.    
            ELSE LEAVE.      
         END.         
      END.   
      CLOSE QUERY aokq .
      PUT "AONRKONTKOD" TODAY " " STRING(TIME,"HH:MM:SS") SKIP.
      /* AONRTIDLAGE */
      OPEN QUERY aotq FOR EACH AONRTIDLAGE WHERE AONRTIDLAGE.AONR = AONRTAB.AONR AND AONRTIDLAGE.DELNR = AONRTAB.DELNR NO-LOCK. 
      DO TRANSACTION:       
         GET FIRST aotq EXCLUSIVE-LOCK.
         IF AVAILABLE AONRTIDLAGE THEN DELETE AONRTIDLAGE.    
      END.
      REPEAT:  
         DO TRANSACTION:
            GET NEXT aotq EXCLUSIVE-LOCK.
            IF AVAILABLE AONRTIDLAGE THEN DELETE AONRTIDLAGE.    
            ELSE LEAVE.      
         END.         
      END.   
      CLOSE QUERY aotq.
      PUT "AONRTIDLAGE" TODAY " " STRING(TIME,"HH:MM:SS") SKIP.
   END.   
END.
/* AONRTAB */
OPEN QUERY aoq FOR EACH AONRTAB WHERE AONRTAB.OMRADE NE "" NO-LOCK. 
DO TRANSACTION:       
   GET FIRST aoq EXCLUSIVE-LOCK.
   IF AVAILABLE AONRTAB THEN DELETE AONRTAB.    
END.
REPEAT:  
   DO TRANSACTION:
      GET NEXT aoq EXCLUSIVE-LOCK.
      IF AVAILABLE AONRTAB THEN DELETE AONRTAB.    
      ELSE LEAVE.      
   END.         
END.
CLOSE QUERY aoq.
PUT "AONRTAB" TODAY " " STRING(TIME,"HH:MM:SS") SKIP.

/* PLANNRTAB */
OPEN QUERY planq FOR EACH PLANNRTAB  NO-LOCK. 
DO TRANSACTION:       
   GET FIRST planq EXCLUSIVE-LOCK.
   IF AVAILABLE PLANNRTAB THEN DELETE PLANNRTAB.    
END.
REPEAT:  
   DO TRANSACTION:
      GET NEXT planq EXCLUSIVE-LOCK.
      IF AVAILABLE PLANNRTAB THEN DELETE PLANNRTAB.    
      ELSE LEAVE.      
   END.         
END.
CLOSE QUERY planq.
PUT "PLANNRTAB" TODAY " " STRING(TIME,"HH:MM:SS") SKIP.
 /* KONTO */
OPEN QUERY kontoq FOR EACH KONTO NO-LOCK. 
DO TRANSACTION:       
   GET FIRST kontoq EXCLUSIVE-LOCK.
   IF AVAILABLE KONTO THEN DO: 
      FIND FIRST JURPERS WHERE JURPERS.JUDID = KONTO.JUDID NO-LOCK NO-ERROR.
      IF AVAILABLE JURPERS THEN DO:
         IF JURPERS.VIJUDID =  "ELNÄT" OR JURPERS.VIJUDID =  "SEAB" OR JURPERS.VIJUDID =  "ServaNet" THEN DO:
            DELETE KONTO.    
         END.
      END.
      ELSE IF KONTO.JUDID = ""  THEN DELETE KONTO.   
   END.
END.
REPEAT:  
   DO TRANSACTION:
      GET NEXT kontoq EXCLUSIVE-LOCK.
      IF AVAILABLE KONTO THEN DO: 
         FIND FIRST JURPERS WHERE JURPERS.JUDID = KONTO.JUDID NO-LOCK NO-ERROR.
         IF AVAILABLE JURPERS THEN DO:
            IF JURPERS.VIJUDID =  "ELNÄT" OR JURPERS.VIJUDID =  "SEAB" OR JURPERS.VIJUDID =  "ServaNet" THEN DO:
               DELETE KONTO.    
            END.
         END.
         ELSE IF KONTO.JUDID = ""  THEN DELETE KONTO.   
      END.
      ELSE LEAVE.      
   END.         
END.   
CLOSE QUERY kontoq.
PUT "KONTO" TODAY " " STRING(TIME,"HH:MM:SS") SKIP.
/* KALKSPEC */
OPEN QUERY ksq FOR EACH KALKSPEC  NO-LOCK. 
DO TRANSACTION:       
   GET FIRST ksq EXCLUSIVE-LOCK.
   IF AVAILABLE KALKSPEC THEN DELETE KALKSPEC.    
END.
REPEAT:  
   DO TRANSACTION:
      GET NEXT ksq EXCLUSIVE-LOCK.
      IF AVAILABLE KALKSPEC THEN DELETE KALKSPEC.    
      ELSE LEAVE.      
   END.         
END.
CLOSE QUERY ksq.
PUT "KALKSPEC" TODAY " " STRING(TIME,"HH:MM:SS") SKIP.
/* FASTSPEC */
OPEN QUERY fsq FOR EACH FASTSPEC  NO-LOCK. 
DO TRANSACTION:       
   GET FIRST fsq EXCLUSIVE-LOCK.
   IF AVAILABLE FASTSPEC THEN DELETE FASTSPEC.    
END.
REPEAT:  
   DO TRANSACTION:
      GET NEXT fsq EXCLUSIVE-LOCK.
      IF AVAILABLE FASTSPEC THEN DELETE FASTSPEC.    
      ELSE LEAVE.      
   END.         
END.
CLOSE QUERY fsq.
PUT "FASTSPEC" TODAY " " STRING(TIME,"HH:MM:SS") SKIP.
/* KALKAONR */
OPEN QUERY kaq FOR EACH KALKAONR  NO-LOCK. 
DO TRANSACTION:       
   GET FIRST kaq EXCLUSIVE-LOCK.
   IF AVAILABLE KALKAONR THEN DELETE KALKAONR.    
END.
REPEAT:  
   DO TRANSACTION:
      GET NEXT kaq EXCLUSIVE-LOCK.
      IF AVAILABLE KALKAONR THEN DELETE KALKAONR.    
      ELSE LEAVE.      
   END.         
END.
CLOSE QUERY kaq.
PUT "KALKAONR" TODAY " " STRING(TIME,"HH:MM:SS") SKIP.
/* BEREDNING */
OPEN QUERY berq FOR EACH BEREDNING  NO-LOCK. 
DO TRANSACTION:       
   GET FIRST berq EXCLUSIVE-LOCK.
   IF AVAILABLE BEREDNING THEN DELETE BEREDNING.    
END.
REPEAT:  
   DO TRANSACTION:
      GET NEXT berq EXCLUSIVE-LOCK.
      IF AVAILABLE BEREDNING THEN DELETE BEREDNING.    
      ELSE LEAVE.      
   END.         
END.
CLOSE QUERY berq .
PUT "BEREDNING" TODAY " " STRING(TIME,"HH:MM:SS") SKIP.
/* BERMTRL */
OPEN QUERY bmtq FOR EACH BERMTRL  NO-LOCK. 
DO TRANSACTION:       
   GET FIRST bmtq EXCLUSIVE-LOCK.
   IF AVAILABLE BERMTRL THEN DELETE BERMTRL.    
END.
REPEAT:  
   DO TRANSACTION:
      GET NEXT bmtq EXCLUSIVE-LOCK.
      IF AVAILABLE BERMTRL THEN DELETE BERMTRL.    
      ELSE LEAVE.      
   END.         
END.
CLOSE QUERY bmtq.
PUT "BERMTRL" TODAY " " STRING(TIME,"HH:MM:SS") SKIP.
/* arbart */
OPEN QUERY aaq FOR EACH arbetsart  NO-LOCK. 
DO TRANSACTION:       
   GET FIRST aaq EXCLUSIVE-LOCK.
   IF AVAILABLE arbetsart THEN DELETE arbetsart.    
END.
REPEAT:  
   DO TRANSACTION:
      GET NEXT aaq EXCLUSIVE-LOCK.
      IF AVAILABLE arbetsart THEN DELETE arbetsart.    
      ELSE LEAVE.      
   END.         
END.
CLOSE QUERY aaq .
PUT "arbetsart" TODAY " " STRING(TIME,"HH:MM:SS") SKIP.
/* prioritet */
OPEN QUERY priq FOR EACH prioritet  NO-LOCK. 
DO TRANSACTION:       
   GET FIRST priq.
   IF AVAILABLE prioritet THEN DELETE prioritet.    
END.
REPEAT:  
   DO TRANSACTION:
      GET NEXT priq EXCLUSIVE-LOCK.
      IF AVAILABLE prioritet THEN DELETE prioritet.    
      ELSE LEAVE.      
   END.         
END.
CLOSE QUERY priq.
PUT "prioritet" TODAY " " STRING(TIME,"HH:MM:SS") SKIP.
/* kontostrang */
OPEN QUERY kstrq FOR EACH kontostrang  NO-LOCK. 
DO TRANSACTION:       
   GET FIRST kstrq.
   IF AVAILABLE prioritet THEN DELETE kontostrang.    
END.
REPEAT:  
   DO TRANSACTION:
      GET NEXT kstrq EXCLUSIVE-LOCK.
      IF AVAILABLE kontostrang THEN DELETE kontostrang.    
      ELSE LEAVE.      
   END.         
END.
CLOSE QUERY kstrq.
PUT "kontostrang" TODAY " " STRING(TIME,"HH:MM:SS") SKIP.

/* omradetab */
OPEN QUERY omrq FOR EACH omradetab  NO-LOCK. 
DO TRANSACTION:       
   GET FIRST omrq EXCLUSIVE-LOCK.
   IF AVAILABLE omradetab THEN DO: 
      FIND FIRST AVDELNING WHERE AVDELNING.AVDELNINGNR = OMRADETAB.AVDELNINGNR NO-LOCK NO-ERROR.
      FIND FIRST JURPERS WHERE JURPERS.JUDID = AVDELNING.POSTANST NO-LOCK NO-ERROR.
      IF AVAILABLE JURPERS THEN DO:
         IF JURPERS.VIJUDID =  "ELNÄT" OR JURPERS.VIJUDID =  "SEAB" OR JURPERS.VIJUDID =  "ServaNet" THEN DO:
            DELETE omradetab.    
         END.
      END.                  
   END.
END.
REPEAT:  
   DO TRANSACTION:
      GET NEXT omrq EXCLUSIVE-LOCK.
      IF AVAILABLE omradetab THEN DO: 
         FIND FIRST AVDELNING WHERE AVDELNING.AVDELNINGNR = OMRADETAB.AVDELNINGNR NO-LOCK NO-ERROR.
         FIND FIRST JURPERS WHERE JURPERS.JUDID = AVDELNING.POSTANST NO-LOCK NO-ERROR.
         IF AVAILABLE JURPERS THEN DO:
            IF JURPERS.VIJUDID =  "ELNÄT" OR JURPERS.VIJUDID =  "SEAB" OR JURPERS.VIJUDID =  "ServaNet" THEN DO:
               DELETE omradetab.    
            END.
         END.                  
      END.
      ELSE LEAVE.      
   END.         
END.
CLOSE QUERY omrq.
PUT "omradetab" TODAY " " STRING(TIME,"HH:MM:SS") SKIP.

OUTPUT CLOSE.
/* bestallare

*/


