/*xrensMSV2.P*/
/*manuellt :
tidslagen
avtal*/
FOR EACH personaltab NO-LOCK:
   FIND FIRST OMRADETAB WHERE OMRADETAB.OMRADE = PERSONALTAB.OMRADE NO-LOCK NO-ERROR.
   FIND FIRST AVDELNING WHERE AVDELNING.AVDELNINGNR = OMRADETAB.AVDELNINGNR NO-LOCK NO-ERROR.
   FIND FIRST JURPERS WHERE JURPERS.JUDID = AVDELNING.POSTANST NO-LOCK NO-ERROR.
   IF JURPERS.VIJUDID =  "svab" THEN DO:
      /* TIDREGITAB */
      OPEN QUERY tidq FOR EACH TIDREGITAB WHERE TIDREGITAB.PERSONALKOD = personaltab.PERSONALKOD AND TIDREGITAB.DATUM GE 10/01/2009 AND TIDREGITAB.DATUM < 10/27/2009  NO-LOCK. 
      DO TRANSACTION:       
         GET FIRST tidq EXCLUSIVE-LOCK.
         IF AVAILABLE TIDREGITAB THEN DELETE TIDREGITAB.    
      END.
      REPEAT:  
         DO TRANSACTION:
            GET NEXT tidq EXCLUSIVE-LOCK.
            IF AVAILABLE TIDREGITAB THEN DELETE TIDREGITAB.    
            ELSE LEAVE.      
         END.         
      END.   
      CLOSE QUERY tidq.
      /* FLEXTID */
      OPEN QUERY flexq FOR EACH FLEXTID WHERE FLEXTID.PERSONALKOD = personaltab.PERSONALKOD AND FLEXTID.DATUM GE 10/01/2009 AND FLEXTID.DATUM < 10/27/2009 NO-LOCK. 
      DO TRANSACTION:       
         GET FIRST flexq EXCLUSIVE-LOCK.
         IF AVAILABLE FLEXTID THEN DELETE FLEXTID.    
      END.
      REPEAT:  
         DO TRANSACTION:
            GET NEXT flexq EXCLUSIVE-LOCK.
            IF AVAILABLE FLEXTID THEN DELETE FLEXTID.    
            ELSE LEAVE.      
         END.         
      END.   
      CLOSE QUERY flexq.
      /* FLEXDAG */
      OPEN QUERY fldq FOR EACH FLEXDAG WHERE FLEXDAG.PERSONALKOD = personaltab.PERSONALKOD AND FLEXDAG.DATUM GE 10/01/2009 AND FLEXDAG.DATUM < 10/27/2009 NO-LOCK. 
      DO TRANSACTION:       
         GET FIRST fldq EXCLUSIVE-LOCK.
         IF AVAILABLE FLEXDAG THEN DELETE FLEXDAG.    
      END.
      REPEAT:  
         DO TRANSACTION:
            GET NEXT fldq EXCLUSIVE-LOCK.
            IF AVAILABLE FLEXDAG THEN DELETE FLEXDAG.    
            ELSE LEAVE.      
         END.         
      END.
      CLOSE QUERY fldq.
      /* FLBET */
      OPEN QUERY flbq FOR EACH FLBET WHERE FLBET.PERSONALKOD = personaltab.PERSONALKOD AND FLBET.DATUM GE 10/01/2009 NO-LOCK. 
      DO TRANSACTION:       
         GET FIRST flbq EXCLUSIVE-LOCK.
         IF AVAILABLE FLBET THEN DELETE FLBET.    
      END.
      REPEAT:  
         DO TRANSACTION:
            GET NEXT flbq EXCLUSIVE-LOCK.
            IF AVAILABLE FLBET THEN DELETE FLBET.    
            ELSE LEAVE.      
         END.         
      END.   
      CLOSE QUERY flbq.
      /* FLEXSALDO */
      OPEN QUERY fsalq FOR EACH FLEXSALDO WHERE FLEXSALDO.PERSONALKOD = personaltab.PERSONALKOD NO-LOCK. 
      DO TRANSACTION:       
         GET FIRST fsalq EXCLUSIVE-LOCK.
         IF AVAILABLE FLEXSALDO THEN DELETE FLEXSALDO.    
      END.
      REPEAT:  
         DO TRANSACTION:
            GET NEXT fsalq EXCLUSIVE-LOCK.
            IF AVAILABLE FLEXSALDO THEN DELETE FLEXSALDO.    
            ELSE LEAVE.      
         END.         
      END.   
      CLOSE QUERY fsalq.
      
      /* SUMTIDDAG */
      OPEN QUERY sumq FOR EACH SUMTIDDAG WHERE SUMTIDDAG.PERSONALKOD = personaltab.PERSONALKOD AND SUMTIDDAG.DATUM GE 10/01/2009  NO-LOCK. 
      DO TRANSACTION:       
         GET FIRST sumq EXCLUSIVE-LOCK.
         IF AVAILABLE SUMTIDDAG THEN DELETE SUMTIDDAG.    
      END.
      REPEAT:  
         DO TRANSACTION:
            GET NEXT sumq EXCLUSIVE-LOCK.
            IF AVAILABLE SUMTIDDAG THEN DELETE SUMTIDDAG.    
            ELSE LEAVE.      
         END.         
      END.   
      CLOSE QUERY sumq.
      /*VECKOARBAV*/
      OPEN QUERY vaavq FOR EACH VECKOARBAV WHERE VECKOARBAV.PERSONALKOD = PERSONALTAB.PERSONALKOD AND VECKOARBAV.VECKONUMMER GE 200941 NO-LOCK. 
      DO TRANSACTION:       
         GET FIRST vaavq EXCLUSIVE-LOCK.
         IF AVAILABLE VECKOARBAV THEN DELETE VECKOARBAV.    
      END.
      REPEAT:  
         DO TRANSACTION:
            GET NEXT vaavq EXCLUSIVE-LOCK.
            IF AVAILABLE VECKOARBAV THEN DELETE VECKOARBAV.    
            ELSE LEAVE.      
         END.         
      END.
      CLOSE QUERY vaavq.

   END.
END.


 


