DEFINE BUFFER SATSBUFF FOR SATS.
/* \\BEREDNING1\DELAD\KLIENT\PRO9\KALLE.TXT */
OUTPUT TO \\BEREDNING1\DELAD\KLIENT\PRO9\KALLE.TXT.
OPEN QUERY SQ FOR EACH SATS WHERE SATS.LEVKOD = "1" AND 
SATS.SATS = TRUE NO-LOCK.
GET FIRST SQ NO-LOCK.
DO  WHILE AVAILABLE(SATS):
   IF SATS.KOD BEGINS "0" OR SATS.KOD BEGINS "1" OR SATS.KOD BEGINS "7" OR
   SATS.KOD BEGINS "9" THEN DO:
       OPEN QUERY DQ FOR EACH SATSBUFF WHERE SATSBUFF.KOD = SATS.KOD AND
       SATSBUFF.SATS = FALSE AND SATSBUFF.LEVKOD = "1" NO-LOCK.
       GET FIRST DQ NO-LOCK.
       DO WHILE AVAILABLE(SATSBUFF):
          FIND FIRST MTRL WHERE MTRL.ENR = SATSBUFF.ENR2 AND MTRL.LEVKOD = "1" AND
          MTRL.KALKNR = 0 NO-LOCK NO-ERROR.
          IF NOT AVAILABLE MTRL THEN DO:
             PUT UNFORMATTED SATSBUFF.KOD + " " + SATSBUFF.BENAMNING + " " + SATSBUFF.ENR2 + " " + SATSBUFF.BENAMNING2 SKIP.
          END.
          GET NEXT DQ NO-LOCK.
       END.
       CLOSE QUERY DQ.
   END.
   GET NEXT SQ NO-LOCK.
END.
