/*XSEMTILLW.P*/
/*DEFINE VARIABLE sdagar AS DECIMAL NO-UNDO.*/
DEFINE VARIABLE stim AS DECIMAL NO-UNDO.
DEFINE VARIABLE hjrak AS INTEGER NO-UNDO.
/*DEFINE VARIABLE totid  AS DECIMAL NO-UNDO.*/
DEFINE TEMP-TABLE stillagg 
   FIELD PERSONALKOD LIKE TIDREGITAB.PERSONALKOD
   FIELD DATUM LIKE TIDREGITAB.DATUM
   FIELD AONR LIKE TIDREGITAB.AONR
   FIELD DELNR LIKE TIDREGITAB.DELNR
   FIELD TOTALT LIKE TIDREGITAB.TOTALT 
   FIELD HELDAG AS LOGICAL
   INDEX PKOD IS PRIMARY DATUM ASCENDING. 
DEFINE BUFFER persbuff FOR PERSONALTAB.
DEFINE BUFFER tbuff FOR TIDREGITAB.
DEFINE VARIABLE pkod AS CHARACTER NO-UNDO.
DEFINE VARIABLE hjdatum AS DATE NO-UNDO.
DEFINE VARIABLE sdagar AS DECIMAL NO-UNDO.
/*DEFINE INPUT PARAMETER pkod AS CHARACTER NO-UNDO.
DEFINE INPUT PARAMETER hjdatum AS DATE NO-UNDO.
DEFINE OUTPUT PARAMETER sdagar AS DECIMAL NO-UNDO.*/


FUNCTION klock100 RETURNS DECIMAL
  ( INPUT ber60 AS DECIMAL ):
/*------------------------------------------------------------------------------
  Purpose:  
    Notes:  
------------------------------------------------------------------------------*/

  RETURN  (TRUNCATE(ber60,0) * 3600 + (ber60 - TRUNCATE(ber60,0)) * 100 * 60) / 3600.

END FUNCTION.
pkod = "".
hjdatum = 04/01/2005.
FIND FIRST PERSONALTAB WHERE PERSONALTAB.PERSONALKOD = pkod NO-LOCK NO-ERROR.
IF MONTH(hjdatum) = 12 THEN DO:         
   OPEN QUERY semq FOR EACH TIDREGITAB WHERE TIDREGITAB.PERSONALKOD = PERSONALTAB.PERSONALKOD   
   AND TIDREGITAB.PRISTYP = "FRÅNVARO." 
   AND TIDREGITAB.TIDLOG = TRUE
   AND YEAR(TIDREGITAB.DATUM) = YEAR(hjdatum)
   AND MONTH(TIDREGITAB.DATUM) > 5 AND MONTH(TIDREGITAB.DATUM) < 9 NO-LOCK.
   GET FIRST semq NO-LOCK.   
   DO WHILE AVAILABLE(TIDREGITAB):           
      IF TIDREGITAB.AONR = "150" OR TIDREGITAB.AONR = "170" OR TIDREGITAB.AONR = "160" OR TIDREGITAB.AONR = "120"
      OR TIDREGITAB.AONR = "121" OR TIDREGITAB.AONR = "130" OR TIDREGITAB.AONR = "119" 
      OR TIDREGITAB.AONR = "155" THEN DO:         
         CREATE stillagg.   
         ASSIGN
         stillagg.PERSONALKOD = TIDREGITAB.PERSONALKOD
         stillagg.DATUM = TIDREGITAB.DATUM
         stillagg.AONR  = TIDREGITAB.AONR 
         stillagg.DELNR = TIDREGITAB.DELNR
         stillagg.TOTALT = TIDREGITAB.TOTALT.
         FIND FIRST tbuff  WHERE tbuff.PERSONALKOD = TIDREGITAB.PERSONALKOD   
         AND tbuff.DATUM = TIDREGITAB.DATUM AND tbuff.AONR NE TIDREGITAB.AONR    
         AND tbuff.TIDLOG = TRUE AND tbuff.OKOD1 = ""
         AND tbuff.LONTILLAGG = ""     NO-LOCK NO-ERROR.
         IF AVAILABLE tbuff THEN DO:
            stillagg.HELDAG = FALSE.
         END.
         ELSE stillagg.HELDAG = TRUE.
         IF TIDREGITAB.AONR = "155" AND stillagg.HELDAG = FALSE THEN DELETE stillagg.
      END.
      /*IF TIDREGITAB.AONR = "155" AND TIDREGITAB.TOTALT > 7 THEN DO:         
         CREATE stillagg.   
         ASSIGN
         stillagg.PERSONALKOD = TIDREGITAB.PERSONALKOD
         stillagg.DATUM = TIDREGITAB.DATUM
         stillagg.AONR  = TIDREGITAB.AONR 
         stillagg.DELNR = TIDREGITAB.DELNR
         stillagg.TOTALT = TIDREGITAB.TOTALT.
      END.*/
      GET NEXT semq NO-LOCK.      
   END.
   CLOSE QUERY semq.
END.
ELSE IF  MONTH(hjdatum) < 5 THEN DO:      
   hjrak = 0.
   OPEN QUERY semnq FOR EACH TIDREGITAB WHERE TIDREGITAB.PERSONALKOD = PERSONALTAB.PERSONALKOD
   AND TIDREGITAB.PRISTYP = "FRÅNVARO."  
   AND TIDREGITAB.TIDLOG = TRUE
   AND YEAR(TIDREGITAB.DATUM) =  ( YEAR(hjdatum) - 1 )
   AND MONTH(TIDREGITAB.DATUM) > 5 AND MONTH(TIDREGITAB.DATUM) < 9 NO-LOCK.
   GET FIRST semnq NO-LOCK.   
   DO WHILE AVAILABLE(TIDREGITAB):             
      IF TIDREGITAB.AONR = "150" OR TIDREGITAB.AONR = "170" OR TIDREGITAB.AONR = "160" OR TIDREGITAB.AONR = "120"
      OR TIDREGITAB.AONR = "121" OR TIDREGITAB.AONR = "130" OR TIDREGITAB.AONR = "119" 
      OR TIDREGITAB.AONR = "155"  THEN DO:         
         CREATE stillagg.   
         ASSIGN
         stillagg.PERSONALKOD = TIDREGITAB.PERSONALKOD
         stillagg.DATUM = TIDREGITAB.DATUM
         stillagg.AONR  = TIDREGITAB.AONR 
         stillagg.DELNR = TIDREGITAB.DELNR
         stillagg.TOTALT = TIDREGITAB.TOTALT.
         hjrak = hjrak + 1.
         FIND FIRST tbuff  WHERE tbuff.PERSONALKOD = TIDREGITAB.PERSONALKOD   
         AND tbuff.DATUM = TIDREGITAB.DATUM AND tbuff.AONR NE TIDREGITAB.AONR    
         AND tbuff.TIDLOG = TRUE AND tbuff.OKOD1 = ""
         AND tbuff.LONTILLAGG = ""     NO-LOCK NO-ERROR.
         IF AVAILABLE tbuff THEN DO:
            stillagg.HELDAG = FALSE.
         END.
         ELSE stillagg.HELDAG = TRUE.
         IF TIDREGITAB.AONR = "155" AND stillagg.HELDAG = FALSE THEN DELETE stillagg.
      END.
      /*IF TIDREGITAB.AONR = "155" AND TIDREGITAB.TOTALT > 7 THEN DO:         
         CREATE stillagg.   
         ASSIGN
         stillagg.PERSONALKOD = TIDREGITAB.PERSONALKOD
         stillagg.DATUM = TIDREGITAB.DATUM
         stillagg.AONR  = TIDREGITAB.AONR 
         stillagg.DELNR = TIDREGITAB.DELNR
         stillagg.TOTALT = TIDREGITAB.TOTALT.
      END.      */
      GET NEXT semnq NO-LOCK.      
   END.
   CLOSE QUERY semnq.   
END.
/*IF MONTH(hjdatum) = 12 THEN DO:         
   OPEN QUERY semq FOR EACH TIDREGITAB WHERE TIDREGITAB.PERSONALKOD = PERSONALTAB.PERSONALKOD
   AND TIDREGITAB.AONR = "150" AND TIDREGITAB.DELNR = 0
   AND TIDREGITAB.TIDLOG = TRUE
   AND YEAR(TIDREGITAB.DATUM) = YEAR(hjdatum)
   AND MONTH(TIDREGITAB.DATUM) > 5 AND MONTH(TIDREGITAB.DATUM) < 9 NO-LOCK.
   GET FIRST semq NO-LOCK.   
   DO WHILE AVAILABLE(TIDREGITAB):      
      /*IF MONTH(TIDREGITAB.DATUM) = 12 AND DAY(TIDREGITAB.DATUM) GE 15 THEN pkod = pkod.
      ELSE DO:      */
      CREATE stillagg.   
      ASSIGN
      stillagg.PERSONALKOD = TIDREGITAB.PERSONALKOD
      stillagg.DATUM = TIDREGITAB.DATUM
      stillagg.AONR  = TIDREGITAB.AONR 
      stillagg.DELNR = TIDREGITAB.DELNR
      stillagg.TOTALT = TIDREGITAB.TOTALT.
      /*END.*/
      GET NEXT semq NO-LOCK.      
   END.
   CLOSE QUERY semq.
   OPEN QUERY semkq FOR EACH TIDREGITAB WHERE TIDREGITAB.PERSONALKOD = PERSONALTAB.PERSONALKOD
   AND TIDREGITAB.AONR = "170" AND TIDREGITAB.DELNR = 0
   AND TIDREGITAB.TIDLOG = TRUE
   AND YEAR(TIDREGITAB.DATUM) = YEAR(hjdatum)
   AND MONTH(TIDREGITAB.DATUM) > 5 AND MONTH(TIDREGITAB.DATUM) < 9 NO-LOCK.
   GET FIRST semkq NO-LOCK.   
   DO WHILE AVAILABLE(TIDREGITAB):       
      /*IF MONTH(TIDREGITAB.DATUM) = 12 AND DAY(TIDREGITAB.DATUM) GE 15 THEN pkod = pkod.
      ELSE DO:      */
         CREATE stillagg.   
         ASSIGN
         stillagg.PERSONALKOD = TIDREGITAB.PERSONALKOD
         stillagg.DATUM = TIDREGITAB.DATUM
         stillagg.AONR  = TIDREGITAB.AONR 
         stillagg.DELNR = TIDREGITAB.DELNR
         stillagg.TOTALT = TIDREGITAB.TOTALT.
      /*END.            */
      GET NEXT semkq NO-LOCK.      
   END.
   CLOSE QUERY semkq.
END.
ELSE IF  MONTH(hjdatum) < 5 THEN DO:         
   hjrak = 0.   
   OPEN QUERY semnq FOR EACH TIDREGITAB WHERE TIDREGITAB.PERSONALKOD = PERSONALTAB.PERSONALKOD
   AND TIDREGITAB.AONR = "150" AND TIDREGITAB.DELNR = 0 
   AND TIDREGITAB.TIDLOG = TRUE
   AND YEAR(TIDREGITAB.DATUM) =  ( YEAR(hjdatum) - 1 )
   AND MONTH(TIDREGITAB.DATUM) > 5 AND MONTH(TIDREGITAB.DATUM) < 9 NO-LOCK.
   GET FIRST semnq NO-LOCK.   
   DO WHILE AVAILABLE(TIDREGITAB):       
      IF MONTH(TIDREGITAB.DATUM) = 12 AND DAY(TIDREGITAB.DATUM) GE 15 THEN pkod = pkod.
      ELSE DO:      
         CREATE stillagg.   
         ASSIGN
         stillagg.PERSONALKOD = TIDREGITAB.PERSONALKOD
         stillagg.DATUM = TIDREGITAB.DATUM
         stillagg.AONR  = TIDREGITAB.AONR 
         stillagg.DELNR = TIDREGITAB.DELNR
         stillagg.TOTALT = TIDREGITAB.TOTALT.
         hjrak = hjrak + 1.
      END.
      GET NEXT semnq NO-LOCK.      
   END.
   CLOSE QUERY semnq.

   IF YEAR(hjdatum) = 2004 THEN DO:
   /*special byte personalkod sundsvall*/
      IF hjrak = 0 THEN DO:
         FIND FIRST persbuff WHERE persbuff.PERSONALKOD NE PERSONALTAB.PERSONALKOD AND persbuff.FORNAMN = PERSONALTAB.FORNAMN AND persbuff.EFTERNAMN = PERSONALTAB.EFTERNAMN NO-LOCK NO-ERROR.
         IF AVAILABLE persbuff THEN DO:
            OPEN QUERY semnsq FOR EACH TIDREGITAB WHERE TIDREGITAB.PERSONALKOD = persbuff.PERSONALKOD
            AND TIDREGITAB.AONR = "150" AND TIDREGITAB.DELNR = 0 
            AND TIDREGITAB.TIDLOG = TRUE
            AND YEAR(TIDREGITAB.DATUM) =  ( YEAR(hjdatum) - 1 )
            AND MONTH(TIDREGITAB.DATUM) > 5 AND MONTH(TIDREGITAB.DATUM) < 9 NO-LOCK.
            GET FIRST semnsq NO-LOCK.   
            DO WHILE AVAILABLE(TIDREGITAB):       
               /*IF MONTH(TIDREGITAB.DATUM) = 12 AND DAY(TIDREGITAB.DATUM) GE 15 THEN pkod = pkod.
               ELSE DO:      */
                  CREATE stillagg.   
                  ASSIGN
                  stillagg.PERSONALKOD = TIDREGITAB.PERSONALKOD
                  stillagg.DATUM = TIDREGITAB.DATUM
                  stillagg.AONR  = TIDREGITAB.AONR 
                  stillagg.DELNR = TIDREGITAB.DELNR
                  stillagg.TOTALT = TIDREGITAB.TOTALT.

               /*END.*/
               GET NEXT semnsq NO-LOCK.      
            END.
            CLOSE QUERY semnsq.
         END.
      END.   
   END.

   OPEN QUERY semknq FOR EACH TIDREGITAB WHERE TIDREGITAB.PERSONALKOD = PERSONALTAB.PERSONALKOD
   AND TIDREGITAB.AONR = "170" AND TIDREGITAB.DELNR = 0 
   AND TIDREGITAB.TIDLOG = TRUE
   AND YEAR(TIDREGITAB.DATUM) =  ( YEAR(hjdatum) - 1 )
   AND MONTH(TIDREGITAB.DATUM) > 5 AND MONTH(TIDREGITAB.DATUM) < 9 NO-LOCK.
   GET FIRST semknq NO-LOCK.   
   DO WHILE AVAILABLE(TIDREGITAB):       
      /*IF MONTH(TIDREGITAB.DATUM) = 12 AND DAY(TIDREGITAB.DATUM) GE 15 THEN pkod = pkod.
      ELSE DO:      */
         CREATE stillagg.   
         ASSIGN
         stillagg.PERSONALKOD = TIDREGITAB.PERSONALKOD
         stillagg.DATUM = TIDREGITAB.DATUM
         stillagg.AONR  = TIDREGITAB.AONR 
         stillagg.DELNR = TIDREGITAB.DELNR
         stillagg.TOTALT = TIDREGITAB.TOTALT.
      /*END.            */
      GET NEXT semknq NO-LOCK.      
   END.
   CLOSE QUERY semknq.
END.*/
sdagar = 0.
/*totid = 7.75.*/
FOR EACH stillagg WHERE stillagg.AONR = "150" AND stillagg.totalt > 0:
   sdagar = sdagar + 1.
   /*totid = klock100(stillagg.totalt).*/
END.
FOR EACH stillagg WHERE stillagg.AONR = "160" OR stillagg.AONR = "119" OR stillagg.AONR = "120"
OR stillagg.AONR = "121" OR stillagg.AONR = "130" OR stillagg.AONR = "155" OR stillagg.AONR = "170":
   IF stillagg.HELDAG =  TRUE THEN DO:   
      sdagar = sdagar + 1.
  /*    totid = klock100(stillagg.totalt).*/
   END.
END.
/*stim = 0.

FOR EACH stillagg WHERE stillagg.AONR = "170"  :
   IF stillagg.totalt > 0 THEN DO:   
      stim = stim + klock100(stillagg.totalt).
   END.
END.
sdagar = sdagar + ( stim / totid ).*/

IF sdagar < 16 THEN DO:
   IF MONTH(hjdatum) = 12 THEN DO:
      FIND FIRST TIDREGITAB WHERE TIDREGITAB.PERSONALKOD = PERSONALTAB.PERSONALKOD
      AND TIDREGITAB.TIDLOG = TRUE   
      AND YEAR(TIDREGITAB.DATUM) =  YEAR(hjdatum)
      AND MONTH(TIDREGITAB.DATUM) < 7 NO-LOCK NO-ERROR.
      IF NOT AVAILABLE TIDREGITAB THEN DO: 
         sdagar = 16.
      END.
      ELSE DO:
         FIND FIRST TIDREGITAB WHERE TIDREGITAB.PERSONALKOD = PERSONALTAB.PERSONALKOD
         AND TIDREGITAB.TIDLOG = TRUE   
         AND YEAR(TIDREGITAB.DATUM) =  YEAR(hjdatum)
         AND MONTH(TIDREGITAB.DATUM) < 6 NO-LOCK NO-ERROR.
         IF NOT AVAILABLE TIDREGITAB THEN DO:
            FOR EACH TIDREGITAB WHERE TIDREGITAB.PERSONALKOD = PERSONALTAB.PERSONALKOD
            AND TIDREGITAB.TIDLOG = TRUE   
            AND TIDREGITAB.AONR = "159" 
            AND YEAR(TIDREGITAB.DATUM) =  YEAR(hjdatum)
            AND MONTH(TIDREGITAB.DATUM) = 6 NO-LOCK:
               sdagar = sdagar + 1.
            END.
         END.
      END.
   END.
   ELSE IF MONTH(hjdatum) LE 4 THEN DO:   
      FIND FIRST TIDREGITAB WHERE TIDREGITAB.PERSONALKOD = PERSONALTAB.PERSONALKOD
      AND TIDREGITAB.TIDLOG = TRUE   
      AND YEAR(TIDREGITAB.DATUM) =  ( YEAR(hjdatum) - 1 )
      AND MONTH(TIDREGITAB.DATUM) < 7 NO-LOCK NO-ERROR.
      IF NOT AVAILABLE TIDREGITAB THEN DO: 
         sdagar = 16.
      END.
      ELSE DO:
         FIND FIRST TIDREGITAB WHERE TIDREGITAB.PERSONALKOD = PERSONALTAB.PERSONALKOD
         AND TIDREGITAB.TIDLOG = TRUE   
         AND YEAR(TIDREGITAB.DATUM) =  ( YEAR(hjdatum) - 1 )
         AND MONTH(TIDREGITAB.DATUM) < 6 NO-LOCK NO-ERROR.
         IF NOT AVAILABLE TIDREGITAB THEN DO: 
            FOR EACH TIDREGITAB WHERE TIDREGITAB.PERSONALKOD = PERSONALTAB.PERSONALKOD
            AND TIDREGITAB.TIDLOG = TRUE   
            AND TIDREGITAB.AONR = "159" 
            AND YEAR(TIDREGITAB.DATUM) =  ( YEAR(hjdatum) - 1 )
            AND MONTH(TIDREGITAB.DATUM) = 6 NO-LOCK:
               sdagar = sdagar + 1.
            END.
         END.
      END.
   END.
END.

   
