DEFINE VAR A AS INTEGER.
DEFINE VAR B AS INTEGER.

A = 0.
B = 0.
FIND FIRST FORETAG  NO-LOCK NO-ERROR.
IF FORETAG.FORETAG = "GRAN" THEN DO:
   OUTPUT TO d:\ELPOOL\ONEHUVLEVBETFRIA.TXT.
   FOR EACH BEREDNING WHERE BEREDNING.BERNR > 0 AND  BEREDNING.OMRADE NE "" /*AND  BEREDNING.AKTIV = TRUE*/  NO-LOCK:
      FIND FIRST OMRADETAB WHERE OMRADETAB.OMRADE = BEREDNING.OMRADE AND OMRADETAB.ELVOMRKOD = 0 NO-LOCK NO-ERROR.
      IF AVAILABLE OMRADETAB THEN DO:
          FIND FIRST BETFRIA  WHERE BETFRIA.BETNR = BEREDNING.BERNR AND
          BETFRIA.FAKTTEXT = BEREDNING.OMRADE    NO-LOCK NO-ERROR.
          IF NOT AVAILABLE BETFRIA THEN DO:
             FIND FIRST INKADRESS WHERE INKADRESS.AONRAONR = BEREDNING.AONR AND INKADRESS.AONRDELNR = BEREDNING.DELNR AND  INKADRESS.LEVKOD = "2" NO-LOCK NO-ERROR.
             IF AVAILABLE INKADRESS THEN DO:
                 CREATE BETFRIA.
                 ASSIGN
                 BETFRIA.BETNR = BEREDNING.BERNR  /*beredningsnummer*/
                 BETFRIA.FAKTTEXT = BEREDNING.OMRADE  /*beredningens område*/
                 BETFRIA.TYP = "2". /*vald leverantör för beredningen*/
                 DISP BEREDNING.BERNR BEREDNING.OMRADE BEREDNING.AONR BEREDNING.DELNR BEREDNING.AKTIV BEREDNING.ANVANDARE.
              END.   
          END.
          ELSE DO:
          END.
       END.   
   END.  
 END.
 IF FORETAG.FORETAG = "ATS" THEN DO:
   OUTPUT TO C:\ELPOOL\ATSHUVLEVBETFRIA.TXT.
   FOR EACH BEREDNING WHERE BEREDNING.BERNR > 0 AND  BEREDNING.OMRADE NE "" /*AND  BEREDNING.AKTIV = TRUE*/  NO-LOCK:
      FIND FIRST OMRADETAB WHERE OMRADETAB.OMRADE = BEREDNING.OMRADE AND OMRADETAB.ELVOMRKOD = 0 NO-LOCK NO-ERROR.
      IF AVAILABLE OMRADETAB THEN DO:
          FIND FIRST BETFRIA  WHERE BETFRIA.BETNR = BEREDNING.BERNR AND
          BETFRIA.FAKTTEXT = BEREDNING.OMRADE    NO-LOCK NO-ERROR.
          IF NOT AVAILABLE BETFRIA THEN DO:             
              CREATE BETFRIA.
              ASSIGN
              BETFRIA.BETNR = BEREDNING.BERNR  /*beredningsnummer*/
              BETFRIA.FAKTTEXT = BEREDNING.OMRADE  /*beredningens område*/
              BETFRIA.TYP = "1". /*vald leverantör för beredningen*/
              DISP BEREDNING.BERNR BEREDNING.OMRADE BEREDNING.AONR BEREDNING.DELNR BEREDNING.AKTIV BEREDNING.ANVANDARE.
              
          END.
          
       END.   
   END.  
 END.   
   
   
      
/*    BETFRIA.TYP = vald_lev*/
