   DEFINE VARIABLE kodanst AS CHARACTER NO-UNDO.
   FOR EACH PERSONALTAB WHERE USE-INDEX PERSONALKOD NO-LOCK:
      FIND FIRST ANSTFORMTAB WHERE ANSTFORMTAB.ANSTALLNING = PERSONALTAB.ANSTALLNING
      USE-INDEX ANSTF NO-LOCK NO-ERROR.  
      ASSIGN
      kodanst = ANSTFORMTAB.KOD.                                                       
      FOR EACH TIDREGITAB WHERE TIDREGITAB.PERSONALKOD = PERSONALTAB.PERSONALKOD AND
      TIDREGITAB.LONTILLAGG NE " " NO-LOCK: 
         RUN lonsum_UI.     
      END.
   END.
PROCEDURE lonsum_UI.   
   /*SUMLON ENDAST FÖR FAKTURERING 
    endast de lönetillägg som skall till fakturering*/
   
   FIND FIRST LONTILL WHERE LONTILL.KOD = kodanst AND
   LONTILL.LONTILLAGG = TIDREGITAB.LONTILLAGG
   USE-INDEX LON NO-LOCK NO-ERROR.
   IF NOT AVAILABLE LONTILL THEN RETURN.      
   IF SUBSTRING(LONTILL.TYPKOD,5,3) NE "FAK" THEN RETURN.                   
   CREATE SUMLON.
   ASSIGN
   SUMLON.PERSONALKOD = TIDREGITAB.PERSONALKOD      
   SUMLON.AONR = TIDREGITAB.AONR
   SUMLON.DELNR = TIDREGITAB.DELNR
   SUMLON.DATUM = TIDREGITAB.DATUM
   SUMLON.VECKOKORD = TIDREGITAB.VECKOKORD
   SUMLON.LONTILLAGG = TIDREGITAB.LONTILLAGG
   SUMLON.LONTILLANTAL = TIDREGITAB.LONTILLANTAL.   
END PROCEDURE.
