DEFINE NEW SHARED VARIABLE infil AS CHARACTER NO-UNDO.
DEFINE NEW SHARED VARIABLE utfil AS CHARACTER NO-UNDO.
DEFINE NEW SHARED VARIABLE quotervar AS CHARACTER FORMAT "X(256)" NO-UNDO.
DEFINE NEW SHARED VARIABLE wtidvar AS CHARACTER FORMAT "X(256)" NO-UNDO.
DEFINE NEW SHARED VARIABLE musz AS LOGICAL NO-UNDO. 
DEFINE VARIABLE str AS CHARACTER FORMAT "X(86)" NO-UNDO. 
DEFINE VARIABLE words AS CHARACTER FORMAT "X(132)" NO-UNDO.

DEFINE NEW SHARED TEMP-TABLE art_temp 
   FIELD ARTNR AS CHARACTER FORMAT "X(10)"
   FIELD DEPNR LIKE MTRLDEP.DEPNR 
   FIELD BOK AS CHARACTER FORMAT "X(2)"
   FIELD SIFF AS CHARACTER FORMAT "X(6)"   
   FIELD FACKID LIKE MTRLDEP.FACKID
   FIELD BENAMNING LIKE MTRLDEP.BENAMNING
   FIELD ENR LIKE MTRLDEP.ENR
   FIELD ENHET LIKE MTRLDEP.ENHET
   FIELD BESTKVANT LIKE MTRLDEP.BESTKVANT
   FIELD BESTPUNKT LIKE MTRLDEP.BESTPUNKT 
   FIELD LEVKOD LIKE MTRLDEP.LEVKOD 
   FIELD OMSATT LIKE MTRLDEP.OMSATT
   FIELD INVANT LIKE MTRLDEP.INVANT
   FIELD IB LIKE MTRLDEP.IB
   FIELD IBDATUM LIKE MTRLDEP.IBDATUM
   FIELD INVDATUM LIKE MTRLDEP.INVDATUM
   FIELD NPRIS LIKE MTRLDEP.NPRIS
   FIELD BPRIS LIKE MTRLDEP.BPRIS
   FIELD SALDO LIKE MTRLDEP.SALDO.
   
DEFINE NEW SHARED TEMP-TABLE for_temp 
   FIELD ARTNR AS CHARACTER FORMAT "X(10)"
   FIELD DEPNR LIKE MTRLDEP.DEPNR 
   FIELD BOK AS CHARACTER FORMAT "X(2)"
   FIELD SIFF AS CHARACTER FORMAT "X(6)"   
   FIELD FACKID LIKE MTRLDEP.FACKID
   FIELD BENAMNING LIKE MTRLDEP.BENAMNING
   FIELD ENR LIKE MTRLDEP.ENR
   FIELD ENHET LIKE MTRLDEP.ENHET
   FIELD BESTKVANT LIKE MTRLDEP.BESTKVANT
   FIELD BESTPUNKT LIKE MTRLDEP.BESTPUNKT 
   FIELD LEVKOD LIKE MTRLDEP.LEVKOD 
   FIELD OMSATT LIKE MTRLDEP.OMSATT
   FIELD INVANT LIKE MTRLDEP.INVANT
   FIELD IB LIKE MTRLDEP.IB
   FIELD IBDATUM LIKE MTRLDEP.IBDATUM
   FIELD INVDATUM LIKE MTRLDEP.INVDATUM
   FIELD NPRIS LIKE MTRLDEP.NPRIS
   FIELD BPRIS LIKE MTRLDEP.BPRIS
   FIELD SALDO LIKE MTRLDEP.SALDO.

DEFINE TEMP-TABLE tidin
   FIELD TIN AS CHARACTER FORMAT "X(256)".
   
   ASSIGN
   infil = "A:\artikel.txt"
   utfil = "A:\forrad.txt"
   wtidvar = "F:\PRO8\GURU\WPLAN\sole.q"
   quotervar = "F:\PRO8\DLC\BIN\quoter".
   DOS SILENT VALUE(quotervar)
   VALUE(infil) > VALUE(wtidvar).           
   INPUT FROM VALUE(wtidvar) NO-ECHO
   CONVERT TARGET "iso8859-1" SOURCE "swedish-7-bit" NO-ECHO.
  /*iso8859-1 swedish-7-bit ibm850"*/
   REPEAT:
      SET words VIEW-AS EDITOR INNER-CHARS 50 INNER-LINES 3 WITH FRAME DDD WIDTH 80.
      CREATE tidin.
      ASSIGN tidin.TIN = words.
   END.
   INPUT CLOSE.
   DISPLAY "INLASNING 1 KLAR".
   FOR EACH tidin:
      CREATE art_temp.
      ASSIGN    
      art_temp.ARTNR = SUBSTRING(tidin.TIN,1,10)
      art_temp.BENAMNING = SUBSTRING(tidin.TIN,12,40)
      art_temp.ENHET = SUBSTRING(tidin.TIN,156,4)
      art_temp.ENR = SUBSTRING(tidin.TIN,160,10).
      IF SUBSTRING(tidin.TIN,190,10) = "ELEF" THEN art_temp.LEVKOD = "1".
      ELSE IF SUBSTRING(tidin.TIN,190,10) = "SELGA" THEN art_temp.LEVKOD = "3".
      ELSE art_temp.LEVKOD = "1".
   END.         
   DISPLAY "SKAPA 1 KLAR".
   FOR EACH tidin:
      DELETE tidin.
   END.   
   RUN F:\PRO8\GURU\WX\XSOLDEP3.P.   
   DISPLAY "SKAPA 2 KLAR".
   FOR EACH for_temp:
      FIND FIRST art_temp WHERE art_temp.ARTNR = for_temp.ARTNR NO-LOCK NO-ERROR.
      IF NOT AVAILABLE art_temp THEN DO:
         DISPLAY for_temp.ARTNR for_temp.ENR for_temp.BENAMNING.
      END.
      ELSE DO:
         CREATE MTRLDEP.
         ASSIGN
         MTRLDEP.DEPNR = for_temp.DEPNR         
         MTRLDEP.ENR = art_temp.ENR 
         MTRLDEP.BENAMNING = art_temp.BENAMNING   
         MTRLDEP.ENHET = art_temp.ENHET
         MTRLDEP.BPRIS = for_temp.NPRIS
         MTRLDEP.NPRIS = for_temp.NPRIS.
         IF for_temp.BESTKVANT = 0 THEN MTRLDEP.BESTKVANT = 1.
         ELSE MTRLDEP.BESTKVANT = for_temp.BESTKVANT.
         ASSIGN 
         MTRLDEP.BESTPUNKT = for_temp.BESTPUNKT    
         MTRLDEP.INVDATUM = TODAY
         MTRLDEP.INVANT = 0
         MTRLDEP.FACKID = ""          
         MTRLDEP.LEVKOD = art_temp.LEVKOD
         MTRLDEP.SALDO = for_temp.SALDO.         
      END.
   END.      
