/*skapa kundregister sollefteå*/

DEFINE NEW SHARED VARIABLE filnamn AS CHARACTER NO-UNDO.
DEFINE NEW SHARED VARIABLE skrivut AS LOGICAL NO-UNDO.
DEFINE NEW SHARED VARIABLE musz AS LOGICAL NO-UNDO.         
DEFINE VARIABLE words AS CHARACTER FORMAT "X(132)" NO-UNDO.
DEFINE TEMP-TABLE tidin
   FIELD TIN AS CHARACTER FORMAT "X(132)".  

DEFINE NEW SHARED TEMP-TABLE temp_kund 
   FIELD BESTID LIKE BESTTAB.BESTID
   FIELD BESTNAMN LIKE BESTTAB.BESTNAMN
   FIELD ADRESS LIKE BESTTAB.ADRESS
   FIELD PNR LIKE BESTTAB.PNR
   FIELD ORT LIKE BESTTAB.ORT
   FIELD TEL LIKE BESTTAB.TEL
   FIELD KONTAKT LIKE BESTTAB.KONTAKT.
   
DOS SILENT quoter A:\kunder.txt > A:\kund.Q.      
   
INPUT FROM A:\kund.Q NO-ECHO.
/*CONVERT TARGET "iso8859-1" SOURCE "swedish-7-bit".*/
REPEAT:
   SET words VIEW-AS EDITOR INNER-CHARS 50 INNER-LINES 3 WITH FRAME DDD WIDTH 80.   
   CREATE TIDIN.   
   ASSIGN TIDIN.TIN = words.   
END.
INPUT CLOSE.

FOR EACH TIDIN:
   CREATE temp_kund.
   ASSIGN
   temp_kund.BESTID = SUBSTRING(TIDIN.TIN,1,6)
   temp_kund.BESTNAMN = SUBSTRING(TIDIN.TIN,8,28)
   temp_kund.KONTAKT = SUBSTRING(TIDIN.TIN,38,20)   
   temp_kund.ADRESS = SUBSTRING(TIDIN.TIN,62,22)
   temp_kund.PNR = SUBSTRING(TIDIN.TIN,95,6)
   temp_kund.ORT = SUBSTRING(TIDIN.TIN,101,13)
   temp_kund.TEL = SUBSTRING(TIDIN.TIN,115,11).                
END.    

FOR EACH temp_kund:         
   FIND FIRST BESTTAB WHERE BESTTAB.BESTID = temp_kund.BESTID
   NO-LOCK NO-ERROR.
   IF AVAILABLE BESTTAB THEN DO:   
      DISPLAY temp_kund.BESTID temp_kund.BESTNAMN temp_kund.KONTAKT 
      temp_kund.ADRESS temp_kund.PNR temp_kund.ORT temp_kund.TEL. 
   END.
   ELSE DO:   
      CREATE BESTTAB.      
      ASSIGN
      BESTTAB.BESTID = temp_kund.BESTID 
      BESTTAB.BESTNAM = temp_kund.BESTNAMN 
      BESTTAB.KONTAKT = temp_kund.KONTAKT 
      BESTTAB.ADRESS = temp_kund.ADRESS 
      BESTTAB.PNR = temp_kund.PNR 
      BESTTAB.ORT = temp_kund.ORT 
      BESTTAB.TEL = temp_kund.TEL 
      BESTTAB.AOKUND = FALSE.
   END.   
END.  
