DEFINE SHARED VARIABLE infil AS CHARACTER NO-UNDO.
DEFINE SHARED VARIABLE utfil AS CHARACTER NO-UNDO.
DEFINE SHARED VARIABLE quotervar AS CHARACTER FORMAT "X(256)" NO-UNDO.
DEFINE SHARED VARIABLE wtidvar AS CHARACTER FORMAT "X(256)" NO-UNDO.
DEFINE SHARED VARIABLE musz AS LOGICAL NO-UNDO. 
DEFINE VARIABLE str AS CHARACTER FORMAT "X(86)" NO-UNDO. 
DEFINE VARIABLE words AS CHARACTER FORMAT "X(132)" NO-UNDO.

DEFINE SHARED TEMP-TABLE for_temp 
   FIELD ARTNR AS CHARACTER FORMAT "X(10)"
   FIELD DEPNR LIKE MTRLDEP.DEPNR 
   FIELD BOK AS CHARACTER FORMAT "X(2)"
   FIELD SIFF AS CHARACTER FORMAT "X(6)"   
   FIELD FACKID LIKE MTRLDEP.FACKID
   FIELD BENAMNING LIKE MTRLDEP.BENAMNING
   FIELD ENR LIKE MTRLDEP.ENR
   FIELD ENHET LIKE MTRLDEP.ENHET
   FIELD BESTKVANT LIKE MTRLDEP.BESTKVANT
   FIELD BESTPUNKT LIKE MTRLDEP.BESTPUNKT 
   FIELD LEVKOD LIKE MTRLDEP.LEVKOD 
   FIELD OMSATT LIKE MTRLDEP.OMSATT
   FIELD INVANT LIKE MTRLDEP.INVANT
   FIELD IB LIKE MTRLDEP.IB
   FIELD IBDATUM LIKE MTRLDEP.IBDATUM
   FIELD INVDATUM LIKE MTRLDEP.INVDATUM
   FIELD NPRIS LIKE MTRLDEP.NPRIS
   FIELD BPRIS LIKE MTRLDEP.BPRIS
   FIELD SALDO LIKE MTRLDEP.SALDO.


DEFINE TEMP-TABLE tidin
   FIELD TIN AS CHARACTER FORMAT "X(256)".
        
   DOS SILENT VALUE(quotervar)
   VALUE(utfil) > VALUE(wtidvar).           
   INPUT FROM VALUE(wtidvar) NO-ECHO
   CONVERT TARGET "iso8859-1" SOURCE "swedish-7-bit" NO-ECHO.
   /*iso8859-1 swedish-7-bit ibm850"*/
   REPEAT:
      SET words VIEW-AS EDITOR INNER-CHARS 50 INNER-LINES 3 WITH FRAME DDD WIDTH 80.
      CREATE tidin.
      ASSIGN tidin.TIN = words.
   END.
   INPUT CLOSE.
   DISPLAY "INLASNING 2 KLAR".
   FOR EACH tidin:
      CREATE for_temp.
      IF SUBSTRING(tidin.TIN,1,2) = "12" THEN for_temp.DEPNR = 1.
      ELSE for_temp.DEPNR = 3.
      ASSIGN         
      for_temp.ARTNR = SUBSTRING(tidin.TIN,4,10)
      for_temp.BESTPUNKT = INTEGER(SUBSTRING(tidin.TIN,155,3))
      for_temp.BESTKVANT = INTEGER(SUBSTRING(tidin.TIN,160,3))
      for_temp.NPRIS = DECIMAL(SUBSTRING(tidin.TIN,164,8)) / EXP(10,2)    
      for_temp.SALDO = INTEGER(SUBSTRING(tidin.TIN,183,5)).
   END.     
