DEFINE NEW SHARED VARIABLE filnamn AS CHARACTER NO-UNDO.
DEFINE NEW SHARED VARIABLE skrivut AS LOGICAL NO-UNDO.
DEFINE NEW SHARED VARIABLE musz AS LOGICAL NO-UNDO.         
DEFINE VARIABLE words AS CHARACTER FORMAT "X(132)" NO-UNDO.
DEFINE TEMP-TABLE tidin
   FIELD TIN AS CHARACTER FORMAT "X(132)".  

DEFINE NEW SHARED TEMP-TABLE temp_dep 
   FIELD DEPNR LIKE MTRLDEP.DEPNR 
   FIELD BOK AS CHARACTER FORMAT "X(2)"
   FIELD SIFF AS CHARACTER FORMAT "X(6)"   
   FIELD FACKID LIKE MTRLDEP.FACKID
   FIELD BENAMNING LIKE MTRLDEP.BENAMNING
   FIELD ENR LIKE MTRLDEP.ENR
   FIELD ENHET LIKE MTRLDEP.ENHET
   FIELD BESTKVANT LIKE MTRLDEP.BESTKVANT
   FIELD BESTPUNKT LIKE MTRLDEP.BESTPUNKT 
   FIELD LEVKOD LIKE MTRLDEP.LEVKOD 
   FIELD OMSATT LIKE MTRLDEP.OMSATT
   FIELD INVANT LIKE MTRLDEP.INVANT
   FIELD IB LIKE MTRLDEP.IB
   FIELD IBDATUM LIKE MTRLDEP.IBDATUM
   FIELD INVDATUM LIKE MTRLDEP.INVDATUM
   FIELD NPRIS LIKE MTRLDEP.NPRIS
   FIELD BPRIS LIKE MTRLDEP.BPRIS.

DOS SILENT quoter A:\varor.txt > A:\var.Q.      
   
INPUT FROM A:\var.Q NO-ECHO.
/*CONVERT TARGET "iso8859-1" SOURCE "swedish-7-bit".*/
REPEAT:
   SET words VIEW-AS EDITOR INNER-CHARS 50 INNER-LINES 3 WITH FRAME DDD WIDTH 80.   
   CREATE TIDIN.   
   ASSIGN TIDIN.TIN = words.   
END.
INPUT CLOSE.

FOR EACH TIDIN:
   CREATE temp_dep.
   ASSIGN    
   temp_dep.ENR = SUBSTRING(TIDIN.TIN,1,11)
   temp_dep.BENAMNING = SUBSTRING(TIDIN.TIN,22,39)
   temp_dep.ENHET = SUBSTRING(TIDIN.TIN,61,3)
   temp_dep.BPRIS = DECIMAL(SUBSTRING(TIDIN.TIN,86,8)) / EXP(10,2)    
   temp_dep.NPRIS = DECIMAL(SUBSTRING(TIDIN.TIN,104,8)) / EXP(10,2).
END.    /*HUVUDPROGRAM ÖVERFÖRING DEPÅ FRÅN EL90 TILL GURU*/  

FOR EACH temp_dep: 
   FIND FIRST MTRLDEP WHERE MTRLDEP.ENR = temp_dep.ENR NO-LOCK NO-ERROR.
   IF AVAILABLE MTRLDEP THEN DO:
      DISPLAY temp_dep.ENR temp_dep.BENAMNING temp_dep.BPRIS.  
   END.
   ELSE DO:   
      CREATE MTRLDEP.
      ASSIGN
      MTRLDEP.DEPNR = 2         
      MTRLDEP.ENR = temp_dep.ENR 
      MTRLDEP.BENAMNING = temp_dep.BENAMNING   
      MTRLDEP.ENHET = temp_dep.ENHET
      MTRLDEP.BPRIS = temp_dep.BPRIS
      MTRLDEP.BESTKVANT = 1 
      MTRLDEP.BESTPUNKT = 0    
      MTRLDEP.INVDATUM = TODAY
      MTRLDEP.INVANT = 0
      MTRLDEP.FACKID = ""          
      MTRLDEP.LEVKOD = "2".
      IF temp_dep.NPRIS = 0 THEN MTRLDEP.NPRIS = temp_dep.BPRIS.
      ELSE MTRLDEP.NPRIS = temp_dep.NPRIS.
   END.   
END.           
