/*XSTARB.P*/

DEFINE VARIABLE program AS CHARACTER FORMAT "X(15)".
DEFINE VARIABLE db AS CHARACTER LABEL "VILKEN DATABAS" .
DEFINE VARIABLE id AS CHARACTER.
DEFINE VARIABLE password AS CHARACTER.
DEFINE VARIABLE kommando AS CHARACTER FORMAT "X(132)" NO-UNDO.
DEFINE VARIABLE varmess AS CHARACTER NO-UNDO.
DEFINE VARIABLE varerror AS INTEGER NO-UNDO.
DEFINE VARIABLE musz AS LOGICAL NO-UNDO.
DEFINE VARIABLE status-ok AS LOGICAL NO-UNDO.
DEFINE TEMP-TABLE valdbtemp 
   FIELD ORDNING AS INTEGER
   FIELD FORETAG AS CHARACTER LABEL "Företag"
   FIELD VALDB AS CHARACTER   LABEL "Databas"
   FIELD DBNAMN AS CHARACTER 
   FIELD DBCON AS CHARACTER 
   FIELD DBCACHE AS CHARACTER
   FIELD Guru.Konstanter:appcon AS CHARACTER 
   FIELD GFORETAG AS CHARACTER
   INDEX ORDNING AS PRIMARY FORETAG ORDNING
   INDEX GFORETAG GFORETAG
   INDEX DBNAMN DBNAMN.

{VALDBALL.I}
REPEAT:
   RUN DISP_UI.      
   UPDATE db WITH FRAME CC.       
   IF db = "" THEN QUIT.
   ELSE DO:
      FIND FIRST valdbtemp WHERE valdbtemp.gforetag = db NO-ERROR.
      IF AVAILABLE valdbtemp THEN DO:
         RUN con_UI.
         {LDALIAS8.I}
         UPDATE id password WITH FRAME CC1.
         HIDE FRAME CC1.
         IF SETUSERID(id,password,"DICTDB") THEN do:
            UPDATE program.
            RUN VALUE(program).
            PAUSE.
         END.   
         QUIT.
      END.
   END.
END.
PROCEDURE disp_UI:
   FOR EACH valdbtemp:
      DISPLAY valdbtemp.ORDNING
      valdbtemp.gFORETAG FORMAT "X(5)"
      valdbtemp.VALDB LABEL "Databas" FORMAT "X(30)".
   END.
END PROCEDURE.

PROCEDURE con_UI :
    kommando = valdbtemp.DBCON.
    MESSAGE kommando.
    CONNECT VALUE(kommando) NO-ERROR.                           
END PROCEDURE.

