/*XSTANSVA.P. STANSKÖRNING VATTENFALL*/
DEFINE NEW SHARED VARIABLE vkdatum AS DATE NO-UNDO.
DEFINE NEW SHARED VARIABLE globanv LIKE ANVANDARE.ANVANDARE NO-UNDO.

DEFINE NEW SHARED VARIABLE appcon AS LOGICAL NO-UNDO.

DEFINE TEMP-TABLE pa90fil
   FIELD PANSTNR LIKE PERSONALTAB.ANSTNR
   FIELD START LIKE TIDREGITAB.START
   FIELD SLUT LIKE TIDREGITAB.SLUT
   FIELD PLONTILLAGG LIKE TIDREGITAB.LONTILLAGG
   FIELD PLONTILLANTAL LIKE TIDREGITAB.LONTILLANTAL
   FIELD POVERTIDTILL LIKE TIDREGITAB.OVERTIDTILL
   FIELD POVERANTAL LIKE TIDREGITAB.OVERANTAL
   FIELD PTRAKTKOD LIKE TIDREGITAB.TRAKTKOD
   FIELD PTRAKTANTAL LIKE TIDREGITAB.TRAKTANTAL
   FIELD PBEREDSKAP LIKE TIDREGITAB.BEREDSKAP
   FIELD PBERANTAL LIKE TIDREGITAB.BERANTAL
   FIELD PDATUM LIKE TIDREGITAB.DATUM
   FIELD SLUTDATUM LIKE TIDREGITAB.DATUM INITIAL ?
   FIELD PVECKONUMMER LIKE TIDREGITAB.VECKONUMMER
   FIELD MANAD AS INTEGER
   FIELD PSORT AS CHARACTER FORMAT "XX"
   FIELD PPAR8 AS DECIMAL FORMAT "-99.99"
   FIELD AONR LIKE TIDREGITAB.AONR
   FIELD DELNR LIKE TIDREGITAB.DELNR
   FIELD PAVTAL AS CHARACTER
   FIELD TID AS LOGICAL
   FIELD BERKOLL AS LOGICAL INITIAL FALSE
   INDEX PANSTNR IS PRIMARY PANSTNR ASCENDING.
globanv = CHR(69) + CHR(76) + CHR(80) + CHR(65) + CHR(79).
vkdatum = 12/10/2000.
CREATE SERVER Guru.Konstanter:apphand.
appcon = Guru.Konstanter:apphand:CONNECT("-S appvatt -H thnuguru -N TCP",CHR(69) + CHR(76) + CHR(80) + CHR(65) + CHR(79),"KAGGEN","") NO-ERROR.
RUN STVAVE1.P ON Guru.Konstanter:apphand TRANSACTION DISTINCT (INPUT vkdatum, INPUT Guru.Konstanter:globanv,OUTPUT TABLE pa90fil).
RUN STVAFR1.P ON Guru.Konstanter:apphand TRANSACTION DISTINCT (INPUT vkdatum, INPUT Guru.Konstanter:globanv,INPUT TABLE pa90fil).

IF Guru.Konstanter:appcon THEN Guru.Konstanter:appcon = Guru.Konstanter:apphand:DISCONNECT().
DELETE OBJECT Guru.Konstanter:apphand.
appcon = FALSE.
