 /*XSUTILLN1SP.P*/
{LESAMMAN.I}  
DEFINE INPUT PARAMETER kordatum AS DATE NO-UNDO.
DEFINE INPUT PARAMETER koranv LIKE ANVANDARE.ANVANDARE NO-UNDO.
DEFINE INPUT PARAMETER gkorvar AS CHARACTER NO-UNDO.
RUN sammut_UI (INPUT 1).
&Scoped-define NEW   
&Scoped-define SHARED 
{LONEDEF.I}
DEFINE NEW SHARED VARIABLE fnytid AS DECIMAL FORMAT "-99.99" NO-UNDO.
DEFINE NEW SHARED VARIABLE vkdatum AS DATE NO-UNDO.
DEFINE NEW SHARED VARIABLE regvnr AS INTEGER FORMAT "999" NO-UNDO.     
DEFINE NEW SHARED VARIABLE regdatum AS DATE NO-UNDO.
DEFINE NEW SHARED VARIABLE regstart LIKE TIDREGITAB.START NO-UNDO. 
DEFINE NEW SHARED VARIABLE regslut LIKE TIDREGITAB.SLUT NO-UNDO.
DEFINE NEW SHARED VARIABLE persrec AS RECID NO-UNDO.
DEFINE NEW SHARED VARIABLE globanv LIKE ANVANDARE.ANVANDARE NO-UNDO.
DEFINE NEW SHARED VARIABLE globforetag LIKE FORETAG.FORETAG NO-UNDO.
DEFINE NEW SHARED VARIABLE regdagnamn AS CHARACTER FORMAT "X(3)" NO-UNDO.        
DEFINE NEW SHARED VARIABLE regtotalt LIKE TIDREGITAB.TOTALT NO-UNDO.
DEFINE NEW SHARED VARIABLE frustarten AS DECIMAL NO-UNDO.
DEFINE NEW SHARED VARIABLE fruslutet AS DECIMAL NO-UNDO.
DEFINE NEW SHARED VARIABLE kaffestart AS DECIMAL NO-UNDO.
DEFINE NEW SHARED VARIABLE kaffeslut AS DECIMAL NO-UNDO.
DEFINE NEW SHARED VARIABLE lunchstarten AS DECIMAL NO-UNDO.
DEFINE NEW SHARED VARIABLE lunchslutet AS DECIMAL NO-UNDO.
DEFINE NEW SHARED VARIABLE nytid AS DECIMAL FORMAT "99.99" NO-UNDO.
DEFINE NEW SHARED VARIABLE sekunder AS INTEGER NO-UNDO.    
DEFINE NEW SHARED VARIABLE korvar AS CHARACTER NO-UNDO.

DEFINE VARIABLE antal LIKE TIDREGITAB.LONTILLANTAL NO-UNDO.   /*LÖN*/
DEFINE VARIABLE antalet LIKE PHJALP.PPAR8 NO-UNDO.   /*LÖN*/
DEFINE VARIABLE personal LIKE PERSONALTAB.PERSONALKOD.      /*LÖN*/
DEFINE VARIABLE pnr LIKE PERSONALTAB.PERSONNUMMER.      /*LÖN*/
DEFINE VARIABLE vecknr LIKE TIDREGITAB.VECKONUMMER.      /*LÖN*/
DEFINE VARIABLE overrapp1 AS CHARACTER FORMAT "X(70)".      /*LÖN*/
DEFINE VARIABLE overrapp2 AS CHARACTER FORMAT "X(70)".      /*ÖVERTID*/
DEFINE VARIABLE overrapp3 AS CHARACTER FORMAT "X(70)".      /*BEREEDSKAP*/
DEFINE VARIABLE overrapp4 AS CHARACTER FORMAT "X(70)".      /*TRAKTAMENTE*/
DEFINE VARIABLE rapphj1 AS CHARACTER FORMAT "X(9)".      /*HJÄLP ANTAL*/
DEFINE VARIABLE rapphj2 AS CHARACTER FORMAT "X(11)".      /*HJÄLP belopp*/
DEFINE VARIABLE datrapphj1 AS DATE FORMAT "999999".      /*HJÄLP datum*/
DEFINE VARIABLE rec AS RECID.
DEFINE VARIABLE para AS LOGICAL NO-UNDO.
DEFINE VARIABLE avtal1 LIKE PERSONALTAB.ANSTALLNING NO-UNDO.
DEFINE VARIABLE avtal LIKE ANSTFORMTAB.KOD NO-UNDO.  
DEFINE VARIABLE oversum AS INTEGER NO-UNDO. 
DEFINE VARIABLE total AS INTEGER NO-UNDO.
DEFINE VARIABLE oa1 AS INTEGER NO-UNDO.
DEFINE VARIABLE oa2 AS INTEGER NO-UNDO.
DEFINE VARIABLE oa3 AS INTEGER NO-UNDO.
DEFINE VARIABLE t2 AS INTEGER NO-UNDO.
DEFINE VARIABLE t3 AS INTEGER NO-UNDO.
DEFINE VARIABLE bryt AS LOGICAL NO-UNDO.
DEFINE VARIABLE nod AS LOGICAL NO-UNDO.
DEFINE VARIABLE seku AS INTEGER NO-UNDO.
DEFINE VARIABLE anstperson LIKE PERSONALTAB.PERSONNUMMER NO-UNDO.
DEFINE VARIABLE musz AS LOGICAL NO-UNDO.

   /*
DEFINE TEMP-TABLE lonefil
   FIELD PPERSONNUMMER LIKE PERSONALTAB.PERSONNUMMER
   FIELD START LIKE TIDREGITAB.START
   FIELD SLUT LIKE TIDREGITAB.SLUT
   FIELD PLONTILLAGG LIKE TIDREGITAB.LONTILLAGG
   FIELD PLONTILLANTAL LIKE TIDREGITAB.LONTILLANTAL
   FIELD POVERTIDTILL LIKE TIDREGITAB.OVERTIDTILL
   FIELD POVERANTAL LIKE TIDREGITAB.OVERANTAL
   FIELD PTRAKTKOD LIKE TIDREGITAB.TRAKTKOD
   FIELD PTRAKTANTAL LIKE TIDREGITAB.TRAKTANTAL
   FIELD PBEREDSKAP LIKE TIDREGITAB.BEREDSKAP
   FIELD PBERANTAL LIKE TIDREGITAB.BERANTAL
   FIELD PDATUM LIKE TIDREGITAB.DATUM
   FIELD SLUTDATUM LIKE TIDREGITAB.DATUM INITIAL ?
   FIELD PVECKONUMMER LIKE TIDREGITAB.VECKONUMMER
   FIELD MANAD AS INTEGER
   FIELD PSORT AS CHARACTER FORMAT "XX"
   FIELD PPAR8 AS DECIMAL FORMAT "-99.99"
   FIELD AONR LIKE TIDREGITAB.AONR
   FIELD DELNR LIKE TIDREGITAB.DELNR
   FIELD PAVTAL AS CHARACTER
   FIELD TID AS LOGICAL
   FIELD BERKOLL AS LOGICAL INITIAL FALSE
   FIELD PROCENT AS DECIMAL FORMAT "999.9"
   FIELD NAMN AS CHARACTER
   FIELD RESMAL AS CHARACTER
   FIELD ERSATTNING AS DECIMAL    
   INDEX PPERSONNUMMER IS PRIMARY PPERSONNUMMER ASCENDING PLONTILLAGG POVERTIDTILL PTRAKTKOD PBEREDSKAP PDATUM.
     */
DEFINE OUTPUT PARAMETER TABLE FOR lonefil.   
DEFINE BUFFER r3buff FOR lonefil.

FUNCTION klock100 RETURNS DECIMAL
  ( INPUT ber60 AS DECIMAL ):
/*------------------------------------------------------------------------------
  Purpose:  
    Notes:  
------------------------------------------------------------------------------*/

  RETURN  (TRUNCATE(ber60,0) * 3600 + (ber60 - TRUNCATE(ber60,0)) * 100 * 60) / 3600.

END FUNCTION.

EMPTY TEMP-TABLE lonefil NO-ERROR.    
FIND FIRST FORETAG USE-INDEX FORETAG NO-LOCK NO-ERROR.
globforetag = FORETAG.FORETAG.
ASSIGN
globanv = koranv
vkdatum = kordatum
korvar = gkorvar.
OPEN QUERY pq FOR EACH PERSONALTAB WHERE PERSONALTAB.PERSMASK = TRUE
AND PERSONALTAB.BRAVO = TRUE
USE-INDEX PERSONALKOD NO-LOCK.
GET FIRST pq NO-LOCK.
DO WHILE AVAILABLE(PERSONALTAB):
   personal = PERSONALTAB.PERSONALKOD.
   avtal1 = PERSONALTAB.ANSTALLNING.
   FIND FIRST ANSTFORMTAB WHERE ANSTFORMTAB.ANSTALLNING = avtal1
   USE-INDEX ANSTF NO-LOCK NO-ERROR.
   avtal = ANSTFORMTAB.KOD.
   FIND FIRST UTRYCKNING WHERE UTRYCKNING.KOD = avtal USE-INDEX UT
   NO-LOCK NO-ERROR.
   IF NOT AVAILABLE UTRYCKNING THEN para = FALSE.
   ELSE para = UTRYCKNING.PARA8.
   OPEN QUERY tq FOR EACH TIDREGITAB WHERE
   TIDREGITAB.PERSONALKOD = PERSONALTAB.PERSONALKOD AND
   TIDREGITAB.GODKAND BEGINS "G" AND TIDREGITAB.VECKOKORD = korvar AND
   TIDREGITAB.DATUM <= vkdatum
   USE-INDEX PSTART NO-LOCK.   
   GET FIRST tq NO-LOCK.
   DO WHILE AVAILABLE(TIDREGITAB):
      IF (TIDREGITAB.TRAKTKOD = " "  OR TIDREGITAB.TRAKTANTAL = 0) AND
      (TIDREGITAB.LONTILLAGG = " "  OR TIDREGITAB.LONTILLANTAL = 0) AND
      (TIDREGITAB.OKOD1 = " " OR TIDREGITAB.OANT1 = 0) AND
      (TIDREGITAB.OKOD2 = " " OR TIDREGITAB.OANT2 = 0) AND
      (TIDREGITAB.OKOD3 = " " OR TIDREGITAB.OANT3 = 0) AND
      (TIDREGITAB.BEREDSKAP = " " OR TIDREGITAB.BERANTAL = 0)
      THEN DO:
         IF PERSONALTAB.BEFATTNING = "TIMANSTÄLLD" AND TIDREGITAB.TOTALT > 0 THEN DO:                                                                     
	         IF TIDREGITAB.PRISTYP = "FRÅNVARO." THEN nytid = nytid.
	         ELSE DO:
   	         CREATE lonefil.
   	         ASSIGN lonefil.PPERSONNUMMER = PERSONALTAB.PERSONNUMMER
   	         lonefil.PLONTILLAGG = "0237"
   	         lonefil.PLONTILLANTAL = TIDREGITAB.TOTALT
   	         lonefil.PDATUM = TIDREGITAB.DATUM
   	         lonefil.PVECKONUMMER = TIDREGITAB.VECKONUMMER
   	         lonefil.AONR = TIDREGITAB.AONR
   	         lonefil.DELNR = TIDREGITAB.DELNR
   	         lonefil.MANAD = MONTH(TIDREGITAB.DATUM)
   	         lonefil.PAVTAL = avtal
               lonefil.NAMN = PERSONALTAB.FORNAMN + " " + PERSONALTAB.EFTERNAMN.
               nytid = lonefil.PLONTILLANTAL.
               RUN TIMSEK.P.
               lonefil.PLONTILLANTAL = (sekunder / 3600).		 
	         END.    
         END.
      END.
      ELSE DO :    
	     IF TIDREGITAB.LONTILLAGG NE " " AND TIDREGITAB.LONTILLANTAL NE 0 THEN DO TRANSACTION:	                
   	     CREATE lonefil.
   	     ASSIGN lonefil.PPERSONNUMMER = PERSONALTAB.PERSONNUMMER
   	     lonefil.PLONTILLAGG = TIDREGITAB.LONTILLAGG
   	     lonefil.PLONTILLANTAL = TIDREGITAB.LONTILLANTAL
   	     lonefil.PDATUM = TIDREGITAB.DATUM
   	     lonefil.PVECKONUMMER = TIDREGITAB.VECKONUMMER
   	     lonefil.AONR = TIDREGITAB.AONR
           lonefil.DELNR = TIDREGITAB.DELNR
           lonefil.MANAD = MONTH(TIDREGITAB.DATUM)
           lonefil.PAVTAL = avtal
           lonefil.NAMN = PERSONALTAB.FORNAMN + " " + PERSONALTAB.EFTERNAMN
           lonefil.RESMAL = TIDREGITAB.RESMAL.
           FIND FIRST LONTILL WHERE LONTILL.LONTILLAGG = lonefil.PLONTILLAGG
           AND LONTILL.KOD = lonefil.PAVTAL USE-INDEX LON NO-LOCK NO-ERROR.       
           IF AVAILABLE LONTILL THEN DO:              
              IF LONTILL.ENHET = "TI" THEN DO:
                 nytid = lonefil.PLONTILLANTAL.
                 RUN TIMSEK.P.
                 lonefil.PLONTILLANTAL = (sekunder / 3600).	   
                 IF lonefil.PLONTILLAGG = "4506" OR lonefil.PLONTILLAGG = "4574" OR lonefil.PLONTILLAGG = "0237" THEN DO: 
                    IF ( lonefil.PLONTILLANTAL - TRUNCATE(lonefil.PLONTILLANTAL,0)) GE 0 AND ( lonefil.PLONTILLANTAL - TRUNCATE(lonefil.PLONTILLANTAL,0)) < 0.26 THEN lonefil.PLONTILLANTAL = TRUNCATE(lonefil.PLONTILLANTAL,0).
                    ELSE IF ( lonefil.PLONTILLANTAL - TRUNCATE(lonefil.PLONTILLANTAL,0)) GE 0.26  AND ( lonefil.PLONTILLANTAL - TRUNCATE(lonefil.PLONTILLANTAL,0)) < 0.76 THEN lonefil.PLONTILLANTAL = TRUNCATE(lonefil.PLONTILLANTAL,0) + 0.50.
                    ELSE  IF ( lonefil.PLONTILLANTAL - TRUNCATE(lonefil.PLONTILLANTAL,0)) GE 0.76  THEN lonefil.PLONTILLANTAL = TRUNCATE(lonefil.PLONTILLANTAL,0) + 1.                  
                 END.
              END.              
              IF lonefil.PLONTILLAGG = "0116" THEN DO: 
                 IF LONTILL.ENHET = "ST" THEN DO:                 
                    ASSIGN lonefil.PLONTILLANTAL = lonefil.PLONTILLANTAL * LONTILL.ERSATTNING.
                 END.
              END.
              IF lonefil.PLONTILLAGG = "0117" THEN DO:            
                 IF LONTILL.ENHET = "ST" THEN DO:                 
                    ASSIGN lonefil.PLONTILLANTAL = lonefil.PLONTILLANTAL * LONTILL.ERSATTNING.
                 END.
              END.
           END.
   	  END.          
        IF TIDREGITAB.OANT1 NE 0 OR TIDREGITAB.OANT2 NE 0 OR TIDREGITAB.OANT3 NE 0
   	  THEN DO TRANSACTION:                                                      
   	     nytid = TIDREGITAB.OANT1.
   	     RUN TIMSEK.P.
   	     oa1 = sekunder.  
   	     nytid = TIDREGITAB.OANT2.
   	     RUN TIMSEK.P. 
   	     oa2 = sekunder.
   	     oversum = oa1 + sekunder.
   	     nytid = TIDREGITAB.OANT3.
   	     RUN TIMSEK.P.
   	     oa3 = sekunder.
   	     oversum = oversum + sekunder.
   	     nytid = TIDREGITAB.TOTALT.
   	     RUN TIMSEK.P.
   	     total = sekunder.  
   	     /*IF TIDREGITAB.OVERAUTO = FALSE  THEN DO:  */
           DO:           
   	        IF OKOD1 NE "" THEN DO:
   	           CREATE lonefil.
   	           ASSIGN lonefil.PPERSONNUMMER = PERSONALTAB.PERSONNUMMER
   	           lonefil.POVERTIDTILL = TIDREGITAB.OKOD1
   	           lonefil.POVERANTAL = TIDREGITAB.OANT1
   	           lonefil.PDATUM = TIDREGITAB.DATUM
   	           lonefil.PVECKONUMMER = TIDREGITAB.VECKONUMMER
   	           lonefil.AONR = TIDREGITAB.AONR
                 lonefil.DELNR = TIDREGITAB.DELNR
                 lonefil.MANAD = MONTH(TIDREGITAB.DATUM)
                 lonefil.PAVTAL = avtal
                 lonefil.TID = TRUE
                 lonefil.START = TIDREGITAB.OST1
                 lonefil.SLUT = TIDREGITAB.OSL1
                 lonefil.NAMN = PERSONALTAB.FORNAMN + " " + PERSONALTAB.EFTERNAMN.
                 nytid = lonefil.POVERANTAL.
                 RUN TIMSEK.P.
                 lonefil.POVERANTAL = (sekunder / 3600).		 
   	        END.    
   	        IF OKOD2 NE "" THEN DO:
   	           CREATE lonefil.
   	           ASSIGN lonefil.PPERSONNUMMER = PERSONALTAB.PERSONNUMMER
   	           lonefil.POVERTIDTILL = TIDREGITAB.OKOD2
   	           lonefil.POVERANTAL = TIDREGITAB.OANT2
   	           lonefil.PDATUM = TIDREGITAB.DATUM
   	           lonefil.PVECKONUMMER = TIDREGITAB.VECKONUMMER
   	           lonefil.AONR = TIDREGITAB.AONR
   	           lonefil.DELNR = TIDREGITAB.DELNR
   	           lonefil.MANAD = MONTH(TIDREGITAB.DATUM)
   	           lonefil.PAVTAL = avtal
                 lonefil.TID = TRUE
                 lonefil.START = TIDREGITAB.OST2
                 lonefil.SLUT = TIDREGITAB.OSL2
                 lonefil.NAMN = PERSONALTAB.FORNAMN + " " + PERSONALTAB.EFTERNAMN.
                 nytid = lonefil.POVERANTAL.
                 RUN TIMSEK.P.
                 lonefil.POVERANTAL = (sekunder / 3600).
   	        END.   
   	        IF OKOD3 NE "" THEN DO:
   	           CREATE lonefil.
   	           ASSIGN lonefil.PPERSONNUMMER = PERSONALTAB.PERSONNUMMER
   	           lonefil.POVERTIDTILL = TIDREGITAB.OKOD3
   	           lonefil.POVERANTAL = TIDREGITAB.OANT3
   	           lonefil.PDATUM = TIDREGITAB.DATUM
   	           lonefil.PVECKONUMMER = TIDREGITAB.VECKONUMMER
   	           lonefil.AONR = TIDREGITAB.AONR
   	           lonefil.DELNR = TIDREGITAB.DELNR
   	           lonefil.MANAD = MONTH(TIDREGITAB.DATUM)
   	           lonefil.PAVTAL = avtal
                 lonefil.TID = TRUE                 
                 lonefil.START = TIDREGITAB.OST3
                 lonefil.SLUT = TIDREGITAB.OSL3
                 lonefil.NAMN = PERSONALTAB.FORNAMN + " " + PERSONALTAB.EFTERNAMN.
                 nytid = lonefil.POVERANTAL.
                 RUN TIMSEK.P.
                 lonefil.POVERANTAL = (sekunder / 3600).
   	        END.                                    
   	     END.
        END.
        IF TIDREGITAB.TRAKTKOD NE " " AND TIDREGITAB.TRAKTANTAL NE 0
   	  THEN DO TRANSACTION:
   	     CREATE lonefil.
   	     ASSIGN lonefil.PPERSONNUMMER = PERSONALTAB.PERSONNUMMER
   	     lonefil.PTRAKTKOD = TIDREGITAB.TRAKTKOD
   	     lonefil.PTRAKTANTAL = TIDREGITAB.TRAKTANTAL
   	     lonefil.PDATUM = TIDREGITAB.DATUM
   	     lonefil.PVECKONUMMER = TIDREGITAB.VECKONUMMER
   	     lonefil.AONR = TIDREGITAB.AONR
           lonefil.DELNR = TIDREGITAB.DELNR
           lonefil.MANAD = MONTH(TIDREGITAB.DATUM)
           lonefil.PAVTAL = PERSONALTAB.TRAAVTAL
           lonefil.TID = FALSE
           lonefil.NAMN = PERSONALTAB.FORNAMN + " " + PERSONALTAB.EFTERNAMN.
   	  END.
   	  IF TIDREGITAB.BEREDSKAP NE " " AND TIDREGITAB.BERANTAL NE 0
   	  THEN DO TRANSACTION:
   	     CREATE lonefil.
   	     ASSIGN lonefil.PPERSONNUMMER = PERSONALTAB.PERSONNUMMER
   	     lonefil.PBEREDSKAP = TIDREGITAB.BEREDSKAP
   	     lonefil.PBERANTAL = TIDREGITAB.BERANTAL
   	     lonefil.PDATUM = TIDREGITAB.DATUM
   	     lonefil.PVECKONUMMER = TIDREGITAB.VECKONUMMER
   	     lonefil.AONR = TIDREGITAB.AONR
           lonefil.DELNR = TIDREGITAB.DELNR
           lonefil.MANAD = MONTH(TIDREGITAB.DATUM)
           lonefil.PAVTAL = PERSONALTAB.BEREDSKAPSAVTAL
           lonefil.START = TIDREGITAB.BEREDSKAPSTART
           lonefil.SLUT = TIDREGITAB.BEREDSKAPSLUT
           lonefil.TID = TRUE
           lonefil.NAMN = PERSONALTAB.FORNAMN + " " + PERSONALTAB.EFTERNAMN.   
           nytid = lonefil.PBERANTAL.
           RUN TIMSEK.P.
           lonefil.PBERANTAL = (sekunder / 3600).
           /*/* markera luncher*/
           IF lonefil.START GE 11 AND lonefil.SLUT LE 13 THEN DO:
              ASSIGN
              lonefil.BERKOLL = TRUE.
              lonefil.ERSATTNING = klock100(lonefil.PBERANTAL).
           END.*/

   	  END.                    
        IF PERSONALTAB.BEFATTNING = "TIMANSTÄLLD" AND TIDREGITAB.TOTALT > 0 THEN DO:                                                                     
	         IF TIDREGITAB.PRISTYP = "FRÅNVARO." THEN nytid = nytid.
	         ELSE DO:
   	         CREATE lonefil.
   	         ASSIGN lonefil.PPERSONNUMMER = PERSONALTAB.PERSONNUMMER
   	         lonefil.PLONTILLAGG = "0237"
   	         lonefil.PLONTILLANTAL = TIDREGITAB.TOTALT
   	         lonefil.PDATUM = TIDREGITAB.DATUM
   	         lonefil.PVECKONUMMER = TIDREGITAB.VECKONUMMER
   	         lonefil.AONR = TIDREGITAB.AONR
   	         lonefil.DELNR = TIDREGITAB.DELNR
   	         lonefil.MANAD = MONTH(TIDREGITAB.DATUM)
   	         lonefil.PAVTAL = avtal
               lonefil.NAMN = PERSONALTAB.FORNAMN + " " + PERSONALTAB.EFTERNAMN.
               nytid = lonefil.PLONTILLANTAL.
               RUN TIMSEK.P.
               lonefil.PLONTILLANTAL = (sekunder / 3600).
	         END.    
         END.
      END.
      GET NEXT tq.
   END.
   GET NEXT pq.
END.
FOR EACH lonefil WHERE lonefil.PPERSONNUMMER = " ":
  DELETE lonefil.
END.
    
FOR EACH lonefil where lonefil.PLONTILLAGG NE "":
   FIND FIRST LONTILL WHERE LONTILL.LONTILLAGG = lonefil.PLONTILLAGG
   AND LONTILL.KOD = lonefil.PAVTAL USE-INDEX LON NO-LOCK NO-ERROR.
   IF AVAILABLE LONTILL AND LONTILL.TYPKOD = "BIL" THEN DELETE lonefil.
   ELSE IF AVAILABLE LONTILL THEN DO: 
      ASSIGN lonefil.PLONTILLAGG = LONTILL.VILART
      lonefil.ERSATTNING = LONTILL.ERSATTNING
      lonefil.PSORT = LONTILL.ENHET.
   END.
END.
FOR EACH lonefil where lonefil.POVERTIDTILL NE "":
   FIND FIRST OVERKOD WHERE OVERKOD.OVERTIDTILL = lonefil.POVERTIDTILL
   AND OVERKOD.KOD = lonefil.PAVTAL USE-INDEX OVER NO-LOCK NO-ERROR.
   IF AVAILABLE OVERKOD THEN DO: 
      ASSIGN lonefil.POVERTIDTILL = OVERKOD.VILART.      
   END.
END.
FOR EACH lonefil where lonefil.PBEREDSKAP NE "":
   FIND FIRST BERKOD WHERE BERKOD.BEREDSKAP = lonefil.PBEREDSKAP 
   AND BERKOD.BEREDSKAPSAVTAL = lonefil.PAVTAL USE-INDEX BERE NO-LOCK NO-ERROR.
   IF AVAILABLE BERKOD THEN DO: 
      ASSIGN lonefil.PBEREDSKAP = BERKOD.VILART.      
   END.
END.
FOR EACH lonefil where lonefil.PTRAKTKOD NE "":
   FIND FIRST TRAKTATAB WHERE TRAKTATAB.TRAKTKOD = lonefil.PTRAKTKOD
   AND TRAKTATAB.TRAAVTAL = lonefil.PAVTAL USE-INDEX TRAAV NO-LOCK NO-ERROR.
   IF AVAILABLE TRAKTATAB THEN DO: 
      ASSIGN lonefil.PTRAKTKOD = TRAKTATAB.VILART
      lonefil.ERSATTNING = TRAKTATAB.ERSATTNING.
   END.
END.
/*IF globforetag = "SUND" THEN DO: 
   OUTPUT TO D:\delad\server\pro9s\EXPORT\lon\tillagg.d NO-ECHO.
   FOR EACH lonefil BY lonefil.PERSONNUMMER:
      EXPORT lonefil.
   END.
END.*/

RUN sammut_UI (INPUT 2).   
   
  
   
