/*XT3.P*/
DEFINE VARIABLE h AS HANDLE.
DEFINE VARIABLE localPartName AS CHARACTER.
RUN XT3p.P PERSISTENT SET h .
RUN GET-NEXT IN h (OUTPUT localPartName).
DISPLAY localPartName WITH FRAME cc DOWN.
DOWN 1 WITH FRAME cc.
RUN GET-NEXT IN h (OUTPUT localPartName).

DISPLAY localPartName WITH FRAME cc DOWN.
/* Add a super procedure */
/*
RUN XT3S.P PERSISTENT SET h.
THIS-PROCEDURE:ADD-SUPER-PROCEDURE (h).

RUN FIRST-NEXT (OUTPUT localPartName).
DISPLAY localPartName.
RUN GET-NEXT (OUTPUT localPartName).
DISPLAY localPartName.
RUN LAST-NEXT (OUTPUT localPartName).
DISPLAY localPartName.
PROCEDURE FIRST-NEXT:
   DEFINE OUTPUT PARAMETER PNAMN AS CHAR.
   RUN SUPER (OUTPUT PNAMN).
END PROCEDURE.
PROCEDURE GET-NEXT:
   DEFINE OUTPUT PARAMETER PNAMN AS CHAR.   
   RUN SUPER (OUTPUT PNAMN).
END PROCEDURE.
PROCEDURE LAST-NEXT:
   DEFINE OUTPUT PARAMETER PNAMN AS CHAR.    
   RUN SUPER (OUTPUT PNAMN).
END PROCEDURE.
    
*/
