/*xt3S.p*/
PROCEDURE FIRST-NEXT:
   DEFINE OUTPUT PARAMETER PNAMN AS CHAR.
   FIND FIRST PERSONALTAB NO-LOCK NO-ERROR.
   IF NOT AVAILABLE PERSONALTAB THEN PNAMN = "X".
   ELSE 
   PNAMN = PERSONALTAB.FORNAMN.
END PROCEDURE.
PROCEDURE GET-NEXT:
   DEFINE OUTPUT PARAMETER PNAMN AS CHAR.
   FIND NEXT PERSONALTAB NO-LOCK NO-ERROR.
   IF NOT AVAILABLE PERSONALTAB THEN PNAMN = "X".
   ELSE 
   PNAMN = PERSONALTAB.FORNAMN.
END PROCEDURE.
PROCEDURE LAST-NEXT:
   DEFINE OUTPUT PARAMETER PNAMN AS CHAR.
   FIND LAST PERSONALTAB NO-LOCK NO-ERROR.
   IF NOT AVAILABLE PERSONALTAB THEN PNAMN = "X".
   ELSE 
   PNAMN = PERSONALTAB.FORNAMN.
END PROCEDURE.
