DEF VAR PKOD LIKE PERSONALTAB.PERSONALKOD NO-UNDO.
OPEN QUERY tidq FOR EACH TIDREGITAB WHERE TIDREGITAB.PERSONALKOD = "41010" AND
YEAR(TIDREGITAB.DATUM) = 1999
AND PRISTYP = "TOT.PRIS." NO-LOCK.
PKOD = "41010" .
FIND FIRST TIMKOSTNADSTAB 
WHERE TIMKOSTNADSTAB.PERSONALKOD = pkod AND
TIMKOSTNADSTAB.PRISTYP = 'TOT.PRIS.' USE-INDEX PRISPERS NO-LOCK NO-ERROR.
DO TRANSACTION:
   GET FIRST tidq EXCLUSIVE-LOCK.   
   IF AVAILABLE TIDREGITAB THEN DO:         
      ASSIGN TIDREGITAB.PRIS = TIMKOSTNADSTAB.PRISA.
   END.
END.
DO WHILE AVAILABLE(TIDREGITAB):
   DO TRANSACTION:
      GET NEXT tidq EXCLUSIVE-LOCK.
      IF AVAILABLE TIDREGITAB THEN DO:           
         ASSIGN TIDREGITAB.PRIS = TIMKOSTNADSTAB.PRISA.
      END.
   END.
END.
