DEF VAR PKOD LIKE PERSONALTAB.PERSONALKOD NO-UNDO.
DEF VAR PTYP LIKE TIMKOSTNADSTAB.PRISTYP NO-UNDO.
OPEN QUERY tidq FOR EACH TIDREGITAB WHERE YEAR(TIDREGITAB.DATUM) = 1999 AND 
VECKOKORD = "" AND PRISTYP = "TOT.PRIS." NO-LOCK.
PKOD = "" .
DO TRANSACTION:
   GET FIRST tidq EXCLUSIVE-LOCK.
   
   IF AVAILABLE TIDREGITAB THEN DO:   
      FIND FIRST AONRTAB WHERE AONRTAB.AONR = TIDREGITAB.AONR USE-INDEX AONR NO-LOCK
      NO-ERROR.
      IF AONRTAB.PRISTYP = TIDREGITAB.PRISTYP THEN PKOD = PKOD.
      ELSE DO:
         FIND FIRST TIMKOSTNADSTAB 
         WHERE TIMKOSTNADSTAB.PERSONALKOD = TIDREGITAB.PERSONALKOD AND
         TIMKOSTNADSTAB.PRISTYP = AONRTAB.PRISTYP USE-INDEX PRISPERS NO-LOCK NO-ERROR.   
         ASSIGN TIDREGITAB.PRISTYP = TIMKOSTNADSTAB.PRISTYP TIDREGITAB.PRIS = TIMKOSTNADSTAB.PRISA.
      END.      
/*      IF pkod ne TIDREGITAB.PERSONALKOD THEN DO:
         pkod = TIDREGITAB.PERSONALKOD.
         FIND FIRST TIMKOSTNADSTAB 
         WHERE TIMKOSTNADSTAB.PERSONALKOD = pkod AND
         TIMKOSTNADSTAB.PRISTYP = 'TOT.PRIS.' USE-INDEX PRISPERS NO-LOCK NO-ERROR.
      END.
      ASSIGN TIDREGITAB.PRIS = TIMKOSTNADSTAB.PRISA.*/
   END.
END.
DO WHILE AVAILABLE(TIDREGITAB):
   DO TRANSACTION:
      GET NEXT tidq EXCLUSIVE-LOCK.
      IF AVAILABLE TIDREGITAB THEN DO:   
         FIND FIRST AONRTAB WHERE AONRTAB.AONR = TIDREGITAB.AONR USE-INDEX AONR NO-LOCK
         NO-ERROR.
         IF AONRTAB.PRISTYP = TIDREGITAB.PRISTYP THEN PKOD = PKOD.
         ELSE DO:
            FIND FIRST TIMKOSTNADSTAB 
            WHERE TIMKOSTNADSTAB.PERSONALKOD = TIDREGITAB.PERSONALKOD AND
            TIMKOSTNADSTAB.PRISTYP = AONRTAB.PRISTYP USE-INDEX PRISPERS NO-LOCK NO-ERROR.   
            ASSIGN TIDREGITAB.PRISTYP = TIMKOSTNADSTAB.PRISTYP TIDREGITAB.PRIS = TIMKOSTNADSTAB.PRISA.
         END.      

/*         IF pkod ne TIDREGITAB.PERSONALKOD THEN DO:
            pkod = TIDREGITAB.PERSONALKOD.
            FIND FIRST TIMKOSTNADSTAB 
            WHERE TIMKOSTNADSTAB.PERSONALKOD = pkod AND
            TIMKOSTNADSTAB.PRISTYP = 'TOT.PRIS.' USE-INDEX PRISPERS NO-LOCK NO-ERROR.
         END.
         ASSIGN TIDREGITAB.PRIS = TIMKOSTNADSTAB.PRISA.*/
      END.
   END.
END.
