
DEFINE BUFFER A FOR BERMTRL.
DEFINE BUFFER B FOR BERMTRL.
OUTPUT TO C:\PROTEMP9\TRANS3.TXT.
OPEN QUERY bq FOR EACH MTRL WHERE MTRL.LEVKOD = "70" AND MTRL.KALKNR = 0 NO-LOCK,
EACH BERMTRL WHERE BERMTRL.ENR = MTRL.ENR AND BERMTRL.LEVKOD = "16"  NO-LOCK.
GET FIRST bq NO-LOCK.
DO WHILE AVAILABLE(BERMTRL):
   FIND FIRST A WHERE A.AONR = BERMTRL.AONR AND A.OMRADE = BERMTRL.OMRADE AND A.INKOP = TRUE NO-LOCK NO-ERROR.
   IF NOT AVAILABLE A THEN DO TRANSACTION:
      GET CURRENT bq EXCLUSIVE-LOCK.
      ASSIGN BERMTRL.LEVKOD = "70".
      /*PUT BERMTRL.AONR BERMTRL.OMRADE BERMTRL.ENR SKIP. */
   END.
   GET NEXT bq NO-LOCK.
END.
OUTPUT CLOSE.
