DEFINE INPUT PARAMETER  VV AS CHAR.   
  FOR EACH FAKTUPPARB WHERE aonr = vv BY FAKTUPPARB.UPLAN%:
   DISPLAY
   FAKTUPPARB.ORDNING 
   FAKTUPPARB.FAKTURERAD 

   FAKTUPPARB.FAKT% 
   FAKTUPPARB.FAKTBELOPP FORMAT ">>>>>>>>>9.<<"
   FAKTUPPARB.FULL 
   FAKTUPPARB.UPLAN% 
   FAKTUPPARB.UPPARB% 
   FAKTUPPARB.UPPBELOPP 

 .
   IF FULL = FALSE THEN UPDATE                             
      FULL FAKTUPPARB.UPPARB% FAKTUPPARB.UPPBELOPP FORMAT ">>>>>>>>>9.<<".
   END.
