 /*vattve.P*/
 DEFINE new SHARED VARIABLE vdatum AS DATE NO-UNDO.
DEFINE new SHARED VARIABLE xdatum AS DATE NO-UNDO.
DEFINE SHARED VARIABLE panytid AS DECIMAL NO-UNDO.
DEFINE SHARED VARIABLE nytid AS DECIMAL FORMAT "99.99" NO-UNDO.
DEFINE SHARED VARIABLE sekunder AS INTEGER FORMAT "-9999999" NO-UNDO.
DEFINE SHARED VARIABLE seku AS INTEGER NO-UNDO.
DEFINE SHARED VARIABLE globforetag LIKE FORETAG.FORETAG NO-UNDO.
DEFINE SHARED VARIABLE vkdatum AS DATE NO-UNDO.
DEFINE SHARED VARIABLE gvisatidpermanad AS LOGICAL NO-UNDO.

DEFINE VARIABLE antal LIKE TIDREGITAB.LONTILLANTAL NO-UNDO.   /*L™N*/
DEFINE VARIABLE antalet LIKE PHJALP.PPAR8 NO-UNDO.   /*L™N*/
DEFINE VARIABLE personal LIKE PERSONALTAB.PERSONALKOD.      /*L™N*/
DEFINE VARIABLE pnr LIKE PERSONALTAB.PERSONNUMMER.      /*L™N*/
DEFINE VARIABLE vecknr LIKE TIDREGITAB.VECKONUMMER.      /*L™N*/
DEFINE VARIABLE overrapp1 AS CHARACTER FORMAT "X(70)".      /*L™N*/
DEFINE VARIABLE overrapp2 AS CHARACTER FORMAT "X(70)".      /*™VERTID*/
DEFINE VARIABLE overrapp3 AS CHARACTER FORMAT "X(70)".      /*BEREEDSKAP*/
DEFINE VARIABLE overrapp4 AS CHARACTER FORMAT "X(70)".      /*TRAKTAMENTE*/
DEFINE VARIABLE rapphj1 AS CHARACTER FORMAT "X(9)".      /*HJŽLP ANTAL*/
DEFINE VARIABLE rapphj2 AS CHARACTER FORMAT "X(11)".      /*HJŽLP belopp*/
DEFINE VARIABLE datrapphj1 AS DATE FORMAT "999999".      /*HJŽLP datum*/
DEFINE VARIABLE rec AS RECID.
DEFINE VARIABLE para AS LOGICAL NO-UNDO.
DEFINE VARIABLE avtal1 LIKE PERSONALTAB.ANSTALLNING NO-UNDO.
DEFINE VARIABLE avtal LIKE ANSTFORMTAB.KOD NO-UNDO.
DEFINE NEW SHARED WORKFILE pa90fil
   FIELD PPERSONNUMMER LIKE PERSONALTAB.PERSONNUMMER
   FIELD PLONTILLAGG LIKE TIDREGITAB.LONTILLAGG
   FIELD PLONTILLANTAL LIKE TIDREGITAB.LONTILLANTAL
   FIELD POVERTIDTILL LIKE TIDREGITAB.OVERTIDTILL
   FIELD POVERANTAL LIKE TIDREGITAB.OVERANTAL
   FIELD PTRAKTKOD LIKE TIDREGITAB.TRAKTKOD
   FIELD PTRAKTANTAL LIKE TIDREGITAB.TRAKTANTAL
   FIELD PBEREDSKAP LIKE TIDREGITAB.BEREDSKAP
   FIELD PBERANTAL LIKE TIDREGITAB.BERANTAL
   FIELD PDATUM LIKE TIDREGITAB.DATUM
   FIELD PVECKONUMMER LIKE TIDREGITAB.VECKONUMMER
   FIELD PSORT AS CHARACTER FORMAT "XX"
   FIELD PPAR8 AS DECIMAL FORMAT "-99.99"
   FIELD PANSTNR LIKE PERSONALTAB.ANSTNR.
FOR EACH pa90fil:
  DELETE pa90fil.
END.
slinga:
REPEAT:
  FIND NEXT PERSONALTAB WHERE PERSONALTAB.PERSMASK = TRUE
  USE-INDEX PERSONALKOD NO-LOCK NO-ERROR.
  IF NOT AVAILABLE PERSONALTAB THEN DO:
    LEAVE slinga.
  END.
  ELSE DO:
    personal = PERSONALTAB.PERSONALKOD.
    avtal1 = PERSONALTAB.ANSTALLNING.
    FIND FIRST ANSTFORMTAB WHERE ANSTFORMTAB.ANSTALLNING = avtal1
    USE-INDEX ANSTF NO-LOCK NO-ERROR.
    avtal = ANSTFORMTAB.KOD.
    FIND FIRST UTRYCKNING WHERE UTRYCKNING.KOD = avtal USE-INDEX UT
    NO-LOCK NO-ERROR.
    IF NOT AVAILABLE UTRYCKNING THEN para = FALSE.
    ELSE para = UTRYCKNING.PARA8.
    FIND FIRST TIDREGITAB USE-INDEX PKOD NO-LOCK NO-ERROR.
    BLOCK12:
    REPEAT:
      FIND NEXT TIDREGITAB WHERE TIDREGITAB.PERSONALKOD = personal
      AND TIDREGITAB.VECKOKORD = " "
      USE-INDEX PSTART NO-LOCK NO-ERROR.
      IF NOT AVAILABLE TIDREGITAB THEN LEAVE BLOCK12.
      IF TIDREGITAB.GODKAND = '' THEN NEXT BLOCK12.
      LEAVE BLOCK12.
    END.
    IF NOT AVAILABLE TIDREGITAB THEN DO:
      personal = personal.
    END.
    ELSE DO:
      rapp1:
      REPEAT:
       IF (TIDREGITAB.TRAKTKOD = " "  OR TIDREGITAB.TRAKTANTAL = 0) AND
       (TIDREGITAB.LONTILLAGG = " "  OR TIDREGITAB.LONTILLANTAL = 0) AND
       (TIDREGITAB.OVERTIDTILL = " " OR TIDREGITAB.OVERANTAL = 0) AND
       (TIDREGITAB.BEREDSKAP = " " OR TIDREGITAB.BERANTAL = 0)
       THEN DO:
	  personal = personal.
       END.
       ELSE DO :
	 IF TIDREGITAB.LONTILLAGG NE " " AND TIDREGITAB.LONTILLANTAL NE 0
	 THEN DO TRANSACTION:
	    CREATE pa90fil.
	    ASSIGN pa90fil.PPERSONNUMMER = PERSONALTAB.PERSONNUMMER
	    pa90fil.PLONTILLAGG = TIDREGITAB.LONTILLAGG
	    pa90fil.PLONTILLANTAL = TIDREGITAB.LONTILLANTAL
	    pa90fil.PDATUM = TIDREGITAB.DATUM
	    pa90fil.PVECKONUMMER = TIDREGITAB.VECKONUMMER.
	 END.
	 IF TIDREGITAB.OVERTIDTILL NE " " AND TIDREGITAB.OVERANTAL NE 0
	 THEN DO TRANSACTION:
	    CREATE pa90fil.
	    ASSIGN pa90fil.PPERSONNUMMER = PERSONALTAB.PERSONNUMMER
	    pa90fil.POVERTIDTILL = TIDREGITAB.OVERTIDTILL
	    pa90fil.POVERANTAL = TIDREGITAB.OVERANTAL.
	    panytid = TIDREGITAB.TOTALT.
	    RUN PATIMSEK.P.
	    seku = sekunder.
	    panytid = TIDREGITAB.OVERANTAL.
	    RUN PATIMSEK.P.
	    sekunder = seku - sekunder.
	    RUN PASEKTIM.P.
	    IF TIDREGITAB.OVERAUTO = TRUE AND para = TRUE THEN DO:
	       ASSIGN pa90fil.PPAR8 = panytid.
	    END.
	    ELSE DO:
	      ASSIGN pa90fil.PPAR8 = 0.
	    END.
	    seku = 0.
	    sekunder = 0.
	    ASSIGN pa90fil.PDATUM = TIDREGITAB.DATUM
	    pa90fil.PVECKONUMMER = TIDREGITAB.VECKONUMMER.
	 END.
	 IF TIDREGITAB.TRAKTKOD NE " " AND TIDREGITAB.TRAKTANTAL NE 0
	 THEN DO TRANSACTION:
	    CREATE pa90fil.
	    ASSIGN pa90fil.PPERSONNUMMER = PERSONALTAB.PERSONNUMMER
	    pa90fil.PTRAKTKOD = TIDREGITAB.TRAKTKOD
	    pa90fil.PTRAKTANTAL = TIDREGITAB.TRAKTANTAL
	    pa90fil.PDATUM = TIDREGITAB.DATUM
	    pa90fil.PVECKONUMMER = TIDREGITAB.VECKONUMMER.
	 END.
	 IF TIDREGITAB.BEREDSKAP NE " " AND TIDREGITAB.BERANTAL NE 0
	 THEN DO TRANSACTION:
	    CREATE pa90fil.
	    ASSIGN pa90fil.PPERSONNUMMER = PERSONALTAB.PERSONNUMMER
	    pa90fil.PBEREDSKAP = TIDREGITAB.BEREDSKAP
	    pa90fil.PBERANTAL = TIDREGITAB.BERANTAL
	    pa90fil.PDATUM = TIDREGITAB.DATUM
	    pa90fil.PVECKONUMMER = TIDREGITAB.VECKONUMMER.
	 END.
       END.
       BLOCK2:
       REPEAT:
	 FIND NEXT TIDREGITAB WHERE TIDREGITAB.PERSONALKOD = personal
	 AND TIDREGITAB.VECKOKORD = " "
	 USE-INDEX PSTART NO-LOCK NO-ERROR.
	 IF NOT AVAILABLE TIDREGITAB THEN LEAVE BLOCK2.
	 IF TIDREGITAB.GODKAND = '' THEN NEXT BLOCK2.
	 LEAVE BLOCK2.
       END.
       IF NOT AVAILABLE TIDREGITAB THEN DO:
	 LEAVE rapp1.
       END.
      END. /*REPEAT*/
    END.
  END.
END.
FIND FIRST pa90fil WHERE pa90fil.PLONTILLAGG = "9008" NO-LOCK NO-ERROR.
IF NOT AVAILABLE pa90fil THEN DO:
  personal = personal.
END.
ELSE DO:
  rec = RECID(pa90fil).
  pnr = pa90fil.PPERSONNUMMER.
  vecknr = pa90fil.PVECKONUMMER.
  DO TRANSACTION:
     FIND FIRST pa90fil WHERE pa90fil.PPERSONNUMMER = pnr AND
     pa90fil.PVECKONUMMER = vecknr AND pa90fil.PPAR8 NE 0
     EXCLUSIVE-LOCK NO-ERROR.
     IF NOT AVAILABLE pa90fil THEN DO:
	personal = personal.
     END.
     ELSE DO:
	ASSIGN pa90fil.PPAR8 = 0.
	ett:
	REPEAT:
	   FIND NEXT pa90fil WHERE pa90fil.PPERSONNUMMER = pnr AND
	   pa90fil.PVECKONUMMER = vecknr AND pa90fil.PPAR8 NE 0
	   EXCLUSIVE-LOCK NO-ERROR.
	   IF NOT AVAILABLE pa90fil THEN LEAVE ett.
	   ASSIGN pa90fil.PPAR8 = 0.
	END.
     END.
  END.
  tva:
  REPEAT:
    FIND FIRST pa90fil WHERE RECID(pa90fil) = rec NO-LOCK NO-ERROR.
    FIND NEXT pa90fil WHERE pa90fil.PLONTILLAGG = "9008"
    NO-LOCK NO-ERROR.
    IF NOT AVAILABLE pa90fil THEN LEAVE tva.
    ELSE DO:
      rec = RECID(pa90fil).
      pnr = pa90fil.PPERSONNUMMER.
      vecknr = pa90fil.PVECKONUMMER.
      DO TRANSACTION:
	 FIND FIRST pa90fil WHERE pa90fil.PPERSONNUMMER = pnr AND
	 pa90fil.PVECKONUMMER = vecknr AND pa90fil.PPAR8 NE 0
	 EXCLUSIVE-LOCK NO-ERROR.
	 IF NOT AVAILABLE pa90fil THEN DO:
	    personal = personal.
	 END.
	 ELSE DO:
	    ASSIGN pa90fil.PPAR8 = 0.
	 END.
      END.
      IF NOT AVAILABLE pa90fil THEN DO:
	 personal = personal.
      END.
      ELSE DO:
	 tre:
	 REPEAT:
	    DO TRANSACTION:
	       FIND NEXT pa90fil WHERE pa90fil.PPERSONNUMMER = pnr AND
	       pa90fil.PVECKONUMMER = vecknr AND pa90fil.PPAR8 NE 0
	       EXCLUSIVE-LOCK NO-ERROR.
	       IF NOT AVAILABLE pa90fil THEN LEAVE tre.
	       ASSIGN pa90fil.PPAR8 = 0.
	    END.
	 END. /*repeat tre*/
      END.
    END.
  END.
END.
DO TRANSACTION:
   FIND FIRST pa90fil WHERE pa90fil.PPAR8 NE 0
   EXCLUSIVE-LOCK NO-ERROR.
   IF NOT AVAILABLE pa90fil THEN DO:
      personal = personal.
   END.
   ELSE DO:
      pnr = pa90fil.PPERSONNUMMER.
      antalet = pa90fil.PPAR8.
      datrapphj1 = pa90fil.PDATUM.
      vecknr = pa90fil.PVECKONUMMER.
      ASSIGN pa90fil.PPAR8 = 0.
      CREATE pa90fil.
      ASSIGN pa90fil.PPERSONNUMMER = pnr
      pa90fil.PLONTILLAGG = "9008"
      pa90fil.PLONTILLANTAL = antalet
      pa90fil.PDATUM = datrapphj1
      pa90fil.PVECKONUMMER = vecknr.
   END.
END.
IF NOT AVAILABLE pa90fil THEN DO:
   personal = personal.
END.
ELSE DO:
   block1:
   REPEAT:
      DO TRANSACTION:
	 FIND NEXT pa90fil WHERE pa90fil.PPAR8 NE 0
	 EXCLUSIVE-LOCK NO-ERROR.
	 IF NOT AVAILABLE pa90fil THEN LEAVE block1.
	 ELSE DO:
	    pnr = pa90fil.PPERSONNUMMER.
	    antalet = pa90fil.PPAR8.
	    datrapphj1 = pa90fil.PDATUM.
	    vecknr = pa90fil.PVECKONUMMER.
	    ASSIGN pa90fil.PPAR8 = 0.
	    CREATE pa90fil.
	    ASSIGN pa90fil.PPERSONNUMMER = pnr
	    pa90fil.PLONTILLAGG = "9008"
	    pa90fil.PLONTILLANTAL = antalet
	    pa90fil.PDATUM = datrapphj1
	    pa90fil.PVECKONUMMER = vecknr.
	 END.
      END.
   END.
END.
FOR EACH pa90fil WHERE pa90fil.PPERSONNUMMER = " ":
  DELETE pa90fil.
END.
IF OPSYS = "MSDOS" THEN DO:
  OUTPUT TO G:\plusd\atr\export\pa90hj.d.
END.
IF OPSYS = "UNIX" THEN DO:
  IF globforetag = "KALI" THEN DO:
    OUTPUT TO /applik/atr/pa90hj.d.
  END.
  ELSE OUTPUT TO /ekonomi/atr/pa90hj.d.
END.
FOR EACH pa90fil
BY PPERSONNUMMER BY PLONTILLAGG BY POVERTIDTILL BY PTRAKTKOD BY PBEREDSKAP:
  EXPORT pa90fil.PPERSONNUMMER pa90fil.PLONTILLAGG pa90fil.PLONTILLANTAL
  pa90fil.POVERTIDTILL pa90fil.POVERANTAL
  pa90fil.PTRAKTKOD pa90fil.PTRAKTANTAL pa90fil.PBEREDSKAP pa90fil.PBERANTAL.
END.
OUTPUT CLOSE.
RUN LONRA4.P. /*summerar veckans sk”rd */
RUN LONRA5.P.      /* summerar veckans sk”rd till tidigare */
