/*KALKYL*/
DEFINE VARIABLE valkalknr AS INTEGER NO-UNDO.
DEFINE VARIABLE bytomr AS CHARACTER NO-UNDO.

ASSIGN
valkalknr = 11111
bytomr = "xxx".

OPEN QUERY kkq FOR EACH FASTKALK WHERE FASTKALK.KALKNR = valkalknr
NO-LOCK.
DO TRANSACTION:
   GET FIRST kkq EXCLUSIVE-LOCK.
   IF AVAILABLE FASTKALK THEN DO:
      FASTKALK.OMRADE = bytomr.
   END.
END.
REPEAT:
   DO TRANSACTION:
      GET NEXT kkq EXCLUSIVE-LOCK.
      IF AVAILABLE FASTKALK THEN DO:
         FASTKALK.OMRADE = bytomr.
      END.
      ELSE LEAVE.
   END.
END.
CLOSE QUERY kkq.
OPEN QUERY befq FOR EACH KALKBEF WHERE KALKBEF.KALKNR = valkalknr
NO-LOCK.
DO TRANSACTION:
   GET FIRST befq EXCLUSIVE-LOCK.
   IF AVAILABLE KALKBEF THEN DO:
      KALKBEF.OMRADE = bytomr.
   END.
END.
REPEAT:
   DO TRANSACTION:
      GET NEXT befq EXCLUSIVE-LOCK.
      IF AVAILABLE KALKBEF THEN DO:
         KALKBEF.OMRADE = bytomr.
      END.
      ELSE LEAVE.
   END.
END.
CLOSE QUERY befq.

OPEN QUERY fq FOR EACH FAKTOR WHERE FAKTOR.KALKNR = valkalknr NO-LOCK.
DO TRANSACTION:
   GET FIRST fq EXCLUSIVE-LOCK.
   IF AVAILABLE FAKTOR THEN DO:
      FAKTOR.OMRADE = bytomr.
   END.
END.
REPEAT:
   GET NEXT fq EXCLUSIVE-LOCK.
   IF AVAILABLE FAKTOR THEN DO:
      FAKTOR.OMRADE = bytomr.
   END.
   ELSE LEAVE.
END.
CLOSE QUERY fq.

OPEN QUERY mtrlq FOR EACH FASTSPEC WHERE FASTSPEC.KALKNR = valkalknr
NO-LOCK.
DO TRANSACTION:
   GET FIRST mtrlq EXCLUSIVE-LOCK.
   IF AVAILABLE FASTSPEC THEN DO:
      FASTSPEC.OMRADE = bytomr.
   END.
END.
REPEAT:
   DO TRANSACTION:
      GET NEXT mtrlq EXCLUSIVE-LOCK.
      IF AVAILABLE FASTSPEC THEN DO:
         FASTSPEC.OMRADE = bytomr.
      END.
      ELSE LEAVE.
   END.
END.
