/* refCallee.p */
{dsOrderTT.i}
{dsOrder.i}

DEFINE VARIABLE hDset AS HANDLE NO-UNDO.

DEFINE DATA-SOURCE srcOrder FOR Customer.
DEFINE DATA-SOURCE srcOline FOR OrderLine.
DEFINE DATA-SOURCE srcItem  FOR Item.

hDset = DATASET dsorder:HANDLE.
hDset:GET-BUFFER-HANDLE(1):ATTACH-DATA-SOURCE(DATA-SOURCE srcOrder:HANDLE).
hDset:GET-BUFFER-HANDLE(2):ATTACH-DATA-SOURCE(DATA-SOURCE srcOline:HANDLE).
hDset:GET-BUFFER-HANDLE(3):ATTACH-DATA-SOURCE(DATA-SOURCE srcItem:HANDLE).

PROCEDURE fillProc:
  DEFINE OUTPUT PARAMETER DATASET FOR dsOrder.

  DATASET dsOrder:FILL().
END PROCEDURE.
