/*ANVAPPTO.P*/
DEFINE INPUT PARAMETER globanv AS CHARACTER NO-UNDO.
DEFINE OUTPUT PARAMETER globsids AS INTEGER NO-UNDO.
DEFINE OUTPUT PARAMETER globsidl AS INTEGER NO-UNDO.
DEBUGGER:SET-BREAK().
IF globanv NE "" THEN DO TRANSACTION:
   FIND FIRST ANVANDARE WHERE ANVANDARE.ANVANDARE = globanv 
   NO-LOCK NO-ERROR.
   IF AVAILABLE ANVANDARE THEN DO:  
      ASSIGN 
      globsidl = ANVANDARE.SIDL  
      globsids = ANVANDARE.SIDS.          
   END.
END.

