/*BESTSKAP.P*/
DEFINE TEMP-TABLE besttemp
   FIELD BBESTID LIKE BESTTAB.BESTID
   FIELD BBESTNAMN LIKE BESTTAB.BESTNAMN 
   INDEX BBEST IS PRIMARY BBESTID ASCENDING
   INDEX BBESTN BBESTNAMN ASCENDING.
DEFINE INPUT PARAMETER val AS INTEGER NO-UNDO.   
DEFINE OUTPUT PARAMETER TABLE FOR besttemp .
IF val = 1 THEN DO:
   OPEN QUERY bq FOR EACH BESTTAB USE-INDEX BEST NO-LOCK.
   GET FIRST bq NO-LOCK.
   DO WHILE AVAILABLE(BESTTAB):
      CREATE besttemp.
      ASSIGN besttemp.BBESTID = BESTTAB.BESTID 
      besttemp.BBESTNAMN = BESTTAB.BESTNAMN.
      GET NEXT bq NO-LOCK.
   END.
END.
IF val = 2 THEN DO:
   /*endast kunder som får kopplas till aonr med mera*/
   OPEN QUERY bq FOR EACH BESTTAB WHERE BESTTAB.AOKUND = TRUE 
   USE-INDEX BEST NO-LOCK.
   GET FIRST bq NO-LOCK.
   DO WHILE AVAILABLE(BESTTAB):
      CREATE besttemp.
      ASSIGN besttemp.BBESTID = BESTTAB.BESTID 
      besttemp.BBESTNAMN = BESTTAB.BESTNAMN.
      GET NEXT bq NO-LOCK.
   END.
END.
