/*BYTANV.P*/
{LOGSEKREGTT.I}
DEFINE INPUT PARAMETER gamanv LIKE ANVANDARE.ANVANDARE NO-UNDO.
DEFINE INPUT PARAMETER nyanv LIKE ANVANDARE.ANVANDARE NO-UNDO.
DEFINE INPUT  PARAMETER gavanv AS CHARACTER NO-UNDO.
DEFINE VARIABLE musz AS LOGICAL NO-UNDO.
OPEN QUERY persekq FOR EACH PERSEK WHERE PERSEK.ANVANDARE = gamanv
NO-LOCK. 
GET FIRST persekq NO-LOCK.
DO WHILE AVAILABLE(PERSEK):
   DO TRANSACTION:
      GET CURRENT persekq EXCLUSIVE-LOCK.
      CREATE logsekregTT.
      ASSIGN 
      logsekregTT.ANVANDARE = PERSEK.ANVANDARE
      logsekregTT.DATUM  = NOW 
      logsekregTT.AVANVANDARE = gavanv
      logsekregTT.PROGRAM = THIS-PROCEDURE:NAME 
      logsekregTT.TYP = "PERS"
      logsekregTT.PERSONALKOD = PERSEK.PERSONALKOD
      logsekregTT.TILLFRAN = FALSE.
      RUN LOGSEKREG.P (INPUT TABLE logsekregTT).
      DELETE logsekregTT.   
      DELETE PERSEK.      
   END.
   GET NEXT persekq NO-LOCK.
END.
OPEN QUERY tidsekq FOR EACH TIDSEK WHERE TIDSEK.ANVANDARE = gamanv
NO-LOCK. 
GET FIRST tidsekq NO-LOCK.
DO WHILE AVAILABLE(TIDSEK):
   DO TRANSACTION:
      GET CURRENT tidsekq EXCLUSIVE-LOCK.
      CREATE logsekregTT.
      ASSIGN 
      logsekregTT.ANVANDARE = TIDSEK.ANVANDARE
      logsekregTT.DATUM  = NOW 
      logsekregTT.AVANVANDARE =  gavanv
      logsekregTT.PROGRAM = THIS-PROCEDURE:NAME 
      logsekregTT.TYP = "TID"
      logsekregTT.PERSONALKOD = TIDSEK.PERSONALKOD
      logsekregTT.TILLFRAN = FALSE.
      RUN LOGSEKREG.P (INPUT TABLE logsekregTT).
      DELETE logsekregTT. 
      DELETE TIDSEK.      
   END.
   GET NEXT tidsekq NO-LOCK.
END.
OPEN QUERY omrsekq FOR EACH OMRSEK WHERE OMRSEK.ANVANDARE = gamanv
NO-LOCK. 
GET FIRST omrsekq NO-LOCK.
DO WHILE AVAILABLE(OMRSEK):
   DO TRANSACTION:
      GET CURRENT omrsekq EXCLUSIVE-LOCK.
      DELETE OMRSEK.      
   END.
   GET NEXT omrsekq NO-LOCK.
END.


OPEN QUERY aonrsekq FOR EACH AONRTAB WHERE AONRTAB.ANVANDARE = gamanv
NO-LOCK. 
DO TRANSACTION:       
   GET FIRST aonrsekq EXCLUSIVE-LOCK.
   IF AVAILABLE AONRTAB THEN AONRTAB.ANVANDARE = nyanv.
END.
REPEAT:  
   DO TRANSACTION:
      GET NEXT aonrsekq EXCLUSIVE-LOCK.         
      IF AVAILABLE AONRTAB THEN AONRTAB.ANVANDARE = nyanv.    
      ELSE LEAVE.      
   END.         
END.
RUN FINNSTABELL.P (INPUT "FAKTURADM", OUTPUT musz).
IF musz = TRUE THEN RUN  BYTANVSTEG2.P  (INPUT gamanv, INPUT nyanv).
OPEN QUERY mq FOR EACH MTRL WHERE MTRL.LEVKOD = "99" + gamanv AND MTRL.KALKNR = 0 NO-LOCK.
GET FIRST mq NO-LOCK.
DO WHILE AVAILABLE(MTRL):
   IF AVAILABLE MTRL THEN DO TRANSACTION:
      GET CURRENT mq EXCLUSIVE-LOCK.
      MTRL.LEVKOD = "99" + nyanv.
   END.
   GET NEXT mq NO-LOCK.
END.
OPEN QUERY anvq FOR EACH ANVAOTAB WHERE ANVAOTAB.ANVANDARE BEGINS gamanv + "$" NO-LOCK.
GET FIRST anvq NO-LOCK.
DO WHILE AVAILABLE(ANVAOTAB):
   IF AVAILABLE ANVAOTAB THEN DO TRANSACTION:
      GET CURRENT anvq EXCLUSIVE-LOCK.
      ANVAOTAB.ANVANDARE = REPLACE(ANVAOTAB.ANVANDARE,gamanv + "$",nyanv + "$").
      
   END.
   GET NEXT anvq NO-LOCK.
END.
OPEN QUERY depq FOR EACH DEPSEK WHERE DEPSEK.ANVANDARE = gamanv NO-LOCK.
GET FIRST depq NO-LOCK.
DO WHILE AVAILABLE(DEPSEK):
   IF AVAILABLE DEPSEK THEN DO TRANSACTION:
      GET CURRENT depq EXCLUSIVE-LOCK.
      DEPSEK.ANVANDARE = nyanv.
   END.
   GET NEXT depq NO-LOCK.
END.

OPEN QUERY aoq FOR EACH AONRTAB WHERE AONRTAB.ANVANDARE = gamanv NO-LOCK.
GET FIRST aoq NO-LOCK.
DO WHILE AVAILABLE(AONRTAB):
   IF AVAILABLE AONRTAB THEN DO TRANSACTION:
      GET CURRENT aoq EXCLUSIVE-LOCK.
      AONRTAB.ANVANDARE = nyanv.
   END.
   GET NEXT aoq NO-LOCK.
END.
FOR EACH EXTRADATA WHERE EXTRADATA.PROGRAM = "FAVO" AND EXTRADATA.HUVUDCH = gamanv AND             
EXTRADATA.HUVUDINT =  ? EXCLUSIVE-LOCK:
   EXTRADATA.HUVUDCH = nyanv.
END.
FOR EACH EXTRADATA WHERE EXTRADATA.PROGRAM = "MACADD" AND EXTRADATA.HUVUDCH = gamanv AND             
EXTRADATA.HUVUDINT =  ? EXCLUSIVE-LOCK:
   EXTRADATA.HUVUDCH = nyanv.
END.
FOR EACH  OFFERT WHERE OFFERT.OFFNR = 1 AND OFFERT.OFFANV = gamanv EXCLUSIVE-LOCK:
   OFFERT.OFFANV = nyanv.
END.
OPEN QUERY bosekq FOR EACH BOLAGSEK WHERE BOLAGSEK.ANVANDARE = gamanv
NO-LOCK. 
DO TRANSACTION:       
   GET FIRST bosekq EXCLUSIVE-LOCK.
   IF AVAILABLE BOLAGSEK THEN BOLAGSEK.ANVANDARE = nyanv.
END.
REPEAT:  
   DO TRANSACTION:
      GET NEXT bosekq EXCLUSIVE-LOCK.         
      IF AVAILABLE BOLAGSEK THEN BOLAGSEK.ANVANDARE = nyanv.    
      ELSE LEAVE.      
   END.         
END.
FOR EACH MEDDELANDE WHERE MEDDELANDE.MOTTAGARE = gamanv EXCLUSIVE-LOCK:
   MEDDELANDE.MOTTAGARE = nyanv.
END.

/*
OPEN QUERY bestq FOR EACH BESTSTAT WHERE BESTSTAT.ANVANDARE = gamanv
NO-LOCK. 
DO TRANSACTION:       
   GET FIRST bestq EXCLUSIVE-LOCK.
   IF AVAILABLE BESTSTAT THEN BESTSTAT.ANVANDARE = nyanv.
END.
REPEAT:  
   DO TRANSACTION:
      GET NEXT bestq EXCLUSIVE-LOCK.         
      IF AVAILABLE BESTSTAT THEN BESTSTAT.ANVANDARE = nyanv.    
      ELSE LEAVE.      
   END.         
END.
*/

/*
OPEN QUERY persekq FOR EACH PERSEK WHERE PERSEK.ANVANDARE = gamanv
USE-INDEX PERSEK NO-LOCK. 
DO TRANSACTION:       
   GET FIRST persekq EXCLUSIVE-LOCK.
   IF AVAILABLE PERSEK THEN PERSEK.ANVANDARE = nyanv.    
END.
REPEAT:  
   DO TRANSACTION:
      GET NEXT persekq EXCLUSIVE-LOCK.
      IF AVAILABLE PERSEK THEN PERSEK.ANVANDARE = nyanv.    
      ELSE LEAVE.      
   END.         
END.      
OPEN QUERY tidsekq FOR EACH TIDSEK WHERE TIDSEK.ANVANDARE = gamanv
USE-INDEX TIDSEK NO-LOCK. 
DO TRANSACTION:       
   GET FIRST tidsekq EXCLUSIVE-LOCK.
   IF AVAILABLE TIDSEK THEN TIDSEK.ANVANDARE = nyanv.    
END.
REPEAT:  
   DO TRANSACTION:
      GET NEXT tidsekq EXCLUSIVE-LOCK.         
      IF AVAILABLE TIDSEK THEN TIDSEK.ANVANDARE = nyanv.    
      ELSE LEAVE.      
   END.         
END.

OPEN QUERY omrsekq FOR EACH OMRSEK WHERE OMRSEK.ANVANDARE = gamanv
NO-LOCK. 
DO TRANSACTION:       
   GET FIRST omrsekq EXCLUSIVE-LOCK.
   IF AVAILABLE OMRSEK THEN OMRSEK.ANVANDARE = nyanv.
END.
REPEAT:  
   DO TRANSACTION:
      GET NEXT omrsekq EXCLUSIVE-LOCK.         
      IF AVAILABLE OMRSEK THEN OMRSEK.ANVANDARE = nyanv.    
      ELSE LEAVE.      
   END.         
END.

OPEN QUERY bosekq FOR EACH BOLAGSEK WHERE BOLAGSEK.ANVANDARE = gamanv
NO-LOCK. 
DO TRANSACTION:       
   GET FIRST bosekq EXCLUSIVE-LOCK.
   IF AVAILABLE BOLAGSEK THEN BOLAGSEK.ANVANDARE = nyanv.
END.
REPEAT:  
   DO TRANSACTION:
      GET NEXT bosekq EXCLUSIVE-LOCK.         
      IF AVAILABLE BOLAGSEK THEN BOLAGSEK.ANVANDARE = nyanv.    
      ELSE LEAVE.      
   END.         
END.
*/
