/*BYTANVSTEG2.P*/
DEFINE INPUT PARAMETER gamanv LIKE ANVANDARE.ANVANDARE NO-UNDO.
DEFINE INPUT PARAMETER nyanv LIKE ANVANDARE.ANVANDARE NO-UNDO.
DEFINE VARIABLE musz AS LOGICAL NO-UNDO.
OPEN QUERY fadmsekq FOR EACH FAKTURADM WHERE FAKTURADM.ANVANDARE = gamanv
NO-LOCK. 
DO TRANSACTION:       
   GET FIRST fadmsekq EXCLUSIVE-LOCK.
   IF AVAILABLE FAKTURADM THEN FAKTURADM.ANVANDARE = nyanv.
END.
REPEAT:  
   DO TRANSACTION:
      GET NEXT fadmsekq EXCLUSIVE-LOCK.         
      IF AVAILABLE FAKTURADM THEN FAKTURADM.ANVANDARE = nyanv.    
      ELSE LEAVE.      
   END.         
END.
OPEN QUERY faktpsekq FOR EACH FAKTPLAN WHERE FAKTPLAN.ANVANDARE = gamanv
NO-LOCK. 
DO TRANSACTION:       
   GET FIRST faktpsekq EXCLUSIVE-LOCK.
   IF AVAILABLE FAKTPLAN THEN FAKTPLAN.ANVANDARE = nyanv.
END.
REPEAT:  
   DO TRANSACTION:
      GET NEXT faktpsekq EXCLUSIVE-LOCK.         
      IF AVAILABLE FAKTPLAN THEN FAKTPLAN.ANVANDARE = nyanv.    
      ELSE LEAVE.      
   END.         
END.
OPEN QUERY faktpsekq FOR EACH FAKTPLAN WHERE FAKTPLAN.HANVANDARE = gamanv
NO-LOCK. 
DO TRANSACTION:       
   GET FIRST faktpsekq EXCLUSIVE-LOCK.
   IF AVAILABLE FAKTPLAN THEN FAKTPLAN.HANVANDARE = nyanv.
END.
REPEAT:  
   DO TRANSACTION:
      GET NEXT faktpsekq EXCLUSIVE-LOCK.         
      IF AVAILABLE FAKTPLAN THEN FAKTPLAN.HANVANDARE = nyanv.    
      ELSE LEAVE.      
   END.         
END.
OPEN QUERY fastanmq FOR EACH FASTANM WHERE FASTANM.ANVANDARE = gamanv
NO-LOCK. 
DO TRANSACTION:       
   GET FIRST fastanmq EXCLUSIVE-LOCK.
   IF AVAILABLE FASTANM THEN FASTANM.ANVANDARE = nyanv.
END.
REPEAT:  
   DO TRANSACTION:
      GET NEXT fastanmq EXCLUSIVE-LOCK.         
      IF AVAILABLE FASTANM THEN FASTANM.ANVANDARE = nyanv.    
      ELSE LEAVE.      
   END.         
END.
OPEN QUERY berq FOR EACH BEREDNING WHERE BEREDNING.ANVANDARE = gamanv NO-LOCK.
GET FIRST berq NO-LOCK.
DO WHILE AVAILABLE(BEREDNING):
   IF AVAILABLE BEREDNING THEN DO TRANSACTION:
      GET CURRENT berq EXCLUSIVE-LOCK.
      BEREDNING.ANVANDARE = nyanv.
   END.
   GET NEXT berq NO-LOCK.
END.
OPEN QUERY bervq FOR EACH BERVAL WHERE BERVAL.ANVANDARE = gamanv NO-LOCK.
GET FIRST bervq NO-LOCK.
DO WHILE AVAILABLE(BERVAL):
   IF AVAILABLE BERVAL THEN DO TRANSACTION:
      GET CURRENT bervq EXCLUSIVE-LOCK.
      BERVAL.ANVANDARE = nyanv.
   END.
   GET NEXT bervq NO-LOCK.
END.
OPEN QUERY fastq FOR EACH FASTSPEC WHERE FASTSPEC.ANVANDARE = gamanv NO-LOCK.
GET FIRST fastq NO-LOCK.
DO WHILE AVAILABLE(FASTSPEC):
   IF AVAILABLE FASTSPEC THEN DO TRANSACTION:
      GET CURRENT fastq EXCLUSIVE-LOCK.
      FASTSPEC.ANVANDARE = nyanv.
   END.
   GET NEXT fastq NO-LOCK.
END.
OPEN QUERY kalkq FOR EACH KALKSPEC WHERE KALKSPEC.ANVANDARE = gamanv NO-LOCK.
GET FIRST kalkq NO-LOCK.
DO WHILE AVAILABLE(KALKSPEC):
   IF AVAILABLE KALKSPEC THEN DO TRANSACTION:
      GET CURRENT kalkq EXCLUSIVE-LOCK.
      KALKSPEC.ANVANDARE = nyanv.
   END.
   GET NEXT kalkq NO-LOCK.
END.
OPEN QUERY vardq FOR EACH VARDERING WHERE VARDERING.ANVANDARE = gamanv NO-LOCK.
GET FIRST vardq NO-LOCK.
DO WHILE AVAILABLE(VARDERING):
   IF AVAILABLE VARDERING THEN DO TRANSACTION:
      GET CURRENT vardq EXCLUSIVE-LOCK.
      VARDERING.ANVANDARE = nyanv.
   END.
   GET NEXT vardq NO-LOCK.
END.

OPEN QUERY dpq FOR EACH DEPA WHERE DEPA.ANVANDARE = gamanv
NO-LOCK. 
DO TRANSACTION:       
   GET FIRST dpq EXCLUSIVE-LOCK.
   IF AVAILABLE DEPA THEN DEPA.ANVANDARE = nyanv.
END.
REPEAT:  
   DO TRANSACTION:
      GET NEXT dpq EXCLUSIVE-LOCK.         
      IF AVAILABLE DEPA THEN DEPA.ANVANDARE = nyanv.    
      ELSE LEAVE.      
   END.         
END.
OPEN QUERY dpsq FOR EACH DEPSEK WHERE DEPSEK.ANVANDARE = gamanv
NO-LOCK. 
DO TRANSACTION:       
   GET FIRST dpsq EXCLUSIVE-LOCK.
   IF AVAILABLE DEPSEK THEN DEPSEK.ANVANDARE = nyanv.
END.
REPEAT:  
   DO TRANSACTION:
      GET NEXT dpsq EXCLUSIVE-LOCK.         
      IF AVAILABLE DEPSEK THEN DEPSEK.ANVANDARE = nyanv.    
      ELSE LEAVE.      
   END.         
END.



