/*KHMT.P*/
&Scoped-define NEW NEW
{GLOBVAR2DEL1.I}

DEFINE TEMP-TABLE kstrang
   FIELD BENAMNING AS CHARACTER
   FIELD K1 AS CHARACTER
   FIELD K2 AS CHARACTER
   FIELD K3 AS CHARACTER
   FIELD K4 AS CHARACTER
   FIELD K5 AS CHARACTER
   FIELD OMRADE AS CHARACTER
   FIELD RADNR AS INTEGER
   FIELD RECTIDVIS AS RECID
   INDEX KONTO K1 K2 K3 K4 K5
   INDEX KONTO2 RADNR.

DEFINE INPUT PARAMETER vadgora AS INTEGER NO-UNDO.
DEFINE INPUT PARAMETER cglobforetag AS CHARACTER NO-UNDO.
DEFINE INPUT PARAMETER avdnr AS INTEGER NO-UNDO.
DEFINE INPUT-OUTPUT PARAMETER TABLE FOR kstrang.
DEFINE OUTPUT PARAMETER jid AS CHARACTER.
Guru.Konstanter:globforetag = cglobforetag.
RUN STYRFORE.P (INPUT Guru.Konstanter:globforetag).

IF vadgora = 1 THEN DO:

   OPEN QUERY till FOR EACH KONTOSTRANG NO-LOCK.
   GET FIRST till NO-LOCK.   
   DO WHILE AVAILABLE(KONTOSTRANG):     
      CREATE kstrang.   
      ASSIGN
      kstrang.BENAMNING = KONTOSTRANG.BENAMNING
      kstrang.K1 = KONTOSTRANG.K1
      kstrang.K2 = KONTOSTRANG.K2         
      kstrang.K3 = KONTOSTRANG.K3
      kstrang.K4 = KONTOSTRANG.K4
      kstrang.K5 = KONTOSTRANG.K5      
      kstrang.RADNR = KONTOSTRANG.RADNR      
      kstrang.OMRADE = KONTOSTRANG.OMRADE      
      kstrang.RECTIDVIS = RECID(KONTOSTRANG).
      
      
      GET NEXT till NO-LOCK.      
   END.
   CLOSE QUERY till.
   FIND FIRST AVDELNING WHERE AVDELNING.AVDELNINGNR = avdnr NO-LOCK NO-ERROR.   
END.
IF vadgora = 2 THEN DO:
   IF Guru.Konstanter:varforetypval[18] = 1 THEN DO:   
      FIND FIRST AVDELNING WHERE AVDELNING.AVDELNINGNR = avdnr NO-LOCK NO-ERROR.   
      IF AVAILABLE AVDELNING  THEN jid = AVDELNING.POSTANST.
      ELSE jid = "".
   END.
   ELSE jid = "".
END.
