/*PERSTIT.P*/
{TIDUTTT.I}
DEFINE INPUT PARAMETER pkod LIKE PERSONALTAB.PERSONALKOD NO-UNDO.
DEFINE OUTPUT PARAMETER TABLE FOR tidut.
CREATE tidut. 
SUBSTRING(tidut.UT,60) = STRING(TODAY) + " " + STRING(TIME,"HH:MM").
   
OPEN QUERY pq FOR EACH PERSEK WHERE PERSEK.PERSONALKOD = pkod NO-LOCK,
EACH ANVANDARE WHERE ANVANDARE.ANVANDARE = PERSEK.ANVANDARE NO-LOCK.
CREATE tidut.
tidut.UT = "ANVÄNDARE SOM KAN ÄNDRA PÅ PERSONENS PERSONUPPGIFTER".
GET FIRST pq NO-LOCK.
DO WHILE AVAILABLE(ANVANDARE):
   CREATE tidut.
   SUBSTRING(tidut.UT,1,10) = ANVANDARE.ANVANDARE.
   SUBSTRING(tidut.UT,12) = ANVANDARE.AV-NAMN.
   Guru.GlobalaVariabler:GDPRvem = Guru.GlobalaVariabler:GDPRvem + "," + ANVANDARE.ANVANDARE + "," + ANVANDARE.PERSONALKOD.
   GET NEXT pq NO-LOCK.
END.
IF Guru.Konstanter:varforetypval[2] = 0 THEN DO:

   CREATE tidut.
   OPEN QUERY tq FOR EACH TIDSEK WHERE TIDSEK.PERSONALKOD = pkod NO-LOCK,
   EACH ANVANDARE WHERE ANVANDARE.ANVANDARE = TIDSEK.ANVANDARE NO-LOCK.
   
   CREATE tidut.
   tidut.UT = "ANVÄNDARE SOM KAN ÄNDRA PÅ PERSONENS TIDSKRIVNING".
   GET FIRST tq NO-LOCK.
   DO WHILE AVAILABLE(ANVANDARE):
      CREATE tidut.
      SUBSTRING(tidut.UT,1,10) = ANVANDARE.ANVANDARE.
      SUBSTRING(tidut.UT,12) = ANVANDARE.AV-NAMN.
      Guru.GlobalaVariabler:GDPRvem = Guru.GlobalaVariabler:GDPRvem + "," + ANVANDARE.ANVANDARE + "," + ANVANDARE.PERSONALKOD.
      GET NEXT tq NO-LOCK.
   END.
END.
{GDPRLOGGCLIENT.I}
