/*SKRIVAPP.P*/
DEFINE INPUT PARAMETER globanv AS CHARACTER NO-UNDO.
DEFINE INPUT PARAMETER rb-print AS CHARACTER NO-UNDO.
DEFINE INPUT-OUTPUT PARAMETER globsidl AS INTEGER NO-UNDO.
DEFINE INPUT-OUTPUT PARAMETER globsids AS INTEGER NO-UNDO.
IF rb-print NE "" THEN DO:
   FIND FIRST SKRIVARDEF WHERE SKRIVARDEF.SKRIVARID = rb-print NO-LOCK NO-ERROR.
   IF NOT AVAILABLE SKRIVARDEF THEN DO TRANSACTION:
      CREATE SKRIVARDEF.
      ASSIGN
      SKRIVARDEF.BREDD = globsidl
      SKRIVARDEF.SIDA = globsids
      SKRIVARDEF.SKRIVARID = rb-print.      
      IF SKRIVARDEF.BREDD = 0 THEN SKRIVARDEF.BREDD = 53.
      IF SKRIVARDEF.SIDA = 0 THEN  SKRIVARDEF.SIDA = 72.
   END.   
   ASSIGN
   globsidl = SKRIVARDEF.BREDD
   globsids = SKRIVARDEF.SIDA. 
END.

