/* p-clrfnt.p */

DEFINE BUTTON quitbtn LABEL "QUIT" BGCOLOR 4 FGCOLOR 15.
DEFINE VARIABLE fgc_frm AS INTEGER BGCOLOR 15 FGCOLOR 0
   VIEW-AS SLIDER MAX-VALUE 15 MIN-VALUE 0.
DEFINE VARIABLE bgc_frm AS INTEGER BGCOLOR 15 FGCOLOR 0
   VIEW-AS SLIDER MAX-VALUE 15 MIN-VALUE 0.
DEFINE VARIABLE font_frm AS INTEGER FONT 1 VIEW-AS SLIDER
   MAX-VALUE 15 MIN-VALUE 0.

FORM
   SKIP (1) "Form Foreground" AT 7 SKIP
   fgc_frm AT 6 SKIP (1)
   "Form Background" AT 7 SKIP
   bgc_frm AT 6 SKIP (1)
   "Form Font" AT 10 skip
   font_frm AT 6 SKIP (2)
   quitbtn AT 12 SKIP (1)
   WITH FRAME x TITLE "Color and Font Test"
      NO-LABELS CENTERED ROW 2 WIDTH 50.
      
ASSIGN FRAME x:RULE-Y = 282
       fgc_frm:MAX-VALUE = COLOR-TABLE:NUM-ENTRIES - 1
       bgc_frm:MAX-VALUE = COLOR-TABLE:NUM-ENTRIES - 1
       font_frm:MAX-VALUE = FONT-TABLE:NUM-ENTRIES - 1.
     
ON VALUE-CHANGED OF fgc_frm
   FRAME x:FGCOLOR = INPUT FRAME x fgc_frm.

ON VALUE-CHANGED OF bgc_frm
   FRAME x:BGCOLOR = INPUT FRAME x bgc_frm.
   
ON VALUE-CHANGED OF font_frm
   FRAME x:FONT = INPUT FRAME x font_frm.

ENABLE ALL WITH FRAME x .

WAIT-FOR WINDOW-CLOSE OF CURRENT-WINDOW OR CHOOSE OF quitbtn.
