/* p-edit1.p */

DEFINE VARIABLE e AS CHARACTER VIEW-AS EDITOR
                      INNER-CHARS 20 INNER-LINES 4.
                      
ENABLE e WITH NO-LABELS.

WAIT-FOR WINDOW-CLOSE OF CURRENT-WINDOW.
