/* p-error5.p */

DEFINE VARIABLE a AS CHARACTER.
DEFINE VARIABLE b AS CHARACTER.
FORM a b WITH FRAME X 2 COLUMNS.

SESSION:APPL-ALERT-BOXES = TRUE.
ON END-ERROR ANYWHERE DO:
  MESSAGE KEYFUNCTION(LASTKEY) "raised".
END.
MESSAGE "Entering UPDATE Block".
DO ON ERROR UNDO, RETRY ON ENDKEY UNDO, LEAVE WITH FRAME X:
  IF RETRY THEN MESSAGE "Retrying UPDATE Block".
  UPDATE a WITH FRAME X.
  MESSAGE "After UPDATE a".
  UPDATE b WITH FRAME X.
  MESSAGE "After UPDATE b".
END.
MESSAGE "Entering ENABLE/WAIT-FOR Block".
DO ON ERROR UNDO, RETRY ON ENDKEY UNDO, LEAVE WITH FRAME X:
  IF RETRY THEN MESSAGE "Retrying ENABLE/WAIT-FOR Block".
  DISABLE ALL.
  ENABLE a.
  WAIT-FOR GO OF FRAME X.
  MESSAGE "After ENABLE/WAIT-FOR a".
  DISABLE ALL.
  ENABLE b. 
  WAIT-FOR GO OF FRAME X.
  MESSAGE "After ENABLE/WAIT-FOR b".
END.
