/* p-fdial1.p */

If FONT-TABLE:NUM-ENTRIES < 13 THEN
    FONT-TABLE:NUM-ENTRIES = 13. 
DEFINE VARIABLE RadioFont  AS INTEGER INITIAL 11.
DEFINE VARIABLE ButtonFont AS INTEGER INITIAL 12.
DEFINE VARIABLE FontSelect AS INTEGER INITIAL 11
    VIEW-AS RADIO-SET
        RADIO-BUTTONS "Radio Font", 11, "Button Font", 12 
        FONT RadioFont.
DEFINE BUTTON bOK          LABEL "OK" FONT ButtonFont.
DEFINE BUTTON bCANCEL  LABEL "CANCEL" FONT ButtonFont.

FORM
    SKIP(0.5) SPACE(0.5)
    FontSelect SPACE(2) bOK SPACE(2) bCANCEL
    SPACE(0.5) SKIP(0.5)
    WITH FRAME fFont TITLE "Choose frame fonts ..." 
         VIEW-AS DIALOG-BOX THREE-D.

ON CHOOSE OF bOK IN FRAME fFont
DO: 
    ASSIGN FontSelect.
    SYSTEM-DIALOG FONT FontSelect.
END.

ON CHOOSE OF bCANCEL IN FRAME fFont STOP.

ENABLE FontSelect bOK bCANCEL WITH FRAME fFont.

WAIT-FOR WINDOW-CLOSE OF FRAME fFont.



