/* p-fof3.p */

DEFINE BUTTON bhidden1 LABEL "HIDDEN".
DEFINE BUTTON bhidden2 LABEL "HIDDEN".
DEFINE BUTTON bhidden3 LABEL "HIDDEN".
DEFINE BUTTON bvisible1 LABEL "VISIBLE".
DEFINE BUTTON bhide1 LABEL "HIDE".
DEFINE BUTTON bhide2 LABEL "HIDE".
DEFINE BUTTON bhide3 LABEL "HIDE".
DEFINE BUTTON bdisp1 LABEL "DISPLAY".
DEFINE BUTTON bdisp2 LABEL "DISPLAY".
DEFINE BUTTON bdisp3 LABEL "DISPLAY".
DEFINE BUTTON bview1 LABEL "VIEW".
DEFINE BUTTON bview2 LABEL "VIEW".
DEFINE BUTTON bview3 LABEL "VIEW".
DEFINE BUTTON bhifld1 LABEL "HIDE".
DEFINE BUTTON bhifld2 LABEL "HIDE".
DEFINE BUTTON bhifld3 LABEL "HIDE".
DEFINE BUTTON bviewf1 LABEL "VIEW FRAME 1".
DEFINE BUTTON bviewf2 LABEL "VIEW FRAME 2".
DEFINE BUTTON bviewf3 LABEL "VIEW FRAME 3".
DEFINE VARIABLE field1 AS CHARACTER.
DEFINE VARIABLE field2 AS CHARACTER.
DEFINE VARIABLE field3 AS CHARACTER.
DEFINE FRAME f1 SKIP(.5)
    SPACE(22) bhidden1 bhide1 field1 
WITH SIDE-LABELS TITLE "FRAME 1" KEEP-TAB-ORDER 
     SIZE 80 BY 8.
DEFINE FRAME f2 SKIP(.5)
    SPACE(6) bhidden2 bhide2 SKIP(.5) SPACE(6) field2 
WITH SIDE-LABELS TITLE "FRAME 2" KEEP-TAB-ORDER 
     SIZE 30 BY 4.5 AT COLUMN 7 ROW 3.
DEFINE FRAME f3 SKIP(.5)
    SPACE(6) bhidden3 bhide3 SKIP(.5) SPACE(6) field3 
WITH SIDE-LABELS TITLE "FRAME 3" KEEP-TAB-ORDER 
     SIZE 30 BY 4.5 AT COLUMN 44 ROW 3.
DEFINE FRAME f4 SKIP
    "Frames" AT 19 "field1" AT 38 "field2" AT 52 "field3" AT 66 SKIP
    bvisible1 AT 5
    bviewf1 AT 19 bdisp1 AT 38 bdisp2 AT 52 bdisp3 AT 66 SKIP(.5) 
    bviewf2 AT 19 bview1 AT 38 bview2 AT 52 bview3 AT 66 SKIP(.5)
    bviewf3 AT 19 bhifld1 AT 38 bhifld2 AT 52 bhifld3 AT 66 SKIP(.5)
WITH TITLE "Control Panel" SIZE 80 by 7 AT COLUMN 1 ROW 9.

FRAME f2:FRAME = FRAME f1:HANDLE.
FRAME f3:FRAME = FRAME f1:HANDLE.
CURRENT-WINDOW:TITLE = "Frame Family View/Hide Demo".

ON CHOOSE OF bhidden1 DO:
    FRAME f1:HIDDEN = TRUE.
    MESSAGE "f1:HIDDEN" FRAME f1:HIDDEN "f1:VISIBLE" FRAME f1:VISIBLE
            "f2:HIDDEN" FRAME f2:HIDDEN "f2:VISIBLE" FRAME f2:VISIBLE
            "f3:HIDDEN" FRAME f3:HIDDEN "f3:VISIBLE" FRAME f3:VISIBLE.
END.

ON CHOOSE OF bhidden2 DO:
    FRAME f2:HIDDEN = TRUE.
    MESSAGE "f2:HIDDEN" FRAME f2:HIDDEN "f2:VISIBLE" FRAME f2:VISIBLE.
END.

ON CHOOSE OF bhidden3 DO:
    FRAME f3:HIDDEN = TRUE.
    MESSAGE "f3:HIDDEN" FRAME f3:HIDDEN "f3:VISIBLE" FRAME f3:VISIBLE.
END.

ON CHOOSE OF bhide1 DO:
    HIDE FRAME f1.
    MESSAGE "f1:HIDDEN" FRAME f1:HIDDEN "f1:VISIBLE" FRAME f1:VISIBLE
            "f2:HIDDEN" FRAME f2:HIDDEN "f2:VISIBLE" FRAME f2:VISIBLE
            "f3:HIDDEN" FRAME f3:HIDDEN "f3:VISIBLE" FRAME f3:VISIBLE.
END.

ON CHOOSE OF bhide2 DO:
    HIDE FRAME f2.
    MESSAGE "f2:HIDDEN" FRAME f2:HIDDEN "f2:VISIBLE" FRAME f2:VISIBLE.
END.

ON CHOOSE OF bhide3 DO:
    HIDE FRAME f3.
    MESSAGE "f3:HIDDEN" FRAME f3:HIDDEN "f3:VISIBLE" FRAME f3:VISIBLE.
END.

ON CHOOSE OF bvisible1 DO:
    MESSAGE "f1:HIDDEN" FRAME f1:HIDDEN "f1:VISIBLE" FRAME f1:VISIBLE
            "f2:HIDDEN" FRAME f2:HIDDEN "f2:VISIBLE" FRAME f2:VISIBLE
            "f3:HIDDEN" FRAME f3:HIDDEN "f3:VISIBLE" FRAME f3:VISIBLE.
    MESSAGE "field1" IF field1:HIDDEN THEN "HIDDEN" ELSE "UNHIDDEN"
                     IF field1:VISIBLE THEN "VISIBLE" ELSE "INVISIBLE"
            "field2" IF field2:HIDDEN THEN "HIDDEN"  ELSE "UNHIDDEN"
                     IF field2:VISIBLE THEN "VISIBLE" ELSE "INVISIBLE"
            "field3" IF field3:HIDDEN THEN "HIDDEN" ELSE "UNHIDDEN"
                     IF field3:VISIBLE THEN "VISIBLE" ELSE "INVISIBLE".
END.

ON CHOOSE OF bdisp1 DO:
    DISPLAY field1 WITH FRAME f1.
    MESSAGE "f1:HIDDEN" FRAME f1:HIDDEN "f1:VISIBLE" FRAME f1:VISIBLE.
    MESSAGE "field1" IF field1:HIDDEN THEN "HIDDEN" ELSE "UNHIDDEN"
                     IF field1:VISIBLE THEN "VISIBLE" ELSE "INVISIBLE".
END.

ON CHOOSE OF bdisp2 DO:
    DISPLAY field2 WITH FRAME f2.
    MESSAGE "f2:HIDDEN" FRAME f2:HIDDEN "f2:VISIBLE" FRAME f2:VISIBLE.
    MESSAGE "field2" IF field2:HIDDEN THEN "HIDDEN" ELSE "UNHIDDEN"
                     IF field2:VISIBLE THEN "VISIBLE" ELSE "INVISIBLE".
END.

ON CHOOSE OF bdisp3 DO:
    DISPLAY field3 WITH FRAME f3.
    MESSAGE "f3:HIDDEN" FRAME f3:HIDDEN "f3:VISIBLE" FRAME f3:VISIBLE.
    MESSAGE "field3" IF field3:HIDDEN THEN "HIDDEN" ELSE "UNHIDDEN"
                     IF field3:VISIBLE THEN "VISIBLE" ELSE "INVISIBLE".
END.

ON CHOOSE OF bview1 DO:
    VIEW field1 IN FRAME f1.
    MESSAGE "f1:HIDDEN" FRAME f1:HIDDEN "f1:VISIBLE" FRAME f1:VISIBLE.
    MESSAGE "field1" IF field1:HIDDEN THEN "HIDDEN" ELSE "UNHIDDEN"
                     IF field1:VISIBLE THEN "VISIBLE" ELSE "INVISIBLE".
END.

ON CHOOSE OF bview2 DO:
    VIEW field2 IN FRAME f2.
    MESSAGE "f2:HIDDEN" FRAME f2:HIDDEN "f2:VISIBLE" FRAME f2:VISIBLE.
    MESSAGE "field2" IF field2:HIDDEN THEN "HIDDEN" ELSE "UNHIDDEN"
                     IF field2:VISIBLE THEN "VISIBLE" ELSE "INVISIBLE".
END.

ON CHOOSE OF bview3 DO:
    VIEW field3 IN FRAME f3.
    MESSAGE "f3:HIDDEN" FRAME f3:HIDDEN "f3:VISIBLE" FRAME f3:VISIBLE.
    MESSAGE "field3" IF field3:HIDDEN THEN "HIDDEN" ELSE "UNHIDDEN"
                     IF field3:VISIBLE THEN "VISIBLE" ELSE "INVISIBLE".
END.

ON CHOOSE OF bhifld1 DO:
    field1:VISIBLE IN FRAME f1 = FALSE.
    MESSAGE "f1:HIDDEN" FRAME f1:HIDDEN "f1:VISIBLE" FRAME f1:VISIBLE.
    MESSAGE "field1" IF field1:HIDDEN THEN "HIDDEN" ELSE "UNHIDDEN"
                     IF field1:VISIBLE THEN "VISIBLE" ELSE "INVISIBLE".
END.

ON CHOOSE OF bhifld2 DO:
    field2:VISIBLE IN FRAME f2 = FALSE.
    MESSAGE "f2:HIDDEN" FRAME f2:HIDDEN "f2:VISIBLE" FRAME f2:VISIBLE.
    MESSAGE "field2" IF field2:HIDDEN THEN "HIDDEN" ELSE "UNHIDDEN"
                     IF field2:VISIBLE THEN "VISIBLE" ELSE "INVISIBLE".
END.

ON CHOOSE OF bhifld3 DO:
    HIDE field3 IN FRAME f3.
    MESSAGE "f3:HIDDEN" FRAME f3:HIDDEN "f3:VISIBLE" FRAME f3:VISIBLE.
    MESSAGE "field3" IF field3:HIDDEN THEN "HIDDEN" ELSE "UNHIDDEN"
                     IF field3:VISIBLE THEN "VISIBLE" ELSE "INVISIBLE".
END.

ON CHOOSE OF bviewf1 DO:
    VIEW FRAME f1.
    MESSAGE "f1:HIDDEN" FRAME f1:HIDDEN "f1:VISIBLE" FRAME f1:VISIBLE
            "f2:HIDDEN" FRAME f2:HIDDEN "f2:VISIBLE" FRAME f2:VISIBLE
            "f3:HIDDEN" FRAME f3:HIDDEN "f3:VISIBLE" FRAME f3:VISIBLE.
END.

ON CHOOSE OF bviewf2 DO:
    VIEW FRAME f2.
    MESSAGE "f1:HIDDEN" FRAME f1:HIDDEN "f1:VISIBLE" FRAME f1:VISIBLE
            "f2:HIDDEN" FRAME f2:HIDDEN "f2:VISIBLE" FRAME f2:VISIBLE.
END.

ON CHOOSE OF bviewf3 DO:
    VIEW FRAME f3.
    MESSAGE "f1:HIDDEN" FRAME f1:HIDDEN "f1:VISIBLE" FRAME f1:VISIBLE
            "f3:HIDDEN" FRAME f3:HIDDEN "f3:VISIBLE" FRAME f3:VISIBLE.
END.

ON GO OF FRAME f1 APPLY "WINDOW-CLOSE" TO CURRENT-WINDOW.

ENABLE ALL WITH FRAME f1.
ENABLE ALL WITH FRAME f2.
ENABLE ALL WITH FRAME f3.
ENABLE ALL WITH FRAME f4.

WAIT-FOR WINDOW-CLOSE OF CURRENT-WINDOW.
