/* p-fof1.p */

DEFINE FRAME fparent WITH SIZE 60 by 10 TITLE "Parent".
DEFINE FRAME fchild WITH SIZE 40 by 5 TITLE "Child".
FRAME fchild:FRAME = FRAME fparent:HANDLE.

DISPLAY WITH FRAME fparent.
ENABLE ALL WITH FRAME fparent.
ENABLE ALL WITH FRAME fchild.

WAIT-FOR WINDOW-CLOSE OF CURRENT-WINDOW.
