/* p-manual.p */

DEFINE RECTANGLE rect1 SIZE-PIXELS 40 BY 40 EDGE-PIXELS 3 NO-FILL.
DEFINE RECTANGLE rect2 SIZE-PIXELS 40 BY 40 EDGE-PIXELS 3 NO-FILL.

FORM SKIP(1) SPACE (1) rect1 SPACE(8) rect2 WITH FRAME a NO-LABELS.

rect1:SELECTABLE IN FRAME a = yes.
rect1:SENSITIVE IN FRAME a = yes.
rect1:MANUAL-HIGHLIGHT IN FRAME a = yes.
rect1:BGCOLOR = 1.
rect2:SELECTABLE IN FRAME a = yes.
rect2:SENSITIVE IN FRAME a = yes.

ON SELECTION OF rect1 IN FRAME a SELF:FILLED = yes.
ON DESELECTION OF rect1 IN FRAME a SELF:FILLED = no.

ENABLE rect1 rect2 WITH FRAME a.
WAIT-FOR GO OF FRAME a.
