DEFINE VARIABLE mynum AS DECIMAL.

SESSION:DATE-FORMAT = "mdy".
DISPLAY SESSION:DATE-FORMAT SPACE(5) TODAY WITH FRAME d1.

SESSION:DATE-FORMAT = "dmy".
DISPLAY SESSION:DATE-FORMAT SPACE(5) TODAY FORMAT "99-99-99"
  WITH FRAME d2.

DISPLAY SESSION:DATE-FORMAT SPACE(5) TODAY FORMAT "99.99.99"
  WITH FRAME d3.

mynum = 12345.67.
SESSION:NUMERIC-FORMAT = "AMERICAN".
DISPLAY SESSION:NUMERIC-FORMAT mynum WITH FRAME f1 NO-LABELS.

SESSION:NUMERIC-FORMAT = "EUROPEAN".
DISPLAY SESSION:NUMERIC-FORMAT mynum WITH FRAME f2 NO-LABELS.
