/* p-wina.p */

OPEN QUERY custq FOR EACH customer.

DEFINE BROWSE custb QUERY custq DISPLAY cust-num name WITH 15 DOWN.

FORM
  custb
  WITH FRAME x.

FORM
   customer
   WITH FRAME y SIDE-LABELS COLUMN 40 ROW 3 WIDTH 75.

ASSIGN DEFAULT-WINDOW:VIRTUAL-WIDTH-CHARS = 120
       DEFAULT-WINDOW:VIRTUAL-HEIGHT-CHARS = 15
       DEFAULT-WINDOW:WIDTH-CHARS = 120
       DEFAULT-WINDOW:HEIGHT-CHARS = 15
       DEFAULT-WINDOW:TITLE = "Customer Browser".

ON ITERATION-CHANGED OF BROWSE custb
  DO:
     DISPLAY customer WITH FRAME y.
  END.

ON WINDOW-CLOSE OF CURRENT-WINDOW 
     QUIT.

ENABLE custb WITH FRAME x.
  
APPLY "ITERATION-CHANGED" TO BROWSE custb.

ENABLE ALL WITH FRAME y.

WAIT-FOR WINDOW-CLOSE OF CURRENT-WINDOW.
