OPEN QUERY DQ FOR EACH BESTDEP WHERE YEAR(BESTDEP.BESTDATUM) < 2003 AND 
BESTDEP.LEVDATUM = ? AND BESTDEP.BERED = FALSE NO-LOCK.
DO TRANSACTION:
   GET FIRST DQ EXCLUSIVE-LOCK.
   IF AVAILABLE BESTDEP THEN DO:
      BESTDEP.LEVDATUM = TODAY.
   END.
END.
REPEAT:
   DO TRANSACTION:
      GET NEXT DQ EXCLUSIVE-LOCK.
      IF AVAILABLE BESTDEP THEN DO:
          BESTDEP.LEVDATUM = TODAY.
      END.
      ELSE LEAVE.
   END.
END.    
