/*ANSBEROP.P*/
DEFINE TEMP-TABLE utberatemp
   FIELD EFTERNAMN   LIKE BEREDAONR.EFTERNAMN 
   FIELD FORNAMN      LIKE BEREDAONR.FORNAMN 
   FIELD PERSONALKOD  LIKE BEREDAONR.PERSONALKOD
   INDEX PERS IS PRIMARY PERSONALKOD
   INDEX FORNAMN FORNAMN PERSONALKOD
   INDEX EFTERNAMN EFTERNAMN PERSONALKOD.
DEFINE INPUT PARAMETER val AS INTEGER NO-UNDO.
DEFINE OUTPUT PARAMETER TABLE FOR utberatemp.
FIND FIRST FORETAG NO-LOCK NO-ERROR.
EMPTY TEMP-TABLE utberatemp NO-ERROR. 
IF val = 1 THEN DO:
    IF FORETAG.FORETAG = "GRAN" OR FORETAG.FORETAG = "SUND" OR FORETAG.FORETAG = "SNAT" OR FORETAG.FORETAG = "MISV" OR FORETAG.FORETAG = "ELPA" OR FORETAG.FORETAG = "GKAL" THEN DO:
      OPEN QUERY bq FOR EACH BEREDAONR NO-LOCK, 
      EACH PERSONALTAB WHERE PERSONALTAB.PERSONALKOD = BEREDAONR.PERSONALKOD AND 
      PERSONALTAB.AKTIV = TRUE NO-LOCK.
   END.          
   ELSE DO:
      OPEN QUERY bq FOR EACH BEREDAONR NO-LOCK, 
      EACH PERSONALTAB WHERE PERSONALTAB.PERSONALKOD = BEREDAONR.PERSONALKOD  
      NO-LOCK.
   END.
   GET FIRST bq NO-LOCK.
   DO WHILE AVAILABLE(PERSONALTAB):
      CREATE utberatemp.
      ASSIGN
      utberatemp.EFTERNAMN    = PERSONALTAB.EFTERNAMN   
      utberatemp.FORNAMN      = PERSONALTAB.FORNAMN    
      utberatemp.PERSONALKOD  = PERSONALTAB.PERSONALKOD.
      Guru.GlobalaVariabler:GDPRvem = Guru.GlobalaVariabler:GDPRvem + "," + PERSONALTAB.PERSONALKOD.
      GET NEXT bq NO-LOCK.
   END.
END.
ELSE IF val = 2 THEN DO:
   IF FORETAG.FORETAG = "GRAN" OR FORETAG.FORETAG = "SUND" OR FORETAG.FORETAG = "SNAT" OR FORETAG.FORETAG = "MISV" OR FORETAG.FORETAG = "ELPA" OR FORETAG.FORETAG = "GKAL" THEN DO:
      OPEN QUERY aq FOR EACH ANSVAONR NO-LOCK, 
      EACH PERSONALTAB WHERE PERSONALTAB.PERSONALKOD = ANSVAONR.PERSONALKOD AND 
      PERSONALTAB.AKTIV = TRUE NO-LOCK.
   END.          
   ELSE DO:
      OPEN QUERY aq FOR EACH ANSVAONR NO-LOCK, 
      EACH PERSONALTAB WHERE PERSONALTAB.PERSONALKOD = ANSVAONR.PERSONALKOD 
      NO-LOCK.
   END.
   GET FIRST aq NO-LOCK.
   DO WHILE AVAILABLE(PERSONALTAB):
      CREATE utberatemp.
      ASSIGN
      utberatemp.EFTERNAMN    = PERSONALTAB.EFTERNAMN   
      utberatemp.FORNAMN      = PERSONALTAB.FORNAMN    
      utberatemp.PERSONALKOD  = PERSONALTAB.PERSONALKOD.
      Guru.GlobalaVariabler:GDPRvem = Guru.GlobalaVariabler:GDPRvem + "," + PERSONALTAB.PERSONALKOD.
      GET NEXT aq NO-LOCK.
   END.
END.

{GDPRLOGGCLIENT.I}   
