/*APAMEDD.P MEDELANDE FRÅN ANDRA DATABASER ENDAST ELPAO*/
DEFINE TEMP-TABLE flermeddtemp
  FIELD EDATUM LIKE MEDDELANDE.EDATUM 
  FIELD EMOTAGET LIKE MEDDELANDE.EMOTAGET 
  FIELD MEDD LIKE MEDDELANDE.MEDD 
  FIELD MOTTAGARE LIKE MEDDELANDE.MOTTAGARE 
  FIELD SANDARE LIKE MEDDELANDE.SANDARE 
  FIELD SDATUM LIKE MEDDELANDE.SDATUM
  FIELD FORETAG LIKE FORETAG.FORETAG
  FIELD MEDREC AS RECID
  INDEX MEDD IS PRIMARY FORETAG SANDARE SDATUM MOTTAGARE EMOTAGET 
  INDEX MEDD2 FORETAG SANDARE MOTTAGARE  
  INDEX MOTTAGARE FORETAG MOTTAGARE EMOTAGET SANDARE. 
DEFINE INPUT PARAMETER vadgora AS INTEGER NO-UNDO.
DEFINE INPUT PARAMETER plusrec AS RECID NO-UNDO.
DEFINE INPUT PARAMETER globanv LIKE ANVANDARE.ANVANDARE NO-UNDO.
DEFINE INPUT-OUTPUT PARAMETER TABLE FOR flermeddtemp.
FIND FIRST FORETAG USE-INDEX FORETAG NO-LOCK NO-ERROR.
IF vadgora = 1 THEN DO:
   /*hämta alla som finns även från andra databaser*/
   OPEN QUERY meddq FOR EACH MEDDELANDE WHERE MEDDELANDE.MOTTAGARE = globanv AND
   MEDDELANDE.EMOTAGET = FALSE NO-LOCK.   
   GET FIRST meddq NO-LOCK. 
   DO WHILE AVAILABLE(MEDDELANDE):
      CREATE flermeddtemp.
      ASSIGN 
      flermeddtemp.FORETAG = FORETAG.FORETAG
      flermeddtemp.MEDD = MEDDELANDE.MEDD
      flermeddtemp.SANDARE = MEDDELANDE.SANDARE 
      flermeddtemp.SDATUM = MEDDELANDE.SDATUM          
      flermeddtemp.MEDREC = RECID(MEDDELANDE).               
      GET NEXT meddq NO-LOCK. 
   END.   
END.
IF vadgora = 2 THEN DO:
   /*behövs ej*/
   FOR EACH flermeddtemp WHERE flermeddtemp.FORETAG = FORETAG.FORETAG:
      DO TRANSACTION:
         CREATE MEDDELANDE.
         ASSIGN         
         MEDDELANDE.EMOTAGET = flermeddtemp.EMOTAGET
         MEDDELANDE.MEDD = flermeddtemp.MEDD 
         MEDDELANDE.SANDARE = flermeddtemp.SANDARE  
         MEDDELANDE.SDATUM = flermeddtemp.SDATUM.          
         DELETE flermeddtemp.
      END.   
   END.  
END.
IF vadgora = 3 THEN DO:
   /*till meddstatus*/
   OPEN QUERY meddq FOR EACH MEDDELANDE WHERE MEDDELANDE.SANDARE = globanv AND
   MEDDELANDE.EMOTAGET = FALSE
   USE-INDEX MEDD NO-LOCK.
   GET FIRST meddq NO-LOCK.
   DO WHILE AVAILABLE(MEDDELANDE):
      CREATE flermeddtemp.
      ASSIGN 
      flermeddtemp.FORETAG = FORETAG.FORETAG
      flermeddtemp.MEDD = MEDDELANDE.MEDD
      flermeddtemp.SANDARE = MEDDELANDE.SANDARE 
      flermeddtemp.SDATUM = MEDDELANDE.SDATUM
      flermeddtemp.MOTTAGARE =MEDDELANDE.MOTTAGARE 
      flermeddtemp.EMOTAGET = MEDDELANDE.EMOTAGET
      flermeddtemp.MEDREC = RECID(MEDDELANDE).
      GET NEXT meddq NO-LOCK.
   END.
END.
IF vadgora = 4 THEN DO:
   /*från medelade status.*/
   FIND FIRST MEDDELANDE WHERE RECID(MEDDELANDE) = plusrec NO-LOCK.
   IF AVAILABLE MEDDELANDE THEN DO:
      CREATE flermeddtemp.
      ASSIGN 
      flermeddtemp.FORETAG = FORETAG.FORETAG
      flermeddtemp.MEDD = MEDDELANDE.MEDD
      flermeddtemp.SANDARE = MEDDELANDE.SANDARE 
      flermeddtemp.SDATUM = MEDDELANDE.SDATUM
      flermeddtemp.MOTTAGARE =MEDDELANDE.MOTTAGARE 
      flermeddtemp.EMOTAGET = MEDDELANDE.EMOTAGET
      flermeddtemp.MEDREC = RECID(MEDDELANDE).
   END.
END.
IF vadgora = 5 THEN DO:
   /*tar bort medd*/
   FOR EACH flermeddtemp WHERE flermeddtemp.FORETAG = "tabort":
      DO TRANSACTION:
         FIND MEDDELANDE WHERE RECID(MEDDELANDE) = flermeddtemp.MEDREC EXCLUSIVE-LOCK NO-ERROR.
         IF AVAILABLE MEDDELANDE THEN DELETE MEDDELANDE.
         DELETE flermeddtemp.         
      END.   
   END. 
   FOR EACH flermeddtemp WHERE flermeddtemp.FORETAG = "spara":
      DO TRANSACTION:
         FIND MEDDELANDE WHERE RECID(MEDDELANDE) = flermeddtemp.MEDREC EXCLUSIVE-LOCK NO-ERROR.
         IF AVAILABLE MEDDELANDE THEN MEDDELANDE.EMOTAGET = TRUE.
         DELETE flermeddtemp.         
      END.   
   END.  
END.
