/*APAMEDDF.P MEDELANDE FRÅN ANDRA DATABASER ENDAST ELPAO*/
DEFINE TEMP-TABLE flermeddtemp
  FIELD EDATUM LIKE MEDDELANDE.EDATUM 
  FIELD EMOTAGET LIKE MEDDELANDE.EMOTAGET 
  FIELD MEDD LIKE MEDDELANDE.MEDD 
  FIELD MOTTAGARE LIKE MEDDELANDE.MOTTAGARE 
  FIELD SANDARE LIKE MEDDELANDE.SANDARE 
  FIELD SDATUM LIKE MEDDELANDE.SDATUM
  FIELD FORETAG LIKE FORETAG.FORETAG
  FIELD MEDREC AS RECID
  INDEX MEDD IS PRIMARY FORETAG SANDARE SDATUM MOTTAGARE EMOTAGET 
  INDEX MEDD2 FORETAG SANDARE MOTTAGARE  
  INDEX MOTTAGARE FORETAG MOTTAGARE EMOTAGET SANDARE. 
DEFINE INPUT PARAMETER TABLE FOR flermeddtemp.
   /*tar bort medd*/
   FOR EACH flermeddtemp WHERE flermeddtemp.FORETAG = "tabort":
      DO TRANSACTION:
         FIND MEDDELANDE WHERE RECID(MEDDELANDE) = flermeddtemp.MEDREC EXCLUSIVE-LOCK NO-ERROR.
         IF AVAILABLE MEDDELANDE THEN DELETE MEDDELANDE.
         DELETE flermeddtemp.         
      END.   
   END. 
   FOR EACH flermeddtemp WHERE flermeddtemp.FORETAG = "spara":
      DO TRANSACTION:
         FIND MEDDELANDE WHERE RECID(MEDDELANDE) = flermeddtemp.MEDREC EXCLUSIVE-LOCK NO-ERROR.
         IF AVAILABLE MEDDELANDE THEN MEDDELANDE.EMOTAGET = TRUE.
         DELETE flermeddtemp.         
      END.   
   END.  
