/*APASMEDD.P*/
DEFINE INPUT PARAMETER EDITOR_MEDD AS CHARACTER.
DEFINE INPUT PARAMETER globanv LIKE ANVANDARE.ANVANDARE.
FOR EACH ANVANDARE NO-LOCK:
   DO TRANSACTION:
      CREATE MEDDELANDE.
      ASSIGN 
      MEDDELANDE.SDATUM = TODAY
      MEDDELANDE.EMOTAGET = FALSE
      MEDDELANDE.MEDD = EDITOR_MEDD
      MEDDELANDE.MOTTAGARE = ANVANDARE.ANVANDARE. 
      MEDDELANDE.SANDARE = Guru.Konstanter:globanv.
   END.   
END.
