/*BAHMT.P*/
{PERSTEMP.I}
/*DEFINE TEMP-TABLE perstemp
   FIELD PERSONALKOD LIKE PERSONALTAB.PERSONALKOD
   FIELD FORNAMN LIKE PERSONALTAB.FORNAMN 
   FIELD EFTERNAMN LIKE PERSONALTAB.EFTERNAMN
   INDEX PKOD IS PRIMARY PERSONALKOD.*/
DEFINE TEMP-TABLE valtemp
   FIELD VALDLISTA AS CHARACTER
   FIELD BAVAL AS INTEGER
   FIELD ALLTID AS LOGICAL
   FIELD STARTDATUM AS DATE
   FIELD SLUTDATUM AS DATE.
DEFINE INPUT-OUTPUT PARAMETER TABLE FOR valtemp.
DEFINE INPUT-OUTPUT PARAMETER TABLE FOR perstemp.
EMPTY TEMP-TABLE perstemp NO-ERROR. 
FIND FIRST valtemp NO-ERROR.

IF valtemp.BAVAL =  1 OR valtemp.BAVAL = 11 THEN DO:
   OPEN QUERY bq FOR EACH BEREDAONR NO-LOCK, 
   EACH PERSONALTAB WHERE PERSONALTAB.PERSONALKOD = BEREDAONR.PERSONALKOD NO-LOCK.
   GET FIRST bq NO-LOCK.
   DO WHILE AVAILABLE(BEREDAONR):
      CREATE perstemp.
      ASSIGN           
      perstemp.PERSONALKOD = BEREDAONR.PERSONALKOD
      perstemp.FORNAMN = PERSONALTAB.FORNAMN
      perstemp.EFTERNAMN = PERSONALTAB.EFTERNAMN.   
      Guru.GlobalaVariabler:GDPRvem = Guru.GlobalaVariabler:GDPRvem + "," + PERSONALTAB.PERSONALKOD.         
      GET NEXT bq NO-LOCK.
   END.
END.
IF valtemp.BAVAL = 2 OR valtemp.BAVAL = 12 THEN DO:
   OPEN QUERY aoq FOR EACH AONRTAB WHERE AONRTAB.AONRAVDATUM = 01/01/91 NO-LOCK.
   GET FIRST aoq NO-LOCK.
   DO WHILE AVAILABLE(AONRTAB):
      IF AONRTAB.STARTDAG = "mån" OR AONRTAB.STARTDAG = "tis" OR 
         AONRTAB.STARTDAG = "ons" OR AONRTAB.STARTDAG = "tor" OR 
         AONRTAB.STARTDAG = "fre" OR AONRTAB.STARTDAG = "lör" OR 
         AONRTAB.STARTDAG = "sön" OR AONRTAB.STARTDAG = "" THEN .
      ELSE DO:
         FIND FIRST perstemp WHERE perstemp.PERSONALKOD = AONRTAB.STARTDAG
         NO-ERROR.
         IF NOT AVAILABLE perstemp THEN DO:
            FIND FIRST PERSONALTAB WHERE PERSONALTAB.PERSONALKOD = AONRTAB.STARTDAG NO-LOCK NO-ERROR.
            IF AVAILABLE PERSONALTAB THEN DO:
               CREATE perstemp.
               ASSIGN 
               perstemp.PERSONALKOD = AONRTAB.STARTDAG               
               perstemp.EFTERNAMN = PERSONALTAB.EFTERNAMN 
               perstemp.FORNAMN = PERSONALTAB.FORNAMN.
               Guru.GlobalaVariabler:GDPRvem = Guru.GlobalaVariabler:GDPRvem + "," + PERSONALTAB.PERSONALKOD.      
            END.
         END.
      END.
      GET NEXT aoq NO-LOCK.
   END.
END.
IF valtemp.BAVAL = 3 OR valtemp.BAVAL = 13 THEN DO:
   OPEN QUERY aq FOR EACH ANSVAONR NO-LOCK,
   EACH PERSONALTAB WHERE PERSONALTAB.PERSONALKOD = ANSVAONR.PERSONALKOD NO-LOCK.
   GET FIRST aq NO-LOCK.
   DO WHILE AVAILABLE(ANSVAONR):
      CREATE perstemp.
      ASSIGN           
      perstemp.PERSONALKOD = ANSVAONR.PERSONALKOD
      perstemp.FORNAMN = ANSVAONR.FORNAMN
      perstemp.EFTERNAMN = ANSVAONR.EFTERNAMN. 
      Guru.GlobalaVariabler:GDPRvem = Guru.GlobalaVariabler:GDPRvem + "," + PERSONALTAB.PERSONALKOD.           
      GET NEXT aq NO-LOCK.
   END.
END.
{GDPRLOGGCLIENT.I}




