/*BOAOAPP.P  */
DEFINE INPUT PARAMETER aonrrec AS RECID NO-UNDO.
DEFINE OUTPUT PARAMETER musz AS LOGICAL NO-UNDO.
FIND AONRTAB WHERE RECID(AONRTAB) = aonrrec NO-LOCK NO-ERROR.                  
IF AONRTAB.FAKTNR = 0 THEN musz = FALSE.
ELSE DO:
   musz = TRUE.   
   RETURN.
END.
FIND FIRST KALKSPEC WHERE KALKSPEC.AONR = AONRTAB.AONR AND
KALKSPEC.DELNR = AONRTAB.DELNR USE-INDEX AONR NO-LOCK NO-ERROR.
IF AVAILABLE KALKSPEC THEN DO:
   musz = TRUE.
   RETURN.
END.    
FIND FIRST KALKAONR WHERE KALKAONR.AONR = AONRTAB.AONR AND
KALKAONR.DELNR = AONRTAB.DELNR USE-INDEX AONR NO-LOCK NO-ERROR.
IF AVAILABLE KALKAONR THEN DO: 
   musz = TRUE.
   RETURN.
END.    

FIND FIRST BEREDNING WHERE BEREDNING.AONR = AONRTAB.AONR AND 
BEREDNING.DELNR = AONRTAB.DELNR USE-INDEX AONR NO-LOCK NO-ERROR.
IF AVAILABLE BEREDNING THEN DO:
   musz = TRUE.
   RETURN.
END.        
FIND FIRST VARDERING WHERE VARDERING.AONR = AONRTAB.AONR AND
VARDERING.DELNR = AONRTAB.DELNR USE-INDEX AONR NO-LOCK NO-ERROR.
IF AVAILABLE VARDERING THEN DO:
   musz = TRUE.
   RETURN.
END.
FIND FIRST VARDERING WHERE VARDERING.AONR = AONRTAB.AONR AND
VARDERING.DELNR = AONRTAB.DELNR USE-INDEX AONR NO-LOCK NO-ERROR.
IF AVAILABLE VARDERING THEN DO:
   musz = TRUE.
   RETURN.
END.
OPEN QUERY aonrkq FOR EACH AONRKONTKOD WHERE AONRKONTKOD.AONR = AONRTAB.AONR AND
AONRKONTKOD.DELNR = AONRTAB.DELNR NO-LOCK.
GET FIRST aonrkq NO-LOCK.
DO WHILE AVAILABLE(AONRKONTKOD):
   DO TRANSACTION:       
      GET CURRENT aonrkq EXCLUSIVE-LOCK.
      DELETE AONRKONTKOD.    
   END.
   GET NEXT aonrkq NO-LOCK.
END.                              
/*
OPEN QUERY succq FOR EACH SUCCAONR WHERE SUCCAONR.AONR = AONRTAB.AONR AND
SUCCAONR.DELNR = SUCCAONR.DELNR NO-LOCK.
GET FIRST succq NO-LOCK.
DO WHILE AVAILABLE(SUCCAONR):
   DO TRANSACTION:       
      GET CURRENT succq EXCLUSIVE-LOCK.
      DELETE SUCCAONR.    
   END.
   GET NEXT succq NO-LOCK.
END.
*/
OPEN QUERY kostq FOR EACH KOSTREG WHERE KOSTREG.AONR = AONRTAB.AONR AND
KOSTREG.DELNR = AONRTAB.DELNR USE-INDEX KOST NO-LOCK.
DO TRANSACTION:       
   GET FIRST kostq EXCLUSIVE-LOCK.
   IF AVAILABLE KOSTREG THEN DELETE KOSTREG.    
END.
REPEAT:  
   DO TRANSACTION:
      GET NEXT kostq EXCLUSIVE-LOCK.
      IF AVAILABLE KOSTREG THEN DELETE KOSTREG.    
      ELSE LEAVE.      
   END.         
END.
OPEN QUERY tidq FOR EACH AONRTIDLAGE WHERE AONRTIDLAGE.AONR = AONRTAB.AONR AND
AONRTIDLAGE.DELNR = AONRTAB.DELNR NO-LOCK.
GET FIRST tidq NO-LOCK.
DO WHILE AVAILABLE(AONRTIDLAGE):
   DO TRANSACTION:       
      GET CURRENT tidq EXCLUSIVE-LOCK.
      
      DELETE AONRTIDLAGE.    
   END.
   GET NEXT tidq NO-LOCK.
END.
DO TRANSACTION:
   FOR EACH AOTIDLKOPP WHERE AOTIDLKOPP.AONR = AONRTAB.AONR AND AOTIDLKOPP.DELNR = AONRTAB.DELNR EXCLUSIVE-LOCK: 
      DELETE AOTIDLKOPP.  
   END.
END.

DO TRANSACTION:
   /*aonr bort mm*/
   FIND AONRTAB WHERE RECID(AONRTAB) = aonrrec EXCLUSIVE-LOCK NO-ERROR.
   DELETE AONRTAB.  
END.
