DEFINE TEMP-TABLE hdschakttemp NO-UNDO
   FIELD SID       AS INTEGER 
   FIELD BERNR     AS INTEGER 
   FIELD OMRADE    AS CHARACTER 
   FIELD BENAMNING AS CHARACTER
   FIELD ANDRAD    AS LOGICAL
   FIELD BORT      AS LOGICAL.