
/*DVLinkApp.p*/
{DEFVALUESNETTT.I}

PROCEDURE FetchEverything:
   DEFINE INPUT PARAMETER Program AS CHARACTER NO-UNDO.
   DEFINE INPUT PARAMETER HuvudChar AS CHARACTER NO-UNDO.
   DEFINE INPUT PARAMETER HuvudInt AS INTEGER NO-UNDO.

   DEFINE VARIABLE DoChar AS LOGICAL INITIAL TRUE NO-UNDO.
   DEFINE VARIABLE DoInt AS LOGICAL INITIAL TRUE NO-UNDO.
   IF HuvudChar EQ "" THEN DoChar = FALSE.
   IF HuvudInt EQ -1 THEN DoInt = FALSE.


   DEFINE VARIABLE q AS CHARACTER NO-UNDO.
   q = "FOR EACH GURUDEFAULTS WHERE GURUDEFAULTS.PROGRAM = ~"" + Program + "~"". 
   
   IF DoChar EQ TRUE THEN q = q + " AND HUVUDCHAR = ~"" + HuvudChar + "~"".
   IF DoInt EQ TRUE THEN q = q + " AND HUVUDINT = ~"" + STRING(HuvudInt) + "~"".
   
   q = q + " NO-LOCK.".
   
   


END PROCEDURE.
