
/*------------------------------------------------------------------------
    File        : EJIPCHKSERVER.I
    Purpose     : 

    Syntax      :

    Description : 

    Author(s)   : 
    Created     : Fri Sep 04 13:34:56 CEST 2020
    Notes       : EJIPCHK VITLISTNING VITLISTA
  ----------------------------------------------------------------------*/

 Computer_LanIP = CHR(69) + CHR(74) + CHR(73) + CHR(80) + CHR(67) + CHR(72) + CHR(75) .
