/* fasttlag.p*/
{NAMNDB.I}
DEFINE INPUT PARAMETER aonrrec AS RECID.
DEFINE INPUT PARAMETER globforetag LIKE FORETAG.FORETAG.
DEFINE VARIABLE mappvar AS CHARACTER NO-UNDO.
DEFINE VARIABLE tlagen AS CHARACTER FORMAT "x(256)" NO-UNDO.

FIND FIRST AONRTAB WHERE RECID(AONRTAB) = aonrrec NO-LOCK NO-ERROR.
IF globforetag = "ELPA" THEN DO:
   mappvar = "\\server05\d\dokument\DOKUMENT\" + AONRTAB.AONR + STRING(AONRTAB.DELNR) + "\".       
END.
ELSE IF namndb() = "GRANNORD" THEN DO:
   /*
   mappvar = "\\DOKUGRAN\DOKUMENT\NÄT (N)\GURU\DOKUMENT\GRAN\" + AONRTAB.AONR + STRING(AONRTAB.DELNR) + "\".         
   */
   mappvar = "\\SRV00486\APPL\GURU\DOKUMENT\GRAN\" + AONRTAB.AONR + STRING(AONRTAB.DELNR) + "\".         
   
END.
ELSE IF namndb() = "GRANES" THEN DO:
   /*
   mappvar = "\\DOKUGRAN\DOKUMENT\NÄT (N)\GURU\DOKUMENT\GRAN\" + AONRTAB.AONR + STRING(AONRTAB.DELNR) + "\".         
   */
   mappvar = "\\SRV00486\APPL\GURU\DOKUMENT\GRAN\" + AONRTAB.AONR + STRING(AONRTAB.DELNR) + "\".         
   
END.
ELSE IF (globforetag = "GRAN" AND namndb() = "UTBI") THEN DO:
   mappvar = "\\SRV00486\APPL\GURU\DOKUMENT\GRANUTBI\" + AONRTAB.AONR + STRING(AONRTAB.DELNR) + "\".         
END.
ELSE IF namndb() = "GRANIT" THEN DO:
   mappvar = "\\SRV00486\APPL\GURU\DOKUMENT\GRANIT\" + AONRTAB.AONR + STRING(AONRTAB.DELNR) + "\".         
END.
ELSE IF namndb() = "GRANADM9" THEN DO:
   mappvar = "\\SRV00486\APPL\GURU\DOKUMENT\GRANADM\" + AONRTAB.AONR + STRING(AONRTAB.DELNR) + "\".         
END.
ELSE IF namndb() = "GRANSOL" THEN DO:
   mappvar = "\\SRV00486\APPL\GURU\DOKUMENT\GRANSOL\" + AONRTAB.AONR + STRING(AONRTAB.DELNR) + "\".         

END.            
ELSE DO:
   mappvar = SESSION:TEMP-DIRECTORY.
END.    

mappvar = mappvar + "fasttrack.txt".

{AMERICANEUROPEAN.I}
OUTPUT TO VALUE(mappvar).


OPEN QUERY tq FOR EACH AONRTIDLAGE WHERE AONRTIDLAGE.AONR = AONRTAB.AONR AND
AONRTIDLAGE.DELNR = AONRTAB.DELNR NO-LOCK,
EACH TIDSLAGEN WHERE TIDSLAGEN.IDTIDLAG = AONRTIDLAGE.idtidlag NO-LOCK.
GET FIRST tq NO-LOCK.
DO WHILE AVAILABLE (AONRTIDLAGE):
   IF AONRTIDLAGE.DATUM1 = ? THEN DO:
      tlagen =  AONRTIDLAG.AONR + CHR(9) + SUBSTRING(AONRTAB.ORT,1,40) + CHR(9) +
      TIDSLAGEN.TIDLAGE + " " + TIDSLAGEN.AKTIVITET1.
   END.
   ELSE DO:
      tlagen =  AONRTIDLAG.AONR + CHR(9) + SUBSTRING(AONRTAB.ORT,1,40) + CHR(9) +
      TIDSLAGEN.TIDLAGE + " " + TIDSLAGEN.AKTIVITET1 + CHR(9) 
      + STRING(AONRTIDLAGE.DATUM1,"9999-99-99").      
   END.

   PUT  tlagen SKIP.
   GET NEXT tq NO-LOCK.
END.

OUTPUT CLOSE.
{EUROPEANAMERICAN.I}
