/*FELTEXTW2.P*/

DEFINE TEMP-TABLE felinut
   FIELD ANVANDARE AS CHARACTER
   FIELD DATUM    AS DATE
   FIELD EMOTAGET AS LOGICAL
   FIELD FELKOD   AS INTEGER
   FIELD FELTEXT  AS CHARACTER
   FIELD PROGRAM  AS CHARACTER
   INDEX FELTEXT IS PRIMARY ANVANDARE FELKOD.
DEFINE INPUT PARAMETER globanv LIKE ANVANDARE.ANVANDARE NO-UNDO.
DEFINE OUTPUT PARAMETER musz AS LOGICAL NO-UNDO.
DEFINE OUTPUT PARAMETER TABLE FOR felinut.
DEFINE QUERY felq FOR FELTEXT.
OPEN QUERY felq FOR EACH FELTEXT WHERE FELTEXT.ANVANDARE = globanv AND 
FELTEXT.EMOTAGET = FALSE
USE-INDEX FELTEXT NO-LOCK.
DO TRANSACTION:
   GET FIRST felq EXCLUSIVE-LOCK.
   IF NOT AVAILABLE FELTEXT THEN RETURN.
   CREATE felinut.
   BUFFER-COPY FELTEXT TO felinut.
   ASSIGN FELTEXT.EMOTAGET = TRUE.
   musz = TRUE.
END.    
REPEAT:
   DO TRANSACTION:
      GET NEXT felq EXCLUSIVE-LOCK.
      IF NOT AVAILABLE FELTEXT THEN LEAVE.
      CREATE felinut.
      BUFFER-COPY FELTEXT TO felinut.
      ASSIGN FELTEXT.EMOTAGET = TRUE.      
   END.    
END.
         
