/*FELTEXTW.P*/
DEFINE TEMP-TABLE felmeddtemp 
  FIELD FELMEDD AS CHARACTER
  FIELD VAL AS INTEGER.
DEFINE INPUT PARAMETER  globanv LIKE ANVANDARE.ANVANDARE NO-UNDO.
DEFIN OUTPUT PARAMETER TABLE FOR felmeddtemp.
DEFINE OUTPUT PARAMETER musz AS LOGICAL NO-UNDO.
DEFINE QUERY felq FOR FELTEXT.
OPEN QUERY felq FOR EACH FELTEXT WHERE FELTEXT.ANVANDARE = globanv AND 
FELTEXT.EMOTAGET = FALSE
USE-INDEX FELTEXT NO-LOCK.
DO TRANSACTION:
   GET FIRST felq EXCLUSIVE-LOCK.
   IF NOT AVAILABLE FELTEXT THEN RETURN.
   CREATE felmeddtemp.  
   ASSIGN                        
   felmeddtemp.FELMEDD = FELTEXT.FELTEXT.
   ASSIGN FELTEXT.EMOTAGET = TRUE.
   musz = TRUE.
END.    
REPEAT:
   DO TRANSACTION:
      GET NEXT felq EXCLUSIVE-LOCK.
      IF NOT AVAILABLE FELTEXT THEN LEAVE.
      CREATE felmeddtemp.  
      ASSIGN                        
      felmeddtemp.FELMEDD = FELTEXT.FELTEXT.
      ASSIGN FELTEXT.EMOTAGET = TRUE.
   END.    
END.
         
