/*FORVER.P SKA EJ GÅ ATT KOMPILERA I WEB körs ej*/
DEFINE INPUT PARAMETER gforetag AS CHARACTER NO-UNDO.
DEFINE INPUT PARAMETER appvar AS CHARACTER NO-UNDO.
{NAMNDB.I}
FIND FIRST FORETAG NO-LOCK NO-ERROR.
IF SUBSTRING(FORETAG.VERSION,20,1) = "" THEN DO TRANSACTION:
   RUN FORETAGAPPKOLL.P (INPUT gforetag, OUTPUT gforetag).
   FIND CURRENT FORETAG EXCLUSIVE-LOCK NO-ERROR.
   ASSIGN
   SUBSTRING(FORETAG.VERSION,20,10) = gforetag
   SUBSTRING(FORETAG.VERSION,32) = appvar.
END.
ELSE DO:
   
   IF SUBSTRING(FORETAG.VERSION,20,10) = gforetag AND  SUBSTRING(FORETAG.VERSION,32) = appvar THEN.
   ELSE DO TRANSACTION:
      RUN FORETAGAPPKOLL.P (INPUT gforetag, OUTPUT gforetag).
      FIND CURRENT FORETAG EXCLUSIVE-LOCK NO-ERROR.
      IF appvar = "" THEN DO: 
         SUBSTRING(FORETAG.VERSION,20,70) ="".
         ASSIGN
         SUBSTRING(FORETAG.VERSION,20,10) = gforetag
         SUBSTRING(FORETAG.VERSION,32) = appvar.
      END.   
   END.
   
END.
IF namndb() = "utbi" THEN. 
ELSE DO TRANSACTION:
   RUN FORETAGAPPKOLL.P (INPUT gforetag, OUTPUT gforetag).
   IF appvar = "" THEN DO:
      FIND CURRENT FORETAG EXCLUSIVE-LOCK NO-ERROR.
      SUBSTRING(FORETAG.VERSION,20,70) ="".
      ASSIGN
      SUBSTRING(FORETAG.VERSION,20,10) = gforetag
      SUBSTRING(FORETAG.VERSION,32) = appvar.
   END.
END.
RELEASE FORETAG.
