
/*------------------------------------------------------------------------
    File        : FUNCAONRSTART.I
    Purpose     : 

    Syntax      :

    Description : 

    Author(s)   : 
    Created     : Tue Oct 20 11:34:28 CEST 2015
    Notes       :
  ----------------------------------------------------------------------*/

FUNCTION brwval RETURNS LOGICAL
  ( /* parameter-definitions */ )  FORWARD.
FUNCTION checkbrw RETURNS LOGICAL
  ( /* parameter-definitions */ )  FORWARD.