/*GURUAPPc.P*/


Guru.SharedVariable:singel = FALSE.
{LDALIAS8.I}

DEFINE VARIABLE ffah AS HANDLE NO-UNDO.
CREATE BUFFER ffah FOR TABLE "FORETAG" .
ffah:FIND-FIRST("WHERE  ",NO-LOCK) NO-ERROR.
RUN Spring.p (TRUE, SUBSTRING(ffah:BUFFER-FIELD("VERSION"):BUFFER-VALUE,20,10) ).

{DELALIAS.I}
