/*KHMT.P*/


DEFINE TEMP-TABLE ktotemp
   FIELD KONTO AS CHARACTER
   FIELD KONTONR AS CHARACTER
   FIELD BENAMNING AS CHARACTER
   FIELD JUDID AS CHARACTER
   FIELD VIJUDID AS CHARACTER
   FIELD OMRADE AS CHARACTER
   FIELD AVDELNINGNR AS INTEGER
   FIELD AKTIV AS LOGICAL
   FIELD RECTIDVIS AS RECID
   INDEX KONTO KONTO KONTONR.

DEFINE INPUT PARAMETER vadgora AS INTEGER NO-UNDO.
DEFINE INPUT PARAMETER fglobforetag AS CHARACTER NO-UNDO.
DEFINE OUTPUT PARAMETER TABLE FOR ktotemp.
&Scoped-define NEW NEW
{GLOBVAR2DEL1.I}

RUN STYRFORE.P (INPUT Guru.Konstanter:globforetag).

IF vadgora = 1 THEN DO:

   OPEN QUERY till FOR EACH KONTO WHERE KONTO.AKTIV = TRUE NO-LOCK.
   GET FIRST till NO-LOCK.   
   DO WHILE AVAILABLE(KONTO):     
      CREATE ktotemp.   
      ASSIGN
      ktotemp.KONTO = KONTO.KONTO
      ktotemp.KONTONR = KONTO.KONTONR
      ktotemp.BENAMNING = KONTO.BENAMNING         
      ktotemp.JUDID = KONTO.JUDID
      ktotemp.OMRADE = KONTO.OMRADE
      ktotemp.AVDELNINGNR = KONTO.AVDELNINGNR
      ktotemp.AKTIV = KONTO.AKTIV
      ktotemp.RECTIDVIS = RECID(KONTO).
      /*konto jurp*/
      IF Guru.Konstanter:varforetypval[18] = 1 THEN DO:
         FIND FIRST JURPERS WHERE JURPERS.JUDID = KONTO.JUDID NO-LOCK NO-ERROR.
         IF AVAILABLE JURPERS THEN DO: 
            ASSIGN ktotemp.VIJUDID = JURPERS.VIJUDID.
         END.
      END.
      
      GET NEXT till NO-LOCK.      
   END.
   CLOSE QUERY till.
END.
