/*KONTSPARAPP.P*/
&Scoped-define NEW NEW
&Scoped-define SHARED SHARED
{GLOBVAR2DEL1.I}
{REGVAR.I}

{AVTPLANTEMP.I}

DEFINE INPUT PARAMETER aonrvar AS CHARACTER NO-UNDO.
DEFINE INPUT PARAMETER delnrvar AS INTEGER NO-UNDO.
DEFINE INPUT PARAMETER plannrvar AS CHARACTER NO-UNDO.
DEFINE INPUT PARAMETER artalvar AS INTEGER NO-UNDO.
DEFINE INPUT PARAMETER benvar AS CHARACTER NO-UNDO.
DEFINE INPUT PARAMETER SEL_K1 AS CHARACTER NO-UNDO.
DEFINE INPUT PARAMETER SEL_K2 AS CHARACTER NO-UNDO.
DEFINE INPUT PARAMETER SEL_K3 AS CHARACTER NO-UNDO.
DEFINE INPUT PARAMETER SEL_K4 AS CHARACTER NO-UNDO.
DEFINE INPUT PARAMETER SEL_K5 AS CHARACTER NO-UNDO.
DEFINE VARIABLE radnrvar AS INTEGER NO-UNDO.

FIND LAST KONTOSTRANG USE-INDEX KONTO2 NO-LOCK NO-ERROR.
IF AVAILABLE KONTOSTRANG THEN DO: 
   ASSIGN radnrvar = KONTOSTRANG.RADNR + 1.
END.
ELSE DO: 
   ASSIGN radnrvar = 1.
END.
CREATE KONTOSTRANG.   
ASSIGN 
KONTOSTRANG.RADNR = radnrvar.
FIND AONRTAB WHERE AONRTAB.AONR = aonrvar AND 
AONRTAB.DELNR = delnrvar NO-LOCK NO-ERROR.
IF AVAILABLE AONRTAB THEN DO: 
   KONTOSTRANG.OMRADE = AONRTAB.OMRADE.
END.      
ELSE DO:
   FIND PLANNRTAB WHERE PLANNRTAB.PLANNR = plannrvar AND 
   PLANNRTAB.ARTAL = artalvar NO-LOCK NO-ERROR.
   KONTOSTRANG.OMRADE = PLANNRTAB.OMRADE.     
END.   
ASSIGN         
KONTOSTRANG.BENAMNING = benvar. 
IF SEL_K1 = "BLANK" THEN ASSIGN KONTOSTRANG.K1 = "" .
ELSE IF SEL_K1 = ? THEN ASSIGN KONTOSTRANG.K1 = "" .
ELSE ASSIGN KONTOSTRANG.K1 = SEL_K1.
IF SEL_K2 = "BLANK" THEN ASSIGN KONTOSTRANG.K2 = "" .
ELSE IF SEL_K2 = ? THEN ASSIGN KONTOSTRANG.K2 = "" .
ELSE ASSIGN KONTOSTRANG.K2 = SEL_K2.
IF SEL_K3 = "BLANK" THEN ASSIGN KONTOSTRANG.K3 = "" .
ELSE IF SEL_K3 = ? THEN ASSIGN KONTOSTRANG.K3 = "" .
ELSE ASSIGN KONTOSTRANG.K3 = SEL_K3.
IF SEL_K4 = "BLANK" THEN ASSIGN KONTOSTRANG.K4 = "" .
ELSE IF SEL_K4 = ? THEN ASSIGN KONTOSTRANG.K4 = "" .   
ELSE ASSIGN KONTOSTRANG.K4 = SEL_K4.
IF SEL_K5 = "BLANK" THEN ASSIGN KONTOSTRANG.K5 = "" .
ELSE IF SEL_K5 = ? THEN ASSIGN KONTOSTRANG.K5 = "" .
ELSE ASSIGN KONTOSTRANG.K5 = SEL_K5.
VALIDATE KONTOSTRANG.
