/*KSTUPPD.P*/


DEFINE TEMP-TABLE kstrang
   FIELD BENAMNING AS CHARACTER
   FIELD K1 AS CHARACTER
   FIELD K2 AS CHARACTER
   FIELD K3 AS CHARACTER
   FIELD K4 AS CHARACTER
   FIELD K5 AS CHARACTER
   FIELD OMRADE AS CHARACTER
   FIELD RADNR AS INTEGER
   FIELD RECTIDVIS AS RECID
   INDEX KONTO K1 K2 K3 K4 K5
   INDEX KONTO2 RADNR.


DEFINE INPUT PARAMETER vadgora AS INTEGER NO-UNDO.
DEFINE INPUT-OUTPUT PARAMETER ktorec AS RECID NO-UNDO.
DEFINE INPUT-OUTPUT PARAMETER TABLE FOR kstrang.


IF vadgora = 1 THEN DO: /*ny*/
   FIND FIRST kstrang WHERE kstrang.RECTIDVIS = ? NO-ERROR.
   DO TRANSACTION:   
      CREATE KONTOSTRANG.            
      ASSIGN
      KONTOSTRANG.BENAMNING = kstrang.BENAMNING
      KONTOSTRANG.K1 = kstrang.K1
      KONTOSTRANG.K2 = kstrang.K2         
      KONTOSTRANG.K3 = kstrang.K3
      KONTOSTRANG.K4 = kstrang.K4
      KONTOSTRANG.K5 = kstrang.K5
      KONTOSTRANG.RADNR = kstrang.RADNR      
      KONTOSTRANG.OMRADE = kstrang.OMRADE     
      kstrang.RECTIDVIS = RECID(KONTOSTRANG)
      ktorec = RECID(KONTOSTRANG).

   END.
END.
ELSE IF vadgora = 2 THEN DO: /*Ändra benämning*/
   DO TRANSACTION:
      FIND FIRST kstrang WHERE kstrang.RECTIDVIS = ktorec NO-LOCK NO-ERROR.
      FIND FIRST KONTOSTRANG WHERE KONTOSTRANG.OMRADE = kstrang.OMRADE AND KONTOSTRANG.K1    = kstrang.K1 AND KONTOSTRANG.K2 = kstrang.K2 AND KONTOSTRANG.K3 = kstrang.K3 
      AND KONTOSTRANG.K4 = kstrang.K4 AND KONTOSTRANG.K5 = kstrang.K5 EXCLUSIVE-LOCK NO-ERROR.
      IF AVAILABLE KONTOSTRANG  THEN DO:
         KONTOSTRANG.BENAMNING = kstrang.BENAMNING.
         kstrang.RECTIDVIS = RECID(KONTOSTRANG).
         ktorec = RECID(KONTOSTRANG).
      END.   
   END.   
END.
ELSE IF vadgora = 3 THEN DO:
   DO TRANSACTION:   
      FIND FIRST KONTOSTRANG WHERE RECID(KONTOSTRANG) = ktorec EXCLUSIVE-LOCK NO-ERROR.
      DELETE KONTOSTRANG.

   END.
END.
ELSE IF vadgora = 4 THEN DO:

END.

