/*MEDDBORT.P*/
DEFINE VARIABLE musz AS LOGICAL NO-UNDO.
OPEN QUERY meddq FOR EACH MEDDELANDE WHERE MEDDELANDE.EMOTAGET = FALSE NO-LOCK.      
DO TRANSACTION:
   GET FIRST meddq EXCLUSIVE-LOCK.
   IF AVAILABLE MEDDELANDE THEN DO:
      IF MEDDELANDE.SANDARE = "FAKT.ADM." THEN musz = musz.
      ELSE IF MEDDELANDE.SDATUM <= TODAY - 30 THEN DELETE MEDDELANDE.
   END.      
END.   
REPEAT:
   DO TRANSACTION:
      GET NEXT meddq EXCLUSIVE-LOCK.
      IF AVAILABLE MEDDELANDE THEN DO:
         IF MEDDELANDE.SANDARE = "FAKT.ADM." THEN musz = musz.
         ELSE IF MEDDELANDE.SDATUM <= TODAY - 30 THEN DELETE MEDDELANDE.
      END.      
      ELSE LEAVE.
   END.
END.
CLOSE QUERY meddq.    
