/*MEDSKAP.P*/
{ANDMEDUT.I}
FOR EACH meddpers USE-INDEX ANV NO-LOCK:
   DO TRANSACTION:
      CREATE MEDDELANDE.
      ASSIGN 
      MEDDELANDE.SDATUM = TODAY
      MEDDELANDE.EMOTAGET = FALSE
      MEDDELANDE.MEDD = EDITOR_MEDD
      MEDDELANDE.MOTTAGARE = meddpers.ANVANDARE. 
      MEDDELANDE.SANDARE = Guru.Konstanter:globanv.
   END.   
END.      
