/*SEKSTART.P*/
DEFINE TEMP-TABLE xsektemp
  FIELD AV-LEVEL AS INTEGER
  FIELD MENYVART AS CHARACTER
  FIELD SEK AS LOGICAL EXTENT 20
  INDEX XSEK IS PRIMARY MENYVART AV-LEVEL.
DEFINE INPUT PARAMETER xhop AS CHARACTER NO-UNDO.            
DEFINE INPUT PARAMETER globniv AS INTEGER NO-UNDO. 
DEFINE OUTPUT PARAMETER TABLE FOR xsektemp.
EMPTY TEMP-TABLE xsektemp NO-ERROR. 
FOR EACH XSEK WHERE XSEK.AV-LEVEL = globniv  NO-LOCK.
   CREATE xsektemp.
   BUFFER-COPY XSEK TO xsektemp.
END. 
