/*SJINTYG.P*/
&Scoped-define NEW NEW
{GLOBVAR2DEL1.I}

DEFINE BUFFER medbuff FOR MEDDELANDE.

FIND FIRST FORETAG NO-LOCK NO-ERROR.
Guru.Konstanter:globforetag = FORETAG.FORETAG.
RUN STYRFORE.P (INPUT Guru.Konstanter:globforetag).
OPEN QUERY aq FOR EACH TIDREGITAB WHERE TIDREGITAB.DATUM = TODAY AND
TIDREGITAB.AONR = "110" NO-LOCK.
GET FIRST aq NO-LOCK.
DO WHILE AVAILABLE(AONRTAB):   
   RUN medd_UI.
   GET NEXT aq NO-LOCK.
END.
PROCEDURE medd_UI:  
   FIND FIRST ANVANDARE WHERE ANVANDARE.PERSONALKOD = AONRTAB.ARBANSVARIG 
   NO-LOCK NO-ERROR.
   IF NOT AVAILABLE ANVANDARE THEN DO:
      FIND FIRST ANVANDARE WHERE ANVANDARE.ANVANDARE = "MON" 
      NO-LOCK NO-ERROR.
      IF NOT AVAILABLE ANVANDARE THEN RETURN.
   END.
   FIND FIRST MEDDELANDE WHERE MEDDELANDE.SANDARE = "SLUTBESIKTNING" AND 
   MEDDELANDE.MOTTAGARE = ANVANDARE.ANVANDARE AND LENGTH(MEDDELANDE.MEDD,"CHARACTER") < 30000 
   EXCLUSIVE-LOCK NO-ERROR.
   IF NOT AVAILABLE MEDDELANDE THEN DO:
      CREATE MEDDELANDE.
      ASSIGN               
      MEDDELANDE.SANDARE = "SLUTBESIKTNING"
      MEDDELANDE.EMOTAGET = FALSE
      MEDDELANDE.SDATUM = TODAY
      MEDDELANDE.MEDD = CAPS(Guru.Konstanter:gaok) + " FÖR SLUT BESIKTNING" + CHR(10) 
      MEDDELANDE.MOTTAGARE = ANVANDARE.ANVANDARE.
   END.
   MEDDELANDE.MED = MEDDELANDE.MED + AONRTAB.AONR + " " +  
   STRING(DELNR,Guru.Konstanter:varforetypchar[1]) + " " + AONRTAB.ORT +  CHR(10).   
END PROCEDURE.
