/*TLAGAUTO.P*/

&Scoped-define NEW NEW
{REGVAR.I}

DEFINE INPUT PARAMETER globanv LIKE ANVANDARE.ANVANDARE NO-UNDO.
DEFINE INPUT PARAMETER aonrrec AS RECID NO-UNDO.
DEFINE INPUT PARAMETER tlagevar LIKE TIDSLAGEN.IDTIDLAG NO-UNDO.

FIND FIRST FORETAG NO-LOCK NO-ERROR.
Guru.Konstanter:globforetag = FORETAG.FORETAG.
IF tlagevar = "Attest" THEN DO:
   FIND AONRTAB WHERE RECID(AONRTAB) = aonrrec NO-LOCK NO-ERROR.
   DO TRANSACTION:
      FIND FIRST TIDSLAGEN WHERE TIDSLAGEN.IDTIDLAG = tlagevar NO-LOCK NO-ERROR.
      IF NOT AVAILABLE TIDSLAGEN THEN DO:
         RETURN.         
      END.
      FIND FIRST BEREDNING WHERE BEREDNING.AONR = AONRTAB.AONR AND
      BEREDNING.DELNR = AONRTAB.DELNR NO-LOCK NO-ERROR.
      FIND LAST BERMTRL WHERE BERMTRL.AONR = BEREDNING.BERAONR AND 
      BERMTRL.OMRADE = BEREDNING.OMRADE AND BERMTRL.INKOP = FALSE 
      USE-INDEX DATUM NO-LOCK NO-ERROR.
      IF AVAILABLE BERMTRL THEN DO:
         FIND FIRST AONRTIDLAGE WHERE AONRTIDLAGE.IDTIDLAG = TIDSLAGE.IDTIDLAG AND 
         AONRTIDLAGE.DATUM1 = BERMTRL.DATUM AND AONRTIDLAGE.AONR = AONRTAB.AONR AND
         AONRTIDLAGE.DELNR = AONRTAB.DELNR EXCLUSIVE-LOCK NO-ERROR.
         IF AVAILABLE AONRTIDLAGE THEN DO:
            AONRTIDLAGE.DATUM2 = TODAY.          
         END.
         ELSE DO:
            CREATE AONRTIDLAGE.
            ASSIGN
            AONRTIDLAGE.IDTIDLAG = TIDSLAGEN.IDTIDLAG   
            AONRTIDLAGE.ANVANDARE1 = globanv
            AONRTIDLAGE.ANVANDARE2 = "AUTOMATISKT"
            AONRTIDLAGE.AONR = AONRTAB.AONR  
            AONRTIDLAGE.DELNR = AONRTAB.DELNR  
            AONRTIDLAGE.DATUM1 = BERMTRL.DATUM.          
         END.         
      END.              
   END.
END.
ELSE IF tlagevar = "TIDFÖRD" THEN DO:
   FIND AONRTAB WHERE RECID(AONRTAB) = aonrrec NO-LOCK NO-ERROR.
   DO TRANSACTION:
      FIND FIRST TIDSLAGEN WHERE TIDSLAGEN.IDTIDLAG = tlagevar NO-LOCK NO-ERROR.
      IF NOT AVAILABLE TIDSLAGEN THEN DO:
         CREATE TIDSLAGE.
         ASSIGN
         TIDSLAGEN.AKTIVITET1 = "Ja"
         TIDSLAGEN.IDTIDLAG = "TIDFÖRD"
         TIDSLAGEN.TIDLAGE = "TIDFÖRD".
      END.
      FIND FIRST AONRTIDLAGE WHERE 
      AONRTIDLAGE.AONR = AONRTAB.AONR AND 
      AONRTIDLAGE.DELNR = AONRTAB.DELNR AND
      AONRTIDLAGE.IDTIDLAG = TIDSLAGEN.IDTIDLAG
      EXCLUSIVE-LOCK NO-ERROR.
      IF AVAILABLE AONRTIDLAGE THEN DO:
         ASSIGN
         AONRTIDLAGE.ANVANDARE1 = globanv
         AONRTIDLAGE.ANVANDARE2 = "AUTOMATISKT"
         AONRTIDLAGE.DATUM1 = AONRTAB.STARTDATUM.
         RETURN.
      END.
      ELSE DO:
         CREATE AONRTIDLAGE.
      END.
      ASSIGN
      AONRTIDLAGE.IDTIDLAG = TIDSLAGEN.IDTIDLAG   
      AONRTIDLAGE.ANVANDARE1 = globanv
      AONRTIDLAGE.ANVANDARE2 = "AUTOMATISKT"
      AONRTIDLAGE.AONR = AONRTAB.AONR  
      AONRTIDLAGE.DELNR = AONRTAB.DELNR  
      AONRTIDLAGE.DATUM1 = AONRTAB.STARTDATUM.      
   END.
END.
ELSE IF tlagevar = "BESTÄLLT" THEN DO:
   FIND AONRTAB WHERE RECID(AONRTAB) = aonrrec NO-LOCK NO-ERROR.
   IF AONRTAB.OMRADE = AONRTAB.BESTID THEN RETURN.
   IF AONRTAB.OMRADE = "" THEN RETURN.
   IF AONRTAB.DELNR NE 0 THEN RETURN.
   DO TRANSACTION:
      FIND FIRST TIDSLAGEN WHERE TIDSLAGEN.IDTIDLAG = tlagevar NO-LOCK NO-ERROR.
      IF NOT AVAILABLE TIDSLAGEN THEN DO:
         CREATE TIDSLAGE.
         ASSIGN
         TIDSLAGEN.AKTIVITET1 = "Ja"
         TIDSLAGEN.IDTIDLAG = "BESTÄLLT"
         TIDSLAGEN.TIDLAGE = "BESTÄLLT".
      END.
      FIND FIRST AONRTIDLAGE WHERE 
      AONRTIDLAGE.AONR = AONRTAB.AONR AND 
      AONRTIDLAGE.DELNR = AONRTAB.DELNR AND
      AONRTIDLAGE.IDTIDLAG = TIDSLAGEN.IDTIDLAG
      EXCLUSIVE-LOCK NO-ERROR.
      IF AVAILABLE AONRTIDLAGE THEN DO:
         IF AONRTIDLAGE.DATUM1 = ? THEN aonrrec = aonrrec.
         ELSE RETURN.
      END.
      ELSE DO:
         CREATE AONRTIDLAGE.
      END.
      ASSIGN
      AONRTIDLAGE.IDTIDLAG = TIDSLAGEN.IDTIDLAG   
      AONRTIDLAGE.ANVANDARE1 = globanv
      AONRTIDLAGE.ANVANDARE2 = "AUTOMATISKT"
      AONRTIDLAGE.AONR = AONRTAB.AONR  
      AONRTIDLAGE.DELNR = AONRTAB.DELNR  
      AONRTIDLAGE.DATUM1 = TODAY.
      /*
      FIND FIRST SUCCAONR WHERE 
      SUCCAONR.AONR = AONRTAB.AONR AND SUCCAONR.DELNR = AONRTAB.DELNR 
      EXCLUSIVE-LOCK NO-ERROR.
      IF AVAILABLE SUCCAONR THEN DO:   
         ASSIGN    
         SUCCAONR.GRUNDBERTID = SUCCAONR.BERTID  
         SUCCAONR.GRUNDEA = SUCCAONR.EA 
         SUCCAONR.GRUNDMTRLK = SUCCAONR.MTRLK 
         SUCCAONR.GRUNDPLANMASK = SUCCAONR.PLANMASK 
         SUCCAONR.GRUNDPLANMONT = SUCCAONR.PLANMONT.                  
      END.   
      */
   END.
END.
ELSE IF tlagevar = "AONRAVSL" THEN DO:
   FIND AONRTAB WHERE RECID(AONRTAB) = aonrrec NO-LOCK NO-ERROR.
   DO TRANSACTION:
      FIND FIRST TIDSLAGEN WHERE TIDSLAGEN.IDTIDLAG = tlagevar NO-LOCK NO-ERROR.
      IF NOT AVAILABLE TIDSLAGEN THEN DO:
         IF NOT AVAILABLE TIDSLAGEN THEN DO:
            CREATE TIDSLAGE.
            ASSIGN
            TIDSLAGEN.AKTIVITET1 = "Ja"
            TIDSLAGEN.IDTIDLAG = "AONRAVSL"
            TIDSLAGEN.TIDLAGE = "Projkt avslutat".
         END.
      END.
      FIND FIRST AONRTIDLAGE WHERE 
      AONRTIDLAGE.AONR = AONRTAB.AONR AND 
      AONRTIDLAGE.DELNR = AONRTAB.DELNR AND
      AONRTIDLAGE.IDTIDLAG = TIDSLAGEN.IDTIDLAG
      EXCLUSIVE-LOCK NO-ERROR.
      IF AVAILABLE AONRTIDLAGE THEN DO:
         IF AONRTAB.AONRAVDATUM = 01/01/91 OR AONRTAB.AONRAVDATUM = 01/01/89 THEN DO:          
            DELETE AONRTIDLAGE.
            RETURN.
         END.
         IF AONRTIDLAGE.DATUM1 = ? THEN aonrrec = aonrrec.
         ELSE RETURN.
      END.
      ELSE DO:
         IF AONRTAB.AONRAVDATUM = 01/01/91 OR AONRTAB.AONRAVDATUM = 01/01/89 THEN RETURN.
         ELSE CREATE AONRTIDLAGE.         
      END.
      ASSIGN
      AONRTIDLAGE.IDTIDLAG = TIDSLAGEN.IDTIDLAG   
      AONRTIDLAGE.ANVANDARE1 = globanv
      AONRTIDLAGE.ANVANDARE2 = "AUTOMATISKT"
      AONRTIDLAGE.AONR = AONRTAB.AONR  
      AONRTIDLAGE.DELNR = AONRTAB.DELNR  
      AONRTIDLAGE.DATUM1 = AONRTAB.AONRAVDATUM
      AONRTIDLAGE.DATUM2 = TODAY.         
   END.
   /*
   DO TRANSACTION:
      FIND FIRST TIDSLAGEN WHERE TIDSLAGEN.IDTIDLAG = "MONTTID" NO-LOCK NO-ERROR.
      IF NOT AVAILABLE TIDSLAGEN THEN RETURN.
      FIND FIRST AONRTIDLAGE WHERE 
      AONRTIDLAGE.AONR = AONRTAB.AONR AND 
      AONRTIDLAGE.DELNR = AONRTAB.DELNR AND
      AONRTIDLAGE.IDTIDLAG = TIDSLAGEN.IDTIDLAG
      EXCLUSIVE-LOCK NO-ERROR.
      IF NOT AVAILABLE AONRTIDLAGE THEN DO:
         RETURN.
      END.
      ELSE DO:         
         IF AONRTIDLAGE.DATUM2 = ? THEN DO:
            ASSIGN
            AONRTIDLAGE.IDTIDLAG = TIDSLAGEN.IDTIDLAG   
            AONRTIDLAGE.ANVANDARE1 = globanv
            AONRTIDLAGE.ANVANDARE2 = "AUTOMATISKT"
            AONRTIDLAGE.AONR = AONRTAB.AONR  
            AONRTIDLAGE.DELNR = AONRTAB.DELNR  
            AONRTIDLAGE.DATUM2 = TODAY.         
         END.        
      END.
   END.
   */
END. 


ELSE IF tlagevar = "TEKNAVSLDATUM" THEN DO:
   FIND AONRTAB WHERE RECID(AONRTAB) = aonrrec NO-LOCK NO-ERROR.
   DO TRANSACTION:
      FIND FIRST TIDSLAGEN WHERE TIDSLAGEN.IDTIDLAG = tlagevar NO-LOCK NO-ERROR.
      IF NOT AVAILABLE TIDSLAGEN THEN DO:
         IF NOT AVAILABLE TIDSLAGEN THEN DO:
            CREATE TIDSLAGE.
            ASSIGN
            TIDSLAGEN.AKTIVITET1 = "Ja"
            TIDSLAGEN.IDTIDLAG = tlagevar
            TIDSLAGEN.TIDLAGE = "Tekniskt avslut".
         END.
      END.
      FIND FIRST AONRTIDLAGE WHERE 
      AONRTIDLAGE.AONR = AONRTAB.AONR AND 
      AONRTIDLAGE.DELNR = AONRTAB.DELNR AND
      AONRTIDLAGE.IDTIDLAG = TIDSLAGEN.IDTIDLAG
      EXCLUSIVE-LOCK NO-ERROR.
      IF NOT AVAILABLE AONRTIDLAGE THEN DO:
         CREATE AONRTIDLAGE.         
      END.
      ASSIGN
      AONRTIDLAGE.IDTIDLAG = TIDSLAGEN.IDTIDLAG   
      AONRTIDLAGE.ANVANDARE1 = "AUTOMATISKT"
      AONRTIDLAGE.AONR = AONRTAB.AONR  
      AONRTIDLAGE.DELNR = AONRTAB.DELNR  
      AONRTIDLAGE.DATUM1 = TODAY.         
   END.
   
END. 

ELSE IF tlagevar = "EKAVSLUT" THEN DO:
   FIND AONRTAB WHERE RECID(AONRTAB) = aonrrec NO-LOCK NO-ERROR.
   DO TRANSACTION:
      FIND FIRST TIDSLAGEN WHERE TIDSLAGEN.IDTIDLAG = tlagevar NO-LOCK NO-ERROR.
      IF NOT AVAILABLE TIDSLAGEN THEN DO:
         IF NOT AVAILABLE TIDSLAGEN THEN DO:
            CREATE TIDSLAGE.
            ASSIGN
            TIDSLAGEN.AKTIVITET1 = "Ja"
            TIDSLAGEN.IDTIDLAG = tlagevar
            TIDSLAGEN.TIDLAGE = "Ekonomiskt avslut".
         END.
      END.
      FIND FIRST AONRTIDLAGE WHERE 
      AONRTIDLAGE.AONR = AONRTAB.AONR AND 
      AONRTIDLAGE.DELNR = AONRTAB.DELNR AND
      AONRTIDLAGE.IDTIDLAG = TIDSLAGEN.IDTIDLAG
      EXCLUSIVE-LOCK NO-ERROR.
      IF NOT AVAILABLE AONRTIDLAGE THEN DO:
         CREATE AONRTIDLAGE.         
      END.
      ASSIGN
      AONRTIDLAGE.IDTIDLAG = TIDSLAGEN.IDTIDLAG   
      AONRTIDLAGE.ANVANDARE1 = "AUTOMATISKT"
      AONRTIDLAGE.AONR = AONRTAB.AONR  
      AONRTIDLAGE.DELNR = AONRTAB.DELNR  
      AONRTIDLAGE.DATUM1 = TODAY.         
   END.
   
END. 

ELSE IF tlagevar = "AOUPPLAGT" THEN DO:
   FIND AONRTAB WHERE RECID(AONRTAB) = aonrrec NO-LOCK NO-ERROR.
   DO TRANSACTION:
      FIND FIRST TIDSLAGEN WHERE TIDSLAGEN.IDTIDLAG = tlagevar NO-LOCK NO-ERROR.
      IF NOT AVAILABLE TIDSLAGEN THEN DO:
         CREATE TIDSLAGEN.
         ASSIGN
         TIDSLAGEN.AKTIVITET1 = "Ja"
         TIDSLAGEN.IDTIDLAG = "AOUPPLAGT" 
         TIDSLAGEN.TIDLAGE = "UPPLAGT".
      END.
      FIND FIRST AONRTIDLAGE WHERE 
      AONRTIDLAGE.AONR = AONRTAB.AONR AND 
      AONRTIDLAGE.DELNR = AONRTAB.DELNR AND
      AONRTIDLAGE.IDTIDLAG = TIDSLAGEN.IDTIDLAG
      EXCLUSIVE-LOCK NO-ERROR.
      IF AVAILABLE AONRTIDLAGE THEN DO:
         IF AONRTIDLAGE.DATUM1 = ? THEN aonrrec = aonrrec.
         ELSE RETURN.
      END.
      ELSE DO:
         CREATE AONRTIDLAGE.
      END.
      ASSIGN
      AONRTIDLAGE.IDTIDLAG = TIDSLAGEN.IDTIDLAG   
      AONRTIDLAGE.ANVANDARE1 = globanv
      AONRTIDLAGE.ANVANDARE2 = "AUTOMATISKT"
      AONRTIDLAGE.AONR = AONRTAB.AONR  
      AONRTIDLAGE.DELNR = AONRTAB.DELNR  
      AONRTIDLAGE.DATUM1 = TODAY.         
   END.
END.
ELSE IF tlagevar = "MONTTID" THEN DO:
   FIND AONRTAB WHERE RECID(AONRTAB) = aonrrec NO-LOCK NO-ERROR.
   DO TRANSACTION:
      FIND FIRST TIDSLAGEN WHERE TIDSLAGEN.IDTIDLAG = tlagevar NO-LOCK NO-ERROR.
      IF NOT AVAILABLE TIDSLAGEN THEN DO:
         CREATE TIDSLAGEN.
         ASSIGN
         TIDSLAGEN.AKTIVITET1 = "Ja"
         TIDSLAGEN.IDTIDLAG = "MONTTID" 
         TIDSLAGEN.TIDLAGE = "MONTÖRSTID STARTAD".      
      END.
      FIND FIRST AONRTIDLAGE WHERE 
      AONRTIDLAGE.AONR = AONRTAB.AONR AND 
      AONRTIDLAGE.DELNR = AONRTAB.DELNR AND
      AONRTIDLAGE.IDTIDLAG = TIDSLAGEN.IDTIDLAG
      EXCLUSIVE-LOCK NO-ERROR.
      IF AVAILABLE AONRTIDLAGE THEN DO:
         RETURN.
      END.
      ELSE DO:
         CREATE AONRTIDLAGE.
      END.
      ASSIGN
      AONRTIDLAGE.IDTIDLAG = TIDSLAGEN.IDTIDLAG   
      AONRTIDLAGE.ANVANDARE1 = globanv
      AONRTIDLAGE.ANVANDARE2 = "AUTOMATISKT"
      AONRTIDLAGE.AONR = AONRTAB.AONR  
      AONRTIDLAGE.DELNR = AONRTAB.DELNR  
      AONRTIDLAGE.DATUM1 = TODAY.         
   END.
END.
ELSE IF tlagevar = "BERTID" THEN DO:
   FIND AONRTAB WHERE RECID(AONRTAB) = aonrrec NO-LOCK NO-ERROR.
   DO TRANSACTION:
      FIND FIRST TIDSLAGEN WHERE TIDSLAGEN.IDTIDLAG = tlagevar NO-LOCK NO-ERROR.
      IF NOT AVAILABLE TIDSLAGEN THEN DO:
         CREATE TIDSLAGEN.
         ASSIGN
         TIDSLAGEN.AKTIVITET1 = "Ja"
         TIDSLAGEN.IDTIDLAG = "BERTID" 
         TIDSLAGEN.TIDLAGE = "BEREDARTID STARTAD".         
      END.
      FIND FIRST AONRTIDLAGE WHERE 
      AONRTIDLAGE.AONR = AONRTAB.AONR AND 
      AONRTIDLAGE.DELNR = AONRTAB.DELNR AND
      AONRTIDLAGE.IDTIDLAG = TIDSLAGEN.IDTIDLAG
      EXCLUSIVE-LOCK NO-ERROR.
      IF AVAILABLE AONRTIDLAGE THEN DO:
         RETURN.
      END.
      ELSE DO:
         CREATE AONRTIDLAGE.
      END.
      ASSIGN
      AONRTIDLAGE.IDTIDLAG = TIDSLAGEN.IDTIDLAG   
      AONRTIDLAGE.ANVANDARE1 = globanv
      AONRTIDLAGE.ANVANDARE2 = "AUTOMATISKT"
      AONRTIDLAGE.AONR = AONRTAB.AONR  
      AONRTIDLAGE.DELNR = AONRTAB.DELNR  
      AONRTIDLAGE.DATUM1 = TODAY.         
   END.
END.
ELSE IF tlagevar = "MBESTÄLLT" THEN DO:
   FIND AONRTAB WHERE RECID(AONRTAB) = aonrrec NO-LOCK NO-ERROR.
   DO TRANSACTION:
      FIND FIRST TIDSLAGEN WHERE TIDSLAGEN.IDTIDLAG = tlagevar NO-LOCK NO-ERROR.
      IF NOT AVAILABLE TIDSLAGEN THEN DO:
         CREATE TIDSLAGEN.
         ASSIGN
         TIDSLAGEN.AKTIVITET1 = "Ja"
         TIDSLAGEN.IDTIDLAG = "MBESTÄLLT" 
         TIDSLAGEN.TIDLAGE = "BEST.MATERIEL".
      END.
      FIND FIRST AONRTIDLAGE WHERE 
      AONRTIDLAGE.AONR = AONRTAB.AONR AND 
      AONRTIDLAGE.DELNR = AONRTAB.DELNR AND
      AONRTIDLAGE.IDTIDLAG = TIDSLAGEN.IDTIDLAG
      EXCLUSIVE-LOCK NO-ERROR.
      IF AVAILABLE AONRTIDLAGE THEN DO:
         IF AONRTIDLAGE.DATUM1 = ? THEN aonrrec = aonrrec.
         ELSE RETURN.
      END.
      ELSE DO:
         CREATE AONRTIDLAGE.
      END.
      ASSIGN
      AONRTIDLAGE.IDTIDLAG = TIDSLAGEN.IDTIDLAG   
      AONRTIDLAGE.ANVANDARE1 = globanv
      AONRTIDLAGE.ANVANDARE2 = "AUTOMATISKT"
      AONRTIDLAGE.AONR = AONRTAB.AONR  
      AONRTIDLAGE.DELNR = AONRTAB.DELNR  
      AONRTIDLAGE.DATUM1 = TODAY.         
   END.
END.
ELSE IF tlagevar = "Materiel" THEN DO:
   FIND AONRTAB WHERE RECID(AONRTAB) = aonrrec NO-LOCK NO-ERROR.
   DO TRANSACTION:
      FIND FIRST TIDSLAGEN WHERE TIDSLAGEN.IDTIDLAG = tlagevar NO-LOCK NO-ERROR.
      IF NOT AVAILABLE TIDSLAGEN THEN DO:
         CREATE TIDSLAGEN.
         ASSIGN
         TIDSLAGEN.AKTIVITET1 = "Beställt"
         TIDSLAGEN.IDTIDLAG = "Materiel" 
         TIDSLAGEN.TIDLAGE = "Materiel".
      END.
      FIND FIRST AONRTIDLAGE WHERE 
      AONRTIDLAGE.AONR = AONRTAB.AONR AND 
      AONRTIDLAGE.DELNR = AONRTAB.DELNR AND
      AONRTIDLAGE.IDTIDLAG = TIDSLAGEN.IDTIDLAG
      EXCLUSIVE-LOCK NO-ERROR.
      IF AVAILABLE AONRTIDLAGE THEN DO:
         IF AONRTIDLAGE.DATUM1 = ? THEN aonrrec = aonrrec.
         ELSE RETURN.
      END.
      ELSE DO:
         CREATE AONRTIDLAGE.
      END.
      ASSIGN
      AONRTIDLAGE.IDTIDLAG = TIDSLAGEN.IDTIDLAG   
      AONRTIDLAGE.ANVANDARE1 = globanv + " AUTOMATISKT"      
      AONRTIDLAGE.AONR = AONRTAB.AONR  
      AONRTIDLAGE.DELNR = AONRTAB.DELNR  
      AONRTIDLAGE.DATUM1 = TODAY.         
   END.
END.
ELSE IF tlagevar = "Materiel Avrop" THEN DO:
   FIND AONRTAB WHERE RECID(AONRTAB) = aonrrec NO-LOCK NO-ERROR.
   DO TRANSACTION:
      FIND FIRST TIDSLAGEN WHERE TIDSLAGEN.IDTIDLAG = tlagevar NO-LOCK NO-ERROR.
      IF NOT AVAILABLE TIDSLAGEN THEN DO:
         CREATE TIDSLAGEN.
         ASSIGN
         TIDSLAGEN.AKTIVITET1 = "Beställt"
         TIDSLAGEN.IDTIDLAG = "Materiel avrop" 
         TIDSLAGEN.TIDLAGE = "Materiel avrop".
      END.
      FIND FIRST AONRTIDLAGE WHERE 
      AONRTIDLAGE.AONR = AONRTAB.AONR AND 
      AONRTIDLAGE.DELNR = AONRTAB.DELNR AND
      AONRTIDLAGE.IDTIDLAG = TIDSLAGEN.IDTIDLAG
      EXCLUSIVE-LOCK NO-ERROR.
      IF AVAILABLE AONRTIDLAGE THEN DO:
         IF AONRTIDLAGE.DATUM1 = ? THEN aonrrec = aonrrec.
         ELSE RETURN.
      END.
      ELSE DO:
         CREATE AONRTIDLAGE.
      END.
      ASSIGN
      AONRTIDLAGE.IDTIDLAG = TIDSLAGEN.IDTIDLAG   
      AONRTIDLAGE.ANVANDARE1 = globanv + " AUTOMATISKT"      
      AONRTIDLAGE.AONR = AONRTAB.AONR  
      AONRTIDLAGE.DELNR = AONRTAB.DELNR  
      AONRTIDLAGE.DATUM1 = TODAY.         
   END.
END.
ELSE IF tlagevar = "MALDATUM" THEN DO:
   FIND AONRTAB WHERE RECID(AONRTAB) = aonrrec NO-LOCK NO-ERROR.
   DO TRANSACTION:
      FIND FIRST TIDSLAGEN WHERE TIDSLAGEN.IDTIDLAG = tlagevar NO-LOCK NO-ERROR.
      IF NOT AVAILABLE TIDSLAGEN THEN DO:
         CREATE TIDSLAGEN.
         ASSIGN
         TIDSLAGEN.AKTIVITET1 = "Ja"
         TIDSLAGEN.IDTIDLAG = "MALDATUM" 
         TIDSLAGEN.TIDLAGE = "MÅLDATUM".
      END.
      FIND FIRST AONRTIDLAGE WHERE 
      AONRTIDLAGE.AONR = AONRTAB.AONR AND 
      AONRTIDLAGE.DELNR = AONRTAB.DELNR AND
      AONRTIDLAGE.IDTIDLAG = TIDSLAGEN.IDTIDLAG
      EXCLUSIVE-LOCK NO-ERROR.
      IF AVAILABLE AONRTIDLAGE THEN DO:
         IF AONRTIDLAGE.DATUM1 = ? THEN aonrrec = aonrrec.
         ELSE RETURN.
      END.
      ELSE DO:
         ASSIGN
         regvnr = AONRTAB.SLUTVNR
         regdagnamn = AONRTAB.SLUTDAG.  
         IF AONRTAB.SLUTVNR NE 0 THEN RUN VECODAT.P.  
         ELSE  regdatum = ?.
         CREATE AONRTIDLAGE.         
         ASSIGN 
         AONRTIDLAGE.IDTIDLAG = TIDSLAGEN.IDTIDLAG   
         AONRTIDLAGE.ANVANDARE1 = globanv
         AONRTIDLAGE.ANVANDARE2 = "AUTOMATISKT"
         AONRTIDLAGE.AONR = AONRTAB.AONR  
         AONRTIDLAGE.DELNR = AONRTAB.DELNR  
         AONRTIDLAGE.DATUM1 = regdatum.         
      END.
   END.
END.
ELSE IF tlagevar = "AOKONTO" THEN DO:
   FIND AONRTAB WHERE RECID(AONRTAB) = aonrrec NO-LOCK NO-ERROR.
   DO TRANSACTION:
      FIND FIRST TIDSLAGEN WHERE TIDSLAGEN.IDTIDLAG = tlagevar NO-LOCK NO-ERROR.
      IF NOT AVAILABLE TIDSLAGEN THEN DO:
         RETURN.         
      END.
      FIND FIRST AONRTIDLAGE WHERE 
      AONRTIDLAGE.AONR = AONRTAB.AONR AND 
      AONRTIDLAGE.DELNR = AONRTAB.DELNR AND
      AONRTIDLAGE.IDTIDLAG = TIDSLAGEN.IDTIDLAG
      EXCLUSIVE-LOCK NO-ERROR.
      IF AVAILABLE AONRTIDLAGE THEN DO:
         ASSIGN
         AONRTIDLAGE.ANVANDARE1 = globanv
         AONRTIDLAGE.ANVANDARE2 = "AUTOMATISKT"
         AONRTIDLAGE.DATUM1 = TODAY.
         RETURN.
      END.
      ELSE DO:
         CREATE AONRTIDLAGE.
      END.
      ASSIGN
      AONRTIDLAGE.IDTIDLAG = TIDSLAGEN.IDTIDLAG   
      AONRTIDLAGE.ANVANDARE1 = globanv
      AONRTIDLAGE.ANVANDARE2 = "AUTOMATISKT"
      AONRTIDLAGE.AONR = AONRTAB.AONR  
      AONRTIDLAGE.DELNR = AONRTAB.DELNR  
      AONRTIDLAGE.DATUM1 = TODAY.      
   END.
END.
ELSE IF tlagevar = "TIDSTOPP" THEN DO:
   DEBUGGER:SET-BREAK().
   FIND AONRTAB WHERE RECID(AONRTAB) = aonrrec NO-LOCK NO-ERROR.
   DO TRANSACTION:
      FIND FIRST TIDSLAGEN WHERE TIDSLAGEN.IDTIDLAG = tlagevar NO-LOCK NO-ERROR.
      IF NOT AVAILABLE TIDSLAGEN THEN DO:
         RETURN.         
      END.
      FIND FIRST AONRTIDLAGE WHERE 
      AONRTIDLAGE.AONR = AONRTAB.AONR AND 
      AONRTIDLAGE.DELNR = AONRTAB.DELNR AND
      AONRTIDLAGE.IDTIDLAG = TIDSLAGEN.IDTIDLAG
      EXCLUSIVE-LOCK NO-ERROR.
      IF AVAILABLE AONRTIDLAGE THEN DO:
         ASSIGN
         AONRTIDLAGE.ANVANDARE1 = globanv
         AONRTIDLAGE.ANVANDARE2 = "AUTOMATISKT"
         AONRTIDLAGE.DATUM1 = DATE(01,01,YEAR(TODAY)).                      
         RETURN.
      END.
      ELSE DO:
         CREATE AONRTIDLAGE.
      END.
      ASSIGN
      AONRTIDLAGE.IDTIDLAG = TIDSLAGEN.IDTIDLAG   
      AONRTIDLAGE.ANVANDARE1 = globanv
      AONRTIDLAGE.ANVANDARE2 = "AUTOMATISKT"
      AONRTIDLAGE.AONR = AONRTAB.AONR  
      AONRTIDLAGE.DELNR = AONRTAB.DELNR  
      AONRTIDLAGE.DATUM1 = DATE(01,01,YEAR(TODAY)).      
   END.
END.
ELSE IF tlagevar = "TIDPLAN" THEN DO:
   FIND AONRTAB WHERE RECID(AONRTAB) = aonrrec NO-LOCK NO-ERROR.
   DO TRANSACTION:
      FIND FIRST TIDSLAGEN WHERE TIDSLAGEN.IDTIDLAG = tlagevar NO-LOCK NO-ERROR.
      IF NOT AVAILABLE TIDSLAGEN THEN DO:
         CREATE TIDSLAGE.
         ASSIGN
         TIDSLAGEN.AKTIVITET1 = "Start"
         TIDSLAGEN.AKTIVITET1 = "Slut"
         TIDSLAGEN.IDTIDLAG = "TIDPLAN"
         TIDSLAGEN.TIDLAGE = "TIDPLAN".        
      END.
      FIND FIRST AONRTIDLAGE WHERE 
      AONRTIDLAGE.AONR = AONRTAB.AONR AND 
      AONRTIDLAGE.DELNR = AONRTAB.DELNR AND
      AONRTIDLAGE.IDTIDLAG = TIDSLAGEN.IDTIDLAG
      EXCLUSIVE-LOCK NO-ERROR.
      IF AVAILABLE AONRTIDLAGE THEN DO:
         ASSIGN
         AONRTIDLAGE.ANVANDARE1 = globanv
         AONRTIDLAGE.ANVANDARE2 = Guru.Konstanter:globanv.
         IF AONRTIDLAGE.DATUM1 = ? THEN AONRTIDLAGE.DATUM1 = TODAY.       
         IF AONRTIDLAGE.DATUM2 = ? THEN AONRTIDLAGE.DATUM2 = TODAY.  
         RETURN.
      END.
      ELSE DO:
         CREATE AONRTIDLAGE.
      END.
      ASSIGN
      AONRTIDLAGE.IDTIDLAG = TIDSLAGEN.IDTIDLAG   
      AONRTIDLAGE.ANVANDARE1 = globanv
      AONRTIDLAGE.ANVANDARE2 = globanv
      AONRTIDLAGE.AONR = AONRTAB.AONR  
      AONRTIDLAGE.DELNR = AONRTAB.DELNR  
      AONRTIDLAGE.DATUM1 = TODAY
      AONRTIDLAGE.DATUM2 = TODAY.      
   END.
END. 
ELSE IF tlagevar = "KMONT" THEN DO:
   RUN skaptidl_UI (INPUT tlagevar,INPUT "START",INPUT "SLUT",INPUT "MONTÖRSTID",INPUT TRUE). 
END.
ELSE IF tlagevar = "KBER" THEN DO:
   RUN skaptidl_UI (INPUT tlagevar,INPUT "START",INPUT "SLUT",INPUT "BEREDARTID",INPUT TRUE).
END.
ELSE IF tlagevar = "KMASK" THEN DO:
   RUN skaptidl_UI (INPUT tlagevar,INPUT "START",INPUT "SLUT",INPUT "MASKINTID",INPUT TRUE).  
END.

ELSE IF tlagevar = "UNDERPREPARATION" THEN DO:
   RUN skaptidl_UI (INPUT tlagevar,INPUT "JA",INPUT "",INPUT "Under beredning",INPUT FALSE).  
END.
ELSE IF tlagevar = "PREPARED" THEN DO:
   RUN skaptidl_UI (INPUT tlagevar,INPUT "JA",INPUT "",INPUT "Beredd",INPUT FALSE).  
END.
ELSE IF tlagevar = "RELEASED" THEN DO:
   RUN skaptidl_UI (INPUT tlagevar,INPUT "JA",INPUT "",INPUT "Frisläppt",INPUT FALSE).  
END.
ELSE IF tlagevar = "STARTED" THEN DO:
   RUN skaptidl_UI (INPUT tlagevar,INPUT "JA",INPUT "",INPUT "Startad",INPUT FALSE).  
END.
ELSE IF tlagevar = "WORKDONE" THEN DO:
   RUN skaptidl_UI (INPUT tlagevar,INPUT "JA",INPUT "",INPUT "Arbete utfört",INPUT FALSE).  
END.
ELSE IF tlagevar = "REPORTED" THEN DO:
   RUN skaptidl_UI (INPUT tlagevar,INPUT "JA",INPUT "",INPUT "Avrapporterad",INPUT FALSE).  
END.
ELSE IF tlagevar = "CANCELED" THEN DO:
   RUN skaptidl_UI (INPUT tlagevar,INPUT "JA",INPUT "",INPUT "Avbruten",INPUT FALSE).  
END.
ELSE IF tlagevar = "FINISHED" THEN DO:
   RUN skaptidl_UI (INPUT tlagevar,INPUT "JA",INPUT "",INPUT "Utförd",INPUT FALSE).  
END.
ELSE IF tlagevar = "FAULTREPORT" THEN DO:
   RUN skaptidl_UI (INPUT tlagevar,INPUT "JA",INPUT "",INPUT "Felanmälan",INPUT FALSE).  
END.
  
PROCEDURE skaptidl_UI :
   DEFINE INPUT PARAMETER idvar AS CHARACTER NO-UNDO.
   DEFINE INPUT PARAMETER a1 AS CHARACTER NO-UNDO.
   DEFINE INPUT PARAMETER a2 AS CHARACTER NO-UNDO.
   DEFINE INPUT PARAMETER benvar AS CHARACTER NO-UNDO.
   DEFINE INPUT  PARAMETER uppdat AS LOGICAL NO-UNDO.
   FIND AONRTAB WHERE RECID(AONRTAB) = aonrrec NO-LOCK NO-ERROR.
   DO TRANSACTION:
      FIND FIRST TIDSLAGEN WHERE TIDSLAGEN.IDTIDLAG = idvar NO-LOCK NO-ERROR.
      IF NOT AVAILABLE TIDSLAGEN THEN DO:
         CREATE TIDSLAGE.
         ASSIGN
         TIDSLAGEN.AKTIVITET1 = a1
         TIDSLAGEN.AKTIVITET2 = a2
         TIDSLAGEN.IDTIDLAG = idvar
         TIDSLAGEN.TIDLAGE = benvar.        
      END.
      FIND FIRST AONRTIDLAGE WHERE 
      AONRTIDLAGE.AONR = AONRTAB.AONR AND 
      AONRTIDLAGE.DELNR = AONRTAB.DELNR AND
      AONRTIDLAGE.IDTIDLAG = TIDSLAGEN.IDTIDLAG
      EXCLUSIVE-LOCK NO-ERROR.
      IF AVAILABLE AONRTIDLAGE THEN DO:
         IF uppdat = TRUE THEN RETURN.
         ASSIGN
         AONRTIDLAGE.ANVANDARE1 = globanv
         AONRTIDLAGE.ANVANDARE2 = Guru.Konstanter:globanv.
         IF AONRTIDLAGE.DATUM1 = ? THEN AONRTIDLAGE.DATUM1 = TODAY.  
         IF AONRTIDLAGE.DATUM2 = ? THEN DO:
            IF TIDSLAGEN.AKTIVITET2 NE "" THEN AONRTIDLAGE.DATUM2 = TODAY.
         END.   
         RETURN.
      END.
      ELSE DO:
         CREATE AONRTIDLAGE.
      END.
      ASSIGN
      AONRTIDLAGE.IDTIDLAG = TIDSLAGEN.IDTIDLAG   
      AONRTIDLAGE.ANVANDARE1 = globanv
      AONRTIDLAGE.ANVANDARE2 = globanv
      AONRTIDLAGE.AONR = AONRTAB.AONR  
      AONRTIDLAGE.DELNR = AONRTAB.DELNR  
      AONRTIDLAGE.DATUM1 = TODAY.
      IF TIDSLAGEN.AKTIVITET2 NE "" THEN AONRTIDLAGE.DATUM2 = TODAY.           
   END.
END PROCEDURE.
