/*ATERSUM.P SUMMERING AV STÖRNING*/
DEFINE TEMP-TABLE avd_temp
   FIELD AVDELNINGNR LIKE STORDISTRIKT.AVDELNINGNR   
   FIELD NAMN LIKE STORDISTRIKT.NAMN
   INDEX AVD IS PRIMARY AVDELNINGNR.

DEFINE TEMP-TABLE stor_temp
   FIELD AVDELNING LIKE AVDELNING.AVDELNINGNAMN
   FIELD DISTRIKT LIKE STORDISTRIKT.NAMN
   FIELD STORNUMMERID AS INTEGER
   FIELD HDATUM LIKE STORNINGSTAB.HDATUM
   FIELD HKLOCKAN LIKE STORNINGSTAB.HKLOCKAN
   FIELD ANVANDARE LIKE STORNINGSTAB.ANVANDARE
   FIELD ANSVARIGPERS LIKE STORNINGSTAB.ANSVARIGPERS
   FIELD TYP AS CHARACTER
   INDEX DATUM HDATUM HKLOCKAN ASCENDING.

DEFINE INPUT PARAMETER TABLE FOR avd_temp.
DEFINE INPUT PARAMETER valfore AS LOGICAL NO-UNDO.
DEFINE INPUT PARAMETER distvar LIKE STORDISTRIKT.DISTRIKTID NO-UNDO.   
DEFINE INPUT PARAMETER bdatum AS DATE NO-UNDO.
DEFINE INPUT PARAMETER avdatum AS DATE NO-UNDO.
DEFINE INPUT PARAMETER period AS INTEGER NO-UNDO.
DEFINE INPUT PARAMETER uttyp AS INTEGER NO-UNDO.
DEFINE INPUT PARAMETER vallista AS INTEGER NO-UNDO.
DEFINE INPUT PARAMETER alla AS LOGICAL NO-UNDO.
DEFINE OUTPUT PARAMETER TABLE FOR stor_temp.


   {muswait.i}   
   IF valfore = TRUE THEN DO:
      FOR EACH avd_temp USE-INDEX AVD:
         OPEN QUERY dq FOR EACH STORDISTRIKT WHERE 
         STORDISTRIKT.AVDELNINGNR = avd_temp.AVDELNINGNR AND 
         STORDISTRIKT.ARTAL = YEAR(bdatum) USE-INDEX AVDARTAL NO-LOCK.
         GET FIRST dq NO-LOCK.
         DO WHILE AVAILABLE(STORDISTRIKT):
            distvar = STORDISTRIKT.DISTRIKTID.
            RUN distrikt_UI.
            GET NEXT dq NO-LOCK.
         END.
         CLOSE QUERY dq.
      END.         
   END.
   ELSE DO:
      IF alla = TRUE THEN DO:
         IF uttyp = 3 THEN DO:
            IF period = 1 THEN DO:
               OPEN QUERY sq FOR EACH STORNINGSTAB WHERE YEAR(STORNINGSTAB.HDATUM) = YEAR(bdatum) AND
               STORNINGSTAB.MERJOBB = TRUE USE-INDEX DATUM NO-LOCK.
            END.
            ELSE DO:
               OPEN QUERY sq FOR EACH STORNINGSTAB WHERE STORNINGSTAB.HDATUM >= bdatum AND
               STORNINGSTAB.HDATUM <= avdatum AND
               STORNINGSTAB.MERJOBB = TRUE USE-INDEX DATUM NO-LOCK.
            END.
         END.
         ELSE DO:
            IF period = 1 THEN DO:
               OPEN QUERY sq FOR EACH STORNINGSTAB WHERE YEAR(STORNINGSTAB.HDATUM) = YEAR(bdatum) AND 
               STORNINGSTAB.STORTYPID = uttyp AND
               STORNINGSTAB.MERJOBB = TRUE USE-INDEX DATUM NO-LOCK.
            END.
            ELSE DO:
               OPEN QUERY sq FOR EACH STORNINGSTAB WHERE STORNINGSTAB.HDATUM >= bdatum AND
               STORNINGSTAB.HDATUM <= avdatum AND 
               STORNINGSTAB.STORTYPID = uttyp AND
               STORNINGSTAB.MERJOBB = TRUE USE-INDEX DATUM NO-LOCK.
            END.
         END.      
         GET FIRST sq NO-LOCK.
         DO WHILE AVAILABLE(STORNINGSTAB):
            RUN summa_UI.                     
            GET NEXT sq NO-LOCK.
         END.
         CLOSE QUERY sq.         
      END.
      ELSE DO:
         RUN distrikt_UI.         
      END.
   END.

PROCEDURE distrikt_UI:
   IF uttyp = 3 THEN DO:
      IF period = 1 THEN DO:
         OPEN QUERY sq FOR EACH STORNINGSTAB WHERE STORNINGSTAB.DISTRIKTID = distvar AND
         YEAR(STORNINGSTAB.HDATUM) = YEAR(bdatum) AND
         STORNINGSTAB.MERJOBB = TRUE USE-INDEX DATUM NO-LOCK.
      END.
      ELSE DO:
         OPEN QUERY sq FOR EACH STORNINGSTAB WHERE STORNINGSTAB.DISTRIKTID = distvar AND
         STORNINGSTAB.HDATUM >= bdatum AND
         STORNINGSTAB.HDATUM <= avdatum AND
         STORNINGSTAB.MERJOBB = TRUE USE-INDEX DATUM NO-LOCK.
      END.
   END.
   ELSE DO:
      IF period = 1 THEN DO:
         OPEN QUERY sq FOR EACH STORNINGSTAB WHERE STORNINGSTAB.DISTRIKTID = distvar AND
         YEAR(STORNINGSTAB.HDATUM) = YEAR(bdatum) AND STORNINGSTAB.STORTYPID = uttyp AND
         STORNINGSTAB.MERJOBB = TRUE USE-INDEX DATUM NO-LOCK.
      END.
      ELSE DO:
         OPEN QUERY sq FOR EACH STORNINGSTAB WHERE STORNINGSTAB.DISTRIKTID = distvar AND
         STORNINGSTAB.HDATUM >= bdatum AND
         STORNINGSTAB.HDATUM <= avdatum AND STORNINGSTAB.STORTYPID = uttyp AND
         STORNINGSTAB.MERJOBB = TRUE USE-INDEX DATUM NO-LOCK.
      END.
   END.     
   GET FIRST sq NO-LOCK.
   DO WHILE AVAILABLE(STORNINGSTAB):                
      RUN summa_UI.
      GET NEXT sq NO-LOCK.
   END.
   CLOSE QUERY sq.    
END PROCEDURE.

PROCEDURE summa_UI:
   CREATE stor_temp.
   FIND FIRST STORDISTRIKT WHERE STORDISTRIKT.DISTRIKTID = STORNINGSTAB.DISTRIKTID
   NO-LOCK NO-ERROR.
   IF AVAILABLE STORDISTRIKT THEN DO:
      stor_temp.DISTRIKT = STORDISTRIKT.NAMN.
      FIND FIRST AVDELNING WHERE AVDELNING.AVDELNINGNR = STORDISTRIKT.AVDELNINGNR
      NO-LOCK NO-ERROR.
      IF AVAILABLE AVDELNING THEN DO:
         stor_temp.AVDELNING = AVDELNING.AVDELNINGNAMN.
      END.
      ELSE DO:
         stor_temp.AVDELNING = "Okänt".
      END.
   END.   
   ELSE DO:
      ASSIGN
      stor_temp.DISTRIKT = "Okänt"
      stor_temp.AVDELNING = "Okänt".
   END.
   IF STORNINGSTAB.STORTYPID = 1 THEN stor_temp.TYP = "Drift".
   ELSE stor_temp.TYP = "Plan".
   ASSIGN
   stor_temp.STORNUMMERID = STORNINGSTAB.STORNUMMERID
   stor_temp.HDATUM = STORNINGSTAB.HDATUM
   stor_temp.HKLOCKAN = STORNINGSTAB.HKLOCKAN
   stor_temp.ANVANDARE = STORNINGSTAB.ANVANDARE
   stor_temp.ANSVARIGPERS = STORNINGSTAB.ANSVARIGPERS.
END PROCEDURE.
