/*DELIMP.P*/
DEFINE INPUT PARAMETER forvar AS INTEGER NO-UNDO.
DEFINE INPUT PARAMETER distvar AS CHARACTER NO-UNDO.
DEFINE INPUT PARAMETER franar AS INTEGER NO-UNDO.

FIND FIRST STORDISTRIKT WHERE STORDISTRIKT.AVDELNINGNR = forvar
AND STORDISTRIKT.VIDISTRIKT = distvar AND STORDISTRIKT.ARTAL = franar NO-LOCK NO-ERROR.
IF AVAILABLE STORDISTRIKT THEN DO:
   OPEN QUERY dq FOR EACH STORNINGSTAB WHERE STORNINGSTAB.DISTRIKTID = STORDISTRIKT.DISTRIKTID
   NO-LOCK.
   GET FIRST dq EXCLUSIVE-LOCK.
   DO WHILE AVAILABLE(STORNINGSTAB):
      OPEN QUERY bq FOR EACH BORTKOPPLAD WHERE BORTKOPPLAD.STORNUMMERID = 
      STORNINGSTAB.STORNUMMERID USE-INDEX STORNUMMERID NO-LOCK.
      GET FIRST bq EXCLUSIVE-LOCK.
      DO WHILE AVAILABLE(BORTKOPPLAD):
         DELETE BORTKOPPLAD.
         GET NEXT bq EXCLUSIVE-LOCK.
      END.
      CLOSE QUERY bq. 
      DELETE STORNINGSTAB.
      GET NEXT dq EXCLUSIVE-LOCK.
   END.
   CLOSE QUERY dq.
END.
