/*DELUPPLAGG.p*/
OPEN QUERY DQ FOR EACH ANLAGGNINGSDEL NO-LOCK.
DO  TRANSACTION:
   GET FIRST DQ EXCLUSIVE-LOCK.
   IF AVAILABLE ANLAGGNINGSDEL THEN DELETE ANLAGGNINGSDEL.
END.
REPEAT:
   DO TRANSACTION:
      GET NEXT DQ EXCLUSIVE-LOCK.
      IF AVAILABLE ANLAGGNINGSDEL THEN DELETE ANLAGGNINGSDEL.
      ELSE LEAVE.
   END.
END.
CLOSE QUERY DQ.

OPEN QUERY DQ1 FOR EACH ANLAGGNINGSTYP NO-LOCK.
DO  TRANSACTION:
   GET FIRST DQ1 EXCLUSIVE-LOCK.
   IF AVAILABLE ANLAGGNINGSTYP THEN DELETE ANLAGGNINGSTYP.
END.
REPEAT:
   DO TRANSACTION:
      GET NEXT DQ1 EXCLUSIVE-LOCK.
      IF AVAILABLE ANLAGGNINGSTYP THEN DELETE ANLAGGNINGSTYP.
      ELSE LEAVE.
   END.
END.
CLOSE QUERY DQ1.

OPEN QUERY DQ2 FOR EACH BRYTORGAN NO-LOCK.
DO  TRANSACTION:
   GET FIRST DQ2 EXCLUSIVE-LOCK.
   IF AVAILABLE BRYTORGAN THEN DELETE BRYTORGAN.
END.
REPEAT:
   DO TRANSACTION:
      GET NEXT DQ2 EXCLUSIVE-LOCK.
      IF AVAILABLE BRYTORGAN THEN DELETE BRYTORGAN.
      ELSE LEAVE.
   END.
END.
CLOSE QUERY DQ2.

OPEN QUERY DQ3 FOR EACH FELORSAK NO-LOCK.
DO  TRANSACTION:
   GET FIRST DQ3 EXCLUSIVE-LOCK.
   IF AVAILABLE FELORSAK THEN DELETE FELORSAK.
END.
REPEAT:
   DO TRANSACTION:
      GET NEXT DQ3 EXCLUSIVE-LOCK.
      IF AVAILABLE FELORSAK THEN DELETE FELORSAK.
      ELSE LEAVE.
   END.
END.
CLOSE QUERY DQ3.

OPEN QUERY DQ4 FOR EACH FELYTTRING NO-LOCK.
DO  TRANSACTION:
   GET FIRST DQ4 EXCLUSIVE-LOCK.
   IF AVAILABLE FELYTTRING THEN DELETE FELYTTRING.
END.
REPEAT:
   DO TRANSACTION:
      GET NEXT DQ4 EXCLUSIVE-LOCK.
      IF AVAILABLE FELYTTRING THEN DELETE FELYTTRING.
      ELSE LEAVE.
   END.
END.
CLOSE QUERY DQ4.

OPEN QUERY DQ5 FOR EACH GRUNDFELTYP NO-LOCK.
DO  TRANSACTION:
   GET FIRST DQ5 EXCLUSIVE-LOCK.
   IF AVAILABLE GRUNDFELTYP THEN DELETE GRUNDFELTYP.
END.
REPEAT:
   DO TRANSACTION:
      GET NEXT DQ5 EXCLUSIVE-LOCK.
      IF AVAILABLE GRUNDFELTYP THEN DELETE GRUNDFELTYP.
      ELSE LEAVE.
   END.
END.
CLOSE QUERY DQ5.

OPEN QUERY DQ6 FOR EACH GRUNDNATSTOR NO-LOCK.
DO  TRANSACTION:
   GET FIRST DQ6 EXCLUSIVE-LOCK.
   IF AVAILABLE GRUNDNATSTOR THEN DELETE GRUNDNATSTOR.
END.
REPEAT:
   DO TRANSACTION:
      GET NEXT DQ6 EXCLUSIVE-LOCK.
      IF AVAILABLE GRUNDNATSTOR THEN DELETE GRUNDNATSTOR.
      ELSE LEAVE.
   END.
END.
CLOSE QUERY DQ6.

OPEN QUERY DQ7 FOR EACH INLASTAB NO-LOCK.
DO  TRANSACTION:
   GET FIRST DQ7 EXCLUSIVE-LOCK.
   IF AVAILABLE INLASTAB THEN DELETE INLASTAB.
END.
REPEAT:
   DO TRANSACTION:
      GET NEXT DQ7 EXCLUSIVE-LOCK.
      IF AVAILABLE INLASTAB THEN DELETE INLASTAB.
      ELSE LEAVE.
   END.
END.
CLOSE QUERY DQ7.

OPEN QUERY DQ8 FOR EACH NATSTOR NO-LOCK.
DO  TRANSACTION:
   GET FIRST DQ8 EXCLUSIVE-LOCK.
   IF AVAILABLE NATSTOR THEN DELETE NATSTOR.
END.
REPEAT:
   DO TRANSACTION:
      GET NEXT DQ8 EXCLUSIVE-LOCK.
      IF AVAILABLE NATSTOR THEN DELETE NATSTOR.
      ELSE LEAVE.
   END.
END.
CLOSE QUERY DQ8.

OPEN QUERY DQ9 FOR EACH NATSTRUKTUR NO-LOCK.
DO  TRANSACTION:
   GET FIRST DQ9 EXCLUSIVE-LOCK.
   IF AVAILABLE NATSTRUKTUR THEN DELETE NATSTRUKTUR.
END.
REPEAT:
   DO TRANSACTION:
      GET NEXT DQ9 EXCLUSIVE-LOCK.
      IF AVAILABLE NATSTRUKTUR THEN DELETE NATSTRUKTUR.
      ELSE LEAVE.
   END.
END.
CLOSE QUERY DQ9.

OPEN QUERY DQ10 FOR EACH NATTYP NO-LOCK.
DO  TRANSACTION:
   GET FIRST DQ10 EXCLUSIVE-LOCK.
   IF AVAILABLE NATTYP THEN DELETE NATTYP.
END.
REPEAT:
   DO TRANSACTION:
      GET NEXT DQ10 EXCLUSIVE-LOCK.
      IF AVAILABLE NATTYP THEN DELETE NATTYP.
      ELSE LEAVE.
   END.
END.
CLOSE QUERY DQ10.

OPEN QUERY DQ11 FOR EACH NATUPPKOPP NO-LOCK.
DO  TRANSACTION:
   GET FIRST DQ11 EXCLUSIVE-LOCK.
   IF AVAILABLE NATUPPKOPP THEN DELETE NATUPPKOPP.
END.
REPEAT:
   DO TRANSACTION:
      GET NEXT DQ11 EXCLUSIVE-LOCK.
      IF AVAILABLE NATUPPKOPP THEN DELETE NATUPPKOPP.
      ELSE LEAVE.
   END.
END.
CLOSE QUERY DQ11.

OPEN QUERY DQ12 FOR EACH NATUPPLAGG1 NO-LOCK.
DO  TRANSACTION:
   GET FIRST DQ12 EXCLUSIVE-LOCK.
   IF AVAILABLE NATUPPLAGG1 THEN DELETE NATUPPLAGG1.
END.
REPEAT:
   DO TRANSACTION:
      GET NEXT DQ12 EXCLUSIVE-LOCK.
      IF AVAILABLE NATUPPLAGG1 THEN DELETE NATUPPLAGG1.
      ELSE LEAVE.
   END.
END.
CLOSE QUERY DQ12.

OPEN QUERY DQ13 FOR EACH NATUPPLAGG2 NO-LOCK.
DO  TRANSACTION:
   GET FIRST DQ13 EXCLUSIVE-LOCK.
   IF AVAILABLE NATUPPLAGG2 THEN DELETE NATUPPLAGG2.
END.
REPEAT:
   DO TRANSACTION:
      GET NEXT DQ13 EXCLUSIVE-LOCK.
      IF AVAILABLE NATUPPLAGG2 THEN DELETE NATUPPLAGG2.
      ELSE LEAVE.
   END.
END.
CLOSE QUERY DQ13.

OPEN QUERY DQ14 FOR EACH NATUPPLAGG3 NO-LOCK.
DO  TRANSACTION:
   GET FIRST DQ14 EXCLUSIVE-LOCK.
   IF AVAILABLE NATUPPLAGG3 THEN DELETE NATUPPLAGG3.
END.
REPEAT:
   DO TRANSACTION:
      GET NEXT DQ14 EXCLUSIVE-LOCK.
      IF AVAILABLE NATUPPLAGG3 THEN DELETE NATUPPLAGG3.
      ELSE LEAVE.
   END.
END.
CLOSE QUERY DQ14.

OPEN QUERY DQ15 FOR EACH NATUPPLAGG4 NO-LOCK.
DO  TRANSACTION:
   GET FIRST DQ15 EXCLUSIVE-LOCK.
   IF AVAILABLE NATUPPLAGG4 THEN DELETE NATUPPLAGG4.
END.
REPEAT:
   DO TRANSACTION:
      GET NEXT DQ15 EXCLUSIVE-LOCK.
      IF AVAILABLE NATUPPLAGG4 THEN DELETE NATUPPLAGG4.
      ELSE LEAVE.
   END.
END.
CLOSE QUERY DQ15.

OPEN QUERY DQ16 FOR EACH RELAINDIKERING NO-LOCK.
DO  TRANSACTION:
   GET FIRST DQ16 EXCLUSIVE-LOCK.
   IF AVAILABLE RELAINDIKERING THEN DELETE RELAINDIKERING.
END.
REPEAT:
   DO TRANSACTION:
      GET NEXT DQ16 EXCLUSIVE-LOCK.
      IF AVAILABLE RELAINDIKERING THEN DELETE RELAINDIKERING.
      ELSE LEAVE.
   END.
END.
CLOSE QUERY DQ16.

OPEN QUERY DQ17 FOR EACH RESERVKRAFTMETOD NO-LOCK.
DO  TRANSACTION:
   GET FIRST DQ17 EXCLUSIVE-LOCK.
   IF AVAILABLE RESERVKRAFTMETOD THEN DELETE RESERVKRAFTMETOD.
END.
REPEAT:
   DO TRANSACTION:
      GET NEXT DQ17 EXCLUSIVE-LOCK.
      IF AVAILABLE RESERVKRAFTMETOD THEN DELETE RESERVKRAFTMETOD.
      ELSE LEAVE.
   END.
END.
CLOSE QUERY DQ17.

OPEN QUERY DQ18 FOR EACH SAKRINGSTYP NO-LOCK.
DO  TRANSACTION:
   GET FIRST DQ18 EXCLUSIVE-LOCK.
   IF AVAILABLE SAKRINGSTYP THEN DELETE SAKRINGSTYP.
END.
REPEAT:
   DO TRANSACTION:
      GET NEXT DQ18 EXCLUSIVE-LOCK.
      IF AVAILABLE SAKRINGSTYP THEN DELETE SAKRINGSTYP.
      ELSE LEAVE.
   END.
END.
CLOSE QUERY DQ18.

OPEN QUERY DQ19 FOR EACH SEKTIONERING NO-LOCK.
DO  TRANSACTION:
   GET FIRST DQ19 EXCLUSIVE-LOCK.
   IF AVAILABLE SEKTIONERING THEN DELETE SEKTIONERING.
END.
REPEAT:
   DO TRANSACTION:
      GET NEXT DQ19 EXCLUSIVE-LOCK.
      IF AVAILABLE SEKTIONERING THEN DELETE SEKTIONERING.
      ELSE LEAVE.
   END.
END.
CLOSE QUERY DQ19.

OPEN QUERY DQ20 FOR EACH SPANNINGSNIV NO-LOCK.
DO  TRANSACTION:
   GET FIRST DQ20 EXCLUSIVE-LOCK.
   IF AVAILABLE SPANNINGSNIV THEN DELETE SPANNINGSNIV.
END.
REPEAT:
   DO TRANSACTION:
      GET NEXT DQ20 EXCLUSIVE-LOCK.
      IF AVAILABLE SPANNINGSNIV THEN DELETE SPANNINGSNIV.
      ELSE LEAVE.
   END.
END.
CLOSE QUERY DQ20.

OPEN QUERY DQ21 FOR EACH STORDRIFTOMR NO-LOCK.
DO  TRANSACTION:
   GET FIRST DQ21 EXCLUSIVE-LOCK.
   IF AVAILABLE STORDRIFTOMR THEN DELETE STORDRIFTOMR.
END.
REPEAT:
   DO TRANSACTION:
      GET NEXT DQ21 EXCLUSIVE-LOCK.
      IF AVAILABLE STORDRIFTOMR THEN DELETE STORDRIFTOMR.
      ELSE LEAVE.
   END.
END.
CLOSE QUERY DQ21.

OPEN QUERY DQ22 FOR EACH STORNINGSTYP NO-LOCK.
DO  TRANSACTION:
   GET FIRST DQ22 EXCLUSIVE-LOCK.
   IF AVAILABLE STORNINGSTYP THEN DELETE STORNINGSTYP.
END.
REPEAT:
   DO TRANSACTION:
      GET NEXT DQ22 EXCLUSIVE-LOCK.
      IF AVAILABLE STORNINGSTYP THEN DELETE STORNINGSTYP.
      ELSE LEAVE.
   END.
END.
CLOSE QUERY DQ22.

OPEN QUERY DQ23 FOR EACH UTLOSNINGSKYDD NO-LOCK.
DO  TRANSACTION:
   GET FIRST DQ23 EXCLUSIVE-LOCK.
   IF AVAILABLE UTLOSNINGSKYDD THEN DELETE UTLOSNINGSKYDD.
END.
REPEAT:
   DO TRANSACTION:
      GET NEXT DQ23 EXCLUSIVE-LOCK.
      IF AVAILABLE UTLOSNINGSKYDD THEN DELETE UTLOSNINGSKYDD.
      ELSE LEAVE.
   END.
END.
CLOSE QUERY DQ23.
