/*  EXPKUND.p EXPORT AV KUNDDATA*/       
DEFINE TEMP-TABLE val_temp
   FIELD AVDELNINGNR LIKE STORDISTRIKT.AVDELNINGNR
   FIELD DISTRIKTID LIKE STORDISTRIKT.DISTRIKTID
   FIELD VIDISTRIKT LIKE STORDISTRIKT.VIDISTRIKT
   FIELD ARTAL LIKE STORDISTRIKT.ARTAL
   FIELD NAMN LIKE STORDISTRIKT.NAMN.

DEFINE TEMP-TABLE dumpa_temp
   FIELD AVDELNINGNR LIKE AVDELNING.AVDELNINGNR
   FIELD VIDISTRIKT LIKE STORDISTRIKT.VIDISTRIKT
   FIELD ARTAL LIKE STORDISTRIKT.ARTAL
   FIELD SPANID AS CHARACTER FORMAT "X(2)"
   FIELD ANTALLUFT LIKE KUNDSTOR.ANTALLUFT
   FIELD ANTALBLAND LIKE KUNDSTOR.ANTALBLAND
   FIELD ANTALKABEL LIKE KUNDSTOR.ANTALKABEL
   FIELD ANTALKUNDER LIKE KUNDSTOR.ANTALKUNDER
   INDEX ORD AVDELNINGNR VIDISTRIKT SPANID ASCENDING.

DEFINE INPUT PARAMETER TABLE FOR val_temp.
DEFINE OUTPUT PARAMETER TABLE FOR dumpa_temp.

FOR EACH val_temp:
   OPEN QUERY sq FOR EACH KUNDSTOR WHERE KUNDSTOR.DISTRIKTID = val_temp.DISTRIKTID AND
   KUNDSTOR.ARTAL = val_temp.ARTAL NO-LOCK.
   GET FIRST sq NO-LOCK.
   DO WHILE AVAILABLE(KUNDSTOR):
      FIND FIRST SPANNINGSNIV WHERE SPANNINGSNIV.SPANID = 
      KUNDSTOR.SPANID USE-INDEX SPANID NO-LOCK NO-ERROR.
      FIND FIRST INLASTAB WHERE INLASTAB.INKODID = SPANNINGSNIV.INKODID
      USE-INDEX INKODID NO-LOCK NO-ERROR.
      CREATE dumpa_temp.
      ASSIGN   
      dumpa_temp.AVDELNINGNR = val_temp.AVDELNINGNR
      dumpa_temp.VIDISTRIKT = val_temp.VIDISTRIKT
      dumpa_temp.ARTAL = val_temp.ARTAL
      dumpa_temp.SPANID = INLASTAB.INKODPOSCH
      dumpa_temp.ANTALKUNDER = KUNDSTOR.ANTALKUNDER
      dumpa_temp.ANTALBLAND = KUNDSTOR.ANTALBLAND
      dumpa_temp.ANTALLUFT = KUNDSTOR.ANTALLUFT
      dumpa_temp.ANTALKABEL = KUNDSTOR.ANTALKABEL.
      
      GET NEXT sq NO-LOCK.
   END.
   CLOSE QUERY sq.
END.

                
