/*EXPLEDN.P EXPORT AV LEDNINGSDATA*/       
DEFINE TEMP-TABLE val_temp
   FIELD AVDELNINGNR LIKE STORDISTRIKT.AVDELNINGNR
   FIELD DISTRIKTID LIKE STORDISTRIKT.DISTRIKTID
   FIELD VIDISTRIKT LIKE STORDISTRIKT.VIDISTRIKT
   FIELD ARTAL LIKE STORDISTRIKT.ARTAL
   FIELD NAMN LIKE STORDISTRIKT.NAMN.

DEFINE TEMP-TABLE dumpa_temp3
   FIELD AVDELNINGNR LIKE AVDELNING.AVDELNINGNR
   FIELD VIDISTRIKT LIKE STORDISTRIKT.VIDISTRIKT
   FIELD ARTAL LIKE STORDISTRIKT.ARTAL
   FIELD SPANID AS CHARACTER FORMAT "X(2)"
   FIELD LANGDLUFT LIKE LEDNINGSDATA.LANGDLUFT
   FIELD LANGDBLAND LIKE LEDNINGSDATA.LANGDBLAND
   FIELD LANGDKABEL LIKE LEDNINGSDATA.LANGDKABEL
   FIELD LANGD LIKE LEDNINGSDATA.LANGD
   FIELD TEXT1 AS CHARACTER
   FIELD TEXT2 AS CHARACTER
   INDEX ORD AVDELNINGNR VIDISTRIKT SPANID ASCENDING.

DEFINE VARIABLE langdvar AS LOGICAL NO-UNDO.

DEFINE INPUT PARAMETER TABLE FOR val_temp.
DEFINE OUTPUT PARAMETER TABLE FOR dumpa_temp3.

FOR EACH val_temp:
   OPEN QUERY sq FOR EACH LEDNINGSDATA WHERE LEDNINGSDATA.DISTRIKTID = val_temp.DISTRIKTID AND
   LEDNINGSDATA.ARTAL = val_temp.ARTAL NO-LOCK.
   GET FIRST sq NO-LOCK.
   DO WHILE AVAILABLE(LEDNINGSDATA):
      FIND FIRST SPANNINGSNIV WHERE SPANNINGSNIV.SPANID = 
      LEDNINGSDATA.SPANID USE-INDEX SPANID NO-LOCK NO-ERROR.
      FIND FIRST INLASTAB WHERE INLASTAB.INKODID = SPANNINGSNIV.INKODID
      USE-INDEX INKODID NO-LOCK NO-ERROR.
      CREATE dumpa_temp3.
      ASSIGN   
      dumpa_temp3.AVDELNINGNR = val_temp.AVDELNINGNR
      dumpa_temp3.VIDISTRIKT = val_temp.VIDISTRIKT
      dumpa_temp3.ARTAL = val_temp.ARTAL
      dumpa_temp3.LANGD = LEDNINGSDATA.LANGD
      dumpa_temp3.LANGDBLAND = LEDNINGSDATA.LANGDBLAND
      dumpa_temp3.LANGDLUFT = LEDNINGSDATA.LANGDLUFT
      dumpa_temp3.LANGDKABEL = LEDNINGSDATA.LANGDKABEL
      dumpa_temp3.SPANID = INLASTAB.INKODPOSCH.
      RUN textkoll_UI.
      IF langdvar = TRUE THEN DO:      
         ASSIGN
         dumpa_temp3.LANGD = LEDNINGSDATA.LANGD * 1000
         dumpa_temp3.LANGDBLAND = LEDNINGSDATA.LANGDBLAND * 1000
         dumpa_temp3.LANGDLUFT = LEDNINGSDATA.LANGDLUFT * 1000
         dumpa_temp3.LANGDKABEL = LEDNINGSDATA.LANGDKABEL * 1000.
      END.
      GET NEXT sq NO-LOCK.
   END.
   CLOSE QUERY sq.
END.

PROCEDURE textkoll_UI:
   IF LEDNINGSDATA.NATUPPLAGGID1 = 4 AND LEDNINGSDATA.NATUPPLAGGID2 = 8 AND
   LEDNINGSDATA.NATUPPLAGGID3 = 20 AND LEDNINGSDAT.NATUPPLAGGID4 = 0 THEN DO:
/*
NATUPPLAGG1
NATUPPLAGGID1 = 4 =  STATIONSAPPARAT
NATUPPLAGG2   
NATUPPLAGGID1 = 4  NATUPPLAGGID2 = 8 =   EFFEKTBRYTARE 

NATUPPLAGG3   
NATUPPLAGGID2 = 8  NATUPPLAGGID3 = 20 =  EFFEKTBRYTARE -UTOMHUS

NATUPPLAGG4   
NATUPPLAGGID4 = 0 FINNS INTE
NATUPPLAGGID3 = 20 FINNS INTE
NATUPPLAGGID2 = 2  NATUPPLAGGID3 = 1 =  EFFEKTBRYTARE
*/

      ASSIGN
      dumpa_temp3.TEXT1 = "Effektbrytare -utomhus"
      dumpa_temp3.TEXT2 = "Effektbrytare"
      langdvar = FALSE.
   END. 
   ELSE IF LEDNINGSDATA.NATUPPLAGGID1 = 4 AND LEDNINGSDATA.NATUPPLAGGID2 = 12 AND
   LEDNINGSDATA.NATUPPLAGGID3 = 27 AND LEDNINGSDAT.NATUPPLAGGID4 = 0 THEN DO:
      ASSIGN
      dumpa_temp3.TEXT1 = "Lastfrånskiljare -utomhus"
      dumpa_temp3.TEXT2 = "Lastfrånskiljare"
      langdvar = FALSE.
   END. 
   ELSE IF LEDNINGSDATA.NATUPPLAGGID1 = 4 AND LEDNINGSDATA.NATUPPLAGGID2 = 9 AND
   LEDNINGSDATA.NATUPPLAGGID3 = 21 AND LEDNINGSDAT.NATUPPLAGGID4 = 0 THEN DO:
      ASSIGN
      dumpa_temp3.TEXT1 = "Frånskiljare -inomhus"
      dumpa_temp3.TEXT2 = "Frånskiljare"
      langdvar = FALSE.
   END. 
   ELSE IF LEDNINGSDATA.NATUPPLAGGID1 = 4 AND LEDNINGSDATA.NATUPPLAGGID2 = 10 AND
   LEDNINGSDATA.NATUPPLAGGID3 = 23 AND LEDNINGSDAT.NATUPPLAGGID4 = 0 THEN DO:
      ASSIGN
      dumpa_temp3.TEXT1 = "-olje med exp.kärl"
      dumpa_temp3.TEXT2 = "Krafttransformator"
      langdvar = FALSE.
   END. 
   ELSE IF LEDNINGSDATA.NATUPPLAGGID1 = 4 AND LEDNINGSDATA.NATUPPLAGGID2 = 8 AND
   LEDNINGSDATA.NATUPPLAGGID3 = 19 AND LEDNINGSDAT.NATUPPLAGGID4 = 0 THEN DO:
      ASSIGN
      dumpa_temp3.TEXT1 = "Effektbrytare -inomhus"
      dumpa_temp3.TEXT2 = "Effektbrytare"
      langdvar = FALSE.
   END. 
   ELSE IF LEDNINGSDATA.NATUPPLAGGID1 = 4 AND LEDNINGSDATA.NATUPPLAGGID2 = 12 AND
   LEDNINGSDATA.NATUPPLAGGID3 = 26 AND LEDNINGSDAT.NATUPPLAGGID4 = 0 THEN DO:
      ASSIGN
      dumpa_temp3.TEXT1 = "Lastfrånskiljare -inomhus"
      dumpa_temp3.TEXT2 = "Lastfrånskiljare"
      langdvar = FALSE.
   END. 
   ELSE IF LEDNINGSDATA.NATUPPLAGGID1 = 4 AND LEDNINGSDATA.NATUPPLAGGID2 = 12 AND
   LEDNINGSDATA.NATUPPLAGGID3 = 28 AND LEDNINGSDAT.NATUPPLAGGID4 = 0 THEN DO:
      ASSIGN
      dumpa_temp3.TEXT1 = "Lastfr.sk. m. säkr. -inomhus"
      dumpa_temp3.TEXT2 = "Lastfrånskiljare med säkring"
      langdvar = FALSE.
   END. 
   ELSE IF LEDNINGSDATA.NATUPPLAGGID1 = 4 AND LEDNINGSDATA.NATUPPLAGGID2 = 10 AND
   LEDNINGSDATA.NATUPPLAGGID3 = 30 AND LEDNINGSDAT.NATUPPLAGGID4 = 0 THEN DO:
      ASSIGN
      dumpa_temp3.TEXT1 = "-olje sluten"
      dumpa_temp3.TEXT2 = "Krafttransformator"
      langdvar = FALSE.
   END. 
   ELSE IF LEDNINGSDATA.NATUPPLAGGID1 = 4 AND LEDNINGSDATA.NATUPPLAGGID2 = 10 AND
   LEDNINGSDATA.NATUPPLAGGID3 = 31 AND LEDNINGSDAT.NATUPPLAGGID4 = 0 THEN DO:
      ASSIGN
      dumpa_temp3.TEXT1 = "-torrisolerad luft"
      dumpa_temp3.TEXT2 = "Krafttransformator"
      langdvar = FALSE.
   END. 
   ELSE IF LEDNINGSDATA.NATUPPLAGGID1 = 4 AND LEDNINGSDATA.NATUPPLAGGID2 = 11 AND
   LEDNINGSDATA.NATUPPLAGGID3 = 24 AND LEDNINGSDAT.NATUPPLAGGID4 = 0 THEN DO:
      ASSIGN
      dumpa_temp3.TEXT1 = "Kondensatorbatterier totalt"
      dumpa_temp3.TEXT2 = "Kondensatorbatterier"
      langdvar = FALSE.
   END. 
   ELSE IF LEDNINGSDATA.NATUPPLAGGID1 = 4 AND LEDNINGSDATA.NATUPPLAGGID2 = 11 AND
   LEDNINGSDATA.NATUPPLAGGID3 = 25 AND LEDNINGSDAT.NATUPPLAGGID4 = 0 THEN DO:
      ASSIGN
      dumpa_temp3.TEXT1 = "varav -PCB"
      dumpa_temp3.TEXT2 = "Kondensatorbatterier"
      langdvar = FALSE.
   END. 
   ELSE IF LEDNINGSDATA.NATUPPLAGGID1 = 2 AND LEDNINGSDATA.NATUPPLAGGID2 = 2 AND
   LEDNINGSDATA.NATUPPLAGGID3 = 3 AND LEDNINGSDAT.NATUPPLAGGID4 = 0 THEN DO:
      ASSIGN
      dumpa_temp3.TEXT1 = "Kraftkabel i mark"
      dumpa_temp3.TEXT2 = "Markledning"
      langdvar = TRUE.
   END.
   ELSE IF LEDNINGSDATA.NATUPPLAGGID1 = 2 AND LEDNINGSDATA.NATUPPLAGGID2 = 2 AND
   LEDNINGSDATA.NATUPPLAGGID3 = 4 AND LEDNINGSDAT.NATUPPLAGGID4 = 0 THEN DO:
      ASSIGN
      dumpa_temp3.TEXT1 = "Varav PEX"
      dumpa_temp3.TEXT2 = "Markledning"
      langdvar = TRUE.
   END.
   ELSE IF LEDNINGSDATA.NATUPPLAGGID1 = 3 AND LEDNINGSDATA.NATUPPLAGGID2 = 4 AND
   LEDNINGSDATA.NATUPPLAGGID3 = 0 AND LEDNINGSDAT.NATUPPLAGGID4 = 0 THEN DO:
      ASSIGN
      dumpa_temp3.TEXT1 = "Fördelningsstation"
      dumpa_temp3.TEXT2 = "Station"
      langdvar = FALSE.
   END. 
   ELSE IF LEDNINGSDATA.NATUPPLAGGID1 = 2 AND LEDNINGSDATA.NATUPPLAGGID2 = 1 AND
   LEDNINGSDATA.NATUPPLAGGID3 = 1 AND LEDNINGSDAT.NATUPPLAGGID4 = 0 THEN DO:
      ASSIGN
      dumpa_temp3.TEXT1 = "Friledning, oisolerad"
      dumpa_temp3.TEXT2 = "Luftledning"
      langdvar = TRUE.
   END. 
   ELSE IF LEDNINGSDATA.NATUPPLAGGID1 = 2 AND LEDNINGSDATA.NATUPPLAGGID2 = 2 AND
   LEDNINGSDATA.NATUPPLAGGID3 = 5 AND LEDNINGSDAT.NATUPPLAGGID4 = 0 THEN DO:
      ASSIGN
      dumpa_temp3.TEXT1 = "Kraftkabel i vatten"
      dumpa_temp3.TEXT2 = "Markledning"
      langdvar = TRUE.
   END. 
   ELSE IF LEDNINGSDATA.NATUPPLAGGID1 = 3 AND LEDNINGSDATA.NATUPPLAGGID2 = 5 AND
   LEDNINGSDATA.NATUPPLAGGID3 = 0 AND LEDNINGSDAT.NATUPPLAGGID4 = 0 THEN DO:
      ASSIGN
      dumpa_temp3.TEXT1 = "Kopplingsstation"
      dumpa_temp3.TEXT2 = "Station"
      langdvar = FALSE.
   END. 
   ELSE IF LEDNINGSDATA.NATUPPLAGGID1 = 3 AND LEDNINGSDATA.NATUPPLAGGID2 = 7 AND
   LEDNINGSDATA.NATUPPLAGGID3 = 13 AND LEDNINGSDAT.NATUPPLAGGID4 = 0 THEN DO:
      ASSIGN
      dumpa_temp3.TEXT1 = "Stolpstation"
      dumpa_temp3.TEXT2 = "Nätstation"
      langdvar = FALSE.
   END. 
   ELSE IF LEDNINGSDATA.NATUPPLAGGID1 = 3 AND LEDNINGSDATA.NATUPPLAGGID2 = 7 AND
   LEDNINGSDATA.NATUPPLAGGID3 = 11 AND LEDNINGSDAT.NATUPPLAGGID4 = 0 THEN DO:
      ASSIGN
      dumpa_temp3.TEXT1 = "Btg el stenstn. inomhusman."
      dumpa_temp3.TEXT2 = "Nätstation"
      langdvar = FALSE.
   END. 
   ELSE IF LEDNINGSDATA.NATUPPLAGGID1 = 3 AND LEDNINGSDATA.NATUPPLAGGID2 = 7 AND
   LEDNINGSDATA.NATUPPLAGGID3 = 12 AND LEDNINGSDAT.NATUPPLAGGID4 = 0 THEN DO:
      ASSIGN
      dumpa_temp3.TEXT1 = "Btg el stenstn. utomhusman."
      dumpa_temp3.TEXT2 = "Nätstation"
      langdvar = FALSE.
   END. 
   ELSE IF LEDNINGSDATA.NATUPPLAGGID1 = 3 AND LEDNINGSDATA.NATUPPLAGGID2 = 7 AND
   LEDNINGSDATA.NATUPPLAGGID3 = 14 AND LEDNINGSDAT.NATUPPLAGGID4 = 0 THEN DO:
      ASSIGN
      dumpa_temp3.TEXT1 = "Plåtstation"
      dumpa_temp3.TEXT2 = "Nätstation"
      langdvar = FALSE.
   END. 
   ELSE IF LEDNINGSDATA.NATUPPLAGGID1 = 3 AND LEDNINGSDATA.NATUPPLAGGID2 = 7 AND
   LEDNINGSDATA.NATUPPLAGGID3 = 15 AND LEDNINGSDAT.NATUPPLAGGID4 = 0 THEN DO:
      ASSIGN
      dumpa_temp3.TEXT1 = "Satellitstation"
      dumpa_temp3.TEXT2 = "Nätstation"
      langdvar = FALSE.
   END. 
   ELSE IF LEDNINGSDATA.NATUPPLAGGID1 = 3 AND LEDNINGSDATA.NATUPPLAGGID2 = 7 AND
   LEDNINGSDATA.NATUPPLAGGID3 = 17 AND LEDNINGSDAT.NATUPPLAGGID4 = 0 THEN DO:
      ASSIGN
      dumpa_temp3.TEXT1 = "Kapslad transformator"
      dumpa_temp3.TEXT2 = "Nätstation"
      langdvar = FALSE.
   END. 
   ELSE IF LEDNINGSDATA.NATUPPLAGGID1 = 3 AND LEDNINGSDATA.NATUPPLAGGID2 = 7 AND
   LEDNINGSDATA.NATUPPLAGGID3 = 18 AND LEDNINGSDAT.NATUPPLAGGID4 = 0 THEN DO:
      ASSIGN
      dumpa_temp3.TEXT1 = "Inhyst station"
      dumpa_temp3.TEXT2 = "Nätstation"
      langdvar = FALSE.
   END.    
   ELSE IF LEDNINGSDATA.NATUPPLAGGID1 = 3 AND LEDNINGSDATA.NATUPPLAGGID2 = 7 AND
   LEDNINGSDATA.NATUPPLAGGID3 = 34 AND LEDNINGSDAT.NATUPPLAGGID4 = 0 THEN DO:      
      ASSIGN
      dumpa_temp3.TEXT1 = "Annan stationstyp"
      dumpa_temp3.TEXT2 = "Nätstation"
      langdvar = FALSE.
   END.   
   ELSE IF LEDNINGSDATA.NATUPPLAGGID1 = 2 AND LEDNINGSDATA.NATUPPLAGGID2 = 1 AND
   LEDNINGSDATA.NATUPPLAGGID3 = 7 AND LEDNINGSDAT.NATUPPLAGGID4 = 0 THEN DO:
      ASSIGN
      dumpa_temp3.TEXT1 = "Hängkabelledning"
      dumpa_temp3.TEXT2 = "Luftledning"
      langdvar = TRUE.
   END. 
   ELSE IF LEDNINGSDATA.NATUPPLAGGID1 = 2 AND LEDNINGSDATA.NATUPPLAGGID2 = 1 AND
   LEDNINGSDATA.NATUPPLAGGID3 = 8 AND LEDNINGSDAT.NATUPPLAGGID4 = 0 THEN DO:
      ASSIGN
      dumpa_temp3.TEXT1 = "Hängspiralkabelledning"
      dumpa_temp3.TEXT2 = "Luftledning"
      langdvar = TRUE.
   END.    
   ELSE IF LEDNINGSDATA.NATUPPLAGGID1 = 2 AND LEDNINGSDATA.NATUPPLAGGID2 = 1 AND
   LEDNINGSDATA.NATUPPLAGGID3 = 33 AND LEDNINGSDAT.NATUPPLAGGID4 = 0 THEN DO:      
      ASSIGN
      dumpa_temp3.TEXT1 = "Säkrings- och apparatlåda"
      dumpa_temp3.TEXT2 = "Luftledning"
      langdvar = FALSE.
   END. 
   ELSE IF LEDNINGSDATA.NATUPPLAGGID1 = 2 AND LEDNINGSDATA.NATUPPLAGGID2 = 1 AND
   LEDNINGSDATA.NATUPPLAGGID3 = 35 AND LEDNINGSDAT.NATUPPLAGGID4 = 0 THEN DO:      
      ASSIGN
      dumpa_temp3.TEXT1 = "Annan ledning"
      dumpa_temp3.TEXT2 = "Luftledning".
   END. 
   ELSE IF LEDNINGSDATA.NATUPPLAGGID1 = 2 AND LEDNINGSDATA.NATUPPLAGGID2 = 1 AND
   LEDNINGSDATA.NATUPPLAGGID3 = 2 AND LEDNINGSDAT.NATUPPLAGGID4 = 3 THEN DO:
      ASSIGN
      dumpa_temp3.TEXT1 = "Lastfrånskiljare"
      dumpa_temp3.TEXT2 = "App. i luftledn. och stolpstn."
      langdvar = FALSE.
   END.
   ELSE IF LEDNINGSDATA.NATUPPLAGGID1 = 2 AND LEDNINGSDATA.NATUPPLAGGID2 = 1 AND
   LEDNINGSDATA.NATUPPLAGGID3 = 2 AND LEDNINGSDAT.NATUPPLAGGID4 = 2 THEN DO:
      ASSIGN
      dumpa_temp3.TEXT1 = "Frånskiljare"
      dumpa_temp3.TEXT2 = "App. i luftledn. och stolpstn."
      langdvar = FALSE.
   END. 
   ELSE IF LEDNINGSDATA.NATUPPLAGGID1 = 4 AND LEDNINGSDATA.NATUPPLAGGID2 = 9 AND
   LEDNINGSDATA.NATUPPLAGGID3 = 22 AND LEDNINGSDAT.NATUPPLAGGID4 = 0 THEN DO:
      ASSIGN
      dumpa_temp3.TEXT1 = "Frånskiljare -utomhus"
      dumpa_temp3.TEXT2 = "Frånskiljare"
      langdvar = FALSE.
   END. 
   ELSE IF LEDNINGSDATA.NATUPPLAGGID1 = 2 AND LEDNINGSDATA.NATUPPLAGGID2 = 1 AND
   LEDNINGSDATA.NATUPPLAGGID3 = 6 AND LEDNINGSDAT.NATUPPLAGGID4 = 0 THEN DO:
      ASSIGN
      dumpa_temp3.TEXT1 = "Friledning, isolerad"
      dumpa_temp3.TEXT2 = "Luftledning"
      langdvar = TRUE.
   END. 
   ELSE IF LEDNINGSDATA.NATUPPLAGGID1 = 2 AND LEDNINGSDATA.NATUPPLAGGID2 = 2 AND
   LEDNINGSDATA.NATUPPLAGGID3 = 10 AND LEDNINGSDAT.NATUPPLAGGID4 = 0 THEN DO:
      ASSIGN
      dumpa_temp3.TEXT1 = "Avgrenings-/Kabelskåp"
      dumpa_temp3.TEXT2 = "Markledning"
      langdvar = FALSE.
   END. 
   ELSE IF LEDNINGSDATA.NATUPPLAGGID1 = 3 AND LEDNINGSDATA.NATUPPLAGGID2 = 3 AND
   LEDNINGSDATA.NATUPPLAGGID3 = 0 AND LEDNINGSDAT.NATUPPLAGGID4 = 0 THEN DO:
      ASSIGN
      dumpa_temp3.TEXT1 = "Regionstation"
      dumpa_temp3.TEXT2 = "Station"
      langdvar = FALSE.
   END. 
   ELSE IF LEDNINGSDATA.NATUPPLAGGID1 = 3 AND LEDNINGSDATA.NATUPPLAGGID2 = 7 AND
   LEDNINGSDATA.NATUPPLAGGID3 = 16 AND LEDNINGSDAT.NATUPPLAGGID4 = 0 THEN DO:
      ASSIGN
      dumpa_temp3.TEXT1 = "Markstation"
      dumpa_temp3.TEXT2 = "Nätstation"
      langdvar = FALSE.
   END. 
   ELSE IF LEDNINGSDATA.NATUPPLAGGID1 = 4 AND LEDNINGSDATA.NATUPPLAGGID2 = 12 AND
   LEDNINGSDATA.NATUPPLAGGID3 = 29 AND LEDNINGSDAT.NATUPPLAGGID4 = 0 THEN DO:
      ASSIGN
      dumpa_temp3.TEXT1 = "Lastfr.sk. m. säkr. -utomhus"
      dumpa_temp3.TEXT2 = "Lastfrånskiljare med säkring"
      langdvar = FALSE.
   END. 
   ELSE IF LEDNINGSDATA.NATUPPLAGGID1 = 2 AND LEDNINGSDATA.NATUPPLAGGID2 = 1 AND
   LEDNINGSDATA.NATUPPLAGGID3 = 2 AND LEDNINGSDAT.NATUPPLAGGID4 = 1 THEN DO:
      ASSIGN
      dumpa_temp3.TEXT1 = "Effektbrytare"
      dumpa_temp3.TEXT2 = "App. i luftledn. och stolpstn."
      langdvar = FALSE.
   END. 
   ELSE IF LEDNINGSDATA.NATUPPLAGGID1 = 3 AND LEDNINGSDATA.NATUPPLAGGID2 = 6 AND
   LEDNINGSDATA.NATUPPLAGGID3 = 0 AND LEDNINGSDAT.NATUPPLAGGID4 = 0 THEN DO:
      ASSIGN
      dumpa_temp3.TEXT1 = "Likriktarstation"
      dumpa_temp3.TEXT2 = "Station"
      langdvar = FALSE.
   END. 
   ELSE IF LEDNINGSDATA.NATUPPLAGGID1 = 4 AND LEDNINGSDATA.NATUPPLAGGID2 = 10 AND
   LEDNINGSDATA.NATUPPLAGGID3 = 32 AND LEDNINGSDAT.NATUPPLAGGID4 = 0 THEN DO:
      ASSIGN
      dumpa_temp3.TEXT1 = "-torrisolerad, solid"
      dumpa_temp3.TEXT2 = "Krafttransformator"
      langdvar = FALSE.
   END. 
   ELSE IF LEDNINGSDATA.NATUPPLAGGID1 = 2 AND LEDNINGSDATA.NATUPPLAGGID2 = 1 AND
   LEDNINGSDATA.NATUPPLAGGID3 = 2 AND LEDNINGSDAT.NATUPPLAGGID4 = 4 THEN DO:
      ASSIGN
      dumpa_temp3.TEXT1 = "Kondensatorbatteri, serie"
      dumpa_temp3.TEXT2 = "App. i luftledn. och stolpstn"
      langdvar = FALSE.
   END. 
   ELSE IF LEDNINGSDATA.NATUPPLAGGID1 = 2 AND LEDNINGSDATA.NATUPPLAGGID2 = 1 AND
   LEDNINGSDATA.NATUPPLAGGID3 = 2 AND LEDNINGSDAT.NATUPPLAGGID4 = 5 THEN DO:
      ASSIGN
      dumpa_temp3.TEXT1 = "Kondensatorbatteri, shunt"
      dumpa_temp3.TEXT2 = "App. i luftledn. och stolpstn."
      langdvar = FALSE.
   END. 
   ELSE IF LEDNINGSDATA.NATUPPLAGGID1 = 2 AND LEDNINGSDATA.NATUPPLAGGID2 = 2 AND
   LEDNINGSDATA.NATUPPLAGGID3 = 9 AND LEDNINGSDAT.NATUPPLAGGID4 = 0 THEN DO:
      ASSIGN
      dumpa_temp3.TEXT1 = "Avgrenings-/Kabelskåp"
      dumpa_temp3.TEXT2 = "Markledning"
      langdvar = FALSE.
   END.  
   ELSE IF LEDNINGSDATA.NATUPPLAGGID1 = 2 AND LEDNINGSDATA.NATUPPLAGGID2 = 2 AND
   LEDNINGSDATA.NATUPPLAGGID3 = 10 AND LEDNINGSDAT.NATUPPLAGGID4 = 0 THEN DO:      
      ASSIGN
      dumpa_temp3.TEXT1 = "Säkrings- och apparatlåda"
      dumpa_temp3.TEXT2 = "Markledning"
      langdvar = FALSE.
   END.
END PROCEDURE.                
