/*IMPDIST.P Import av distrikt*/       
DEFINE NEW SHARED VARIABLE quotervar AS CHARACTER FORMAT "X(256)" NO-UNDO.




DEFINE VARIABLE musz AS LOGICAL NO-UNDO.

DEFINE VARIABLE rad AS INTEGER NO-UNDO.
DEFINE VARIABLE prognamn AS CHARACTER FORMAT "X(20)" NO-UNDO.
DEFINE VARIABLE prognamndat AS CHARACTER FORMAT "X(20)" NO-UNDO.
DEFINE VARIABLE prognamnque AS CHARACTER FORMAT "X(20)" NO-UNDO.                
DEFINE VARIABLE words AS CHARACTER FORMAT "X(132)" NO-UNDO.
DEFINE VARIABLE kommando AS CHARACTER FORMAT "X(132)" NO-UNDO.
DEFINE VARIABLE kommandoprog AS CHARACTER FORMAT "X(20)" NO-UNDO.
DEFINE VARIABLE satsvar AS CHARACTER FORMAT "X(11)" NO-UNDO.
DEFINE VARIABLE enrvar AS CHARACTER FORMAT "X(11)" NO-UNDO.
DEFINE VARIABLE melvar AS INTEGER NO-UNDO.
DEFINE VARIABLE melvar2 AS INTEGER NO-UNDO.
DEFINE VARIABLE langd AS INTEGER NO-UNDO.
DEFINE VARIABLE pos1 AS INTEGER NO-UNDO. 
DEFINE VARIABLE nrvar AS INTEGER NO-UNDO.

{DARINTIDIN.I}
   
   
DEFINE TEMP-TABLE temp_text
   FIELD B1 AS INTEGER /*företag*/
   FIELD B2 AS CHARACTER /*distrikt*/
   FIELD PROGNAMN AS CHARACTER FORMAT "X(100)".   

DEFINE BUFFER distbuff FOR STORDISTRIKT.   

DEFINE INPUT PARAMETER TABLE FOR tidin3.
DEFINE OUTPUT PARAMETER TABLE FOR temp_text.
{AMERICANEUROPEAN.I}
{muswait.i}         
RUN in_UI.
{musarrow.i}
{EUROPEANAMERICAN.I}
PROCEDURE in_UI: 
       
   FOR EACH temp_text:
      DELETE temp_text.
   END.
   
   RUN skapasats_UI.
/*    OS-DELETE VALUE(wtidvar). */
END PROCEDURE.

PROCEDURE skapasats_UI:
   FIND FIRST tidin3 NO-LOCK NO-ERROR.
   FIND FIRST AVDELNING WHERE AVDELNING.AVDELNINGNR = tidin3.B1 NO-LOCK NO-ERROR.
   IF AVAILABLE AVDELNING THEN DO:
      FOR EACH tidin3 NO-LOCK:
         FIND FIRST STORDISTRIKT WHERE STORDISTRIKT.AVDELNINGNR = tidin3.B1 AND
         STORDISTRIKT.VIDISTRIKT = tidin3.B2 AND STORDISTRIKT.ARTAL = tidin3.B3
         NO-LOCK NO-ERROR.
         IF NOT AVAILABLE STORDISTRIKT THEN DO:
            FIND LAST STORDISTRIKT USE-INDEX DISTRIKTID NO-LOCK NO-ERROR.
            IF AVAILABLE STORDISTRIKT THEN nrvar = STORDISTRIKT.DISTRIKTID + 1.
            ELSE nrvar = 1.            
            CREATE STORDISTRIKT.                                               
            ASSIGN
            STORDISTRIKT.AVDELNINGNR = tidin3.B1
            STORDISTRIKT.DISTRIKTID = nrvar
            STORDISTRIKT.VIDISTRIKT = tidin3.B2
            STORDISTRIKT.NAMN = tidin3.B4
            STORDISTRIKT.ARTAL = tidin3.B3.            
         END.
      END.      
   END.
   ELSE DO:
      CREATE temp_text.
      ASSIGN
      temp_text.B1 = tidin3.B1
      temp_text.B2 = tidin3.B2
      temp_text.PROGNAMN = "FÖRETAG SAKNAS". 
   END.
END PROCEDURE.
