/* LEDDATA.p  SUMMERING AV STÖRNING*/

DEFINE TEMP-TABLE leddata_temp
   FIELD SPANID LIKE STORNINGSTAB.FELSPANID   
   FIELD ADELID LIKE STORNINGSTAB.ADELID
   FIELD ANTAL AS INTEGER.

DEFINE TEMP-TABLE avd_temp
   FIELD AVDELNINGNR LIKE STORDISTRIKT.AVDELNINGNR   
   FIELD NAMN LIKE STORDISTRIKT.NAMN
   INDEX AVD IS PRIMARY AVDELNINGNR.

DEFINE INPUT PARAMETER TABLE FOR avd_temp.
DEFINE INPUT PARAMETER valfore AS LOGICAL NO-UNDO.
DEFINE INPUT PARAMETER distvar LIKE STORDISTRIKT.DISTRIKTID NO-UNDO.   
DEFINE INPUT PARAMETER bdatum AS DATE NO-UNDO.
DEFINE INPUT PARAMETER alla AS LOGICAL NO-UNDO.
DEFINE INPUT PARAMETER adelvar LIKE ANLAGGNINGSDEL.ADELID NO-UNDO.
DEFINE INPUT-OUTPUT PARAMETER TABLE FOR leddata_temp.


   {muswait.i}  
   IF valfore = TRUE THEN DO:
      FOR EACH avd_temp USE-INDEX AVD:
         OPEN QUERY dq FOR EACH STORDISTRIKT WHERE 
         STORDISTRIKT.AVDELNINGNR = avd_temp.AVDELNINGNR AND 
         STORDISTRIKT.ARTAL = YEAR(bdatum) USE-INDEX AVDARTAL NO-LOCK.
         GET FIRST dq NO-LOCK.
         DO WHILE AVAILABLE(STORDISTRIKT):
            distvar = STORDISTRIKT.DISTRIKTID.
            RUN distrikt_UI.
            GET NEXT dq NO-LOCK.
         END.
         CLOSE QUERY dq.
      END.         
   END.
   ELSE DO:
      IF alla = TRUE THEN DO:
         IF adelvar = 1 THEN DO:
            OPEN QUERY lq FOR EACH LEDNINGSDATA WHERE LEDNINGSDATA.ARTAL = YEAR(bdatum) AND
            LEDNINGSDATA.NATUPPLAGGID1 = 3 AND LEDNINGSDATA.NATUPPLAGGID2 = 3 AND
            LEDNINGSDATA.NATUPPLAGGID3 = 0 AND LEDNINGSDATA.NATUPPLAGGID4 = 0 NO-LOCK. 
            GET FIRST lq NO-LOCK.
            DO WHILE AVAILABLE(LEDNINGSDATA):
               RUN summa_UI.
               GET NEXT lq NO-LOCK.
            END.
         END.
         ELSE IF adelvar = 2 THEN DO:
            OPEN QUERY lq FOR EACH LEDNINGSDATA WHERE LEDNINGSDATA.ARTAL = YEAR(bdatum) AND
            LEDNINGSDATA.NATUPPLAGGID1 = 3 AND LEDNINGSDATA.NATUPPLAGGID2 = 4 AND
            LEDNINGSDATA.NATUPPLAGGID3 = 0 AND LEDNINGSDATA.NATUPPLAGGID4 = 0 NO-LOCK.
            GET FIRST lq NO-LOCK.
            DO WHILE AVAILABLE(LEDNINGSDATA):
               RUN summa_UI.
               GET NEXT lq NO-LOCK.
            END.
         END.
         ELSE IF adelvar = 3 THEN DO:
            OPEN QUERY lq FOR EACH LEDNINGSDATA WHERE LEDNINGSDATA.ARTAL = YEAR(bdatum) AND
            LEDNINGSDATA.NATUPPLAGGID1 = 3 AND LEDNINGSDATA.NATUPPLAGGID2 = 5 AND
            LEDNINGSDATA.NATUPPLAGGID3 = 0 AND LEDNINGSDATA.NATUPPLAGGID4 = 0 NO-LOCK.
            GET FIRST lq NO-LOCK.
            DO WHILE AVAILABLE(LEDNINGSDATA):
               RUN summa_UI.
               GET NEXT lq NO-LOCK.
            END.
         END.
         ELSE IF adelvar = 4 THEN DO:
            OPEN QUERY lq FOR EACH LEDNINGSDATA WHERE LEDNINGSDATA.ARTAL = YEAR(bdatum) AND
            LEDNINGSDATA.NATUPPLAGGID1 = 3 AND LEDNINGSDATA.NATUPPLAGGID2 = 7 AND
            LEDNINGSDATA.NATUPPLAGGID3 = 13 AND LEDNINGSDATA.NATUPPLAGGID4 = 0 NO-LOCK.
            GET FIRST lq NO-LOCK.
            DO WHILE AVAILABLE(LEDNINGSDATA):
               RUN summa_UI.
               GET NEXT lq NO-LOCK.
            END.
         END.
         ELSE IF adelvar = 5 THEN DO:
            OPEN QUERY lq FOR EACH LEDNINGSDATA WHERE LEDNINGSDATA.ARTAL = YEAR(bdatum) AND
            LEDNINGSDATA.NATUPPLAGGID1 = 3 AND LEDNINGSDATA.NATUPPLAGGID2 = 7 AND
            LEDNINGSDATA.NATUPPLAGGID3 = 11 AND LEDNINGSDATA.NATUPPLAGGID4 = 0 NO-LOCK.
            GET FIRST lq NO-LOCK.
            DO WHILE AVAILABLE(LEDNINGSDATA):
               RUN summa_UI.
               GET NEXT lq NO-LOCK.
            END.
         END.
         ELSE IF adelvar = 6 THEN DO:
            OPEN QUERY lq FOR EACH LEDNINGSDATA WHERE LEDNINGSDATA.ARTAL = YEAR(bdatum) AND
            LEDNINGSDATA.NATUPPLAGGID1 = 3 AND LEDNINGSDATA.NATUPPLAGGID2 = 7 AND
            LEDNINGSDATA.NATUPPLAGGID3 = 12 AND LEDNINGSDATA.NATUPPLAGGID4 = 0 NO-LOCK.
            GET FIRST lq NO-LOCK.
            DO WHILE AVAILABLE(LEDNINGSDATA):
               RUN summa_UI.
               GET NEXT lq NO-LOCK.
            END.
         END.
         ELSE IF adelvar = 7 THEN DO:
            OPEN QUERY lq FOR EACH LEDNINGSDATA WHERE LEDNINGSDATA.ARTAL = YEAR(bdatum) AND
            LEDNINGSDATA.NATUPPLAGGID1 = 3 AND LEDNINGSDATA.NATUPPLAGGID2 = 7 AND
            LEDNINGSDATA.NATUPPLAGGID3 = 14 AND LEDNINGSDATA.NATUPPLAGGID4 = 0 NO-LOCK.
            GET FIRST lq NO-LOCK.
            DO WHILE AVAILABLE(LEDNINGSDATA):
               RUN summa_UI.
               GET NEXT lq NO-LOCK.
            END.
         END.
         ELSE IF adelvar = 8 THEN DO:
            OPEN QUERY lq FOR EACH LEDNINGSDATA WHERE LEDNINGSDATA.ARTAL = YEAR(bdatum) AND
            LEDNINGSDATA.NATUPPLAGGID1 = 3 AND LEDNINGSDATA.NATUPPLAGGID2 = 7 AND
            LEDNINGSDATA.NATUPPLAGGID3 = 15 AND LEDNINGSDATA.NATUPPLAGGID4 = 0 NO-LOCK.
            GET FIRST lq NO-LOCK.
            DO WHILE AVAILABLE(LEDNINGSDATA):
               RUN summa_UI.
               GET NEXT lq NO-LOCK.
            END.
         END.
         ELSE IF adelvar = 9 THEN DO:
            OPEN QUERY lq FOR EACH LEDNINGSDATA WHERE LEDNINGSDATA.ARTAL = YEAR(bdatum) AND
            LEDNINGSDATA.NATUPPLAGGID1 = 3 AND LEDNINGSDATA.NATUPPLAGGID2 = 7 AND
            LEDNINGSDATA.NATUPPLAGGID3 = 16 AND LEDNINGSDATA.NATUPPLAGGID4 = 0 NO-LOCK.
            GET FIRST lq NO-LOCK.
            DO WHILE AVAILABLE(LEDNINGSDATA):
               RUN summa_UI.
               GET NEXT lq NO-LOCK.
            END.
         END.
         ELSE IF adelvar = 10 THEN DO:
            OPEN QUERY lq FOR EACH LEDNINGSDATA WHERE LEDNINGSDATA.ARTAL = YEAR(bdatum) AND
            LEDNINGSDATA.NATUPPLAGGID1 = 3 AND LEDNINGSDATA.NATUPPLAGGID2 = 7 AND
            LEDNINGSDATA.NATUPPLAGGID3 = 17 AND LEDNINGSDATA.NATUPPLAGGID4 = 0 NO-LOCK.
            GET FIRST lq NO-LOCK.
            DO WHILE AVAILABLE(LEDNINGSDATA):
               RUN summa_UI.
               GET NEXT lq NO-LOCK.
            END.
         END.
         ELSE IF adelvar = 11 THEN DO:
            OPEN QUERY lq FOR EACH LEDNINGSDATA WHERE LEDNINGSDATA.ARTAL = YEAR(bdatum) AND
            LEDNINGSDATA.NATUPPLAGGID1 = 3 AND LEDNINGSDATA.NATUPPLAGGID2 = 7 AND
            LEDNINGSDATA.NATUPPLAGGID3 = 18 AND LEDNINGSDATA.NATUPPLAGGID4 = 0 NO-LOCK.
            GET FIRST lq NO-LOCK.
            DO WHILE AVAILABLE(LEDNINGSDATA):
               RUN summa_UI.
               GET NEXT lq NO-LOCK.
            END.
         END.
         ELSE IF adelvar = 12 THEN DO:
            OPEN QUERY lq FOR EACH LEDNINGSDATA WHERE LEDNINGSDATA.ARTAL = YEAR(bdatum) AND
            LEDNINGSDATA.NATUPPLAGGID1 = 3 AND LEDNINGSDATA.NATUPPLAGGID2 = 7 AND
            LEDNINGSDATA.NATUPPLAGGID3 = 18 AND LEDNINGSDATA.NATUPPLAGGID4 = 0 NO-LOCK.
            GET FIRST lq NO-LOCK.
            DO WHILE AVAILABLE(LEDNINGSDATA):
               RUN summa_UI.
               GET NEXT lq NO-LOCK.
            END.
         END.
         ELSE IF adelvar = 13 THEN DO:
            OPEN QUERY lq FOR EACH LEDNINGSDATA WHERE LEDNINGSDATA.ARTAL = YEAR(bdatum) AND
            LEDNINGSDATA.NATUPPLAGGID1 = 2 AND LEDNINGSDATA.NATUPPLAGGID2 = 1 AND
            LEDNINGSDATA.NATUPPLAGGID3 = 1 AND LEDNINGSDATA.NATUPPLAGGID4 = 0 NO-LOCK.
            GET FIRST lq NO-LOCK.
            DO WHILE AVAILABLE(LEDNINGSDATA):
               RUN summa_UI.
               GET NEXT lq NO-LOCK.
            END.
         END.
         ELSE IF adelvar = 14 THEN DO:
            OPEN QUERY lq FOR EACH LEDNINGSDATA WHERE LEDNINGSDATA.ARTAL = YEAR(bdatum) AND
            LEDNINGSDATA.NATUPPLAGGID1 = 2 AND LEDNINGSDATA.NATUPPLAGGID2 = 1 AND
            LEDNINGSDATA.NATUPPLAGGID3 = 6 AND LEDNINGSDATA.NATUPPLAGGID4 = 0 NO-LOCK.
            GET FIRST lq NO-LOCK.
            DO WHILE AVAILABLE(LEDNINGSDATA):
               RUN summa_UI.
               GET NEXT lq NO-LOCK.
            END.
         END.
         ELSE IF adelvar = 15 THEN DO:
            OPEN QUERY lq FOR EACH LEDNINGSDATA WHERE LEDNINGSDATA.ARTAL = YEAR(bdatum) AND
            LEDNINGSDATA.NATUPPLAGGID1 = 2 AND LEDNINGSDATA.NATUPPLAGGID2 = 1 AND
            LEDNINGSDATA.NATUPPLAGGID3 = 7 AND LEDNINGSDATA.NATUPPLAGGID4 = 0 NO-LOCK.
            GET FIRST lq NO-LOCK.
            DO WHILE AVAILABLE(LEDNINGSDATA):
               RUN summa_UI.
               GET NEXT lq NO-LOCK.
            END.
         END.
         ELSE IF adelvar = 16 THEN DO:
            OPEN QUERY lq FOR EACH LEDNINGSDATA WHERE LEDNINGSDATA.ARTAL = YEAR(bdatum) AND
            LEDNINGSDATA.NATUPPLAGGID1 = 2 AND LEDNINGSDATA.NATUPPLAGGID2 = 1 AND
            LEDNINGSDATA.NATUPPLAGGID3 = 8 AND LEDNINGSDATA.NATUPPLAGGID4 = 0 NO-LOCK.
            GET FIRST lq NO-LOCK.
            DO WHILE AVAILABLE(LEDNINGSDATA):
               RUN summa_UI.
               GET NEXT lq NO-LOCK.
            END.
         END.
         ELSE IF adelvar = 17 THEN DO:
            /*finns ej*/
         END.
         ELSE IF adelvar = 18 THEN DO:
            /*finns ej*/
         END.
         ELSE IF adelvar = 19 THEN DO:
            OPEN QUERY lq FOR EACH LEDNINGSDATA WHERE LEDNINGSDATA.ARTAL = YEAR(bdatum) AND
            LEDNINGSDATA.NATUPPLAGGID1 = 2 AND LEDNINGSDATA.NATUPPLAGGID2 = 2 AND
            LEDNINGSDATA.NATUPPLAGGID3 = 3 AND LEDNINGSDATA.NATUPPLAGGID4 = 0 NO-LOCK.
            GET FIRST lq NO-LOCK.
            DO WHILE AVAILABLE(LEDNINGSDATA):
               RUN summa_UI.
               GET NEXT lq NO-LOCK.
            END.
         END.
         ELSE IF adelvar = 20 THEN DO:
            OPEN QUERY lq FOR EACH LEDNINGSDATA WHERE LEDNINGSDATA.ARTAL = YEAR(bdatum) AND
            LEDNINGSDATA.NATUPPLAGGID1 = 2 AND LEDNINGSDATA.NATUPPLAGGID2 = 2 AND
            LEDNINGSDATA.NATUPPLAGGID3 = 5 AND LEDNINGSDATA.NATUPPLAGGID4 = 0 NO-LOCK.
            GET FIRST lq NO-LOCK.
            DO WHILE AVAILABLE(LEDNINGSDATA):
               RUN summa_UI.
               GET NEXT lq NO-LOCK.
            END.
         END.
         ELSE IF adelvar = 21 THEN DO:
            /*finns ej*/
         END.
         ELSE IF adelvar = 22 THEN DO:
            OPEN QUERY lq FOR EACH LEDNINGSDATA WHERE LEDNINGSDATA.ARTAL = YEAR(bdatum) AND
            LEDNINGSDATA.NATUPPLAGGID1 = 2 AND LEDNINGSDATA.NATUPPLAGGID2 = 2 AND
            LEDNINGSDATA.NATUPPLAGGID3 = 9 AND LEDNINGSDATA.NATUPPLAGGID4 = 0 NO-LOCK.
            GET FIRST lq NO-LOCK.
            DO WHILE AVAILABLE(LEDNINGSDATA):
               RUN summa_UI.
               GET NEXT lq NO-LOCK.
            END.
         END.
         ELSE IF adelvar = 23 THEN DO:
            OPEN QUERY lq FOR EACH LEDNINGSDATA WHERE LEDNINGSDATA.ARTAL = YEAR(bdatum) AND
            LEDNINGSDATA.NATUPPLAGGID1 = 2 AND LEDNINGSDATA.NATUPPLAGGID2 = 2 AND
            LEDNINGSDATA.NATUPPLAGGID3 = 10 AND LEDNINGSDATA.NATUPPLAGGID4 = 0 NO-LOCK.
            GET FIRST lq NO-LOCK.
            DO WHILE AVAILABLE(LEDNINGSDATA):
               RUN summa_UI.
               GET NEXT lq NO-LOCK.
            END.
         END.
         ELSE IF adelvar = 24 THEN DO:
            /*finns ej*/
         END.             
      END.
      ELSE DO:
         RUN distrikt_UI.         
      END.
   END.

PROCEDURE distrikt_UI:   
   IF adelvar = 1 THEN DO:
      OPEN QUERY lq FOR EACH LEDNINGSDATA WHERE LEDNINGSDATA.ARTAL = YEAR(bdatum) AND
      LEDNINGSDATA.DISTRIKT = distvar AND LEDNINGSDATA.NATUPPLAGGID1 = 3 AND LEDNINGSDATA.NATUPPLAGGID2 = 3 AND
      LEDNINGSDATA.NATUPPLAGGID3 = 0 AND LEDNINGSDATA.NATUPPLAGGID4 = 0 NO-LOCK. 
      GET FIRST lq NO-LOCK.
      DO WHILE AVAILABLE(LEDNINGSDATA):
         RUN summa_UI.
         GET NEXT lq NO-LOCK.
      END.
   END.
   ELSE IF adelvar = 2 THEN DO:
      OPEN QUERY lq FOR EACH LEDNINGSDATA WHERE LEDNINGSDATA.ARTAL = YEAR(bdatum) AND
      LEDNINGSDATA.DISTRIKT = distvar AND LEDNINGSDATA.NATUPPLAGGID1 = 3 AND LEDNINGSDATA.NATUPPLAGGID2 = 4 AND
      LEDNINGSDATA.NATUPPLAGGID3 = 0 AND LEDNINGSDATA.NATUPPLAGGID4 = 0 NO-LOCK.
      GET FIRST lq NO-LOCK.
      DO WHILE AVAILABLE(LEDNINGSDATA):
         RUN summa_UI.
         GET NEXT lq NO-LOCK.
      END.
   END.
   ELSE IF adelvar = 3 THEN DO:
      OPEN QUERY lq FOR EACH LEDNINGSDATA WHERE LEDNINGSDATA.ARTAL = YEAR(bdatum) AND
      LEDNINGSDATA.DISTRIKT = distvar AND LEDNINGSDATA.NATUPPLAGGID1 = 3 AND LEDNINGSDATA.NATUPPLAGGID2 = 5 AND
      LEDNINGSDATA.NATUPPLAGGID3 = 0 AND LEDNINGSDATA.NATUPPLAGGID4 = 0 NO-LOCK.
      GET FIRST lq NO-LOCK.
      DO WHILE AVAILABLE(LEDNINGSDATA):
         RUN summa_UI.
         GET NEXT lq NO-LOCK.
      END.
   END.
   ELSE IF adelvar = 4 THEN DO:
      OPEN QUERY lq FOR EACH LEDNINGSDATA WHERE LEDNINGSDATA.ARTAL = YEAR(bdatum) AND
      LEDNINGSDATA.DISTRIKT = distvar AND LEDNINGSDATA.NATUPPLAGGID1 = 3 AND LEDNINGSDATA.NATUPPLAGGID2 = 7 AND
      LEDNINGSDATA.NATUPPLAGGID3 = 13 AND LEDNINGSDATA.NATUPPLAGGID4 = 0 NO-LOCK.
      GET FIRST lq NO-LOCK.
      DO WHILE AVAILABLE(LEDNINGSDATA):
         RUN summa_UI.
         GET NEXT lq NO-LOCK.
      END.
   END.
   ELSE IF adelvar = 5 THEN DO:
      OPEN QUERY lq FOR EACH LEDNINGSDATA WHERE LEDNINGSDATA.ARTAL = YEAR(bdatum) AND
      LEDNINGSDATA.DISTRIKT = distvar AND LEDNINGSDATA.NATUPPLAGGID1 = 3 AND LEDNINGSDATA.NATUPPLAGGID2 = 7 AND
      LEDNINGSDATA.NATUPPLAGGID3 = 11 AND LEDNINGSDATA.NATUPPLAGGID4 = 0 NO-LOCK.
      GET FIRST lq NO-LOCK.
      DO WHILE AVAILABLE(LEDNINGSDATA):
         RUN summa_UI.
         GET NEXT lq NO-LOCK.
      END.
   END.
   ELSE IF adelvar = 6 THEN DO:
      OPEN QUERY lq FOR EACH LEDNINGSDATA WHERE LEDNINGSDATA.ARTAL = YEAR(bdatum) AND
      LEDNINGSDATA.DISTRIKT = distvar AND LEDNINGSDATA.NATUPPLAGGID1 = 3 AND LEDNINGSDATA.NATUPPLAGGID2 = 7 AND
      LEDNINGSDATA.NATUPPLAGGID3 = 12 AND LEDNINGSDATA.NATUPPLAGGID4 = 0 NO-LOCK.
      GET FIRST lq NO-LOCK.
      DO WHILE AVAILABLE(LEDNINGSDATA):
         RUN summa_UI.
         GET NEXT lq NO-LOCK.
      END.
   END.
   ELSE IF adelvar = 7 THEN DO:
      OPEN QUERY lq FOR EACH LEDNINGSDATA WHERE LEDNINGSDATA.ARTAL = YEAR(bdatum) AND
      LEDNINGSDATA.DISTRIKT = distvar AND LEDNINGSDATA.NATUPPLAGGID1 = 3 AND LEDNINGSDATA.NATUPPLAGGID2 = 7 AND
      LEDNINGSDATA.NATUPPLAGGID3 = 14 AND LEDNINGSDATA.NATUPPLAGGID4 = 0 NO-LOCK.
      GET FIRST lq NO-LOCK.
      DO WHILE AVAILABLE(LEDNINGSDATA):
         RUN summa_UI.
         GET NEXT lq NO-LOCK.
      END.
   END.
   ELSE IF adelvar = 8 THEN DO:
      OPEN QUERY lq FOR EACH LEDNINGSDATA WHERE LEDNINGSDATA.ARTAL = YEAR(bdatum) AND
      LEDNINGSDATA.DISTRIKT = distvar AND LEDNINGSDATA.NATUPPLAGGID1 = 3 AND LEDNINGSDATA.NATUPPLAGGID2 = 7 AND
      LEDNINGSDATA.NATUPPLAGGID3 = 15 AND LEDNINGSDATA.NATUPPLAGGID4 = 0 NO-LOCK.
      GET FIRST lq NO-LOCK.
      DO WHILE AVAILABLE(LEDNINGSDATA):
         RUN summa_UI.
         GET NEXT lq NO-LOCK.
      END.
   END.
   ELSE IF adelvar = 9 THEN DO:
      OPEN QUERY lq FOR EACH LEDNINGSDATA WHERE LEDNINGSDATA.ARTAL = YEAR(bdatum) AND
      LEDNINGSDATA.DISTRIKT = distvar AND LEDNINGSDATA.NATUPPLAGGID1 = 3 AND LEDNINGSDATA.NATUPPLAGGID2 = 7 AND
      LEDNINGSDATA.NATUPPLAGGID3 = 16 AND LEDNINGSDATA.NATUPPLAGGID4 = 0 NO-LOCK.
      GET FIRST lq NO-LOCK.
      DO WHILE AVAILABLE(LEDNINGSDATA):
         RUN summa_UI.
         GET NEXT lq NO-LOCK.
      END.
   END.
   ELSE IF adelvar = 10 THEN DO:
      OPEN QUERY lq FOR EACH LEDNINGSDATA WHERE LEDNINGSDATA.ARTAL = YEAR(bdatum) AND
      LEDNINGSDATA.DISTRIKT = distvar AND LEDNINGSDATA.NATUPPLAGGID1 = 3 AND LEDNINGSDATA.NATUPPLAGGID2 = 7 AND
      LEDNINGSDATA.NATUPPLAGGID3 = 17 AND LEDNINGSDATA.NATUPPLAGGID4 = 0 NO-LOCK.
      GET FIRST lq NO-LOCK.
      DO WHILE AVAILABLE(LEDNINGSDATA):
         RUN summa_UI.
         GET NEXT lq NO-LOCK.
      END.
   END.
   ELSE IF adelvar = 11 THEN DO:
      OPEN QUERY lq FOR EACH LEDNINGSDATA WHERE LEDNINGSDATA.ARTAL = YEAR(bdatum) AND
      LEDNINGSDATA.DISTRIKT = distvar AND LEDNINGSDATA.NATUPPLAGGID1 = 3 AND LEDNINGSDATA.NATUPPLAGGID2 = 7 AND
      LEDNINGSDATA.NATUPPLAGGID3 = 18 AND LEDNINGSDATA.NATUPPLAGGID4 = 0 NO-LOCK.
      GET FIRST lq NO-LOCK.
      DO WHILE AVAILABLE(LEDNINGSDATA):
         RUN summa_UI.
         GET NEXT lq NO-LOCK.
      END.
   END.
   ELSE IF adelvar = 12 THEN DO:
      OPEN QUERY lq FOR EACH LEDNINGSDATA WHERE LEDNINGSDATA.ARTAL = YEAR(bdatum) AND
      LEDNINGSDATA.DISTRIKT = distvar AND LEDNINGSDATA.NATUPPLAGGID1 = 3 AND LEDNINGSDATA.NATUPPLAGGID2 = 7 AND
      LEDNINGSDATA.NATUPPLAGGID3 = 18 AND LEDNINGSDATA.NATUPPLAGGID4 = 0 NO-LOCK.
      GET FIRST lq NO-LOCK.
      DO WHILE AVAILABLE(LEDNINGSDATA):
         RUN summa_UI.
         GET NEXT lq NO-LOCK.
      END.
   END.
   ELSE IF adelvar = 13 THEN DO:
      OPEN QUERY lq FOR EACH LEDNINGSDATA WHERE LEDNINGSDATA.ARTAL = YEAR(bdatum) AND
      LEDNINGSDATA.DISTRIKT = distvar AND LEDNINGSDATA.NATUPPLAGGID1 = 2 AND LEDNINGSDATA.NATUPPLAGGID2 = 1 AND
      LEDNINGSDATA.NATUPPLAGGID3 = 1 AND LEDNINGSDATA.NATUPPLAGGID4 = 0 NO-LOCK.
      GET FIRST lq NO-LOCK.
      DO WHILE AVAILABLE(LEDNINGSDATA):
         RUN summa_UI.
         GET NEXT lq NO-LOCK.
      END.
   END.
   ELSE IF adelvar = 14 THEN DO:
      OPEN QUERY lq FOR EACH LEDNINGSDATA WHERE LEDNINGSDATA.ARTAL = YEAR(bdatum) AND
      LEDNINGSDATA.DISTRIKT = distvar AND LEDNINGSDATA.NATUPPLAGGID1 = 2 AND LEDNINGSDATA.NATUPPLAGGID2 = 1 AND
      LEDNINGSDATA.NATUPPLAGGID3 = 6 AND LEDNINGSDATA.NATUPPLAGGID4 = 0 NO-LOCK.
      GET FIRST lq NO-LOCK.
      DO WHILE AVAILABLE(LEDNINGSDATA):
         RUN summa_UI.
         GET NEXT lq NO-LOCK.
      END.
   END.
   ELSE IF adelvar = 15 THEN DO:
      OPEN QUERY lq FOR EACH LEDNINGSDATA WHERE LEDNINGSDATA.ARTAL = YEAR(bdatum) AND
      LEDNINGSDATA.DISTRIKT = distvar AND LEDNINGSDATA.NATUPPLAGGID1 = 2 AND LEDNINGSDATA.NATUPPLAGGID2 = 1 AND
      LEDNINGSDATA.NATUPPLAGGID3 = 7 AND LEDNINGSDATA.NATUPPLAGGID4 = 0 NO-LOCK.
      GET FIRST lq NO-LOCK.
      DO WHILE AVAILABLE(LEDNINGSDATA):
         RUN summa_UI.
         GET NEXT lq NO-LOCK.
      END.
   END.
   ELSE IF adelvar = 16 THEN DO:
      OPEN QUERY lq FOR EACH LEDNINGSDATA WHERE LEDNINGSDATA.ARTAL = YEAR(bdatum) AND
      LEDNINGSDATA.DISTRIKT = distvar AND LEDNINGSDATA.NATUPPLAGGID1 = 2 AND LEDNINGSDATA.NATUPPLAGGID2 = 1 AND
      LEDNINGSDATA.NATUPPLAGGID3 = 8 AND LEDNINGSDATA.NATUPPLAGGID4 = 0 NO-LOCK.
      GET FIRST lq NO-LOCK.
      DO WHILE AVAILABLE(LEDNINGSDATA):
         RUN summa_UI.
         GET NEXT lq NO-LOCK.
      END.
   END.
   ELSE IF adelvar = 17 THEN DO:
      /*finns ej*/
   END.
   ELSE IF adelvar = 18 THEN DO:
      /*finns ej*/
   END.
   ELSE IF adelvar = 19 THEN DO:
      OPEN QUERY lq FOR EACH LEDNINGSDATA WHERE LEDNINGSDATA.ARTAL = YEAR(bdatum) AND
      LEDNINGSDATA.DISTRIKT = distvar AND LEDNINGSDATA.NATUPPLAGGID1 = 2 AND LEDNINGSDATA.NATUPPLAGGID2 = 2 AND
      LEDNINGSDATA.NATUPPLAGGID3 = 3 AND LEDNINGSDATA.NATUPPLAGGID4 = 0 NO-LOCK.
      GET FIRST lq NO-LOCK.
      DO WHILE AVAILABLE(LEDNINGSDATA):
         RUN summa_UI.
         GET NEXT lq NO-LOCK.
      END.
   END.
   ELSE IF adelvar = 20 THEN DO:
      OPEN QUERY lq FOR EACH LEDNINGSDATA WHERE LEDNINGSDATA.ARTAL = YEAR(bdatum) AND
      LEDNINGSDATA.DISTRIKT = distvar AND LEDNINGSDATA.NATUPPLAGGID1 = 2 AND LEDNINGSDATA.NATUPPLAGGID2 = 2 AND
      LEDNINGSDATA.NATUPPLAGGID3 = 5 AND LEDNINGSDATA.NATUPPLAGGID4 = 0 NO-LOCK.
      GET FIRST lq NO-LOCK.
      DO WHILE AVAILABLE(LEDNINGSDATA):
         RUN summa_UI.
         GET NEXT lq NO-LOCK.
      END.
   END.
   ELSE IF adelvar = 21 THEN DO:
      /*finns ej*/
   END.
   ELSE IF adelvar = 22 THEN DO:
      OPEN QUERY lq FOR EACH LEDNINGSDATA WHERE LEDNINGSDATA.ARTAL = YEAR(bdatum) AND
      LEDNINGSDATA.DISTRIKT = distvar AND LEDNINGSDATA.NATUPPLAGGID1 = 2 AND LEDNINGSDATA.NATUPPLAGGID2 = 2 AND
      LEDNINGSDATA.NATUPPLAGGID3 = 9 AND LEDNINGSDATA.NATUPPLAGGID4 = 0 NO-LOCK.
      GET FIRST lq NO-LOCK.
      DO WHILE AVAILABLE(LEDNINGSDATA):
         RUN summa_UI.
         GET NEXT lq NO-LOCK.
      END.
   END.
   ELSE IF adelvar = 23 THEN DO:
      OPEN QUERY lq FOR EACH LEDNINGSDATA WHERE LEDNINGSDATA.ARTAL = YEAR(bdatum) AND
      LEDNINGSDATA.DISTRIKT = distvar AND LEDNINGSDATA.DISTRIKT = distvar AND LEDNINGSDATA.NATUPPLAGGID1 = 2 AND LEDNINGSDATA.NATUPPLAGGID2 = 2 AND
      LEDNINGSDATA.NATUPPLAGGID3 = 10 AND LEDNINGSDATA.NATUPPLAGGID4 = 0 NO-LOCK.
      GET FIRST lq NO-LOCK.
      DO WHILE AVAILABLE(LEDNINGSDATA):
         RUN summa_UI.
         GET NEXT lq NO-LOCK.
      END.
   END.
   ELSE IF adelvar = 24 THEN DO:
      /*finns ej*/
   END.
END PROCEDURE.

PROCEDURE summa_UI.
   CREATE leddata_temp.
   ASSIGN
   leddata_temp.ADELID = adelvar
   leddata_temp.ANTAL = LEDNINGSDATA.LANGD.
   IF LEDNINGSDATA.SPANID = 1 THEN leddata_temp.SPANID = 5.   
   ELSE IF LEDNINGSDATA.SPANID = 12 THEN leddata_temp.SPANID = 6.
   ELSE IF LEDNINGSDATA.SPANID = 18 THEN leddata_temp.SPANID = 7.
   ELSE IF LEDNINGSDATA.SPANID = 19 THEN leddata_temp.SPANID = 8.
   ELSE IF LEDNINGSDATA.SPANID = 20 THEN leddata_temp.SPANID = 9.
   ELSE IF LEDNINGSDATA.SPANID = 21 THEN leddata_temp.SPANID = 10.
   ELSE IF LEDNINGSDATA.SPANID = 22 THEN leddata_temp.SPANID = 11.
   ELSE IF LEDNINGSDATA.SPANID = 23 THEN leddata_temp.SPANID = 13.
   ELSE IF LEDNINGSDATA.SPANID = 24 THEN leddata_temp.SPANID = 14.
   ELSE IF LEDNINGSDATA.SPANID = 3 THEN leddata_temp.SPANID = 15.

END PROCEDURE.
