/*STORDEL.P DELETE VID KOPIERING AV GRUNDDATA FRÅN ETT ÅR TILL ETT ANNAT*/
DEFINE INPUT PARAMETER distvar LIKE STORDISTRIKT.DISTRIKTID NO-UNDO.   
DEFINE INPUT PARAMETER arvar LIKE STORDISTRIKT.ARTAL NO-UNDO.
DEFINE INPUT PARAMETER distvar2 LIKE STORDISTRIKT.DISTRIKTID NO-UNDO.   
DEFINE INPUT PARAMETER arvar2 LIKE STORDISTRIKT.ARTAL NO-UNDO.

DEFINE BUFFER kbuff FOR KUNDSTOR.
DEFINE BUFFER lbuff FOR LEDNINGSDATA.

   OPEN QUERY aq FOR EACH KUNDSTOR WHERE KUNDSTOR.DISTRIKTID = distvar2 AND
   KUNDSTOR.ARTAL = arvar2 NO-LOCK.
   DO TRANSACTION:
      GET FIRST aq NO-LOCK.
      IF AVAILABLE KUNDSTOR THEN DO:
         CREATE kbuff.
         ASSIGN
         kbuff.DISTRIKTID = distvar
         kbuff.ARTAL = arvar
         kbuff.SPANID = KUNDSTOR.SPANID 
         kbuff.INDATUM = KUNDSTOR.INDATUM 
         kbuff.ANTALLUFT = KUNDSTOR.ANTALLUFT 
         kbuff.ANTALKUNDER = KUNDSTOR.ANTALKUNDER 
         kbuff.ANTALKABEL = KUNDSTOR.ANTALKABEL 
         kbuff.ANTALBLAND = KUNDSTOR.ANTALBLAND.
      END.
   END.
   REPEAT:
      DO TRANSACTION:
         GET NEXT aq NO-LOCK.
         IF AVAILABLE KUNDSTOR THEN DO:
            CREATE kbuff.
            ASSIGN
            kbuff.DISTRIKTID = distvar
            kbuff.ARTAL = arvar
            kbuff.SPANID = KUNDSTOR.SPANID 
            kbuff.INDATUM = KUNDSTOR.INDATUM 
            kbuff.ANTALLUFT = KUNDSTOR.ANTALLUFT 
            kbuff.ANTALKUNDER = KUNDSTOR.ANTALKUNDER 
            kbuff.ANTALKABEL = KUNDSTOR.ANTALKABEL 
            kbuff.ANTALBLAND = KUNDSTOR.ANTALBLAND.
         END.
         ELSE LEAVE.
      END.
   END.
   CLOSE QUERY aq.

   OPEN QUERY bq FOR EACH LEDNINGSDATA WHERE LEDNINGSDATA.DISTRIKTID = distvar2 AND
   LEDNINGSDATA.ARTAL = arvar2 NO-LOCK.
   DO TRANSACTION:
      GET FIRST bq NO-LOCK.
      IF AVAILABLE LEDNINGSDATA THEN DO:
         CREATE lbuff.
         ASSIGN
         lbuff.DISTRIKTID = distvar
         lbuff.ARTAL = arvar
         lbuff.SPANID = LEDNINGSDATA.SPANID 
         lbuff.NATUPPLAGGID4 = LEDNINGSDATA.NATUPPLAGGID4 
         lbuff.NATUPPLAGGID3 = LEDNINGSDATA.NATUPPLAGGID3 
         lbuff.NATUPPLAGGID2 = LEDNINGSDATA.NATUPPLAGGID2 
         lbuff.NATUPPLAGGID1 = LEDNINGSDATA.NATUPPLAGGID1 
         lbuff.LANGDLUFT = LEDNINGSDATA.LANGDLUFT 
         lbuff.LANGDKABEL = LEDNINGSDATA.LANGDKABEL 
         lbuff.LANGDBLAND = LEDNINGSDATA.LANGDBLAND 
         lbuff.LANGD = LEDNINGSDATA.LANGD 
         lbuff.INDATUM = LEDNINGSDATA.INDATUM.
      END.          
   END.
   REPEAT:
      DO TRANSACTION:
         GET NEXT bq NO-LOCK.
         IF AVAILABLE LEDNINGSDATA THEN DO:
            CREATE lbuff.
            ASSIGN
            lbuff.DISTRIKTID = distvar
            lbuff.ARTAL = arvar
            lbuff.SPANID = LEDNINGSDATA.SPANID 
            lbuff.NATUPPLAGGID4 = LEDNINGSDATA.NATUPPLAGGID4 
            lbuff.NATUPPLAGGID3 = LEDNINGSDATA.NATUPPLAGGID3 
            lbuff.NATUPPLAGGID2 = LEDNINGSDATA.NATUPPLAGGID2 
            lbuff.NATUPPLAGGID1 = LEDNINGSDATA.NATUPPLAGGID1 
            lbuff.LANGDLUFT = LEDNINGSDATA.LANGDLUFT 
            lbuff.LANGDKABEL = LEDNINGSDATA.LANGDKABEL 
            lbuff.LANGDBLAND = LEDNINGSDATA.LANGDBLAND 
            lbuff.LANGD = LEDNINGSDATA.LANGD 
            lbuff.INDATUM = LEDNINGSDATA.INDATUM.
         END.
         ELSE LEAVE.
      END.
   END.
   CLOSE QUERY bq.
