/*STORDEL.P DELETE VID KOPIERING AV GRUNDDATA FRÅN ETT ÅR TILL ETT ANNAT*/
DEFINE INPUT PARAMETER distvar LIKE STORDISTRIKT.DISTRIKTID NO-UNDO.   
DEFINE INPUT PARAMETER arvar LIKE STORDISTRIKT.ARTAL NO-UNDO.

   OPEN QUERY aq FOR EACH KUNDSTOR WHERE KUNDSTOR.DISTRIKTID = distvar AND
   KUNDSTOR.ARTAL = arvar NO-LOCK.
   GET FIRST aq EXCLUSIVE-LOCK.
   DO WHILE AVAILABLE(KUNDSTOR):
      DELETE KUNDSTOR.
      GET NEXT aq EXCLUSIVE-LOCK.
   END.
   CLOSE QUERY aq.

   OPEN QUERY bq FOR EACH LEDNINGSDATA WHERE LEDNINGSDATA.DISTRIKTID = distvar AND
   LEDNINGSDATA.ARTAL = arvar NO-LOCK.
   GET FIRST bq EXCLUSIVE-LOCK.
   DO WHILE AVAILABLE(LEDNINGSDATA):
      DELETE LEDNINGSDATA.
      GET NEXT bq EXCLUSIVE-LOCK.
   END.
   CLOSE QUERY bq.
