/*XGLOM2.P*/
{AMERICANEUROPEAN.I}
DEFINE VARIABLE KALLE AS CHARACTER NO-UNDO.
KALLE = SESSION:TEMP-DIRECTORY.
KALLE = KALLE + "ELPOOL.TXT". 
OUTPUT TO VALUE(KALLE).
OPEN QUERY AQ FOR EACH STORDISTRIKT NO-LOCK.
DO TRANSACTION:
   GET FIRST AQ EXCLUSIVE-LOCK.
   EXPORT STORDISTRIKT.
END.
REPEAT:
   DO TRANSACTION:
      GET NEXT AQ EXCLUSIVE-LOCK.
      IF AVAILABLE STORDISTRIKT THEN EXPORT STORDISTRIKT.
      ELSE LEAVE.
   END.
END.
OUTPUT CLOSE.
MESSAGE SESSION:TEMP-DIRECTORY + "\ELPOOL.TXT".
{EUROPEANAMERICAN.I}
/*
FOR EACH STORDISTRIKT WHERE STORDISTRIKT.ARTAL = 0 EXCLUSIVE-LOCK:
   ASSIGN STORDISTRIKT.ARTAL = 2005.
END.
FOR EACH STORDISTRIKT WHERE STORDISTRIKT.ARTAL = ? EXCLUSIVE-LOCK:
   ASSIGN STORDISTRIKT.ARTAL = 2005.
END.
*/

