/*XGLOM.P INLÄSNING AV MODERDARWINS gruddata ledningar*/       
DEFINE NEW SHARED VARIABLE quotervar AS CHARACTER FORMAT "X(256)" NO-UNDO.
DEFINE VARIABLE dlcvar AS CHARACTER NO-UNDO.
DEFINE VARIABLE wtidvar AS CHARACTER NO-UNDO.



DEFINE VARIABLE musz AS LOGICAL NO-UNDO.

DEFINE VARIABLE rad AS INTEGER NO-UNDO.
DEFINE VARIABLE prognamn AS CHARACTER FORMAT "X(20)" NO-UNDO.
DEFINE VARIABLE prognamndat AS CHARACTER FORMAT "X(20)" NO-UNDO.
DEFINE VARIABLE prognamnque AS CHARACTER FORMAT "X(20)" NO-UNDO.                
DEFINE VARIABLE words AS CHARACTER FORMAT "X(132)" NO-UNDO.
DEFINE VARIABLE kommando AS CHARACTER FORMAT "X(132)" NO-UNDO.
DEFINE VARIABLE kommandoprog AS CHARACTER FORMAT "X(20)" NO-UNDO.
DEFINE VARIABLE satsvar AS CHARACTER FORMAT "X(11)" NO-UNDO.
DEFINE VARIABLE enrvar AS CHARACTER FORMAT "X(11)" NO-UNDO.
DEFINE VARIABLE melvar AS INTEGER NO-UNDO.
DEFINE VARIABLE melvar2 AS INTEGER NO-UNDO.
DEFINE VARIABLE langd AS INTEGER NO-UNDO.
DEFINE VARIABLE pos1 AS INTEGER NO-UNDO. 
DEFINE VARIABLE filnamn AS CHARACTER NO-UNDO.
DEFINE VARIABLE nrvar AS INTEGER NO-UNDO.
DEFINE VARIABLE nat1 AS INTEGER NO-UNDO.
DEFINE VARIABLE nat2 AS INTEGER NO-UNDO.
DEFINE VARIABLE nat3 AS INTEGER NO-UNDO.
DEFINE VARIABLE nat4 AS INTEGER NO-UNDO.

DEFINE TEMP-TABLE tidin
   FIELD B1                 AS INTEGER 
   FIELD B2                 AS CHARACTER
   FIELD B3                 AS INTEGER 
   FIELD B4                 AS CHARACTER
   FIELD B5                 AS INTEGER 
   FIELD B6                 AS INTEGER
   FIELD B7                 AS INTEGER
   FIELD B8                 AS INTEGER
   FIELD B9                 AS CHARACTER.
   
DEFINE TEMP-TABLE infil
   FIELD PROGNAMN AS CHARACTER FORMAT "X(78)" 
   INDEX PRO IS PRIMARY PROGNAMN.
   
DEFINE TEMP-TABLE intid
   FIELD TIN AS CHARACTER FORMAT "X(78)" .
   
DEFINE TEMP-TABLE temp_TEXT
   FIELD PROGNAMN AS CHARACTER FORMAT "X(100)".   

DEFINE BUFFER distbuff FOR STORDISTRIKT.   

{muswait.i}
{AMERICANEUROPEAN.I}         
RUN in_UI.
{EUROPEANAMERICAN.I}
{musarrow.i}

PROCEDURE in_UI: 
   FOR EACH intid:
      DELETE intid.
   END.
   FOR EACH tidin:
      DELETE tidin.
   END.    
   
   filnamn = "\\pc112\delad\elpool\elpnj\darwin\glomt.txt".
   RUN PROVAG.P.
   ASSIGN
   dlcvar = dlcvar + "QUOTER.EXE"
   wtidvar = wtidvar + "kabpris.q".   
   
   OS-COMMAND SILENT VALUE(dlcvar)
   VALUE(filnamn) > VALUE(wtidvar).   
   INPUT FROM VALUE(wtidvar) NO-ECHO.    
   /*CONVERT TARGET "iso8859-1" SOURCE "ibm850" NO-ECHO.
   iso8859-1 swedish-7-bit ibm850"*/
   REPEAT:
      DO TRANSACTION: 
         SET words VIEW-AS EDITOR INNER-CHARS 78 INNER-LINES 80 WITH FRAME DDD WIDTH 80.   
         CREATE intid.   
         ASSIGN intid.TIN = words.   
      END.
   END.
   INPUT CLOSE.               
   OUTPUT TO VALUE(wtidvar).
   FOR EACH intid:          
      PUT UNFORMATTED intid.TIN SKIP.     
   END.
   OUTPUT CLOSE.
   INPUT FROM VALUE(wtidvar) NO-ECHO.
   REPEAT:
      DO TRANSACTION: 
         CREATE tidin.
         ASSIGN.
         IMPORT DELIMITER ";" tidin   NO-ERROR.
      END.               
   END.   
   RUN skapasats_UI.           
   OS-DELETE VALUE(wtidvar).
END PROCEDURE.

PROCEDURE skapasats_UI:   
   FOR EACH tidin NO-LOCK:
      FIND FIRST AVDELNING WHERE AVDELNING.AVDELNINGNR = tidin.B1 NO-LOCK NO-ERROR.
      IF AVAILABLE AVDELNING THEN DO:
         FIND FIRST STORDISTRIKT WHERE STORDISTRIKT.AVDELNINGNR = tidin.B1 AND
         STORDISTRIKT.VIDISTRIKT = tidin.B2 AND STORDISTRIKT.ARTAL = tidin.B3
         NO-LOCK NO-ERROR.
         IF AVAILABLE STORDISTRIKT THEN DO:         
            RUN skapakund_UI.
         END.
         ELSE DO:
            CREATE temp_text.
            ASSIGN
            temp_text.PROGNAMN = "dist SAKNAS" + STRING(tidin.B1) + ";" + tidin.B2 + ";" + STRING(tidin.B3) + ";" +
            tidin.B4 + ";" + STRING(tidin.B5) + ";" + STRING(tidin.B6) + ";"
            + STRING(tidin.B7) + ";" + STRING(tidin.B8) + ";" + tidin.B9.
         END.   
      END.
      ELSE DO:
         CREATE temp_text.
         ASSIGN
         temp_text.PROGNAMN = "FORE SAKNAS" + STRING(tidin.B1) + ";" + tidin.B2 + ";" + STRING(tidin.B3) + ";" +
         tidin.B4 + ";" + STRING(tidin.B5) + ";" + STRING(tidin.B6) + ";"
         + STRING(tidin.B7) + ";" + STRING(tidin.B8) + ";" + tidin.B9. 
      END.   
   END.   
   OUTPUT TO "\\pc112\DELAD\FELglom.txt" 
   APPEND CONVERT TARGET "iso8859-1" SOURCE "iso8859-1" 
   NO-ECHO.
   FOR EACH temp_TEXT NO-LOCK.
      PUT UNFORMATTED temp_TEXT.PROGNAMN SKIP.
   END.
END PROCEDURE.

PROCEDURE skapakund_UI:   
   FIND FIRST INLASTAB WHERE INLASTAB.INKOD = "D" AND INLASTAB.INKODTYP = "1" AND
   INLASTAB.INKODPOSCH = SUBSTRING(tidin.B4,3,2) USE-INDEX INKOD
   NO-LOCK NO-ERROR.
   IF AVAILABLE INLASTAB THEN DO:
   FIND FIRST SPANNINGSNIV WHERE SPANNINGSNIV.INKODID = INLASTAB.INKODID
   NO-LOCK NO-ERROR.
   RUN textkoll_UI.     
   END.
END PROCEDURE.   

PROCEDURE textkoll_UI:
   IF tidin.B9 = "Regionstation" THEN DO:
      ASSIGN
      nat1 = 3
      nat2 = 3
      nat3 = 0
      nat4 = 0.
      FIND FIRST LEDNINGSDATA WHERE LEDNINGSDATA.DISTRIKTID = STORDISTRIKT.DISTRIKTID AND
      LEDNINGSDATA.SPANID = SPANNINGSNIV.SPANID AND LEDNINGSDATA.ARTAL = STORDISTRIKT.ARTAL
      AND LEDNINGSDATA.NATUPPLAGGID1 = nat1 AND LEDNINGSDATA.NATUPPLAGGID2 = nat2 and
      LEDNINGSDATA.NATUPPLAGGID3 = nat3 AND LEDNINGSDATA.NATUPPLAGGID4 = nat4 NO-LOCK NO-ERROR.
      IF NOT AVAILABLE LEDNINGSDATA THEN DO:      
         CREATE LEDNINGSDATA.
         ASSIGN
         LEDNINGSDATA.DISTRIKTID = STORDISTRIKT.DISTRIKTID
         LEDNINGSDATA.ARTAL = STORDISTRIKT.ARTAL
         LEDNINGSDATA.LANGDLUFT = tidin.B6
         LEDNINGSDATA.LANGDBLAND = tidin.B5
         LEDNINGSDATA.LANGDKABEL = tidin.B7
         LEDNINGSDATA.LANGD = tidin.B8
         LEDNINGSDATA.SPANID = SPANNINGSNIV.SPANID
         LEDNINGSDATA.NATUPPLAGGID1 = nat1
         LEDNINGSDATA.NATUPPLAGGID2 = nat2
         LEDNINGSDATA.NATUPPLAGGID3 = nat3
         LEDNINGSDATA.NATUPPLAGGID4 = nat4.
      END.
   END.
   ELSE IF tidin.B9 = "Fördelningsstation" THEN DO:
      ASSIGN
      nat1 = 3
      nat2 = 4
      nat3 = 0
      nat4 = 0.
      FIND FIRST LEDNINGSDATA WHERE LEDNINGSDATA.DISTRIKTID = STORDISTRIKT.DISTRIKTID AND
      LEDNINGSDATA.SPANID = SPANNINGSNIV.SPANID AND LEDNINGSDATA.ARTAL = STORDISTRIKT.ARTAL
      AND LEDNINGSDATA.NATUPPLAGGID1 = nat1 AND LEDNINGSDATA.NATUPPLAGGID2 = nat2 and
      LEDNINGSDATA.NATUPPLAGGID3 = nat3 AND LEDNINGSDATA.NATUPPLAGGID4 = nat4 NO-LOCK NO-ERROR.
      IF NOT AVAILABLE LEDNINGSDATA THEN DO:      
         CREATE LEDNINGSDATA.
         ASSIGN
         LEDNINGSDATA.DISTRIKTID = STORDISTRIKT.DISTRIKTID
         LEDNINGSDATA.ARTAL = STORDISTRIKT.ARTAL
         LEDNINGSDATA.LANGDLUFT = tidin.B6
         LEDNINGSDATA.LANGDBLAND = tidin.B5
         LEDNINGSDATA.LANGDKABEL = tidin.B7
         LEDNINGSDATA.LANGD = tidin.B8
         LEDNINGSDATA.SPANID = SPANNINGSNIV.SPANID
         LEDNINGSDATA.NATUPPLAGGID1 = nat1
         LEDNINGSDATA.NATUPPLAGGID2 = nat2
         LEDNINGSDATA.NATUPPLAGGID3 = nat3
         LEDNINGSDATA.NATUPPLAGGID4 = nat4.
      END.
   END.
   ELSE IF tidin.B9 = "Kopplingsstation" THEN DO:
      ASSIGN
      nat1 = 3
      nat2 = 5
      nat3 = 0
      nat4 = 0.
      FIND FIRST LEDNINGSDATA WHERE LEDNINGSDATA.DISTRIKTID = STORDISTRIKT.DISTRIKTID AND
      LEDNINGSDATA.SPANID = SPANNINGSNIV.SPANID AND LEDNINGSDATA.ARTAL = STORDISTRIKT.ARTAL
      AND LEDNINGSDATA.NATUPPLAGGID1 = nat1 AND LEDNINGSDATA.NATUPPLAGGID2 = nat2 and
      LEDNINGSDATA.NATUPPLAGGID3 = nat3 AND LEDNINGSDATA.NATUPPLAGGID4 = nat4 NO-LOCK NO-ERROR.
      IF NOT AVAILABLE LEDNINGSDATA THEN DO:      
         CREATE LEDNINGSDATA.
         ASSIGN
         LEDNINGSDATA.DISTRIKTID = STORDISTRIKT.DISTRIKTID
         LEDNINGSDATA.ARTAL = STORDISTRIKT.ARTAL
         LEDNINGSDATA.LANGDLUFT = tidin.B6
         LEDNINGSDATA.LANGDBLAND = tidin.B5
         LEDNINGSDATA.LANGDKABEL = tidin.B7
         LEDNINGSDATA.LANGD = tidin.B8
         LEDNINGSDATA.SPANID = SPANNINGSNIV.SPANID
         LEDNINGSDATA.NATUPPLAGGID1 = nat1
         LEDNINGSDATA.NATUPPLAGGID2 = nat2
         LEDNINGSDATA.NATUPPLAGGID3 = nat3
         LEDNINGSDATA.NATUPPLAGGID4 = nat4.
      END.
   END.
   ELSE DO:
      CREATE temp_text.
      ASSIGN
      temp_text.PROGNAMN = "TEXT SAKNAS" + STRING(tidin.B1) + ";" + tidin.B2 + ";" + STRING(tidin.B3) + ";" +
      tidin.B4 + ";" + STRING(tidin.B5) + ";" + STRING(tidin.B6) + ";"
      + STRING(tidin.B7) + ";" + STRING(tidin.B8) + ";" + STRING(tidin.B9).
      DELETE TIDIN.
   END.
END PROCEDURE.
