/*XSKAPTAB.P*/
DEFINE VARIABLE tabn AS CHARACTER NO-UNDO. 
OPEN QUERY fq FOR EACH INLASTAB WHERE INLASTAB.TABNAMN NE ""
NO-LOCK BY INLASTAB.TABNAMN.
GET FIRST fq NO-LOCK.
DO WHILE AVAILABLE(INLASTAB):
   IF tabn NE INLASTAB.TABNAMN THEN DO:
      tabn = INLASTAB.TABNAMN.
      RUN ladda1_UI.     
  END.
  GET NEXT fq NO-LOCK.
     
END.
PROCEDURE ladda1_UI:   
   {AMERICANEUROPEAN.I}
   RUN "XSKAPIN.I" INLASTAB.TABNAMN.
   /*  FUNKAR EJ I RUN TIME KOMPILERAD.*/
  
   {EUROPEANAMERICAN.I}
END PROCEDURE.
