/*XSKLADD2.p*/
/*
FOR EACH ANLAGGNINGSTYP :
   UPDATE ANLAGGNINGSTYP.
END.


FOR EACH ANLAGGNINGSDEL :
   UPDATE ANLAGGNINGSDEL.
END.
FOR EACH FELYTTRING :
   UPDATE FELYTTRING.
END.

FOR EACH GRUNDFELTYP :
   DISPLAY GRUNDFELTYP.
END.


FOR EACH FELORSAK :
   UPDATE FELORSAK.
END.
FOR EACH GRUNDNATSTOR.
   display GRUNDNATSTOR.
END.

FOR EACH NATSTRUKTUR :
   UPDATE NATSTRUKTUR.
END.
*/
FOR EACH SPANNINGSNIV :
   UPDATE SPANNINGSNIV.
END.



/*
FOR EACH BRYTORGAN :
   UPDATE BRYTORGAN.
END.
FOR EACH GRUNDFELTYP :
   UPDATE GRUNDFELTYP.
END.
FOR EACH GRUNDNATSTOR.
   UPDATE GRUNDNATSTOR.
END.
FOR EACH NATTYP :
   UPDATE NATTYP.
END.
FOR EACH RELAINDIKERING :
   UPDATE RELAINDIKERING.
END.
FOR EACH RESERVKRAFTMETOD :
   UPDATE RESERVKRAFTMETOD.
END.
FOR EACH SEKTIONERING :
   UPDATE SEKTIONERING.
END.
FOR EACH STORDRIFTOMR :
   UPDATE STORDRIFTOMR.
END.
FOR EACH STORNINGSTYP :
   UPDATE STORNINGSTYP.
END.
FOR EACH UTLOSNINGSKYDD :
   UPDATE UTLOSNINGSKYDD.
END.
*/
