/*XSKLADD.p*/
FOR EACH INLASTAB :
IF INLASTAB.TABNAMN = 'ANLAGGNINGSDEL' THEN DO:
  CREATE ANLAGGNINGSDEL.
  ASSIGN
  ANLAGGNINGSDEL.INKODID = INLASTAB.INKODID
  ANLAGGNINGSDEL.NAMN = INLASTAB.NAMN.
END.
IF INLASTAB.TABNAMN = 'ANLAGGNINGSTYP' THEN DO:
  CREATE ANLAGGNINGSTYP.
  ASSIGN
  ANLAGGNINGSTYP.INKODID = INLASTAB.INKODID
  ANLAGGNINGSTYP.NAMN = INLASTAB.NAMN.
END.
IF INLASTAB.TABNAMN = 'BRYTORGAN' THEN DO:
  CREATE BRYTORGAN.
  ASSIGN
  BRYTORGAN.INKODID = INLASTAB.INKODID
  BRYTORGAN.NAMN = INLASTAB.NAMN.
END.
IF INLASTAB.TABNAMN = 'FELORSAK' THEN DO:
  CREATE FELORSAK.
  ASSIGN
  FELORSAK.INKODID = INLASTAB.INKODID
  FELORSAK.NAMN = INLASTAB.NAMN.
END.
IF INLASTAB.TABNAMN = 'FELYTTRING' THEN DO:
  CREATE FELYTTRING.
  ASSIGN
  FELYTTRING.INKODID = INLASTAB.INKODID
  FELYTTRING.NAMN = INLASTAB.NAMN.
END.
IF INLASTAB.TABNAMN = 'GRUNDFELTYP' THEN DO:
  CREATE GRUNDFELTYP.
  ASSIGN
  GRUNDFELTYP.INKODID = INLASTAB.INKODID
  GRUNDFELTYP.NAMN = INLASTAB.NAMN.
END.
IF INLASTAB.TABNAMN = 'GRUNDNATSTOR' THEN DO:
  CREATE GRUNDNATSTOR.
  ASSIGN
  GRUNDNATSTOR.INKODID = INLASTAB.INKODID
  GRUNDNATSTOR.NAMN = INLASTAB.NAMN.
END.

IF INLASTAB.TABNAMN = 'NATSTRUKTUR' THEN DO:
  CREATE NATSTRUKTUR.
  ASSIGN
  NATSTRUKTUR.INKODID = INLASTAB.INKODID
  NATSTRUKTUR.NAMN = INLASTAB.NAMN.
END.
IF INLASTAB.TABNAMN = 'NATTYP' THEN DO:
  CREATE NATTYP.
  ASSIGN
  NATTYP.INKODID = INLASTAB.INKODID
  NATTYP.NAMN = INLASTAB.NAMN.
END.
IF INLASTAB.TABNAMN = 'RELAINDIKERING' THEN DO:
  CREATE RELAINDIKERING.
  ASSIGN
  RELAINDIKERING.INKODID = INLASTAB.INKODID
  RELAINDIKERING.NAMN = INLASTAB.NAMN.
END.
IF INLASTAB.TABNAMN = 'RESERVKRAFTMETOD' THEN DO:
  CREATE RESERVKRAFTMETOD.
  ASSIGN
  RESERVKRAFTMETOD.INKODID = INLASTAB.INKODID
  RESERVKRAFTMETOD.NAMN = INLASTAB.NAMN.
END.
IF INLASTAB.TABNAMN = 'SEKTIONERING' THEN DO:
  CREATE SEKTIONERING.
  ASSIGN
  SEKTIONERING.INKODID = INLASTAB.INKODID
  SEKTIONERING.NAMN = INLASTAB.NAMN.
END.
IF INLASTAB.TABNAMN = 'SPANNINGSNIV' THEN DO:
  CREATE SPANNINGSNIV.
  ASSIGN
  SPANNINGSNIV.INKODID = INLASTAB.INKODID
  SPANNINGSNIV.NAMN = INLASTAB.NAMN.
END.
IF INLASTAB.TABNAMN = 'STORDRIFTOMR' THEN DO:
  CREATE STORDRIFTOMR.
  ASSIGN
  STORDRIFTOMR.INKODID = INLASTAB.INKODID
  STORDRIFTOMR.NAMN = INLASTAB.NAMN.
END.
IF INLASTAB.TABNAMN = 'STORNINGSTYP' THEN DO:
  CREATE STORNINGSTYP.
  ASSIGN
  STORNINGSTYP.INKODID = INLASTAB.INKODID
  STORNINGSTYP.NAMN = INLASTAB.NAMN.
END.
IF INLASTAB.TABNAMN = 'UTLOSNINGSKYDD' THEN DO:
  CREATE UTLOSNINGSKYDD.
  ASSIGN
  UTLOSNINGSKYDD.INKODID = INLASTAB.INKODID
  UTLOSNINGSKYDD.NAMN = INLASTAB.NAMN.
END.
END.
