/*XSKLADD3.p*/
FOR EACH NATUPPLAGG1 :
   UPDATE NATUPPLAGG1.
END.
FOR EACH NATUPPLAGG2 :
   UPDATE NATUPPLAGG2.
END.
FOR EACH NATUPPLAGG3 :
   UPDATE NATUPPLAGG3.
END.
FOR EACH NATUPPLAGG4 :
   UPDATE NATUPPLAGG4.
END.
