/*XXT.P*/
{AMERICANEUROPEAN.I}
OUTPUT TO F:\INLAST.TXT.
   FOR EACH INLASTAB NO-LOCK BY INLASTAB.INKOD BY INLASTAB.INKODTYP BY 
INLASTAB.INKODPOSCH BY INLASTAB.INLASTNR:
    PUT INKOD INKODTYP INKODPOSCH NAMN TABNAMN INKODID INLASTNR ORDNING SKIP.
END.
{EUROPEANAMERICAN.I}