/*CREMTRL.p*/

DEFINE TEMP-TABLE tidin
   FIELD TIN AS CHARACTER FORMAT "X(256)".

DEFINE INPUT PARAMETER decivar AS INTEGER NO-UNDO. 
DEFINE INPUT PARAMETER pos2 AS INTEGER NO-UNDO.

DEFINE INPUT PARAMETER leverant LIKE LEVERANTOR.LEVKOD NO-UNDO.
DEFINE INPUT PARAMETER e1 AS INTEGER NO-UNDO.
DEFINE INPUT PARAMETER e2 AS INTEGER NO-UNDO.
DEFINE INPUT PARAMETER b1 AS INTEGER NO-UNDO.
DEFINE INPUT PARAMETER b2 AS INTEGER NO-UNDO.
DEFINE INPUT PARAMETER en1 AS INTEGER NO-UNDO.
DEFINE INPUT PARAMETER en2 AS INTEGER NO-UNDO.
DEFINE INPUT PARAMETER bp1 AS INTEGER NO-UNDO.
DEFINE INPUT PARAMETER bp2 AS INTEGER NO-UNDO.
DEFINE INPUT PARAMETER np1 AS INTEGER NO-UNDO.
DEFINE INPUT PARAMETER np2 AS INTEGER NO-UNDO. 


DEFINE INPUT PARAMETER TABLE FOR tidin.

DEFINE VARIABLE raknare AS INTEGER NO-UNDO. 
FIND FIRST FORETAG NO-LOCK NO-ERROR.
FIND FIRST tidin NO-LOCK NO-ERROR.
IF AVAILABLE tidin THEN DO TRANSACTION:    
   raknare = 1.
   CREATE MTRL.  
   {MTRLCREATE.I} 
   ASSIGN 
   MTRL.LEVKOD = leverant
   MTRL.ENR = SUBSTRING(tidin.TIN,e1,
   (e2 - e1) + 1)
   MTRL.BENAMNING = SUBSTRING(tidin.TIN,b1,
   (b2 - b1) + 1)
   MTRL.ENHET = SUBSTRING(tidin.TIN,en1,
   (en2 - en1) + 1).                                                      
   /*Sundsvall tar med inledande "E" men tex UZ får då inledande blank*/ 
   IF SUBSTRING(MTRL.ENR,1,1) = " " THEN MTRL.ENR = SUBSTRING(MTRL.ENR,2).
   IF SUBSTRING(tidin.TIN,(pos2 - decivar),1) = "." THEN DO:
      IF np1 = 0 THEN DO: 
         MTRL.NPRIS = DECIMAL(SUBSTRING(tidin.TIN,bp1,
         (bp2 - bp1) + 1)).
      END.
      ELSE DO:          
         MTRL.NPRIS = DECIMAL(SUBSTRING(tidin.TIN,np1,
         (np2 - np1) + 1)).
      END.
      IF bp1 = 0 THEN DO:
         MTRL.BPRIS = DECIMAL(SUBSTRING(tidin.TIN,np1,
         (np2 - np1) + 1)).
      END.
      ELSE DO:      
         MTRL.BPRIS = DECIMAL(SUBSTRING(tidin.TIN,bp1,
         (bp2 - bp1) + 1)). 
      END.      
   END. 
   ELSE DO:  
      IF np1 = 0 THEN DO: 
         MTRL.NPRIS = DECIMAL(SUBSTRING(tidin.TIN,bp1,
         (bp2 - bp1) + 1)) / EXP(10,decivar).
      END.
      ELSE DO:          
          MTRL.NPRIS = DECIMAL(SUBSTRING(tidin.TIN,np1,
          (np2 - np1) + 1)) / EXP(10,decivar).
      END.
      IF bp1 = 0 THEN DO:
         MTRL.BPRIS = DECIMAL(SUBSTRING(tidin.TIN,np1,
         (np2 - np1) + 1)) / EXP(10,decivar).
      END.
      ELSE DO:      
         MTRL.BPRIS = DECIMAL(SUBSTRING(tidin.TIN,bp1,
         (bp2 - bp1) + 1)) / EXP(10,decivar). 
      END.
   END.
   IF FORETAG.FORETAG = "cVAST" THEN DO:
      /*Borttaget 20140110 lena*/
      MTRL.NPRIS = 0.99 * MTRL.NPRIS .
      MTRL.BPRIS = 0.99 * MTRL.BPRIS.
   END.                                 
   IF FORETAG.FORETAG = "VAST" THEN.    
   ELSE IF FORETAG.FORETAG = "GKAL" THEN.
   ELSE DO:                 
   /* Bara Vattenfall och Kalmar har priset i filen
   IF FORETAG.FORETAG = "CELPA"  OR FORETAG.FORETAG = "REJI" OR FORETAG.FORETAG = "ELPC" OR FORETAG.FORETAG = "LIMO" OR FORETAG.FORETAG = "ALTE" 
   OR FORETAG.FORETAG = "SWEO" OR FORETAG.FORETAG = "PICA" OR FORETAG.FORETAG = "SSEL" OR FORETAG.FORETAG = "GETB" OR FORETAG.FORETAG = "ELKB" 
   OR FORETAG.FORETAG = "RAMB" OR FORETAG.FORETAG = "SKEK" OR FORETAG.FORETAG = "YSEN" OR FORETAG.FORETAG = "LAKL" OR FORETAG.FORETAG = "MOLN"
   OR FORETAG.FORETAG = "TOSE" OR FORETAG.FORETAG = "KRIN" OR FORETAG.FORETAG = "elkb" OR FORETAG.FORETAG = "LAPP" OR FORETAG.FORETAG = "afco" OR FORETAG.FORETAG = "ATS"  
   OR FORETAG.FORETAG = "TECT" OR FORETAG.FORETAG = "SKOG" OR FORETAG.FORETAG = "WSP"  OR FORETAG.FORETAG = "ESKO" OR FORETAG.FORETAG = "MINI" OR FORETAG.FORETAG = "PENO"
   OR FORETAG.FORETAG = "GREL" OR FORETAG.FORETAG = "KEKR" OR FORETAG.FORETAG = "SKOK"  OR FORETAG.FORETAG = "kewa" OR FORETAG.FORETAG = "DUTA" OR FORETAG.FORETAG = "SKOL"
   OR FORETAG.FORETAG = "POWE" OR FORETAG.FORETAG = "OTER"  OR FORETAG.FORETAG = "WIGA" OR FORETAG.FORETAG = "TECM" OR FORETAG.FORETAG = "enka"
   OR FORETAG.FORETAG = "cgkal" OR FORETAG.FORETAG = "fors" OR FORETAG.FORETAG = "etsa" OR FORETAG.FORETAG = "PFBK" OR FORETAG.FORETAG = "rojo" OR FORETAG.FORETAG = "psnk"
   OR FORETAG.FORETAG = "SVEA" OR FORETAG.FORETAG = "PC2U"  THEN DO:*/      
      ASSIGN
      MTRL.NPRIS = 0
      MTRL.BPRIS = 0.
   END.
END.
DEBUGGER:SET-BREAK().
REPEAT: 
   FIND NEXT tidin NO-LOCK NO-ERROR.
   IF NOT AVAILABLE tidin THEN LEAVE.
   ELSE DO TRANSACTION:      
      raknare = raknare + 1.
      CREATE MTRL.  
      {MTRLCREATE.I} 
      ASSIGN 
      MTRL.LEVKOD = leverant
      MTRL.ENR = SUBSTRING(tidin.TIN,e1,
      (e2 - e1) + 1)
      MTRL.BENAMNING = SUBSTRING(tidin.TIN,b1,
      (b2 - b1) + 1)
      MTRL.ENHET = SUBSTRING(tidin.TIN,en1,
      (en2 - en1) + 1).                                                                         
      IF SUBSTRING(tidin.TIN,(pos2 - decivar),1) = "." THEN DO:
         IF np1 = 0 THEN DO: 
            MTRL.NPRIS = DECIMAL(SUBSTRING(tidin.TIN,bp1,
            (bp2 - bp1) + 1)).
         END.
         ELSE DO:          
            MTRL.NPRIS = DECIMAL(SUBSTRING(tidin.TIN,np1,
            (np2 - np1) + 1)).
         END.
         IF bp1 = 0 THEN DO:
            MTRL.BPRIS = DECIMAL(SUBSTRING(tidin.TIN,np1,
            (np2 - np1) + 1)).
         END.
         ELSE DO:      
            MTRL.BPRIS = DECIMAL(SUBSTRING(tidin.TIN,bp1,
            (bp2 - bp1) + 1)). 
         END.      
      END. 
      ELSE DO:  
         IF np1 = 0 THEN DO: 
            MTRL.NPRIS = DECIMAL(SUBSTRING(tidin.TIN,bp1,
            (bp2 - bp1) + 1)) / EXP(10,decivar).
         END.
         ELSE DO:          
            MTRL.NPRIS = DECIMAL(SUBSTRING(tidin.TIN,np1,
            (np2 - np1) + 1)) / EXP(10,decivar).
         END.
         IF bp1 = 0 THEN DO:
            MTRL.BPRIS = DECIMAL(SUBSTRING(tidin.TIN,np1,
            (np2 - np1) + 1)) / EXP(10,decivar).
         END.
         ELSE DO:      
            MTRL.BPRIS = DECIMAL(SUBSTRING(tidin.TIN,bp1,
            (bp2 - bp1) + 1)) / EXP(10,decivar). 
         END.
      END.
      IF FORETAG.FORETAG = "cVAST"  THEN DO:
         /*Borttaget 20140110 lena*/
         MTRL.NPRIS = 0.99 * MTRL.NPRIS .
         MTRL.BPRIS = 0.99 * MTRL.BPRIS.
      END.         
      IF FORETAG.FORETAG = "VAST" THEN.    
      ELSE IF FORETAG.FORETAG = "GKAL" THEN.
      ELSE DO:                 
      /* Bara Vattenfall och Kalmar har priset i filen                                          
      IF FORETAG.FORETAG = "CELPA" OR FORETAG.FORETAG = "REJI" OR FORETAG.FORETA = "ELPC"  OR FORETAG.FORETA = "LIMO" OR FORETAG.FORETAG = "ALTE"
      OR FORETAG.FORETAG = "SWEO" OR FORETAG.FORETAG = "PICA"  OR FORETAG.FORETAG = "SSEL" OR FORETAG.FORETAG = "GETB"  OR FORETAG.FORETAG = "ELKB" 
      OR FORETAG.FORETAG = "RAMB" OR FORETAG.FORETAG = "SKEK" OR FORETAG.FORETAG = "YSEN" OR FORETAG.FORETAG = "LAKL" OR FORETAG.FORETAG = "MOLN"
      OR FORETAG.FORETAG = "TOSE" OR FORETAG.FORETAG = "KRIN" OR FORETAG.FORETAG = "elkb" OR FORETAG.FORETAG = "LAPP"  OR FORETAG.FORETAG = "afco" OR FORETAG.FORETAG = "ATS"
      OR FORETAG.FORETAG = "TECT" OR FORETAG.FORETAG = "SKOG" OR FORETAG.FORETAG = "WSP"  OR FORETAG.FORETAG = "ESKO" OR FORETAG.FORETAG = "MINI" OR FORETAG.FORETAG = "PENO"
      OR FORETAG.FORETAG = "GREL" OR FORETAG.FORETAG = "KEKR"  OR FORETAG.FORETAG = "SKOK" OR FORETAG.FORETAG = "kewa" OR FORETAG.FORETAG = "SKOL"
      OR FORETAG.FORETAG = "POWE" OR FORETAG.FORETAG = "OTER"  OR FORETAG.FORETAG = "WIGA"  OR FORETAG.FORETAG = "TECM" OR FORETAG.FORETAG = "enka"
      OR FORETAG.FORETAG = "cgkal" OR FORETAG.FORETAG = "fors" OR FORETAG.FORETAG = "etsa" OR FORETAG.FORETAG = "PFBK" OR FORETAG.FORETAG = "rojo" OR FORETAG.FORETAG = "psnk"
      OR FORETAG.FORETAG = "SVEA" OR FORETAG.FORETAG = "PC2U" THEN DO:*/         
         ASSIGN
         MTRL.NPRIS = 0
         MTRL.BPRIS = 0.
      END.
   END. 
END.
RELEASE MTRL NO-ERROR.
IF FORETAG.FORETAG = "VAST"  THEN DO:         
   FOR EACH MTRL WHERE MTRL.LEVKOD = leverant AND MTRL.NPRIS = 0 AND KALKNR = 0 EXCLUSIVE-LOCK:
      DELETE MTRL.
   END.  
END.
