/*TAR BORT SATSREGISTER FÖR LEVERANTÖR*/

DEFINE INPUT PARAMETER globforetag LIKE FORETAG.FORETAG NO-UNDO.   
DEFINE INPUT PARAMETER leverant LIKE LEVERANTOR.LEVKOD NO-UNDO.

   {muswait.i}
   OPEN QUERY mtrlq FOR EACH SATS WHERE  
   SATS.LEVKOD = leverant NO-LOCK.
   DO TRANSACTION:
      GET FIRST mtrlq EXCLUSIVE-LOCK.
      IF AVAILABLE SATS THEN DO:
         DELETE SATS.         
      END.  
   END.
   REPEAT:
      DO TRANSACTION:
         GET NEXT mtrlq EXCLUSIVE-LOCK.
         IF AVAILABLE SATS THEN DO:
            DELETE SATS.
         END.
         ELSE LEAVE.
      END.
   END.   
   CLOSE QUERY mtrlq.   
