/*ENRELEFB3.p*/
DEFINE VARIABLE kalle AS LOGICAL NO-UNDO. 
DEFINE INPUT PARAMETER leverant LIKE LEVERANTOR.LEVKOD NO-UNDO.
  
   OPEN QUERY kq FOR EACH BERMTRL WHERE BERMTRL.LEVKOD = leverant
   NO-LOCK.
   DO TRANSACTION:
      GET FIRST kq EXCLUSIVE-LOCK.
      IF SUBSTRING(BERMTRL.ENR,1,1) = "E" THEN BERMTRL.ENR = SUBSTRING(BERMTRL.ENR,2).      
   END.
   REPEAT:
      DO TRANSACTION:
         GET NEXT kq EXCLUSIVE-LOCK.
         IF NOT AVAILABLE BERMTRL THEN LEAVE.
         ELSE DO:
            IF SUBSTRING(BERMTRL.ENR,1,1) = "E" THEN BERMTRL.ENR = SUBSTRING(BERMTRL.ENR,2).            
         END.
      END.
   END.

   