/*UPPDATERING AV MTRLPRISER UNDER NATTKÖRNING FÖR KALMAR*/
DEFINE VARIABLE musz AS LOGICAL NO-UNDO.
OPEN QUERY levq FOR EACH LEVERANTOR WHERE LEVERANTOR.BORTTAG = FALSE NO-LOCK.
GET FIRST levq NO-LOCK.
DO  WHILE AVAILABLE(LEVERANTOR):
   IF LEVERANTOR.LEVKOD = "0" OR LEVERANTOR.LEVKOD = "99" THEN DO:
      musz = musz.
   END.
   ELSE DO:
      /*Uppdatera priser i gjorda bered. för vald lev.*/
      RUN PRISUBER.P (INPUT LEVERANTOR.LEVKOD).      
      /*Uppdatera priser i adm.bered. för vald lev.*/
      RUN PRISUPP.P (INPUT LEVERANTOR.LEVKOD).
   END.
   GET NEXT levq NO-LOCK.
END.
