/*LADDEGENK.p TAR BORT FASTANM EGENK OCH LADDAR NYA FRÅN .D FIL*/
FIND FIRST FORETAG  WHERE NO-LOCK NO-ERROR.      

   

{AMERICANEUROPEAN.I}
   {muswait.i}
   /*OPEN QUERY egenq FOR EACH FASTANM WHERE FASTANM.PROGRAM BEGINS "EGENK" NO-LOCK.
   DO TRANSACTION:
      GET FIRST egenq EXCLUSIVE-LOCK.
      IF AVAILABLE FASTANM THEN DO:
         DELETE FASTANM.
         GET NEXT egenq EXCLUSIVE-LOCK.
      END.
   END.
   DO WHILE AVAILABLE(FASTANM):
      DO TRANSACTION:
         DELETE FASTANM.
         GET NEXT egenq EXCLUSIVE-LOCK.
      END.
   END.
   CLOSE QUERY egenq.*/
   IF FORETAG.FORETAG = "KRIN"   THEN DO:
      INPUT FROM C:\delad\KRIN\fastanm.d convert target "iso8859-1" source "iso8859-1".       
   END. 
      
   REPEAT: 
      CREATE FASTANM.  
      ASSIGN.     
      IMPORT FASTANM.         
   END.
   INPUT CLOSE.
   
   {EUROPEANAMERICAN.I}
