/*
rbprompt.p   

Running Report Engine from an application - PRINTRB INTERFACE.

Running multiple reports and prompting for user input.   
*/
	DEF VAR RB-REPORT-NAME AS CHARACTER INITIAL "".
	DEF VAR RB-DB-CONNECTION AS CHARACTER INITIAL "".
	DEF VAR RB-INCLUDE-RECORDS AS CHARACTER INITIAL "".
	DEF VAR RB-FILTER AS CHARACTER INITIAL "".
	DEF VAR RB-MEMO-FILE AS CHARACTER INITIAL "".
	DEF VAR RB-PRINT-DESTINATION AS CHARACTER INITIAL "".
	DEF VAR RB-PRINTER-NAME AS CHARACTER INITIAL "".
	DEF VAR RB-PRINTER-PORT AS CHARACTER INITIAL "".
	DEF VAR RB-OUTPUT-FILE AS CHARACTER INITIAL "".
	DEF VAR RB-NUMBER-COPIES AS INTEGER INITIAL 1.
	DEF VAR RB-BEGIN-PAGE AS INTEGER INITIAL 0.
	DEF VAR RB-END-PAGE AS INTEGER INITIAL 0.
	DEF VAR RB-TEST-PATTERN AS LOGICAL INITIAL no.
	DEF VAR RB-WINDOW-TITLE AS CHARACTER INITIAL "".
	DEF VAR RB-DISPLAY-ERRORS AS LOGICAL INITIAL yes.
	DEF VAR RB-DISPLAY-STATUS AS LOGICAL INITIAL yes.
	DEF VAR RB-NO-WAIT AS LOGICAL INITIAL no.
	DEF VAR RB-OTHER-PARAMETERS AS CHARACTER INITIAL "".

	DEF VAR report-list AS CHARACTER.
	DEF VAR report-count AS INTEGER.
	DEF VAR report-number AS INTEGER.

	DEF INPUT PARAMETER report-library AS CHARACTER.

	DEF VAR user-answer AS LOGICAL.

	RUN aderb/_getname.p (report-library, OUTPUT report-list, 
				OUTPUT report-count).

	DO report-number = 1 to report-count:

		RB-REPORT-NAME = ENTRY (report-number, report-list).

		MESSAGE "Report Number " + string (report-number) + " is " 
				+ RB-REPORT-NAME + ". Do you want to print it?"
				VIEW-AS ALERT-BOX QUESTION BUTTONS yes-no 
				UPDATE user-answer.

		IF (user-answer) THEN

			RUN aderb/_printrb.p (report-library,
				RB-REPORT-NAME,
				RB-DB-CONNECTION,
				RB-INCLUDE-RECORDS,
				RB-FILTER,
				RB-MEMO-FILE,
				RB-PRINT-DESTINATION,
				RB-PRINTER-NAME,
				RB-PRINTER-PORT,
				RB-OUTPUT-FILE,
				RB-NUMBER-COPIES,
				RB-BEGIN-PAGE,
				RB-END-PAGE,
				RB-TEST-PATTERN,
				RB-WINDOW-TITLE,
				RB-DISPLAY-ERRORS,
				RB-DISPLAY-STATUS,
				RB-NO-WAIT,
				RB-OTHER-PARAMETERS).

	END.

