/*BORTEXTK.P KOLLAR SÅ ATT DET ÄR OK ATT TA BORT EN KUND*/

DEFINE INPUT PARAMETER kundnrvar AS INTEGER NO-UNDO.
DEFINE OUTPUT PARAMETER okvar AS LOGICAL NO-UNDO.

   FIND FIRST KALKKUND WHERE 
   KALKKUND.K1 = kundnrvar OR 
   KALKKUND.K2 = kundnrvar OR KALKKUND.K3 = kundnrvar OR
   KALKKUND.K4 = kundnrvar OR KALKKUND.K5 = kundnrvar NO-LOCK NO-ERROR.   
   IF AVAILABLE KALKKUND THEN okvar = FALSE.   
   ELSE okvar = TRUE.
