/*PERBEFPRIS2.P*/
/*HÄMTAR PRISLISTOR*/
&Scoped-define NEW NEW
&Scoped-define SHARED SHARED
{PERBEF.I}

DEFINE INPUT PARAMETER pkod AS CHARACTER NO-UNDO.
DEFINE INPUT PARAMETER hmtdatum AS DATE NO-UNDO.
DEFINE OUTPUT PARAMETER TABLE FOR perspristemp.
DEFINE OUTPUT PARAMETER TABLE FOR befvaltemp.
IF MONTH(hmtdatum) = 12 THEN DO:
   hmtdatum = DATE(12,31,YEAR(hmtdatum)).
END.
ELSE DO:   
   hmtdatum = DATE((MONTH(hmtdatum) + 1),01,YEAR(hmtdatum)) - 1.
END.
IF pkod = "" THEN DO:
   OPEN QUERY bq FOR EACH BEFATTNINGSTAB NO-LOCK.
   GET FIRST bq NO-LOCK.
   DO WHILE AVAILABLE(BEFATTNINGSTAB):  
      FIND FIRST befvaltemp WHERE befvaltemp.BEFATTNING = BEFATTNINGSTAB.BEFATTNING NO-ERROR.
      IF NOT AVAILABLE befvaltemp THEN DO:
         CREATE befvaltemp.
         ASSIGN
         befvaltemp.BEFATTNING  = BEFATTNINGSTAB.BEFATTNING  
         befvaltemp.VIBEFATTNING = BEFATTNINGSTAB.NAMN.
      END.
      GET NEXT bq NO-LOCK.
   END.
   RETURN.
END.
OPEN QUERY pq FOR EACH PERSONALPRIS WHERE PERSONALPRIS.PERSONALKOD = pkod AND 
YEAR(PERSONALPRIS.SLUTDATUM) = YEAR(hmtdatum) AND 
MONTH(PERSONALPRIS.SLUTDATUM) = MONTH(hmtdatum)
NO-LOCK.
GET FIRST pq NO-LOCK.
FIND FIRST PERSONALTAB WHERE PERSONALTAB.PERSONALKOD = pkod NO-LOCK NO-ERROR.
FIND FIRST BEFATTNINGSTAB WHERE BEFATTNINGSTAB.BEFATTNING = PERSONALTAB.BEFATTNING NO-LOCK NO-ERROR.
DO WHILE AVAILABLE(PERSONALPRIS):  
   FIND FIRST PERSONALTAB WHERE PERSONALTAB.PERSONALKOD = PERSONALPRIS.PERSONALKOD NO-LOCK NO-ERROR.
   CREATE perspristemp.
   IF AVAILABLE PERSONALTAB THEN BUFFER-COPY PERSONALTAB TO perspristemp.
   BUFFER-COPY PERSONALPRIS TO perspristemp.
   IF perspristemp.BEFATTNING = "RESTID..." OR perspristemp.BEFATTNING = "FRÅNVARO." THEN DO:
      perspristemp.VIBEFATTNING = perspristemp.BEFATTNING.
   END.
   ASSIGN 
   perspristemp.PBEFATTNING = BEFATTNINGSTAB.NAMN.
   GET NEXT pq NO-LOCK.
END.
OPEN QUERY pq FOR EACH PERSONALPRIS WHERE PERSONALPRIS.PERSONALKOD = pkod AND 
PERSONALPRIS.STARTDATUM <= hmtdatum AND PERSONALPRIS.SLUTDATUM >= hmtdatum
NO-LOCK.
GET FIRST pq NO-LOCK.
FIND FIRST PERSONALTAB WHERE PERSONALTAB.PERSONALKOD = pkod NO-LOCK NO-ERROR.
FIND FIRST BEFATTNINGSTAB WHERE BEFATTNINGSTAB.BEFATTNING = PERSONALTAB.BEFATTNING NO-LOCK NO-ERROR.
DO WHILE AVAILABLE(PERSONALPRIS):  
   CREATE perspristemp.
   BUFFER-COPY PERSONALPRIS TO perspristemp. 
   IF perspristemp.SLUTDATUM = ? THEN perspristemp.SLUTDATUM = hmtdatum.
   IF perspristemp.BEFATTNING = "RESTID..." OR perspristemp.BEFATTNING = "FRÅNVARO." THEN DO:
      perspristemp.VIBEFATTNING = perspristemp.BEFATTNING.
   END.  
   ASSIGN 
   perspristemp.PBEFATTNING = BEFATTNINGSTAB.NAMN.
   GET NEXT pq NO-LOCK.
END.

OPEN QUERY bpq FOR EACH BEFATTNINGSTAB NO-LOCK, 
EACH perspristemp WHERE perspristemp.BEFATTNING = BEFATTNINGSTAB.BEFATTNING. 
GET FIRST bpq NO-LOCK.
DO WHILE AVAILABLE(BEFATTNINGSTAB):  
   perspristemp.VIBEFATTNING = BEFATTNINGSTAB.NAMN.    
   IF perspristemp.BEFATTNING = "RESTID..." OR perspristemp.BEFATTNING = "FRÅNVARO." THEN DO:
   END.
   ELSE DO:
      FIND FIRST befvaltemp WHERE befvaltemp.BEFATTNING = BEFATTNINGSTAB.BEFATTNING NO-ERROR.
      IF NOT AVAILABLE befvaltemp THEN DO:
         CREATE befvaltemp.
         ASSIGN
         befvaltemp.BEFATTNING  = BEFATTNINGSTAB.BEFATTNING  
         befvaltemp.VIBEFATTNING = BEFATTNINGSTAB.NAMN.
      END.
   END.
   GET NEXT bpq NO-LOCK.
END.
FIND FIRST befvaltemp NO-ERROR.
IF NOT AVAILABLE befvaltemp THEN DO:
   OPEN QUERY bq FOR EACH BEFATTNINGSTAB NO-LOCK.
   GET FIRST bq NO-LOCK.
   DO WHILE AVAILABLE(BEFATTNINGSTAB):  
      FIND FIRST befvaltemp WHERE befvaltemp.BEFATTNING = BEFATTNINGSTAB.BEFATTNING NO-ERROR.
      IF NOT AVAILABLE befvaltemp THEN DO:
         CREATE befvaltemp.
         ASSIGN
         befvaltemp.BEFATTNING  = BEFATTNINGSTAB.BEFATTNING  
         befvaltemp.VIBEFATTNING = BEFATTNINGSTAB.NAMN.
      END.
      GET NEXT bq NO-LOCK.
   END.
END.
