/*PHMTAEN.P*/
&Scoped-define NEW NEW
&Scoped-define SHARED SHARED
/*{PHMT.I}*/
{VPERSONALTEMP.I}

DEFINE INPUT PARAMETER vem AS CHARACTER NO-UNDO.
DEFINE OUTPUT PARAMETER TABLE FOR valperstemp.
EMPTY TEMP-TABLE valperstemp NO-ERROR. 
FIND FIRST PERSONALTAB WHERE PERSONALTAB.PERSONALKOD = vem
NO-LOCK NO-ERROR.
IF AVAILABLE PERSONALTAB THEN DO:
   FIND FIRST valperstemp WHERE valperstemp.PERSONALKOD = vem NO-ERROR.
   IF NOT AVAILABLE valperstemp THEN CREATE valperstemp.
   BUFFER-COPY PERSONALTAB TO valperstemp.
   valperstemp.PERSRECID = RECID(PERSONALTAB).
   Guru.GlobalaVariabler:GDPRvem = Guru.GlobalaVariabler:GDPRvem + "," + PERSONALTAB.PERSONALKOD.
   {GDPRLOGGCLIENT.I}
END.
