/*PRISDEB.P*/
DEFINE VARIABLE timraknare AS INTEGER NO-UNDO.
DEFINE VARIABLE dpkod AS CHARACTER NO-UNDO.
{DEBPRIUT.I}
DEFINE INPUT PARAMETER visstart AS INTEGER.
DEFINE INPUT PARAMETER visslut AS INTEGER.
IF forsta = TRUE THEN DO:
   OPEN QUERY persq FOR EACH PERSONALTAB USE-INDEX PERSONALKOD NO-LOCK.
   GET FIRST persq NO-LOCK.
   DO WHILE AVAILABLE(PERSONALTAB):
      CREATE debpris.
      ASSIGN 
      debpris.PERSONALKOD = PERSONALTAB.PERSONALKOD 
      debpris.FORNAMN = PERSONALTAB.FORNAMN
      debpris.EFTERNAMN = PERSONALTAB.EFTERNAMN
      debpris.BEFATTNING = PERSONALTAB.BEFATTNING
      debpris.OMRADE = PERSONALTAB.OMRADE.  
      Guru.GlobalaVariabler:GDPRvem = Guru.GlobalaVariabler:GDPRvem + "," + PERSONALTAB.PERSONALKOD.
                  
      GET NEXT persq NO-LOCK.        
   END.   
END.   
{GDPRLOGGCLIENT.I}
RELEASE debpris.
FOR EACH debpris USE-INDEX PERSONALKOD:
   timraknare = 1.    
   OPEN QUERY tq FOR EACH TIMKOSTNADSTAB WHERE 
   TIMKOSTNADSTAB.PERSONALKOD = debpris.PERSONALKOD
   USE-INDEX PRISPERS NO-LOCK.
   GET FIRST tq NO-LOCK.  
   REPEAT:
      IF NOT AVAILABLE TIMKOSTNADSTAB THEN LEAVE.   
      ASSIGN debpris.TIMPRISREC = RECID(TIMKOSTNADSTAB).
      IF timraknare = 1 THEN
      ASSIGN debpris.PRISA = TIMKOSTNADSTAB.PRISA. 
      IF timraknare = 2 THEN
      ASSIGN debpris.PRISA-2 = TIMKOSTNADSTAB.PRISA.
      IF timraknare = 3 THEN
      ASSIGN debpris.PRISA-3 = TIMKOSTNADSTAB.PRISA.
      IF timraknare = 4 THEN
      ASSIGN debpris.PRISA-4 = TIMKOSTNADSTAB.PRISA.
      IF timraknare = 4 THEN LEAVE.
      timraknare = timraknare + 1.    
      GET NEXT tq NO-LOCK.   
   END.
END.
