/* r-acmlt.p */

FOR EACH customer:
    ACCUMULATE credit-limit (AVERAGE COUNT MAXIMUM).
END.
DISPLAY "MAX-CREDIT STATISTICS FOR ALL CUSTOMERS:" SKIP(2)
	"AVERAGE =" (ACCUM AVERAGE credit-limit) SKIP(1)
	"MAXIMUM =" (ACCUM MAXIMUM credit-limit) SKIP(1)
	"NUMBER OF CUSTOMERS =" (ACCUM COUNT credit-limit) SKIP(1)
	WITH NO-LABELS.
