/* r-chs1.p */

DEFINE VARIABLE abc AS CHARACTER FORMAT "x(3)" EXTENT 42.
DEFINE VARIABLE i AS INTEGER.

DO i = 1 TO 42:
    abc[i] = STRING(i,">9").
END.

DISPLAY abc NO-LABELS WITH ATTR-SPACE CENTERED ROW 4
	TITLE "CHOOSE STATEMENT" FRAME f-choose WIDTH 36.
DISPLAY "Enter your selection " WITH CENTERED NO-BOX FRAME f-instruct.
PAUSE 1 BEFORE-HIDE NO-MESSAGE.

REPEAT:
    HIDE MESSAGE.
    CHOOSE FIELD abc AUTO-RETURN WITH FRAME f-choose.
    MESSAGE "You selected -> " FRAME-VALUE.
END.
