DEFINE VARIABLE red AS INTEGER INIT 0.
DEFINE VARIABLE blue AS INTEGER INIT 127.
DEFINE VARIABLE green AS INTEGER INIT 127.
DEFINE VARIABLE i AS INTEGER.

i = COLOR-TABLE:NUM-ENTRIES.
COLOR-TABLE:NUM-ENTRIES = i + 1.
COLOR-TABLE:SET-DYNAMIC(i, yes).
COLOR-TABLE:SET-RED-VALUE(i, red).
COLOR-TABLE:SET-GREEN-VALUE(i, green).
COLOR-TABLE:SET-BLUE-VALUE(i, blue).

DISPLAY COLOR-TABLE:GET-RED-VALUE(i).
DISPLAY COLOR-TABLE:GET-GREEN-VALUE(i).
DISPLAY COLOR-TABLE:GET-BLUE-VALUE(i ).



