DEFINE VARIABLE cnum AS CHARACTER FORMAT "x(3)".
DEFINE VARIABLE cdate AS CHARACTER FORMAT "x(16)".
DEFINE VARIABLE ddate AS DATE FORMAT "99/99/9999".

INPUT FROM VALUE(SEARCH("r-date.dat")).

REPEAT:
   SET cnum cdate.
   ddate = DATE(cdate).
   DISPLAY ddate.
END.

INPUT CLOSE.
