/* r-defrec.p */

DEFINE RECTANGLE rec SIZE 40 BY 8 EDGE-PIXELS 8.

DEFINE VARIABLE msg AS CHARACTER FORMAT "X(19)"
   INIT "W E L C O M E   T O " VIEW-AS TEXT.

DEFINE IMAGE pro FILE "pro".

DEFINE FRAME x
  rec
  msg NO-LABEL AT ROW 2 COLUMN 11
  pro AT ROW 4 COLUMN 16 
WITH ROW 7 CENTERED.


DISPLAY rec msg pro WITH FRAME x.
