/* r-fntdlg.p */

DEFINE VARIABLE Font1	   AS INTEGER INITIAL 1.
DEFINE VARIABLE Font2	   AS INTEGER INITIAL 2.
DEFINE VARIABLE FontSelect AS INTEGER INITIAL 1
    VIEW-AS RADIO-SET RADIO-BUTTONS
	"Font 1", 1,
	"Font 2", 2 
	FONT Font1
	.
DEFINE BUTTON bOK     LABEL "OK" FONT Font2.
DEFINE BUTTON bCANCEL LABEL "CANCEL" FONT Font2.

FORM
    SKIP(0.5) SPACE(0.5)
    FontSelect SPACE(2) bOK SPACE(2) bCANCEL
    SPACE(0.5) SKIP(0.5)
WITH FRAME fFont
    TITLE "Choose frame fonts ..." 
    VIEW-AS DIALOG-BOX
    .

ON CHOOSE OF bOK
DO:
    IF INTEGER(FontSelect:SCREEN-VALUE) = Font1 THEN
	SYSTEM-DIALOG FONT Font1.
    ELSE
	SYSTEM-DIALOG FONT Font2.
END.

ON CHOOSE OF bCANCEL QUIT.

ENABLE FontSelect bOK bCANCEL WITH FRAME fFont.
WAIT-FOR CHOOSE OF bCANCEL.




