DEFINE VARIABLE text-string AS CHARACTER FORMAT "x(76)".

INPUT FROM VALUE(SEARCH("hello")).
DO WHILE TRUE:
   IMPORT UNFORMATTED text-string.
   DISPLAY text-string WITH DOWN FRAME x.
   DOWN WITH FRAME x.
END.

INPUT CLOSE.
