
DEFINE VARIABLE drives AS CHARACTER
   LABEL "Select a Drive"
   VIEW-AS SELECTION-LIST INNER-CHARS 3 INNER-LINES 5.
DEFINE FRAME f
   drives.

drives:LIST-ITEMS = OS-DRIVES.
UPDATE drives WITH FRAME f.
MESSAGE "Files will be written to drive" INPUT drives:SCREEN-VALUE.
