
DEFINE VAR choice AS INTEGER LABEL "You selected".
DEFINE VAR a AS INTEGER.
UPDATE a VIEW-AS SLIDER
	MAX-VALUE 100 MIN-VALUE 1 SIZE-CHAR 33 BY 3 
	TIC-MARKS BOTTOM FREQUENCY 10
	LABEL "Slide to select an integer. Then press GO."
	WITH FRAME f THREE-D.
choice = a.
DISPLAY choice WITH FRAME b SIDE-LABELS THREE-D.
PAUSE.



