/* r-sub.p */

DEFINE VARIABLE rtext AS CHARACTER FORMAT "x(50)" .
DEFINE VARIABLE orig AS CHARACTER FORMAT "x(31)".
DEFINE VARIABLE strt AS INTEGER FORMAT ">9".
DEFINE VARIABLE leng AS INTEGER FORMAT ">9".

orig = "Now is the time to use PROGRESS".
DISPLAY orig WITH CENTERED TITLE "Original Text" NO-LABEL.
REPEAT:
   rtext = orig.
   UPDATE strt LABEL "START" leng LABEL "LENGTH".
   SUBSTRING(rtext,strt,leng,"CHARACTER") = "XXXXXXXXX".
   DISPLAY rtext LABEL "WORD" WITH CENTERED.
END.
