/* r-widhnd.p */

DEFINE VARIABLE whand AS WIDGET-HANDLE.
DEFINE VARIABLE chand AS CHARACTER.

CREATE FRAME whand.
chand = STRING(whand).
DELETE WIDGET whand.
whand = WIDGET-HANDLE(chand).
MESSAGE VALID-HANDLE(whand) VIEW-AS ALERT-BOX
 INFORMATION BUTTONS OK.
